## 1. 필요 라이브러리 호출

In [1]:
# 환경설정
import os
import sys
import time
from tqdm import tqdm
import nest_asyncio
nest_asyncio.apply()
from dotenv import load_dotenv

load_dotenv()
# duckdb
import duckdb

# 데이터 전처리
import re
import pandas as pd
import numpy as np
import polars as pl
from datetime import datetime, timedelta
from copy import deepcopy

# 데이터 수집
import requests
from bs4 import BeautifulSoup


# VectorDB 저장
from hashlib import md5
from langchain_community.vectorstores.utils import filter_complex_metadata # ChromaDB가 제공하지 못하는 데이터 형태를 자동으로 string처리
from datetime import datetime, timezone

## LLM 활용
from summary_function import NewsSummaryAgent
# LLM 활용을 위한 dict형태 구축
from collections import defaultdict

# langchain 계열
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

from langchain_openai import ChatOpenAI

# 1. LLM 모델 세팅 (OpenAI)
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
#from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)

# ㄱRe-ranker 모델 활용
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

## 2. ETF 목록 가져오기

In [2]:
ETF_conn = duckdb.connect('../DB/ETF.db')

In [3]:
ETF_df = ETF_conn.execute('select * from IRP_ETF_COMPOSE_table').fetchdf()
ETF_conn.close()

In [4]:
ETF_df = ETF_df.map(lambda x : x.strip())

In [5]:
ETF_df_task_1 = ETF_df[ETF_df['구성종목 종목명'] != "설정현금액"]
ETF_df_task_1 = ETF_df_task_1[ETF_df_task_1['구성종목 종목명'] != "원화현금"]
ETF_df_task_1 = ETF_df_task_1[1:]

In [6]:
# 원하는 컬럼 필터링
ETF_df_task_2 = ETF_df_task_1[['ETF 종목명','구성종목 표준코드','구성종목 종목명','편입비율']]

In [7]:
# 구성종목 중 상위 5개 추출
ETF_df_task_3 = ETF_df_task_2.sort_values(by=['ETF 종목명','편입비율'], ascending=False)

In [8]:
# 종목별 상위 5개
ETF_df_task_4= ETF_df_task_3.groupby('ETF 종목명').head(5)

In [9]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('반도체')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('전지')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('자율주행')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('금융')]

,ETF 종목명,구성종목 표준코드,구성종목 종목명,편입비율
34483,TIGER 25-12 금융채(AA-이상),KR6205498EC7,하나카드273,4.988738
34398,TIGER 25-12 금융채(AA-이상),KR6005273F23,아이엠뱅크46-02이12A-21,4.10297
34473,TIGER 25-12 금융채(AA-이상),KR6140178EB5,케이비국민카드421-1,3.300191
34461,TIGER 25-12 금융채(AA-이상),KR6079314EA3,JB 우리캐피탈524-1(지),2.485386
34475,TIGER 25-12 금융채(AA-이상),KR6145763DC9,BNK캐피탈338-3,2.48222
7606,TIGER 200 금융,KR7316140003,우리금융지주,7.825771
7587,TIGER 200 금융,KR7000810002,삼성화재,7.048532
7595,TIGER 200 금융,KR7032830002,삼성생명,5.727802
7607,TIGER 200 금융,KR7323410001,카카오뱅크,5.180046
7602,TIGER 200 금융,KR7138040001,메리츠금융지주,4.741424
63268,SOL 금융지주플러스고배당,KR7005940002,NH투자증권,5.574874
63270,SOL 금융지주플러스고배당,KR7071050009,한국금융지주,5.456068
63273,SOL 금융지주플러스고배당,KR7138040001,메리츠금융지주,4.724787
63274,SOL 금융지주플러스고배당,KR7138930003,BNK금융지주,3.423077
63276,SOL 금융지주플러스고배당,KR7175330000,JB금융지주,3.214653
36119,RISE 코리아금융고배당,KR7001720002,신영증권,9.789689
36130,RISE 코리아금융고배당,KR7316140003,우리금융지주,9.566045
36127,RISE 코리아금융고배당,KR7105560007,KB금융,9.41425
36123,RISE 코리아금융고배당,KR7024110009,기업은행,9.18122
36118,RISE 코리아금융고배당,KR7000810002,삼성화재,9.125524
29586,RISE 금융채액티브,KR6174147F13,우리카드259-3,6.792848
29582,RISE 금융채액티브,KR6032711EC2,신한카드2244-1,6.775031
29584,RISE 금융채액티브,KR6079315F44,JB 우리캐피탈533-5,6.765295
29580,RISE 금융채액티브,KR6008276F57,산은캐피탈767-3,6.720173
29583,RISE 금융채액티브,KR6033662E66,우리금융캐피탈503-2,5.751116
21311,RISE 200금융,KR7316140003,우리금융지주,7.848761
21292,RISE 200금융,KR7000810002,삼성화재,7.198696
21300,RISE 200금융,KR7032830002,삼성생명,5.759096
21312,RISE 200금융,KR7323410001,카카오뱅크,5.192032
21307,RISE 200금융,KR7138040001,메리츠금융지주,4.756095
3075,KODEX 미국금융테크액티브,CA82509L1076,SHOPIFY-A,9.846667
3080,KODEX 미국금융테크액티브,US0640581007,BANK OF NEW YORK MELLON CORP,9.411734
3078,KODEX 미국금융테크액티브,KYG6683N1034,NU Holdings Ltd/Cayman Islands,9.396511
3092,KODEX 미국금융테크액티브,US92826C8394,VISA INC-CLASS A SHARES,9.096284
3082,KODEX 미국금융테크액티브,US09290D1019,BLACKROCK INC,8.979381
56492,KODEX 미국S&P500금융,US46625H1005,JPMORGAN CHASE & CO,9.654794
56522,KODEX 미국S&P500금융,US92826C8394,VISA INC-CLASS A SHARES,7.900418
56500,KODEX 미국S&P500금융,US57636Q1040,MASTERCARD INC-CLASS A,5.941876
56516,KODEX 미국S&P500금융,US81369Y6059,FINANCIAL SELECT SECTOR SPDR,5.793727
56463,KODEX 미국S&P500금융,US0605051046,BANK OF AMERICA CORP,3.751882
36060,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005830005,DB손해보험,5.910951
36061,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005940002,NH투자증권,5.140565
36062,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7016360000,삼성증권,4.771763
36066,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7071050009,한국금융지주,3.505522
36064,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7039490008,키움증권,3.154331
58932,1Q 단기금융채액티브,KR6019453E35,아이비케이캐피탈301-3,4.057166
58937,1Q 단기금융채액티브,KR6095926E42,현대커머셜514-1,4.042198
58934,1Q 단기금융채액티브,KR6079316E69,JB 우리캐피탈513-2,4.041418
58938,1Q 단기금융채액티브,KR6131791DA0,연합자산관리34-1,4.039457
58939,1Q 단기금융채액티브,KR6145761DB5,BNK캐피탈333-1,4.025209

## 3. 고객 데이터 시나리오
 - 고객 데이터 생성

In [10]:
Customer_A = ETF_df_task_4[ETF_df_task_4['ETF 종목명'].isin(['ACE AI반도체포커스','ACE 2차전지&친환경차액티브','KODEX 자율주행액티브','RISE 200금융'])]

In [11]:
Customer_A = Customer_A.reset_index().drop('index',axis = 1)

In [12]:
Custer_Having_ticker_lst = list(Customer_A['구성종목 종목명'].unique())

In [13]:
Custer_Having_ticker_lst

['우리금융지주',
 '삼성화재',
 '삼성생명',
 '카카오뱅크',
 '메리츠금융지주',
 '현대모비스',
 '현대오토에버',
 'SK하이닉스',
 '현대글로비스',
 '현대차',
 '삼성전자',
 '한미반도체',
 '파크시스템스',
 'DB하이텍',
 '기아',
 'POSCO홀딩스',
 'LG에너지솔루션']

## 4. 고객 데이터 저장

In [14]:
con = duckdb.connect('../DB/Customer.db')

# Pandas DataFrame을 DuckDB에서 참조할 수 있도록 등록
con.register('temp_df', Customer_A)

# 테이블이 없다면 생성
con.execute("""
    CREATE TABLE IF NOT EXISTS Customers AS
    SELECT * FROM temp_df LIMIT 0
""")

# 데이터 삽입
con.execute("INSERT INTO Customers SELECT * FROM temp_df")

# 정리
con.unregister('temp_df')
con.close()

## 5. 고객이 보유하고 있는 데이터를 DB에 저장하기

In [77]:
import asyncio
import aiohttp
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin,urlparse
import duckdb

# ▶ 헤더
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
}

# ▶ 기사 리스트 파싱 함수
async def get_article_urls(session, page_url):
    try:
        async with session.get(page_url, headers=headers) as resp:
            text = await resp.text()
            soup = BeautifulSoup(text, 'html.parser')
            ul = soup.select_one('#content > div.left_cont > div > div.section.hk_news > div.section_cont > ul')
            if not ul:
                return []

            urls = []
            for a in ul.find_all('a', href=True):
                href = a['href']
                if '/article/' in href:
                    urls.append(href)
            return list(set(urls))  # 중복 제거
    except Exception as e:
        print(f"[get_article_urls error] {page_url} - {e}")
        return []

# ▶ 기사 상세 파싱 함수
async def fetch_article(session, url):
    try:
        async with session.get(url, headers=headers) as resp:
            html = await resp.text()
            soup = BeautifulSoup(html, 'html.parser')

            hostname = urlparse(url).hostname

            # ✅ 1. magazine.hankyung.com용 로직
            if 'magazine.hankyung.com' in hostname:
                return {
                    'header': soup.select_one('#contents h1.news-tit').text.strip() if soup.select_one('#contents h1.news-tit') else None,
                    'summary': None,
                    'content': soup.select_one('#magazineView').text.strip() if soup.select_one('#magazineView') else None,
                    'url': url,
                    'datetime': soup.select_one('#contents span.txt-num').text.strip() if soup.select_one('#contents span.txt-num') else None,
                }

            # ✅ 2. www.hankyung.com일 경우 기존 로직
            elif 'hankyung.com' in hostname:
                return {
                    'header': soup.select_one('h1.headline').text.strip() if soup.select_one('h1.headline') else None,
                    'summary': soup.select_one('div.summary').text.strip() if soup.select_one('div.summary') else None,
                    'content': soup.select_one('#articletxt').text.strip() if soup.select_one('#articletxt') else None,
                    'url': url,
                    'datetime': soup.select_one('div.datetime span.txt-date').text.strip() if soup.select_one('div.datetime span.txt-date') else None,
                }

            # ✅ 알 수 없는 도메인
            else:
                print(f"⚠️ 알 수 없는 호스트: {hostname}")
                return {'url': url, 'header': None, 'summary': None, 'content': None, 'datetime': None}

    except Exception as e:
        print(f"[fetch_article error] {url} - {e}")
        return {'url': url, 'header': None, 'summary': None, 'content': None, 'datetime': None}
# ▶ 메인 비동기 루프
async def extract_news_data_async(query_text, page_range):
    base_url = 'https://search.hankyung.com/search/news?query={query}&page={page}'
    search_urls = [base_url.format(query=query_text, page=p+1) for p in range(page_range)]

    async with aiohttp.ClientSession() as session:
        # 1. 페이지별 기사 링크 수집
        tasks = [get_article_urls(session, url) for url in search_urls]
        results = await asyncio.gather(*tasks)
        article_urls = list(set([url for sublist in results for url in sublist]))

        print(f"🔗 총 {len(article_urls)}개의 기사 URL 수집됨")

        # 2. 기사 본문 수집
        article_tasks = [fetch_article(session, url) for url in article_urls]
        articles = await asyncio.gather(*article_tasks)

        # 3. ticker 컬럼 추가
        for article in articles:
            article['ticker'] = query_text

        # 4. 비어 있으면 dummy row 추가
        if not articles:
            articles = [{
                'header': None,
                'summary': None,
                'content': None,
                'url': None,
                'datetime': None,
                'ticker': query_text
            }]
            print("⚠️ 수집된 기사가 없어 None 값으로 대체 저장합니다.")

        # 4. DuckDB 저장
        df = pd.DataFrame(articles)
        con = duckdb.connect('../DB/Customer_news.db')

        # Pandas DataFrame을 DuckDB에서 참조할 수 있도록 등록
        con.register('temp_df', df)

        # 테이블이 없다면 생성
        con.execute("""
            CREATE TABLE IF NOT EXISTS articles AS
            SELECT * FROM temp_df LIMIT 0
        """)

        # 데이터 삽입
        con.execute("INSERT INTO articles SELECT * FROM temp_df")

        # 정리
        con.unregister('temp_df')
        con.close()

        print(f"✅ 저장 완료: ../DB/Customer_news.db (ticker = {query_text})")

# ▶ 실행 함수
def extract_news_data(query_text, page_range):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(extract_news_data_async(query_text, page_range))

In [ ]:
for ticker in Custer_Having_ticker_lst:
    extract_news_data(ticker,50)

🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 우리금융지주)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성화재)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성생명)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 카카오뱅크)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 메리츠금융지주)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대모비스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대오토에버)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = SK하이닉스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대글로비스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대차)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = SK하이닉스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성전자)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 한미반도체)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 파크시스템스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = DB하이텍)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대모비스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대차)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 기아)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = POSCO홀딩스)
🔗 총 500개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = LG에너지솔루션)

저장이 잘 되었는 지 확인

In [15]:
cus_news = duckdb.connect('../DB/Customer_news.db')

In [16]:
cusA_news_df = cus_news.execute('select * from articles').fetch_df()
cus_news.close()

In [17]:
cusA_news_df.head(5)

,header,summary,content,url,datetime,ticker
0,"18일, 거래소 외국인 순매수상위에 전기,전자 업종 4종목",None,"외국인 투자자는 18일 거래소에서 삼성전자, NAVER, 크래프톤 등을 중점적으로 ...",https://www.hankyung.com/article/202506184343L,2025.06.18 18:35,우리금융지주
1,"""실적·주주환원 훈풍""…은행·증권주 신고가 행진, 스탁론 매수세도 유입",None,국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가...,https://www.hankyung.com/article/202507096279a,2025.07.09 10:30,우리금융지주
2,"12일, 외국인 거래소에서 한화에어로스페이스(+5.3%), 현대차(+0.25%) 등...",None,"외국인 투자자는 12일 거래소에서 한화에어로스페이스, 현대차, 현대건설 등을 중점적...",https://www.hankyung.com/article/202506121791L,2025.06.12 18:35,우리금융지주
3,"금감원, 우리금융 경평 '2→3등급' 결론…이번주 통보할 듯",None,금감원 / 사진=노정동 기자\n\n 금융감독원이 우리금융...,https://www.hankyung.com/article/2025031784556,2025.03.17 11:18,우리금융지주
4,한도 초과 걱정 없이 연 4%대 금리로 저점 집중투자 시작하기!,None,부자네스탁론이 특별 이벤트로 5년고정 연 4.9%의 저금리 스탁론 상품을 출시하면서...,https://www.hankyung.com/article/202506056123a,2025.06.05 14:38,우리금융지주

In [18]:
cusA_news_df.shape

(10000, 6)

In [19]:
# 중복제거 필요...
cusA_news_df.groupby('ticker').count()

          header  summary  content   url  datetime
ticker
DB하이텍        500       62      500   500       500
LG에너지솔루션     500       96      500   500       500
POSCO홀딩스     500       25      500   500       500
SK하이닉스      1000      238     1000  1000      1000
기아           499      238      499   500       499
메리츠금융지주      500      128      500   500       500
삼성생명         500      165      500   500       500
삼성전자         500      161      500   500       500
삼성화재         499      186      499   500       499
우리금융지주       500      175      500   500       500
카카오뱅크        498      122      498   500       498
파크시스템스       500       32      500   500       500
한미반도체        500       69      500   500       500
현대글로비스       500      128      500   500       500
현대모비스       1000      338     1000  1000      1000
현대오토에버       500       57      500   500       500
현대차         1000      356     1000  1000      1000

In [20]:
cusA_news_df = cusA_news_df.drop_duplicates()

In [21]:
cusA_news_df.groupby('ticker').count()

          header  summary  content  url  datetime
ticker
DB하이텍        500       62      500  500       500
LG에너지솔루션     500       96      500  500       500
POSCO홀딩스     500       25      500  500       500
SK하이닉스       500      119      500  500       500
기아           499      238      499  500       499
메리츠금융지주      500      128      500  500       500
삼성생명         500      165      500  500       500
삼성전자         500      161      500  500       500
삼성화재         499      186      499  500       499
우리금융지주       500      175      500  500       500
카카오뱅크        498      122      498  500       498
파크시스템스       500       32      500  500       500
한미반도체        500       69      500  500       500
현대글로비스       500      128      500  500       500
현대모비스        500      169      500  500       500
현대오토에버       500       57      500  500       500
현대차          500      178      500  500       500

## 번외) 날짜 전처리 확인 : 최근 N일치 가져오는 로직 생성

In [22]:
cusA_news_df['Date'] = cusA_news_df.datetime.str[:10]
cusA_news_df = cusA_news_df.drop('datetime',axis=1)
cusA_news_df['Date'] = pd.to_datetime(cusA_news_df['Date'])

In [23]:
# 2. 기준일 계산 (오늘 날짜 - 5일)
today = pd.to_datetime("2025-07-30")
five_days_ago = today - timedelta(days=30)

# 3. 최근 5일치 필터링
recent_news_df = cusA_news_df[cusA_news_df['Date'] >= five_days_ago]

In [24]:
recent_news_df

,header,summary,content,url,ticker,Date
1,"""실적·주주환원 훈풍""…은행·증권주 신고가 행진, 스탁론 매수세도 유입",None,국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가...,https://www.hankyung.com/article/202507096279a,우리금융지주,2025-07-09
5,"미래에셋만 너무 비싸다?…""PBR 1.2배도 가능""",None,영상 모듈 닫기\n\n\n\n\n<앵커> 증시 상승세에 힘입어 국내 증권사들도 2분...,https://www.hankyung.com/article/2025071501385,우리금융지주,2025-07-15
7,"09일, 외국인 거래소에서 삼성전자(-1.63%), 두산에너빌리티(-3.3%) 등 순매도",None,"외국인 투자자는 09일 거래소에서 삼성전자, 두산에너빌리티, 삼성SDI 등을 중점적...",https://www.hankyung.com/article/202507098435L,우리금융지주,2025-07-09
8,"01일, 코스닥 외국인 순매수상위에 일반전기전자 업종 5종목",None,"외국인 투자자는 01일 코스닥에서 리가켐바이오, 솔브레인, 디앤디파마텍 등을 중점적...",https://www.hankyung.com/article/202508017025L,우리금융지주,2025-08-01
13,반도체 대장주 자리 꿰차더니…SK하이닉스 개미들 '두근두근',2분기 실적 시즌 돌입…영업이익 추정치 살펴보니\n\n하이닉스 영업익 첫 9조 넘을...,2분기 실적 발표 시즌에 본격 돌입하면서 주도주의 성적표가 윤곽을 드러내고 있다. ...,https://www.hankyung.com/article/2025072252001,우리금융지주,2025-07-22
...,...,...,...,...,...,...
9995,"코스피, 3200선 회복…테슬라 업은 삼성전자, 7만원대 탈환",코스닥은 0.3% '하락'\n원·달러 환율 1382원에 주간거래 마쳐,28일 서울 중구 하나은행 본점 딜링룸에서 직원들이 업무를 보고 있다. /사진=연합...,https://www.hankyung.com/article/2025072866196,LG에너지솔루션,2025-07-28
9996,"코스피, 3년10개월 만에 3200선 돌파…'연고점 또 경신'",삼성전자·하이닉스 2%대 강세,사진=연합뉴스\n\n 코스피지수가 11일 개인투자자의 매...,https://www.hankyung.com/article/2025071119236,LG에너지솔루션,2025-07-11
9997,"코스피, 3190선 약세 출발…코스닥은 강보합",None,전날인 14일 오후 서울 중구 하나은행 본점 딜링룸 전광판. /사진=뉴스1\n\n ...,https://www.hankyung.com/article/2025071582926,LG에너지솔루션,2025-07-15
9998,"이자 부담은 최소로, 투자 효율은 최대로! 신용대출 3%대 활용법",None,"전송종목 : 바이오비쥬, 엘브이엠씨홀딩스, 크리스탈신소재, GRT, 잉글우드랩최근 ...",https://www.hankyung.com/article/202507071499a,LG에너지솔루션,2025-07-07
9999,"코스피, 기관 '저가매수'에 강세…바이오株 '들썩'",None,사진=연합뉴스\n\n 코스피가 기관의 저가매수에 강세를 ...,https://www.hankyung.com/article/2025080499546,LG에너지솔루션,2025-08-04

In [25]:
recent_news_df= recent_news_df.drop_duplicates()

In [26]:
# 최근 30일치 뉴스 기사 필터링 시 남아있는 뉴스 기사 개수
recent_news_df.groupby('ticker').count()

          header  summary  content  url  Date
ticker
DB하이텍         30        4       30   30    30
LG에너지솔루션     500       96      500  500   500
POSCO홀딩스     464       23      464  464   464
SK하이닉스       500      119      500  500   500
기아           411      191      411  411   411
메리츠금융지주       51        5       51   51    51
삼성생명         140       45      140  140   140
삼성전자         500      161      500  500   500
삼성화재          96       31       96   96    96
우리금융지주       153       46      153  153   153
카카오뱅크        117       17      117  117   117
파크시스템스        26        1       26   26    26
한미반도체        228       43      228  228   228
현대글로비스        53       15       53   53    53
현대모비스        116       27      116  116   116
현대오토에버        19        3       19   19    19
현대차          500      178      500  500   500

## 정규식으로 뉴스 기사 내 불용어 처리

In [27]:
boilerplate_patterns = [
    r"\* 아래 텍스트는 실제 방송 내용과 차이가 있을 수 있으니.*",
    r"\*인터뷰를 인용보도할 때는 프로그램명.*",
    r"저작권은.*에 있습니다.*",
    r"▶ 알립니다.*",
    r"\[앵커\].*?\[",
    r"\[기자\].*?\[",
    r"\[.*?\]",             # 모든 대괄호 안 내용
    r"영상취재:.*",
    r"영상편집:.*",
    r"그래픽:.*",
    r"\/?사진=(연합뉴스|뉴스\S*)[^\n]*\s*"       # 사진=출처 or /사진=출처 패턴 제거
]

In [28]:
compiled_pattern = re.compile("|".join(boilerplate_patterns))

In [29]:
test_pattern = cusA_news_df.content.astype(str).apply(lambda x : compiled_pattern.sub("", x).strip())

In [30]:
cusA_news_df.content.astype(str).apply(lambda x : len(x)).describe()

count      8500.000000
mean       1677.332000
std        7343.833444
min           0.000000
25%         707.000000
50%        1077.000000
75%        1496.000000
max      125274.000000
Name: content, dtype: float64

In [31]:
test_pattern.apply(lambda x : len(x)).describe()

count      8500.000000
mean       1660.115294
std        7342.442298
min           0.000000
25%         689.750000
50%        1073.000000
75%        1496.000000
max      125274.000000
Name: content, dtype: float64

#### 결론 : 큰 영향 없다..? 그냥 해보자

## 질문 생성 (For Labeling)  -- 주말 작업 예정 .. 모델 성능평가를 위함
Part_1 : Re-Ranking 라벨링

In [32]:
def labeling(data):
  template = """
  <instruction>
  다음은 뉴스 기사 본문과 해당 기사에 매핑된 종목명(티커)입니다.
  당신의 임무는 기사 본문이 해당 종목에 대한 기사인지 여부를 판별하는 것입니다.

  규칙:
  - 1 : 뉴스 내용이 해당 종목 기사 내용임.
     예: 종목명이 기사에 등장하고, 그 종목의 실적, 주가, 제품, 사건, 경영, 산업 동향 등과 밀접한 관련이 있음.
     예) 종목의 실적/주가/사업/이슈/계약/정책/규제/소송/리스크/전망 등.
     예) 섹터 기사라도 해당 종목이 사례/주요 구성원으로 명시적 언급되고 맥락에 기여.
  - 0 : 뉴스 내용이 해당 종목과 직접적으로 관련이 없음  
     예: 종목명이 전혀 등장하지 않거나, 비슷한 용어를 가진 단어의 내용이 등장하더라도 다른 주제가 메인인 경우.
     예) 피상적 나열(태그/키워드/꼬리말 광고)만 존재, 타사 이슈가 중심.
     
  출력 형식:
  - 숫자 1 또는 0만 출력
  </instruction>

  예시:
  ---
  [티커] 삼성전자
  [본문] 삼성전자가 2분기 실적 호조를 발표하며 주가가 3% 상승했다.
  [정답] 1
  ---
  [티커] 삼성전자
  [본문] 미국 증시가 기술주 중심으로 상승세를 보였다. 애플과 구글 주가가 상승했다.
  [정답] 0
  ---

  다음 데이터를 분류하세요.

  [티커] {ticker_name}
  [본문] {news_content}
  [정답]
  """

  prompt = ChatPromptTemplate.from_template(template)

  # 3. 체인 구성
  chain = prompt | llm | StrOutputParser()

  # 4. 실행 예시
  query = chain.invoke({"news_content": data,'ticker_name' : '우리금융지주'})
  return query

## 6. VectorDB 저장

In [33]:
# 4. OpenAI 임베딩 모델 로딩
embedding = OpenAIEmbeddings(model="text-embedding-3-large")

persist_directory = "../VectorDB/chroma_news_db"

vectordb = Chroma(
    persist_directory=persist_directory,
    embedding_function=embedding,
    collection_name="SLM_News")

In [34]:
def pick_splitter_by_length(text_len: int) -> RecursiveCharacterTextSplitter:
    """
    뉴스 본문의 길이에 따라 적절한 텍스트 분할기를 반환합니다.
    """
    if text_len <= 1200:
        # 짧은 기사 → 굳이 자르지 않고 1덩어리로 처리
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=0,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 10_000:
        # 중간 길이 → 일반적인 1,200자 기준으로 분할
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=150,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 50_000:
        # 긴 기사 → 덩어리를 좀 더 키움
        return RecursiveCharacterTextSplitter(
            chunk_size=1800,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )
    else:
        # 초장문 → 더 크게 자르되, 요약도 고려 (이건 후속 처리 필요)
        return RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )

In [35]:
# 2. 문서 리스트 생성 (chunk + metadata 포함)
def make_documents(df):
    docs = []

    for idx, row in tqdm(df.iterrows()):
        text = row["content"]
        splitter = pick_splitter_by_length(len(text))
        chunks = splitter.split_text(text)
        for i, chunk in enumerate(chunks):
            label = labeling(chunks)
            metadata = {
                "title": row["header"],
                "url": row["url"],
                "Date": row["Date"],
                "ticker": row.get("ticker", "None"),
                "chunk_idx": i,
                "original_idx": idx,
                'label' : label  #labeling한 결과를 넣자!! 
            }
            time.sleep(0.1)
            docs.append(Document(page_content=chunk, metadata=metadata))

    return docs

In [36]:
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max() # 가지고 있는 뉴스의 가장 최신 데이터
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

In [37]:
def make_doc_id(d: Document) -> str:
    """
    url + chunk_idx(없으면 0) + 시간
    """
    run_utc = datetime.now(timezone.utc)
    base = f"{d.metadata.get('url','')}_{d.metadata.get('chunk_idx', 0)}_{run_utc}"
    return md5(base.encode("utf-8")).hexdigest()

def chunks(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

## Label작업 수행

In [38]:
for ticker in Custer_Having_ticker_lst:
    print(f"========= ticker {ticker} 진행 중~ =============")
    task_1_df = get_recent_articles(cusA_news_df,ticker=ticker,days = 30)
    task_1_df['Date'] = task_1_df.Date.astype('str')
    # document 만들기
    task_1_docs = make_documents(task_1_df)
    length_docs = len(task_1_docs)
    print(f'각 {ticker} 별 docs의 개수 : {length_docs}')
    BATCH = 64  # 상황에 맞게 조절

    for docs in tqdm(chunks(task_1_docs, BATCH), total=(len(task_1_docs) + BATCH - 1) // BATCH):

        ids = [make_doc_id(d) for d in docs]
        vectordb.add_documents(documents=docs, ids=ids)
        time.sleep(0.1)

========= ticker 우리금융지주 진행 중~ =============

0it [00:00, ?it/s]

115it [02:56,  1.54s/it]

각 우리금융지주 별 docs의 개수 : 219

100%|██████████| 4/4 [00:10<00:00,  2.50s/it]

========= ticker 삼성화재 진행 중~ =============

76it [01:32,  1.22s/it]

각 삼성화재 별 docs의 개수 : 123

100%|██████████| 2/2 [00:06<00:00,  3.04s/it]

========= ticker 삼성생명 진행 중~ =============

100it [02:31,  1.51s/it]

각 삼성생명 별 docs의 개수 : 193

100%|██████████| 4/4 [00:10<00:00,  2.55s/it]

========= ticker 카카오뱅크 진행 중~ =============

87it [01:38,  1.13s/it]

각 카카오뱅크 별 docs의 개수 : 122

100%|██████████| 2/2 [00:05<00:00,  2.76s/it]

========= ticker 메리츠금융지주 진행 중~ =============

39it [00:50,  1.29s/it]

각 메리츠금융지주 별 docs의 개수 : 66

100%|██████████| 2/2 [00:04<00:00,  2.06s/it]

========= ticker 현대모비스 진행 중~ =============

93it [01:42,  1.10s/it]

각 현대모비스 별 docs의 개수 : 128

100%|██████████| 2/2 [00:05<00:00,  2.91s/it]

========= ticker 현대오토에버 진행 중~ =============

17it [00:15,  1.09it/s]

각 현대오토에버 별 docs의 개수 : 22

100%|██████████| 1/1 [00:01<00:00,  1.86s/it]

========= ticker SK하이닉스 진행 중~ =============

500it [12:24,  1.49s/it]

각 SK하이닉스 별 docs의 개수 : 968

100%|██████████| 16/16 [00:49<00:00,  3.10s/it]

========= ticker 현대글로비스 진행 중~ =============

43it [00:45,  1.07s/it]

각 현대글로비스 별 docs의 개수 : 63

100%|██████████| 1/1 [00:03<00:00,  3.01s/it]

========= ticker 현대차 진행 중~ =============

303it [08:18,  1.65s/it]

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo in organization org-CuTNQyXsUJcPWkwA97y1gHEH on tokens per min (TPM): Limit 200000, Used 194032, Requested 6075. Please try again in 32ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

In [37]:
print("Number of documents in DB:", vectordb._collection.count())

Number of documents in DB: 685

## 7. cross-encoder 모델(w/langchain 예시)

Re-ranker 사용하기 전

In [39]:
retriver_target = ['우리금융지주','삼성화재','카카오뱅크','삼성생명','메리츠금융지주','현대모비스','현대글로비스','SK하이닉스','현대오토에버']

In [40]:
retriever_total = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : retriver_target}})

In [41]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i + 1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

Re-ranker 모델 사용 후

In [43]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=50)
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_total
)

검색 유사도 측정
 - 이유 : 적정한 조건을 찾기 위함

In [47]:
scored_docs = []

retriever가 내부에서 메타데이터 필터(where/filter) 를 쓰고 있는데, 거기에 ['우리금융지주', ...] 같은 리스트를 그대로 넣어둔 상태예요. 대부분의 벡터스토어(특히 Chroma/LangChain)는 where/filter 값이 단일 값(str/int/float) 이거나 연산자 표현식이어야 하고, 리스트는 $in 같은 연산자로 감싸줘야 합니다. 그래서 get_relevant_documents() 부를 때마다 같은 잘못된 필터가 적용되어 터진 거죠.

빠른 해결책 (권장)
루프마다 단일 종목으로 필터를 바꿔서 조회하세요.

In [48]:
for ticker in retriver_target:
    retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs.append(dd)
    #scored_docs.sort(key=lambda x: (x.metadata[''],x.metadata["relevance_score"]), reverse=True)

이 뉴스들 중에서 "우리금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 우리금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/var/folders/xq/zzsj9f116r7brgm2wm610nx00000gn/T/ipykernel_36208/2935046578.py:8: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성화재"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성화재가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "카카오뱅크"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 카카오뱅크가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성생명"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성생명가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "메리츠금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 메리츠금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대모비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대모비스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대글로비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대글로비스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대오토에버"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대오토에버가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [49]:
# 4) 확인 - raw data
for i, d in enumerate(scored_docs[:50], 1):
    print(f"{i:02d} | original_idx : {d.metadata['original_idx']} | chunk_idx : {d.metadata['chunk_idx']}| score : {d.metadata['relevance_score']:.4f} | {d.metadata.get('title')}")

01 | original_idx : 245 | chunk_idx : 1| score : 0.1130 | 더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트
02 | original_idx : 158 | chunk_idx : 0| score : 0.0100 | 대출 수익성 악화에…4대 금융 실적 꺾였다
03 | original_idx : 475 | chunk_idx : 0| score : 0.2153 | 4대금융 2분기 순익 5.4조…사상 최대 실적
04 | original_idx : 237 | chunk_idx : 0| score : 0.6022 | '우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수
05 | original_idx : 245 | chunk_idx : 3| score : 0.0047 | 더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트
06 | original_idx : 158 | chunk_idx : 1| score : 0.3583 | 대출 수익성 악화에…4대 금융 실적 꺾였다
07 | original_idx : 1 | chunk_idx : 0| score : 0.1089 | "실적·주주환원 훈풍"…은행·증권주 신고가 행진, 스탁론 매수세도 유입
08 | original_idx : 23 | chunk_idx : 0| score : 0.2479 | '우리금융지주' 52주 신고가 경신, 갈수록 돋보일 고배당 매력 - NH투자증권, BUY
09 | original_idx : 258 | chunk_idx : 2| score : 0.0045 | 4대금융, 이자 대신 환차익 덕 봤다…"하반기엔 불투명"
10 | original_idx : 229 | chunk_idx : 0| score : 0.0163 | 금융지주 영구채 '큰장' 선다…신한·하나 등 1.8조원 쏟아질 듯
11 | original_idx : 476 | chunk_idx : 0| score : 0.3970 | "우리금융지주, 연말로 갈수록 고배당 부각…목표가↑"-NH
12 | original_idx : 446 | chunk_idx : 0| score : 0.2653 | “금리 하락에도 이익 증가” 금융지주, 실적 온도차
13 | original_idx : 236 | chunk_idx : 0| score : 0.0009 | 금융사 채권 발행 봇물…저금리에 자본 확충
14 | original_idx : 354 | chunk_idx : 0| score : 0.0910 | 16일, 거래소 외국인 순매도상위에 운수장비 업종 2종목
15 | original_idx : 305 | chunk_idx : 0| score : 0.1203 | 이 한방에 3배 수익? 전문가도 몰래 챙긴 비밀 종목은
16 | original_idx : 446 | chunk_idx : 1| score : 0.0232 | “금리 하락에도 이익 증가” 금융지주, 실적 온도차
17 | original_idx : 1 | chunk_idx : 1| score : 0.0099 | "실적·주주환원 훈풍"…은행·증권주 신고가 행진, 스탁론 매수세도 유입
18 | original_idx : 245 | chunk_idx : 2| score : 0.0233 | 더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트
19 | original_idx : 374 | chunk_idx : 0| score : 0.4674 | '우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수
20 | original_idx : 258 | chunk_idx : 1| score : 0.0786 | 4대금융, 이자 대신 환차익 덕 봤다…"하반기엔 불투명"
21 | original_idx : 16 | chunk_idx : 0| score : 0.1248 | 2025 밸류업 CEO 50 랭킹 - 금융 11~20위
22 | original_idx : 211 | chunk_idx : 0| score : 0.0172 | 은행 ETF 고공행진…수익률 톱5 휩쓸었다
23 | original_idx : 423 | chunk_idx : 1| score : 0.0032 | '이자놀이' 비판에…금융 협회장 소집
24 | original_idx : 49 | chunk_idx : 0| score : 0.1203 | '우리금융지주' 52주 신고가 경신, 장기 보유 매력 유효 - 미래에셋증권, 매수
25 | original_idx : 93 | chunk_idx : 2| score : 0.0016 | 은행권 "위험자산에 ELS·DLF 손실 배제를"
26 | original_idx : 258 | chunk_idx : 0| score : 0.0425 | 4대금융, 이자 대신 환차익 덕 봤다…"하반기엔 불투명"
27 | original_idx : 26 | chunk_idx : 3| score : 0.0036 | 최대 실적 카뱅…"스테이블코인 시장 선점"
28 | original_idx : 13 | chunk_idx : 1| score : 0.0069 | 반도체 대장주 자리 꿰차더니…SK하이닉스 개미들 '두근두근'
29 | original_idx : 133 | chunk_idx : 0| score : 0.0197 | 2년 새 35% 늘어난 주주환원...KT&G, 시총 대비 환원율 1위
30 | original_idx : 404 | chunk_idx : 0| score : 0.0375 | 15일, 거래소 외국인 순매도상위에 보험 업종 3종목
31 | original_idx : 5 | chunk_idx : 1| score : 0.0008 | 미래에셋만 너무 비싸다?…"PBR 1.2배도 가능"
32 | original_idx : 213 | chunk_idx : 0| score : 0.0040 | POSCO홀딩스, 그린본드 발행·기술 협업·수급 재평가로 상승 기대감
33 | original_idx : 212 | chunk_idx : 0| score : 0.0139 | “금융의 본질을 넘어 더 멀리 보고 깊이 고민할 것”[CEO 말말말]
34 | original_idx : 67 | chunk_idx : 2| score : 0.0006 | [마켓PRO] 고배당주 열풍…증권주 ETF 일주일 새 15% '줄상승'
35 | original_idx : 333 | chunk_idx : 1| score : 0.0029 | 자사주 매입 속속 연기…금융지주 밸류업 차질
36 | original_idx : 276 | chunk_idx : 2| score : 0.0006 | '큰손'들 대거 몰려들더니…일주일 새 줄줄이 15% 뛰었다
37 | original_idx : 5 | chunk_idx : 2| score : 0.0004 | 미래에셋만 너무 비싸다?…"PBR 1.2배도 가능"
38 | original_idx : 276 | chunk_idx : 0| score : 0.0012 | '큰손'들 대거 몰려들더니…일주일 새 줄줄이 15% 뛰었다
39 | original_idx : 236 | chunk_idx : 1| score : 0.0257 | 금융사 채권 발행 봇물…저금리에 자본 확충
40 | original_idx : 291 | chunk_idx : 1| score : 0.0589 | 배당주 급락에도…증권가 "지금이 매수할 때"
41 | original_idx : 67 | chunk_idx : 1| score : 0.0138 | [마켓PRO] 고배당주 열풍…증권주 ETF 일주일 새 15% '줄상승'
42 | original_idx : 209 | chunk_idx : 1| score : 0.2312 | [마켓PRO] Today's Pick : "에코프로비엠, 3분기 흑자전환 기대"
43 | original_idx : 276 | chunk_idx : 1| score : 0.0138 | '큰손'들 대거 몰려들더니…일주일 새 줄줄이 15% 뛰었다
44 | original_idx : 44 | chunk_idx : 0| score : 0.0014 | 국민연금, 2분기 금융·지주·내수주 비중 확대… 2차전지 비중은 축소
45 | original_idx : 32 | chunk_idx : 0| score : 0.0730 | 28일, 거래소 외국인 순매수상위에 전기,전자 업종 5종목
46 | original_idx : 273 | chunk_idx : 0| score : 0.0118 | 08일, 거래소 외국인 순매수상위에 전기,전자 업종 3종목
47 | original_idx : 387 | chunk_idx : 0| score : 0.0677 | 금융주 동반 하락…하나금융지주 급락
48 | original_idx : 26 | chunk_idx : 2| score : 0.0005 | 최대 실적 카뱅…"스테이블코인 시장 선점"
49 | original_idx : 212 | chunk_idx : 2| score : 0.0227 | “금융의 본질을 넘어 더 멀리 보고 깊이 고민할 것”[CEO 말말말]
50 | original_idx : 194 | chunk_idx : 1| score : 0.0633 | 지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]

### Re-Ranker 모델 측정

In [50]:
rerank_df = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs)))

In [51]:
rerank_df.ticker.value_counts()

ticker
우리금융지주     50
삼성화재       50
카카오뱅크      50
삼성생명       50
메리츠금융지주    50
현대모비스      50
현대글로비스     50
SK하이닉스     50
현대오토에버     22
Name: count, dtype: int64

In [52]:
rerank_df.head()

,chunk_idx,title,label,original_idx,ticker,url,Date,relevance_score
0,1,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",1,245,우리금융지주,https://www.hankyung.com/article/2025070981175,2025-07-09,0.113008
1,0,대출 수익성 악화에…4대 금융 실적 꺾였다,1,158,우리금융지주,https://www.hankyung.com/article/2025071501731,2025-07-15,0.010040
2,0,4대금융 2분기 순익 5.4조…사상 최대 실적,1,475,우리금융지주,https://www.hankyung.com/article/2025072528861,2025-07-25,0.215311
3,0,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",1,237,우리금융지주,https://www.hankyung.com/article/202507145874L,2025-07-14,0.602175
4,3,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",1,245,우리금융지주,https://www.hankyung.com/article/2025070981175,2025-07-09,0.004671

In [53]:
rerank_df= rerank_df.sort_values(by=['ticker','relevance_score'])

In [54]:
rerank_df.shape

(422, 8)

In [56]:
rerank_df.ticker.value_counts()

ticker
SK하이닉스     50
메리츠금융지주    50
삼성생명       50
삼성화재       50
우리금융지주     50
카카오뱅크      50
현대글로비스     50
현대모비스      50
현대오토에버     22
Name: count, dtype: int64

In [131]:
rerank_df[rerank_df.ticker=='SK하이닉스'].label.value_counts()

label
1    49
0     1
Name: count, dtype: int64

In [57]:
VecDB = vectordb._collection
total_results = VecDB.get(
         include = ['documents','metadatas']   
        )

In [58]:
total_df = pd.DataFrame(total_results['metadatas'])

In [59]:
total_df.shape

(1904, 7)

In [60]:
total_df.ticker.value_counts()

ticker
SK하이닉스     968
우리금융지주     219
삼성생명       193
현대모비스      128
삼성화재       123
카카오뱅크      122
메리츠금융지주     66
현대글로비스      63
현대오토에버      22
Name: count, dtype: int64

In [132]:
total_df[total_df.ticker=='SK하이닉스'].label.value_counts()

label
1    797
0    171
Name: count, dtype: int64

In [61]:
import numpy as np
import pandas as pd

def _dcg_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    if L.size == 0: return 0.0
    discounts = 1.0 / np.log2(np.arange(2, L.size + 2))
    return float(np.sum(L * discounts))

def ndcg_at_k(labels, k=50):
    labels = np.asarray(labels)
    dcg  = _dcg_at_k(labels, k)
    idcg = _dcg_at_k(np.sort(labels)[::-1], k)
    return 0.0 if idcg == 0 else dcg / idcg

def precision_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    return float(L.mean()) if L.size else 0.0

def recall_at_k(labels, total_relevant, k=50):
    if not total_relevant or total_relevant <= 0: return 0.0
    return float(np.sum(np.asarray(labels)[:k])) / float(total_relevant)

def mrr_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    hit = np.where(L > 0)[0]
    return 0.0 if hit.size == 0 else 1.0 / (hit[0] + 1)

def map_at_k(labels, total_relevant, k=50):
    L = np.asarray(labels)[:k]
    if L.sum() == 0: return 0.0
    precisions, hit = [], 0
    for i, y in enumerate(L, start=1):
        if y:
            hit += 1
            precisions.append(hit / i)
    denom = max(1, min(total_relevant if total_relevant is not None else int(L.sum()), k))
    return float(np.sum(precisions) / denom)

def eval_reranker_chunk(pool_df, ranked_df, k=50, rank_col="rank", score_col="relevance_score"):
    # 1) 풀: label만 필요 (score/rank 불필요)
    total_rel_pool = int(
        pd.to_numeric(pool_df["label"], errors="coerce").fillna(0).clip(0,1).sum()
    )
    print(f'total_rel_pool : {total_rel_pool}')

    # 2) 랭크드: 순서가 필요 (rank 우선, 없으면 score로 정렬, 둘 다 없으면 현재 순서 사용)
    g = ranked_df.copy()
    if rank_col in g.columns:
        g = g.sort_values(rank_col, ascending=True)
    elif score_col in g.columns:
        g = g.sort_values(score_col, ascending=False)
        g[rank_col] = np.arange(1, len(g)+1)
    else:
        g[rank_col] = np.arange(1, len(g)+1)

    y_topk = pd.to_numeric(g["label"], errors="coerce").fillna(0).clip(0,1).astype(int).values[:k]
    print(f'y_topk : {y_topk}')
    return {
        f"Precision@{k}": precision_at_k(y_topk, k),
        f"Recall@{k}(pool)": recall_at_k(y_topk, total_rel_pool, k),
        f"MRR@{k}": mrr_at_k(y_topk, k),
        f"MAP@{k}": map_at_k(y_topk, total_rel_pool, k),
        f"nDCG@{k}": ndcg_at_k(y_topk, k),
        "PoolSize": int(len(pool_df)),
        "PoolRelevant": total_rel_pool,
        "TopK": int(min(len(g), k)),
        "TopKRelevant": int(y_topk.sum()),
    }

In [66]:
rerank_eval = []

In [67]:
for kind in retriver_target:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target = rerank_df[rerank_df.ticker==kind]
    rerank_eval.append(eval_reranker_chunk(total_df_target,rerank_df_target))

total_rel_pool : 180
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 91
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 0 0 1 1 0 1 0 0]
total_rel_pool : 99
y_topk : [1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 109
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0
 1 1 1 1 0 0 1 0 0 1 1 0 0]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 0 0 0 0 1 0 0 0 0 0 0 0 0]
total_rel_pool : 98
y_topk : [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0
 1 1 1 1 1 0 1 0 1 1 0 0 1]
total_rel_pool : 49
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 0 1 0 1 1]
total_rel_pool : 797
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 14
y_topk : [1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1]

In [68]:
rerank_eval_con = dict(zip(Custer_Having_ticker_lst,rerank_eval))

In [69]:
pd.DataFrame(rerank_eval_con)

,우리금융지주,삼성화재,삼성생명,카카오뱅크,메리츠금융지주,현대모비스,현대오토에버,SK하이닉스,현대글로비스
Precision@50,1.000000,0.780000,0.900000,0.800000,0.680000,0.820000,0.800000,0.980000,0.636364
Recall@50(pool),0.277778,0.428571,0.454545,0.366972,0.723404,0.418367,0.816327,0.061481,1.000000
MRR@50,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
MAP@50,1.000000,0.718375,0.817043,0.764605,0.694256,0.740508,0.729028,0.973507,0.896701
nDCG@50,1.000000,0.982615,0.977576,0.990670,0.991350,0.964739,0.976200,0.998768,0.972676
PoolSize,219.000000,123.000000,122.000000,193.000000,66.000000,128.000000,63.000000,968.000000,22.000000
PoolRelevant,180.000000,91.000000,99.000000,109.000000,47.000000,98.000000,49.000000,797.000000,14.000000
TopK,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,22.000000
TopKRelevant,50.000000,39.000000,45.000000,40.000000,34.000000,41.000000,40.000000,49.000000,14.000000

### original 본문 가져오기

In [91]:
test_ticker = 'SK하이닉스'

In [92]:
CrossEncoder_prompt_test = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [ ]:
# rerank을 통해 문서 가져오기
reranked_docs = compressor.compress_documents(raw_docs, query=CrossEncoder_prompt_test)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [105]:
retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})

In [106]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
)

In [107]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [108]:
def get_full_article_from_chroma(original_idx: int, kind : str, vectordb) -> dict:
    """original_idx 기준으로 chunk들을 모아 원문 복원"""
    # 1. 해당 article의 모든 chunk 가져오기
    VecDB = vectordb._collection
    results = VecDB.get(
      where = { "$and" : [ # 빈 쿼리로 전체 탐색
            {"original_idx": original_idx}, 
            {"ticker": kind}
            ]
         },
         include = ['documents','metadatas']   
        )
        
    if not results:
        return {"error": f"No chunks found for original_idx {original_idx}"}

    #print(results)
    #print(results['metadatas'][0]['chunk_idx'])

    # 4. 대표 metadata 하나 뽑아 저장
    return {
        "title": results['metadatas'][0]["title"],
        "url": results['metadatas'][0]["url"],
        "Date": results['metadatas'][0]["Date"],
        "ticker": results['metadatas'][0]["ticker"],
        "content": results['documents'][0]
    }

In [109]:
original_idxs = list(map(lambda x: x.metadata['original_idx'], compressed_docs))

In [110]:
original_idxs

[3739,
 3607,
 3798,
 3838,
 3791,
 3706,
 3951,
 3659,
 3885,
 3666,
 3538,
 3897,
 3583,
 3980,
 3511,
 3691,
 3806,
 3531,
 3802,
 3966,
 3618,
 3656,
 3690,
 3844,
 3986,
 3732,
 3584,
 3764,
 3537,
 3802,
 3882,
 3955,
 3588,
 3700,
 3801,
 3802,
 3808,
 3648,
 3922,
 3529,
 3605,
 3785,
 3700,
 3802,
 3987,
 3847,
 3802,
 3763,
 3905,
 3807]

In [112]:
get_full_article_from_chroma(3980, kind=test_ticker,vectordb=vectordb)

{'title': '05일, 외국인 거래소에서 SK하이닉스(+2.13%), 삼성SDI(+10.22%) 등 순매수',
 'url': 'https://www.hankyung.com/article/202508053349L',
 'Date': '2025-08-05',
 'ticker': 'SK하이닉스',
 'content': '외국인 투자자는 05일 거래소에서 SK하이닉스, 삼성SDI, SK바이오팜 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 SK하이닉스, 삼성SDI, SK바이오팜, 삼성중공업, 두산에너빌리티, 한화오션, 에코프로머티, LS ELECTRIC, 두산, 한국전력등이다.이중에 전기,전자 업종에 속한 종목이 6개 포함되어 있다.이날 외국인 투자자가 순매수한 종목들 중에 SK하이닉스, 삼성SDI, SK바이오팜 등은 전일 대비 주가가 상승했다.[08월05일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'}

In [113]:
top_n_original = [get_full_article_from_chroma(idx,kind=test_ticker,vectordb=vectordb) for idx in original_idxs]

In [114]:
top_n_original[0]

{'title': '24일, 외국인 거래소에서 한화오션(+6.35%), SK하이닉스(+0.19%) 등 순매수',
 'url': 'https://www.hankyung.com/article/202507240571L',
 'Date': '2025-07-24',
 'ticker': 'SK하이닉스',
 'content': '외국인 투자자는 24일 거래소에서 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 한화오션, SK하이닉스, 두산에너빌리티, LG에너지솔루션, 기아, 한화비전, 한화에어로스페이스, 삼성전자, 삼성바이오로직스, LG화학등이다.이중에 전기,전자 업종에 속한 종목이 6개 포함되어 있다.한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했고, 기아, 삼성전자, 현대차 등은 주가가 하락했다.[07월24일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'}

In [115]:
original_contents = list(map(lambda x: x['content'],top_n_original))

In [116]:
total_contents = ''.join(original_contents)

In [117]:
total_contents

'외국인 투자자는 24일 거래소에서 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 한화오션, SK하이닉스, 두산에너빌리티, LG에너지솔루션, 기아, 한화비전, 한화에어로스페이스, 삼성전자, 삼성바이오로직스, LG화학등이다.이중에 전기,전자 업종에 속한 종목이 6개 포함되어 있다.한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했고, 기아, 삼성전자, 현대차 등은 주가가 하락했다.[07월24일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.기관 투자자는 30일 거래소에서 삼성전자, 현대차, 삼성전기 등을 중점적으로 사들인 것으로 나타났다.기관 투자자의 순매수 상위 20개 종목은 삼성전자, 현대차, 삼성전기, KODEX 레버리지, 삼성SDI, SK하이닉스, 한화에어로스페이스, 카카오, LG에너지솔루션, 기아등이다.이중에 전기,전자 업종에 속한 종목이 8개 포함되어 있다.삼성전자, 현대차, 삼성전기 등은 전일 대비 주가가 상승했고, 한화에어로스페이스, 한국전력 등은 주가가 하락했다.[07월30일]거래소 기관 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 17일 거래소에서 SK하이닉스, 카카오페이, NAVER 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 SK하이닉스, 카카오페이, NAVER, 두산에너빌리티, HD현대미포, 삼성에스디에스, 하나금융지주, HD현대일렉트릭, 현대차, 풍산등이다.이중에 운수장비 업종에 속한 종목이 4개 포함되어 있다.HD현대미포, 하나금융지주, 현대차 등은 전일 대비 주가가 상승했고, SK하이닉스, 카카오페이, NAVER 등은 주가가 하락했다.[07월17일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.기관 투자자는 05일 거래소에서 SK하이닉스, KODEX 200선물인버스2X, 현대모비스 등을 중점적으로 매도한 것으로 나타났다.기관 투자자의 순매도 상위 20개 종목은 SK하이닉스, KODEX 200선물인버스2X, 현대모비스, 기아, TIGER CD1년금리액티브(합성), NAVER, KODEX 인버스, POSCO홀딩스, 현대글로비스, KODEX 200타겟위클리커버드콜등이다.이중에 운수장비 업종에 속한 종목이 3개 포함되어 있다.SK하이닉스, 현대모비스, TIGER CD1년금리액티브(합성) 등은 전일 대비 주가가 상승했고, KODEX 200선물인버스2X, 기아, NAVER 등은 주가가 하락했다.[08월05일]거래소 기관 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 04일 거래소에서 SK하이닉스, 한화오션, NAVER 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 SK하이닉스, 한화오션, NAVER, 삼성전자, KT&G, 삼성SDI, HD현대인프라코어, 하나금융지주, POSCO홀딩스, 대한조선등이다.이중에 전기,전자 업종에 속한 종목이 5개 포함되어 있다.NAVER, 삼성전자, KT&G 등은 전일 대비 주가가 상승했고, 한화오션, POSCO홀딩스, 대한조선 등은 주가가 하락했다.[08월04일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.기관 투자자는 29일 거래소에서 KODEX 레버리지, LG에너지솔루션, 현대로템 등을 중점적으로 사들인 것으로 나타났다.기관 투자자의 순매수 상위 20개 종목은 KODEX 레버리지, LG에너지솔루션, 현대로템, SK하이닉스, 두산에너빌리티, 한화에어로스페이스, KODEX 200, 한전기술, 에이피알, 한국전력등이다.이중에 운수장비 업종에 속한 종목이 4개 포함되어 있다.KODEX 레버리지, LG에너지솔루션, 현대로템 등은 전일 대비 주가가 상승했고, 한국전력 등은 주가가 하락했다.[07월29일]거래소 기관 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 18일 거래소에서 SK하이닉스, 삼양식품, POSCO홀딩스 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 SK하이닉스, 삼양식품, POSCO홀딩스, 한화오션, 현대로템, 삼성전자우, 유한양행, 삼성바이오로직스, 현대차, 한국콜마등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.POSCO홀딩스, 현대차, 카카오페이 등은 전일 대비 주가가 상승했고, SK하이닉스, 삼양식품, 한화오션 등은 주가가 하락했다.[07월18일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 16일 거래소에서 삼성전자, SK하이닉스, 한화에어로스페이스 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 삼성전자, SK하이닉스, 한화에어로스페이스, 롯데지주, 달바글로벌, 삼성전자우, 이수페타시스, SK스퀘어, 현대로템, 효성중공업등이다.이중에 전기,전자 업종에 속한 종목이 6개 포함되어 있다.삼성전자, 한화에어로스페이스, 삼성전자우 등은 전일 대비 주가가 상승했고, SK하이닉스, 롯데지주, 달바글로벌 등은 주가가 하락했다.[07월16일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 25일 거래소에서 NAVER, SK하이닉스, 삼성중공업 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 NAVER, SK하이닉스, 삼성중공업, LG에너지솔루션, 삼성SDI, 효성중공업, 신한지주, 한올바이오파마, 두산, SK텔레콤등이다.이중에 전기,전자 업종에 속한 종목이 8개 포함되어 있다.NAVER, 효성중공업, 신한지주 등은 전일 대비 주가가 상승했고, SK하이닉스, 삼성중공업, LG에너지솔루션 등은 주가가 하락했다.[07월25일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 28일 거래소에서 두산에너빌리티, LG에너지솔루션, 삼성중공업 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 두산에너빌리티, LG에너지솔루션, 삼성중공업, SK하이닉스, 현대차, 하나금융지주, NAVER, KB금융, 삼성SDI, HD한국조선해양등이다.이중에 전기,전자 업종에 속한 종목이 4개 포함되어 있다.LG에너지솔루션, 현대차, NAVER 등은 전일 대비 주가가 상승했고, 두산에너빌리티, 삼성중공업, SK하이닉스 등은 주가가 하락했다.[07월28일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.기관 투자자는 23일 거래소에서 넷마블, 한국전력, 삼성전자 등을 중점적으로 매도한 것으로 나타났다.기관 투자자의 순매도 상위 20개 종목은 넷마블, 한국전력, 삼성전자, HD현대일렉트릭, 에이피알, 카카오, 두산, 삼성물산, 현대건설, LIG넥스원등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.한국전력, 삼성전자, HD현대일렉트릭 등은 전일 대비 주가가 상승했고, 넷마블, 카카오, 두산 등은 주가가 하락했다.[07월23일]거래소 기관 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 01일 거래소에서 두산에너빌리티, SK하이닉스, 한화시스템 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 두산에너빌리티, SK하이닉스, 한화시스템, 한화에어로스페이스, HD현대미포, 삼성전자, 삼성SDI, 에이피알, 대한조선, HD현대중공업등이다.이중에 전기,전자 업종에 속한 종목이 5개 포함되어 있다.한화시스템, 대한조선 등은 전일 대비 주가가 상승했고, 두산에너빌리티, SK하이닉스, 한화에어로스페이스 등은 주가가 하락했다.[08월01일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 23일 거래소에서 삼성전자, SK하이닉스, 두산에너빌리티 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 삼성전자, SK하이닉스, 두산에너빌리티, 한화솔루션, 삼성SDI, NAVER, 한화오션, 삼성바이오로직스, 코웨이, 삼성중공업등이다.이중에 전기,전자 업종에 속한 종목이 5개 포함되어 있다.삼성전자, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했고, NAVER, 한화오션, 삼성중공업 등은 주가가 하락했다.[07월23일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 05일 거래소에서 SK하이닉스, 삼성SDI, SK바이오팜 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 SK하이닉스, 삼성SDI, SK바이오팜, 삼성중공업, 두산에너빌리티, 한화오션, 에코프로머티, LS ELECTRIC, 두산, 한국전력등이다.이중에 전기,전자 업종에 속한 종목이 6개 포함되어 있다.이날 외국인 투자자가 순매수한 종목들 중에 SK하이닉스, 삼성SDI, SK바이오팜 등은 전일 대비 주가가 상승했다.[08월05일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.2분기 실적 발표 시즌에 본격 돌입하면서 주도주의 성적표가 윤곽을 드러내고 있다. 코스피지수가 단기 급등하며 밸류에이션(실적 대비 주가 수준)이 높아진 만큼 실적이 주가 향방을 가를 주요 변수로 작용할 것이라는 분석이 나온다.BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세기관 투자자는 31일 거래소에서 SK하이닉스, KODEX 200선물인버스2X, 두산 등을 중점적으로 사들인 것으로 나타났다.기관 투자자의 순매수 상위 20개 종목은 SK하이닉스, KODEX 200선물인버스2X, 두산, 두산에너빌리티, 한화시스템, 삼양식품, SOL 조선TOP3플러스, LS ELECTRIC, 하이브, 한미반도체등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.SK하이닉스, KODEX 200선물인버스2X, 두산 등은 전일 대비 주가가 상승했고, 메리츠금융지주 등은 주가가 하락했다.[07월31일]거래소 기관 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.삼성·SK·현대차·LG 등 4대 그룹 중심 투자 계획 취합추가 펀드도 논의…정부 조달자금도 투입 가능성반도체·방산·금융·조선\n증권사 리서치센터장 10명의 추천종목\r\n                                \n\n\n\n21일 서울 여의도 한국거래소 전광판에 종가가 표시되고 있다./임형택 기자“지금 들어가도 될까.”코스피지수가 3200을 넘어섰지만 아직 주식을 사지 않은 투자자들의 고민이 깊어지고 있다. 기존 대장주들이 앞으로도 더 오를 수 있을 것이라는 기대감과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있다.특히 정부의 세금 정책이 엇박자를 보이면서 실망감에 주가가 다시 출렁이자 투자자들은 진입 시점을 저울질하고 있다. 상승과 변동성의 갈림길에서 한경비즈니스는 국내 주요 증권사 리서치센터장 10명에게 향후 코스피 5000시대 또는 추세적 상승을 이끌 주도주를 물었다. 센터장들은 ‘명실상부한 주도주’라 불릴 만한 11개 기업을 꼽았다. 센터장들이 추천한 11개 기업은 코스피 전체 시가총액의 3분의 1을 떠받치고 있다. 키워드는 ‘겹호재’다.이들은 기업의 본질적인 경쟁력과 함께 미국 정책 변화에 따른 호재를 동시에 갖추고 있다. 실적 기반의 성장 가능성은 물론이고 시장 대비 높은 상승률과 미국발 호재를 반영할 수 있는 종목이다.상법 개정 등으로 \n코리아 디스카운트 해소 국면 진입\n\n코스피 5000은 물론\n1만까지 점치는 전문가도 나와\n\n기업실적 향상 없는\n주가 상승은 결국 거품으로 끝나한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n에이치시티는 하이닉스 품질보증부문에서 분리된 시험·인증 및 측정기기 교정 전문기업으로, 스마트폰·통신장비뿐 아니라 전기차·배터리·방산 등으로 사업을 확대 중이다.2분기 매출 292억원, 영업이익 50억원으로 전년 대비 각각 22%, 30% 증가하며 호실적을 기록했다.정보통신 신제품 수주와 전기차 전장품 시험인증 매출이 성장 요인으로, 실적 발표 후 주가는 30% 이상 급등했다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 하나마이크론 한화오션 포스코엠텍 대덕전자한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n한화엔진이 또다시 어닝서프라이즈를 기록했다. 2025년 2분기 실적은 매출액 3,877억 원, 영업이익 338억 원으로 각각 컨센서스를 14%, 35% 상회했다.수주 기반의 안정적인 성장과 선가 상승에 따른 마진 개선이 실적에 반영된 것으로 보인다.주가는 전거래일 기준으로 4일 연속 상승하며 52주 신고가를 기록했으며, 외국인과 기관의 동반 순매수가 이어지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.카카오페이 산일전기 한국전력 SK하이닉스 HJ중공업올해 상반기 증시 상승은 주로 대형주 중심으로 나타났지만, 하반기에는 실적이 개선되고 있는 저평가 중소형주가 주목받을 것이란 전망이 나오고 있다. 특히 시가총액 1조원 안팎의 종목 중 주가수익비율(PER)이 낮고 실적 개선세가 뚜렷한 기업들이 투자 유망군으로 꼽힌다.이러한 중소형주 중심 전략은 ETF 상품으로도 출시돼 운용되고 있으며, 주요 포트폴리오는 수출 기반 제조업, 전력기기, 금융업종 등 실적 개선 가능성이 높은 분야에 집중돼 있다.특히, 부동산 규제와 증시 부양책이 동시에 진행되는 정책 환경 속에서 증권주 등 금융업종의 수혜 가능성도 제기되고 있다. 자산 이동 흐름이 부동산에서 증시로 전환될 수 있다는 분석이다.한편, 스탁론에 대한 관심이 날로높아지고 있다. 모처럼 잡은 투자기회를 놓치지 않으려는 투자자들이 주식매입을 위해 더 많은 자금을 활용할 수 있는 스탁론으로 눈길을 돌리고 있기 때문이다. 현 주가는 실적을 따라가지 못하고 있는 상황으로, 밸류에이션 리레이팅이 필요한 시기라는 평가도 나오고 있다.\n\n\n\n\n \n\n◆ 하이스탁론, 연 4%대 업계 최저금리로 추가 투자금은 물론 신용미수 대환까지!<하이스탁론>에서 누구나 부담 없이 스탁론을 경험할 수 있도록 연 4%대 최저금리 상품을 출시했다. 주식매입 용도는 물론 증권사 미수/신용 대환도 가능하며 신용등급 차등 없이 자기자본 포함 최대 4배까지 활용할 수 있다.이와 함께 DSR 한도 때문에 기존 스탁론 이용이 어려웠던 투자자들은 위한 DSR 무관 상품도 취급 중이다. 또한 장중 거래가 어려웠던 투자자를 위한 대체거래소(NXT) 거래도 가능해졌다.<하이스탁론>의 새로운 상품에 대해 자세히 알고 싶은 투자자는 고객상담센터(1599-0313)로 연락하면 대출 여부와 상관없이 24시간 언제든 전문상담원과 편리한 상담이 가능하다.○ 연 4%대 업계 최저금리 상품 출시○ 대체거래소(NXT) 거래 가능!○ 21년 연속 시장 점유율 1위, 16년 연속 대한민국퍼스트브랜드 대상○ 증권사 신용/미수 실시간 상환, 한종목 100% 집중 투자○ 믿을 수 있는 상담품질보증제※하이스탁론상담센터 : 1599-0313바로가기:https://www.hisl.co.kr/0313◆ 현 시각 관심종목 Top 10 : SK하이닉스, POSCO홀딩스, 포바이포, 한국전력, YGPLUS, 네이처셀, LS머트리얼즈, 영풍, 송원산업, 한국비엔씨무료상담올해 상반기 증시 상승은 주로 대형주 중심으로 나타났지만, 하반기에는 실적이 개선되고 있는 저평가 중소형주가 주목받을 것이란 전망이 나오고 있다. 특히 시가총액 1조원 안팎의 종목 중 주가수익비율(PER)이 낮고 실적 개선세가 뚜렷한 기업들이 투자 유망군으로 꼽힌다.이러한 중소형주 중심 전략은 ETF 상품으로도 출시돼 운용되고 있으며, 주요 포트폴리오는 수출 기반 제조업, 전력기기, 금융업종 등 실적 개선 가능성이 높은 분야에 집중돼 있다.특히, 부동산 규제와 증시 부양책이 동시에 진행되는 정책 환경 속에서 증권주 등 금융업종의 수혜 가능성도 제기되고 있다. 자산 이동 흐름이 부동산에서 증시로 전환될 수 있다는 분석이다.한편, 스탁론에 대한 관심이 날로높아지고 있다. 모처럼 잡은 투자기회를 놓치지 않으려는 투자자들이 주식매입을 위해 더 많은 자금을 활용할 수 있는 스탁론으로 눈길을 돌리고 있기 때문이다. 현 주가는 실적을 따라가지 못하고 있는 상황으로, 밸류에이션 리레이팅이 필요한 시기라는 평가도 나오고 있다.\n\n\n\n\n \n\n◆ 하이스탁론, 연 4%대 업계 최저금리로 추가 투자금은 물론 신용미수 대환까지!<하이스탁론>에서 누구나 부담 없이 스탁론을 경험할 수 있도록 연 4%대 최저금리 상품을 출시했다. 주식매입 용도는 물론 증권사 미수/신용 대환도 가능하며 신용등급 차등 없이 자기자본 포함 최대 4배까지 활용할 수 있다.이와 함께 DSR 한도 때문에 기존 스탁론 이용이 어려웠던 투자자들은 위한 DSR 무관 상품도 취급 중이다. 또한 장중 거래가 어려웠던 투자자를 위한 대체거래소(NXT) 거래도 가능해졌다.<하이스탁론>의 새로운 상품에 대해 자세히 알고 싶은 투자자는 고객상담센터(1599-0313)로 연락하면 대출 여부와 상관없이 24시간 언제든 전문상담원과 편리한 상담이 가능하다.○ 연 4%대 업계 최저금리 상품 출시○ 대체거래소(NXT) 거래 가능!○ 21년 연속 시장 점유율 1위, 16년 연속 대한민국퍼스트브랜드 대상○ 증권사 신용/미수 실시간 상환, 한종목 100% 집중 투자○ 믿을 수 있는 상담품질보증제※하이스탁론상담센터 : 1599-0313바로가기:https://www.hisl.co.kr/0313◆ 현 시각 관심종목 Top 10 : SK하이닉스, POSCO홀딩스, 포바이포, 한국전력, YGPLUS, 네이처셀, LS머트리얼즈, 영풍, 송원산업, 한국비엔씨무료상담백문불여일견(百聞不如一見). 백 번 듣는 것보다 한 번 보는 게 낫다는 말이다. 가짜뉴스 홍수 속 정보의 불균형을 조금이라도 해소하기 위해 주식 투자 경력 19년의 ‘전투개미’가 직접 상장사를 찾아간다. 회사의 사업 현황을 살피고 경영진을 만나 투자자들의 궁금증을 해결한다. 전투개미는 평소 그가 ‘주식은 전쟁터’라는 사고에 입각해 매번 승리하기 위해 주식 투자에 임하는 상황을 빗대 사용하는 단어다. 주식 투자에 있어서 그 누구보다 손실의 아픔이 크다는 걸 잘 알기에 오늘도 개인투자자 입장에서 기사를 쓴다. <편집자주>\n\n\n\n\n김진동 대표가 유기금속 제조 플랜트에서 사업 내용을 설명하고 있다. 천안=윤현주 기자\n\n                “전고체 배터리 핵심 소재와 석유화학 촉매 사업이 미래 먹거리입니다. 사업 다변화로 글로벌 소재 전문기업으로 우뚝 서겠습니다.”김진동 레이크머티리얼즈 대표(1966년생)는 지난 1일 기자와 만나 신성장동력에 대해 이같이 밝혔다. 이 회사는 유기금속화합물 설계 및 초고순도 화합물 트리메탈알루미늄(TMA) 제조기술을 기반으로 반도체·태양광·LED·메탈로센촉매·디스플레이 등의 소재로 사용되는 초고순도 유기금속화합물을 개발 및 공급한다. 유기금속화합물이란 유기물 분자(리간드)와 금속 원자가 결합해 만들어진 화합물(케미칼)로 산업적 응용성을 강조해 유기금속소재 또는 전구체(프리커서)라고 한다. \n                    \n\n\n\n충청남도 천안시 동남구 성남면5산단4로 41에 위치한 레이크머티리얼즈 천안사업장. 천안=윤현주 기자\n\n                2010년 5월 13일 설립했는데, 이듬해 국내 유일 TMA 국산화에 성공했다. 2014년 1월 중국 법인을 세웠고 2016년 12월 1천만불 수출의 탑을 수상한다. 2017년 대만 지점을 설립했고, 2018년 7월과 8월 일본 키옥시아·삼성전자에 반도체 소재를 공급하기 시작한다. 2023년 12월 5천만불 수출의 탑을 수상했고 지난해 8월 코스닥 라이징스타로 선정됐다.\n                    \n\n\n\n환경안전팀 직원들이 업무 회의를 하고 있다. 천안=윤현주 기자한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n에이치시티는 하이닉스 품질보증부문에서 분리된 시험·인증 및 측정기기 교정 전문기업으로, 스마트폰·통신장비뿐 아니라 전기차·배터리·방산 등으로 사업을 확대 중이다.2분기 매출 292억원, 영업이익 50억원으로 전년 대비 각각 22%, 30% 증가하며 호실적을 기록했다.정보통신 신제품 수주와 전기차 전장품 시험인증 매출이 성장 요인으로, 실적 발표 후 주가는 30% 이상 급등했다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.에이치시티 삼성전기 이수페타시스 LG이노텍 파크시스템스한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n에이치시티는 하이닉스 품질보증부문에서 분리된 시험·인증 및 측정기기 교정 전문기업으로, 스마트폰·통신장비뿐 아니라 전기차·배터리·방산 등으로 사업을 확대 중이다.2분기 매출 292억원, 영업이익 50억원으로 전년 대비 각각 22%, 30% 증가하며 호실적을 기록했다.정보통신 신제품 수주와 전기차 전장품 시험인증 매출이 성장 요인으로, 실적 발표 후 주가는 30% 이상 급등했다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.두산테스나 삼성전기 삼성SDI 두산에너빌리티 네이처셀한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n에이치시티는 하이닉스 품질보증부문에서 분리된 시험·인증 및 측정기기 교정 전문기업으로, 스마트폰·통신장비뿐 아니라 전기차·배터리·방산 등으로 사업을 확대 중이다.2분기 매출 292억원, 영업이익 50억원으로 전년 대비 각각 22%, 30% 증가하며 호실적을 기록했다.정보통신 신제품 수주와 전기차 전장품 시험인증 매출이 성장 요인으로, 실적 발표 후 주가는 30% 이상 급등했다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.SK하이닉스 NAVER 포바이포 동성화인텍 하이드로리튬새 정부의 증시 부양책 기대로 국내 증시가 파죽지세로 달리고 있습니다. 코스피지수는 이재명 대통령이 당선된 후 ‘삼천피’(코스피 3000)를 탈환했고, 3200선까지 터치했습니다. 한경닷컴은 여의도 증권가 전문가들에게 하반기 증시 전망에 관해 묻고 세 편에 걸쳐 주도주와 수급 등 전망에 대해 짚었습니다. [편집자주]\n\n\n\n\n사진=한경 DB반도체·방산·금융·조선\n증권사 리서치센터장 10명의 추천종목\r\n                                \n\n\n\n21일 서울 여의도 한국거래소 전광판에 종가가 표시되고 있다./임형택 기자“지금 들어가도 될까.”코스피지수가 3200을 넘어섰지만 아직 주식을 사지 않은 투자자들의 고민이 깊어지고 있다. 기존 대장주들이 앞으로도 더 오를 수 있을 것이라는 기대감과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있다.특히 정부의 세금 정책이 엇박자를 보이면서 실망감에 주가가 다시 출렁이자 투자자들은 진입 시점을 저울질하고 있다. 상승과 변동성의 갈림길에서 한경비즈니스는 국내 주요 증권사 리서치센터장 10명에게 향후 코스피 5000시대 또는 추세적 상승을 이끌 주도주를 물었다. 센터장들은 ‘명실상부한 주도주’라 불릴 만한 11개 기업을 꼽았다. 센터장들이 추천한 11개 기업은 코스피 전체 시가총액의 3분의 1을 떠받치고 있다. 키워드는 ‘겹호재’다.이들은 기업의 본질적인 경쟁력과 함께 미국 정책 변화에 따른 호재를 동시에 갖추고 있다. 실적 기반의 성장 가능성은 물론이고 시장 대비 높은 상승률과 미국발 호재를 반영할 수 있는 종목이다.[한경ESG] 글로벌 리더 인터뷰 - 다르시 드라우트 베하레스 박사\n                    \n\n\n\n다르시 드라우트 베하레스 박사가 <한경ESG>와 인터뷰하고 있다. 사진=서범세 기자※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.\n\n\n\n\n\n                투자수익률 상위 1％ 고수들이 21일 오전 SK하이닉스를 집중 매수하고 있다. 반면 삼성중공업은 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 SK하이닉스, 한화엔진, 한국전력 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％에 속하는 투자자의 매매동향을 취합한 결과다.오전 10시 현재 SK하이닉스가 이전 거래일보다 1.67% 올랐고, 한화엔진이 8.06% 상승했다. 한국전력은 0.97% 강세다. SK하이닉스는 미 투자은행(IB) 골드만삭스의 투자의견 하향 조정으로 지난 17일 주가가 9% 급락한 뒤 반등을 시도하는 모습이다. 한화엔진은 2분기 친환경 엔진 사업의 호조 기대로 지난 8일 이후 상승 탄력을 받고 있다.\n                    \n\n\n\n\n                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 삼성중공업, 두산에너빌리티, 펩트론 순이다. 주가는 각각 직전 거래일 대비 2.45%, 3.24%, 0.34% 변동했다. 삼성중공업과 두산에너빌리티는 최근 3개월간 주가가 크게 오르며 이익실현을 자극한 것으로 보인다.\n                    \n\n\n\n\n                이태호 기자 thlee@hankyung.com최근 글로벌 리튬 관련 산업이 회복세를 보이면서, 리튬 테마 종목 전체가 강한 상승 흐름을 나타냈고, 이에 연동해 미래나노텍도 연일 눈에 띄는 반등 국면을 맞았다. 특히 리튬 테마가 급등한 하루에 관련 주가가 함께 크게 오르며 주목받았으며, 전 거래일 대비 상승률이 한 자릿수에서 두 자릿수 수준까지 확대되었다는 평가다. 이와 함께 거래량도 급증하며, 시장 관심이 집중되고 있음을 보여주었다.투자자 수급 구조를 살펴보면, 리튬 테마 전반에서 기관이 테마 종목 전체를 중심으로 수백억 원대 매수에 나선 반면, 외국인과 개인은 일부 매도에 나서며 투자 중립적 분위기가 형성되었다. 그러나 미래나노텍은 테마 내에서도 퀀트 기반 재무 점수 상위권에 위치, 성장성과 안정성, 수익성 지표에서 긍정 평가를 받으면서 상대적으로 매수세가 몰린 것으로 보인다.지난 며칠간 미래나노텍은 세 거래일 연속 상승세를 이어가며, 테마 중심 흐름에 맞춰 주가가 1만 원선을 회복하거나 일시 상회하며 지지선을 다지는 모습을 보였다. 외국인의 순매도에도 불구하고 개인투자자의 매수 열기가 거래량 증가로 이어졌고, 이는 상승 흐름이 단기간에 그치지 않을 수 있음을 시사한다.이 같은 주가 흐름은 단순히 테마 모멘텀에 그치지 않고, 업종 내 밸류에이션 매력이 반영된 결과라는 분석도 있다. 경쟁 종목 대비 상대적으로 PER가 낮고 재무안정성이 양호한 점이 시장에서 투자 매력도를 더했다는 평가가 많다.결과적으로, 리튬 관련 업황 회복과 시장의 펀더멘털 기반 관심이 맞물리며 미래나노텍은 최근 뚜렷한 상승 흐름을 형성했다. 다만 외국인 매도세와 테마 자체의 등락성도 병존하는 만큼, 향후 흐름이 지속될지는 시장 체력과 수급 변화에 따라 달라질 가능성이 있다. 앞으로도 기술지표와 수급 방향, 테마 전체 흐름을 함께 주시할 필요가 있다.삼성전자, 현대차, 한화오션, SK하이닉스, 기아무료상담사진=게티이미지뱅크 \n\n                외국인 투자자가 국내 증시에서 지난달에만 6조원 넘는 주식을 사들인 가운데 삼성전자를 집중 매집한 것으로 나타났다. 반면 외국계 증권사가 실적 성장에 의문을 제기하며 투자의견을 낮춘 SK하이닉스와 네이버에 대해서는 매도에 나섰다. 1일 한국거래소에 따르면 외국인은 지난달 유가증권시장과 코스닥시장에서 총 6조2621억원어치 주식을 사들였다. 외국인은 지난달 23거래일 중 5거래일을 제외하고 전부 \'바이 코리아\'(Buy Korea)였다.\n                    \n\n\n\n사진=게티이미지뱅크SK·신세계·네이버, 연예인 자녀 배출\n최태원 SK그룹 회장, 직접 홍보 나서기도\n\nMZ세대 특성도 반영된 변화\n자신이 가치 있고 특별하다고 여기는 경험에 \n적극적으로 투자하는 경향 짙어\r\n                                \n[커버스토리 - “아빠 회사 안 가요” 다이아 수저들의 반란]반도체·방산·금융·조선\n증권사 리서치센터장 10명의 추천종목\r\n                                \n\n\n\n21일 서울 여의도 한국거래소 전광판에 종가가 표시되고 있다./임형택 기자“지금 들어가도 될까.”코스피지수가 3200을 넘어섰지만 아직 주식을 사지 않은 투자자들의 고민이 깊어지고 있다. 기존 대장주들이 앞으로도 더 오를 수 있을 것이라는 기대감과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있다.특히 정부의 세금 정책이 엇박자를 보이면서 실망감에 주가가 다시 출렁이자 투자자들은 진입 시점을 저울질하고 있다. 상승과 변동성의 갈림길에서 한경비즈니스는 국내 주요 증권사 리서치센터장 10명에게 향후 코스피 5000시대 또는 추세적 상승을 이끌 주도주를 물었다. 센터장들은 ‘명실상부한 주도주’라 불릴 만한 11개 기업을 꼽았다. 센터장들이 추천한 11개 기업은 코스피 전체 시가총액의 3분의 1을 떠받치고 있다. 키워드는 ‘겹호재’다.이들은 기업의 본질적인 경쟁력과 함께 미국 정책 변화에 따른 호재를 동시에 갖추고 있다. 실적 기반의 성장 가능성은 물론이고 시장 대비 높은 상승률과 미국발 호재를 반영할 수 있는 종목이다.전송종목 : 비에이치, 현대이지웰, 파트론, 한라IMS, 네오팜한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.SK하이닉스 카카오페이 다날 한화시스템 솔브레인SK하이닉스가 최근 AI 수요 호조와 HBM(고대역폭 메모리) 시장 지배력을 바탕으로 주가 강세 흐름을 유지하고 있다. 증권업계에서는 글로벌 메모리 업황 회복 속에서 SK하이닉스가 현대판 퍼포먼스 리더 중 하나란 평가가 나온다.1분기 실적 발표에서 매출과 영업이익이 역대 두 번째 기록 수준으로 호조를 보였으며, 영업이익률도 탄탄한 흐름을 이어갔다. 특히 AI 서버 수요 확대로 HBM3E 등 고부가 제품 비중이 크게 확대된 점이 실적을 견인했다.시장 조사기관에 따르면 SK하이닉스는 글로벌 DRAM 점유율에서 선두 자리를 꿰찼으며, HBM 시장에서도 절반에 달하는 비중을 확보한 것으로 파악된다. 이는 삼성전자의 실적 둔화와 대비되며, 차별적 경쟁 우위로 받아들여진다.주가 역시 강한 랠리 후에도 추가 상승 여력을 인정받고 있다. 최근 글로벌 반도체 업종 내에서 SK하이닉스 주가는 업계 평균을 웃도는 흐름을 보였고, 일부 증권사는 목표주가를 상향하며 매수 의견을 강화했다.다만 증권업계에서는 미·중 무역 리스크, 미국의 수출 규제 가능성, 단기 수요 사이클 둔화 등이 향후 주요 변수로 꼽히고 있다. 특히 일부 고객의 재고 선매입 현상이 2분기 수요 변동성을 키울 수 있다는 우려도 제기된다.휴림로봇, GS, 현대차, 삼성물산, 한미반도체무료상담한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 SK하이닉스 삼성전기 LG이노텍 삼성에스디에스SK하이닉스 2분기 최대실적\n"하반기 HBM 더 좋다"\n\n외국계IB, 반도체 저승사자라 불려\n업계, "의도적이라는 확증 없어"\r\n                                \n\n\n\nSK하이닉스 이천 M14 공장./SK하이닉스“고대역폭메모리(HBM)의 수요 성장성은 의심할 여지가 없다.”SK하이닉스가 내년 ‘HBM 공급과잉’과 가격 하락으로 실적이 꺾일 수 있다는 시장의 우려에 대해 내놓은 답이다. 골드만삭스가 투자의견을 하향한 지 딱 일주일 만이다. 골드만삭스는 7월 17일 SK하이닉스에 대한 투자의견을 중립으로 하향하고 목표주가를 31만원으로 제시했다. “내년 처음으로 HBM 가격이 두 자릿수 %까지 하락세를 보일 수 있다”는 것이 골드만삭스의 의견이다.시장 경쟁이 격화하면 HBM 가격 협상력이 점차 공급자에서 수요자로 넘어가면서 SK하이닉스도 HBM 가격 하락 압력을 받을 것이란 얘기다.골드만삭스는 “SK하이닉스는 주요 고객사(엔비디아) 매출 비중이 높은 편”이라며 그만큼 마진 손실 압력도 클 것이라고 전망했다. 이 보고서로 인해 그날 SK하이닉스 주가는 9% 폭락했다. 시가총액은 하루 만에 19조3000억원 증발했다. 일주일 뒤인 24일 SK하이닉스는 2분기 실적을 발표했다. 결과는 역대 최고. 분기 영업이익이 처음으로 9조원을 넘어섰다.  SK하이닉스는 2분기 실적발표 콘퍼런스콜에서 “향후 HBM 시장은 성장 초기의 급격한 성장률까지는 아니더라도 AI 기술의 빠른 발전과 확산으로 고객들의 풀이 확대되고 있고 신제품과 새로운 서비스가 계속해서 출시된다는 점을 고려할 때 앞으로도 높은 성장성을 지속할 것”이라고 말했다.SK하이닉스는 올해 투자 규모를 기존 계획보다 더 늘릴 계획이다. 특히 HBM 생산을 위한 장비 투자가 늘어날 것이라고 밝혔다. 내년 HBM 공급에 대한 가시성이 확보됐다는 뜻이다.SK하이닉스는 올해 HBM 물량을 이미 ‘솔드아웃(완판)’한 상태다. 현재 주력인 HBM3E(5세대) 12단 제품을 엔비디아를 비롯한 주요 고객사들에 공급 중이다. 내년 물량의 ‘완판’ 여부는 올해 하반기 내에 결정될 것으로 보인다.  ‘반도체 겨울’ 진단 계속 빗나간다한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\nLG에너지솔루이 테슬라와 5.9조원 규모 LFP 배터리 공급 계약을 체결했다. 이번 수주는 ESS용 배터리로 3년간 공급하며 최대 7년까지 연장 가능하다.2025년 5월부터 미시간 홀랜드 공장에서 LFP 생산을 시작한 가운데, 연매출 대비 7.7% 규모로 LFP 시장 진출 성과를 입증했다.중국산 배터리 제한으로 국내 업체 반사수혜 기대가 커졌으나, 공시 후 주가는 보합권

In [118]:
len(total_contents)

24304

## 요약하기

### 요약함수 호출
- 가져온 원 본문을 전부 적용하기

In [119]:
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

In [124]:
def summarize_top_articles_2(total_contents: str,ticker:str,max_iters:int) -> pd.DataFrame:
    agent = NewsSummaryAgent(max_iters=max_iters)
    runnable = build_summary_graph(agent)

    rows = []
    doc = total_contents

    state = {"article": doc, "summary": "", "feedback": "", "iteration": 0}
    result = runnable.invoke(state)

    print("✅ 실행 결과 키:", result.keys())
    # 여기서 final_summary 반드시 존재해야 함(위 패치 기준)
    final_summary = result.get("final_summary")
    if not final_summary:
        print("❌ final_summary 없음. 디버그용 전체 상태:", result)
        # 계속 진행할지, 실패로 표기할지 선택

    rows.append({
        "ticker": ticker,
        "date": '2025-07-30', # 위 조회 기준일자로 연동시켜서 바꿀 예정
        "summary": final_summary,
        "feedback": result.get("last_feedback", "피드백 없음"),
    })

    return pd.DataFrame(rows)

In [125]:
result_df = summarize_top_articles_2(total_contents,ticker=test_ticker,max_iters=5)

summart : ✅ 주요 요약
- 외국인 투자자, 특정 종목 집중 매수 및 매도
  외국인 투자자는 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도한 것으로 나타났다.

- 기관 투자자, 전기·전자 업종에 집중
  기관 투자자는 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했다.

- 코스피지수 상승, 투자자 고민 증가
  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있으며, 기존 대장주들의 추가 상승 가능성과 부담감이 동시에 작용하고 있다.

🔑 키워드
- 외국인 투자자
- 기관 투자자
- SK하이닉스
- 삼성전자
- 코스피지수
- 전기·전자 업종
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약이 원문 기사에서 다루어진 모든 세부 사항을 정확하게 반영하지 못하고 있습니다. 예를 들어, 외국인과 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보가 일부 누락되었습니다.] </reason>
- 포괄성: 부족함 <reason> [기사의 주요 내용 중 일부가 요약에 포함되지 않았습니다. 예를 들어, 특정 날짜에 대한 투자자 행동이나 주가 변동에 대한 세부 정보가 누락되었습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하는 것이 아니라 다양한 종목과 투자자 행동에 대한 정보가 포함되어 있습니다.] </reason>

**피드백:**
요약의 정확성과 포괄성을 개선하기 위해 원문 기사에서 다루어진 모든 주요 세부 사항을 포함하도록 해야 합니다. 특히, 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보와 주가 변동에 대한 세부 사항을 추가하는 것이 필요합니다. 또한, 일관성을 유지하기 위해 특정 종목에 대한 정보가 아닌 전체적인 투자자 행동과 시장 상황을 포괄적으로 다루는 것이 중요합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **외국인 투자자, 다양한 종목 매수 및 매도**\n  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있습니다.\n\n- **기관 투자자, 전기·전자 업종에 집중**\n  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.\n\n- **코스피지수 상승, 투자자 고민 증가**\n  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.\n\n- **주요 종목의 주가 변동**\n  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.\n\n🔑 키워드\n- 외국인 투자자\n- 기관 투자자\n- SK하이닉스\n- 삼성전자\n- 코스피지수\n- 전기·전자 업종\n\n**개선 포인트:**\n- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.\n- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.\n- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약이 원문 기사의 모든 세부 사항을 정확히 반영하지 못했습니다. 특히, 외국인과 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보가 일부 누락되었거나 부정확하게 전달되었습니다.] </reason>
- 포괄성: 부족함 <reason> [중요한 정보가 모두 포함되지 않았습니다. 특히, 다양한 날짜에 따른 투자자들의 행동 변화와 그에 따른 주가 변동이 충분히 설명되지 않았습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하는 것이 아니라 다양한 종목과 투자자 행동을 다루고 있어 일관성이 부족합니다.] </reason>

**피드백:**
요약의 정확성과 포괄성을 높이기 위해 원문 기사에서 제공된 구체적인 데이터와 날짜별 투자자 행동을 더 명확하게 반영해야 합니다. 특히, 외국인과 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하고, 주가 변동에 따른 투자 전략의 변화도 설명하는 것이 필요합니다. 또한, 일관성을 유지하기 위해 특정 종목이나 투자자 행동에 초점을 맞추는 것이 좋습니다. 이를 통해 독자가 요약을 통해 원문 기사의 핵심 내용을 보다 명확하게 이해할 수 있도록 개선할 수 있습니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **외국인 투자자, 전기·전자 업종에 집중 매수 및 매도**  \n  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.\n\n- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  \n  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.\n\n- **코스피지수 상승, 투자자 고민 증가**  \n  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.\n\n- **주요 종목의 주가 변동**  \n  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.\n\n🔑 키워드\n- 외국인 투자자\n- 기관 투자자\n- SK하이닉스\n- 삼성전자\n- 코스피지수\n- 전기·전자 업종\n\n**개선 포인트:**\n- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.\n- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.\n- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.'
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약은 원문 기사에서 언급된 여러 날짜와 다양한 종목에 대한 구체적인 매수 및 매도 정보를 충분히 반영하지 못하고 있습니다. 또한, 특정 날짜의 투자자 행동에 대한 구체적인 내용이 누락되었습니다.] </reason>
- 포괄성: 부족함 <reason> [요약은 기사에서 다룬 모든 주요 정보를 포괄하지 못하고 있습니다. 특히, 외국인과 기관 투자자의 구체적인 매수 및 매도 종목 리스트와 그에 따른 주가 변동에 대한 정보가 부족합니다.] </reason>
- 간결성: 부족함 <reason> [요약이 다소 길고 복잡하여, 불필요한 정보가 포함되어 있는 느낌을 줍니다. 핵심 정보만을 간결하게 전달할 필요가 있습니다.] </reason>
- 문장구성: 부족함 <reason> [문장이 복잡하고 명확하지 않아, 독자가 요약의 내용을 쉽게 이해하기 어렵습니다. 더 자연스럽고 명확한 문장 구성이 필요합니다.] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하는 것이 아니라, 다양한 종목과 투자자 행동을 다루고 있어 일관성이 부족합니다.] </reason>

**피드백:**
요약의 정확성과 포괄성을 높이기 위해, 원문 기사에서 언급된 외국인 및 기관 투자자의 매수 및 매도 종목 리스트와 그에 따른 주가 변동에 대한 구체적인 정보를 포함해야 합니다. 또한, 요약을 더 간결하게 구성하여 핵심 정보를 명확하게 전달할 필요가 있습니다. 문장 구성을 개선하여 독자가 내용을 쉽게 이해할 수 있도록 해야 하며, 특정 종목에 대한 일관된 정보를 제공하는 것이 중요합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**  \n  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.\n\n- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  \n  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.\n\n- **코스피지수 상승, 투자자 고민 증가**  \n  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.\n\n- **주요 종목의 주가 변동**  \n  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.\n\n🔑 키워드\n- 외국인 투자자\n- 기관 투자자\n- SK하이닉스\n- 삼성전자\n- 코스피지수\n- 전기·전자 업종\n\n**개선 포인트:**\n- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.\n- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.\n- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.'
[should_stop] Iteration: 3
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약이 원문 기사와 완전히 일치하지 않습니다. 특히, 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보가 일부 누락되었습니다.] </reason>
- 포괄성: 부족함 <reason> [중요한 정보가 모두 포함되지 않았습니다. 특히, 외국인과 기관 투자자의 구체적인 매수 및 매도 종목 리스트와 주가 변동에 대한 세부 사항이 부족합니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용이 일관되지 않고, 다양한 종목과 투자자 행동을 일관성 있게 다루지 못했습니다.] </reason>

**피드백:**
요약의 정확성과 포괄성을 개선하기 위해서는 원문 기사에서 언급된 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 더 포함해야 합니다. 또한, 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화할 필요가 있습니다. 일관성을 높이기 위해서는 다양한 종목과 투자자 행동을 일관성 있게 다루어야 합니다. 이를 통해 독자가 요약을 통해 원문 기사의 주요 내용을 명확히 이해할 수 있도록 해야 합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**  \n  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.\n\n- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  \n  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.\n\n- **코스피지수 상승, 투자자 고민 증가**  \n  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.\n\n- **주요 종목의 주가 변동**  \n  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.\n\n🔑 키워드\n- 외국인 투자자\n- 기관 투자자\n- SK하이닉스\n- 삼성전자\n- 코스피지수\n- 전기·전자 업종\n\n**개선 포인트:**\n- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.\n- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.\n- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.'
[should_stop] Iteration: 4
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 언급된 일부 정보가 원문 기사와 일치하지 않거나, 원문에 없는 세부 사항이 포함되어 있습니다. 예를 들어, 외국인 투자자와 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보가 원문과 다소 차이가 있습니다.] </reason>

- 포괄성: 부족함 <reason> [요약에서 다루지 않은 중요한 정보가 있습니다. 예를 들어, 외국인 및 기관 투자자의 매수 및 매도 종목의 구체적인 리스트와 주가 변동에 대한 세부 사항이 충분히 포함되지 않았습니다.] </reason>

- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>

- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>

- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하는 것이 아니라, 다양한 종목과 투자자 행동에 대한 내용이 혼재되어 있어 일관성이 떨어집니다.] </reason>

**피드백:**

1. **정확성 개선**: 요약에서 언급된 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 정보가 원문과 일치하도록 수정이 필요합니다. 원문에서 제공된 구체적인 종목 리스트와 주가 변동 정보를 정확히 반영하세요.

2. **포괄성 개선**: 요약에 포함된 정보가 원문에서 다루는 모든 중요한 요소를 충분히 포괄하도록 보완해야 합니다. 특히, 외국인 및 기관 투자자의 매수 및 매도 종목 리스트와 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화하세요.

3. **일관성 개선**: 요약에서 특정 종목이나 투자자 행동에 대한 내용이 일관되게 다뤄지도록 구조를 개선하세요. 다양한 종목과 투자자 행동을 일관성 있게 다루어 독자가 혼란스럽지 않도록 해야 합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**  \n  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.\n\n- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  \n  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.\n\n- **코스피지수 상승, 투자자 고민 증가**  \n  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.\n\n- **주요 종목의 주가 변동**  \n  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.\n\n🔑 키워드\n- 외국인 투자자\n- 기관 투자자\n- SK하이닉스\n- 삼성전자\n- 코스피지수\n- 전기·전자 업종\n\n**개선 포인트:**\n- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.\n- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.\n- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.'
[should_stop] Iteration: 5
[should_stop] Feedback:
 **평가:**

- 정확성: 부족함 <reason> [요약에서 언급된 일부 내용이 원문 기사와 일치하지 않거나 부정확한 부분이 있습니다. 예를 들어, 외국인 투자자와 기관 투자자의 매수 및 매도 종목에 대한 정보가 혼재되어 있습니다.] </reason>

- 포괄성: 부족함 <reason> [요약에서 모든 중요한 정보가 포함되지 않았습니다. 예를 들어, 외국인과 기관 투자자의 구체적인 매수 및 매도 종목 리스트가 누락되었습니다.] </reason>

- 간결성: 좋음 <reason> [요약이 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>

- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>

- 일관성: 부족함 <reason> [특정 종목에 대한 내용이 일관되게 다루어지지 않았습니다. 예를 들어, SK하이닉스와 같은 특정 종목에 대한 정보가 중복되거나 혼재되어 있습니다.] </reason>

**피드백:**

- **정확성 개선:** 요약에서 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 정보를 명확하게 구분하고, 원문 기사와 일치하도록 수정해야 합니다.

- **포괄성 개선:** 외국인과 기관 투자자의 매수 및 매도 상위 종목 리스트를 포함하여 요약의 포괄성을 높여야 합니다.

- **일관성 개선:** 특정 종목에 대한 정보를 일관되게 다루고, 중복되거나 혼재된 내용을 정리하여 명확성을 높여야 합니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])

In [126]:
result_df

,ticker,date,summary,feedback
0,SK하이닉스,2025-07-30,"✅ 주요 요약\n\n- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수...",**평가:**\n\n- 정확성: 부족함 <reason> [요약에서 언급된 일부 내용...

In [127]:
print(result_df.summary.values[0])

✅ 주요 요약

- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**
  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.

- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**
  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. 이들 종목 중 일부는 전일 대비 주가가 상승했습니다.

- **코스피지수 상승, 투자자 고민 증가**
  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.

- **주요 종목의 주가 변동**
  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.

🔑 키워드
- 외국인 투자자
- 기관 투자자
- SK하이닉스
- 삼성전자
- 코스피지수
- 전기·전자 업종

**개선 포인트:**
- 외국인 및 기관 투자자의 매수 및 매도 종목에 대한 구체적인 정보를 포함하여 정확성을 높였습니다.
- 주가 변동에 대한 세부 사항을 추가하여 포괄성을 강화했습니다.
- 다양한 종목과 투자자 행동을 일관성 있게 다루었습니다.

## 피드백 정리
- 삼성전자  : 삼성전자에 대한 내용 잘 요약
- 우리금융지주 : 우리금융지주에 대한 내용 잘 요약
- SK하이닉스 : 요약은 되었으나,, 시장 내/외부 사람들의 구매 패턴, 동향에 대한 정보가 주로 요약이 되고 있음<br>
            > recall@50(pool) 이 상당히 낮게 나옴!
  > SK하이닉스에 대한 케이스를 봤을 때, chunk에 대해서만 요약을 해야하나 싶음<br>
  > 2025.08.11) 현재 작업은 전체 원문에 대한 요약이었음. 그래서.. SK 하이닉스 회사 본질에 대한 정보를 제대로 요약해주지 못하나 싶음<br>
  > 프롬프트 내부 요약 평가 기준 의 "일관성" 영역에 명확히 종목명을 말해야겠다..

# 과거 버전

In [204]:
import pandas as pd
from datetime import datetime, timedelta
# cross-encoder
from sentence_transformers import CrossEncoder
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

# 1. 모델 준비 (CrossEncoder for Re-ranking) # 예시 모델 하나 생성
rerank_model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# 2. 최근 5일치 필터링 함수
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max()
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

# 3. huggingface 모델 이용.
def rerank_articles(df: pd.DataFrame,ticker:str ,query: str, top_k: int = 5):
    task_df= df[df.ticker == ticker]
    docs = task_df['content'].tolist()
    # 모델 이용?? 
    pairs = [(query, doc) for doc in docs]
    scores = rerank_model.predict(pairs)
    
    task_df_2 = task_df.copy()
    task_df_2['score'] = scores
    return task_df_2.sort_values(by='score', ascending=False).head(top_k)

# 4. 전체 요약 실행 함수
def summarize_top_articles(df: pd.DataFrame, ticker: str, query: str, top_k: int = 5):
    recent_df = get_recent_articles(df, ticker)
    top_df = rerank_articles(recent_df, query=query,ticker=ticker, top_k=top_k)

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)

    results = []
    for _, row in top_df.iterrows():
        state = {
            "article": row['content'],
            "summary": "",
            "feedback": "",
            "iteration": 0
        }
        result = runnable.invoke(state)


        print("✅ 실행 결과 타입:", type(result))
        print("✅ 실행 결과 키 목록:", result.keys())
        print("✅ 실행 결과 전체 내용:", result)

        if "final_summary" not in result:
            print("❌ final_summary 키가 없습니다. 중단합니다.")
            continue  # 또는 raise Exception("final_summary 없음")

        print(f'실행 결과 : {result}')
        results.append({
            "ticker": row['ticker'],
            "date": row['Date'],
            "header": row['header'],
            "url": row['url'],
            "summary": result["final_summary"], 
             "feedback": result.get("last_feedback", "피드백 없음")
        })
    return pd.DataFrame(results)

In [55]:
query = "우리금융지주 관련 시황"
ticker = "우리금융지주"  # 예시
result_df = summarize_top_articles(cusA_news_df, ticker=ticker, query=query, top_k=3)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음 <reason> 원문의 내용을 정확하게 반영하고 있음. </reason>
- 포괄성: 부족함 <reason> 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용이 누락되었음. </reason>
- 간결성: 좋음 <reason> 불필요한 표현 없이 요약 내용을 간결하게 전달하였음. </reason>
- 문장구성: 좋음 <reason> 문장이 자연스럽고 명확하게 구성되어 있음. </reason>

[피드백]
요약의 포괄성이 부족한 점이 아쉽습니다. 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용을 요약에 포함시키면 더욱 완벽한 요약이 될 것 같습니다. 이 부분을 고려하여 요약을 수정해보시는 것을 추천드립니다.
✅ '정확성' 평가 통과
❌ '포괄성' 평가에서 좋음이 아님
[should_stop] next_step = no

KeyError: 'Input to PromptTemplate is missing variables {\'"foo"\', \'"properties"\'}.  Expected: [\'"foo"\', \'"properties"\', \'article\', \'feedback\', \'summary\'] Received: [\'article\', \'summary\', \'feedback\']\nNote: if you intended {"foo"} to be part of the string and not a variable, please escape it with double curly braces like: \'{{"foo"}}\'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT '

In [35]:
def summarize_top_articles(total_contents :str):

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)
    results = []
    
    doc = total_contents

    state = {
        "article": doc['content'],
        "summary": "",
        "feedback": "",
        "iteration": 0
    }
    result = runnable.invoke(state)


    print("✅ 실행 결과 타입:", type(result))
    print("✅ 실행 결과 키 목록:", result.keys())
    print("✅ 실행 결과 전체 내용:", result)

    if "final_summary" not in result:
        print("❌ final_summary 키가 없습니다.")

    print(f'실행 결과 : {result}')
    results.append({
        "ticker": doc['ticker'],
        "date": doc['Date'],
        "header": doc['title'],
        "url": doc['url'],
        "summary": result["final_summary"], 
            "feedback": result.get("last_feedback", "피드백 없음")
    })
    return pd.DataFrame(results)