## 1. 필요 라이브러리 호출

In [3]:
# 환경설정
import os
import sys
import time
from tqdm import tqdm
import nest_asyncio
nest_asyncio.apply()
from dotenv import load_dotenv

load_dotenv()
# duckdb
import duckdb

# 데이터 전처리
import re
import pandas as pd
import numpy as np
import polars as pl
from datetime import datetime, timedelta
from copy import deepcopy

# 데이터 수집
import requests
from bs4 import BeautifulSoup


# VectorDB 저장
from hashlib import md5
from langchain_community.vectorstores.utils import filter_complex_metadata # ChromaDB가 제공하지 못하는 데이터 형태를 자동으로 string처리
from datetime import datetime, timezone

## LLM 활용
#from summary_function import NewsSummaryAgent
# LLM 활용을 위한 dict형태 구축
from collections import defaultdict

# langchain 계열
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

from langchain_openai import ChatOpenAI

# 1. LLM 모델 세팅 (OpenAI)
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
#from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)

# ㄱRe-ranker 모델 활용
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

## 2. ETF 목록 가져오기

In [8]:
ETF_conn = duckdb.connect('../DB/ETF.db')

In [9]:
ETF_df = ETF_conn.execute('select * from IRP_ETF_COMPOSE_table').fetchdf()
ETF_conn.close()

In [10]:
ETF_df = ETF_df.map(lambda x : x.strip())

In [11]:
ETF_df_task_1 = ETF_df[ETF_df['구성종목 종목명'] != "설정현금액"]
ETF_df_task_1 = ETF_df_task_1[ETF_df_task_1['구성종목 종목명'] != "원화현금"]
ETF_df_task_1 = ETF_df_task_1[1:]

In [12]:
# 원하는 컬럼 필터링
ETF_df_task_2 = ETF_df_task_1[['ETF 종목명','구성종목 표준코드','구성종목 종목명','편입비율']]

In [13]:
# 구성종목 중 상위 5개 추출
ETF_df_task_3 = ETF_df_task_2.sort_values(by=['ETF 종목명','편입비율'], ascending=False)

In [14]:
# 종목별 상위 5개
ETF_df_task_4= ETF_df_task_3.groupby('ETF 종목명').head(5)

In [15]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('반도체')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('전지')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('자율주행')]
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('금융')]

,ETF 종목명,구성종목 표준코드,구성종목 종목명,편입비율
34483,TIGER 25-12 금융채(AA-이상),KR6205498EC7,하나카드273,4.988738
34398,TIGER 25-12 금융채(AA-이상),KR6005273F23,아이엠뱅크46-02이12A-21,4.10297
34473,TIGER 25-12 금융채(AA-이상),KR6140178EB5,케이비국민카드421-1,3.300191
34461,TIGER 25-12 금융채(AA-이상),KR6079314EA3,JB 우리캐피탈524-1(지),2.485386
34475,TIGER 25-12 금융채(AA-이상),KR6145763DC9,BNK캐피탈338-3,2.48222
7606,TIGER 200 금융,KR7316140003,우리금융지주,7.825771
7587,TIGER 200 금융,KR7000810002,삼성화재,7.048532
7595,TIGER 200 금융,KR7032830002,삼성생명,5.727802
7607,TIGER 200 금융,KR7323410001,카카오뱅크,5.180046
7602,TIGER 200 금융,KR7138040001,메리츠금융지주,4.741424
63268,SOL 금융지주플러스고배당,KR7005940002,NH투자증권,5.574874
63270,SOL 금융지주플러스고배당,KR7071050009,한국금융지주,5.456068
63273,SOL 금융지주플러스고배당,KR7138040001,메리츠금융지주,4.724787
63274,SOL 금융지주플러스고배당,KR7138930003,BNK금융지주,3.423077
63276,SOL 금융지주플러스고배당,KR7175330000,JB금융지주,3.214653
36119,RISE 코리아금융고배당,KR7001720002,신영증권,9.789689
36130,RISE 코리아금융고배당,KR7316140003,우리금융지주,9.566045
36127,RISE 코리아금융고배당,KR7105560007,KB금융,9.41425
36123,RISE 코리아금융고배당,KR7024110009,기업은행,9.18122
36118,RISE 코리아금융고배당,KR7000810002,삼성화재,9.125524
29586,RISE 금융채액티브,KR6174147F13,우리카드259-3,6.792848
29582,RISE 금융채액티브,KR6032711EC2,신한카드2244-1,6.775031
29584,RISE 금융채액티브,KR6079315F44,JB 우리캐피탈533-5,6.765295
29580,RISE 금융채액티브,KR6008276F57,산은캐피탈767-3,6.720173
29583,RISE 금융채액티브,KR6033662E66,우리금융캐피탈503-2,5.751116
21311,RISE 200금융,KR7316140003,우리금융지주,7.848761
21292,RISE 200금융,KR7000810002,삼성화재,7.198696
21300,RISE 200금융,KR7032830002,삼성생명,5.759096
21312,RISE 200금융,KR7323410001,카카오뱅크,5.192032
21307,RISE 200금융,KR7138040001,메리츠금융지주,4.756095
3075,KODEX 미국금융테크액티브,CA82509L1076,SHOPIFY-A,9.846667
3080,KODEX 미국금융테크액티브,US0640581007,BANK OF NEW YORK MELLON CORP,9.411734
3078,KODEX 미국금융테크액티브,KYG6683N1034,NU Holdings Ltd/Cayman Islands,9.396511
3092,KODEX 미국금융테크액티브,US92826C8394,VISA INC-CLASS A SHARES,9.096284
3082,KODEX 미국금융테크액티브,US09290D1019,BLACKROCK INC,8.979381
56492,KODEX 미국S&P500금융,US46625H1005,JPMORGAN CHASE & CO,9.654794
56522,KODEX 미국S&P500금융,US92826C8394,VISA INC-CLASS A SHARES,7.900418
56500,KODEX 미국S&P500금융,US57636Q1040,MASTERCARD INC-CLASS A,5.941876
56516,KODEX 미국S&P500금융,US81369Y6059,FINANCIAL SELECT SECTOR SPDR,5.793727
56463,KODEX 미국S&P500금융,US0605051046,BANK OF AMERICA CORP,3.751882
36060,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005830005,DB손해보험,5.910951
36061,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005940002,NH투자증권,5.140565
36062,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7016360000,삼성증권,4.771763
36066,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7071050009,한국금융지주,3.505522
36064,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7039490008,키움증권,3.154331
58932,1Q 단기금융채액티브,KR6019453E35,아이비케이캐피탈301-3,4.057166
58937,1Q 단기금융채액티브,KR6095926E42,현대커머셜514-1,4.042198
58934,1Q 단기금융채액티브,KR6079316E69,JB 우리캐피탈513-2,4.041418
58938,1Q 단기금융채액티브,KR6131791DA0,연합자산관리34-1,4.039457
58939,1Q 단기금융채액티브,KR6145761DB5,BNK캐피탈333-1,4.025209

## 3. 고객 데이터 시나리오
 - 고객 데이터 생성

In [16]:
Customer_A = ETF_df_task_4[ETF_df_task_4['ETF 종목명'].isin(['ACE AI반도체포커스','ACE 2차전지&친환경차액티브','KODEX 자율주행액티브','RISE 200금융'])]

In [17]:
Customer_A = Customer_A.reset_index().drop('index',axis = 1)

In [18]:
Customer_A

             ETF 종목명     구성종목 표준코드  구성종목 종목명       편입비율
0         RISE 200금융  KR7316140003    우리금융지주   7.848761
1         RISE 200금융  KR7000810002      삼성화재   7.198696
2         RISE 200금융  KR7032830002      삼성생명   5.759096
3         RISE 200금융  KR7323410001     카카오뱅크   5.192032
4         RISE 200금융  KR7138040001   메리츠금융지주   4.756095
5      KODEX 자율주행액티브  KR7012330007     현대모비스   8.590932
6      KODEX 자율주행액티브  KR7307950006    현대오토에버   7.626326
7      KODEX 자율주행액티브  KR7000660001    SK하이닉스   5.967903
8      KODEX 자율주행액티브  KR7086280005    현대글로비스   4.925796
9      KODEX 자율주행액티브  KR7005380001       현대차   4.391058
10      ACE AI반도체포커스  KR7000660001    SK하이닉스  25.755918
11      ACE AI반도체포커스  KR7005930003      삼성전자  24.736614
12      ACE AI반도체포커스  KR7042700005     한미반도체  24.473018
13      ACE AI반도체포커스  KR7140860008    파크시스템스   1.519344
14      ACE AI반도체포커스  KR7000990002     DB하이텍   1.517061
15  ACE 2차전지&친환경차액티브  KR7012330007     현대모비스    8.46777
16  ACE 2차전지&친환경차액티브  KR7005380001       현대차    8.23665
17  ACE 2차전지&친환경차액티브  KR7000270009        기아   8.090785
18  ACE 2차전지&친환경차액티브  KR7005490008  POSCO홀딩스   7.842668
19  ACE 2차전지&친환경차액티브  KR7373220003  LG에너지솔루션   7.376414

In [19]:
Customer_A.to_csv('customer_set.csv',encoding='utf-8-sig')

In [20]:
Custer_Having_ticker_lst = list(Customer_A['구성종목 종목명'].unique())

In [21]:
Custer_Having_ticker_lst

['우리금융지주',
 '삼성화재',
 '삼성생명',
 '카카오뱅크',
 '메리츠금융지주',
 '현대모비스',
 '현대오토에버',
 'SK하이닉스',
 '현대글로비스',
 '현대차',
 '삼성전자',
 '한미반도체',
 '파크시스템스',
 'DB하이텍',
 '기아',
 'POSCO홀딩스',
 'LG에너지솔루션']

## 4. 고객 데이터 저장

In [15]:
con = duckdb.connect('../DB/Customer.db')

# Pandas DataFrame을 DuckDB에서 참조할 수 있도록 등록
con.register('temp_df', Customer_A)

# 테이블이 없다면 생성
con.execute("""
    CREATE TABLE IF NOT EXISTS Customers AS
    SELECT * FROM temp_df LIMIT 0
""")

# 데이터 삽입
con.execute("INSERT INTO Customers SELECT * FROM temp_df")

# 정리
con.unregister('temp_df')
con.close()

## 5. 고객이 보유하고 있는 데이터를 DB에 저장하기

In [48]:
import asyncio
import aiohttp
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin,urlparse
import duckdb

# ▶ 헤더
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
}

# ▶ 기사 리스트 파싱 함수
async def get_article_urls(session, page_url):
    try:
        async with session.get(page_url, headers=headers) as resp:
            text = await resp.text()
            soup = BeautifulSoup(text, 'html.parser')
            ul = soup.select_one('#content > div.left_cont > div > div.section.hk_news > div.section_cont > ul')
            if not ul:
                return []

            urls = []
            for a in ul.find_all('a', href=True):
                href = a['href']
                if '/article/' in href:
                    urls.append(href)
            return list(set(urls))  # 중복 제거
    except Exception as e:
        print(f"[get_article_urls error] {page_url} - {e}")
        return []

# ▶ 기사 상세 파싱 함수
async def fetch_article(session, url):
    try:
        async with session.get(url, headers=headers) as resp:
            html = await resp.text()
            soup = BeautifulSoup(html, 'html.parser')

            hostname = urlparse(url).hostname

            # ✅ 1. magazine.hankyung.com용 로직
            if 'magazine.hankyung.com' in hostname:
                return {
                    'header': soup.select_one('#contents h1.news-tit').text.strip() if soup.select_one('#contents h1.news-tit') else None,
                    'summary': None,
                    'content': soup.select_one('#magazineView').text.strip() if soup.select_one('#magazineView') else None,
                    'url': url,
                    'datetime': soup.select_one('#contents span.txt-num').text.strip() if soup.select_one('#contents span.txt-num') else None,
                }

            # ✅ 2. www.hankyung.com일 경우 기존 로직
            elif 'hankyung.com' in hostname:
                return {
                    'header': soup.select_one('h1.headline').text.strip() if soup.select_one('h1.headline') else None,
                    'summary': soup.select_one('div.summary').text.strip() if soup.select_one('div.summary') else None,
                    'content': soup.select_one('#articletxt').text.strip() if soup.select_one('#articletxt') else None,
                    'url': url,
                    'datetime': soup.select_one('div.datetime span.txt-date').text.strip() if soup.select_one('div.datetime span.txt-date') else None,
                }

            # ✅ 알 수 없는 도메인
            else:
                print(f"⚠️ 알 수 없는 호스트: {hostname}")
                return {'url': url, 'header': None, 'summary': None, 'content': None, 'datetime': None}

    except Exception as e:
        print(f"[fetch_article error] {url} - {e}")
        return {'url': url, 'header': None, 'summary': None, 'content': None, 'datetime': None}
# ▶ 메인 비동기 루프
async def extract_news_data_async(query_text, page_range):
    base_url = 'https://search.hankyung.com/search/news?query={query}&page={page}'
    search_urls = [base_url.format(query=query_text, page=p+1) for p in range(page_range)]

    async with aiohttp.ClientSession() as session:
        # 1. 페이지별 기사 링크 수집
        tasks = [get_article_urls(session, url) for url in search_urls]
        results = await asyncio.gather(*tasks)
        article_urls = list(set([url for sublist in results for url in sublist]))

        print(f"🔗 총 {len(article_urls)}개의 기사 URL 수집됨")

        # 2. 기사 본문 수집
        article_tasks = [fetch_article(session, url) for url in article_urls]
        articles = await asyncio.gather(*article_tasks)

        # 3. ticker 컬럼 추가
        for article in articles:
            article['ticker'] = query_text

        # 4. 비어 있으면 dummy row 추가
        if not articles:
            articles = [{
                'header': None,
                'summary': None,
                'content': None,
                'url': None,
                'datetime': None,
                'ticker': query_text
            }]
            print("⚠️ 수집된 기사가 없어 None 값으로 대체 저장합니다.")

        # 4. DuckDB 저장
        df = pd.DataFrame(articles)
        con = duckdb.connect('../DB/Customer_news_sim.db')

        # Pandas DataFrame을 DuckDB에서 참조할 수 있도록 등록
        con.register('temp_df', df)

        # 테이블이 없다면 생성
        con.execute("""
            CREATE TABLE IF NOT EXISTS articles AS
            SELECT * FROM temp_df LIMIT 0
        """)

        # 데이터 삽입
        con.execute("INSERT INTO articles SELECT * FROM temp_df")

        # 정리
        con.unregister('temp_df')
        con.close()

        print(f"✅ 저장 완료: ../DB/Customer_news.db (ticker = {query_text})")

# ▶ 실행 함수
def extract_news_data(query_text, page_range):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(extract_news_data_async(query_text, page_range))

In [109]:
for ticker in Custer_Having_ticker_lst:
    extract_news_data(ticker,20)

🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 우리금융지주)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성화재)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성생명)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 카카오뱅크)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 메리츠금융지주)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대모비스)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대오토에버)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = SK하이닉스)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대글로비스)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 현대차)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 삼성전자)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 한미반도체)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 파크시스템스)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = DB하이텍)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = 기아)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = POSCO홀딩스)
🔗 총 200개의 기사 URL 수집됨
✅ 저장 완료: ../DB/Customer_news.db (ticker = LG에너지솔루션)

저장이 잘 되었는 지 확인

In [45]:
cus_news = duckdb.connect('../DB/Customer_news_sim.db')

In [46]:
cusA_news_df = cus_news.execute('select * from articles').fetch_df()
cus_news.close()

In [49]:
cusA_news_df.sample(200,random_state=42)

,header,summary,content,url,datetime,ticker
1024,금융권 수장들 줄줄이 임기만료…'역대급 인사 큰장' 선다,지주 회장부터 행장까지\n'인사 태풍' 몰아치나\n\n들썩이는 금융 공공기관 \n산...,올 하반기 금융권 수장 인사와 관련해 ‘역대급 큰 장’이 설 것으로 전망된다. 일부...,https://www.hankyung.com/article/2025072126601,2025.07.21 17:53,우리금융지주
2177,"나우로보틱스, 노란봉투법 통과 후 로봇주 강세 속 18% 급등",None,나우로보틱스 주가가 2025년 8월 28일 코스닥 시장에서 전 거래일 대비 18% ...,https://www.hankyung.com/article/202508287036a,2025.08.28 13:13,현대오토에버
1444,휴머노이드 ‘부활’ 신호탄...정부 정책·노란봉투법 수혜 기대에 로봇주 급등,None,보합세를 이어가던 로봇주가 정부의 경제성장전략 발표와 ‘노란봉투법’ 시행 기대감을 ...,https://www.hankyung.com/article/202508274514a,2025.08.28 10:10,삼성생명
3386,"01일, 코스닥 기관 순매수상위에 제약 업종 8종목",None,"기관 투자자는 01일 코스닥에서 알테오젠, 파마리서치, 휴젤 등을 중점적으로 사들인...",https://www.hankyung.com/article/202504014081L,2025.04.01 18:35,파크시스템스
3203,"'페이스메이커' 자처한 李…대미 투자펀드, 큰 틀서 합의",None,영상 모듈 닫기\n\n\n\n\n[앵커]우리시간으로 오늘 새벽 백악관에서 이재명 대...,https://www.hankyung.com/article/2025082629065,2025.08.26 14:52,한미반도체
...,...,...,...,...,...,...
1041,"우리금융그룹, 美 관세 피해 수출업체에 10조2000억 투입…상생대출·금리 우대",자영업 지원 '우리동네 선한가게'\n장애인 위한 물품 기부함 설치,임종룡 우리금융그룹 회장(왼쪽)과 고객이 지난 3월 굿윌기부함에 1호 기부를 하는 ...,https://www.hankyung.com/article/2025071611511,2025.07.16 15:41,우리금융지주
314,"화우, 'M&A 스타' 이진국·윤소연 변호사 영입","윤희웅 대표, 류명현 외국변호사 이어\n기업자문 분야 대거 보강","(왼쪽부터) 이진국, 윤소연 화우 변호사. 사진=화우 제공\n\n ...",https://www.hankyung.com/article/202508049948i,2025.08.04 11:43,현대오토에버
490,토큰증권(STO) 국정과제 포함에 관련주 강세…정책·외국인 수급 동반 호재,None,토큰증권(STO)이 새 정부의 5개년 국정과제에 포함되며 관련 종목들이 연일 상승세...,https://www.hankyung.com/article/202508287466a,2025.08.29 11:00,현대차
3953,"주식 신용대출 이자 부담, 무빙스탁 3%대 금리로 한숨 돌린다",None,"전송종목 : 유비케어, 엠케이전자, 유나이티드제약, 동성화인텍, SJG세종최근 주식...",https://www.hankyung.com/article/202508299043a,2025.08.29 10:37,POSCO홀딩스
3259,"""파크시스템스, 사이클과 무관한 우상향 계속…목표가 상향""-iM",None,iM증권은 18일 파크시스템스에 대해 올해도 사이클과 관계없이 꾸준한 성장세를 보일...,https://www.hankyung.com/article/2025061822376,2025.06.18 08:51,파크시스템스

In [44]:
cusA_news_df.to_csv('news.csv',encoding='utf-8-sig')

In [159]:
cusA_news_df.head(5)

,header,summary,content,url,datetime,ticker
0,"iM뱅크(아이엠뱅크), 2025 을지연습 실시",☞ 8월18일 ~ 20일 국가적 차원의 위기 대응훈련 동참\n\n☞ 위기관리 및 대...,"iM뱅크(아이엠뱅크, 은행장 황병우)는 안보 태세를 강화하고 비상 상황에서 국민의 ...",https://www.hankyung.com/article/202508201792P,2025.08.20 17:58,우리금융지주
1,2025 밸류업 CEO 50 랭킹 - 금융 11~20위,None,[커버스토리] 2025 밸류업 CEO 50\n\n\n\n\n\n\n\n\n\n\n\...,https://magazine.hankyung.com/money/article/20...,2025.08.04 10:53,우리금융지주
2,"""삼성전자보다 더 받아요""...은행원 연봉 보니 '헉'",None,사진=뉴스1국내 주요 시중은행 직원들의 올 상반기 평균 급여가 6350만원에 달하는...,https://magazine.hankyung.com/business/article...,2025.08.16 18:00,우리금융지주
3,"HD현대미포, 조선 업황 회복에 수익성 개선 기대와 수급 흐름 맞물려 상승세",None,조선업 전반의 회복세가 부각되면서 HD현대미포에 대한 투자자들의 관심이 다시 고조되...,https://www.hankyung.com/article/202508185277a,2025.08.18 13:03,우리금융지주
4,"국민이 이끄는 대한민국 경제, 이제 국민이 주주!",농협금융「우리가 주인! 내 주식 갖기」캠페인 전개 -,NH농협금융지주(회장 이찬우)는 8월 15일부터 10월 31일까지「우리가 주인! 내...,https://www.hankyung.com/article/202508125826P,2025.08.12 13:51,우리금융지주

In [160]:
cusA_news_df.shape

(4250, 6)

In [161]:
# 중복제거 필요...
cusA_news_df.groupby('ticker').count()

          header  summary  content  url  datetime
ticker
DB하이텍        250       29      250  250       250
LG에너지솔루션     250       54      250  250       250
POSCO홀딩스     250       12      250  250       250
SK하이닉스       250       64      250  250       250
기아           250      115      250  250       250
메리츠금융지주      250       59      250  250       250
삼성생명         250       91      250  250       250
삼성전자         250       81      250  250       250
삼성화재         250      105      250  250       250
우리금융지주       250       94      250  250       250
카카오뱅크        250       42      250  250       250
파크시스템스       250       18      250  250       250
한미반도체        249       74      249  250       249
현대글로비스       250       62      250  250       250
현대모비스        250       72      250  250       250
현대오토에버       250       28      250  250       250
현대차          250       93      250  250       250

In [162]:
cusA_news_df = cusA_news_df.drop_duplicates()

In [163]:
cusA_news_df.groupby('ticker').count()

          header  summary  content  url  datetime
ticker
DB하이텍        200       23      200  200       200
LG에너지솔루션     200       43      200  200       200
POSCO홀딩스     200       12      200  200       200
SK하이닉스       200       52      200  200       200
기아           200       93      200  200       200
메리츠금융지주      200       47      200  200       200
삼성생명         200       72      200  200       200
삼성전자         200       64      200  200       200
삼성화재         200       81      200  200       200
우리금융지주       200       68      200  200       200
카카오뱅크        200       33      200  200       200
파크시스템스       200       14      200  200       200
한미반도체        199       53      199  200       199
현대글로비스       200       51      200  200       200
현대모비스        200       53      200  200       200
현대오토에버       200       22      200  200       200
현대차          200       77      200  200       200

## 번외) 날짜 전처리 확인 : 최근 N일치 가져오는 로직 생성

In [164]:
cusA_news_df['Date'] = cusA_news_df.datetime.str[:10]
cusA_news_df = cusA_news_df.drop('datetime',axis=1)
cusA_news_df['Date'] = pd.to_datetime(cusA_news_df['Date'])

In [165]:
# 2. 기준일 계산 (오늘 날짜 - 5일)
today = pd.to_datetime("2025-08-29")
five_days_ago = today - timedelta(days=5)

# 3. 최근 5일치 필터링
recent_news_df = cusA_news_df[cusA_news_df['Date'] >= five_days_ago]

In [166]:
recent_news_df

,header,summary,content,url,ticker,Date
11,한국 디지털자산 산업의 미래는 어떤 모습인가 [태평양의 미래금융],韓 구체적 규제안 전무...예측가능성 0\n美 백악관은 디지털 자산 규제 '166페...,한경 로앤비즈의 ‘Law Street’ 칼럼은 기업과 개인에게 실용적인 법률 지식을...,https://www.hankyung.com/article/202508263699i,우리금융지주,2025-08-27
12,"iM금융그룹, UNGC-UNFCCC-UNEP 공동 ‘기후 리더십 조찬간담회’ 참여",‘기후행동 통한 비즈니스 리더십 기획 확보’ 주제 논의,iM금융그룹(회장 황병우)은 지난 27일 서울 그랜드하얏트 호텔에서 열린 UNGC(...,https://www.hankyung.com/article/202508287972P,우리금융지주,2025-08-28
14,"“I LOVE iM!”…iM금융그룹, 건강한 기업문화 조성 박차",‘우리 회사 사랑하기’ 캠페인 진행\n\n계열사 모바일 서비스 이용 장려,iM금융그룹(회장 황병우)은 오는 9월 말까지 전 계열사 임직원을 대상으로 「I L...,https://www.hankyung.com/article/202508262387P,우리금융지주,2025-08-26
17,"휴먼시아 청약, 다시 생각해 볼게요 [김용우의 각개전투]",공공주택도 대형 건설사 브랜드 가능\n프리미엄 이미지·입찰 허들에 '멈칫'\n보급형...,한경 로앤비즈의 'Law Street' 칼럼은 기업과 개인에게 실용적인 법률 지식을...,https://www.hankyung.com/article/202508237248i,우리금융지주,2025-08-26
18,"증권주, 美 금리인하 기대감에 동반 강세",None,제롬 파월 미 중앙은행(Fed) 의장이 지난 22일(현지시간) 미 와이오밍주 잭슨홀...,https://www.hankyung.com/article/2025082591866,우리금융지주,2025-08-25
...,...,...,...,...,...,...
4232,증권사 신용융자 쓰시는 분? 이 상품 하나면 3%대 금리로 가능합니다,None,"전송종목 : HD현대중공업, 두산퓨얼셀, 하이브, 솔브레인, SK아이이테크놀로지최근...",https://www.hankyung.com/article/202508258834a,LG에너지솔루션,2025-08-25
4237,이재용 회장 방미사절단 출국…삼성·SK·LG 등 재계 총출동,None,이재용 삼성전자 회장이 24일 오후 서울 강서구 김포비즈니스항공센터에서 한미 정상회...,https://www.hankyung.com/article/2025082482927,LG에너지솔루션,2025-08-24
4241,"증권사 신용 이용자들 주목! 3%대 금리의 상품 출시!!, 매도없이 전환가능",None,"전송종목 : LG에너지솔루션, DL이앤씨, F&F, SK스퀘어, 에코프로머티최근 주...",https://www.hankyung.com/article/202508258835a,LG에너지솔루션,2025-08-25
4244,[단독] 5조 갚아야하는데 현금 '텅텅'…줄줄이 '초비상',10대 석화기업 단기 차입금만 5.3兆 \n대주주 증자 압박 커진다\n\n1년내 만...,"국내 10대 석유화학 기업이 발행한 회사채, 기업어음(CP) 가운데 1년 안에 만기...",https://www.hankyung.com/article/2025082484091,LG에너지솔루션,2025-08-24
4246,"코스피, 미 금리인하 불확실성 부각에 하락…원전주↓",4거래일 만에 하락세로 돌아서\n외인·기관 '팔자'…개인 '사자'\n\n알래스카LN...,이재명 대통령과 도널드 트럼프 미국 대통령이 25일(현지시간) 미국 워싱턴DC 백악...,https://www.hankyung.com/article/2025082617196,LG에너지솔루션,2025-08-26

In [167]:
recent_news_df= recent_news_df.drop_duplicates()

In [168]:
# 최근 30일치 뉴스 기사 필터링 시 남아있는 뉴스 기사 개수
recent_news_df.groupby('ticker').count()

          header  summary  content  url  Date
ticker
DB하이텍          2        0        2    2     2
LG에너지솔루션      75       15       75   75    75
POSCO홀딩스      51        0       51   51    51
SK하이닉스       132       36      132  132   132
기아            62       30       62   62    62
메리츠금융지주        5        2        5    5     5
삼성생명          17        7       17   17    17
삼성전자         200       64      200  200   200
삼성화재          19        9       19   19    19
우리금융지주        11        7       11   11    11
카카오뱅크         12        3       12   12    12
파크시스템스         3        0        3    3     3
한미반도체         49       20       49   49    49
현대글로비스        16        4       16   16    16
현대모비스         17        5       17   17    17
현대오토에버         4        2        4    4     4
현대차          180       71      180  180   180

## 정규식으로 뉴스 기사 내 불용어 처리

In [169]:
boilerplate_patterns = [
    r"\* 아래 텍스트는 실제 방송 내용과 차이가 있을 수 있으니.*",
    r"\*인터뷰를 인용보도할 때는 프로그램명.*",
    r"저작권은.*에 있습니다.*",
    r"▶ 알립니다.*",
    r"\[앵커\].*?\[",
    r"\[기자\].*?\[",
    r"\[.*?\]",             # 모든 대괄호 안 내용
    r"영상취재:.*",
    r"영상편집:.*",
    r"그래픽:.*",
    r"\/?사진=(연합뉴스|뉴스\S*)[^\n]*\s*"       # 사진=출처 or /사진=출처 패턴 제거
]

In [170]:
compiled_pattern = re.compile("|".join(boilerplate_patterns))

In [171]:
test_pattern = cusA_news_df.content.astype(str).apply(lambda x : compiled_pattern.sub("", x).strip())

In [172]:
cusA_news_df.content.astype(str).apply(lambda x : len(x)).describe()

count      3400.000000
mean       1689.115882
std        6914.147389
min           0.000000
25%         726.000000
50%        1080.000000
75%        1500.000000
max      125274.000000
Name: content, dtype: float64

In [173]:
test_pattern.apply(lambda x : len(x)).describe()

count      3400.000000
mean       1673.633529
std        6912.770281
min           0.000000
25%         716.000000
50%        1077.000000
75%        1499.250000
max      125274.000000
Name: content, dtype: float64

#### 결론 : 큰 영향 없다..? 그냥 해보자

## 질문 생성 (For Labeling)  -- 주말 작업 예정 .. 모델 성능평가를 위함
Part_1 : Re-Ranking 라벨링

In [174]:
def labeling(data,ticker):
  template = """
  <instruction>
  다음은 뉴스 기사 본문과 해당 기사에 매핑된 종목명(티커)입니다.
  당신의 임무는 기사 본문이 해당 종목에 대한 기사인지 여부를 판별하는 것입니다.

  규칙:
  - 1 : 뉴스 내용이 해당 종목의 시황을 나타낼 경우.
     예: 종목명이 기사에 등장하고, 그 종목의 실적, 주가, 제품, 사건, 경영, 산업 동향 등과 밀접한 관련이 있음.
     예) 종목의 실적/주가/사업/이슈/계약/정책/규제/소송/리스크/전망 등.
     예) 섹터 기사라도 해당 종목이 사례/주요 구성원으로 명시적 언급되고 맥락에 기여.
  - 0 : 뉴스 내용이 해당 종목을 단순 언급하는 경우이거나, 직접적으로 관련이 없음  
     예: 종목명이 전혀 등장하지 않거나, 비슷한 용어를 가진 단어의 내용이 등장하더라도 다른 주제가 메인인 경우.
     예) 피상적 나열(태그/키워드/꼬리말 광고)만 존재, 타사 이슈가 중심.
     
  출력 형식:
  - 숫자 1 또는 0만 출력
  </instruction>

  예시:
  ---
  [티커] 삼성전자
  [본문] 삼성전자가 2분기 실적 호조를 발표하며 주가가 3% 상승했다.
  [정답] 1
  ---
  [티커] 삼성전자
  [본문] 미국 증시가 기술주 중심으로 상승세를 보였다. 애플과 구글 주가가 상승했다.
  [정답] 0
  ---

  다음 데이터를 분류하세요.

  [티커] {ticker_name}
  [본문] {news_content}
  [정답]
  """

  prompt = ChatPromptTemplate.from_template(template)

  # 3. 체인 구성
  chain = prompt | llm | StrOutputParser()

  # 4. 실행 예시
  query = chain.invoke({"news_content": data,'ticker_name' : ticker})
  return query

## 6. VectorDB 저장

In [4]:
# 4. OpenAI 임베딩 모델 로딩
embedding = OpenAIEmbeddings(model="text-embedding-3-large")

persist_directory = "../VectorDB/chroma_news_db"

vectordb = Chroma(
    persist_directory=persist_directory,
    embedding_function=embedding,
    collection_name="SLM_News_5")

In [176]:
def pick_splitter_by_length(text_len: int) -> RecursiveCharacterTextSplitter:
    """
    뉴스 본문의 길이에 따라 적절한 텍스트 분할기를 반환합니다.
    """
    if text_len <= 1200:
        # 짧은 기사 → 굳이 자르지 않고 1덩어리로 처리
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=0,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 10_000:
        # 중간 길이 → 일반적인 1,200자 기준으로 분할
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=150,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 50_000:
        # 긴 기사 → 덩어리를 좀 더 키움
        return RecursiveCharacterTextSplitter(
            chunk_size=1800,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )
    else:
        # 초장문 → 더 크게 자르되, 요약도 고려 (이건 후속 처리 필요)
        return RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )

In [177]:
# 2. 문서 리스트 생성 (chunk + metadata 포함)
def make_documents(df):
    docs = []

    for idx, row in tqdm(df.iterrows()):
        text = row["content"]
        splitter = pick_splitter_by_length(len(text))
        chunks = splitter.split_text(text)
        for i, chunk in enumerate(chunks):
            label = labeling(chunks,row['ticker'])
            metadata = {
                "title": row["header"],
                "url": row["url"],
                "Date": row["Date"],
                "ticker": row.get("ticker", "None"),
                "chunk_idx": i,
                "original_idx": idx,
                'label' : label  #labeling한 결과를 넣자!! 
            }
            time.sleep(0.1)
            docs.append(Document(page_content=chunk, metadata=metadata))

    return docs

In [178]:
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max() # 가지고 있는 뉴스의 가장 최신 데이터
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

In [179]:
def make_doc_id(d: Document) -> str:
    """
    url + chunk_idx(없으면 0) + 시간
    """
    run_utc = datetime.now(timezone.utc)
    base = f"{d.metadata.get('url','')}_{d.metadata.get('chunk_idx', 0)}_{run_utc}"
    return md5(base.encode("utf-8")).hexdigest()

def chunks(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

## Label작업 수행

In [136]:
for ticker in Custer_Having_ticker_lst:
    print(f"========= ticker {ticker} 진행 중~ =============")
    task_1_df = get_recent_articles(cusA_news_df,ticker=ticker,days = 20)
    task_1_df['Date'] = task_1_df.Date.astype('str')
    # document 만들기
    task_1_docs = make_documents(task_1_df)
    length_docs = len(task_1_docs)
    print(f'각 {ticker} 별 docs의 개수 : {length_docs}')
    BATCH = 32  # 상황에 맞게 조절

    for docs in tqdm(chunks(task_1_docs, BATCH), total=(len(task_1_docs) + BATCH - 1) // BATCH):

        ids = [make_doc_id(d) for d in docs]
        vectordb.add_documents(documents=docs, ids=ids)
        time.sleep(0.1)

========= ticker 우리금융지주 진행 중~ =============

33it [00:45,  1.39s/it]

각 우리금융지주 별 docs의 개수 : 58

100%|██████████| 2/2 [00:03<00:00,  1.83s/it]

========= ticker 삼성화재 진행 중~ =============

50it [01:49,  2.19s/it]

각 삼성화재 별 docs의 개수 : 130

100%|██████████| 5/5 [00:11<00:00,  2.39s/it]

========= ticker 삼성생명 진행 중~ =============

70it [02:34,  2.20s/it]

각 삼성생명 별 docs의 개수 : 182

100%|██████████| 6/6 [00:11<00:00,  1.90s/it]

========= ticker 카카오뱅크 진행 중~ =============

43it [01:38,  2.28s/it]

각 카카오뱅크 별 docs의 개수 : 115

100%|██████████| 4/4 [00:08<00:00,  2.12s/it]

========= ticker 메리츠금융지주 진행 중~ =============

41it [00:41,  1.01s/it]

각 메리츠금융지주 별 docs의 개수 : 58

100%|██████████| 2/2 [00:04<00:00,  2.01s/it]

========= ticker 현대모비스 진행 중~ =============

41it [00:37,  1.09it/s]

각 현대모비스 별 docs의 개수 : 54

100%|██████████| 2/2 [00:04<00:00,  2.25s/it]

========= ticker 현대오토에버 진행 중~ =============

7it [00:57,  8.17s/it]

각 현대오토에버 별 docs의 개수 : 48

100%|██████████| 2/2 [00:04<00:00,  2.21s/it]

========= ticker SK하이닉스 진행 중~ =============

200it [04:18,  1.29s/it]

각 SK하이닉스 별 docs의 개수 : 359

100%|██████████| 12/12 [00:26<00:00,  2.18s/it]

========= ticker 현대글로비스 진행 중~ =============

30it [00:23,  1.27it/s]

각 현대글로비스 별 docs의 개수 : 36

100%|██████████| 2/2 [00:02<00:00,  1.45s/it]

========= ticker 현대차 진행 중~ =============

200it [04:46,  1.43s/it]

각 현대차 별 docs의 개수 : 386

100%|██████████| 13/13 [00:24<00:00,  1.90s/it]

========= ticker 삼성전자 진행 중~ =============

200it [04:20,  1.30s/it]

각 삼성전자 별 docs의 개수 : 356

100%|██████████| 12/12 [00:25<00:00,  2.17s/it]

========= ticker 한미반도체 진행 중~ =============

122it [02:52,  1.42s/it]

각 한미반도체 별 docs의 개수 : 245

100%|██████████| 8/8 [00:16<00:00,  2.01s/it]

========= ticker 파크시스템스 진행 중~ =============

7it [00:46,  6.65s/it]

각 파크시스템스 별 docs의 개수 : 45

100%|██████████| 2/2 [00:03<00:00,  1.89s/it]

========= ticker DB하이텍 진행 중~ =============

4it [00:04,  1.21s/it]

각 DB하이텍 별 docs의 개수 : 6

100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

========= ticker 기아 진행 중~ =============

162it [03:42,  1.37s/it]

각 기아 별 docs의 개수 : 306

100%|██████████| 10/10 [00:19<00:00,  1.91s/it]

========= ticker POSCO홀딩스 진행 중~ =============

146it [02:50,  1.17s/it]

각 POSCO홀딩스 별 docs의 개수 : 250

100%|██████████| 8/8 [00:19<00:00,  2.42s/it]

========= ticker LG에너지솔루션 진행 중~ =============

195it [04:30,  1.39s/it]

각 LG에너지솔루션 별 docs의 개수 : 379

100%|██████████| 12/12 [00:25<00:00,  2.16s/it]

In [181]:
print("Number of documents in DB:", vectordb._collection.count())

Number of documents in DB: 3129

## 7. cross-encoder 모델(w/langchain 예시)

In [87]:
import numpy as np
import pandas as pd

def _dcg_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    if L.size == 0: return 0.0
    discounts = 1.0 / np.log2(np.arange(2, L.size + 2))
    return float(np.sum(L * discounts))

def ndcg_at_k(labels, k=50):
    labels = np.asarray(labels)
    dcg  = _dcg_at_k(labels, k)
    idcg = _dcg_at_k(np.sort(labels)[::-1], k)
    return 0.0 if idcg == 0 else dcg / idcg

def precision_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    return float(L.mean()) if L.size else 0.0

def recall_at_k(labels, total_relevant, k=50):
    if not total_relevant or total_relevant <= 0: return 0.0
    return float(np.sum(np.asarray(labels)[:k])) / float(total_relevant)

def mrr_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    hit = np.where(L > 0)[0]
    return 0.0 if hit.size == 0 else 1.0 / (hit[0] + 1)

def map_at_k(labels, total_relevant, k=50):
    L = np.asarray(labels)[:k]
    if L.sum() == 0: return 0.0
    precisions, hit = [], 0
    for i, y in enumerate(L, start=1):
        if y:
            hit += 1
            precisions.append(hit / i)
    denom = max(1, min(total_relevant if total_relevant is not None else int(L.sum()), k))
    return float(np.sum(precisions) / denom)

def eval_reranker_chunk(pool_df, ranked_df, k=50, rank_col="rank", score_col="relevance_score"):
    # 1) 풀: label만 필요 (score/rank 불필요)
    total_rel_pool = int(
        pd.to_numeric(pool_df["label"], errors="coerce").fillna(0).clip(0,1).sum()
    )
    print(f'total_rel_pool : {total_rel_pool}')

    # 2) 랭크드: 순서가 필요 (rank 우선, 없으면 score로 정렬, 둘 다 없으면 현재 순서 사용)
    g = ranked_df.copy()
    if rank_col in g.columns:
        g = g.sort_values(rank_col, ascending=True)
    elif score_col in g.columns:
        g = g.sort_values(score_col, ascending=False)
        g[rank_col] = np.arange(1, len(g)+1)
    else:
        g[rank_col] = np.arange(1, len(g)+1)

    y_topk = pd.to_numeric(g["label"], errors="coerce").fillna(0).clip(0,1).astype(int).values[:k]
    print(f'y_topk : {y_topk}')
    return {
        f"Precision@{k}": precision_at_k(y_topk, k),
        f"Recall@{k}(pool)": recall_at_k(y_topk, total_rel_pool, k),
        f"MRR@{k}": mrr_at_k(y_topk, k),
        f"MAP@{k}": map_at_k(y_topk, total_rel_pool, k),
        f"nDCG@{k}": ndcg_at_k(y_topk, k),
        "PoolSize": int(len(pool_df)),
        "PoolRelevant": total_rel_pool,
        "TopK": int(min(len(g), k)),
        "TopKRelevant": int(y_topk.sum()),
    }

Re-ranker 사용하기 전

In [63]:
retriver_target = ['우리금융지주','삼성화재','카카오뱅크','삼성생명','메리츠금융지주','현대모비스','현대글로비스','SK하이닉스','현대오토에버']

In [64]:
retriever_total = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : retriver_target}})

In [65]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i + 1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

In [78]:
before_lst = []

In [79]:
for ticker in retriver_target:
    retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    before_lst.extend(raw_docs)
    print(list(map(lambda x: x.metadata['label'],raw_docs))[:5])
    print(list(map(lambda x: x.page_content,raw_docs))[:5])

이 뉴스들 중에서 "우리금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 우리금융지주가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['<앵커> 오늘 금융지주 주가가 오전에 잠시 조정받는 듯했는데 KB금융 제외하곤 낙폭을 줄여가는 모습입니다. 앞서 최민정 기자 언급한 자사주 의무 소각 관련해 금융지주들에는 어떤 영향이 있을지 경제부 유주안 기자와 이야기 나눠봅니다. 금융지주들은 자사주 매입과 소각에 꽤 적극적인데, 보유중인 자사주의 비중은 어떻습니까?<기자>4대 금융지주 자사주 보유 현황(KB 4.54%, 신한 2.09%, 하나 3.77%, 우리 1.16%)은, 보시다시피 비중이 크다고 보이진 않습니다.자사주 소각 의무화 추진에 따른 수혜주로 꼽히는 미래에셋(22.98) 대신(25.12) 신영(52.58%) 등에 비하면 매우 작은 수준이고요, 일반지주사들(티와이홀딩스 29.79%, SK 24.8%, 롯데지주 27.37% 등)에 비해서도 비중이 낮습니다.과거 역사를 살펴보면 금융주에 있어서는 자사주 ‘지배의 도구’보다는 인수합병 때 주식교환을 하기 위해, 전략적 투자자와 주식을 스왑하는 차원에서 일정 부분 보유해왔던 것을 알 수 있고요, 최근 들어서는 매입하면 바로 소각해서 주식의 가치를 올리는, 주주환원의 수단으로 자사주를 활용해 왔습니다.따라서, 자사주 소각 의무화에 따른 강제성 측면에서 금융지주에 미치는 단기적 직접적 영향은 크지 않겠습니다. 중장기적으로 볼 때 금융지주의 주주환원에 보다 힘이 실릴 것이란 기대감으로 이어질 수 있는데요,정책이 추구하는 목표를 이미 금융지주사들이 실행해 옮기고 있는 것이고, 향후 상장사들 사이에 자사주 매입소각이 보편화되면 재무적 여력과, 주주환원에 대한 강한 의지를 가진 금융사들이 더 적극적인 주주환원을 펼칠 수 있는 배경이 될 수 있을 것입니다.또한, 정부가 함께 추진중인 배당소득 분리과세 정책은 배당성향이 높고, 분기배당에 적극적인 금융주에게 특히 긍정적인 정책으로 받아들여지고 있습니다.<앵커> 어제 삼성전자 실적으로 인해 다소 가라앉은 분위기로 어닝시즌 개막되었는데요. 금융주 실적은 어떨 걸로 전망됩니까?<기자> 4대 지주만 놓고 볼 때, 당초 2분기는 좀 쉬어갈 것으로 예상이 되었습니다. 이는 2024년 2분기에 실적이 워낙 좋았던 것에 대한 기저효과와 더불어, 시중금리가 내려가면서 이자이익이 축소될 것으로 예상되었기 때문입니다.에프앤가이드 취합 컨센서스로 보면 KB금융의 2분기 당기순이익이 전년동기대비 약 5% 감소한 1조 6300억원, 우리금융지주 약 9% 감소한 8700억원으로 전망이', 'KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기', 'KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 내며 분기 기준 사상 최대 실적 기록을 썼다. 이자이익 증가세가 사실상 멈췄지만, 환율이 안정된 덕분에 비이자이익이 15% 넘게 늘어난 영향이 크다는 분석이 나온다.25일 금융권에 따르면 4대 금융지주의 지난 2분기 순이익은 총 5조3954억원이었다. 지난해 같은 기간(5조1241억원)과 비교해 2713억원(5.3%) 늘었다. 4대 금융지주의 순이익 합산액이 5조3000억원을 넘은 것은 이번이 처음이다.금융지주별로 보면 하나금융의 순이익이 작년 2분기 1조347억원에서 올 2분기 1조1733억원으로 1386억원(13.4%) 늘어 가장 큰 증가폭을 보였다. 같은 기간 신한금융은 1조4255억원에서 1조5491억원으로 1236억원(8.7%) 불어났다. KB금융의 2분기 순이익은 1조7384억원으로 4대 금융지주 중 가장 많았지만, 전년 동기 대비로는 0.3% 증가하는 데 그쳤다. 우리금융의 순이익은 같은 기간 9315억원에서 9346억원으로 0.3% 늘었다.실적 증가를 이끈 것은 비이자이익이다. 4대 금융지주의 비이자이익은 작년 2분기 3조4264억원에서 올 2분기 3조9591억원으로 5327억원(15.5%) 증가했다. 원화가 강세 흐름을 보이면서 외화환산이익이 늘었다는 게 4대 금융지주의 공통된 설명이다. 반면 4대 금융지주의 올 2분기 이자이익은 전년 동기 대비 0.4% 늘어나는 데 그쳤다.정의진/김진성 기자 justjin@hankyung.com', '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 296.2만주를 순매수했고, 개인들도 41.8만주를 순매수했다. 하지만 기관은 294.9만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 51.3%, 26.2%로 비중이 높다.더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', 'KB금융이 최대 8천억원, 신한과 하나가 각 3~4천억원, 우리 1500억원, 도합 1조6천원에 달하는 자사주 소각 파티를 벌일 것으로 기대하고 있습니다.배당과 자사주 매입소각 합친 총주주환원율이 올해 50% 넘어가는 케이스도 탄생할지 관전포인트입니다.<앵커> 그간 주가가 많이도 올랐는데, 향후 추가 상승을 기대해볼 수 있나요?<기자> 2분기 이후 4대 금융지주 주가는 일제히 40% 이상 올랐습니다.워낙 국내 증시 저평가 되어있다보니 주식시장에서 장부가 만큼만이라도 평가를 받으라는 의미에서 PBR 1배가 목표치로 설정되어 있는데요, 주가가 45% 올랐어도 KB금융의 PBR이 0.7배 수준입니다. 나머지 3곳은 장부가 절반의 가치밖에 인정을 못 받고 있습니다.따라서 오늘 주가 하락에 대해서는 금융권 안팎과, 기업분석하는 증권업계 쪽에선 최근 급등에 따른 단기조정의 성격으로 파악을 하고 있습니다.마지막으로 4곳 중 어디가 가장 좋을 것이냐도 궁금하실텐데. KB금융이 실적과 주주환원 측면에서 압도적일 것으로 예상되고 주가 측면에서도 1위 프리미엄이 지속될 것이란 전망이 있는 동시에 또다른 측면에선 키맞추기가 이뤄질 것으로 예상하기도 합니다.  KB가 0.7배 수준까지 올랐으니, 2~4위권이 부지런히 키맞추기를 위해 올라올 것으로 기대하는 시각도 있습니다.<네 잘 들었습니다>유주안기자 jayou@wowtv.co.kr']
이 뉴스들 중에서 "삼성화재"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성화재가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 15.0만주를 순매수한 반면, 기관은 13.0만주를 순매도했고, 개인들도 1.8만주를 순매도한 것으로 집계됐다. 같은 기간 이 종목의 거래 비중은 외국인과 기관이 각각 63.0%, 27.0%로 비중이 높다.한편 외국인과 기관은 이 종목에 대해서 각각 최근 4일 연속 순매수, 4일 연속 순매도 행진을 벌이고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]삼성화재 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 점진적인 기업가치, 주주가치 향상 기대 - NH투자증권, BUY07월 04일 NH투자증권의 정준섭 애널리스트는 삼성화재에 대해 "삼성화재는 아직 초과자본에 대한 적극적인 활용 방안 미제시. 다만 대외 여건 호전에 따라 장기적으로 초과자본 활용 확대 기대"라고 분석하며, 투자의견 \'BUY\', 목표주가 \'523,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 14.2만주를 순매수한 반면, 기관은 11.8만주를 순매도했고, 개인들도 2.3만주를 순매도한 것으로 집계됐다. 같은 기간 이 종목의 거래 비중은 외국인과 기관이 각각 62.8%, 27.0%로 비중이 높다.한편 외국인과 기관은 이 종목에 대해서 각각 최근 5일 연속 순매수, 5일 연속 순매도 행진을 벌이고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]삼성화재 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 깔끔하다 - 한국투자증권, 매수07월 09일 한국투자증권의 홍예란 애널리스트는 삼성화재에 대해 "순이익 6,036억원으로 컨센서스 부합. 수익성도 1분기를 저점으로 점차 개선될 것"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'530,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '◇4대 기업 화두는 ‘재생에너지·자원 순환’13일 산업계에 따르면 이달 들어서만 70여 개 기업이 ESG 실천 성과를 담은 보고서를 공개했다. 업계에선 올해 보고서 발행 건수가 지난해 204건을 넘어 사상 최대에 이를 것으로 내다보고 있다.삼성전자는 ‘2025 지속가능성경영보고서’에서 재생에너지 사용량이 지난해 처음 1만GWh를 넘어섰다고 공개했다. 한국 전체 가구가 두 달 가까이 쓰는 전력량이다. 이 회사의 지난해 재생에너지 사용량은 1만69GWh로 전년(9289GWh)보다 8.4% 늘었다.현대차는 폐차의 재활용 소재를 신차에 적용하는 ‘카 투 카(Car to Car) 프로젝트’를 소개했다. 지난해 10월 국내 최대 규모인 444메가와트(㎿) 재생에너지 공급계약(PPA)을 체결한 사례도 적시했다. 이 계약으로 현대차는 20년간 국내 사업장에서만 연간 610GWh 재생에너지를 공급받는다.SK하이닉스는 지난해 대비 에너지 효율을 내년 30%, 2030년까지 60% 개선하기로 약속하면서 저전력 D램을 ‘지속가능 제품’으로 지정했다. 저전력 D램은 PC와 서버용 D램보다 전력 소모를 획기적으로 줄인 메모리반도체다.LG전자는 지난해 국내외 사업장 폐기물 재활용률이 97.4%로 2030년 목표치(95%)를 초과 달성했다고 밝혔다. 이 회사는 지난해 56개국에서 총 53만2630t의 폐전자 제품을 회수했다. 7대 주요 제품의 사용 단계 탄소 배출량도 2020년보다 19.4% 줄였다. ◇금융계는 ‘기후 리스크’ 강조금융권은 기후 리스크를 핵심 화두로 지목했다. 기후 리스크가 실적 및 재무 구조 관리와 밀접한 연관이 있다는 판단에서다. 한국은행은 지난 3월 국내 금융사들이 기후변화 위험에 대응하지 않으면 손실 규모가 46조원에 이를 것으로 분석했다.KB금융은 산출 대상 자산군을 해외 국채까지 확대한 ‘금융 배출량’과 기후 위기 시나리오 분석을 바탕으로 수립한 ‘기후 회복력 중장기 대응 전략’ 등을 담은 기후 위기 관리 방안을 공개했다. JB금융은 ESG 내재화의 4대 핵심 전략 중 ‘기후변화 대응’을 처음 꼽았다. 우리금융은 과학 기반 탄소 감축 목표 이니셔티브(SBTi)에서 인증받은 탄소 감축 목표 수치를 공개했다. 화재·폭우 등 기후변화에 따른 재난이 대형 손실로 이어질 가능성이 있는 보험사들은 지속가능경영보고서에 온실가스 배출량 등을 상세하게 공개하는 등 기후 리스크에 민감하게 대응하고 있다.인공지능(AI)을', '외국인 투자자는 15일 거래소에서 현대차, 삼성화재, 기아 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 현대차, 삼성화재, 기아, 기업은행, SK텔레콤, NAVER, 신한지주, 우리금융지주, 삼성SDI, DB손해보험등이다.이중에 보험 업종에 속한 종목이 3개 포함되어 있다.기업은행, NAVER, 우리금융지주 등은 전일 대비 주가가 상승했고, 현대차, 삼성화재, 기아 등은 주가가 하락했다.[07월15일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '더불어민주당 김남근 의원이 발의한 자사주 의무 소각 법안이 본격적으로 논의되며, 보험업종에 수혜 기대감이 커지고 있다. 해당 법안은 기업이 보유한 자사주를 소각하도록 의무화하는 내용을 담고 있으며, 이는 자사주 비중이 높은 보험주에 긍정적 영향을 미칠 것으로 보인다.현재 보험업종의 평균 자사주 보유 비율은 약 13.4% 수준이다. 시장에서는 자사주 소각을 통해 주주가치 제고와 주당순이익(EPS) 개선이 기대된다는 분석이 지배적이다.LS증권은 최근 보고서에서 보험업종에 대한 추가 호재로 ▲킥스비율(K-ICS, 신지급여력제도) 규제기준 하향 ▲예약환급금준비금 적립요건 완화 등을 꼽았다. 아울러 보험판매 수수료 개편, 실손보험 개혁 논의 등이 병행되면 전반적인 보험업종 체질 개선이 본격화될 것으로 내다봤다.정책 기대감이 커지면서 ▲삼성화재 ▲삼성생명 ▲한화손해보험 ▲현대해상 ▲DB손해보험 등 주요 보험 종목들이 연일 상승세를 나타내고 있다. 특히 자사주 비율이 높고 배당 성향이 우수한 종목들은 테마 수급까지 유입되며 관심이 집중되고 있다.이처럼 테마 이벤트와 정책 변화에 따른 단기 상승세에 투자 기회를 찾는 투자자들은 스탁론을 활용한 레버리지 전략도 적극 검토 중이다. 안정적인 보험주의 특성상 하방 리스크가 상대적으로 제한적이라는 점에서, 자금 효율성과 단기 수익률을 모두 고려한 접근이 가능하다는 평가다.\n\n\n\n\n \n\n▶ 더머니스탁론 신규 상품 전격 출시! (DSR 규제 X)▶ 최대 400% 레버리지 투자, 증권사 신용미수 대환 가능!▶ 한 종목 100% 집중 투자 가능!▶ 더머니스탁론 바로가기 (https://themoney.co.kr/ha)▶ 더머니스탁론 전화 상담 1600-7096▶ 더머니스탁론 카카오톡 상담 (http://pf.kakao.com/_cVfxbn/chat)관심종목: 삼성화재, 삼성생명, 한화손해보험, 현대해상, DB손해보험무료상담']
이 뉴스들 중에서 "카카오뱅크"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 카카오뱅크가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
["경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에대한인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n종목추천 서비스 종합 플랫폼 한경유레카에 입점한 친절한미정씨가 전거래일(10일) 카카오뱅크를 추천하여 수익률 6.6%를 기록했다.친절한미정씨는 성장, 가치, 성과, 안정성, 모멘텀 등 기업의 가치를 평가하는 5개 중요 변수를 AI 학습 및 분석하여 상대평가 점수화 지표화한 QAIS(Quin AI Score)라는 자체 점수를 통해 종목을 추천한다.  친절한미정씨는 최근 자사주 의무 매입에 대한 상법개정에 따라 은행주들이 강세를 보이고 AI관련주인 2가지 모멘텀을 카카오뱅크가 가지고 있어 QAIS가 높아져 해당 종목을 추천했다고 전했다. 한경유레카에서 신규가입을 하고 친절한미정씨를 구독하면 1개월간 무료로 추천종목을 문자로 받아볼 수 있다.  본 글은 투자 참고용입니다.카카오페이 우리기술투자 SK하이닉스 삼성전자 두산에너빌리티", "경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에대한인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n종목추천 서비스 종합 플랫폼 한경유레카에 입점한 친절한미정씨가 전거래일(10일) 카카오뱅크를 추천하여 수익률 6.6%를 기록했다.친절한미정씨는 성장, 가치, 성과, 안정성, 모멘텀 등 기업의 가치를 평가하는 5개 중요 변수를 AI 학습 및 분석하여 상대평가 점수화 지표화한 QAIS(Quin AI Score)라는 자체 점수를 통해 종목을 추천한다.  친절한미정씨는 최근 자사주 의무 매입에 대한 상법개정에 따라 은행주들이 강세를 보이고 AI관련주인 2가지 모멘텀을 카카오뱅크가 가지고 있어 QAIS가 높아져 해당 종목을 추천했다고 전했다. 한경유레카에서 신규가입을 하고 친절한미정씨를 구독하면 1개월간 무료로 추천종목을 문자로 받아볼 수 있다.  본 글은 투자 참고용입니다.카카오뱅크 제주은행 푸른저축은행 기업은행 신한지주", '주주환원 내용인데. 최근 발표된 정부 세제개편안에 따르면 배당성향이 일정 수준 이상 되어야 그 주주가 분리과세 등 혜택을 볼 수 있는데 카카오뱅크가 여기에 해당하죠?<기자＞ 지난해 말 ‘성장중심의 밸류업 전략’을 발표한 바 있고, 당시 제시한 수준의 목표를 실현해가고 있습니다.이에 따르면, BIS 자기자본 비율이 직전연도 주요 시중은행 평균 상회할 경우 주주환원율을 2027년 50% 까지 확대한다는 계획도 함께 담겼었습니다.카카오뱅크는 지난해 말 기준 배당성향이 39%에 달합니다. 최근 정부가 발표한 세제개편안에 따르면 배당성향이 40% 이상인 기업에 투자하는 주주들은 배당소득 분리과세 혜택을 받게 되는데요. 카카오뱅크가 은행주중 유일하게 이 기준을 충족합니다. 이는 다른 은행지주 계열과 달리 별도의 자사주 매입소각 없이, 배당으로만 주주환원을 하고 있기 때문입니다.증권업계에선 올해 카카오뱅크의 배당성향이 45% 이상으로 늘어날 것으로 예상하고 있고요, 세제개편안이 이대로 통과되면 카카오뱅크 보유 주주는 분리과세 혜택을 볼 수 있을 것으로 예상됩니다.지금까지 보도국에서 한국경제TV 유주안입니다.유주안기자 jayou@wowtv.co.kr', "경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에대한인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n종목추천 서비스 종합 플랫폼 한경유레카에 입점한 친절한미정씨가 전거래일(10일) 카카오뱅크를 추천하여 수익률 6.6%를 기록했다.친절한미정씨는 성장, 가치, 성과, 안정성, 모멘텀 등 기업의 가치를 평가하는 5개 중요 변수를 AI 학습 및 분석하여 상대평가 점수화 지표화한 QAIS(Quin AI Score)라는 자체 점수를 통해 종목을 추천한다.  친절한미정씨는 최근 자사주 의무 매입에 대한 상법개정에 따라 은행주들이 강세를 보이고 AI관련주인 2가지 모멘텀을 카카오뱅크가 가지고 있어 QAIS가 높아져 해당 종목을 추천했다고 전했다. 한경유레카에서 신규가입을 하고 친절한미정씨를 구독하면 1개월간 무료로 추천종목을 문자로 받아볼 수 있다.  본 글은 투자 참고용입니다.한화솔루션 오가노이드사이언스 제주은행 한화손해보험 카카오", '인터넷전문은행 카카오뱅크가 올해 상반기 역대 최대 실적을 냈다.카카오뱅크는 올 2분기 순이익이 1263억원으로 집계됐다고 6일 공시했다. 이는 전년 동기(1202억원)보다 5.1% 증가한 수치다. 올해 상반기 순이익은 2637억원으로 전년 동기(2314억원)보다 14% 늘었다. 반기 기준 역대 최대 기록이다.카카오뱅크의 상반기 영업수익은 1조5625억원으로 나타났다. 이 중 이자수익은 9999억원으로 전년 동기(1조204억원)보다 2% 줄었다. 대출 잔액이 늘었지만 시장금리가 전반적으로 하락한 영향이라고 카카오뱅크 측은 설명했다.2분기 순이자마진(NIM)은 1.92%로 직전 분기보다 0.17%포인트 축소했다. 반면 상반기 비이자수익은 5626억원으로 전년 동기(4315억원)보다 30.4% 급증했다. 카카오뱅크는 대출·투자·지급결제 등 다양한 부문에서 플랫폼 역량이 강화돼 펌뱅킹·오픈뱅킹·광고 수익이 고르게 성장했다고 설명했다.상반기 수수료·플랫폼 수익은 전년 동기 대비 8.3% 늘어난 1535억원 수준이다. 영업수익에서 비이자수익이 차지하는 비중도 36%로 확대했다. 올 2분기 기준 고객 수는 2586만명, 월간 활성 이용자(MAU)는 1990만명이다. 같은 기간 수신 잔액은 63조7000억원, 여신 잔액은 44조8000억원으로 집계됐다.김태림 기자 tae@hankyung.com']
이 뉴스들 중에서 "삼성생명"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성생명가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['삼성생명(032830)이 최근 안정적인 실적 흐름과 재무 건전성을 바탕으로 주가 강세 흐름을 보이고 있다. 보험 업계 전반이 고금리 환경 속에서 자산 운용 수익이 확대되는 가운데, 삼성생명은 대형 보험사로서 구조적 강점을 다시금 입증했다는 평가다.올해 1분기 삼성생명은 보험이익과 투자이익 모두에서 견조한 성과를 기록했으며, 특히 건강보험 등 보장성 상품 확대 전략이 신계약 가치를 높이며 수익성 개선에 기여했다는 분석이 나온다. 또한, 지급여력비율(RBC) 역시 업계 평균을 상회하며 자본 건전성 측면에서도 안정적인 상태를 유지 중이다.증권가에서는 삼성생명이 높은 배당 성향과 함께 장기 투자 매력을 갖춘 종목으로 다시 조명받고 있다고 평가한다. 최근 자회사 지분 정리 가능성이나 지배구조 이슈 등도 일부 해소되면서, 오히려 중장기 투자자 입장에서 불확실성이 줄었다는 점에서 긍정적이라는 의견이 우세하다.다만 보험업 특성상 금리 민감도가 높고, 회계기준(IFRS17) 정착 과정에서 단기 실적 변동 가능성은 남아 있는 만큼, 시장 변동성과의 연동성은 주의 깊게 살펴볼 필요가 있다.결론적으로, 삼성생명은 내재가치 대비 저평가 매력이 부각되고 있는 대표 보험주로서, 건실한 재무구조와 보수적 경영 전략이 현시점에서 다시금 주목받고 있다.POSCO홀딩스, 칩스앤미디어, 산일전기, 대한항공, 삼성물산무료상담', '삼성생명(032830)이 최근 안정적인 실적 흐름과 재무 건전성을 바탕으로 주가 강세 흐름을 보이고 있다. 보험 업계 전반이 고금리 환경 속에서 자산 운용 수익이 확대되는 가운데, 삼성생명은 대형 보험사로서 구조적 강점을 다시금 입증했다는 평가다.올해 1분기 삼성생명은 보험이익과 투자이익 모두에서 견조한 성과를 기록했으며, 특히 건강보험 등 보장성 상품 확대 전략이 신계약 가치를 높이며 수익성 개선에 기여했다는 분석이 나온다. 또한, 지급여력비율(RBC) 역시 업계 평균을 상회하며 자본 건전성 측면에서도 안정적인 상태를 유지 중이다.증권가에서는 삼성생명이 높은 배당 성향과 함께 장기 투자 매력을 갖춘 종목으로 다시 조명받고 있다고 평가한다. 최근 자회사 지분 정리 가능성이나 지배구조 이슈 등도 일부 해소되면서, 오히려 중장기 투자자 입장에서 불확실성이 줄었다는 점에서 긍정적이라는 의견이 우세하다.다만 보험업 특성상 금리 민감도가 높고, 회계기준(IFRS17) 정착 과정에서 단기 실적 변동 가능성은 남아 있는 만큼, 시장 변동성과의 연동성은 주의 깊게 살펴볼 필요가 있다.결론적으로, 삼성생명은 내재가치 대비 저평가 매력이 부각되고 있는 대표 보험주로서, 건실한 재무구조와 보수적 경영 전략이 현시점에서 다시금 주목받고 있다.카카오, 동방, 미래에셋증권, 뉴엔AI, 우리금융지주무료상담', '삼성생명(032830)이 최근 안정적인 실적 흐름과 재무 건전성을 바탕으로 주가 강세 흐름을 보이고 있다. 보험 업계 전반이 고금리 환경 속에서 자산 운용 수익이 확대되는 가운데, 삼성생명은 대형 보험사로서 구조적 강점을 다시금 입증했다는 평가다.올해 1분기 삼성생명은 보험이익과 투자이익 모두에서 견조한 성과를 기록했으며, 특히 건강보험 등 보장성 상품 확대 전략이 신계약 가치를 높이며 수익성 개선에 기여했다는 분석이 나온다. 또한, 지급여력비율(RBC) 역시 업계 평균을 상회하며 자본 건전성 측면에서도 안정적인 상태를 유지 중이다.증권가에서는 삼성생명이 높은 배당 성향과 함께 장기 투자 매력을 갖춘 종목으로 다시 조명받고 있다고 평가한다. 최근 자회사 지분 정리 가능성이나 지배구조 이슈 등도 일부 해소되면서, 오히려 중장기 투자자 입장에서 불확실성이 줄었다는 점에서 긍정적이라는 의견이 우세하다.다만 보험업 특성상 금리 민감도가 높고, 회계기준(IFRS17) 정착 과정에서 단기 실적 변동 가능성은 남아 있는 만큼, 시장 변동성과의 연동성은 주의 깊게 살펴볼 필요가 있다.결론적으로, 삼성생명은 내재가치 대비 저평가 매력이 부각되고 있는 대표 보험주로서, 건실한 재무구조와 보수적 경영 전략이 현시점에서 다시금 주목받고 있다.삼성생명, 동양철관, 신한지주, 우리기술, 달바글로벌무료상담', '◆ 최근 애널리스트 분석의견- 2Q25 Preview: 이상 무(無) - 한국투자증권, 매수07월 09일 한국투자증권의 홍예란 애널리스트는 삼성생명에 대해 "순이익 6,634억원으로 컨센서스 6% 하회. 건강보장 비중 지속 상승하는 점 고무적"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'150,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '활용한 인스타그램 콘텐츠는 브랜드의 정체성을 2030세대들에게 더욱 가깝고 친숙하게 풀어냈다는 평가를 받는다. 「랜덤 음료 뽑기」, 「직장인 명언 시리즈」 등 직장인의 일상과 감정을 유쾌하게 풀어낸 콘텐츠는 여러차례 공유되며 높은 인기를 얻고 있다.삼성생명 관계자는 “보험이라는 어려운 주제를 젊은 세대가 공감할 수 있는 콘텐츠 언어로 쉽게 풀어내기 위해 노력하고 있다”면서 “앞으로도 고객의 일상에 응원과 감동을 전하는 미디어 콘텐츠를 통해 ‘라이프 파트너’로서 삼성생명의 이미지를 확대해 나갈 것”이라고 말했다.']
이 뉴스들 중에서 "메리츠금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 메리츠금융지주가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['사진=한경DB\n\n                금융당국이 메리츠화재 전 사장 등을 검찰에 고발하기로 했다. 자사의 합병정보를 이용해서 시세차익을 봤다는 혐의다.17일 금융권에 따르면 금융위원회 산하 증권선물위원회(증선위)는 전날 정례회의에서 메리츠화재 전 사장 A씨와 임원 B씨를 자본시장법상 미공개정보 이용행위 금지 위반 혐의로 검찰에 고발·통보하기로 결정했다.이들은 메리츠금융지주 합병 계획 발표를 앞두고 주식을 대거 사들였다가, 주가가 오르자 매도해 시세차익 수억원을 본 것으로 알려졌다.앞선 2022년 11월 메리츠금융지주는 메리츠증권과 메리츠화재를 완전 자회사로 편입한다는 방침과 함께 주주환원 계획을 발표한 바 있다. 발표가 있은 다음날 3개 종목은 상한가를 기록했다.당사자들은 "합병계획을 모르고 주식을 샀다"는 취지로 소명했지만, 금융당국은 금융사 고위 임원에는 더욱 엄정한 기준을 적용해야 한다고 봤다.신민경 한경닷컴 기자 radio@hankyung.com', '사진=메리츠화재금융당국이 자사 합병 정보를 이용해 수억원대 시세차익을 챙긴 혐의로 메리츠화재 전직 사장 등을 검찰에 고발했다.17일 금융당국과 금융권에 따르면 금융위원회 산하 증권선물위원회(증선위)는 전날 정례회의를 열고 메리츠화재 전 사장 A씨와 임원 B씨를 자본시장법상 미공개정보 이용행위 금지 위반 혐의로 검찰에 고발하기로 결정했다.이들은 메리츠금융지주의 합병 계획 발표 직전 가족 명의까지 동원해 주식을 대거 사들였다가 주가가 오르자 이를 되팔아 각각 5억원이 넘는 차익을 얻은 것으로 알려졌다.당사자들은 “합병 계획을 모르고 주식을 샀다”고 항변했으나 금융당국은 이들의 기존 주식 거래 패턴과 가족 계좌의 이례적인 매매 정황 등을 고려했을 때 해당 매매 행위가 일반적이지 않다고 봤다.증선위는 합병을 앞두고 자사주를 매입해 시세차익을 챙긴 다른 메리츠화재 임원 2명과 직원 1명도 검찰에 통보했다.메리츠금융지주는 2022년 11월 메리츠증권과 메리츠화재를 완전 자회사로 편입한다는 방침과 함께 대규모 주주환원 계획을 발표했다. 발표 다음 날 관련 3개 종목은 모두 상한가를 기록했다.김태림 기자 tae@hankyung.com', '▶마켓인사이트 7월 17일 오후 3시 3분금융당국이 2022년 메리츠금융지주 합병 정보를 미리 알고 주식을 사들여 수억원의 시세 차익을 얻은 메리츠화재 전 사장 등 임원들을 검찰에 고발한다.17일 금융당국과 금융권에 따르면 금융위원회 산하 증권선물위원회는 전날 정례회의에서 메리츠화재 전 사장 이모씨와 임원 등을 자본시장법상 미공개 정보 이용 행위 금지 위반 혐의로 검찰에 고발·통보하기로 결정했다.이들은 메리츠금융지주 합병 계획을 발표하기 전에 가족 명의까지 동원해 미리 관련 주식을 대규모로 사들였다가 합병 발표 이후 주가가 오르자 팔았다. 이를 통해 수억원의 시세 차익을 본 것으로 전해졌다.메리츠금융지주는 2022년 11월 상장 자회사이던 메리츠증권과 메리츠화재를 지분 100%를 보유한 완전자회사로 편입했다. 발표 이튿날 메리츠금융지주, 메리츠증권, 메리츠화재 등은 나란히 상한가로 치솟았다.이들은 합병 계획과 무관하게 해당 주식을 거래했다고 항변한 것으로 알려졌다. 그러나 금융당국은 금융회사 고위 임원의 비위 행위에는 더욱 엄정한 기준을 적용해야 한다고 봤다.최석철 기자 dolsoi@hankyung.com', '외국인 투자자는 16일 거래소에서 KB금융, 현대차, 메리츠금융지주 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 KB금융, 현대차, 메리츠금융지주, 삼성SDI, NAVER, 우리금융지주, 삼성중공업, 풍산, 두산에너빌리티, 한화솔루션등이다.이중에 운수장비 업종에 속한 종목이 2개 포함되어 있다.NAVER, 풍산, DL이앤씨 등은 전일 대비 주가가 상승했고, KB금융, 현대차, 메리츠금융지주 등은 주가가 하락했다.[07월16일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '메리츠금융의 주주 환원 정책이 시장의 밸류업 교과서로 자리 잡고 있다. 확실한 실적과 주주친화적 행보, 주가 상승이라는 삼박자를 고루 갖춘 메리츠식 밸류업 정책은 국내 금융 시장에 적잖은 반향을 일으키는 중이다.']
이 뉴스들 중에서 "현대모비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대모비스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['영상 모듈 닫기\n\n\n\n\n\n\n\n\n\n                <앵커>현대차와 기아의 2분기 영업이익이 두 자릿수 감소세를 보이며 자동차 관세에 직격탄을 맞았습니다.그런데 차 부품사인 현대모비스의 경우 영업익이 37% 급증하며 그 배경에 관심이 모아지고 있습니다.산업부 배창학 기자 나와 있습니다.배 기자, 현대모비스 먼저 살펴보죠.2분기 실적 얼마나 잘 나왔습니까?<기자>현대모비스는 오늘 2분기 매출액 약 15조 9,400억 원, 영업이익 약 8,700억 원을 기록했다고 공시했습니다.\n                    \n\n\n\n\n                지난해 같은 기간과 비교하면 매출은 9%, 영업익은 37% 증가했습니다.영업익의 경우 분기 기준 역대 최대 수치입니다.\n                    \n\n\n\n\n                상반기 누적 실적도 매출 31조 원, 영업익 1조 7천억 원을 내며 수익성이 크게 개선됐습니다.미국이 차에 이어 부품에도 25% 관세를 부과해 실적에 타격이 있을 것이라는 예측이 빗나간 겁니다.', '◆ 최근 애널리스트 분석의견- 공매도를 이겨내며 우상향 중, 최선호주 유지 - 키움증권, BUY07월 10일 키움증권의 신윤철 애널리스트는 현대모비스에 대해 "현대모비스는 2025년 8월 27일로 2025 CEO Investor Day 개최일을 공시했다. 상호관세 부과 시작일(8월 1일) 이후에 진행 예정인 행사이기에 자동차 및 자동차부품 품목관 세율에 대한 양국 간 최종 협의 역시 마무리된 시점일 가능성이 높다. 만약 품목관세율이 기대보다 높은 수준에서 확정될 경우, 경영진은 행사를 통해 품목관세 업황에서 현대 모비스가 자동차 섹터 내 가장 안정적인 투자 선택지임을 어필할 필요가 있다."이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'385,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.', '현대모비스 제공\n\n현대모비스는 올해 2분기 매출 15조9362억원, 영업이익 8700억원을 달성했다고 25일 밝혔다. 지난해 같은 기간 대비 매출과 영업이익이 각각 8.7%, 36.8% 증가했다.북미 전동화 공장의 가동이 본격화되고, 고부가가치 전장 부품 공급이 확대되는 등 제품믹스 효과로 실적개선을 견인했다.여기에 우호적 환율 환경에서 사후서비스(AS) 부품의 글로벌 판매 확대와 전사적인 수익성개선 활동이 성과로 이어지면서 영업이익도 대폭 상승했다.현대모비스의 상반기 매출액도 30조6883억원, 영업이익 1조6467억원을 달성했고, 지난해 같은 기간 대비 각각 7.6%, 39.7% 증가했다.현대모비스는 "미래 모빌리티 경쟁력 강화를 위해 지난 수년간 연구개발과 글로벌 신거점 확충 등 시설투자도 지속해서 확대한 결과"라고 설명했다.현대모비스는 올해 상반기까지 현대차와 기아를 제외한 글로벌 고객사를 대상으로 21억2000달러의 수주 성과를 기록했다. 이는 연간 목표 금액인 74억5000달러의 약 30% 수준이다.현대모비스 관계자는 “글로벌 관세 이슈와 전기차 수요 둔화 등의 영향으로 주요 고객사의 프로젝트가 일부 이연되기도 했지만, 대규모 수주 일정이 하반기에 집중되어 있어 연간 목표 달성을 위해 지속해서 노력할 것”이라고 설명했다.현대모비스는 올해 초 발표한 주주가치 제고 정책의 일환으로 중간배당액을 기존 1000원에서 1500원으로 확대한다고 발표했다. 총 1100억원 규모의 자기주식도 매입해 전량 소각하고, 기존 보유분인 자기주식 70만주도 추가로 소각할 예정이다.현대모비스는 다음 달 27일 여의도 페어몬트호텔에서 \'2025 CEO 인베스터데이\'를 연다. 이규석 사장이 미래 성장전략 등을 주제로 주주들과 이해관계자들에게 직접 나서 소통할 예정이다.최수진 한경닷컴 기자 naive@hankyung.com', '※Today\'s Pick은 매일 아침 여의도 애널리스트들이 발간한 종목분석 보고서 중 투자의견 및 목표주가가 변경된 종목을 위주로 한국경제 기자들이 핵심 내용을 간추려 전달합니다.👀주목할 만한 보고서📋📈📉현대모비스- "상법 개정의 나비효과 "📈목표주가 : 31만원→ 39만원(상향)  / 현재주가 : 30만9500원    투자의견 : 매수(유지) / SK증권[체크 포인트]-올 2분기 매출 전년동기 대비 2.5%, 영업이익 7.4% 상승 예상. -관세 영향은 완성차보다 적어. 직접적 노출액은 매출액의 6% 수준. -앞으로 현대차그룹 지배구조 최상단에 위치할 가능성. -향후 현대차그룹의 지배구조 개편은 상법개정 등 흐름에서 소액주주들이 불리할 가능성 낮아. -자동차섹터에서 상법개정이 주가가 가장 긍정적인 영향을 미치는 기업. -배당소득세 분리과세 개정안 통과될 경우 주주환원 정책 상향 가능성도. 하이브-"실적은 주춤, 하지만 모멘텀은 여전히 유효"📋 목표주가: 36만원→36만원(유지)  / 현재 주가 : 27만7000원    투자의견 : 매수(유지) / 한화투자증권[체크 포인트]-2분기 실적은 영업이익 기준으로 시장 기대치 하회 추정. -내년을 바라보는 모멘텀은 여전. -BTS는 최근 내년 봄에 새 앨범 발매, 이후 월드투어 스케줄 시사. -앨범·콘서트 등 직접매출 비롯해 MD, 콘텐츠, 멤버십 등 간접매출 확대도 가파를 전망. -빅히트뮤직에선 올 3분기 남자 아이돌이 데뷔 예정. -매출군이 앨범에서 MD로 옮겨가는 구간. -시장 기대치와 실제 실적 사이 괴리가 좁혀지는 데엔 시간 소요되는 중. KT-"서행할 차례"📈목표주가 : 6만2000원→6만6000원(상향)   / 현재주가 : 5만5600원    투자의견 : 매수(유지) / 유진투자증권[체크 포인트]-부동산 이익, 구조조정 통한 체질개선 등 재료가 대부분 소화.-상반기 대비 하반기 상승동력은 약해질 전망. -비핵심자산 유동화를 통한 주주환원은 중장기적 유효, 단기 실현성은 낮아. -2분기 분기배당 주당 600원 예상, 직전분기와 동일, 전년동기 대비 +20%. -AI는 국내 시장 경쟁 심화와 실질적 역량 검증 부족으로 기대감 미반영 상태.  -3분기는 SK텔레콤 영업 재개, 단통법 폐지, 신규 휴대폰 출시 등 주요 이벤트 집중.-마케팅비가 일시적으로 증가할 전망.  KT&G -"해외궐련 순항 + 추경 모멘텀 + 주주환원 콜라보 "📋 목표주가:', '[속보] 현대모비스, 2Q 영업익 8700억원 전년비 36.8% 증가박수빈 한경닷컴 기자 waterbean@hankyung.com']
이 뉴스들 중에서 "현대글로비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대글로비스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']

In [80]:
before_lst[0]

Document(id='31e5a84962c84ec540a883b882579f4c', metadata={'title': '더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트', 'original_idx': 245, 'chunk_idx': 1, 'label': '1', 'ticker': '우리금융지주', 'Date': '2025-07-09', 'url': 'https://www.hankyung.com/article/2025070981175'}, page_content='<앵커> 오늘 금융지주 주가가 오전에 잠시 조정받는 듯했는데 KB금융 제외하곤 낙폭을 줄여가는 모습입니다. 앞서 최민정 기자 언급한 자사주 의무 소각 관련해 금융지주들에는 어떤 영향이 있을지 경제부 유주안 기자와 이야기 나눠봅니다. 금융지주들은 자사주 매입과 소각에 꽤 적극적인데, 보유중인 자사주의 비중은 어떻습니까?<기자>4대 금융지주 자사주 보유 현황(KB 4.54%, 신한 2.09%, 하나 3.77%, 우리 1.16%)은, 보시다시피 비중이 크다고 보이진 않습니다.자사주 소각 의무화 추진에 따른 수혜주로 꼽히는 미래에셋(22.98) 대신(25.12) 신영(52.58%) 등에 비하면 매우 작은 수준이고요, 일반지주사들(티와이홀딩스 29.79%, SK 24.8%, 롯데지주 27.37% 등)에 비해서도 비중이 낮습니다.과거 역사를 살펴보면 금융주에 있어서는 자사주 ‘지배의 도구’보다는 인수합병 때 주식교환을 하기 위해, 전략적 투자자와 주식을 스왑하는 차원에서 일정 부분 보유해왔던 것을 알 수 있고요, 최근 들어서는 매입하면 바로 소각해서 주식의 가치를 올리는, 주주환원의 수단으로 자사주를 활용해 왔습니다.따라서, 자사주 소각 의무화에 따른 강제성 측면에서 금융지주에 미치는 단기적 직접적 영향은 크지 않겠습니다. 중장기적으로 볼 때 금융지주의 주주환원에 보다 힘이 실릴 것이란 기대감으로 이어질 수 있는데요,정책이 추구하는 목표를 이미 금융지주사들이 실행해 옮기고 있는 것이고, 향후 상장사들 사이에 자사주 매입소각이 보편화되면 재무적 여력과, 주주환원에 대한 강한 의지를 가진 금융사들이 더 적극적인 주주환원을 펼칠 수 있는 배경이 될 수 있을 것입니다.또한, 정부가 함께 추진중인 배당소득 분리과세 정책은 배당성향이 높고, 분기배당에 적극적인 금융주에게 특히 긍정적인 정책으로 받아들여지고 있습니다.<앵커> 어제 삼성전자 실적으로 인해 다소 가라앉은 분위기로 어닝시즌 개막되었는데요. 금융주 실적은 어떨 걸로 전망됩니까?<기자> 4대 지주만 놓고 볼 때, 당초 2분기는 좀 쉬어갈 것으로 예상이 되었습니다. 이는 2024년 2분기에 실적이 워낙 좋았던 것에 대한 기저효과와 더불어, 시중금리가 내려가면서 이자이익이 축소될 것으로 예상되었기 때문입니다.에프앤가이드 취합 컨센서스로 보면 KB금융의 2분기 당기순이익이 전년동기대비 약 5% 감소한 1조 6300억원, 우리금융지주 약 9% 감소한 8700억원으로 전망이')

In [81]:
rerank_df_before = pd.DataFrame(list(map(lambda x: x.metadata,before_lst)))

In [82]:
rerank_df_before

,title,original_idx,chunk_idx,label,ticker,Date,url
0,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",245,1,1,우리금융지주,2025-07-09,https://www.hankyung.com/article/2025070981175
1,대출 수익성 악화에…4대 금융 실적 꺾였다,158,0,1,우리금융지주,2025-07-15,https://www.hankyung.com/article/2025071501731
2,4대금융 2분기 순익 5.4조…사상 최대 실적,475,0,1,우리금융지주,2025-07-25,https://www.hankyung.com/article/2025072528861
3,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",237,0,1,우리금융지주,2025-07-14,https://www.hankyung.com/article/202507145874L
4,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",245,3,1,우리금융지주,2025-07-09,https://www.hankyung.com/article/2025070981175
...,...,...,...,...,...,...,...
417,[인천테크노파크 2025년 인천 라이징스타 선정기업] 실시간 항공난류 진단 및 예측...,3412,2,1,현대오토에버,2025-08-07,https://magazine.hankyung.com/job-joy/article/...
418,[인천테크노파크 2025년 인천 라이징스타 선정기업] 실시간 항공난류 진단 및 예측...,3412,3,1,현대오토에버,2025-08-07,https://magazine.hankyung.com/job-joy/article/...
419,"화우, 'M&A 스타' 이진국·윤소연 변호사 영입",3063,0,0,현대오토에버,2025-08-04,https://www.hankyung.com/article/202508049948i
420,[인천테크노파크 2025년 인천 라이징스타 선정기업] 실시간 항공난류 진단 및 예측...,3412,0,1,현대오토에버,2025-08-07,https://magazine.hankyung.com/job-joy/article/...
421,고금리 OUT! 증권사 신용대출 3%대로 전환하는 방법,3211,1,1,현대오토에버,2025-07-24,https://www.hankyung.com/article/202507248234a

In [85]:
VecDB = vectordb._collection
total_results = VecDB.get(
         include = ['documents','metadatas']   
        )

In [86]:
total_df = pd.DataFrame(total_results['metadatas'])

In [106]:
total_df

,original_idx,Date,title,ticker,label,url,chunk_idx
0,236,2025-08-07,금융사 채권 발행 봇물…저금리에 자본 확충,우리금융지주,1,https://www.hankyung.com/article/2025080765681,0
1,236,2025-08-07,금융사 채권 발행 봇물…저금리에 자본 확충,우리금융지주,1,https://www.hankyung.com/article/2025080765681,1
2,236,2025-08-07,금융사 채권 발행 봇물…저금리에 자본 확충,우리금융지주,1,https://www.hankyung.com/article/2025080765681,2
3,413,2025-08-07,"07일, 거래소 외국인 순매수상위에 전기,전자 업종 4종목",우리금융지주,1,https://www.hankyung.com/article/202508078176L,0
4,209,2025-08-06,"[마켓PRO] Today's Pick : ""에코프로비엠, 3분기 흑자전환 기대""",우리금융지주,1,https://www.hankyung.com/article/202508063668i,0
...,...,...,...,...,...,...,...
1899,4130,2025-07-10,"현대글로비스, '대·중소기업 안전 상생' 고용부 장관상",현대글로비스,1,https://www.hankyung.com/article/202507109861i,0
1900,4485,2025-07-10,"현대글로비스, 협력사 안전 상생 최우수기업으로 고용부장관상 수상",현대글로비스,1,https://www.hankyung.com/article/202507109010P,0
1901,4080,2025-07-09,美 관세에 웃는 '현대차 삼형제',현대글로비스,1,https://www.hankyung.com/article/2025070982441,0
1902,4260,2025-07-08,9~10% 주식 관련 대출에서 3%대 대출로 교체,현대글로비스,1,https://www.hankyung.com/article/202507083739a,0
1903,4260,2025-07-08,9~10% 주식 관련 대출에서 3%대 대출로 교체,현대글로비스,1,https://www.hankyung.com/article/202507083739a,1

In [88]:
rerank_eval = []

In [89]:
for kind in retriver_target:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target = rerank_df_before[rerank_df_before.ticker==kind]
    rerank_eval.append(eval_reranker_chunk(total_df_target,rerank_df_target))

total_rel_pool : 191
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 94
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 0 0 1]
total_rel_pool : 119
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 110
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 0 0 0 1 1 1 1]
total_rel_pool : 49
y_topk : [1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 0
 1 1 1 1 1 0 0 0 0 1 0 1 1]
total_rel_pool : 122
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 60
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 949
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 20
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1]

In [90]:
rerank_eval_con = dict(zip(retriver_target,rerank_eval))

In [91]:
pd.DataFrame(rerank_eval_con)

,우리금융지주,삼성화재,카카오뱅크,삼성생명,메리츠금융지주,현대모비스,현대글로비스,SK하이닉스,현대오토에버
Precision@50,1.00000,0.840000,0.980000,0.920000,0.720000,0.980000,0.960000,1.000000,0.909091
Recall@50(pool),0.26178,0.446809,0.411765,0.418182,0.734694,0.401639,0.800000,0.052687,1.000000
MRR@50,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
MAP@50,1.00000,0.762385,0.969249,0.911969,0.611900,0.969916,0.925175,1.000000,0.985283
nDCG@50,1.00000,0.978525,0.997838,0.998426,0.956682,0.997991,0.991895,1.000000,0.996850
PoolSize,219.00000,123.000000,122.000000,193.000000,66.000000,128.000000,63.000000,968.000000,22.000000
PoolRelevant,191.00000,94.000000,119.000000,110.000000,49.000000,122.000000,60.000000,949.000000,20.000000
TopK,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,22.000000
TopKRelevant,50.00000,42.000000,49.000000,46.000000,36.000000,49.000000,48.000000,50.000000,20.000000

Re-ranker 모델 사용 후

In [92]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=50)
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_total
)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

검색 유사도 측정
 - 이유 : 적정한 조건을 찾기 위함

In [93]:
scored_docs = []

retriever가 내부에서 메타데이터 필터(where/filter) 를 쓰고 있는데, 거기에 ['우리금융지주', ...] 같은 리스트를 그대로 넣어둔 상태예요. 대부분의 벡터스토어(특히 Chroma/LangChain)는 where/filter 값이 단일 값(str/int/float) 이거나 연산자 표현식이어야 하고, 리스트는 $in 같은 연산자로 감싸줘야 합니다. 그래서 get_relevant_documents() 부를 때마다 같은 잘못된 필터가 적용되어 터진 거죠.

빠른 해결책 (권장)
루프마다 단일 종목으로 필터를 바꿔서 조회하세요.

In [94]:
for ticker in retriver_target:
    retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs.append(dd)
    #scored_docs.sort(key=lambda x: (x.metadata[''],x.metadata["relevance_score"]), reverse=True)

이 뉴스들 중에서 "우리금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 우리금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성화재"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성화재가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "카카오뱅크"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 카카오뱅크가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성생명"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성생명가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "메리츠금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 메리츠금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대모비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대모비스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대글로비스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대글로비스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대오토에버"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대오토에버가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [95]:
# 4) 확인 - raw data
for i, d in enumerate(scored_docs, 1):
    if d.metadata['ticker'] == 'SK하이닉스':
        print(f"{i:02d} | ticker : {d.metadata['ticker']}| original_idx : {d.metadata['original_idx']} | chunk_idx : {d.metadata['chunk_idx']}| score : {d.metadata['relevance_score']:.4f} | {d.metadata.get('title')}")

351 | ticker : SK하이닉스| original_idx : 3807 | chunk_idx : 0| score : 0.0024 | SK하이닉스 "올 하반기도 D램 긍정적 업황…내년 HBM 수요 대비 선제 투자"
352 | ticker : SK하이닉스| original_idx : 3596 | chunk_idx : 0| score : 0.0721 | SK하이닉스 37만원까지 간다고?…종토방 개미들 '술렁' [선한결의 이기업 왜이래]
353 | ticker : SK하이닉스| original_idx : 3967 | chunk_idx : 0| score : 0.3013 | '꿈의 직장'서 밀린 삼성전자…1위는 '이곳'
354 | ticker : SK하이닉스| original_idx : 3541 | chunk_idx : 0| score : 0.1787 | SK하이닉스, 2분기 사상 최대 실적에 주가 3% 강세
355 | ticker : SK하이닉스| original_idx : 3922 | chunk_idx : 0| score : 0.3585 | SK하이닉스, AI 메모리 힘입어 실적·주가 동반 강세 지속
356 | ticker : SK하이닉스| original_idx : 3955 | chunk_idx : 0| score : 0.0815 | [마켓PRO] "주가조정은 기회"…고수들, SK하이닉스·한화엔진 매수
357 | ticker : SK하이닉스| original_idx : 3653 | chunk_idx : 0| score : 0.0639 | [속보] SK하이닉스, 2분기 역대 최대 매출·영업이익 달성
358 | ticker : SK하이닉스| original_idx : 3867 | chunk_idx : 1| score : 0.2453 | SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위
359 | ticker : SK하이닉스| original_idx : 3712 | chunk_idx : 1| score : 0.2636 | SK하이닉스, HBM 둔화 일축…"내년 2배 성장"
360 | ticker : SK하이닉스| original_idx : 3802 | chunk_idx : 1| score : 0.0948 | “지금 들어가도 될까?”…센터장들이 꼽은 '코스피 5000 대장주'[코스피5000 시대]
361 | ticker : SK하이닉스| original_idx : 3867 | chunk_idx : 2| score : 0.4554 | SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위
362 | ticker : SK하이닉스| original_idx : 3615 | chunk_idx : 0| score : 0.0895 | SK하이닉스, 일하고 싶은 기업 첫 1위..삼성전자 3위로 밀려나
363 | ticker : SK하이닉스| original_idx : 3746 | chunk_idx : 6| score : 0.0777 | 연준 독립성 훼손 우려에 금리 급등…"그림자 연준 될 수도"
364 | ticker : SK하이닉스| original_idx : 3587 | chunk_idx : 0| score : 0.1745 | 골드만삭스 '중립' 의견에…SK하이닉스 주가 5%대 급락
365 | ticker : SK하이닉스| original_idx : 3782 | chunk_idx : 0| score : 0.3340 | "HBM 주도" VS "독주 흔들"…하이닉스 놓고 엇갈린 전망
366 | ticker : SK하이닉스| original_idx : 3815 | chunk_idx : 0| score : 0.4317 | SK하이닉스, 삼성전자 제쳤다…메모리 시장 첫 '1위'
367 | ticker : SK하이닉스| original_idx : 3744 | chunk_idx : 0| score : 0.6015 | AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화
368 | ticker : SK하이닉스| original_idx : 3980 | chunk_idx : 0| score : 0.2721 | 05일, 외국인 거래소에서 SK하이닉스(+2.13%), 삼성SDI(+10.22%) 등 순매수
369 | ticker : SK하이닉스| original_idx : 3855 | chunk_idx : 1| score : 0.1822 | 개미들, SK하이닉스에 '1.2조' 올인할 때…외국인은 '반전'
370 | ticker : SK하이닉스| original_idx : 3615 | chunk_idx : 2| score : 0.0598 | SK하이닉스, 일하고 싶은 기업 첫 1위..삼성전자 3위로 밀려나
371 | ticker : SK하이닉스| original_idx : 3713 | chunk_idx : 0| score : 0.2748 | 17일, 기관 거래소에서 SK하이닉스(-8.95%), SK스퀘어(-8.73%) 등 순매도
372 | ticker : SK하이닉스| original_idx : 3806 | chunk_idx : 0| score : 0.2758 | 31일, 기관 거래소에서 SK하이닉스(+3.8%), KODEX 200선물인버스2X(+0.63%) 등 순매수
373 | ticker : SK하이닉스| original_idx : 3764 | chunk_idx : 0| score : 0.1113 | [심층분석] 에이치시티, SK하이닉스와 함께봐야 하는 이유
374 | ticker : SK하이닉스| original_idx : 3816 | chunk_idx : 0| score : 0.1612 | SK하이닉스, 2분기 영업이익 9.2조…사상 최대 실적 경신
375 | ticker : SK하이닉스| original_idx : 3855 | chunk_idx : 0| score : 0.1644 | 개미들, SK하이닉스에 '1.2조' 올인할 때…외국인은 '반전'
376 | ticker : SK하이닉스| original_idx : 3705 | chunk_idx : 2| score : 0.0367 | "삼성·마이크론 생산 늘리면 HBM 가격 최대 35% 하락"
377 | ticker : SK하이닉스| original_idx : 3791 | chunk_idx : 0| score : 0.1506 | 04일, 거래소 외국인 순매도상위에 전기,전자 업종 5종목
378 | ticker : SK하이닉스| original_idx : 3927 | chunk_idx : 1| score : 0.6722 | SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+]
379 | ticker : SK하이닉스| original_idx : 3618 | chunk_idx : 0| score : 0.0056 | [심층분석] 에이치시티, SK하이닉스와 함께봐야 하는 이유
380 | ticker : SK하이닉스| original_idx : 3586 | chunk_idx : 0| score : 0.3344 | 글로벌 반도체 리스크와 기술주 조정 장세 속 SK하이닉스
381 | ticker : SK하이닉스| original_idx : 3662 | chunk_idx : 2| score : 0.1100 | 골드만 비관론 정면 반박한 SK "HBM4 설비 투자 늘릴 것"
382 | ticker : SK하이닉스| original_idx : 3850 | chunk_idx : 0| score : 0.0506 | SK하이닉스 또 최대실적…"하반기 HBM 더 좋다"
383 | ticker : SK하이닉스| original_idx : 3610 | chunk_idx : 0| score : 0.1144 | "HBM 공급과잉 우려"…SK하이닉스 주가 급락
384 | ticker : SK하이닉스| original_idx : 3551 | chunk_idx : 2| score : 0.1144 | 골드만삭스 한마디에 주가 급락…SK하이닉스 개미들 '비명' [종목+]
385 | ticker : SK하이닉스| original_idx : 3916 | chunk_idx : 0| score : 0.2885 | SK하이닉스, HBM 독주와 AI 메모리 혁신 속 실적 ‘정점’ 전망
386 | ticker : SK하이닉스| original_idx : 3732 | chunk_idx : 0| score : 0.0032 | [심층분석] 에이치시티, SK하이닉스와 함께봐야 하는 이유
387 | ticker : SK하이닉스| original_idx : 3629 | chunk_idx : 4| score : 0.0106 | [마켓PRO] SK하이닉스, 시장 주도권 '잃을 것 vs 지킬 것'…증권가 갑론을박 [선한결의 이기업 왜이래]
388 | ticker : SK하이닉스| original_idx : 3584 | chunk_idx : 0| score : 0.0041 | [심층분석] 에이치시티, SK하이닉스와 함께봐야 하는 이유
389 | ticker : SK하이닉스| original_idx : 3670 | chunk_idx : 0| score : 0.3016 | SK하이닉스, AI 중심 수요·기술 우위 기반 실적 기대감이 반등 견인
390 | ticker : SK하이닉스| original_idx : 3605 | chunk_idx : 0| score : 0.2384 | "반도체 겨울" 경고와 반대로 가는 주가…모건·골드만은 왜?
391 | ticker : SK하이닉스| original_idx : 3724 | chunk_idx : 0| score : 0.6117 | '역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다
392 | ticker : SK하이닉스| original_idx : 3941 | chunk_idx : 0| score : 0.2922 | 골드만삭스 경고에 주춤한 SK하이닉스, HBM 경쟁 심화에 대한 경계감 확산
393 | ticker : SK하이닉스| original_idx : 3885 | chunk_idx : 0| score : 0.3146 | 25일, 거래소 외국인 순매도상위에 전기,전자 업종 8종목
394 | ticker : SK하이닉스| original_idx : 3989 | chunk_idx : 0| score : 0.0662 | [속보] SK하이닉스, 2분기 영업익 9조2129억…전년비 68.5%↑
395 | ticker : SK하이닉스| original_idx : 3973 | chunk_idx : 0| score : 0.1732 | 삼성전자·하이닉스 둘 다 담아야 하나…개미들 술렁이는 이유
396 | ticker : SK하이닉스| original_idx : 3725 | chunk_idx : 0| score : 0.1038 | [마켓PRO] 삼성전자 수주 '잭팟' 터졌다...협력사까지 쓸어담은 고수들
397 | ticker : SK하이닉스| original_idx : 3879 | chunk_idx : 0| score : 0.0026 | [심층분석] 에이치시티, SK하이닉스와 함께봐야 하는 이유
398 | ticker : SK하이닉스| original_idx : 3596 | chunk_idx : 3| score : 0.0558 | SK하이닉스 37만원까지 간다고?…종토방 개미들 '술렁' [선한결의 이기업 왜이래]
399 | ticker : SK하이닉스| original_idx : 3512 | chunk_idx : 0| score : 0.1189 | SK하이닉스, HBM 수요 자신감…AI 시대 '풀스택 메모리' 본격화
400 | ticker : SK하이닉스| original_idx : 3684 | chunk_idx : 1| score : 0.0330 | 코스피, 닷새 연속 올라 3230선 마감…4년만에 최고

### Re-Ranker 모델 측정

In [96]:
rerank_df = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs)))

In [97]:
rerank_df.ticker.value_counts()

ticker
우리금융지주     50
삼성화재       50
카카오뱅크      50
삼성생명       50
메리츠금융지주    50
현대모비스      50
현대글로비스     50
SK하이닉스     50
현대오토에버     22
Name: count, dtype: int64

In [98]:
rerank_df.head()

,Date,label,ticker,title,chunk_idx,original_idx,url,relevance_score
0,2025-07-09,1,우리금융지주,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",1,245,https://www.hankyung.com/article/2025070981175,0.113008
1,2025-07-15,1,우리금융지주,대출 수익성 악화에…4대 금융 실적 꺾였다,0,158,https://www.hankyung.com/article/2025071501731,0.010040
2,2025-07-25,1,우리금융지주,4대금융 2분기 순익 5.4조…사상 최대 실적,0,475,https://www.hankyung.com/article/2025072528861,0.215311
3,2025-07-14,1,우리금융지주,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",0,237,https://www.hankyung.com/article/202507145874L,0.602175
4,2025-07-09,1,우리금융지주,"더 커진 주주환원 기대감…금융주, 어닝시즌 관전포인트",3,245,https://www.hankyung.com/article/2025070981175,0.004671

In [99]:
rerank_df= rerank_df.sort_values(by=['ticker','relevance_score'],ascending=False)

In [100]:
rerank_df.shape

(422, 8)

In [241]:
rerank_df[rerank_df.ticker=='SK하이닉스'].head()

,chunk_idx,title,label,original_idx,ticker,url,Date,relevance_score
377,1,SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+],1,3927,SK하이닉스,https://www.hankyung.com/article/2025072510306,2025-07-25,0.672207
390,0,"'역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다",1,3724,SK하이닉스,https://magazine.hankyung.com/business/article...,2025-07-24,0.611750
366,0,"AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화",1,3744,SK하이닉스,https://www.hankyung.com/article/202507313103a,2025-07-31,0.601519
360,2,"SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위",1,3867,SK하이닉스,https://magazine.hankyung.com/job-joy/article/...,2025-07-28,0.455363
365,0,"SK하이닉스, 삼성전자 제쳤다…메모리 시장 첫 '1위'",1,3815,SK하이닉스,https://www.hankyung.com/article/2025073147077,2025-07-31,0.431711

In [179]:
rerank_df.ticker.value_counts()

ticker
SK하이닉스     50
메리츠금융지주    50
삼성생명       50
삼성화재       50
우리금융지주     50
카카오뱅크      50
현대글로비스     50
현대모비스      50
현대오토에버     22
Name: count, dtype: int64

In [180]:
rerank_df[rerank_df.ticker=='SK하이닉스'].label.value_counts()

label
1    49
0     1
Name: count, dtype: int64

In [83]:
VecDB = vectordb._collection
total_results = VecDB.get(
         include = ['documents','metadatas']   
        )

In [84]:
total_df = pd.DataFrame(total_results['metadatas'])

In [183]:
total_df.shape

(1904, 7)

In [184]:
total_df.ticker.value_counts()

ticker
SK하이닉스     968
우리금융지주     219
삼성생명       193
현대모비스      128
삼성화재       123
카카오뱅크      122
메리츠금융지주     66
현대글로비스      63
현대오토에버      22
Name: count, dtype: int64

In [185]:
total_df[total_df.ticker=='SK하이닉스'].label.value_counts()

label
1    797
0    171
Name: count, dtype: int64

In [101]:
import numpy as np
import pandas as pd

def _dcg_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    if L.size == 0: return 0.0
    discounts = 1.0 / np.log2(np.arange(2, L.size + 2))
    return float(np.sum(L * discounts))

def ndcg_at_k(labels, k=50):
    labels = np.asarray(labels)
    dcg  = _dcg_at_k(labels, k)
    idcg = _dcg_at_k(np.sort(labels)[::-1], k)
    return 0.0 if idcg == 0 else dcg / idcg

def precision_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    return float(L.mean()) if L.size else 0.0

def recall_at_k(labels, total_relevant, k=50):
    if not total_relevant or total_relevant <= 0: return 0.0
    return float(np.sum(np.asarray(labels)[:k])) / float(total_relevant)

def mrr_at_k(labels, k=50):
    L = np.asarray(labels)[:k]
    hit = np.where(L > 0)[0]
    return 0.0 if hit.size == 0 else 1.0 / (hit[0] + 1)

def map_at_k(labels, total_relevant, k=50):
    L = np.asarray(labels)[:k]
    if L.sum() == 0: return 0.0
    precisions, hit = [], 0
    for i, y in enumerate(L, start=1):
        if y:
            hit += 1
            precisions.append(hit / i)
    denom = max(1, min(total_relevant if total_relevant is not None else int(L.sum()), k))
    return float(np.sum(precisions) / denom)

def eval_reranker_chunk(pool_df, ranked_df, k=50, rank_col="rank", score_col="relevance_score"):
    # 1) 풀: label만 필요 (score/rank 불필요)
    total_rel_pool = int(
        pd.to_numeric(pool_df["label"], errors="coerce").fillna(0).clip(0,1).sum()
    )
    print(f'total_rel_pool : {total_rel_pool}')

    # 2) 랭크드: 순서가 필요 (rank 우선, 없으면 score로 정렬, 둘 다 없으면 현재 순서 사용)
    g = ranked_df.copy()
    if rank_col in g.columns:
        g = g.sort_values(rank_col, ascending=True)
    elif score_col in g.columns:
        g = g.sort_values(score_col, ascending=False)
        g[rank_col] = np.arange(1, len(g)+1)
    else:
        g[rank_col] = np.arange(1, len(g)+1)

    y_topk = pd.to_numeric(g["label"], errors="coerce").fillna(0).clip(0,1).astype(int).values[:k]
    print(f'y_topk : {y_topk}')
    return {
        f"Precision@{k}": precision_at_k(y_topk, k),
        f"Recall@{k}(pool)": recall_at_k(y_topk, total_rel_pool, k),
        f"MRR@{k}": mrr_at_k(y_topk, k),
        f"MAP@{k}": map_at_k(y_topk, total_rel_pool, k),
        f"nDCG@{k}": ndcg_at_k(y_topk, k),
        "PoolSize": int(len(pool_df)),
        "PoolRelevant": total_rel_pool,
        "TopK": int(min(len(g), k)),
        "TopKRelevant": int(y_topk.sum()),
    }

In [102]:
rerank_eval = []

In [103]:
for kind in retriver_target:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target = rerank_df[rerank_df.ticker==kind]
    rerank_eval.append(eval_reranker_chunk(total_df_target,rerank_df_target))

total_rel_pool : 191
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 94
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 0 1 0 1]
total_rel_pool : 119
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 110
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 0 0 1 1]
total_rel_pool : 49
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 0 0 0 0 0 0 1 0 0 0 0 1 0]
total_rel_pool : 122
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1]
total_rel_pool : 60
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 949
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 20
y_topk : [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1]

In [104]:
rerank_eval_con = dict(zip(Custer_Having_ticker_lst,rerank_eval))

In [105]:
pd.DataFrame(rerank_eval_con)

,우리금융지주,삼성화재,삼성생명,카카오뱅크,메리츠금융지주,현대모비스,현대오토에버,SK하이닉스,현대글로비스
Precision@50,1.00000,0.840000,0.980000,0.920000,0.720000,0.980000,0.960000,1.000000,0.909091
Recall@50(pool),0.26178,0.446809,0.411765,0.418182,0.734694,0.401639,0.800000,0.052687,1.000000
MRR@50,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
MAP@50,1.00000,0.767898,0.966335,0.895437,0.714515,0.979192,0.938764,1.000000,0.966561
nDCG@50,1.00000,0.980836,0.997134,0.994110,0.994518,0.999858,0.995489,1.000000,0.991779
PoolSize,219.00000,123.000000,122.000000,193.000000,66.000000,128.000000,63.000000,968.000000,22.000000
PoolRelevant,191.00000,94.000000,119.000000,110.000000,49.000000,122.000000,60.000000,949.000000,20.000000
TopK,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,22.000000
TopKRelevant,50.00000,42.000000,49.000000,46.000000,36.000000,49.000000,48.000000,50.000000,20.000000

# 요약문 실험 테스트 수행

## 1. original 본문 가져오기

In [297]:
test_ticker = '우리금융지주'

In [298]:
CrossEncoder_prompt_test = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [91]:
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
compressor = CrossEncoderReranker(model=model, top_n=20)

In [313]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
)

In [315]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt_test)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [24]:
def get_full_article_from_chroma(original_idx: int, kind : str, vectordb) -> dict:
    """original_idx 기준으로 chunk들을 모아 원문 복원"""
    # 1. 해당 article의 모든 chunk 가져오기
    VecDB = vectordb._collection
    results = VecDB.get(
      where = { "$and" : [ # 빈 쿼리로 전체 탐색
            {"original_idx": original_idx}, 
            {"ticker": kind}
            ]
         },
         include = ['documents','metadatas']   
        )
        
    if not results:
        return {"error": f"No chunks found for original_idx {original_idx}"}

    #print(results)
    #print(results['metadatas'][0]['chunk_idx'])

    # 4. 대표 metadata 하나 뽑아 저장
    return {
        "title": results['metadatas'][0]["title"],
        "url": results['metadatas'][0]["url"],
        "Date": results['metadatas'][0]["Date"],
        "ticker": results['metadatas'][0]["ticker"],
        "content": results['documents'][0]
    }

In [317]:
original_idxs = list(map(lambda x: x.metadata['original_idx'], compressed_docs))

In [318]:
top_n_original = [get_full_article_from_chroma(idx,kind=test_ticker,vectordb=vectordb) for idx in original_idxs]

In [320]:
top_n_original[:5]

[{'title': "'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",
  'url': 'https://www.hankyung.com/article/202507145874L',
  'Date': '2025-07-14',
  'ticker': '우리금융지주',
  'content': '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 296.2만주를 순매수했고, 개인들도 41.8만주를 순매수했다. 하지만 기관은 294.9만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 51.3%, 26.2%로 비중이 높다.더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'},
 {'title': "'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",
  'url': 'https://www.hankyung.com/article/202507084010L',
  'Date': '2025-07-08',
  'ticker': '우리금융지주',
  'content': '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'},
 {'title': '"우리금융지주, 연말로 갈수록 고배당 부각…목표가↑"-NH',
  'url': 'https://www.hankyung.com/article/2025070836976',
  'Date': '2025-07-08',
  'ticker': '우리금융지주',
  'content': '사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.com'},
 {'title': '대출 수익성 악화에…4대 금융 실적 꺾였다',
  'url': 'https://www.hankyung.com/article/2025071501731',
  'Date': '2025-07-15',
  'ticker': '우리금융지주',
  'content': 'KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기'},
 {'title': '“금리 하락에도 이익 증가” 금융지주, 실적 온도차',
  'url': 'https://magazine.hankyung.com/business/article/202507210813b',
  'Date': '2025-07-21',
  'ticker': '우리금융지주',
  'content': '서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요'}]

In [321]:
original_contents = list(map(lambda x: x['content'],top_n_original))

In [322]:
total_contents = ''.join(original_contents)

In [323]:
total_contents

'◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 296.2만주를 순매수했고, 개인들도 41.8만주를 순매수했다. 하지만 기관은 294.9만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 51.3%, 26.2%로 비중이 높다.더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.comKB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.※Today\'s Pick은 매일 아침 여의도 애널리스트들이 발간한 종목분석 보고서 중 투자의견 및 목표주가가 변경된 종목을 위주로 한국경제 기자들이 핵심 내용을 간추려 전달합니다.\n\n\n\n\n충북 오창에 위치한 에코프로비엠 본사. 사진=에코프로비엠KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 내며 분기 기준 사상 최대 실적 기록을 썼다. 이자이익 증가세가 사실상 멈췄지만, 환율이 안정된 덕분에 비이자이익이 15% 넘게 늘어난 영향이 크다는 분석이 나온다.25일 금융권에 따르면 4대 금융지주의 지난 2분기 순이익은 총 5조3954억원이었다. 지난해 같은 기간(5조1241억원)과 비교해 2713억원(5.3%) 늘었다. 4대 금융지주의 순이익 합산액이 5조3000억원을 넘은 것은 이번이 처음이다.금융지주별로 보면 하나금융의 순이익이 작년 2분기 1조347억원에서 올 2분기 1조1733억원으로 1386억원(13.4%) 늘어 가장 큰 증가폭을 보였다. 같은 기간 신한금융은 1조4255억원에서 1조5491억원으로 1236억원(8.7%) 불어났다. KB금융의 2분기 순이익은 1조7384억원으로 4대 금융지주 중 가장 많았지만, 전년 동기 대비로는 0.3% 증가하는 데 그쳤다. 우리금융의 순이익은 같은 기간 9315억원에서 9346억원으로 0.3% 늘었다.실적 증가를 이끈 것은 비이자이익이다. 4대 금융지주의 비이자이익은 작년 2분기 3조4264억원에서 올 2분기 3조9591억원으로 5327억원(15.5%) 증가했다. 원화가 강세 흐름을 보이면서 외화환산이익이 늘었다는 게 4대 금융지주의 공통된 설명이다. 반면 4대 금융지주의 올 2분기 이자이익은 전년 동기 대비 0.4% 늘어나는 데 그쳤다.정의진/김진성 기자 justjin@hankyung.com[커버스토리] 2025 밸류업 CEO 50\n\n\n\n\n\n\n\n\n\n\n\n<2025 밸류업 CEO 50 - 금융>11위 임종룡 우리금융지주업종명 금융지주취임일 주가(원) 11,010     최근 주가(원) 21,350     취임일 2023년 3월 24일주가수익률 93.9%배당수익률 21.8%총주주수익률 115.7%12위 빈대인 BNK금융지주업종명 금융지주취임일 주가(원) 6,250     최근 주가(원) 11,790     취임일 2023년 3월 17일주가수익률 88.6%배당수익률 20.5%총주주수익률 109.1%13위 양종희 KB금융업종명 금융지주취임일 주가(원) 54,100     최근 주가(원) 106,500     취임일 2023년 11월 21일주가수익률 96.9%배당수익률 10.4%총주주수익률 107.2%14위 정종표 DB손해보험업종명 보험취임일 주가(원) 65,300     최근 주가(원) 120,200     취임일 2023년 1월 1일주가수익률 84.1%배당수익률 18.5%총주주수익률 102.6%15위 김성태 기업은행업종명 은행취임일 주가(원) 9,560     최근 주가(원) 17,290     취임일 2023년 1월 3일주가수익률 80.9%배당수익률 21.4%총주주수익률 102.3% 16위 함영주 하나금융지주업종명 금융지주취임일 주가(원) 49,350     최근 주가(원) 80,000     취임일 2022년 3월 25일주가수익률 62.1%배당수익률 22.8%총주주수익률 84.9%17위 진옥동 신한지주업종명 금융지주취임일 주가(원) 35,750     최근 주가(원) 59,300 취임일 2023년 3월 23일주가수익률 65.9%배당수익률 13.5%총주주수익률 79.4%18위 박종문 삼성증권업종명 증권취임일 주가(원) 41,550     최근 주가(원) 67,700     취임일 2024년 3월 21일주가수익률 62.9%배당수익률 8.4%총주주수익률 71.4%19위 윤병운 NH투자증권업종명 증권취임일 주가(원) 12,350     최근 주가(원) 19,170     취임일 2024년 3월 27일주가수익률 55.2%배당수익률 7.7%총주주수익률 62.9%20위 박봉권 교보증권업종명 증권취임일 주가(원) 6,770     최근 주가(원) 8,450     취임일 2020년 2월 4일주가수익률 24.8%배당수익률 28.1%총주주수익률 52.9%출산정책 지원, 미 관세 소식, 스테이블코인 등등… 요즘처럼 뉴스 하나에 시장이 요동치는 시대엔, 방향을 잡아줄 확실한 나침반이 필요할 때! 매일 갈아타는 시장 주도주, 오늘도 놓칠 건가요?“불새와 함께라면, 상한가는 남의 얘기가 아닙니다.”\n\n\n\n\n \n\n👉 애경케미칼, 콜마홀딩스 적중의 비밀 확인! (클릭)한국증시의 다양한 대내외 변수 속에서도 높은 수익률과 압도적인 종목 적중률로 단숨에 개인투자자들의 주목을 받는 ‘불새’ 전문가!특히 화제가 되는 건 “내일의 상한가가 미리 보인다”는 평가.불새는 매일 아침 시황 분석, 이슈 정리, 유망 테마 종목, 그리고 핵심 진입 타이밍까지 친절하게 짚어준다. 초보자도 이해할 수 있을 정도로 쉬운 해설에 더해, 결과는 놀라울 정도로 정확하다는 평이다.✅ 정책 테마의 중심에서 상한가를 선점하고 싶다면? 지금 확인!(클릭)무엇보다 놀라운 점은, 이 모든 정보가 100% 무료라는 사실.불새가 운영 중인 텔레그램 채널에 입장만 하면, 아무 조건 없이 매일 고퀄리티 정보를 받아볼 수 있다.👉 내일의 상한가 종목, 입장만 하면 바로 확인 가능! (클릭)ㅤ-최근 핫이슈 종목한화오션, 우리기술투자, 카카오, 키이스트, 우리금융지주무료상담◆ 최근 애널리스트 분석의견- 장기 보유 매력 유효 - 미래에셋증권, 매수07월 14일 미래에셋증권의 정태준 애널리스트는 우리금융지주에 대해 "투자의견 매수로 상향, 목표주가 29,000원으로 상향. 주주환원 매력 배가 예상. 2분기 지배주주순이익은 컨센서스에 부합하는 8,477억원을 예상"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.영상 모듈 닫기국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가고 있다. 특히 신한지주가 18년 만에 사상 최고가를 경신하는 등 주요 금융주가 연이어 52주 신고가를 돌파하고 있다.하나증권에 따르면, 4대 금융지주의 2분기 합산 순이익은 6조 4천억 원 수준으로 전년 동기 대비 약 3.5% 증가할 것으로 전망된다. 이러한 실적 개선은 금리 안정과 비이자 수익 확대 전략, 건전성 관리 성과에 기인한 것으로 분석된다.또한 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것이라는 전망이 제기되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다. 배당 외에도 자사주 정책이 강화될 경우 금융주의 밸류에이션 리레이팅 가능성도 커지고 있다.증권주 역시 국내 증시 반등과 거래대금 증가에 따른 수혜 기대감에 힘입어 주목받고 있다. 주요 증권사들의 올해 영업이익 전망치는 약 1조 2천억 원으로, 이는 전년 대비 10.2% 증가한 수준이다.이 같은 흐름에 따라 8일 장중 ▲신한지주, ▲하나금융지주, ▲KB금융, ▲우리금융지주, ▲유안타증권, ▲iM금융지주, ▲JB금융지주, ▲BNK금융지주 등이 일제히 52주 신고가를 돌파했다. 특히 신한지주는 7만 원 선을 돌파하며 2006년 이후 18년 만에 최고가를 기록했다.외국인 투자자는 16일 거래소에서 KB금융, 현대차, 메리츠금융지주 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 KB금융, 현대차, 메리츠금융지주, 삼성SDI, NAVER, 우리금융지주, 삼성중공업, 풍산, 두산에너빌리티, 한화솔루션등이다.이중에 운수장비 업종에 속한 종목이 2개 포함되어 있다.NAVER, 풍산, DL이앤씨 등은 전일 대비 주가가 상승했고, KB금융, 현대차, 메리츠금융지주 등은 주가가 하락했다.[07월16일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세정부가 발표한 배당소득 분리과세안이 시장 기대보다 후퇴하면서 배당주가 지난 1일 일제히 급락했다. 하지만 오히려 저가 매수 기회로 삼아야 한다는 조언이 증권가 일각에서 나온다. 기업들이 배당을 늘리는 추세인 데다 주가가 반등했을 때 자본차익을 기대할 수 있어서다. 이번 세제 개편안에 따른 분리과세 조건을 충족하는 기업과 조건을 맞추기 위해 배당을 늘릴 종목에 주목하라는 게 전문가들의 조언이다.\n                    \n\n\n\n\n\n\n이미지 크게보기KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방외국인 투자자는 15일 거래소에서 현대차, 삼성화재, 기아 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 현대차, 삼성화재, 기아, 기업은행, SK텔레콤, NAVER, 신한지주, 우리금융지주, 삼성SDI, DB손해보험등이다.이중에 보험 업종에 속한 종목이 3개 포함되어 있다.기업은행, NAVER, 우리금융지주 등은 전일 대비 주가가 상승했고, 현대차, 삼성화재, 기아 등은 주가가 하락했다.[07월15일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.Getty Images Bank\n\n                하나금융지주와 기업은행을 비롯한 5개 금융지주사가 자본성증권(신종자본증권 및 후순위채권) 발행에 나섰다.금융권 자본성증권에 대한 기관투자가들의 선호도가 높아진 최근 흐름에 맞춰 낮은 금리에 자본을 확충한다는 계획이다.보험사 중에서는 DB손해보험이 5000억원 규모의 기본자본 신종자본증권을 보험업계에서 처음으로 발행한다. ◇ 금융사·보험사 자본조달 봇물하나금융과 기업은행은 다음 달 자본성증권 발행을 앞두고 이사회 결의에 나섰다.영상 모듈 닫기서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요남산에서 바라본 서울 시내 스케치.2024.05.31 최혁 기자지난 2년 동안 국내 시가총액 상위 100대 기업의 주주환원 규모가 35% 이상 증가한 것으로 나타났다.특히 KT&G는 시가총액 대비 주주환원 비율에서 1위를 기록했다.6일 기업데이터연구소 CEO스코어에 따르면 2022년 33조7240억 원이던 주주환원 총액은 2024년 45조5784억 원으로 11조8544억 원 35.2% 증가했다.같은 기간 조사 대상 기업들의 시가총액도 1405조4819억 원에서 1664조9773억 원으로 증가하며 시총 대비 환원율은 2.4%에서 2.7%로 소폭 상승했다.\r\n                    \n\n\nCEO스코어 제공주주환원 항목 중 가장 큰 비중을 차지하는 배당금은 2022년 31조8891억 원에서 지난해 37조3201억 원으로 17.0% 증가했다.하지만 전체 주주환원에서 배당이 차지하는 비중은 94.6%에서 81.9%로 낮아졌다.이는 주식소각의 증가에 따른 변화로 같은 기간 주식소각 총액은 1조8349억 원에서 8조2583억 원으로 무려 350.1% 급증했다.기업별로 보면 지난해 시가총액 대비 주주환원 비율이 가장 높은 기업은 KT&G로 10.0%에 달했다.\r\n                    \n\n\nCEO스코어 제공이어 키움증권(9.1%), 우리금융지주(9.0%), 삼성증권(8.0%), SK텔레콤(8.0%) 등이 상위권에 올랐다. 이 외에도 NH투자증권, 하나금융지주, 기업은행, 기아, 삼성물산 등이 상위 10위 안에 포함됐다.특히 금융업권 기업들이 전반적으로 높은 주주환원율을 보인 점이 눈에 띈다. 배당과 자사주 소각 등을 통해 적극적으로 주주 가치를 제고하려는 움직임이 활발하게 나타났다.반면 주주환원을 전혀 하지 않은 기업들도 다수 존재했다. 삼성바이오로직스, LG에너지솔루션, 두산에너빌리티, 한화오션, 알테오젠, 삼성중공업, 카카오페이 등 총 17개 기업은 지난해 주주환원 활동을 하지 않은 것으로 조사됐다.정유진 기자 jinjin@hankyung.com은행 관련 상장지수펀드(ETF) 수익률이 고공 행진하고 있다. 편입된 은행주들이 잇달아 신고가를 갈아 치우면서다. 하반기 은행주의 주주환원 정책이 확대될 것이란 기대도 커지고 있다.\n\n\n\n\n\n                9일 한국거래소에 따르면 국내 상장 ETF(레버리지·인버스 제외)의 최근 1주일(7월 2~8일) 수익률 상위권을 은행 ETF가 휩쓸었다. 가장 높은 수익을 낸 건 ‘TIGER 은행’으로, 이 기간 10.14% 올랐다. KB·신한·하나·우리금융 등 4대 금융지주 주식을 각각 포트폴리오의 20% 내외로 담은 상품이다. 이날 기준 하나금융지주의 비중이 20.04%이고 KB금융(19.06%), 신한지주(18.03%) 등도 높은 비중으로 편입했다.2위부터 4위도 은행 관련 상품이 채웠다. ‘TIGER 은행고배당플러스TOP10’이 해당 기간 9.91%의 수익률을 내며 2위에 올랐다. ‘SOL 금융지주플러스고배당’(9.48%), ‘KODEX 은행’(9.4%) 등이 뒤를 이었다.은행주는 최근 눈에 띄는 상승세를 보이고 있다. KRX은행지수의 1주일 상승률은 9.69%에 달하는데, 이는 35개 KRX지수 중 1위다. 4대 금융지주의 주가는 전날 나란히 장중 52주 최고가를 찍기도 했다.최근 상법 개정안이 국회를 통과한 데 이어 배당소득 분리과세 등 배당 관련 세제도 개편될 가능성이 점쳐지며 대표적인 저PBR(주가순자산비율)주인 은행주에 대한 상승 기대가 커졌다는 분석이 나온다. 박혜진 대신증권 연구원은 “배당 세제 개편 관련 기대감만으로도 은행주는 코스피지수를 웃도는 주가 상승률을 보이고 있다”고 말했다.양지윤 기자 yang@hankyung.com▶마켓인사이트 8월 6일 오후 3시 13분금융지주들이 하반기 신종자본증권(영구채) 발행 작업에 시동을 걸고 있다. 최대 1조8000억원에 육박하는 금융지주의 신종자본증권이 하반기 채권시장에 쏟아질 전망이다. 조달 환경도 개선된 만큼 신종자본증권을 통해 유동성 확보와 자본 확충을 모두 잡겠다는 구상으로 풀이된다.6일 금융감독원 전자공시시스템에 따르면 주요 금융지주가 이사회 결의를 통해 확정한 하반기 신종자본증권 조달 규모는 총 1조7900억원으로 집계됐다. 올해 상반기 금융지주 신종자본증권 발행 규모(1조7050억원)를 웃돈다.신종자본증권은 주식과 채권 성격을 동시에 지닌 하이브리드 채권을 뜻한다. 국제결제은행(BIS) 기준 자기자본비율 산정 때 자본으로 인정받을 수 있어 금융사가 주로 발행한다.5대 금융지주에서는 신한, 하나, 우리, 농협금융이 하반기 신종자본증권 조달 계획을 확정했다. 신한, 하나, 우리금융은 각각 최대 4000억원 규모의 신종자본증권 발행을 추진한다. 농협금융은 지난달 25일 3400억원 규모 신종자본증권 발행을 의결했다.지방에 거점에 둔 금융지주에서는 iM금융과 BNK금융이 신종자본증권 카드를 꺼내 들었다. iM금융은 1000억원을 신종자본증권을 통해 조달할 계획이다. BNK금융은 최대 1500억원어치 신종자본증권을 발행한다는 방침이다.금융지주들이 앞다퉈 자본 확충에 나선 것은 기존에 발행한 신종자본증권의 차환 물량이 줄줄이 도래하기 때문이다. 예컨대 신한, 하나, 우리금융은 신종자본증권으로 조달하는 자금의 대부분을 채무상환용으로 쓸 계획이다. 계열사 지원 등 운영자금 확보를 위해 신종자본증권을 활용하는 경우도 있다. 농협금융은 NH투자증권 등 계열사 유상증자 자금을 지원하기 위해 이번 신종자본증권 발행에 나선 것으로 알려졌다.신종자본증권 조달 환경이 개선되고 있는 것도 호재다. 한 금융지주 관계자는 “보험사보다 신용도가 높은 금융지주 신종자본증권의 희소성이 높아지고 있다”며 “기관과 개인투자자의 관심이 커 목표 물량을 모두 채울 가능성이 크다”고 말했다.장현주 기자 blacksea@hankyung.com정부가 발표한 배당소득 분리과세안이 시장 기대보다 후퇴하면서 배당주가 지난 1일 일제히 급락했다. 하지만 오히려 저가 매수 기회로 삼아야 한다는 조언이 증권가 일각에서 나온다. 기업들이 배당을 늘리는 추세인 데다 주가가 반등했을 때 자본차익을 기대할 수 있어서다. 이번 세제 개편안에 따른 분리과세 조건을 충족하는 기업과 조건을 맞추기 위해 배당을 늘릴 종목에 주목하라는 게 전문가들의 조언이다.\n                    \n\n\n\n\n\n\n이미지 크게보기[한경ESG] 지속가능경영 보고서 CEO 말말말 - 4대 금융지주 \n\n\n\n\n\n“KB금융그룹은 ‘세상을 바꾸는 금융’이라는 사명을 바탕으로 금융의 본질을 넘어 더 멀리 보고 더 깊이 고민하겠습니다.”양종희 KB금융그룹 회장 세상을 바꾸는 금융[1] KB금융그룹은 고객에게는 신뢰할 수 있는 금융, 주주에게는 장기적 성장 가능성을 제시하는 기업, 지역사회에는 함께 성장하는 든든한 동반자가 되는 것을 진정한 가치로 삼아 최선을 다하고 있습니다. [2] 금융은 단순한 자금 중개를 넘어 개인의 삶과 기업의 미래, 나아가 사회 전체의 지속가능성을 연결하는 중요한 기반입니다. 금융의 본질적 역할을 되새기며, 다음 세대에게 더 나은 환경과 기회를 전하는 책임을 다하고자 합니다.[3] KB금융그룹은 기후 위기, 저출생, 지역 소멸, 일자리 문제 등 우리 삶을 위협하는 문제를 외면하지 않고, 금융 본업의 역량을 발휘해 사회와 함께하는 따뜻한 파트너십을 실천해왔습니다. 또 돌봄과 소상공인 지원 등 의미 있는 사회적가치를 창출하고, 이웃과 사회와의 관계를 균형 있게 헤아리며 공존을 추구하고자 했습니다.[4] 앞으로도 KB금융그룹은 고객의 신뢰와 사회의 기대를 가장 소중한 자산으로 여기며, 국민 모두의 성장이 KB의 성장으로 이어지는 지속가능한 길을 함께 만들어가겠습니다.※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.ETF 주간 수익률 TOP20지난 한 주간 금융주(은행, 증권, 보험) 등 고배당주에 투자하는 상장지수펀드(ETF)들이 수익률 상위권을 휩쓸었다.  13일 한국거래소에 따르면 지난 7~11일 기준 국내 상장 ETF 수익률 상위 20개 종목 중 14개가 고배당주 관련 ETF인 것으로 나타났다. 정부와 국회가 배당 활성화 정책을 추진하면서 정책 수혜 기대가 커진 영향이다. \n                    \n\n\n\ndb한경db\n\n                지난 한 주간 금융주(은행, 증권, 보험) 등 고배당주에 투자하는 상장지수펀드(ETF)들이 수익률 상위권을 휩쓸었다.  13일 한국거래소에 따르면 지난 7~11일 기준 국내 상장 ETF 수익률 상위 20개 종목 중 14개가 고배당주 관련 ETF인 것으로 나타났다. 정부와 국회가 배당 활성화 정책을 추진하면서 정책 수혜 기대가 커진 영향이다. \n                    \n\n\n\ndb외국인 투자자는 08일 거래소에서 이수페타시스, 삼성중공업, SK하이닉스 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 이수페타시스, 삼성중공업, SK하이닉스, 하나금융지주, 삼양식품, HD현대, KB금융, 신한지주, 동양철관, 현대차등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.이수페타시스, 삼성중공업, SK하이닉스 등은 전일 대비 주가가 상승했고, POSCO홀딩스, LG화학 등은 주가가 하락했다.[07월08일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가고 있다. 특히 신한지주가 18년 만에 사상 최고가를 경신하는 등 주요 금융주가 연이어 52주 신고가를 돌파하고 있다.하나증권에 따르면, 4대 금융지주의 2분기 합산 순이익은 6조 4천억 원 수준으로 전년 동기 대비 약 3.5% 증가할 것으로 전망된다. 이러한 실적 개선은 금리 안정과 비이자 수익 확대 전략, 건전성 관리 성과에 기인한 것으로 분석된다.또한 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것이라는 전망이 제기되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다. 배당 외에도 자사주 정책이 강화될 경우 금융주의 밸류에이션 리레이팅 가능성도 커지고 있다.증권주 역시 국내 증시 반등과 거래대금 증가에 따른 수혜 기대감에 힘입어 주목받고 있다. 주요 증권사들의 올해 영업이익 전망치는 약 1조 2천억 원으로, 이는 전년 대비 10.2% 증가한 수준이다.이 같은 흐름에 따라 8일 장중 ▲신한지주, ▲하나금융지주, ▲KB금융, ▲우리금융지주, ▲유안타증권, ▲iM금융지주, ▲JB금융지주, ▲BNK금융지주 등이 일제히 52주 신고가를 돌파했다. 특히 신한지주는 7만 원 선을 돌파하며 2006년 이후 18년 만에 최고가를 기록했다.2분기 실적 발표 시즌에 본격 돌입하면서 주도주의 성적표가 윤곽을 드러내고 있다. 코스피지수가 단기 급등하며 밸류에이션(실적 대비 주가 수준)이 높아진 만큼 실적이 주가 향방을 가를 주요 변수로 작용할 것이라는 분석이 나온다.사진=게티이미지뱅크 \n\n                올해 강세장을 주도해 온 전력기기주는 지난 1월 말 큰 조정을 겪었다. 중국의 저가 인공지능(AI) 모델 ‘딥시크’의 등장으로 엔비디아 등 미국 AI주가 동반 급락하던 때다. 당시 신한자산운용 주식운용팀 펀드매니저들은 이 같은 조정을 저가 매수로 기회로 보고 HD현대일렉트릭과 효성중공업 등 전력기기주 비중을 대폭 늘렸다. 이후 전력기기주가 급등하면서 ‘SOL 코리아메가테크액티브’ 상장지수펀드(ETF)는 올해 코스피지수를 두 배 이상 앞지르는 성적을 내고 있다. ◇펀드매니저가 주도주에 집중 투자\n\n\n\n\n\n\n\n이미지 크게보기영상 모듈 닫기KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방POSCO홀딩스는 최근 글로벌 금융시장에서 새롭게 주목받고 있다. 먼저 해외 투자자들이 높은 관심을 보인 그린본드 발행은 기업의 친환경 전환 전략에 대한 시장의 신뢰를 강화한 대표적 이벤트였다. POSCO홀딩스는 에너지 소재와 신재생 인프라 투자 자금 조달을 위해 700백만 달러 규모의 글로벌 그린본드를 성공적으로 발행했으며, 예상보다 높은 수요에 힘입어 빠르게 완판된 것으로 알려졌다. 이 과정은 지속 가능한 경영과 ESG 중심 전략에 대한 시장 평가를 크게 끌어올렸다.기술 협업 측면에서도 긍정적 변화가 감지된다. POSCO홀딩스는 호주의 그린 수소 기업 ‘Hysata’와의 전해조 기술 공동 개발을 추진하고 있으며, 이는 향후 수소 경제 시대의 성장 동력으로 꼽히는 혁신 프로젝트에 대한 기대감을 자극했다. 전해조 소재와 시스템 기술 역량을 결합해 상업화 속도를 높이려는 이 전략은 ESG 트렌드가 실질 사업으로 이어지는 구조적 모멘텀으로 인식된다.기업 구조 개선과 수급 재평가도 흐름을 뒷받침한다. 해외 증권사 애널리스트들은 최근 POSCO홀딩스의 매출 회복과 함께 실적 기반 기업가치 재평가 가능성에 대한 리포트를 내놓고 있으며, 일부는 철강산업 내 경쟁사 대비 상대 강도(RS) 지표의 상승 여력을 언급하기도 했다. 내년 초 예정된 실적 발표도 중요한 분기점으로 꼽히고 있으며, 시장에서는 이를 통해 상승 주도권이 강화될 수 있다는 기대가 형성되고 있다.수출·투자 측면에서도 주목할 만한 진전이 있다. POSCO E&C는 최근 태국 LNG 터미널 프로젝트 수주에 성공하며 인프라 사업에서의 해외 성과를 확보했으며, 이는 그룹의 비철강 부문 수익 확장 가능성을 증명했다. 이러한 프로젝트 중심 수익 기반 확대는 기업 리스크를 분산시키고 성장 잠재력을 강화하는 요소로 평가된다.다날, 우리금융지주, 한화시스템, 쿠콘, 삼성바이오로직스무료상담영상 모듈 닫기이재명 대통령이 국내 금융권의 ‘이자놀이’를 경고하자 금융당국이 전 업권 협회장을 긴급 소집해 투자 확대 등 관련 대책을 논의한다. 사상 최대 이익을 거둔 금융사들의 대출 위주 영업 방식을 첨단산업과 벤처·대체투자 등 ‘생산적 금융’으로 전환하는 방안 등을 검토할 것으로 예상된다.27일 금융위원회에 따르면 권대영 금융위 부위원장은 28일 은행연합회, 생명보험협회, 손해보험협회, 여신금융협회, 금융투자협회 등 업권을 대표하는 협회장들과 긴급 조찬 간담회를 할 예정이다. 간담회에서는 업권별 기업 투자 촉진 및 자본시장 활성화 방안 등을 논의할 것으로 전해졌다.금융당국 고위 관계자는 “사상 최대 이익을 거둔 금융사들을 향해 국민의 비판 목소리가 커지고 있다”며 “시대적 요구를 반영한 개선책을 정부와 업계가 함께 마련하기 위한 첫 번째 자리”라고 말했다. 이 대통령은 지난 24일 열린 수석·보좌관회의에서 “손쉬운 주택담보대출 같은 이자놀이에 매달릴 것이 아니라 투자 확대에도 신경 써달라”며 “그래야 국민 경제의 파이가 커지고 금융기관도 건전하게 성장 발전할 수 있지 않겠냐”고 했다. 금융당국, 부동산 대신 기업투자 주문할 듯 벤처 투자 등 생산적 금융 강조…금융권도 규제 개선 건의할 듯금융지주들이 미처 계산하지 못한 재원 부족 문제로 자사주 매입 시기를 내년으로 미루는 일이 잇따르고 있다. 앞다퉈 주주환원 확대를 약속했지만, 배당가능이익이라는 상법상 제약을 간과한 채 속도전을 펼친 탓이다. 손쉬운 ‘이자 놀이’ 대신 기업에 자금 투입을 늘리라는 정부 요구로 자본 비율 관리까지 까다로워지면서 당초 약속한 주주가치 제고 계획이 흔들릴 것이라는 관측이 나온다.국내 은행권이 주가연계증권(ELS) 등 고위험 상품 판매와 운영에 따른 손실액을 10년간 위험가중자산(RWA)에 반영하는 규제와 관련해 외부 컨설팅을 받기로 했다. 해외 사례 수집 등을 통해 근거를 마련한 뒤 “재발 우려를 차단했다면 관련 손실을 RWA에 반영하지 않도록 해달라”고 금융당국에 요구하기 위해서다. 은행의 건전성 관리에 오랫동안 부담을 안긴 ‘홍콩 H지수 ELS 사태’의 족쇄에서 벗어날지 주목된다. ◇“판매 중단 상품 손실은 예외”\n\n\n\n\n\n\n\n이미지 크게보기올해 2분기 국민연금은 국내 증시 상승세에 맞춰 금융, 지주, 내수 관련주 비중을 확대하며 포트폴리오를 조정했다. 이와 동시에 업황 부진이 이어지는 2차전지 업종에 대한 지분 비중은 줄였다.국민연금은 상법 개정안 통과 기대에 따른 주주환원 여력과 지배구조 개편 수혜가 예상되는 금융주와 지주사에 대한 투자를 늘렸으며, 내수 진작 기대가 커지면서 내수주도 추가 매수했다. 반면 2차전지 업종은 당분간 실적 기대가 낮아짐에 따라 비중을 축소했다.또한 일부 기업에 대해 단순투자 목적에서 일반투자로 보유 목적을 변경하며 지배구조 개선 등 주주 의견 전달을 강화하려는 움직임도 보였다. 국민연금은 내년도 기금운용계획에서 국내주식 비중을 소폭 줄이고 해외주식 비중을 늘릴 계획이다.한편, 스탁론에 대한 

In [324]:
len(total_contents)

22496

수기 입력으로 확인
> 확인 사유 : 0번째 문서가 이상하..?

In [310]:
retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
CrossEncoder_prompt = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''
print(CrossEncoder_prompt.strip())
raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]

scores = model.score(pairs)
scored = sorted(zip(raw_docs, scores), key=lambda x: float(x[1]), reverse=True)[:50]
scored_docs=[]
# 3) 점수 붙이고 재정렬
for d, s in zip(raw_docs, scores):
    dd = deepcopy(d)
    dd.metadata["relevance_score"] = float(s)
    scored_docs.append(dd)

이 뉴스들 중에서 "우리금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, 우리금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [311]:
pd.DataFrame(list(map(lambda x: x.metadata,scored_docs))).sort_values(by=['ticker','relevance_score'],ascending=False).head(5)

,chunk_idx,title,url,label,original_idx,ticker,Date,relevance_score
3,0,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",https://www.hankyung.com/article/202507145874L,1,237,우리금융지주,2025-07-14,0.602175
14,0,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",https://www.hankyung.com/article/202507084010L,1,374,우리금융지주,2025-07-08,0.467356
9,0,"""우리금융지주, 연말로 갈수록 고배당 부각…목표가↑""-NH",https://www.hankyung.com/article/2025070836976,1,476,우리금융지주,2025-07-08,0.397002
6,1,대출 수익성 악화에…4대 금융 실적 꺾였다,https://www.hankyung.com/article/2025071501731,1,158,우리금융지주,2025-07-15,0.358331
10,0,"“금리 하락에도 이익 증가” 금융지주, 실적 온도차",https://magazine.hankyung.com/business/article...,1,446,우리금융지주,2025-07-21,0.265313

## 요약하기

### 요약함수 호출
- 가져온 원 본문을 전부 적용하기

In [27]:
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

In [28]:
def summarize_top_articles_2(total_contents: str,ticker:str,max_iters:int) -> pd.DataFrame:
    agent = NewsSummaryAgent(max_iters=max_iters)
    runnable = build_summary_graph(agent)

    rows = []
    doc = total_contents

    state = {"article": doc, "summary": "", "feedback": "", "iteration": 0}
    result = runnable.invoke(state)

    print("✅ 실행 결과 키:", result.keys())
    # 여기서 final_summary 반드시 존재해야 함(위 패치 기준)
    final_summary = result.get("final_summary")
    if not final_summary:
        print("❌ final_summary 없음. 디버그용 전체 상태:", result)
        # 계속 진행할지, 실패로 표기할지 선택

    rows.append({
        "ticker": ticker,
        "date": '2025-07-30', # 위 조회 기준일자로 연동시켜서 바꿀 예정
        "summary": final_summary,
        "feedback": result.get("last_feedback", "피드백 없음"),
    })

    return pd.DataFrame(rows)

In [325]:
result_df = summarize_top_articles_2(total_contents,ticker=test_ticker,max_iters=5)

summart : ✅ 주요 요약
- 외국인, 우리금융지주 대량 순매수
  외국인은 최근 3일 연속으로 우리금융지주 주식을 대량 순매수하며 투자자들의 관심이 집중되고 있다.

- 우리금융지주, 2분기 순이익 감소 전망
  우리금융지주의 2분기 순이익은 전년 대비 감소할 것으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용 등으로 인한 판매관리비 증가가 원인으로 분석된다.

- 4대 금융지주, 비이자이익 증가로 실적 선방
  KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있다.

🔑 키워드: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망.
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 언급된 외국인 순매수와 관련된 정보는 기사에 있지만, 요약에서 언급된 '우리금융지주 2분기 순이익 감소 전망'의 구체적인 원인인 '모바일 트레이딩 시스템 개발과 신규 인력 채용'은 기사에 명시되어 있지 않습니다.] </reason>
- 포괄성: 부족함 <reason> [요약은 외국인 순매수와 2분기 실적 전망에 대한 주요 내용을 다루고 있지만, 기사에 포함된 다양한 애널리스트 의견과 금융지주들의 배당 및 자사주 매입 관련 정보가 누락되었습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 핵심 정보를 간결하게 전달하고 있습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있어 이해하기 쉽습니다.] </reason>
- 일관성: 부족함 <reason> [요약은 특정 종목인 '우리금융지주'에 대한 내용에 집중하고 있지만, 기사에는 다른 금융지주들에 대한 정보도 포함되어 있어 일관성이 부족합니다.] </reason>

**피드백:**
- 정확성을 높이기 위해서는 기사에 명시된 정보만을 기반으로 요약을 작성해야 합니다. 예를 들어, '모바일 트레이딩 시스템 개발과 신규 인력 채용'과 같은 구체적인 원인은 기사에 명시되지 않았으므로 요약에서 제외해야 합니다.
- 포괄성을 개선하기 위해서는 기사에 언급된 다양한 애널리스트 의견, 금융지주들의 배당 및 자사주 매입 관련 정보 등도 포함하여 전체적인 맥락을 더 잘 반영해야 합니다.
- 일관성을 높이기 위해서는 특정 종목에 대한 정보뿐만 아니라 기사에 포함된 다른 금융지주들에 대한 정보도 고려하여 요약을 작성해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n- 외국인, 우리금융지주 대량 순매수\n  외국인은 최근 3일 연속으로 우리금융지주 주식을 대량 순매수하며 투자자들의 관심이 집중되고 있다.\n\n- 우리금융지주, 2분기 순이익 감소 전망\n  우리금융지주의 2분기 순이익은 전년 대비 감소할 것으로 예상되며, 이는 판매관리비 증가가 원인으로 분석된다.\n\n- 4대 금융지주, 비이자이익 증가로 실적 선방\n  KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있다.\n\n- 애널리스트 의견 및 배당 매력\n  NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망이다.\n\n- 금융지주들의 배당 및 자사주 매입\n  4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다.\n\n🔑 키워드: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입."
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약 내용이 원문 기사와 일부 일치하지 않으며, 특히 외국인 순매수와 관련된 수치가 일관되지 않음] </reason>
- 포괄성: 부족함 <reason> [중요한 정보가 모두 포함되지 않았으며, 특히 금융지주들의 실적과 관련된 세부 사항이 누락됨] </reason>
- 간결성: 좋음 <reason> [불필요한 표현 없이 간결하게 작성됨] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성됨] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하지 않고, 여러 금융지주에 대한 내용이 혼재되어 있음] </reason>

**피드백:**
1. **정확성**: 요약에서 외국인 순매수와 관련된 수치가 원문과 일치하지 않으므로, 원문에서 제공된 수치를 정확히 반영해야 합니다.

2. **포괄성**: 금융지주들의 실적에 대한 세부 사항, 특히 각 금융지주의 실적 변화와 그 원인에 대한 정보가 요약에 포함되어야 합니다. 예를 들어, 각 금융지주의 순이익 변화와 그 이유에 대한 정보가 필요합니다.

3. **일관성**: 요약은 특정 종목(우리금융지주)에 대한 내용으로 일관되게 작성되어야 합니다. 현재 요약은 여러 금융지주에 대한 내용을 혼재하고 있어, 특정 종목에 집중된 요약을 작성해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입."
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약에서 언급된 내용 외에도 기사에는 다른 금융지주사들의 실적 및 전망, 배당 정책, 외국인 투자 동향 등 다양한 정보가 포함되어 있으나, 요약에서는 주로 우리금융지주에 대한 내용만 다루고 있습니다.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

피드백:
포괄성 측면에서 개선이 필요합니다. 기사에는 우리금융지주 외에도 다른 금융지주사들의 실적, 배당 정책, 외국인 투자 동향 등 다양한 정보가 포함되어 있습니다. 요약에서는 이러한 다양한 정보를 포함하여 독자가 전체 기사의 주요 내용을 파악할 수 있도록 해야 합니다. 특히, 다른 금융지주사들의 실적 및 전망, 배당 정책에 대한 정보도 요약에 포함되면 더 포괄적인 요약이 될 것입니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주."
[should_stop] Iteration: 3
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약은 원문 기사의 주요 내용을 대부분 반영하고 있지만, 일부 세부 사항과 수치가 원문과 일치하지 않거나 누락되었습니다.] </reason>
- 포괄성: 부족함 <reason> [요약은 주요 포인트를 다루고 있지만, 기사에서 다룬 모든 중요한 내용을 포함하지 않았습니다. 특히, 다른 금융지주사의 실적 및 전망에 대한 세부 사항이 부족합니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장 구조가 자연스럽고 명확하게 작성되었습니다.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목에 대한 내용에 집중되어 있지 않고, 여러 금융지주사에 대한 내용이 혼재되어 있습니다.] </reason>

피드백:
1. **정확성 및 포괄성 개선**: 요약에서 언급된 수치와 세부 사항이 원문과 일치하도록 주의하세요. 특히, 다른 금융지주사들의 실적 및 전망에 대한 구체적인 수치를 포함하여 포괄성을 높일 필요가 있습니다.

2. **일관성 개선**: 요약의 초점을 명확히 하여 특정 종목이나 주제에 대한 일관된 정보를 제공하도록 하세요. 여러 금융지주사에 대한 정보를 다룰 경우, 각 금융지주사에 대한 정보를 명확히 구분하여 제시하는 것이 좋습니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주."
[should_stop] Iteration: 4
[should_stop] Feedback:
 - 정확성: 좋음
  <reason> 요약 내용이 원문 기사와 대체로 일치하며, 주요 정보가 정확하게 전달되었습니다. </reason>

- 포괄성: 부족함
  <reason> 원문 기사에서 다루고 있는 다양한 금융지주사들의 실적 및 전망에 대한 정보가 충분히 포함되지 않았습니다. </reason>

- 간결성: 좋음
  <reason> 요약이 불필요한 표현 없이 간결하게 작성되었습니다. </reason>

- 문장구성: 좋음
  <reason> 문장이 자연스럽고 명확하게 구성되어 있습니다. </reason>

- 일관성: 부족함
  <reason> 요약이 특정 종목(우리금융지주)에 초점을 맞추고 있으나, 원문 기사는 다양한 금융지주사에 대한 정보를 포함하고 있습니다. </reason>

**피드백:**
포괄성과 일관성 측면에서 개선이 필요합니다. 원문 기사는 다양한 금융지주사의 실적과 전망을 다루고 있으므로, 요약에서도 다른 금융지주사들에 대한 정보가 더 포함되어야 합니다. 또한, 요약이 특정 종목에만 집중되지 않도록 다양한 금융지주사에 대한 정보를 균형 있게 다루는 것이 중요합니다. 이를 통해 독자가 전체적인 금융 시장 상황을 더 잘 이해할 수 있도록 해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n- **금융지주사들의 장기 전망**\n  - 4대 금융지주의 연간 순이익은 총 18조원에 육박할 것으로 예상되며, 이는 비이자이익 증가와 주주환원 정책 강화에 기인합니다. 그러나 경기 침체와 대출 규제 강화로 인해 하반기 실적에는 불확실성이 존재합니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주, 주주환원 정책."
[should_stop] Iteration: 5
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 언급된 일부 정보가 원문 기사와 일치하지 않거나 부정확합니다. 예를 들어, 외국인 순매수와 관련된 수치가 일치하지 않습니다.] </reason>
- 포괄성: 부족함 <reason> [요약에서 중요한 정보가 일부 누락되었습니다. 예를 들어, 다른 금융지주사의 실적 및 전망에 대한 정보가 충분히 포함되지 않았습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목인 우리금융지주에 대한 내용에 집중되어 있지만, 다른 금융지주사에 대한 정보도 포함되어 있어 일관성이 부족합니다.] </reason>

피드백:
1. **정확성**: 원문 기사와의 일치성을 높이기 위해 요약에서 언급된 수치와 정보를 다시 한 번 확인하고, 정확하게 반영해야 합니다.
2. **포괄성**: 다른 금융지주사들의 실적 및 전망에 대한 정보를 더 포함하여 전체적인 맥락을 제공해야 합니다.
3. **일관성**: 특정 종목에 대한 내용만을 요약하려면, 다른 금융지주사에 대한 정보는 제외하거나 별도로 분리하여 작성하는 것이 좋습니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])

In [326]:
result_df

,ticker,date,summary,feedback
0,우리금융지주,2025-07-30,"✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n - 외국인은 ...",- 정확성: 부족함 <reason> [요약에서 언급된 일부 정보가 원문 기사와 일치...

In [327]:
print(result_df.summary.values[0])

✅ 주요 요약

- **외국인, 우리금융지주 대량 순매수**
  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.

- **우리금융지주, 2분기 순이익 감소 전망**
  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.

- **4대 금융지주, 비이자이익 증가로 실적 선방**
  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.

- **애널리스트 의견 및 배당 매력**
  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.

- **금융지주들의 배당 및 자사주 매입**
  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.

- **다른 금융지주사들의 실적 및 전망**
  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.

- **금융지주사들의 장기 전망**
  - 4대 금융지주의 연간 순이익은 총 18조원에 육박할 것으로 예상되며, 이는 비이자이익 증가와 주주환원 정책 강화에 기인합니다. 그러나 경기 침체와 대출 규제 강화로 인해 하반기 실적에는 불확실성이 존재합니다.

🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주, 주주환원 정책.

## 피드백 정리
- 삼성전자  : 삼성전자에 대한 내용 잘 요약
- 우리금융지주 : 우리금융지주에 대한 내용 잘 요약
- SK하이닉스 : 요약은 되었으나,, 시장 내/외부 사람들의 구매 패턴, 동향에 대한 정보가 주로 요약이 되고 있음<br>
            > recall@50(pool) 이 상당히 낮게 나옴!
  > SK하이닉스에 대한 케이스를 봤을 때, chunk에 대해서만 요약을 해야하나 싶음<br>
  > 2025.08.11) 현재 작업은 전체 원문에 대한 요약이었음. 그래서.. SK 하이닉스 회사 본질에 대한 정보를 제대로 요약해주지 못하나 싶음<br>
  > 프롬프트 내부 요약 평가 기준 의 "일관성" 영역에 명확히 종목명을 말해야겠다..

## 시뮬레이션 한 애들 전체 돌리기

In [52]:
total_con_lst = []

In [6]:
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [54]:
for ticker in Custer_Having_ticker_lst:
    print(f'{ticker} =======')
    CrossEncoder_prompt_test = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : ticker}})
    compressor = CrossEncoderReranker(model=model, top_n=20)
    compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
    )
    compressed_docs = compression_retriever.invoke(CrossEncoder_prompt_test)
    original_idxs = list(map(lambda x: x.metadata['original_idx'], compressed_docs))
    top_n_original = [get_full_article_from_chroma(idx,kind=ticker,vectordb=vectordb) for idx in original_idxs]
    print(f'원문 개수 : {len(top_n_original)}')
    original_contents = list(map(lambda x: x['content'],top_n_original))
    total_contents = ''.join(original_contents)
    print(f'원문 총 length : {len(total_contents)}')
    total_con_lst.append(summarize_top_articles_2(total_contents,ticker=ticker,max_iters=5))

우리금융지주 =======

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

원문 개수 : 20
원문 총 length : 17384
summart : ✅ 주요 요약
- 글로벌 투자자, 한국 금융주에 대한 관치금융 리스크 우려
  글로벌 투자자들이 한국 금융주에 대한 정부의 관치금융 리스크 확산을 우려하며, 주가 하락에 대한 문의가 증가하고 있음.

- 정부의 금융권 압박, 은행주 주가 하락의 주요 원인
  정부의 상생 압박과 세금, 과징금 증가가 은행주 주가에 부정적 영향을 미치며, 주주환원 정책의 동력을 상실할 수 있다는 우려가 제기됨.

- 금융사 평균 급여 증가, 고액 연봉 논란
  금융사 직원들의 평균 급여가 증가하면서 고액 연봉 논란이 일고 있으며, 이는 정부의 금융권 압박과 맞물려 상생 압박이 더욱 거세질 가능성이 있음.

📌 키워드: 관치금융 리스크, 글로벌 투자자, 은행주 주가 하락, 정부 압박, 고액 연봉 논란, 금융권 상생 압박, 주주환원 정책.
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약에서 언급된 '금융사 평균 급여 증가'와 관련된 부분은 원문에서 다루고 있지 않음. 또한, 원문에서 언급된 외국인 투자자들의 방한 및 금융당국과의 회동 계획 등 구체적인 내용이 요약에 포함되지 않음.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 부족함 <reason> [요약에서 언급된 '금융사 평균 급여 증가' 부분이 원문 기사와 관련이 없으며, 특정 종목에 대한 내용이 아닌 일반적인 금융권 상황을 다루고 있음.] </reason>

피드백:
1. 포괄성: 요약에 포함된 '금융사 평균 급여 증가' 부분은 원문 기사에서 다루고 있지 않으므로, 이 부분을 삭제하고 원문에서 다룬 외국인 투자자들의 방한 및 금융당국과의 회동 계획 등 구체적인 내용을 추가해야 합니다.
2. 일관성: 요약은 특정 종목에 대한 내용이 아니라 금융권 전반에 대한 내용을 다루고 있으므로, 요약의 일관성을 높이기 위해 원문 기사에 충실한 정보를 포함해야 합니다. '금융사 평균 급여 증가' 부분을 삭제하고, 원문에서 언급된 '관치금융 리스크'와 관련된 구체적인 상황을 더 명확하게 설명하는 것이 좋습니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **글로벌 투자자, 한국 금융주에 대한 관치금융 리스크 우려**\n  글로벌 투자자들이 한국 금융주에 대한 정부의 관치금융 리스크 확산을 우려하며, 주가 하락에 대한 문의가 증가하고 있음. 이로 인해 주요 글로벌 투자은행(IB) 관계자들이 이례적으로 방한을 추진하고 있음.\n\n- **정부의 금융권 압박, 은행주 주가 하락의 주요 원인**\n  정부의 상생 압박과 세금, 과징금 증가가 은행주 주가에 부정적 영향을 미치며, 주주환원 정책의 동력을 상실할 수 있다는 우려가 제기됨. 특히, 교육세율 인상과 같은 정책 변화가 금융사의 수익성에 부담을 주고 있음.\n\n- **외국인 투자자 방한 및 금융당국과의 회동 계획**\n  JP모간, 모건스탠리 등 글로벌 투자은행 관계자들이 다음달 한국을 방문하여 금융당국 고위 관계자 및 4대 금융지주 회장들과의 회동을 계획하고 있음. 이는 정부의 금융권 압박에 따른 리스크를 직접 확인하기 위한 것으로 보임.\n\n📌 **키워드**: 관치금융 리스크, 글로벌 투자자, 은행주 주가 하락, 정부 압박, 외국인 투자자 방한, 금융당국 회동, 주주환원 정책.'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약이 주요 내용을 다루고 있지만, 기사에서 언급된 구체적인 수치나 특정 금융지주의 상황에 대한 세부 정보가 부족합니다.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

**피드백:**
포괄성 측면에서 요약이 기사에서 다루는 모든 중요한 정보를 포함하지 못하고 있습니다. 예를 들어, 기사에서는 특정 금융지주의 주가 하락 수치와 정부의 세금 및 과징금 정책 변화가 금융사에 미치는 구체적인 영향을 다루고 있습니다. 이러한 세부 사항을 요약에 포함시켜 포괄성을 높일 수 있습니다. 또한, 외국인 투자자들의 구체적인 우려 사항이나 질문 내용도 요약에 포함하면 더 완전한 정보 전달이 가능할 것입니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **글로벌 투자자, 한국 금융주에 대한 관치금융 리스크 우려**  \n  글로벌 투자자들이 한국 금융주에 대한 정부의 관치금융 리스크 확산을 우려하며, 주가 하락에 대한 문의가 증가하고 있음. 이로 인해 주요 글로벌 투자은행(IB) 관계자들이 이례적으로 방한을 추진하고 있음.\n\n- **정부의 금융권 압박, 은행주 주가 하락의 주요 원인**  \n  정부의 상생 압박과 세금, 과징금 증가가 은행주 주가에 부정적 영향을 미치며, 주주환원 정책의 동력을 상실할 수 있다는 우려가 제기됨. 특히, 교육세율 인상과 같은 정책 변화가 금융사의 수익성에 부담을 주고 있음.\n\n- **외국인 투자자 방한 및 금융당국과의 회동 계획**  \n  JP모간, 모건스탠리 등 글로벌 투자은행 관계자들이 다음달 한국을 방문하여 금융당국 고위 관계자 및 4대 금융지주 회장들과의 회동을 계획하고 있음. 이는 정부의 금융권 압박에 따른 리스크를 직접 확인하기 위한 것으로 보임.\n\n- **구체적인 금융지주 주가 하락 및 세금 정책 변화**  \n  KB금융, 신한지주, 하나금융지주, 우리금융지주 등 주요 금융지주 주가가 최근 한 달 새 10% 이상 급락했으며, 정부의 교육세율 인상으로 인해 최대 4조5000억원의 비용 부담이 예상됨. 이는 금융사의 수익성에 직접적인 영향을 미치고 있음.\n\n- **외국인 투자자들의 구체적인 우려 사항**  \n  외국인 투자자들은 국민성장펀드로 인한 이익 감소, 위험가중치 조정에도 불구하고 자본 비율 하락 가능성, 금융감독원장 임명에 따른 리스크 등을 우려하고 있음.\n\n📌 **키워드**: 관치금융 리스크, 글로벌 투자자, 은행주 주가 하락, 정부 압박, 외국인 투자자 방한, 금융당국 회동, 주주환원 정책, 교육세율 인상, 금융지주 주가, 외국인 투자자 우려.'
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 좋음
  <reason> 요약 내용이 원문 기사와 일치하며, 주요 정보와 핵심 사항을 잘 반영하고 있습니다. </reason>

- 포괄성: 좋음
  <reason> 요약이 기사에서 다루고 있는 주요 이슈와 정보를 모두 포함하고 있으며, 중요한 세부사항도 잘 언급하고 있습니다. </reason>

- 간결성: 좋음
  <reason> 요약이 불필요한 표현 없이 핵심 내용을 간결하게 전달하고 있습니다. </reason>

- 문장구성: 좋음
  <reason> 문장이 자연스럽고 명확하게 구성되어 있어 이해하기 쉽습니다. </reason>

- 일관성: 좋음
  <reason> 요약이 특정 종목에 대한 내용만을 다루고 있으며, 일관성을 유지하고 있습니다. </reason>

피드백:
전체적으로 요약이 매우 잘 작성되었습니다. 주요 정보와 세부 사항을 정확하고 포괄적으로 전달하면서도 간결하고 명확하게 구성되어 있습니다. 현재 상태로도 충분히 좋은 요약이지만, 만약 추가적인 개선을 고려한다면, 각 항목 간의 연결성을 조금 더 강화하여 독자가 흐름을 쉽게 따라갈 수 있도록 하면 더욱 좋을 것입니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])
삼성화재 =======

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

원문 개수 : 20
원문 총 length : 35595
summart : ✅ 주요 요약
- 삼성화재, AI 의료심사 도입으로 암 진단 및 수술급여 심사 효율성 향상
  삼성화재는 AI 기반의 의료심사 시스템을 도입하여 암 진단 및 수술급여 심사의 효율성과 정확성을 높였으며, 인력 검토 비중이 약 55% 감소했다고 발표했습니다.

- '해외 2시간 항공지연 특약' 출시로 항공기 지연 및 결항 손해 보장
  삼성화재는 해외 출발 항공편의 2시간 이상 지연 및 결항 시 발생하는 손해를 최대 50만원까지 보장하는 '해외 2시간 항공지연 특약'을 출시하여 고객의 여행 불편을 최소화하고자 했습니다.

- 외국인 투자자, SK하이닉스 등 주요 종목 순매수
  외국인 투자자들은 SK하이닉스, 현대차, HD한국조선해양 등 주요 종목을 집중적으로 매수하였으며, 운수장비 업종에 속한 종목들이 다수 포함되었습니다.

키워드: 삼성화재, AI 의료심사, 항공지연 특약, 외국인 투자자, SK하이닉스, 현대차, HD한국조선해양
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 좋음
  <reason> 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다. </reason>

- 포괄성: 좋음
  <reason> 기사에서 다루는 주요 주제인 삼성화재의 AI 의료심사 도입, 항공지연 특약 출시, 외국인 투자자의 주요 종목 매수에 대한 정보가 모두 포함되어 있습니다. </reason>

- 간결성: 좋음
  <reason> 요약은 불필요한 표현 없이 간결하게 작성되었습니다. </reason>

- 문장구성: 좋음
  <reason> 문장이 자연스럽고 명확하게 구성되어 있습니다. </reason>

- 일관성: 좋음
  <reason> 특정 종목에 대한 내용만 존재하며, 다른 불필요한 정보가 포함되지 않았습니다. </reason>

피드백:
현재 요약은 모든 평가 기준에서 좋은 평가를 받았습니다. 각 항목에 대한 정보가 명확하고 간결하게 전달되었으며, 원문 기사와의 일치도 잘 이루어졌습니다. 추가적인 개선이 필요하지 않습니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **삼성화재, AI 의료심사 도입으로 암 진단 및 수술급여 심사 효율성 향상**\n  - 삼성화재는 AI 기반의 의료심사 시스템을 도입하여 암 진단 및 수술급여 심사의 효율성과 정확성을 높였으며, 인력 검토 비중이 약 55% 감소했다고 발표했습니다.\n\n- **'해외 2시간 항공지연 특약' 출시로 항공기 지연 및 결항 손해 보장**\n  - 삼성화재는 해외 출발 항공편의 2시간 이상 지연 및 결항 시 발생하는 손해를 최대 50만원까지 보장하는 '해외 2시간 항공지연 특약'을 출시하여 고객의 여행 불편을 최소화하고자 했습니다.\n\n- **외국인 투자자, SK하이닉스 등 주요 종목 순매수**\n  - 외국인 투자자들은 SK하이닉스, 현대차, HD한국조선해양 등 주요 종목을 집중적으로 매수하였으며, 운수장비 업종에 속한 종목들이 다수 포함되었습니다.\n\n**키워드:** 삼성화재, AI 의료심사, 항공지연 특약, 외국인 투자자, SK하이닉스, 현대차, HD한국조선해양\n\n**피드백:**\n- **정확성:** 좋음\n  - 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다.\n\n- **포괄성:** 좋음\n  - 기사에서 다루는 주요 주제인 삼성화재의 AI 의료심사 도입, 항공지연 특약 출시, 외국인 투자자의 주요 종목 매수에 대한 정보가 모두 포함되어 있습니다.\n\n- **간결성:** 좋음\n  - 요약은 불필요한 표현 없이 간결하게 작성되었습니다.\n\n- **문장구성:** 좋음\n  - 문장이 자연스럽고 명확하게 구성되어 있습니다.\n\n- **일관성:** 좋음\n  - 특정 종목에 대한 내용만 존재하며, 다른 불필요한 정보가 포함되지 않았습니다.\n\n**피드백:**\n현재 요약은 모든 평가 기준에서 좋은 평가를 받았습니다. 각 항목에 대한 정보가 명확하고 간결하게 전달되었으며, 원문 기사와의 일치도 잘 이루어졌습니다. 추가적인 개선이 필요하지 않습니다."
[should_stop] Iteration: 1
[should_stop] Feedback:
 **평가:**

- **정확성:** 좋음
  - 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다.

- **포괄성:** 좋음
  - 기사에서 다루는 주요 주제인 삼성화재의 AI 의료심사 도입, 항공지연 특약 출시, 외국인 투자자의 주요 종목 매수에 대한 정보가 모두 포함되어 있습니다.

- **간결성:** 좋음
  - 요약은 불필요한 표현 없이 간결하게 작성되었습니다.

- **문장구성:** 좋음
  - 문장이 자연스럽고 명확하게 구성되어 있습니다.

- **일관성:** 좋음
  - 특정 종목에 대한 내용만 존재하며, 다른 불필요한 정보가 포함되지 않았습니다.

**피드백:**
현재 요약은 모든 평가 기준에서 좋은 평가를 받았습니다. 각 항목에 대한 정보가 명확하고 간결하게 전달되었으며, 원문 기사와의 일치도 잘 이루어졌습니다. 추가적인 개선이 필요하지 않습니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **삼성화재, AI 의료심사 도입으로 암 진단 및 수술급여 심사 효율성 향상**\n  - 삼성화재는 AI 기반의 의료심사 시스템을 도입하여 암 진단 및 수술급여 심사의 효율성과 정확성을 높였으며, 인력 검토 비중이 약 55% 감소했다고 발표했습니다. 이 시스템은 OCR 기술과 생성형 AI를 결합하여 심사 과정의 일관성과 신뢰성을 강화했습니다.\n\n- **'해외 2시간 항공지연 특약' 출시로 항공기 지연 및 결항 손해 보장**\n  - 삼성화재는 해외 출발 항공편의 2시간 이상 지연 및 결항 시 발생하는 손해를 최대 50만원까지 보장하는 '해외 2시간 항공지연 특약'을 출시하여 고객의 여행 불편을 최소화하고자 했습니다. 이 특약은 식음료 비용, 숙박비 등도 보장합니다.\n\n- **외국인 투자자, SK하이닉스 등 주요 종목 순매수**\n  - 외국인 투자자들은 SK하이닉스, 현대차, HD한국조선해양 등 주요 종목을 집중적으로 매수하였으며, 운수장비 업종에 속한 종목들이 다수 포함되었습니다. 이들 종목 중 일부는 주가가 상승했습니다.\n\n**키워드:** 삼성화재, AI 의료심사, 항공지연 특약, 외국인 투자자, SK하이닉스, 현대차, HD한국조선해양\n\n**피드백:**\n- **정확성:** 좋음\n  - 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다.\n\n- **포괄성:** 좋음\n  - 기사에서 다루는 주요 주제인 삼성화재의 AI 의료심사 도입, 항공지연 특약 출시, 외국인 투자자의 주요 종목 매수에 대한 정보가 모두 포함되어 있습니다.\n\n- **간결성:** 좋음\n  - 요약은 불필요한 표현 없이 간결하게 작성되었습니다.\n\n- **문장구성:** 좋음\n  - 문장이 자연스럽고 명확하게 구성되어 있습니다.\n\n- **일관성:** 좋음\n  - 특정 종목에 대한 내용만 존재하며, 다른 불필요한 정보가 포함되지 않았습니다.\n\n**피드백:**\n현재 요약은 모든 평가 기준에서 좋은 평가를 받았습니다. 각 항목에 대한 정보가 명확하고 간결하게 전달되었으며, 원문 기사와의 일치도 잘 이루어졌습니다. 추가적인 개선이 필요하지 않습니다."
[should_stop] Iteration: 2
[should_stop] Feedback:
 **평가:**

- 정확성: 좋음
  - 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다.

- 포괄성: 좋음
  - 기사에서 다루는 주요 주제인 삼성화재의 AI 의료심사 도입, 항공지연 특약 출시, 외국인 투자자의 주요 종목 매수에 대한 정보가 모두 포함되어 있습니다.

- 간결성: 좋음
  - 요약은 불필요한 표현 없이 간결하게 작성되었습니다.

- 문장구성: 좋음
  - 문장이 자연스럽고 명확하게 구성되어 있습니다.

- 일관성: 좋음
  - 특정 종목에 대한 내용만 존재하며, 다른 불필요한 정보가 포함되지 않았습니다.

**피드백:**
현재 요약은 모든 평가 기준에서 좋은 평가를 받았습니다. 각 항목에 대한 정보가 명확하고 간결하게 전달되었으며, 원문 기사와의 일치도 잘 이루어졌습니다. 추가적인 개선이 필요하지 않습니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])
삼성생명 =======

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

KeyboardInterrupt:

In [31]:
total_df = pd.concat(total_con_lst)

In [32]:
total_df.to_csv('total_df.csv',encoding='utf-8-sig')

In [33]:
for _,data in total_df.iterrows():
    print(data.ticker)
    print(data.summary)
    print('-'*100)

우리금융지주
✅ 주요 요약

- **외국인 투자자, 한국 금융시장에 대한 우려 증가**
  글로벌 투자은행인 JP모간과 모건스탠리가 한국을 방문하여 금융당국 및 주요 금융지주 회장들과 회동할 예정입니다. 이는 정부의 금융권 압박과 관련된 리스크를 직접 평가하기 위한 것으로, 국민성장펀드와 교육세 인상 등으로 인한 금융사의 건전성 악화에 대한 우려가 커지고 있습니다.

- **정부의 금융권 압박, 은행주 하락 원인**
  정부의 정책 변화, 특히 교육세 인상과 금융권에 대한 비판이 은행주의 투자심리를 위축시키고 있습니다. 이는 외국인 투자자들이 한국 금융시장에서의 투자 매력을 재평가하게 만들고 있으며, 금융지주 주가에 부정적인 영향을 미치고 있습니다.

- **금융권의 높은 연봉, 정부의 상생 압박 강화**
  금융권의 높은 연봉과 사상 최대 실적이 정부의 상생 압박을 강화시키고 있습니다. 이는 금융사의 수익성과 경쟁력을 약화시키는 요인으로 작용하고 있으며, 외국인 지분율이 높은 금융지주사들은 비상 상황에 직면하고 있습니다.

🔑 **키워드**: 글로벌 투자자, 금융시장, 정부 압박, 은행주 하락, 금융권 연봉, 상생 압박, 교육세 인상, 투자심리, 금융사 수익성.

**개선 포인트**:
1. **정확성**: 기사에 명시된 내용을 중심으로 요약을 구성하여 정확성을 높였습니다.
2. **간결성**: 중복된 표현을 제거하고, 핵심 내용을 중심으로 간결하게 작성했습니다.
3. **일관성**: 금융권의 연봉 문제와 정부의 정책 변화에 대한 영향을 별도로 다루어 일관성을 유지했습니다.
----------------------------------------------------------------------------------------------------
삼성화재
✅ 주요 요약
- 삼성생명, 상반기 사상 최대 실적 기록
  삼성생명은 올해 상반기 순이익이 1조3941억원으로 전년 동기 대비 1.9% 증가하며, 2년 연속 최대 실적을 기록했습니다. 건강보험 판매 호조가 실적을 견인했습니다.

- 삼성화재, 소비자보호대상 손해보험 부문 최우수상 수상
  삼성화재는 소비자 보호 경영 구조를 확립하고 고객 의견을 반영한 점이 인정되어 '금융소비자보호대상' 손해보험 부문에서 최우수상을 수상했습니다. 고객 참여 활동을 통해 실질적인 개선을 도모하고 있습니다.

- 삼성화재, 항공지연 특약 출시로 해외여행보험 강화
  삼성화재는 해외 항공지연 시 최대 50만원까지 보장하는 '해외 2시간 항공지연 특약'을 출시하여 해외여행보험을 강화했습니다. 이는 고객의 여행 중 불편을 최소화하기 위한 조치입니다.

✅ 키워드
- 삼성생명, 최대 실적, 순이익, 건강보험
- 삼성화재, 소비자보호대상, 최우수상, 고객 참여
- 항공지연 특약, 해외여행보험, 보장 강화
----------------------------------------------------------------------------------------------------
삼성생명
✅ 주요 요약

- **삼성생명, 2분기 실적 시장 기대치 초과**
  삼성생명의 2분기 연결 지배 순이익이 전년 동기 대비 2% 증가하여 시장 컨센서스를 9% 초과하며 양호한 실적을 기록하였습니다. 이는 손실계약 환입과 보험계약마진(CSM) 상각익 증가가 주요 원인으로 작용했습니다.

- **투자의견 '보유'로 하향, 주가 상승 여력 제한적**
  한화투자증권은 삼성생명의 호실적에도 불구하고 주가 상승 여력이 제한적이라며 투자의견을 '매수'에서 '보유'로 하향 조정하였습니다. 이는 현재 주가가 적정 가치를 충분히 반영하고 있다는 분석에 기반합니다.

- **삼성전자 지분 매각 가능성, 자본효율성 개선 기대**
  삼성생명이 보유한 삼성전자 지분 매각 가능성으로 인해 자본효율성이 개선될 것으로 기대되며, 이는 주가에 긍정적으로 반영될 전망입니다. 정부의 보험업법 개정안과 상법 개정안이 국회에 상정되면서 지분 처분 압력이 커지고 있습니다.

📌 **키워드**: 삼성생명, 2분기 실적, 주가 상승, 투자의견 하향, 삼성전자 지분 매각, 자본효율성 개선.
----------------------------------------------------------------------------------------------------
카카오뱅크
✅ 주요 요약

- **인터넷은행, 가계대출 규제로 국공채 투자 증가**
  - 인터넷은행들이 가계대출 규제로 인해 대출 확장에 제약을 받자, 예·적금으로 모은 자금을 국공채에 투자하여 유가증권이 급증함. 이는 안정적이지만 수익성이 낮아 수익성 지표가 시중은행보다 빠르게 하락하고 있음.

- **중·저신용자 대출 비중 규제 대응 어려움**
  - 인터넷은행들이 중·저신용자 대출 비중 규제를 맞추기 위해 고신용자 대출을 줄이며 대응 중이나, 대출 문턱이 높아져 어려움을 겪고 있음.

🔑 **키워드**: 인터넷은행, 가계대출 규제, 국공채 투자, 수익성 하락, 중·저신용자 대출, 비중 규제, 대출 문턱.

---

**개선 포인트**:
- **정확성**: 인터넷은행의 수익성 하락 이유와 관련된 구체적인 설명을 추가하여 정보 전달의 정확성을 높였습니다.
- **포괄성**: 인터넷은행의 가계대출 규제와 국공채 투자, 중·저신용자 대출 비중 규제 등 중요한 정보가 모두 포함되었습니다.
- **일관성**: 인터넷은행 관련 내용에 집중하여 요약의 일관성을 유지했습니다.
----------------------------------------------------------------------------------------------------
메리츠금융지주
✅ 주요 요약
- 메리츠금융지주, 상반기 역대 최대 실적 기록
  메리츠금융지주는 상반기 연결기준 순이익 1조3584억원을 기록하며 전년 동기 대비 2.3% 증가, 반기 기준 최대 실적을 경신했다. 이는 메리츠화재와 메리츠증권의 안정적인 수익 구조 강화에 기인한다.

- 주주환원 정책 강화, 자사주 매입 및 소각 적극 추진
  메리츠금융지주는 7000억원 규모의 자사주 신탁계약을 체결하고, 주주가치 제고를 위해 자사주 매입 및 소각을 적극적으로 추진하고 있다. 이는 주주 신뢰 회복과 주가 상승의 주요 요인으로 작용하고 있다.

- 실적 기반의 주가 상승, 중장기 가치 재평가 기대
  메리츠금융지주의 실적 개선과 주주환원 정책이 결합되어 주가가 상승하고 있으며, 이는 중장기적인 가치 재평가의 신호로 해석되고 있다. 특히, 업계 최고 수준의 자기자본이익률(ROE) 26.3%는 기업의 수익성과 안정성을 뒷받침한다.

🔑 키워드: 메리츠금융지주, 최대 실적, 주주환원, 자사주 매입, 주가 상승, 중장기 가치 재평가, 실적 개선, 자기자본이익률(ROE)
----------------------------------------------------------------------------------------------------
현대모비스
✅ 주요 요약

- **현대모비스, 차량용 반도체 연구개발 프로세스 ISO 26262 인증 획득**
  - 현대모비스는 차량용 반도체 연구개발 프로세스 전체에 대해 국제 안전 표준인 ISO 26262 인증을 획득했습니다. 이는 제품 단위로 인증받은 것과 동일한 신뢰성을 확보하게 하며, 국내 차량용 반도체 생태계 확장에 기여할 계획입니다.

- **로보틱스 및 반도체 분야에서 신성장 동력 확보 계획**
  - 현대모비스는 로보틱스와 차량용 반도체 분야에서 미래 성장 기회를 포착하고, 핵심 역량을 조기에 확보하기 위한 전략을 발표했습니다. 특히, 로봇 관절 모터인 '액추에이터' 개발을 통해 로봇 시장 진출을 공식화했습니다.

- **외국인 투자자, 현대모비스 주식 집중 매수**
  - 외국인 투자자들이 현대모비스 주식을 집중적으로 매수하며, 주가 상승세를 뒷받침하고 있습니다. 이는 현대모비스의 실적 개선과 미래 성장 가능성에 대한 긍정적 평가가 반영된 결과로 보입니다.

🔑 **키워드**: 현대모비스, ISO 26262, 차량용 반도체, 로보틱스, 외국인 투자자, 주가 상승, 신성장 동력, 인증 획득, 연구개발, 투자 전략.
----------------------------------------------------------------------------------------------------
현대오토에버
✅ 주요 요약

- **KTis 실적 개선**
  KTis는 매출액 140,722백만원으로 4.10% 증가, 순이익은 73.21% 증가한 5,481백만원을 기록하며 긍정적인 실적을 보임.

- **NI스틸 실적 하락**
  NI스틸은 매출액이 21.06% 감소한 63,016백만원, 순이익은 45.65% 감소한 5,142백만원으로 실적이 하락.

- **경보제약 매출 증가, 순이익 적자전환**
  경보제약은 매출액 65,313백만원으로 11.81% 증가했으나, 순이익은 적자전환.

- **롯데하이마트 순이익 급증**
  롯데하이마트는 매출액 594,203백만원으로 0.83% 증가, 순이익은 667.23% 증가한 11,117백만원을 기록하며 순이익이 급증.

- **삼성제약 흑자전환**
  삼성제약은 매출액 10,898백만원으로 3.02% 증가, 순이익은 63,572백만원으로 흑자전환.

- **사조오양 실적 호조**
  사조오양은 매출액 100,747백만원으로 7.75% 증가, 순이익은 354.12% 증가한 7,060백만원을 기록.

- **미창석유공업 순이익 증가**
  미창석유공업은 매출액 104,163백만원으로 11.24% 감소했으나, 순이익은 32.74% 증가한 38,970백만원을 기록.

- **광명전기 적자 지속**
  광명전기는 매출액 26,657백만원으로 7.90% 감소, 영업이익과 순이익 모두 적자가 지속됨.

- **삼일씨엔에스 흑자전환**
  삼일씨엔에스는 매출액 58,012백만원으로 0.88% 증가, 순이익은 흑자전환하여 1,225백만원을 기록.

- **미래아이앤지 매출 증가, 순이익 적자전환**
  미래아이앤지는 매출액 3,624백만원으로 21.01% 증가했으나, 순이익은 적자전환.

🔑 키워드: KTis, NI스틸, 경보제약, 롯데하이마트, 삼성제약, 사조오양, 미창석유공업, 광명전기, 삼일씨엔에스, 미래아이앤지, 매출액, 순이익, 증감률.
----------------------------------------------------------------------------------------------------
SK하이닉스
✅ 주요 요약
- **SK하이닉스, AI 메모리 수요 증가로 HBM 시장에서 우위 점유**
  SK하이닉스는 AI 메모리 수요 확대에 힘입어 고대역폭 메모리(HBM) 분야에서 우위를 점하며, 기업 사상 최대 분기 실적을 기록하고 있다. NVIDIA 등 주요 AI 고객과의 협력 강화가 긍정적으로 작용했다.

- **HBM 시장 성장 전망 및 가격 압박 우려**
  SK하이닉스는 HBM 시장의 높은 성장률을 예상하지만, 일부 분석가들은 2026년 이후 공급 과잉과 가격 경쟁 심화 가능성을 우려하고 있다.

- **321단 2테라비트 QLC 낸드플래시 양산 시작**
  SK하이닉스는 321단 2테라비트 QLC 낸드플래시를 양산하여 AI 데이터센터 시장을 본격적으로 공략할 계획이다. 이 제품은 데이터 전송 속도와 전력 효율성을 크게 개선했다.

🔑 **키워드**: SK하이닉스, AI 메모리, 고대역폭 메모리(HBM), 321단 QLC 낸드플래시, 시장 성장 전망, 가격 압박, 기술 경쟁력.
----------------------------------------------------------------------------------------------------
현대글로비스
✅ 주요 요약

- **현대글로비스, 세계 물류 브랜드 21위 기록**
  - 현대글로비스는 브랜드 파이낸스의 '로지스틱스 25 2025' 보고서에서 30억 달러의 가치를 인정받아 세계 물류 브랜드 21위에 올랐으며, 이는 국내 물류기업 중 유일한 기록이다.

- **현대글로비스, 2분기 사상 최대 실적 달성**
  - 현대글로비스는 2분기 매출 7조5160억 원, 영업이익 5389억 원을 기록하며, 비계열 고객사 확장과 중국 완성차 운송 물량 증가로 사상 최대 실적을 달성했다.

- **글로벌 물류 네트워크 확장 및 신사업 투자**
  - 현대글로비스는 친환경 및 첨단 공급망 구축에 지속적으로 투자하며, 항공 물류 사업 확장 등으로 글로벌 물류 네트워크를 강화하고 있다.

🔑 키워드
- 현대글로비스
- 물류 브랜드
- 2분기 실적
- 비계열 고객
- 중국 완성차 운송
- 글로벌 네트워크
- 항공 물류
- 친환경 투자

### 피드백
- **정확성: 좋음**
  - 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다.

- **포괄성: 좋음**
  - 현대글로비스에 대한 중요한 정보가 모두 포함되어 있으며, 브랜드 가치, 실적, 글로벌 네트워크 확장 및 신사업 투자에 대한 내용이 잘 반영되었습니다.

- **간결성: 좋음**
  - 불필요한 표현 없이 핵심 내용만 간결하게 전달되었습니다.

- **문장구성: 좋음**
  - 문장이 자연스럽고 명확하게 구성되어 있어 이해하기 쉽습니다.

- **일관성: 좋음**
  - 현대글로비스에 대한 내용만 포함되어 있으며, 다른 종목에 대한 내용은 없습니다.

### 개선된 요약
요약은 전반적으로 잘 작성되었으며, 현대글로비스에 대한 주요 정보를 정확하고 간결하게 전달하고 있습니다. 모든 평가 기준에서 좋은 평가를 받았으며, 개선이 필요한 부분은 없습니다. 앞으로도 이러한 형식을 유지하여 요약을 작성하면 좋겠습니다.
----------------------------------------------------------------------------------------------------
현대차
✅ 주요 요약

- **현대차그룹, 미국에 260억 달러 투자 계획 발표**
  현대차그룹은 미국 내 제철소 건설 및 로봇 공장 신설 등 다양한 분야에 260억 달러를 투자하여 미래 사업 경쟁력을 강화하고, 미국과의 경제 협력을 확대할 계획임.

- **현대차, 유럽 전기차 시장 공략 위한 현지 전용 모델 출시 예정**
  현대차는 유럽 전기차 시장의 성장세에 맞춰 독일에서 '아이오닉2'를 공개할 예정이며, 이는 유럽 현지에서 개발 및 생산될 전략 모델임.

- **현대차그룹, 글로벌 리더십 인정받아**
  현대차그룹의 제네시스가 JD파워의 '2025 기술 경험 지수' 조사에서 5년 연속 1위를 차지하며, 현대차와 기아도 각각 대중차 브랜드 1위와 2위를 기록함.

- **현대차, 미국 내 관세 및 노조 리스크 직면**
  현대차는 미국의 15% 관세와 노조 파업 가능성으로 인해 수익성 악화와 생산 차질의 위험에 직면해 있음. 노조는 파업권을 확보하고 구체적인 파업 계획을 논의 중임.

- **현대차그룹, 미국 내 생산 및 공급망 강화**
  현대차그룹은 미국 루이지애나 주에 270만 톤 규모의 전기로 제철소를 건설하고, 연 3만 대 규모의 로봇 공장을 신설하여 미국 내 철강-부품-완성차로 이어지는 밸류 체인을 구축할 계획임.
----------------------------------------------------------------------------------------------------
삼성전자
✅ 주요 요약

- **삼성전자, 테슬라와 AI 칩 공급 계약 체결**
  삼성전자는 테슬라와 수조 원대 규모의 AI 칩 공급 계약을 체결하여, 반도체 부문에 중장기적 성장 동력을 제공할 수 있는 중요한 이벤트로 평가받고 있다.

- **IFA 2025 참가 및 AI 홈 기술력 소개**
  삼성전자는 독일 베를린에서 열리는 IFA 2025에 참가하여 'AI 홈, 미래 일상을 현실로'라는 주제로 최신 디스플레이 기술과 AI 기반 가전제품을 선보일 예정이다. 이는 스마트홈 플랫폼 '스마트싱스'를 통해 차별화된 AI 홈 경험을 제공하는 데 중점을 두고 있다.

- **글로벌 무역 환경 개선 및 경영 리스크 해소**
  미국과 중국 간 관세 완화 논의와 한국과의 무역 긴장 완화 조짐이 나타나고 있으며, 경영 승계 관련 법적 리스크가 해소되어 투자자 신뢰 회복에 긍정적인 영향을 미치고 있다.

- **미국 시장에서의 실적 증가**
  삼성전자는 미국 시장에서 스마트폰 사업의 호조로 상반기 순이익이 전년 동기 대비 세 배 가까이 증가했다. 이는 갤럭시 Z폴드7의 성공적인 출시와 맞물려 하반기 실적 개선 가능성을 높이고 있다.

- **삼성전자의 AI 인재 발굴 및 육성 전략**
  삼성전자는 AI 엑스퍼트 프로그램을 통해 내부 AI 인재를 발굴하고 육성하여, AI 선도 기업으로 도약하기 위한 전략을 추진하고 있다. 이 프로그램은 AI 관련 최고 수준의 성과를 낸 임직원에게 격려금과 자격 수당을 제공한다.

🔑 키워드: 삼성전자, 테슬라, AI 칩 공급 계약, 반도체, IFA 2025, AI 홈, 무역 환경, 경영 리스크, AI 엑스퍼트, 투자자 신뢰, 글로벌 공급망, 관세 완화, 미국 시장, 실적 증가.
----------------------------------------------------------------------------------------------------
한미반도체
✅ 주요 요약

- **한미반도체, HBM 시장 성장과 AI 수요 증가로 주가 상승**
  한미반도체는 고대역폭 메모리(HBM) 시장의 성장과 AI 중심 데이터 처리 수요 증가로 주가가 상승했으며, HBM 패키징 공정 장비의 독점 공급자로 주목받고 있음.

- **SK하이닉스로부터 대규모 수주 확보, 실적 호조**
  한미반도체는 SK하이닉스로부터 창사 이래 최대 규모의 HBM용 듀얼 TC 본더 수주를 확보하며 실적 호조를 이어가고 있음. 이는 기술력과 납품 안정성을 입증한 결과로, 향후 실적 모멘텀에 대한 신뢰를 강화함.

- **주주 친화 정책으로 투자 매력 강화**
  한미반도체는 자사주 소각 등 적극적인 주주 환원 전략을 통해 기업의 실적과 미래 성장성에 대한 자신감을 나타내며, 투자자들의 관심을 끌고 있음.

- **후발 경쟁자들의 시장 진입으로 경쟁 심화 우려**
  한화세미텍과 LG전자의 차세대 패키징 장비 개발로 인해 한미반도체의 단독 공급 구조에 균열이 생길 수 있다는 우려가 제기되고 있음.

🔑 키워드: 한미반도체, 고대역폭 메모리(HBM), AI 데이터 처리, 주가 상승, SK하이닉스, 대규모 수주, 주주 친화 정책, 경쟁 심화, 한화세미텍, LG전자.
----------------------------------------------------------------------------------------------------
파크시스템스
✅ 주요 요약

- **유가증권시장 2025년 2분기 실적 현황**
  - **KTis**: 매출액 140,722백만원으로 4.10% 증가, 순이익 73.21% 증가한 5,481백만원 기록.
  - **NI스틸**: 매출액 63,016백만원으로 21.06% 감소, 순이익 45.65% 감소.
  - **경보제약**: 매출 11.81% 증가했으나 순이익은 적자전환.
  - **롯데하이마트**: 매출액 594,203백만원으로 0.83% 증가, 순이익 667.23% 증가.
  - **삼성제약**: 매출액 10,898백만원으로 3.02% 증가, 순이익 흑자전환.

- **기사, AI 알고리즘에 의해 자동 생성**
  이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 작성되었습니다.

🔑 **키워드**: 유가증권시장, 실적 현황, KTis, NI스틸, 경보제약, 롯데하이마트, 삼성제약, AI 알고리즘, 자동 생성.

**피드백 반영**:
1. **정확성**: 각 종목의 실적 수치와 변화율을 정확하게 반영했습니다.
2. **포괄성**: 원문 기사에 언급된 모든 주요 정보를 포함하여 포괄성을 높였습니다.
3. **간결성**: 불필요한 중복 표현을 제거하고, 핵심 정보를 간결하게 전달했습니다.
4. **문장구성**: 문장을 명확하고 간단하게 구성하여 독자가 쉽게 이해할 수 있도록 했습니다.
5. **일관성**: 특정 종목의 실적에 초점을 맞춰 일관된 정보를 제공했습니다.
----------------------------------------------------------------------------------------------------
DB하이텍
✅ 주요 요약

- **외국인 투자자, 카카오 등 주요 종목 집중 매수**
  8월 26일, 외국인 투자자들이 카카오, HD현대일렉트릭, 효성중공업 등 다양한 종목을 집중적으로 매수했으며, 특히 전기·전자 업종의 주식들이 포함됨. 이들 종목 중 일부는 주가가 상승했으나, 두산과 한화에어로스페이스 등은 하락세를 보임.

- **부자네스탁론, 유연한 조건의 스탁론 상품으로 주목**
  부자네스탁론은 본인 자산 포함 최대 4배까지 투자 가능하며, 담보유지비율 120%의 조건을 제공하여 투자자들 사이에서 인기를 끌고 있음. 이 상품은 미수금이나 반대매매 위험을 해결해주는 대환대출 서비스도 포함하고 있어, 다양한 투자 솔루션을 제공함.

- **미국 정부, 인텔 지분 인수 논의로 주가 상승**
  미국 정부가 인텔 지분 인수를 논의하면서 인텔 주가가 급등세를 보임. 이 논의는 오하이오주 반도체 공장 건설에 자금을 투입할 가능성이 있으며, 정부의 반도체 산업 개입이 글로벌 경쟁 구도에 영향을 미칠 것으로 예상됨. 전문가들은 이로 인해 삼성전자와 TSMC 같은 경쟁사에 부정적 영향을 미칠 수 있다고 평가함.
----------------------------------------------------------------------------------------------------
기아
✅ 주요 요약

- **현대차 및 기아, 외국인 투자자 매수세로 주가 상승**
  - 외국인 투자자들이 현대차와 기아를 대규모로 매수하면서 주가가 상승세를 보이고 있습니다. 이는 미국의 25% 고율 관세 불확실성 해소와 현지화 전략 강화에 따른 결과로 분석됩니다. 현대차는 최근 한 달간 5.5% 상승하며 유가증권시장 시가총액 5위 자리를 탈환했습니다.

- **현대차, 미국 시장에서 하이브리드 차량 수요 증가로 긍정적 전망**
  - 현대차는 하이브리드 차량의 미국 내 수요 증가에 힘입어 시장 점유율을 확대할 계획입니다. 특히, 팰리세이드 하이브리드 모델을 미국에 출시할 예정이며, GM과의 협업을 통해 미국 내 핵심 제조업체로 성장할 가능성이 높습니다. 현재 현대차의 하이브리드 시장 점유율은 15%로, 내년에는 20%, 2027년에는 30%까지 확대될 것으로 예상됩니다.

- **현대차그룹, JD파워 기술 경험 지수 조사에서 제네시스와 현대차 1위 차지**
  - 제네시스는 고급 브랜드 부문에서, 현대차는 대중 브랜드 부문에서 각각 1위를 차지했습니다. 이번 조사는 2025년형 신차를 구입한 7만6230명을 대상으로 진행되었으며, 제네시스는 538점, 현대차는 493점을 기록하며 기술 혁신과 소비자 만족도에서 높은 평가를 받았습니다.

- **현대차 및 기아, 유럽 시장에서의 성과**
  - 현대차와 기아는 유럽 시장에서도 주목할 만한 성과를 거두고 있습니다. 2025년 7월 유럽 시장에서 현대차와 기아의 점유율은 각각 4.5%와 3.9%를 기록했습니다. 특히, 현대차의 투싼과 코나, 기아의 스포티지와 씨드가 주요 판매 차종으로 자리 잡고 있습니다. 현대차는 49,148대, 기아는 42,671대를 판매하며 각각 전년 대비 3.9% 증가와 8.5% 감소를 기록했습니다.

- **현대차, 미국 내 생산 확대**
  - 현대차는 미국 내 생산을 확대하며 현지화 전략을 강화하고 있습니다. 올해 상반기 미국 공장에서의 생산량은 전년 대비 22% 증가했으며, HMGMA의 가동률도 72.6%로 상승했습니다. 이는 미국 시장에서의 경쟁력을 높이기 위한 전략으로 평가됩니다.

✅ 키워드
- 현대차, 기아, 외국인 투자자, 주가 상승, 하이브리드 차량, 미국 시장, JD파워, 제네시스, 유럽 시장, 생산 확대, 기술 혁신, 소비자 만족도

✅ 개선 사항
1. **포괄성 강화**: 현대차와 기아의 유럽 시장 점유율 변화 및 주요 판매 차종에 대한 구체적인 수치를 포함하여 요약의 포괄성을 높였습니다.
2. **일관성 유지**: 현대차와 기아의 주가 상승 및 JD파워 조사 결과에 대한 부분을 별도로 구분하여 설명함으로써 일관성을 강화했습니다.
----------------------------------------------------------------------------------------------------
POSCO홀딩스
✅ 주요 요약

- **에코프로비엠, 깜짝 실적 발표와 전기차 시장 회복 기대에 주가 상승**
  - 2분기 실적 발표에서 예상치를 크게 웃도는 영업이익 흑자 전환 소식이 투자 심리를 자극하며, 전기차 시장의 회복 분위기가 에코프로비엠에 대한 구조적 수혜 기대를 높임.

- **외국인 매수세와 밸류에이션 재평가로 주가 상승세 지속**
  - 외국인 투자자 중심의 매수세가 강하게 유입되며, 밸류에이션 측면에서 과거에 비해 저평가 해소 흐름이 감지되면서 주가 상승의 논리적 기반이 됨.

- **과열 우려 속 신중한 투자 접근 필요**
  - 높은 밸류에이션 부담과 2차전지 수요 회복 속도에 대한 불확실성으로 인해 일부에서는 과열 우려의 목소리가 존재하며, 투자자들에게 신중한 접근을 당부.

🔑 **키워드**: 에코프로비엠, 전기차 시장, 실적 발표, 외국인 매수세, 밸류에이션 재평가, 과열 우려, 투자 심리.
----------------------------------------------------------------------------------------------------
LG에너지솔루션
✅ 주요 요약

- **국내 배터리 3사, 상반기 공장 가동률 저조**
  LG에너지솔루션, 삼성SDI, SK온 등 국내 배터리 3사의 상반기 공장 가동률이 40~50%대에 그쳤으며, 이는 전기차 수요 둔화와 발주 조정의 영향으로 분석됨.

- **LG에너지솔루션, 베트남 킴롱모터스와 MOU 체결**
  LG에너지솔루션은 베트남 킴롱모터스와 전기버스용 배터리 셀 공급을 위한 업무협약을 체결하며 아시아 전기차 시장 내 입지를 강화함.

- **한국 배터리 3사, 글로벌 시장 점유율 하락**
  LG에너지솔루션, SK온, 삼성SDI의 글로벌 시장 점유율이 중국 CATL에 비해 크게 낮아졌으며, 삼성SDI와 SK온은 적자 가능성이 높음.

- **배터리 3사, 연구개발(R&D) 투자 증가**
  불황에도 불구하고 LG에너지솔루션과 삼성SDI는 연구개발(R&D) 투자를 늘리며 미래 기술 개발에 집중하고 있음. LG에너지솔루션의 R&D 비용은 매출의 5.2%를 차지하며, 삼성SDI는 11.1%로 증가함.

🔑 키워드
- 배터리 3사
- 공장 가동률
- 전기차 수요
- LG에너지솔루션
- 베트남 킴롱모터스
- 글로벌 시장 점유율
- CATL
- 적자 가능성
- 연구개발 투자 증가
----------------------------------------------------------------------------------------------------

## 2. chunk만 수행하기

In [ ]:
test_ticker = '우리금융지주'
CrossEncoder_prompt_test = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [254]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=50)

In [255]:
retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})

In [256]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
)

In [257]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [259]:
list(map(lambda x: x.metadata['title'],compressed_docs))[:5]

["SK하이닉스 또 '사상 최고' 실적…분기 영업익 9조 넘었다",
 "SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+]",
 "'역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다",
 'AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화',
 'SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위']

compressed_docs와 수기로 계산한 것이 같은 것 증명

In [246]:
retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
CrossEncoder_prompt = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''
print(CrossEncoder_prompt.strip())
raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]

scores = model.score(pairs)
scored = sorted(zip(raw_docs, scores), key=lambda x: float(x[1]), reverse=True)[:50]
scored_docs=[]
# 3) 점수 붙이고 재정렬
for d, s in zip(raw_docs, scores):
    dd = deepcopy(d)
    dd.metadata["relevance_score"] = float(s)
    scored_docs.append(dd)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [260]:
pd.DataFrame(list(map(lambda x: x.metadata,scored_docs))).sort_values(by=['ticker','relevance_score'],ascending=False).head(5)

,original_idx,title,url,label,chunk_idx,ticker,Date,relevance_score
47,3560,SK하이닉스 또 '사상 최고' 실적…분기 영업익 9조 넘었다,https://www.hankyung.com/article/202507248226g,1,1,SK하이닉스,2025-07-24,0.684618
25,3927,SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+],https://www.hankyung.com/article/2025072510306,1,1,SK하이닉스,2025-07-25,0.672207
37,3724,"'역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다",https://magazine.hankyung.com/business/article...,1,0,SK하이닉스,2025-07-24,0.611750
15,3744,"AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화",https://www.hankyung.com/article/202507313103a,1,0,SK하이닉스,2025-07-31,0.601519
14,3867,"SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위",https://magazine.hankyung.com/job-joy/article/...,1,2,SK하이닉스,2025-07-28,0.455363

이어서 시작

In [336]:
unique_lst = list(set(list(map(lambda x: x.page_content,compressed_docs))))

In [337]:
chunk_total = ''.join(unique_lst)

In [338]:
chunk_total

'KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요 금융지주들의 연간 실적 전망은 오히려 상향 조정되는 추세다.이는 각 금융지주가 이자이익 축소에 대비해 새로운 수익원 확보에 주력했기 때문으로 분석된다.KB금융은 오는 24일, 신한·하나·우리금융은 25일 차례로 2분기 실적을 발표할 예정이다.정유진 기자 jinjin@hankyung.com강세장을 이끈 것은 5조원 순매수한 연기금 외에 자사주와 외국인이다. 현재까지 자사주 매입은 약 10조원에 달할 것으로 추정되는데 삼성전자와 은행이 주요 매수 주체였다. 이 추세는 정부 정책과 맞물려서 하반기에도 이어진다. 하반기 6조원이 더해지면 올해 약16조원이 자사주 매입의 형태로 증시에 유입되는데 이는 작년의 2조원 자사주 순매수와 크게 대비된다. 외인은 연초부터 4월 말까지 트럼프의 관세 악재로 18조 매도했지만 이후 매수로 전환해서 12조원의 순매수를 누적했다.2000년 이후 25년 동안 외인의 누적 순매수 추세는 2번의 80조원 싸이클과 1번의 40조원 사이클을 보인 후 4번째 순환사이클을 막 시작했다. 직전 순매수 저점에서 12조를 매수하면서 업사이클로 전환했는데 향후 몇 년에 걸쳐 수십 조원의 한국 주식 순매수가 지속될 것으로 전망된다. 외인은 한국의 기업이익이 추세적으로 증가하고 원화 강세가 추세를 형성할 때 수년 지속되는 매수 싸이클을 형성하는데 이번에는 친주주 성향의 새 정부 정책으로 순매수 싸이클 정점이 높고 지속 기간도 높을 것으로 전망된다. 정부의 부동산 억제 정책과 증시 친화적인 정책으로 국내 투자가들의 장기투자 전환 가능성도 높아 수년간 지속되는 강세장이 예상된다. 원전주/증권/은행지수가 걱정의 벽을 타고 예상보다 큰 폭으로 상승했고 이익 전망이 구조적으로 향상된 조선, 방산, 원전, 전력기기 업종과 주주 환원이 강화된 지주, 금융 업종이 상반기 상승을 주도했다. 급등한 지수보다 더 큰 폭으로 오른 상반기 주도주에 대한 차익 실현 수요가 매우 커서 그동안 소외된 삼성전자와 밸류체인, 2차전지, 소재의 반등이 강력한데 그럼에도 후자의 이익 규모와 지속성이 제한적이어서 8월 이후의 유망 업종 선택에는 많은 고민이 필요하다. 기존 주도 업종들은 성장 가능성에도 불구하고 밸류에이션 부담과 피크 아웃에 대한 우려가 상존해서 주가 및 기간 조정을 염두에 두고 저가 매수를 고려해야 하고 소외되었던 주식들의 급반등은 조심스러운 시각으로 접근할 필요성이 높다. KOSPI 3,000pt 이후 매수 강도를 높여가고 있는 외인이 선호하면서 하반기 및 내년에 이익이 크게 증가할 수 있는 대형주에 대한 매수 수요가 지속될 가능성이 높은 국면이 기대된다. 업종별 키 맞추기지수가 걱정의 벽을 타고 예상보다 큰 폭으로 상승했고 이익 전망이 구조적으로 향상된 조선, 방산, 원전, 전력기기 업종과 주주 환원이대장주라는 걸 감안해도 너무 올랐다는 건가요?<기자> 그렇습니다. 한국투자증권과 삼성증권 등 경쟁사들이 미래에셋증권에 대해 2분기 어닝 서프라이즈 기대가 된다면서도 투자의견을 \'중립\'으로 하향 조정했습니다. 다른 증권사 대비 더 다양한 수혜가 이미 반영됐다고 판단한 건데요. 대표적인 게 자사주 소각 의무화와 스테이블코인 법제화입니다.미래에셋증권의 자사주 보유량은 23% 수준으로 대형 증권사 가운데 가장 많습니다. 또 자회사인 미래에셋컨설팅이 스테이블 코인 상표를 출원하면서 사실상 정책적 호재는 모두 입었습니다. 주가가 고평가 됐다는 입장에서는 자사주 소각과 스테이블 코인은 이제 법안 발의 단계인 탓에 실제 실행까진 지금은 너무 이른 시점이라는 판단입니다.우리가 적정주가를 산정하는 방법 가운데 하나로 주가순자산비율(PBR)을 활용하잖아요. 증권업종은 대표적인 저 PBR 업종인데요. 최근 가파른 주가 상승으로 미래에셋증권이 한때 PBR 1배 수준를 넘기기도 했습니다. 순이익이 커지면 PBR은 낮아지는데. 2분기 순이익 증가분을 반영해도 PBR이 1배 수준을 보여 추가 상승여력이 낮다는 평가입니다.<앵커> 우리 증권사들도 금융위기 전에는 PBR 1배 이상을 보인 것으로 아는데요.<기자> 증권업 호황시절인 2008년 이전에 1배에서 1.5배 수준을 보이긴 했는데요. 그 이후엔 드물었습니다. 팬데믹 기간 1배에 근접하긴 했지만 다시 하락해 최근까지 0.4배 정도에 머물렀습니다. 현재 JP모건이나 골드만삭스, 모건스탠리 같은 글로벌 투자은행(IB)들의 PBR이 2배 수준에 근접하는데요.더 오를 수 있다는 쪽에선 미래에셋증권 뿐만 아니라 다른 증권사들의 PBR이 평균 0.9배 수준으로 올라왔다는 점을 강조합니다. 무엇보다 증권업종의 저 PBR이 한국 증시의 이른바 \'코리아 디스카운드\'로부터 비롯됐다는 점에서 증시 상승세가 이어진다면 PBR 1.2배 이상까지도 문제 없다는 시각이 있습니다. 실제 NH투자증권은 미래에셋증권의 타겟 PBR을 1.2배로 설정해 목표주가를 28,000원으로 제시했습니다.<앵커> 네. 잘 들었습니다.정재홍기자 jhjeong@wowtv.co.kr금융당국이 예정에 없던 긴급 간담회를 소집한 것은 사상 최대 이익을 거둔 금융지주를 향한 금융권 안팎의 ‘불편한 기류’가 확산하고 있어서다. 경기 악화, 미국발(發) 관세 불확실성 등 각종 악재가 불거지는 와중에 금융권만 때아닌 호황을 누리고 있다는 비판이 커지고 있기 때문이다.KB 신한 하나 우리 등 4대 금융은 올 상반기에만 10조원 넘는 순이익을 냈다. 이자이익과 비이자이익이 동시에 불어나며 역대 최대 순이익을 올렸다. 저금리 기조 속에도 4대 금융의 상반기 이자수익은 21조924억원으로, 작년 동기(20조8106억원) 대비 2818억원(1.4%) 늘었다. 금융권 관계자는 “금리, 환율 하락으로 유가증권·외환·파생 이익 등이 전반적으로 급증했고 은행 퇴직연금·방카슈랑스 판매수수료와 증권 중개수수료 등 비이자이익도 증가했다”고 설명했다.역대급 이익을 낸 금융권을 향한 정부의 압박은 한층 거세지고 있다. 이재명 대통령이 ‘이자놀이’를 비판하면서다. 이 대통령은 시장 유동 자금이 부동산이 아니라 국가 경쟁력을 높일 수 있는 혁신 기업에 유입돼야 한다는 의견을 여러 차례 밝혔다.금융당국은 이번 간담회를 통해 대통령 핵심 공약인 ‘100조원 첨단산업 펀드’ 조성을 위한 금융권의 적극적인 참여를 독려할 것으로 보인다. 앞서 정부는 국민과 기업이 함께 참여하는 100조원 규모 펀드를 통해 인공지능(AI), 바이오, 항공우주 등 첨단 산업 경쟁력을 높이겠다는 로드맵을 마련했다. 다양한 자본시장 활성화 방안도 논의될 전망이다. 앞서 권대영 금융위원회 부위원장은 “금융권에 넘치는 돈이 자본시장 등 생산적인 곳으로 흘러갈 수 있도록 물꼬를 트겠다”고 공언했다.금융권은 이번 간담회에서 벤처 투자 등을 늘리기 위한 규제 개선 방안을 건의한다는 계획이다. 현 제도로는 정부가 요구하는 기업 투자에 적극 뛰어들기 어렵기 때문이다. 금융당국은 업계 요구를 받아들여 위험가중자산(RWA) 가중치 조정 등의 제도 개편을 고심 중이다.박재원 기자 wonderful@hankyung.com남산에서 바라본 서울 시내 스케치.2024.05.31 최혁 기자지난 2년 동안 국내 시가총액 상위 100대 기업의 주주환원 규모가 35% 이상 증가한 것으로 나타났다.특히 KT&G는 시가총액 대비 주주환원 비율에서 1위를 기록했다.6일 기업데이터연구소 CEO스코어에 따르면 2022년 33조7240억 원이던 주주환원 총액은 2024년 45조5784억 원으로 11조8544억 원 35.2% 증가했다.같은 기간 조사 대상 기업들의 시가총액도 1405조4819억 원에서 1664조9773억 원으로 증가하며 시총 대비 환원율은 2.4%에서 2.7%로 소폭 상승했다.\r\n                    \n\n\nCEO스코어 제공주주환원 항목 중 가장 큰 비중을 차지하는 배당금은 2022년 31조8891억 원에서 지난해 37조3201억 원으로 17.0% 증가했다.하지만 전체 주주환원에서 배당이 차지하는 비중은 94.6%에서 81.9%로 낮아졌다.이는 주식소각의 증가에 따른 변화로 같은 기간 주식소각 총액은 1조8349억 원에서 8조2583억 원으로 무려 350.1% 급증했다.기업별로 보면 지난해 시가총액 대비 주주환원 비율이 가장 높은 기업은 KT&G로 10.0%에 달했다.\r\n                    \n\n\nCEO스코어 제공이어 키움증권(9.1%), 우리금융지주(9.0%), 삼성증권(8.0%), SK텔레콤(8.0%) 등이 상위권에 올랐다. 이 외에도 NH투자증권, 하나금융지주, 기업은행, 기아, 삼성물산 등이 상위 10위 안에 포함됐다.특히 금융업권 기업들이 전반적으로 높은 주주환원율을 보인 점이 눈에 띈다. 배당과 자사주 소각 등을 통해 적극적으로 주주 가치를 제고하려는 움직임이 활발하게 나타났다.반면 주주환원을 전혀 하지 않은 기업들도 다수 존재했다. 삼성바이오로직스, LG에너지솔루션, 두산에너빌리티, 한화오션, 알테오젠, 삼성중공업, 카카오페이 등 총 17개 기업은 지난해 주주환원 활동을 하지 않은 것으로 조사됐다.정유진 기자 jinjin@hankyung.com4일 금융권에 따르면 KB금융은 지난달 24일 밸류업(기업가치 제고) 전략의 일환으로 자사주 8500억원어치를 매입·소각하겠다고 발표했다. 그러면서 올해 배당가능이익 한도 때문에 1900억원어치는 내년에 취득해 없애겠다는 계획을 내놨다. 배당가능이익은 전년도 이익잉여금 중 배당과 자사주 매입에 쓰이지 않고 남은 금액을 말한다. 현재 상법에서는 배당가능이익을 초과하지 않는 선에서 자사주를 매입·소각하도록 돼 있다. 국내 은행계 금융지주가 배당가능이익이 부족해 자사주 매입을 다음해로 미룬 것은 지난해 JB금융(310억원)에 이어 이번이 두 번째다.KB금융은 지난해 10월 발표한 밸류업 계획에 따라 올해 보통주자본비율(CET1) 13%를 초과하는 자본은 모두 주주환원에 쓰기로 했다. 그런데 CET1(6월 말 13.74%)이 예상 이상으로 오르면서 준비된 재원만으로는 약속한 규모로 주주환원을 하기 어려운 상황이 발생했다. 나상록 KB금융 최고재무책임자(CFO)는 “은행과 증권 등 계열사 중간배당 등을 통해 배당가능이익을 늘리는 방안을 검토하고 있다”며 “1900억원어치 자사주 매입이 해를 넘기더라도 이 내용과 별도로 내년 주주환원 규모를 산정할 것”이라고 말했다.자사주 소각 때문에 주요 주주 지분율이 상승해 법에서 허용하는 한도를 넘길 수 있다는 문제도 여전하다. 삼양사는 6월 30일 JB금융 주식 12만5000주를 처분해 지분율을 14.37%에서 14.30%로 낮췄다. JB금융의 자사주 매입·소각으로 지분율이 금융지주회사법상 한도인 10%(지방금융지주는 15%)를 넘기는 것을 방지하기 위해 내린 결정이다. OK저축은행도 같은 이유로 지난달 8일 계열사인 OK캐피탈에 iM금융 주식을 매각해 지분율을 9.7%에서 7.92%로 떨어뜨렸다.정부가 혁신기업과 중소·벤처기업, 소상공인에게 더 많은 자금을 공급하라고 요구해 금융지주의 주주환원 계획에 차질이 생길 가능성도 있다. 금융권 관계자는 “비교적 위험가중치가 높은 기업 대출을 대거 늘리면 주주환원 기준이 되는 CET1 관리가 어려워질 수 있다”고 말했다.김진성 기자 jskim1028@hankyung.com<앵커> 오늘 금융지주 주가가 오전에 잠시 조정받는 듯했는데 KB금융 제외하곤 낙폭을 줄여가는 모습입니다. 앞서 최민정 기자 언급한 자사주 의무 소각 관련해 금융지주들에는 어떤 영향이 있을지 경제부 유주안 기자와 이야기 나눠봅니다. 금융지주들은 자사주 매입과 소각에 꽤 적극적인데, 보유중인 자사주의 비중은 어떻습니까?<기자>4대 금융지주 자사주 보유 현황(KB 4.54%, 신한 2.09%, 하나 3.77%, 우리 1.16%)은, 보시다시피 비중이 크다고 보이진 않습니다.자사주 소각 의무화 추진에 따른 수혜주로 꼽히는 미래에셋(22.98) 대신(25.12) 신영(52.58%) 등에 비하면 매우 작은 수준이고요, 일반지주사들(티와이홀딩스 29.79%, SK 24.8%, 롯데지주 27.37% 등)에 비해서도 비중이 낮습니다.과거 역사를 살펴보면 금융주에 있어서는 자사주 ‘지배의 도구’보다는 인수합병 때 주식교환을 하기 위해, 전략적 투자자와 주식을 스왑하는 차원에서 일정 부분 보유해왔던 것을 알 수 있고요, 최근 들어서는 매입하면 바로 소각해서 주식의 가치를 올리는, 주주환원의 수단으로 자사주를 활용해 왔습니다.따라서, 자사주 소각 의무화에 따른 강제성 측면에서 금융지주에 미치는 단기적 직접적 영향은 크지 않겠습니다. 중장기적으로 볼 때 금융지주의 주주환원에 보다 힘이 실릴 것이란 기대감으로 이어질 수 있는데요,정책이 추구하는 목표를 이미 금융지주사들이 실행해 옮기고 있는 것이고, 향후 상장사들 사이에 자사주 매입소각이 보편화되면 재무적 여력과, 주주환원에 대한 강한 의지를 가진 금융사들이 더 적극적인 주주환원을 펼칠 수 있는 배경이 될 수 있을 것입니다.또한, 정부가 함께 추진중인 배당소득 분리과세 정책은 배당성향이 높고, 분기배당에 적극적인 금융주에게 특히 긍정적인 정책으로 받아들여지고 있습니다.<앵커> 어제 삼성전자 실적으로 인해 다소 가라앉은 분위기로 어닝시즌 개막되었는데요. 금융주 실적은 어떨 걸로 전망됩니까?<기자> 4대 지주만 놓고 볼 때, 당초 2분기는 좀 쉬어갈 것으로 예상이 되었습니다. 이는 2024년 2분기에 실적이 워낙 좋았던 것에 대한 기저효과와 더불어, 시중금리가 내려가면서 이자이익이 축소될 것으로 예상되었기 때문입니다.에프앤가이드 취합 컨센서스로 보면 KB금융의 2분기 당기순이익이 전년동기대비 약 5% 감소한 1조 6300억원, 우리금융지주 약 9% 감소한 8700억원으로 전망이이미지 크게보기\n\n\n\n                15일 금융정보업체 에프앤가이드에 따르면 4대 금융지주의 지난 2분기 순이익 추정치는 총 5조80억원이다. 작년 2분기(5조1241억원)와 비교해 1161억원(2.3%) 줄어든 규모다.4대 금융지주의 분기 단위 순이익이 전년 동기 대비 감소한 것은 작년 1분기(-6910억원) 이후 처음이다. 작년 1분기엔 4대 시중은행(국민·신한·하나·우리)이 홍콩 H지수 ELS 배상을 위해 총 1조3174억원을 일회성 비용인 충당부채로 적립한 영향으로 금융지주 실적이 줄었다. 홍콩 ELS 배상이라는 일회성 비용을 제외하면 4대 금융지주의 합산 순이익이 전년 동기 대비 감소한 것은 2023년 4분기(-3458억원) 이후 1년6개월 만에 처음이다.2분기엔 별다른 일회성 비용이 발생하지 않았는데도 실적이 줄어든 것으로 추정되는 것은 이자수익 감소세가 본격화했기 때문이다. 에프앤가이드에 따르면 KB금융의 이자수익은 작년 2분기 7조6116억원에서 올 2분기 7조5600억원으로 516억원(0.7%) 감소한 것으로 추정된다. 같은 기간 하나금융의 이자수익도 6조36억원에서 5조7800억원으로 4.7% 줄어들고, 우리금융은 5조4184억원에서 5조3620억원으로 1% 축소됐을 것으로 추산된다. 신한금융의 이자수익 추정치는 집계되지 않았다.업계에서는 올해 2분기를 시작으로 금융지주의 분기별 실적이 본격적인 감소세에 접어들 것이란 전망이 많다. 기준금리 인하로 핵심 수익성 지표인 순이자마진(NIM)이 하락하는 가운데 정부가 강력한 가계대출 억제 정책을 펼치고 있어 대출을 늘리기 어렵기 때문이다. 정부는 지난달 27일 발표한 ‘가계부채 관리 방안’(6·27 부동산 대책)을 통해 올 하반기부터 가계대출 증가량 목표치를 당초 계획 대비 50% 수준으로 줄이겠다고 밝혔다.한 금융지주 여신 담당 임원은 “금융지주들이 모두 공격적인 기업가치 제고(밸류업) 계획을 내놓은 가운데 경기 침체가 심화하고 있어 밸류업에 불리한 기업대출을 확대하기가 쉽지 않은 노릇”이라며 “양적 성장보다 내실을 다지는 방향으로 나아갈 것”이라고 말했다.4대 금융지주는 오는 24일 KB금융이, 25일 신한·하나·우리금융이 2분기 실적을 발표한다. 상반기 기준으로는 작년 실적을 끌어내린 홍콩 H지수 ELS 배상과 관련한 기저효과로 올해 실적이 전년 대비 개선됐을 것으로 추정된다.정의진 기자 justjin@hankyung.com◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.우리금융지주 등을 편입하고 있다. 강대권 라이프자산운용 대표는 “주주환원과 배당 확대는 앞으로 수년간 국내 증시의 주요 테마가 될 것”이라며 “액티브 ETF는 펀드매니저가 종목을 관리하고 장기 수익을 목표로 하기 때문에 퇴직연금에 편입하기 좋은 상품”이라고 설명했다.태광산업에 대한 행동주의로 주목받은 트러스톤자산운용의 대표 상품은 ‘TRUSTON 주주가치액티브’(올해 수익률 40.97%)다. 태광산업을 비롯해 NH투자증권, 현대엘리베이터, KB금융, 삼성카드, 키움증권 등에 투자한다. ‘HANARO 주주가치성장코리아액티브’(33.59%)도 같은 테마로 시장에서 주목하는 ETF 가운데 하나다.헤지펀드의 강자 타임폴리오자산운용은 미국 증시에 투자하는 액티브 ETF에서 경쟁력을 과시하고 있다. AI 관련주에 집중 투자하는 ‘TIMEFOLIO 글로벌AI인공지능액티브’ ‘TIMEFOLIO 미국나스닥100액티브’ 등이 대표적이다.최만수 기자 bebop@hankyung.comBBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.com[커버스토리] 2025 밸류업 CEO 50\n\n\n\n\n\n\n\n\n\n\n\n<2025 밸류업 CEO 50 - 금융>11위 임종룡 우리금융지주업종명 금융지주취임일 주가(원) 11,010     최근 주가(원) 21,350     취임일 2023년 3월 24일주가수익률 93.9%배당수익률 21.8%총주주수익률 115.7%12위 빈대인 BNK금융지주업종명 금융지주취임일 주가(원) 6,250     최근 주가(원) 11,790     취임일 2023년 3월 17일주가수익률 88.6%배당수익률 20.5%총주주수익률 109.1%13위 양종희 KB금융업종명 금융지주취임일 주가(원) 54,100     최근 주가(원) 106,500     취임일 2023년 11월 21일주가수익률 96.9%배당수익률 10.4%총주주수익률 107.2%14위 정종표 DB손해보험업종명 보험취임일 주가(원) 65,300     최근 주가(원) 120,200     취임일 2023년 1월 1일주가수익률 84.1%배당수익률 18.5%총주주수익률 102.6%15위 김성태 기업은행업종명 은행취임일 주가(원) 9,560     최근 주가(원) 17,290     취임일 2023년 1월 3일주가수익률 80.9%배당수익률 21.4%총주주수익률 102.3% 16위 함영주 하나금융지주업종명 금융지주취임일 주가(원) 49,350     최근 주가(원) 80,000     취임일 2022년 3월 25일주가수익률 62.1%배당수익률 22.8%총주주수익률 84.9%17위 진옥동 신한지주업종명 금융지주취임일 주가(원) 35,750     최근 주가(원) 59,300 취임일 2023년 3월 23일주가수익률 65.9%배당수익률 13.5%총주주수익률 79.4%18위 박종문 삼성증권업종명 증권취임일 주가(원) 41,550     최근 주가(원) 67,700     취임일 2024년 3월 21일주가수익률 62.9%배당수익률 8.4%총주주수익률 71.4%19위 윤병운 NH투자증권업종명 증권취임일 주가(원) 12,350     최근 주가(원) 19,170     취임일 2024년 3월 27일주가수익률 55.2%배당수익률 7.7%총주주수익률 62.9%20위 박봉권 교보증권업종명 증권취임일 주가(원) 6,770     최근 주가(원) 8,450     취임일 2020년 2월 4일주가수익률 24.8%배당수익률 28.1%총주주수익률 52.9%KB금융이 최대 8천억원, 신한과 하나가 각 3~4천억원, 우리 1500억원, 도합 1조6천원에 달하는 자사주 소각 파티를 벌일 것으로 기대하고 있습니다.배당과 자사주 매입소각 합친 총주주환원율이 올해 50% 넘어가는 케이스도 탄생할지 관전포인트입니다.<앵커> 그간 주가가 많이도 올랐는데, 향후 추가 상승을 기대해볼 수 있나요?<기자> 2분기 이후 4대 금융지주 주가는 일제히 40% 이상 올랐습니다.워낙 국내 증시 저평가 되어있다보니 주식시장에서 장부가 만큼만이라도 평가를 받으라는 의미에서 PBR 1배가 목표치로 설정되어 있는데요, 주가가 45% 올랐어도 KB금융의 PBR이 0.7배 수준입니다. 나머지 3곳은 장부가 절반의 가치밖에 인정을 못 받고 있습니다.따라서 오늘 주가 하락에 대해서는 금융권 안팎과, 기업분석하는 증권업계 쪽에선 최근 급등에 따른 단기조정의 성격으로 파악을 하고 있습니다.마지막으로 4곳 중 어디가 가장 좋을 것이냐도 궁금하실텐데. KB금융이 실적과 주주환원 측면에서 압도적일 것으로 예상되고 주가 측면에서도 1위 프리미엄이 지속될 것이란 전망이 있는 동시에 또다른 측면에선 키맞추기가 이뤄질 것으로 예상하기도 합니다.  KB가 0.7배 수준까지 올랐으니, 2~4위권이 부지런히 키맞추기를 위해 올라올 것으로 기대하는 시각도 있습니다.<네 잘 들었습니다>유주안기자 jayou@wowtv.co.kr◇하이닉스·KB금융…실적 ‘슈퍼위크’22일 금융정보업체 에프앤가이드에 따르면 증권사 세 곳 이상이 내놓은 상장사 100곳의 올해 2분기 영업이익 추정치는 총 39조5944억원인 것으로 집계됐다. 한 달 전 같은 곳을 대상으로 추정한 금액(42조3291억원)보다 6.4% 감소했다. 올 초(44조4976억원)와 비교해선 11%가량 낮아진 수치다. 주요 종목의 2분기 실적 발표가 줄줄이 예고된 가운데 종목별 ‘옥석 가리기’가 중요해진 배경이다.새로운 반도체 대장주 SK하이닉스는 24일 2분기 실적을 발표한다. SK하이닉스의 2분기 실적 컨센서스(증권사 추정치 평균)는 매출 20조6109억원, 영업이익 9조199억원이다. 전년 동기 대비 매출과 영업이익이 각각 25.5%, 64.9% 급증했을 것으로 관측됐다. 3개월 전 영업이익 추정치(7조8988억원)와 비교해 시장의 눈높이가 대폭 높아졌다.전문가들은 SK하이닉스가 무난히 사상 첫 분기 영업이익 9조원 시대를 열 것으로 보고 있다. 호실적 기대를 높이는 일등 공신은 고대역폭메모리(HBM)다. 손인준 흥국증권 연구원은 “메타 등 전방업체의 경쟁 심화, 엔비디아의 중국 수출 허가 등 계속해서 확인되는 인공지능(AI) 수요 강세 신호를 감안하면 HBM 경쟁 심화 및 가격 하락 우려는 지양할 필요가 있다”고 말했다.새 정부 출범 후 주도주로 자리매김한 금융주는 24일 KB금융을 시작으로 25일 신한·하나·우리금융 등이 잇달아 실적을 내놓는다. 4대 금융지주의 2분기 순이익은 총 5조1118억원으로 전년 동기(5조1687억원)보다 1.1% 감소했을 것으로 추정됐다. 자사주 매입·소각 등 주주환원 규모가 시장 기대를 충족할지도 관심사다. ◇탄력받는 조선·방산·원전올해 국내 증시의 상승장을 이끈 조선·방산·원전주는 2분기 실적 발표를 계기로 한층 탄력받을 것이란 전망이 많다. 한화오션(29일 실적 발표)의 2분기 영업이익 추정치는 한 달 전보다 6.8% 늘어났다. 3개월 전보다는 64.1% 급증했다.한화에어로스페이스, 현대로템, 한국항공우주산업, LIG넥스원 등 대형 방산업체 4곳의 2분기 영업이익 추정치는 1조1049억원으로, 역대 처음 분기 영업이익 1조원 시대를 열 전망이다.한 달 전보다 2분기 영업이익 추정치가 가장 많이 늘어난 방산주는 풍산(10.9%)이다. 한화시스템(3.4%) 한화에어로스페이스(2.4%) 등이 뒤를 이었다.원전 대장주 두산에너빌리티는 25일 2분기👀주목할 만한 보고서 에코프로비엠-소형/ESS 호조와 일회성 이익으로 컨센서스 상회📈목표주가 : 13만원→15만원(상향) / 현재주가 : 12만4500원   투자의견 : 매수(유지) /  KB증권[체크 포인트]- 2분기 실적 매출액 7,797억원 (-4% YoY), 영업이익 490억원(+1,159% YoY, 영업이익률 6.3%)으로 컨센서스 상회.- 3분기 실적은 매출액 7,726억원 (+48% YoY), 영업이익 371억원(흑자전환, 영업이익률 4.8%)으로 기대. IRA 종료로 인해 북미 EV향 판매는 소폭 감소할 것으로 예상. 다만 소형전지/ESS향은 수요 강세 흐름이 지속될 것으로 전망. 2분기에 이어 인도네시아 투자활동 이익과 재고평가손실 충당금 환입이 예상되어 수익성도 양호할 것.- 전방 고객의 EV/소형전지/ESS향 판매 증가 등을 고려해 2026E~2030E 평균 영업이익률 기존 4.8%에서 5.4%로 상향 조정. 우리금융지주-가장 높은 배당수익률📈목표주가 : 2만2000원→3만1000원(상향) / 현재주가 : 2만4900원   투자의견 : 매수(유지) /  유안타증권[체크 포인트]- 2분기 지배주주순이익은 9,346억원으로 컨센서스를 12.6% 상회. 컨센서스를 상회한 이유는 벤처캐피탈 자회사에서 투자한 달바글로벌 평가이익 470억원 및 지점매각익 100억원이 영업외손익에 반영됐기 때문.- 2025년 자사주 1,500억원을 매입을 진행했으며 추가적인 자사주 매입은 없을 것으로 판단.- 우리금융지주는 자본잉여금을 이익잉여금으로 이입해 비과세 배당 실시 발표. 3조원 수준으로 3~4년간의 주주환원 재원으로 활용될 전망. 해당 비과세 배당은 2025년 결산 배당부터 적용될 전망. 결산배당을 비과세 시 배당수익률은 5.7%로 커버리지 은행 중 가장 높은 수준.- 올해 CET-1 비율 12.5% 초과 달성으로 내년부터는 35%가 넘는 총주주환원율이 기대. 2) 비과세 배당을 통한 높은 배당수익률은 경쟁사와 차별화된 투자 포인트로 작용할 것. 3) 증권 및 보험 자회사의 이익기여도 확대가 기대. BNK금융지주-대손비용 우려는 완화되고 있다📈목표주가 : 1만4500원→1만8000원(상향) / 현재주가 : 1만4410원   투자의견 : 매수(유지) /  유안타증권[체크 포인트]- 2분기 지배주주순이익은 3,092억원으로 컨센서스를 26.5% 실적을 기록. 디지털타워 매각으로 일회성 이익 약 540억원이 반영◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.6일 투자은행(IB)업계에 따르면 하나금융은 이달 29일 2700억원 규모의 신종자본증권(AA-)을 발행을 앞두고 20일 수요예측에 나설 예정이다. 기관 투자가의 높은 수요를 예상해 최대 4000억원까지 한도를 열어뒀다. 금리는 연 3%대 초반을 예상하고 있다.기업은행도 3000억원 규모의 후순위채권(AA+) 발행에 대한 이사회 결의를 마친 뒤 곧 수요예측에 들어갈 예정이다.신한지주, 우리금융지주, BNK금융지주 등도 지난달 이사회 결의를 열고 자본성증권 발행을 결정했다. 신한지주는 신종자본증권(AA-) 2700억원을 발행해 운영자금으로 400억원, 채무상환자금으로 2300억원을 사용할 예정이다. 우리금융지주는 2700억원 규모의 신종자본증권(AA-)을 발행해 운영자금에 700억원, 채무상환에 2000억원을 투입한다. BNK금융지주는 1050억원 규모의 신종자본증권(AA-)을 발행해 모두 운영자금에 사용한다.이들 금융지주들은 증권사와 보험사, 캐피탈사 등도 거느리고 있다. 증권사의 자기자본을 확대하고, 보험사의 지급여력 개선 등에도 해당 자금이 사용될 예정이다. 신용도가 높은 금융지주사가 대량으로 자금을 조달한 뒤 각 계열사에 투입해 재무건전성을 높이는 역할이다.보험사들도 금융당국의 새로운 자본규제를 앞두고 자금 조달에 나서고 있다. DB손해보험은 다음 달 1일 5000억원 규모의 기본자본 신종자본증권(AA) 발행을 계획하고 있다. 희망 금리는 최대 3.8%로 책정했다.보험사의 자본은 손실흡수성에 따라 기본자본(Tier1, 자본금·이익잉여금 등)과 보완자본(Tier2, 후순위채권 등)으로 나뉜다. 금감원은 보험사의 자본 건전성을 강화하기 위해 기본자본 지급여력(K-ICS·킥스)비율을 새 자본규제 지표로 도입할 방침이다. ◇ 높은 수익률에 국고채 대비 선호시중은행들은 지난해 자본성증권 약 4조7700억원을 발행했다. 지난 5년 동안 발행한 자본성증권은 총 21조5850억원, 연평균 4조3000억원 규모다. 보험사도 지난해 약 8조3250억원의 자본성증권을 발행하며 자본을 확충했다.금융지주사의 자본성증권 발행이 활발해지면서 스프레드는 축소되는 추세다. 지난 6월 발행된 우리은행의 10년 만기 후순위채의 스프레드는 0.44%포인트로 역대 최저 수준을 기록했다.스프레드는 회사채 수익률과 동일 만기 국고채 수익률 간 금리차를 뜻한다. 이는 해당 기업의 신용도가 높다는 뜻으로, 투자자[한경ESG] 지속가능경영 보고서 CEO 말말말 - 4대 금융지주 \n\n\n\n\n\n“KB금융그룹은 ‘세상을 바꾸는 금융’이라는 사명을 바탕으로 금융의 본질을 넘어 더 멀리 보고 더 깊이 고민하겠습니다.”양종희 KB금융그룹 회장 세상을 바꾸는 금융[1] KB금융그룹은 고객에게는 신뢰할 수 있는 금융, 주주에게는 장기적 성장 가능성을 제시하는 기업, 지역사회에는 함께 성장하는 든든한 동반자가 되는 것을 진정한 가치로 삼아 최선을 다하고 있습니다. [2] 금융은 단순한 자금 중개를 넘어 개인의 삶과 기업의 미래, 나아가 사회 전체의 지속가능성을 연결하는 중요한 기반입니다. 금융의 본질적 역할을 되새기며, 다음 세대에게 더 나은 환경과 기회를 전하는 책임을 다하고자 합니다.[3] KB금융그룹은 기후 위기, 저출생, 지역 소멸, 일자리 문제 등 우리 삶을 위협하는 문제를 외면하지 않고, 금융 본업의 역량을 발휘해 사회와 함께하는 따뜻한 파트너십을 실천해왔습니다. 또 돌봄과 소상공인 지원 등 의미 있는 사회적가치를 창출하고, 이웃과 사회와의 관계를 균형 있게 헤아리며 공존을 추구하고자 했습니다.[4] 앞으로도 KB금융그룹은 고객의 신뢰와 사회의 기대를 가장 소중한 자산으로 여기며, 국민 모두의 성장이 KB의 성장으로 이어지는 지속가능한 길을 함께 만들어가겠습니다.◆ 최근 애널리스트 분석의견- 장기 보유 매력 유효 - 미래에셋증권, 매수07월 14일 미래에셋증권의 정태준 애널리스트는 우리금융지주에 대해 "투자의견 매수로 상향, 목표주가 29,000원으로 상향. 주주환원 매력 배가 예상. 2분기 지배주주순이익은 컨센서스에 부합하는 8,477억원을 예상"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 08일 거래소에서 이수페타시스, 삼성중공업, SK하이닉스 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 이수페타시스, 삼성중공업, SK하이닉스, 하나금융지주, 삼양식품, HD현대, KB금융, 신한지주, 동양철관, 현대차등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.이수페타시스, 삼성중공업, SK하이닉스 등은 전일 대비 주가가 상승했고, POSCO홀딩스, LG화학 등은 주가가 하락했다.[07월08일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요결론부터 말하자면 주도주가 바뀌었다.2021년 시장을 지배했던 ‘BBIG’(배터리·바이오·인터넷·게임)는 힘을 잃었다. 2025년의 시장은 ‘지금조방원’(지주회사·금융·조선·방산·원자력)과 ‘ABCDE’(AI·바이오·문화·방산·에너지)의 무대다.코스피 3000 시대를 이끌었던 2021년과 3200선으로 끌어올린 2025년의 주도주를 비교 분석했다. 2021년은 팬데믹 저점이었던 코스피 1457.64(2020년 3월 19일)부터 사상 최고치인 3305.21(2021년 7월 6일)을 기록할 때까지의 구간이다. 상승률은 126.75%. 전례 없는 유동성과 기업 펀더멘털 개선이 맞물린 결과였다. 박스권에 갇혀 있던 국내 증시가 근 18년 만에 구조적 상향 돌파를 이룬 시기로 평가된다.반면 2025년의 상승은 정책 주도형 랠리다. 새 정부의 증시 부양 기조와 거버넌스 개혁 기대가 주가를 끌어올리고 있다.두 시기를 대표하는 코스피 시가총액 상위 50개 종목의 주가 상승률을 비교 분석해 ‘과거의 주도주’와 ‘현재의 주도주’가 어떻게 달라졌는지 분석한 결과, 2025년의 장세는 지주회사, 금융, 조선, 방산, 원자력 등 이른바 ‘지금조방원’이 이끌었다.가장 높은 상승률을 기록한 종목은 현대로템이다. 올해 1월 초 4만9700원이던 주가는 7월 말 19만9800원까지 오르며 302.01% 급등했다. 폴란드와 체결한 K2 전차 등 방산 수출 기대와 글로벌 지정학적 리스크 확대가 주가를 밀어올렸다.두산에너빌리티(289.74%)는 지난 정부의 원전 정책 정상화로 반등에 성공한 이후 최근 AI 산업 확산에 따른 전력 수요 증가로 다시 주목받았다. 한화에어로스페이스(185.84%)

In [339]:
len(chunk_total)

37824

In [340]:
result_df_chunk = summarize_top_articles_2(chunk_total,ticker=test_ticker,max_iters=5)

summart : ✅ 주요 요약
- 4대 금융지주, 2분기 순이익 전년 대비 감소
  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 감소했으며, 이는 이자수익 감소와 가계대출 억제 정책으로 인한 결과로 분석됨.

- 금융지주, 주주환원 정책 강화
  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.

- 정부의 부동산 대출 규제와 증시 친화 정책
  정부의 부동산 대출 규제에도 불구하고 금융지주들의 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.

🔑 키워드
- 4대 금융지주
- 순이익 감소
- 이자수익
- 가계대출 억제
- 주주환원 정책
- 자사주 매입
- 부동산 대출 규제
- 증시 친화 정책
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약 내용이 원문 기사와 일부 일치하지 않으며, 특히 금융지주의 순이익 증가에 대한 부분이 잘못 전달됨] </reason>
- 포괄성: 부족함 <reason> [기사의 중요한 정보 중 일부가 누락되었으며, 특히 정부의 정책 변화와 이에 따른 금융지주의 대응 전략이 충분히 다루어지지 않음] </reason>
- 간결성: 좋음 <reason> [요약은 간결하게 작성되어 있으며, 불필요한 정보가 포함되지 않음] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있음] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용이 아닌, 전체 금융지주에 대한 내용임에도 불구하고 일관성이 부족함] </reason>

피드백:
1. 정확성을 높이기 위해 원문 기사에서 언급된 순이익 증가와 감소에 대한 정보를 정확히 반영해야 합니다. 특히, 금융지주의 순이익이 전년 대비 증가했다는 부분을 명확히 해야 합니다.
2. 포괄성을 개선하기 위해 정부의 부동산 대출 규제와 증시 친화 정책에 대한 자세한 설명을 추가해야 합니다. 또한, 금융지주들의 새로운 수익원 확보 전략에 대한 정보도 포함되어야 합니다.
3. 일관성을 유지하기 위해 요약의 초점을 금융지주 전체에 맞추고, 특정 종목에 대한 정보는 배제해야 합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n- 4대 금융지주, 2분기 순이익 전년 대비 증가\n  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 증가했으며, 이는 비이자수익의 증가와 환율 안정에 따른 외화환산이익 덕분으로 분석됨.\n\n- 금융지주, 주주환원 정책 강화\n  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.\n\n- 정부의 부동산 대출 규제와 증시 친화 정책\n  정부의 부동산 대출 규제에도 불구하고 금융지주들의 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.\n\n🔑 키워드\n- 4대 금융지주\n- 순이익 증가\n- 비이자수익\n- 환율 안정\n- 주주환원 정책\n- 자사주 매입\n- 부동산 대출 규제\n- 증시 친화 정책'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 4대 금융지주의 순이익이 전년 대비 증가했다고 했으나, 원문에서는 순이익이 감소했다고 언급하고 있습니다. 이는 요약의 핵심 내용이 원문과 일치하지 않음을 의미합니다.] </reason>
- 포괄성: 부족함 <reason> [요약에서 정부의 부동산 대출 규제와 증시 친화 정책에 대한 언급은 있지만, 원문에서 다루는 다양한 금융 관련 이슈와 세부 사항들이 충분히 포함되지 않았습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 핵심 사항을 간결하게 전달하고 있습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [요약에서 특정 종목에 대한 내용만 존재하지 않고, 다양한 주제를 다루고 있어 일관성이 부족합니다.] </reason>

피드백:
- 정확성을 높이기 위해 원문 기사에서 언급된 순이익 감소와 관련된 내용을 정확히 반영해야 합니다.
- 포괄성을 개선하기 위해 원문에서 다루는 다양한 금융 이슈, 예를 들어 주주환원 정책의 구체적인 내용이나 금융지주들의 실적 전망에 대한 세부 사항을 추가하는 것이 좋습니다.
- 일관성을 유지하기 위해 요약의 초점을 명확히 하고, 특정 주제나 종목에 대한 내용을 중심으로 구성하는 것이 필요합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- 4대 금융지주, 2분기 순이익 감소\n  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 감소했으며, 이는 이자수익 감소와 경기 침체로 인한 대출 자산 확대의 어려움 때문으로 분석됨.\n\n- 금융지주, 주주환원 정책 강화\n  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.\n\n- 정부의 부동산 대출 규제와 증시 친화 정책\n  정부의 부동산 대출 규제에도 불구하고 금융지주들의 연간 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.\n\n🔑 키워드\n- 4대 금융지주\n- 순이익 감소\n- 이자수익 감소\n- 주주환원 정책\n- 자사주 매입\n- 부동산 대출 규제\n- 증시 친화 정책'
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약이 원문 기사와 완전히 일치하지 않음. 특히, 4대 금융지주의 순이익이 감소한 이유와 관련된 구체적인 내용이 부족함.] </reason>
- 포괄성: 부족함 <reason> [기사의 중요한 정보 중 일부가 누락되었음. 예를 들어, 금융지주의 비이자이익 증가와 관련된 내용이 포함되지 않음.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성됨.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있음.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목에 대한 내용만 존재하는 것이 아니라 다양한 정보를 포함하고 있음.] </reason>

피드백:
1. **정확성**: 원문 기사에서 4대 금융지주의 순이익 감소 이유에 대한 구체적인 내용을 더 명확하게 반영해야 합니다. 예를 들어, 이자수익 감소 외에도 비이자이익 증가와 같은 다른 요인들도 포함되어야 합니다.

2. **포괄성**: 금융지주의 비이자이익 증가와 정부의 정책 변화가 금융지주 실적에 미치는 영향 등 중요한 정보가 누락되었습니다. 이러한 정보를 포함하여 요약의 포괄성을 높일 필요가 있습니다.

3. **일관성**: 요약이 특정 종목에 대한 내용만 다루는 것이 아니라, 다양한 측면에서 정보를 제공해야 합니다. 이를 위해 관련 정보를 더 체계적으로 정리하여 일관성을 높여야 합니다.
[should_stop] next_step = no

KeyboardInterrupt:

In [270]:
print(result_df_chunk.summary.values[0])

✅ 주요 요약

- **SK하이닉스, 2분기 사상 최대 실적 기록**
  SK하이닉스는 2분기 매출 22조2320억원, 영업이익 9조2129억원을 기록하며 사상 최대 실적을 달성했다. 이는 AI 메모리 수요 증가와 D램 및 낸드플래시 출하량 증가에 기인한다.

- **HBM 시장에서의 경쟁 심화 우려**
  SK하이닉스는 HBM 시장에서의 독점적 지위가 경쟁 심화로 인해 위협받을 수 있다는 우려가 제기되고 있다. 삼성전자와 마이크론의 시장 진입이 예상되며, 가격 하락 가능성이 논의되고 있다.

- **SK하이닉스의 HBM 수요 성장 확신**
  SK하이닉스는 HBM 수요가 지속적으로 증가할 것이라고 확신하며, AI 시장에서의 핵심 제품으로서의 중요성을 강조하고 있다. 이에 따라 HBM 생산을 위한 투자를 확대할 계획이다.

- **주가 변동 및 외부 기관의 평가**
  SK하이닉스의 실적 발표 이후 주가는 일시적으로 상승했으나, 외부 기관의 평가에 따라 변동성을 보였다. 골드만삭스는 HBM 시장의 경쟁 심화로 인한 가격 하락 가능성을 지적하며 투자의견을 하향 조정했다. 반면, 다른 기관들은 SK하이닉스의 기술력과 시장 지배력을 긍정적으로 평가하며, 장기적인 성장 가능성을 강조했다.

🔑 키워드
- SK하이닉스
- 2분기 실적
- HBM 시장
- AI 메모리
- 경쟁 심화
- 가격 하락
- 투자 확대
- 주가 변동
- 외부 기관 평가

## 청크 토탈 시뮬레이션

In [34]:
chunk_array_lst = []

In [51]:
for ticker in Custer_Having_ticker_lst:
    print(f'{ticker} 진행=======================')
    CrossEncoder_prompt_test = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : ticker}})
    compressor = CrossEncoderReranker(model=model, top_n=20)
    compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
    )
    compressed_docs = compression_retriever.invoke(CrossEncoder_prompt_test)
    unique_lst = list(set(list(map(lambda x: x.page_content,compressed_docs))))
    print(f'chunk 개수 : {len(unique_lst)}')
    chunk_total = ''.join(unique_lst)
    chunk_array_lst.append(summarize_top_articles_2(chunk_total,ticker=ticker,max_iters=5))

우리금융지주 진행=======================

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

chunk 개수 : 7
summart : ✅ 주요 요약
- 국내 4대 금융지주, 상반기 평균 급여 1억원 돌파
  KB금융, 우리금융 등 주요 금융지주들이 사상 최대 실적을 기록하며 평균 급여가 1억원을 넘었고, 이는 제조업 대기업보다 높은 수준이다.

- 금융주 주가 하락, 정부의 압박과 세금 인상 영향
  정부의 교육세 인상 및 과징금 부과 등으로 인해 금융주 주가가 하락하고 있으며, 외국인 주주 비율이 높은 금융지주사들이 특히 영향을 받고 있다.

- 정부의 금융권 압박, 외국인 투자자 우려 증가
  이재명 정부의 금융권에 대한 압박이 강화되면서 외국인 투자자들 사이에서 우려가 커지고 있으며, 이는 금융지주사의 주가에 부정적인 영향을 미치고 있다.

키워드: 금융지주, 평균 급여, 주가 하락, 정부 압박, 교육세 인상, 외국인 투자자, 이재명 정부, 금융권 압박, 주주환원.
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약이 주요 내용을 잘 담고 있지만, 기사에서 언급된 비금융권의 급여 정보나 코스피 상장사의 실적 개선 등 추가적인 세부 사항이 누락되었습니다.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

피드백:
포괄성 측면에서, 요약은 금융지주와 관련된 주요 내용을 잘 전달하고 있지만, 기사에서 언급된 다른 중요한 정보들, 예를 들어 비금융권의 급여 정보나 코스피 상장사의 실적 개선 등의 내용도 포함하면 더 포괄적인 요약이 될 것입니다. 이러한 세부 사항을 추가하여 독자가 전체 기사의 맥락을 더 잘 이해할 수 있도록 하는 것이 좋습니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **국내 4대 금융지주, 상반기 평균 급여 1억원 돌파**  \n  KB금융과 우리금융 등 주요 금융지주들이 사상 최대 실적을 기록하며 평균 급여가 1억원을 넘었고, 이는 제조업 대기업보다 높은 수준이다.\n\n- **비금융권 급여 현황**  \n  SK하이닉스는 1억1700만원으로 비금융권에서 가장 높은 급여를 기록했으며, 네이버와 SK텔레콤은 각각 9200만원을 기록했다. 이는 메모리 반도체 업황 회복과 온라인 광고 및 AI 플랫폼 투자 성과에 기인한다.\n\n- **금융주 주가 하락, 정부의 압박과 세금 인상 영향**  \n  정부의 교육세 인상 및 과징금 부과 등으로 인해 금융주 주가가 하락하고 있으며, 외국인 주주 비율이 높은 금융지주사들이 특히 영향을 받고 있다.\n\n- **코스피 상장사 실적 개선**  \n  코스피 상장사들은 반도체와 금융업 호조로 영업이익 110조원을 기록하며 전년 대비 8% 증가했다. 그러나 코스닥 상장사들은 순이익이 감소하며 대조적인 흐름을 보였다.\n\n- **정부의 금융권 압박, 외국인 투자자 우려 증가**  \n  이재명 정부의 금융권에 대한 압박이 강화되면서 외국인 투자자들 사이에서 우려가 커지고 있으며, 이는 금융지주사의 주가에 부정적인 영향을 미치고 있다.\n\n**키워드:** 금융지주, 평균 급여, 비금융권 급여, 주가 하락, 정부 압박, 교육세 인상, 외국인 투자자, 코스피 실적 개선, 이재명 정부, 금융권 압박, 주주환원.'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음
  <reason> 요약 내용이 원문 기사와 일치하며, 주요 정보가 정확하게 전달되었습니다. </reason>

- 포괄성: 좋음
  <reason> 기사에서 다룬 주요 정보와 핵심 내용이 모두 포함되어 있습니다. </reason>

- 간결성: 좋음
  <reason> 불필요한 표현 없이 간결하게 요약되었습니다. </reason>

- 문장구성: 좋음
  <reason> 문장이 자연스럽고 명확하게 구성되어 있습니다. </reason>

- 일관성: 좋음
  <reason> 특정 종목에 대한 내용만 존재하며, 일관성이 유지되고 있습니다. </reason>

피드백:
전체적으로 요약이 잘 이루어졌으며, 기사에서 다룬 주요 사항들이 명확하고 간결하게 전달되었습니다. 모든 평가 기준에서 좋은 평가를 받을 만큼 요약이 잘 작성되었습니다. 추가적인 개선이 필요하지 않습니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])
삼성화재 진행=======================

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

KeyboardInterrupt:

In [36]:
chunk_df = pd.concat(chunk_array_lst)

In [38]:
chunk_df.to_csv('chunk_df.csv',encoding='utf-8-sig')

In [39]:
chunk_df

,ticker,date,summary,feedback
0,우리금융지주,2025-07-30,"✅ 주요 요약\n\n- **국내 4대 금융지주, 평균 급여 사상 첫 반기 1억 원 ...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 일치하며, 주요 ..."
0,삼성화재,2025-07-30,"✅ 주요 요약\n\n- **삼성화재, AI 의료심사 도입으로 암 진단 심사 효율성 ...",**평가:**\n\n- 정확성: 좋음\n <reason> 요약 내용이 원문 기사와...
0,삼성생명,2025-07-30,"✅ 주요 요약\n\n- **삼성그룹, 하반기 대규모 공개채용 실시** \n 삼성...","- 정확성: 좋음 <reason> [요약 내용이 원문 기사와 일치하며, 삼성그룹의 ..."
0,카카오뱅크,2025-07-30,"✅ **주요 요약**\n\n- **카카오 창업자 김범수, 법적 문제 직면**\n ...","- 정확성: 좋음 <reason> 요약 내용이 원문 기사와 일치하며, 주요 사건과 ..."
0,메리츠금융지주,2025-07-30,"✅ 주요 요약\n\n- **현대해상, 실적 부진에도 주가 상승**\n - 현대해상...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 일치하며, 현대해..."
0,현대모비스,2025-07-30,"✅ 주요 요약\n\n- **현대모비스, 차량용 반도체 연구개발 프로세스 ISO 26...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 일치하며, 현대모..."
0,현대오토에버,2025-07-30,"✅ 주요 요약\n- 기관 투자자, 다양한 종목 순매수\n 기관 투자자들은 KODE...","- 정확성: 부족함 <reason> 요약 내용이 원문 기사와 일부 일치하지만, 원문..."
0,SK하이닉스,2025-07-30,"✅ 주요 요약\n\n- **삼성전자 주가 상승, SK하이닉스 주가 하락** \n ...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 대체로 일치하며,..."
0,현대글로비스,2025-07-30,"✅ 주요 요약\n\n- **현대차와 기아, 외국인 매수세로 주가 상승** \n ...","- 정확성: 좋음\n <reason> 요약 내용이 원문 기사와 일치하며, 주요 정..."
0,현대차,2025-07-30,"✅ 주요 요약\n\n- **현대차그룹, 미국에 50억 달러 추가 투자 발표**\n ...",- 정확성: 부족함 <reason> [요약에서 언급된 몇 가지 세부 사항이 원문 기...
0,삼성전자,2025-07-30,"✅ 주요 요약\n\n- **삼성전자, AI 엑스퍼트 프로그램 신설 및 인재 발굴 강...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 잘 일치하며, 주..."
0,한미반도체,2025-07-30,"✅ 주요 요약\n\n- **한국 대미 수출, 8월 초 14% 급감**\n - 미국...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 일치하며, 주요 ..."
0,파크시스템스,2025-07-30,"✅ 주요 요약\n\n- **기관 투자자, 코스닥에서 다양한 종목 순매수**\n -...",**평가:**\n\n- 정확성: 부족함 <reason> 요약에서 언급된 종목의 실적...
0,DB하이텍,2025-07-30,"✅ 주요 요약\n- **부자네스탁론, 투자자들 사이에서 인기** \n 부자네스탁...","- 정확성: 좋음 <reason> [요약 내용이 원문 기사와 일치하며, 주요 정보가..."
0,기아,2025-07-30,"✅ 주요 요약\n\n- **현대차와 기아, 외국인 투자자 매수세로 주가 상승**\n...",- 정확성: 부족함 <reason> [요약 내용이 원문 기사와 일치하지 않는 부분이...
0,POSCO홀딩스,2025-07-30,✅ 주요 요약\n\n- **금리 변동성과 실적 호조 기업 주목** \n - 금리...,"- 정확성: 좋음 <reason> [요약 내용이 원문 기사와 잘 일치하며, 주요 포..."
0,LG에너지솔루션,2025-07-30,"✅ 주요 요약\n\n- **2차전지 업종, ESS 수요 증가로 성장 기대** \n...",- 정확성: 부족함 <reason> [요약이 원문 기사와 일치하지 않는 부분이 있습...

In [40]:
for _,data in chunk_df.iterrows():
    print(data.ticker)
    print(data.summary)
    print('-'*100)

우리금융지주
✅ 주요 요약

- **국내 4대 금융지주, 평균 급여 사상 첫 반기 1억 원 돌파**
  - KB금융이 1억1200만원으로 가장 높은 평균 급여를 기록했으며, 금융지주들의 상반기 순이익이 10조3254억원을 넘어서며 급여 상승에 기여함.

- **금융지주 주가 하락, 정부의 세금 및 과징금 부담 증가**
  - 교육세 인상과 과징금 부과 등으로 인해 금융지주 주가가 하락하고 있으며, 정부의 압박이 주가에 부정적 영향을 미치고 있음.

- **외국인 투자자, 정부의 금융권 압박에 우려**
  - 외국인 지분율이 높은 금융지주사들이 정부의 압박으로 인해 주가가 하락하고 있으며, 외국인 투자자들의 우려가 증가하고 있음.

🔑 **키워드**: 4대 금융지주, 평균 급여, 주가 하락, 교육세 인상, 외국인 투자자, 정부 압박, 금융권, 과징금, KB금융, 신한금융, 하나금융, 우리금융, 이자놀이, 주주환원.
----------------------------------------------------------------------------------------------------
삼성화재
✅ 주요 요약

- **삼성화재, AI 의료심사 도입으로 암 진단 심사 효율성 향상**
  삼성화재는 AI 의료심사를 도입하여 암 진단 보험금 지급 심사의 효율성과 정확성을 높였습니다. 이 시스템은 의료 데이터를 자동으로 분석하여 심사자의 검토 시간을 단축하고, 인력 검토 비중을 55% 감소시켰습니다. 삼성화재는 AI의료심사 시스템의 특허출원을 완료했습니다.

- **외국인 투자자, SK하이닉스 등 주요 종목 순매수**
  외국인 투자자들은 SK하이닉스, 현대차, HD한국조선해양, 삼양식품, 기아, 이수페타시스, 현대로템, 한화오션, 한국항공우주, 삼성화재 등 주요 종목을 집중적으로 매수했습니다. 특히 운수장비 업종의 종목들이 다수 포함되어 있으며, SK하이닉스와 현대차는 주가 상승을 기록했습니다.

- **삼성화재, 항공지연 특약 출시로 고객 편의성 증대**
  삼성화재는 해외 출발 항공기 지연 및 결항 시 실손 보장을 제공하는 특약을 출시했습니다. 이 특약은 고객의 여행 중 불편을 최소화하고, 최대 50만원까지 보장합니다. 이는 국내외 모든 공항에서 2시간 이상 항공 지연 시 보장을 제공하는 업계 최초의 사례입니다.

🔑 **키워드**: 삼성화재, AI 의료심사, 외국인 투자자, SK하이닉스, 항공지연 특약, 효율성, 암 진단, 운수장비 업종, 고객 편의성.

**개선 포인트**:
1. **정확성**: 외국인 투자자 관련 내용을 원문에 맞춰 정확하게 전달했습니다.
2. **포괄성**: 삼성화재의 AI 의료심사 도입과 관련된 세부 사항을 포함하여 원문 기사의 다양한 주제를 충분히 반영했습니다.
3. **일관성**: 각 주제를 별도로 요약하여 주제가 혼재되지 않도록 구성했습니다.
----------------------------------------------------------------------------------------------------
삼성생명
✅ 주요 요약

- **삼성그룹, 하반기 대규모 공개채용 실시**
  삼성전자를 포함한 19개 계열사가 하반기 신입사원 공개채용을 시작하며, 국내외 불확실성 속에서도 미래 인재 투자를 지속할 계획이다. 지원자는 9월 3일까지 지원서를 제출할 수 있으며, 직무적합성 평가, 삼성직무적성검사(GSAT), 면접, 건강검진 순으로 채용 절차가 진행된다.

- **삼성, 인재 육성 및 채용 제도 혁신 지속**
  삼성은 청년들의 소프트웨어 경쟁력 강화를 위한 '삼성청년SW·AI아카데미'(SSAFY)를 운영하며, 열린 채용 문화와 인사제도 혁신을 통해 우수 인재를 공정하게 선발하고 있다. 또한, 직급 통폐합과 평가제도 개선을 통해 수평적 조직문화를 확산하고 있다.

🔑 키워드: 삼성그룹, 공개채용, 인재 육성, 인사제도 혁신, 수평적 조직문화

**피드백 반영**: 요약의 일관성을 높이기 위해 삼성생명 실적 관련 내용을 배제하고, 삼성그룹의 하반기 공개채용과 인재 육성에 집중하여 작성하였습니다.
----------------------------------------------------------------------------------------------------
카카오뱅크
✅ **주요 요약**

- **카카오 창업자 김범수, 법적 문제 직면**
  - 김범수는 SM엔터 주가 조작 혐의로 징역 15년과 벌금 5억 원을 구형받았다. 검찰은 그가 시세조종을 통해 부당한 이익을 취했다고 주장한다.

- **카카오의 스테이블코인 사업 준비**
  - 카카오는 스테이블코인 발행과 유통을 위한 TF를 구성하고 있으며, 카카오뱅크와 카카오페이가 핵심 역할을 수행할 예정이다. 카카오뱅크는 준비금 수탁 은행 역할을, 카카오페이는 유통과 결제망 역할을 맡을 계획이다. 법·제도 정비가 완료되면 본격적인 사업을 시작할 예정이다.

- **인터넷은행의 대출 전략 및 유가증권 운용**
  - 카카오뱅크와 케이뱅크는 중·저신용자 대출 비중 규제를 준수하기 위해 고신용자 대출을 줄이는 등 전략을 조정하고 있다. 또한, 유가증권 운용액이 급증하며 시중은행과 비교해 빠른 증가세를 보이고 있다. 이는 대출을 내줄 곳을 찾지 못한 결과로, 유가증권 투자를 통해 안정적인 수익을 확보하려는 전략이다.

- **카카오의 다른 사업 전략 및 시장 상황**
  - 카카오는 원화 기반 스테이블코인 시장 진입을 준비 중이며, 네이버와 토스와 함께 시장을 선점하기 위한 전략을 모색하고 있다. 법·제도 정비가 완료되면 블록체인 기반의 국경 간 송금과 결제가 가능해져, 이를 먼저 시장에 안착시킨 기업이 가장 큰 수혜를 거둘 것으로 예상된다.

🔑 **키워드**: 카카오, 김범수, 자본시장법, 시세조종, 스테이블코인, 인터넷은행, 중·저신용자, 대출 규제, 유가증권 운용, 시장 전략, 법·제도 정비.

### 주제별 요약

- **김범수의 법적 문제**: SM엔터 주가 조작 혐의로 징역 15년 구형.
- **스테이블코인 사업**: 카카오의 TF 구성 및 전략 점검, 카카오뱅크와 카카오페이의 역할.
- **대출 전략 및 유가증권 운용**: 인터넷은행의 중·저신용자 대출 비중 조정 및 유가증권 운용액 증가.
- **시장 상황 및 전략**: 원화 스테이블코인 시장 진입 준비 및 법·제도 정비 필요성.
----------------------------------------------------------------------------------------------------
메리츠금융지주
✅ 주요 요약

- **현대해상, 실적 부진에도 주가 상승**
  - 현대해상의 상반기 순이익이 전년 대비 46% 감소했으나, 증권사들의 긍정적 평가와 CSM 성장세 덕분에 주가가 상승세를 보임. 특히, KB증권은 투자의견을 상향하고 목표가를 6.7% 높임.

- **메리츠금융, 사상 최대 실적 및 주주환원 정책 강화**
  - 메리츠금융지주는 상반기 최대 실적을 기록하며 주주환원 정책을 강화, 주가가 급등세를 보임. 자사주 매입 및 소각을 통해 주주가치 제고에 집중.

- **보험업계, 세제 개편으로 경영환경 악화 우려**
  - 정부의 교육세율 인상 등으로 보험사들의 재무건전성 악화와 순이익 감소가 예상되며, 업계의 경영환경이 부정적으로 전망됨. 삼성화재는 교육세 인상이 장기보험의 미래 비용 증가에 영향을 미칠 것이라고 지적.

🔑 **키워드**: 현대해상, 메리츠금융, CSM 성장, 주주환원 정책, 교육세율 인상, 보험업계 경영환경.
----------------------------------------------------------------------------------------------------
현대모비스
✅ 주요 요약

- **현대모비스, 차량용 반도체 연구개발 프로세스 ISO 26262 인증 획득**
  - 현대모비스는 독일 엑시다로부터 차량용 반도체 연구개발 프로세스 전체에 대해 ISO 26262 인증을 받았으며, 이는 제품 단위로 인증받은 것과 동일한 수준의 신뢰성을 확보하게 됨.

- **로보틱스 및 차량용 반도체 사업 확장 계획 발표**
  - 현대모비스는 로보틱스 액추에이터 시장 진출과 차량용 반도체 개발을 통해 사업 확장을 계획하고 있으며, 2029년까지 홀로그래픽 윈드쉴드 디스플레이 출시를 목표로 하고 있음.

- **글로벌 시장에서의 수익성 및 매출 성장 목표 설정**
  - 현대모비스는 2027년까지 연평균 매출 증가율 8% 이상 및 영업이익률 5~6% 달성을 목표로 하며, 비현대차그룹 계열사 매출 비중을 2033년까지 40%로 확대할 계획임.

- **기술 개발 및 시장 전략 강화**
  - 현대모비스는 전동화, ADAS, IVI 등 고부가가치 핵심 부품을 중심으로 글로벌 고객사와의 협력을 강화하고 있으며, 전기차 및 자율주행차 관련 기술 개발에 집중하고 있음.
  - 국내외 주요 협력사와의 파트너십을 통해 차량용 반도체 생태계 확장을 추진하고 있으며, 2021년 인수한 현대오트론의 반도체 사업을 기반으로 16종의 반도체를 양산 중임.

🔑 키워드
- 현대모비스
- ISO 26262 인증
- 차량용 반도체
- 로보틱스
- 액추에이터
- 홀로그래픽 디스플레이
- 매출 성장
- 수익성
- 글로벌 시장
- 기술 개발
- 시장 전략
- 협력사 파트너십
----------------------------------------------------------------------------------------------------
현대오토에버
✅ 주요 요약
- 기관 투자자, 다양한 종목 순매수
  기관 투자자들은 KODEX 200, 현대로템, SK하이닉스, 한화오션, HD현대미포, HD한국조선해양, 현대모비스, LS, 한화엔진 등 다양한 종목을 중점적으로 매수하였으며, 운수장비 업종 종목 4개가 포함됨.

- SK하이닉스 등 일부 종목 주가 상승
  SK하이닉스, KODEX 200선물인버스2X 등은 전일 대비 주가가 상승했으며, KODEX 200, HD한국조선해양 등은 하락.

- 추가 종목 정보
  KODEX 200선물인버스2X, 한화오션, HD현대미포, HD한국조선해양, 현대모비스, LS, 한화엔진 등도 기관 투자자들의 주요 매수 종목으로 포함됨.

- 운수장비 업종의 주목
  운수장비 업종에 속한 현대로템, HD현대미포, HD한국조선해양, 현대모비스 등 4개 종목이 기관 투자자들의 주목을 받았으며, 이들 종목의 주가 변동이 시장에 큰 영향을 미침.

🔑 키워드
- 기관 투자자
- KODEX 200
- 현대로템
- SK하이닉스
- 주가 상승
- 운수장비 업종

📌 개선 포인트
- 포괄성을 높이기 위해 더 많은 종목 정보를 포함하였으며, 일관성을 위해 기사 자동생성 알고리즘에 대한 언급을 생략하였습니다.
----------------------------------------------------------------------------------------------------
SK하이닉스
✅ 주요 요약

- **삼성전자 주가 상승, SK하이닉스 주가 하락**
  삼성전자는 HBM4 시장 진입 기대감과 미국 상무부의 지분 취득 검토 소식으로 주가가 상승했으며, SK하이닉스는 시장 경쟁 심화와 AI 거품론으로 주가가 하락세를 보임.

- **삼성전자, 하반기 실적 개선 전망**
  삼성전자는 HBM4 시장 점유율 상승과 파운드리 부문 신규 거래처 확보로 인해 하반기 영업이익이 18조원에 이를 것으로 예상됨.

- **SK하이닉스, HBM 시장 경쟁 심화 우려**
  SK하이닉스는 HBM 시장에서 경쟁 심화로 인해 시장 점유율 하락 우려가 있으며, 이에 따라 주가 상승 탄력이 둔화될 가능성이 있음.

- **고액 자산가들의 SK하이닉스 매수**
  최근 AI 산업 거품론으로 주가가 하락하자 고액 자산가들이 SK하이닉스를 저가 매수하며 78억2000만원어치 순매수를 기록함.

- **AI 관련 시장 전망**
  SK하이닉스는 AI 메모리 수요 확대에 따라 HBM 분야에서 우위를 점하고 있으며, 향후 수년간 시장이 수십억 달러 규모로 확대될 것으로 전망됨.

- **외국인 투자자 동향**
  외국인 투자자들은 SK하이닉스와 삼성전자를 포함한 주요 전기·전자 업종에 대한 매수와 매도를 활발히 진행하며 시장에 영향을 미치고 있음.

🔑 키워드: 삼성전자, SK하이닉스, HBM4, 주가 상승, 주가 하락, 시장 경쟁, AI 거품론, 영업이익, 파운드리, 시장 점유율, 외국인 투자자, 미국 상무부, 고액 자산가, AI 메모리 수요.
----------------------------------------------------------------------------------------------------
현대글로비스
✅ 주요 요약

- **현대차와 기아, 외국인 매수세로 주가 상승**
  최근 한 달간 현대차와 기아의 주가는 각각 5.5%와 5.84% 상승했습니다. 외국인 투자자들이 현대차와 기아를 각각 1790억 원, 351억 원어치 순매수하며 주가 상승을 견인했습니다. 이는 미국의 고율 관세 이슈가 해소되면서 자동차주에 대한 투자 매력이 부각된 결과입니다. 현대차는 미국 현지화 전략을 통해 일본과 유럽 경쟁사보다 앞서고 있으며, 향후 3년간 4조 원 규모의 자사주 매입과 소각 계획이 주가에 긍정적 영향을 미칠 것으로 예상됩니다.

- **현대글로비스, 사상 최대 실적 및 주가 상승**
  현대글로비스는 해운 부문에서 비계열 고객 물량 확대와 선대 운영 효율화로 사상 최대 실적을 기록했습니다. 2분기 매출은 7조 5,160억 원, 영업이익은 5,389억 원으로 전년 동기 대비 각각 6.4%, 22.7% 증가했습니다. 외국인 매수세 유입과 글로벌 물류 네트워크 확장으로 주가 상승세를 지속하고 있습니다.

- **글로벌 물류 브랜드 가치 상승**
  현대글로비스는 브랜드 파이낸스의 평가에서 높은 성장률을 기록하며 세계 물류 브랜드 21위에 올랐습니다. 친환경·첨단 공급망 구축 및 글로벌 네트워크 확장이 성장의 주요 요인으로 작용하고 있습니다.

- **미래 성장 전략 및 투자 계획**
  현대글로비스는 2030년까지 9조 원을 육상 물류 사업 진출, 물류 자동화 및 디지털 전환, 전기차 사용 후 배터리 순환 사업 등 새 먹거리에 투자해 매출 40조 원을 달성할 계획입니다. 이는 지속 가능한 경영 실천을 통해 긍정적 가치 창출을 이어가려는 의지를 반영합니다.

🔑 **키워드**
- 현대차, 기아, 외국인 매수세, 현대글로비스, 사상 최대 실적, 글로벌 물류 브랜드, 친환경 공급망, 물류 네트워크, 미래 성장 전략, 투자 계획.
----------------------------------------------------------------------------------------------------
현대차
✅ 주요 요약

- **현대차그룹, 미국에 50억 달러 추가 투자 발표**
  현대차그룹은 미국 루이지애나에 270만 톤 규모의 전기로 제철소를 건설하고, 연간 3만 대 생산 가능한 로봇 공장을 신설하는 등 4년간 260억 달러를 투자하여 미래산업 경쟁력을 강화할 계획이다. 이번 투자는 제철, 자동차, 로봇 등 다양한 분야에 걸쳐 있으며, 미국 내 철강-부품-완성차로 이어지는 밸류 체인을 구축하여 경쟁력을 높일 예정이다.

- **현대차 노조, 파업 찬반 투표에서 90% 이상 찬성**
  현대차 노조는 임금 인상과 근로조건 개선을 요구하며 파업을 준비 중이며, 중앙노동위원회의 조정 중지 결정으로 합법적인 파업권을 확보했다. 노조는 기본급 인상, 성과급 지급, 근로시간 단축 등을 요구하고 있다.

- **현대차, 미국 관세 영향으로 상반기 영업이익 감소**
  현대차는 미국의 25% 관세로 인해 상반기 영업이익이 전년 대비 7.7% 감소했으며, 하반기에는 관세 영향이 더 커질 것으로 예상된다. 이는 미국 내 자동차 생산능력 확대와 전기차, 하이브리드 등 다양한 차종 라인업을 통해 대응할 계획이다.

- **현대차그룹, 글로벌 리더십 인정**
  현대차그룹의 양희원 R&D본부장과 랜디 파커 북미권역본부장이 미국 자동차 전문 매체 오토모티브 뉴스의 '2025 오토모티브 뉴스 올스타'로 선정되며 글로벌 자동차 산업에서의 리더십과 혁신성을 인정받았다. 양희원 사장은 제품 개발 부문에서, 랜디 파커 CEO는 글로벌 완성차 미국 임원 부문에서 수상했다.

- **현대차그룹, 청정에너지 장관 회의에서 수소 생태계 구축 강조**
  현대차그룹은 제16차 청정에너지 장관 회의에 참가해 수소 생태계 구축의 필요성을 강조하며, 국제 협력을 통한 저탄소 산업 전환 촉진을 논의했다. 켄 라미레즈 부사장은 공공과 민간의 협력을 통한 수소 인프라 구축의 중요성을 역설했다.

**키워드:** 현대차그룹, 미국 투자, 제철소, 로봇 공장, 파업, 노조, 관세, 영업이익 감소, 글로벌 리더십, 오토모티브 뉴스 올스타, 청정에너지 장관 회의, 수소 생태계.
----------------------------------------------------------------------------------------------------
삼성전자
✅ 주요 요약

- **삼성전자, AI 엑스퍼트 프로그램 신설 및 인재 발굴 강화**
  삼성전자는 AI 분야의 우수 인재를 'AI 엑스퍼트'로 선정하고, 격려금 2000만원과 자격 수당 50만원을 지급하는 프로그램을 도입했다. 선정 기준은 AI 관련 최고 수준 학회 논문 발표, 글로벌 AI 대회 수상, 사내 AI 과제 표창 등이며, 이는 AI 선도 기업으로 도약하기 위한 전략의 일환이다.

- **테슬라와의 대규모 AI 칩 공급 계약 체결**
  삼성전자는 테슬라와 수조 원대의 AI 칩 공급 계약을 체결하여, 파운드리 사업과 반도체 부문에서 중장기적 성장 동력을 확보할 수 있는 기반을 마련했다. 이는 삼성의 반도체 수요를 안정적으로 견인할 수 있는 실질적 기반으로 평가된다.

- **글로벌 메모리 시장 경쟁 심화와 기술력 개선 필요**
  SK하이닉스의 시장 점유율 확대에 따라 삼성전자는 메모리 경쟁에서 압박을 받고 있으며, 기술력 개선과 고객 다변화를 추진해야 하는 과제를 안고 있다. 특히, 고대역폭 메모리(HBM) 시장에서의 경쟁이 심화되고 있다.

- **무역 환경 변화와 기업 거버넌스 안정화**
  미국과 중국 간 관세 완화 논의와 한국과의 무역 긴장 완화 조짐이 나타나고 있으며, 대법원의 경영 승계 관련 판결 확정으로 법적 리스크가 일부 해소되었다는 평가가 있다. 이는 삼성의 글로벌 공급망 안정과 시장 접근성 회복에 긍정적인 영향을 미칠 것으로 보인다.

- **외국인 투자자 동향 및 주가 관련 정보**
  최근 외국인 투자자들은 삼성전자를 포함한 주요 종목을 매도하고 있으며, 이는 글로벌 경제 불확실성과 관련이 있다. 삼성전자의 주가는 테슬라와의 계약 체결 등 긍정적 요인에도 불구하고, 메모리 시장 경쟁 심화로 인해 변동성을 보이고 있다.

🔑 키워드
- 삼성전자
- AI 엑스퍼트
- 테슬라
- AI 칩 공급 계약
- 글로벌 메모리 시장
- SK하이닉스
- 무역 환경
- 관세 완화
- 경영 승계
- 법적 리스크
- 외국인 투자자
- 주가 변동성
----------------------------------------------------------------------------------------------------
한미반도체
✅ 주요 요약

- **한국 대미 수출, 8월 초 14% 급감**
  - 미국과 중국으로의 수출이 두 자릿수 감소율을 기록하며, 철강과 알루미늄 등 주요 수출 품목의 부진이 지속됨.
  - 반도체를 제외한 수출 품목 전반이 부진한 가운데, 반도체는 전체 수출의 26%를 차지하며 역대 최대 비중 기록.

- **반도체 수출, 39억 달러로 전년 대비 12% 증가**
  - D램과 HBM 등 세부 품목에서 강세를 보이며, 반도체가 수출의 유일한 희망으로 부각됨.

- **한미 정상회담, 1500억 달러 규모 대미 투자 계획 발표**
  - 삼성전자, 현대차 등 주요 기업들이 경제사절단으로 참석해 반도체, 배터리, 조선 등 첨단 분야에서 대미 투자 협력 방안을 모색함.

- **한미 정상회담에서 논의된 세부 내용**
  - 이재명 대통령은 경제단체 대표 및 주요 기업인들과 간담회를 열어 관세 협상 이후의 전략을 논의.
  - 기업인들은 대미 투자와 구매 계획을 점검하며, 일자리 창출과 미래 산업 육성을 위한 의견을 전달.

- **기업인들의 구체적인 발언 및 계획**
  - 이재용 삼성전자 회장은 양질의 일자리 창출과 고부가가치 산업 육성을 위한 투자를 약속.
  - 서정진 셀트리온 회장은 젊은 창업인을 키우기 위해 스타트업 투자를 늘려야 한다고 제언.

- **경제사절단의 구성 및 역할**
  - 이재용 삼성전자 회장, 최태원 SK그룹 회장, 정의선 현대차그룹 회장 등 주요 그룹 총수들이 경제사절단으로 동행.
  - 반도체, 배터리, 자동차, 조선 등 첨단 산업 분야에서 협력 방안을 논의하며, 1500억 달러 규모의 대미 투자 계획을 발표.

- **추가 세부 사항**
  - 한미 정상회담에서 반도체, 배터리, 조선업 등 경제 협력과 첨단 기술, 핵심 광물 등에서의 파트너십 강화를 논의.
  - 미국의 반도체 관세 설정 예고로 인한 시장의 우려와 대응 방안도 논의됨.
----------------------------------------------------------------------------------------------------
파크시스템스
✅ 주요 요약

- **기관 투자자, 코스닥에서 다양한 종목 순매수**
  - 기관 투자자들은 코스닥 시장에서 에이비엘바이오, 덕산네오룩스, ISC 등 다양한 종목을 집중적으로 매수하였습니다. 특히, 제약 업종의 종목 3개가 포함되어 있으며, 이는 해당 종목들의 주가 상승에 긍정적인 영향을 미쳤습니다.

- **주요 종목의 주가 변동**
  - 에이비엘바이오, 덕산네오룩스, ISC 등의 주가는 전일 대비 상승하였으며, 반면 에스엠 등의 주가는 하락세를 보였습니다. 하림은 흑자전환을 기록하며 주가가 상승하였고, 하이록코리아도 상승세를 보였습니다. 반면, 하이비젼시스템은 적자전환으로 인해 주가가 하락하였습니다.

- **다양한 종목의 실적 및 주가 동향**
  - 하림은 흑자전환을 기록하며 18.76%의 주가 상승을 보였고, 하이록코리아는 17.89% 상승하였습니다. 하이비젼시스템은 적자전환으로 인해 주가가 54.61% 하락하였습니다. 이 외에도 다양한 종목들이 실적에 따라 주가 변동을 보였습니다.

- **뉴스 기사, AI 알고리즘에 의해 자동 생성**
  - 해당 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 작성되었습니다.

**키워드:** 기관 투자자, 코스닥, 에이비엘바이오, 덕산네오룩스, ISC, 주가 상승, AI 알고리즘, 자동 생성, 하림, 하이록코리아, 하이비젼시스템, 주가 변동, 투자자 동향.

**개선 사항:**
1. **정확성**: 원문 기사에서 언급된 모든 주요 종목의 실적 및 주가 변동 정보를 보다 상세히 반영하였습니다. 특히, 수치나 구체적인 변동 이유 등을 포함하여 정보의 정확성을 높였습니다.
2. **포괄성**: 주요 종목 외에도 다양한 종목에 대한 정보를 포함하여 포괄성을 높였습니다.
3. **일관성**: 특정 종목에 대한 정보만을 요약에 포함시키고, 다른 종목에 대한 정보는 별도로 구분하여 제공하였습니다.
----------------------------------------------------------------------------------------------------
DB하이텍
✅ 주요 요약
- **부자네스탁론, 투자자들 사이에서 인기**
  부자네스탁론이 새롭게 출시한 스탁론 상품이 투자자들 사이에서 주목받고 있다. 이 상품은 본인 자산 포함 최대 4배까지 투자 가능하며, 담보유지비율 120%의 유연한 조건을 제공한다.

- **다양한 투자 솔루션과 대환대출 서비스 제공**
  스탁론은 증권사 신용융자보다 높은 레버리지와 낮은 담보유지비율을 제공하며, 미수금 및 반대매매 위험을 해결하는 대환대출 상품도 포함되어 있다.

- **맞춤형 대출로 규제 이슈 해결**
  신용, 주식담보대출 이용 불가 종목 및 D.S.R 규제에 제약을 받는 투자자들에게 계좌 평가금액 기준으로 맞춤형 대출을 제공하여 실질적인 해결책을 제시한다.

- **고객 맞춤형 대출 방법 제공**
  부자네스탁론은 고객의 투자 상황에 맞춰 최적의 대출 방법을 제공하며, 강화된 금융 규제 환경 속에서도 투자자들의 기회를 넓히기 위해 노력하고 있다.

🔑 키워드: 부자네스탁론, 스탁론, 투자자, 대환대출, 맞춤형 대출, 금융 규제, 투자 솔루션, 레버리지, 담보유지비율.
----------------------------------------------------------------------------------------------------
기아
✅ 주요 요약

- **현대차와 기아, 외국인 투자자 매수세로 주가 상승**
  외국인 투자자들이 현대차와 기아를 대규모로 매수하면서 이들 자동차주의 주가가 상승세를 보이고 있습니다. 현대차는 최근 한 달간 5.5% 상승하며 시가총액 5위 자리를 탈환했습니다. 이는 기존 주도 업종에서 차익 실현이 이루어지는 가운데 저평가 매력이 부각된 결과입니다.

- **미국 시장에서의 현지화 전략 및 하이브리드 차량 수요 증가**
  현대차는 미국 시장에서의 현지화 전략과 하이브리드 차량 수요 증가로 인해 향후 3년간 4조원 규모의 자사주 매입과 소각 계획이 주가에 긍정적 영향을 미칠 것으로 분석되고 있습니다. 팰리세이드 하이브리드 모델의 미국 출시도 예정되어 있습니다.

- **배터리 안전성 강화 및 협력 관계**
  현대차와 기아는 배터리 안전성을 높이기 위해 배터리 3사와 협력하여 배터리 셀 화재 감지 시스템과 화재 진압 기술을 공동 연구하고 있으며, 소방 기술을 고도화하는데 지속 협력할 계획입니다.

- **미국 시장에서의 전략적 대응**
  현대차와 기아는 미국발 관세 리스크에 대응하기 위해 미국 내 생산과 부품 조달을 빠르게 확대하고 있으며, 현지 공장 가동률을 높여 안정적인 생산체제를 갖추고 있습니다. 이는 미국 시장에서의 경쟁력을 강화하기 위한 전략적 대응입니다.

- **기아의 전기차 시장 공략**
  기아는 다양한 사용 목적에 맞게 조립할 수 있는 전기 밴 PV5를 출시하며, 고객의 목소리를 반영한 혁신적인 모빌리티 솔루션을 제공하고 있습니다. 이는 전기차 시장에서의 경쟁력을 높이기 위한 전략입니다.
----------------------------------------------------------------------------------------------------
POSCO홀딩스
✅ 주요 요약

- **금리 변동성과 실적 호조 기업 주목**
  - 금리 변동성과 대외 불확실성 증가로 인해 안정적인 투자처로 실적 호조 기업이 주목받고 있으며, 특히 실적과 전망이 긍정적인 종목에 투자자들의 관심이 집중되고 있음.

- **스탁론에 대한 관심 증가와 올뉴스탁론의 저금리 상품 출시**
  - 투자자들이 스탁론을 통해 더 많은 자금을 활용하려는 경향이 증가하고 있으며, 올뉴스탁론은 DSR 무관 상품과 연 4%대의 업계 최저 금리 상품을 제공하여 다양한 선택지를 제공하고 있음. DSR 무관 상품은 기존 대출액이나 소득에 관계없이 최대 4배까지 자금 활용이 가능하며, 대체거래소(NXT) 거래도 지원함.

- **외국인 투자자들의 주요 종목 매수 및 매도 동향**
  - 외국인 투자자들이 SK하이닉스, 삼성전자, 카카오 등 주요 종목을 매수하고 있으며, 전기·전자 업종의 주가가 상승세를 보이는 가운데 일부 종목은 하락세를 기록하고 있음. 특히, SK하이닉스와 삼성전자는 외국인 매수세가 강하게 유입되고 있음.

- **에코프로비엠의 주가 상승 배경**
  - 에코프로비엠은 깜짝 실적 발표와 전기차 시장 회복 기대, 밸류에이션 재평가, 외국인 매수세 강화로 주가 상승세를 이어가고 있음. 그러나 높은 밸류에이션 부담과 2차전지 수요 회복 속도에 대한 불확실성도 존재함.

- **무빙스탁의 대환자금대출 서비스**
  - 무빙스탁은 고금리 주식대출을 3%대 저금리로 전환할 수 있는 대환자금대출 서비스를 제공, 투자자들의 이자 부담을 줄이고 효율적인 자금 운용을 지원하고 있음. 이벤트 기간 동안 대환자금대출 신청 시 이자 비용이 발생하지 않아 투자자들에게 즉각적인 혜택을 제공함.

- **효성중공업의 주가 상승 배경**
  - AI와 데이터센터 확산에 따른 전력기기 수요 상승, 초고압 장비 수주 확대, 역대급 실적 기록, 그리고 배당 및 밸류에이션 재평가가 주가 상승의 주요 요인으로 작용함.

- **포스코그룹의 인도 협력 강화**
  - 포스코그룹은 인도 JSW그룹과의 협력을 통해 인도 내 일관제철소 건설을 추진 중이며, 이는 인도 철강 시장의 성장에 대응하기 위한 전략적 움직임으로 평가됨.

🔑 **키워드**: 금리 변동성, 실적 호조 기업, 스탁론, 올뉴스탁론, 외국인 투자자, SK하이닉스, 삼성전자, 카카오, 전기·전자 업종, 주가 상승, 에코프로비엠, 전기차 시장, 밸류에이션 재평가, 무빙스탁, 대환자금대출, 효성중공업, 포스코그룹, 인도 협력.
----------------------------------------------------------------------------------------------------
LG에너지솔루션
✅ 주요 요약

- **2차전지 업종, ESS 수요 증가로 성장 기대**
  이동근 대표는 2차전지 업종의 성장 가능성을 강조하며, ESS(에너지저장장치) 수요 증가가 전력 수급 균형과 전력망 안정성을 높일 것이라고 진단했습니다. 그는 LG에너지솔루션과 현대차를 유망 종목으로 꼽으며, 각각의 투자 전략을 제시했습니다.

- **전기차 배터리 기술 혁신과 안전성 강화**
  전고체 배터리의 상용화가 2025~2026년에 본격화될 것으로 예상되며, 이는 전기차 주행거리와 안전성을 획기적으로 개선할 것으로 보입니다. 삼성SDI는 전고체 배터리 양산을 2027년 목표로 하고 있습니다.

- **투자 전략 및 종목 추천**
  이동근 대표는 LG에너지솔루션의 ESS 성장성과 현대차의 저평가 매력을 강조하며, 각각의 진입가와 목표가를 제시했습니다. 그는 단기 급등한 종목보다는 실적 턴어라운드가 가능한 기업에 집중할 것을 권장했습니다.

- **시장 동향 및 기타 기업 정보**
  최근 2차전지 업종의 반등은 ESS 수요 증가와 관련이 있으며, LG에너지솔루션과 삼성SDI는 이 시장에서의 입지를 강화하고 있습니다. 또한, 전고체 배터리 기술의 발전이 가속화되면서 관련 기업들의 기술 경쟁이 심화되고 있습니다.

- **다양한 기업의 시장 전략**
  LG에너지솔루션, 삼성SDI, SK온 등 국내 배터리 3사는 전기차 배터리 시장에서의 입지를 강화하기 위해 연구개발(R&D) 투자를 늘리고 있으며, 각 사의 차입금 증가와 함께 미래 기술 개발을 위한 노력을 지속하고 있습니다.

- **글로벌 시장에서의 경쟁**
  한국 배터리 기업들은 중국 CATL과의 경쟁에서 점유율을 회복하기 위해 기술력과 생산능력을 강화하고 있으며, 특히 북미 시장에서의 성장을 목표로 하고 있습니다.

🔑 키워드
- 2차전지
- ESS 수요
- 전고체 배터리
- LG에너지솔루션
- 현대차
- 투자 전략
- 성장 기대
- 글로벌 경쟁
----------------------------------------------------------------------------------------------------

## 원문 그대로 vs chunking만 사용 비교
> 결론 : chunking된 문서만을 사용하는 게 유리?

[SK하이닉스]

1. 원문 그대로
- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**  <br>
  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.<br>

- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  <br>
  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. <br>이들 종목 중 일부는 전일 대비 주가가 상승했습니다.

- **코스피지수 상승, 투자자 고민 증가**  <br>
  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.

- **주요 종목의 주가 변동**  <br>
  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.


2. chunking된 문서만 사용
- **SK하이닉스, 2분기 사상 최대 실적 기록**<br>
  SK하이닉스는 2분기 매출 22조2320억원, 영업이익 9조2129억원을 기록하며 사상 최대 실적을 달성했다. 이는 AI 메모리 수요 증가와 D램 및 낸드플래시 출하량 증가에 기인한다.<br>

- **HBM 시장에서의 경쟁 심화 우려**<br>
  SK하이닉스는 HBM 시장에서의 독점적 지위가 경쟁 심화로 인해 위협받을 수 있다는 우려가 제기되고 있다. 삼성전자와 마이크론의 시장 진입이 예상되며, 가격 하락 가능성이 논의되고 있다.<br>

- **SK하이닉스의 HBM 수요 성장 확신**<br>
  SK하이닉스는 HBM 수요가 지속적으로 증가할 것이라고 확신하며, AI 시장에서의 핵심 제품으로서의 중요성을 강조하고 있다. 이에 따라 HBM 생산을 위한 투자를 확대할 계획이다.

- **주가 변동 및 외부 기관의 평가**<br>
  SK하이닉스의 실적 발표 이후 주가는 일시적으로 상승했으나, 외부 기관의 평가에 따라 변동성을 보였다. 골드만삭스는 HBM 시장의 경쟁 심화로 인한 가격 하락 가능성을 지적하며 투자의견을 하향 조정했다. 반면, 다른 기관들은 SK하이닉스의 기술력과 시장 지배력을 긍정적으로 평가하며, 장기적인 성장 가능성을 강조했다.<br>

# 과거 버전

In [204]:
import pandas as pd
from datetime import datetime, timedelta
# cross-encoder
from sentence_transformers import CrossEncoder
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

# 1. 모델 준비 (CrossEncoder for Re-ranking) # 예시 모델 하나 생성
rerank_model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# 2. 최근 5일치 필터링 함수
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max()
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

# 3. huggingface 모델 이용.
def rerank_articles(df: pd.DataFrame,ticker:str ,query: str, top_k: int = 5):
    task_df= df[df.ticker == ticker]
    docs = task_df['content'].tolist()
    # 모델 이용?? 
    pairs = [(query, doc) for doc in docs]
    scores = rerank_model.predict(pairs)
    
    task_df_2 = task_df.copy()
    task_df_2['score'] = scores
    return task_df_2.sort_values(by='score', ascending=False).head(top_k)

# 4. 전체 요약 실행 함수
def summarize_top_articles(df: pd.DataFrame, ticker: str, query: str, top_k: int = 5):
    recent_df = get_recent_articles(df, ticker)
    top_df = rerank_articles(recent_df, query=query,ticker=ticker, top_k=top_k)

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)

    results = []
    for _, row in top_df.iterrows():
        state = {
            "article": row['content'],
            "summary": "",
            "feedback": "",
            "iteration": 0
        }
        result = runnable.invoke(state)


        print("✅ 실행 결과 타입:", type(result))
        print("✅ 실행 결과 키 목록:", result.keys())
        print("✅ 실행 결과 전체 내용:", result)

        if "final_summary" not in result:
            print("❌ final_summary 키가 없습니다. 중단합니다.")
            continue  # 또는 raise Exception("final_summary 없음")

        print(f'실행 결과 : {result}')
        results.append({
            "ticker": row['ticker'],
            "date": row['Date'],
            "header": row['header'],
            "url": row['url'],
            "summary": result["final_summary"], 
             "feedback": result.get("last_feedback", "피드백 없음")
        })
    return pd.DataFrame(results)

In [55]:
query = "우리금융지주 관련 시황"
ticker = "우리금융지주"  # 예시
result_df = summarize_top_articles(cusA_news_df, ticker=ticker, query=query, top_k=3)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음 <reason> 원문의 내용을 정확하게 반영하고 있음. </reason>
- 포괄성: 부족함 <reason> 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용이 누락되었음. </reason>
- 간결성: 좋음 <reason> 불필요한 표현 없이 요약 내용을 간결하게 전달하였음. </reason>
- 문장구성: 좋음 <reason> 문장이 자연스럽고 명확하게 구성되어 있음. </reason>

[피드백]
요약의 포괄성이 부족한 점이 아쉽습니다. 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용을 요약에 포함시키면 더욱 완벽한 요약이 될 것 같습니다. 이 부분을 고려하여 요약을 수정해보시는 것을 추천드립니다.
✅ '정확성' 평가 통과
❌ '포괄성' 평가에서 좋음이 아님
[should_stop] next_step = no

KeyError: 'Input to PromptTemplate is missing variables {\'"foo"\', \'"properties"\'}.  Expected: [\'"foo"\', \'"properties"\', \'article\', \'feedback\', \'summary\'] Received: [\'article\', \'summary\', \'feedback\']\nNote: if you intended {"foo"} to be part of the string and not a variable, please escape it with double curly braces like: \'{{"foo"}}\'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT '

In [35]:
def summarize_top_articles(total_contents :str):

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)
    results = []
    
    doc = total_contents

    state = {
        "article": doc['content'],
        "summary": "",
        "feedback": "",
        "iteration": 0
    }
    result = runnable.invoke(state)


    print("✅ 실행 결과 타입:", type(result))
    print("✅ 실행 결과 키 목록:", result.keys())
    print("✅ 실행 결과 전체 내용:", result)

    if "final_summary" not in result:
        print("❌ final_summary 키가 없습니다.")

    print(f'실행 결과 : {result}')
    results.append({
        "ticker": doc['ticker'],
        "date": doc['Date'],
        "header": doc['title'],
        "url": doc['url'],
        "summary": result["final_summary"], 
            "feedback": result.get("last_feedback", "피드백 없음")
    })
    return pd.DataFrame(results)