In [76]:
# 환경설정
import os
import sys
import time
from tqdm import tqdm
import nest_asyncio
nest_asyncio.apply()
from dotenv import load_dotenv

load_dotenv()
# duckdb
import duckdb

# 데이터 전처리
import pandas as pd
import numpy as np
import polars as pl
from datetime import datetime, timedelta
from copy import deepcopy

# 데이터 수집
import requests
from bs4 import BeautifulSoup

# VectorDB 저장
from hashlib import md5
from langchain_community.vectorstores.utils import filter_complex_metadata # ChromaDB가 제공하지 못하는 데이터 형태를 자동으로 string처리


## LLM 활용
from summary_function import NewsSummaryAgent
# LLM 활용을 위한 dict형태 구축
from collections import defaultdict

# langchain 계열
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

from langchain_openai import ChatOpenAI

# 1. LLM 모델 세팅 (OpenAI)
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
#from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)

In [2]:
ETF_conn = duckdb.connect('../DB/ETF.db')

In [3]:
ETF_df = ETF_conn.execute('select * from IRP_ETF_COMPOSE_table').fetchdf()
ETF_conn.close()

In [4]:
ETF_df = ETF_df.map(lambda x : x.strip())

In [5]:
ETF_df_task_1 = ETF_df[ETF_df['구성종목 종목명'] != "설정현금액"]
ETF_df_task_1 = ETF_df_task_1[ETF_df_task_1['구성종목 종목명'] != "원화현금"]
ETF_df_task_1 = ETF_df_task_1[1:]

In [6]:
# 원하는 컬럼 필터링
ETF_df_task_2 = ETF_df_task_1[['ETF 종목명','구성종목 표준코드','구성종목 종목명','편입비율']]

In [7]:
# 구성종목 중 상위 5개 추출
ETF_df_task_3 = ETF_df_task_2.sort_values(by=['ETF 종목명','편입비율'], ascending=False)

In [8]:
# 종목별 상위 5개
ETF_df_task_4= ETF_df_task_3.groupby('ETF 종목명').head(5)

In [9]:
ETF_df_task_4

                     ETF 종목명     구성종목 표준코드          구성종목 종목명       편입비율
7839               파워 코스피100  KR7005930003              삼성전자  22.979477
7899               파워 코스피100  KR7105560007              KB금융   2.846638
7856               파워 코스피100  KR7012450003         한화에어로스페이스   2.680652
7876               파워 코스피100  KR7035420009             NAVER   2.595262
7836               파워 코스피100  KR7005380001               현대차   2.280681
...                      ...           ...               ...        ...
59727  1Q 25-08 회사채(A+이상)액티브  KR6079317D93  JB 우리캐피탈488-3(지)   8.851804
59728  1Q 25-08 회사채(A+이상)액티브  KR6095923D95     현대커머셜485-3(지)   8.850334
59723  1Q 25-08 회사채(A+이상)액티브  KR6023788D91        신한캐피탈487-2   8.844456
59722  1Q 25-08 회사채(A+이상)액티브  KR601945CD90     아이비케이캐피탈290-7   8.842961
59726  1Q 25-08 회사채(A+이상)액티브  KR6065903DA1         현대카드886-3   8.833223

[4235 rows x 4 columns]

In [10]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('반도체')]

              ETF 종목명     구성종목 표준코드 구성종목 종목명       편입비율
61034  WON 반도체밸류체인액티브  KR7402340004    SK스퀘어   4.673431
61026  WON 반도체밸류체인액티브  KR7039030002   이오테크닉스   4.617986
61027  WON 반도체밸류체인액티브  KR7058470006     리노공업   4.522346
61019  WON 반도체밸류체인액티브  KR7000150003       두산   4.518261
61030  WON 반도체밸류체인액티브  KR7140860008   파크시스템스   4.513108
...               ...           ...      ...        ...
59981    ACE AI반도체포커스  KR7000660001   SK하이닉스  25.755918
59985    ACE AI반도체포커스  KR7005930003     삼성전자  24.736614
59992    ACE AI반도체포커스  KR7042700005    한미반도체  24.473018
59998    ACE AI반도체포커스  KR7140860008   파크시스템스   1.519344
59982    ACE AI반도체포커스  KR7000990002    DB하이텍   1.517061

[187 rows x 4 columns]

In [11]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('전지')]

,ETF 종목명,구성종목 표준코드,구성종목 종목명,편입비율
44379,TIGER 글로벌리튬&2차전지SOLACTIVE(합성),KRYZTRSEAH18,글로벌리튬2차전지 TRS 241017-18,8.990678
44380,TIGER 글로벌리튬&2차전지SOLACTIVE(합성),KRYZTRSF1E02,글로벌리튬2차전지 TRS 250114-02,32.05569
44381,TIGER 글로벌리튬&2차전지SOLACTIVE(합성),KRYZTRSF5E01,글로벌리튬2차전지 TRS 250514-01,27.325525
44378,TIGER 글로벌리튬&2차전지SOLACTIVE(합성),KRYZTRSE7Q01,글로벌리튬2차전지 TRS 240724-01,2.877921
44377,TIGER 글로벌리튬&2차전지SOLACTIVE(합성),KRYZTRSE7C04,글로벌리튬2차전지 TRS 240712-04,14.624746
...,...,...,...,...
43926,ACE 2차전지&친환경차액티브,KR7012330007,현대모비스,8.46777
43920,ACE 2차전지&친환경차액티브,KR7005380001,현대차,8.23665
43914,ACE 2차전지&친환경차액티브,KR7000270009,기아,8.090785
43921,ACE 2차전지&친환경차액티브,KR7005490008,POSCO홀딩스,7.842668
43958,ACE 2차전지&친환경차액티브,KR7373220003,LG에너지솔루션,7.376414

In [12]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('자율주행')]

,ETF 종목명,구성종목 표준코드,구성종목 종목명,편입비율
44360,TIGER 글로벌자율주행&전기차SOLACTIVE,US5949181045,MICROSOFT CORP,3.65966
44363,TIGER 글로벌자율주행&전기차SOLACTIVE,US67066G1040,NVIDIA CORP,3.405895
44366,TIGER 글로벌자율주행&전기차SOLACTIVE,US7475251036,QUALCOMM INC,2.930486
44342,TIGER 글로벌자율주행&전기차SOLACTIVE,US02079K3059,ALPHABET INC-CL A,2.869684
44318,TIGER 글로벌자율주행&전기차SOLACTIVE,JP3633400001,TOYOTA MOTOR CORP,2.808817
43543,KODEX 자율주행액티브,KR7012330007,현대모비스,8.590932
43570,KODEX 자율주행액티브,KR7307950006,현대오토에버,7.626326
43529,KODEX 자율주행액티브,KR7000660001,SK하이닉스,5.967903
43556,KODEX 자율주행액티브,KR7086280005,현대글로비스,4.925796
43531,KODEX 자율주행액티브,KR7005380001,현대차,4.391058
46626,ACE 글로벌자율주행액티브,US67066G1040,NVIDIA Corp,9.219579
46629,ACE 글로벌자율주행액티브,US88160R1014,TESLA MOTORS,8.094959
46611,ACE 글로벌자율주행액티브,CNE100001526,(선)BYD CO LTD -A,7.761908
46624,ACE 글로벌자율주행액티브,US25460G2865,Direxion Daily TSLA Bull 2X Sh,6.847424
46622,ACE 글로벌자율주행액티브,US0420682058,ARM Holdings PLC,4.973885

In [13]:
ETF_df_task_4[ETF_df_task_4['ETF 종목명'].str.contains('금융')]

,ETF 종목명,구성종목 표준코드,구성종목 종목명,편입비율
34483,TIGER 25-12 금융채(AA-이상),KR6205498EC7,하나카드273,4.988738
34398,TIGER 25-12 금융채(AA-이상),KR6005273F23,아이엠뱅크46-02이12A-21,4.10297
34473,TIGER 25-12 금융채(AA-이상),KR6140178EB5,케이비국민카드421-1,3.300191
34461,TIGER 25-12 금융채(AA-이상),KR6079314EA3,JB 우리캐피탈524-1(지),2.485386
34475,TIGER 25-12 금융채(AA-이상),KR6145763DC9,BNK캐피탈338-3,2.48222
7606,TIGER 200 금융,KR7316140003,우리금융지주,7.825771
7587,TIGER 200 금융,KR7000810002,삼성화재,7.048532
7595,TIGER 200 금융,KR7032830002,삼성생명,5.727802
7607,TIGER 200 금융,KR7323410001,카카오뱅크,5.180046
7602,TIGER 200 금융,KR7138040001,메리츠금융지주,4.741424
63268,SOL 금융지주플러스고배당,KR7005940002,NH투자증권,5.574874
63270,SOL 금융지주플러스고배당,KR7071050009,한국금융지주,5.456068
63273,SOL 금융지주플러스고배당,KR7138040001,메리츠금융지주,4.724787
63274,SOL 금융지주플러스고배당,KR7138930003,BNK금융지주,3.423077
63276,SOL 금융지주플러스고배당,KR7175330000,JB금융지주,3.214653
36119,RISE 코리아금융고배당,KR7001720002,신영증권,9.789689
36130,RISE 코리아금융고배당,KR7316140003,우리금융지주,9.566045
36127,RISE 코리아금융고배당,KR7105560007,KB금융,9.41425
36123,RISE 코리아금융고배당,KR7024110009,기업은행,9.18122
36118,RISE 코리아금융고배당,KR7000810002,삼성화재,9.125524
29586,RISE 금융채액티브,KR6174147F13,우리카드259-3,6.792848
29582,RISE 금융채액티브,KR6032711EC2,신한카드2244-1,6.775031
29584,RISE 금융채액티브,KR6079315F44,JB 우리캐피탈533-5,6.765295
29580,RISE 금융채액티브,KR6008276F57,산은캐피탈767-3,6.720173
29583,RISE 금융채액티브,KR6033662E66,우리금융캐피탈503-2,5.751116
21311,RISE 200금융,KR7316140003,우리금융지주,7.848761
21292,RISE 200금융,KR7000810002,삼성화재,7.198696
21300,RISE 200금융,KR7032830002,삼성생명,5.759096
21312,RISE 200금융,KR7323410001,카카오뱅크,5.192032
21307,RISE 200금융,KR7138040001,메리츠금융지주,4.756095
3075,KODEX 미국금융테크액티브,CA82509L1076,SHOPIFY-A,9.846667
3080,KODEX 미국금융테크액티브,US0640581007,BANK OF NEW YORK MELLON CORP,9.411734
3078,KODEX 미국금융테크액티브,KYG6683N1034,NU Holdings Ltd/Cayman Islands,9.396511
3092,KODEX 미국금융테크액티브,US92826C8394,VISA INC-CLASS A SHARES,9.096284
3082,KODEX 미국금융테크액티브,US09290D1019,BLACKROCK INC,8.979381
56492,KODEX 미국S&P500금융,US46625H1005,JPMORGAN CHASE & CO,9.654794
56522,KODEX 미국S&P500금융,US92826C8394,VISA INC-CLASS A SHARES,7.900418
56500,KODEX 미국S&P500금융,US57636Q1040,MASTERCARD INC-CLASS A,5.941876
56516,KODEX 미국S&P500금융,US81369Y6059,FINANCIAL SELECT SECTOR SPDR,5.793727
56463,KODEX 미국S&P500금융,US0605051046,BANK OF AMERICA CORP,3.751882
36060,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005830005,DB손해보험,5.910951
36061,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7005940002,NH투자증권,5.140565
36062,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7016360000,삼성증권,4.771763
36066,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7071050009,한국금융지주,3.505522
36064,KODEX 금융고배당TOP10타겟위클리커버드콜,KR7039490008,키움증권,3.154331
58932,1Q 단기금융채액티브,KR6019453E35,아이비케이캐피탈301-3,4.057166
58937,1Q 단기금융채액티브,KR6095926E42,현대커머셜514-1,4.042198
58934,1Q 단기금융채액티브,KR6079316E69,JB 우리캐피탈513-2,4.041418
58938,1Q 단기금융채액티브,KR6131791DA0,연합자산관리34-1,4.039457
58939,1Q 단기금융채액티브,KR6145761DB5,BNK캐피탈333-1,4.025209

## 고객 데이터 시나리오

In [14]:
Customer_A = ETF_df_task_4[ETF_df_task_4['ETF 종목명'].isin(['ACE AI반도체포커스','ACE 2차전지&친환경차액티브','KODEX 자율주행액티브','RISE 200금융'])]

In [15]:
Customer_A = Customer_A.reset_index().drop('index',axis = 1)

In [16]:
Customer_A

             ETF 종목명     구성종목 표준코드  구성종목 종목명       편입비율
0         RISE 200금융  KR7316140003    우리금융지주   7.848761
1         RISE 200금융  KR7000810002      삼성화재   7.198696
2         RISE 200금융  KR7032830002      삼성생명   5.759096
3         RISE 200금융  KR7323410001     카카오뱅크   5.192032
4         RISE 200금융  KR7138040001   메리츠금융지주   4.756095
5      KODEX 자율주행액티브  KR7012330007     현대모비스   8.590932
6      KODEX 자율주행액티브  KR7307950006    현대오토에버   7.626326
7      KODEX 자율주행액티브  KR7000660001    SK하이닉스   5.967903
8      KODEX 자율주행액티브  KR7086280005    현대글로비스   4.925796
9      KODEX 자율주행액티브  KR7005380001       현대차   4.391058
10      ACE AI반도체포커스  KR7000660001    SK하이닉스  25.755918
11      ACE AI반도체포커스  KR7005930003      삼성전자  24.736614
12      ACE AI반도체포커스  KR7042700005     한미반도체  24.473018
13      ACE AI반도체포커스  KR7140860008    파크시스템스   1.519344
14      ACE AI반도체포커스  KR7000990002     DB하이텍   1.517061
15  ACE 2차전지&친환경차액티브  KR7012330007     현대모비스    8.46777
16  ACE 2차전지&친환경차액티브  KR7005380001       현대차    8.23665
17  ACE 2차전지&친환경차액티브  KR7000270009        기아   8.090785
18  ACE 2차전지&친환경차액티브  KR7005490008  POSCO홀딩스   7.842668
19  ACE 2차전지&친환경차액티브  KR7373220003  LG에너지솔루션   7.376414

In [17]:
cus_news = duckdb.connect('../DB/Customer_news.db')

In [18]:
cusA_news_df = cus_news.execute('select * from articles').fetch_df()
cus_news.close()

In [19]:
cusA_news_df.head(5)

,header,summary,content,url,datetime,ticker
0,"18일, 거래소 외국인 순매수상위에 전기,전자 업종 4종목",None,"외국인 투자자는 18일 거래소에서 삼성전자, NAVER, 크래프톤 등을 중점적으로 ...",https://www.hankyung.com/article/202506184343L,2025.06.18 18:35,우리금융지주
1,"""실적·주주환원 훈풍""…은행·증권주 신고가 행진, 스탁론 매수세도 유입",None,국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가...,https://www.hankyung.com/article/202507096279a,2025.07.09 10:30,우리금융지주
2,"12일, 외국인 거래소에서 한화에어로스페이스(+5.3%), 현대차(+0.25%) 등...",None,"외국인 투자자는 12일 거래소에서 한화에어로스페이스, 현대차, 현대건설 등을 중점적...",https://www.hankyung.com/article/202506121791L,2025.06.12 18:35,우리금융지주
3,"금감원, 우리금융 경평 '2→3등급' 결론…이번주 통보할 듯",None,금감원 / 사진=노정동 기자\n\n 금융감독원이 우리금융...,https://www.hankyung.com/article/2025031784556,2025.03.17 11:18,우리금융지주
4,한도 초과 걱정 없이 연 4%대 금리로 저점 집중투자 시작하기!,None,부자네스탁론이 특별 이벤트로 5년고정 연 4.9%의 저금리 스탁론 상품을 출시하면서...,https://www.hankyung.com/article/202506056123a,2025.06.05 14:38,우리금융지주

In [20]:
cusA_news_df.shape

(10000, 6)

## 날짜 전처리

In [21]:
cusA_news_df['Date'] = cusA_news_df.datetime.str[:10]
cusA_news_df = cusA_news_df.drop('datetime',axis=1)

In [22]:
cusA_news_df['Date'] = pd.to_datetime(cusA_news_df['Date'])
# 2. 기준일 계산 (오늘 날짜 - 5일)
today = pd.to_datetime("2025-07-30")
five_days_ago = today - timedelta(days=30)

# 3. 최근 5일치 필터링
recent_news_df = cusA_news_df[cusA_news_df['Date'] >= five_days_ago]

In [23]:
recent_news_df= recent_news_df.drop_duplicates()

In [24]:
# 최근 30일치 뉴스 기사 필터링 시 남아있는 뉴스 기사 개수
recent_news_df.groupby('ticker').count()

          header  summary  content  url  Date
ticker
DB하이텍         30        4       30   30    30
LG에너지솔루션     500       96      500  500   500
POSCO홀딩스     464       23      464  464   464
SK하이닉스       500      119      500  500   500
기아           411      191      411  411   411
메리츠금융지주       51        5       51   51    51
삼성생명         140       45      140  140   140
삼성전자         500      161      500  500   500
삼성화재          96       31       96   96    96
우리금융지주       153       46      153  153   153
카카오뱅크        117       17      117  117   117
파크시스템스        26        1       26   26    26
한미반도체        228       43      228  228   228
현대글로비스        53       15       53   53    53
현대모비스        116       27      116  116   116
현대오토에버        19        3       19   19    19
현대차          500      178      500  500   500

## VectorDB 저장

- 진행한 종목 : 우리금융지주, 삼성전자

In [25]:
# 4. OpenAI 임베딩 모델 로딩
embedding = OpenAIEmbeddings(model="text-embedding-3-large")

persist_directory = "../VectorDB/chroma_news_db"

vectordb = Chroma(
    persist_directory=persist_directory,
    embedding_function=embedding
)

In [32]:
def pick_splitter_by_length(text_len: int) -> RecursiveCharacterTextSplitter:
    """
    뉴스 본문의 길이에 따라 적절한 텍스트 분할기를 반환합니다.
    """
    if text_len <= 1200:
        # 짧은 기사 → 굳이 자르지 않고 1덩어리로 처리
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=0,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 10_000:
        # 중간 길이 → 일반적인 1,200자 기준으로 분할
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=150,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 50_000:
        # 긴 기사 → 덩어리를 좀 더 키움
        return RecursiveCharacterTextSplitter(
            chunk_size=1800,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )
    else:
        # 초장문 → 더 크게 자르되, 요약도 고려 (이건 후속 처리 필요)
        return RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )

In [33]:
# 2. 문서 리스트 생성 (chunk + metadata 포함)
def make_documents(df):
    docs = []

    for idx, row in df.iterrows():
        text = row["content"]
        splitter = pick_splitter_by_length(len(text))
        chunks = splitter.split_text(text)

        for i, chunk in enumerate(chunks):
            metadata = {
                "title": row["header"],
                "url": row["url"],
                "Date": row["Date"],
                "ticker": row.get("ticker", "None"),
                "chunk_idx": i,
                "original_idx": idx,
            }
            docs.append(Document(page_content=chunk, metadata=metadata))

    return docs

In [34]:
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max()
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

In [35]:
def make_doc_id(d: Document) -> str:
    """
    url + chunk_idx(없으면 0) 조합으로 안정적인 고유 id 생성
    """
    base = f"{d.metadata.get('url','')}_{d.metadata.get('chunk_idx', 0)}"
    return md5(base.encode("utf-8")).hexdigest()

def chunks(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

In [36]:
recent_df_woori = get_recent_articles(cusA_news_df,ticker='삼성전자',days = 30)
recent_df_woori['Date'] = recent_df_woori.Date.astype('str')
recent_df_woori_docs = make_documents(recent_df_woori)
BATCH = 64  # 상황에 맞게 조절

for docs in tqdm(chunks(recent_df_woori_docs, BATCH), total=(len(recent_df_woori_docs) + BATCH - 1) // BATCH):

    ids = [make_doc_id(d) for d in docs]
    vectordb.add_documents(documents=docs, ids=ids)

100%|██████████| 15/15 [00:37<00:00,  2.47s/it]

In [43]:
len(recent_df_woori_docs)

219

In [37]:
print("Number of documents in DB:", vectordb._collection.count())

Number of documents in DB: 1139

## cross-encoder 모델(w/langchain 예시)

In [27]:
retriever = vectordb.as_retriever(search_kwargs={"k": 30,'filter' : {'ticker' : '삼성전자'}})

In [28]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i + 1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

In [29]:
query = '''
이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.
'''
docs = retriever.invoke(query)
pretty_print_docs(docs)

Document 1:

플랙트(공조), 마시모(오디오), 젤스(헬스케어) 등 여러 인수합병을 진행했습니다.앞으로도 M&A를 통해 급변하는 글로벌 기술 트렌드에 대응하겠다면서 AI, 공조, 메디텍, 전장 등 신성장 분야의 후보 업체들을 검토 중이라고 설명했습니다. 사업 경쟁력 강화와 사업 규모를 확대하기 위해 비슷한 분야의 업체들을 추가로 인수할 가능성을 내비친 것으로 보입니다.또한 삼성은 올해 상반기 미래 신기술, 우수 기술업체 발굴을 위해 약 40여개 업체에 1억2,000만 달러(1,700억원) 이상을 벤처 투자했다고 강조했습니다.지난 29일에는 국내 AI 반도체 기업인 리벨리온이 삼성 계열사로부터 대규모 투자를 받았다고 발표하기도 했습니다.이재용 회장이 사법리스크 해소로 '뉴삼성' 구축에 속도를 내고 있는 가운데, 지난 2017년 하만과 같은 초대형 M&A도 기대되고 있습니다.<앵커>잘 들었습니다.홍헌표기자 hphong@wowtv.co.kr
----------------------------------------------------------------------------------------------------
Document 2:

자사주 소각, 이재용 회장의 사법 리스크 해소 등 여러 호재에도 불구하고 삼성전자 주가는 줄곧 6만 원대에 머물렀다.삼성전자가 사실상 ‘잠든 상태’에서도 코스피는 크게 올랐다. 그렇다면 삼성전자가 본격적으로 기지개를 켠다면 어떨까.지난 28일 삼성전자는 테슬라와의 납품 계약, 이른바 ‘23조 잭팟’ 소식에 주가가 7만 원대를 회복했다. 전문가들은 “삼성전자의 반등이야말로 코스피 5000 돌파의 열쇠”라고 진단한다.삼성전자가 지수를 실질적으로 견인하려면 주가는 얼마나 올라야 할까. 삼성전자의 시가총액은 7월 24일 기준 약 390조원이다.2021년 고점(주가 약 9만1000원) 당시에는 약 540조원에 달했다. 단순 계산으로 지수 3300에서 5000까지 51% 오르려면, 삼성전자 역시 현재 주가에서 9만원 이상으로 회복해야 한다는 계산이 나온다.삼성전자와 함께 주가를 견인할 신흥 대장주도 필요하다. 기준은 명확하다. 시가총액이 크고 기관·외국인 수급이 몰리며 정부 정책이나 글로벌 산업 트렌드를 타야 한다. 2025년 7월까지의 상승률 상위 종목 중에는 한화에어로스페이스, LIG넥스원, 두산에너빌리티, SK하이닉스, POSCO홀딩스 등이 후보로 꼽힌다. 이들은 정책, 실적, 수급, 산업 구조 재편이라는 4박자를 동시에 갖춘 기업들이다.정채희 기자 poof34@hankyung.com
----------------------------------------------------------------------------------------------------
Document 3:

삼성전자가 올해 하반기 확장현실(XR) 헤드셋(사진), 두 번 접는 ‘트리폴드폰’ 등 신제품을 출격시킨다. 인공지능(AI), 메디테크(의료기술), 냉난방공조(HVAC) 등 신사업을 강화하기 위해 추가 인수합병(M&A)도 추진한다.31일 삼성전자에 따르면 갤럭시 스마트폰 등 모바일 기기를 담당하는 모바일경험(MX)사업부는 올 2분기 매출 29조2000억원, 영업이익 3조1000억원을 기록했다. 1년 전보다 매출은 6.6%, 영업이익은 39% 늘었다. 갤럭시 S25 시리즈 등 프리미엄 제품과 갤럭시탭 10 시리즈 등 태블릿PC 판매가 늘어난 영향이다.삼성전자는 7월 출시한 갤럭시 Z폴드7·플립7 등 폴더블 신제품 판매를 늘리고 갤럭시 S25 시리즈의 마케팅을 강화해 3분기 실적을 끌어올릴 계획이다. XR 헤드셋, 트리폴드폰 등 차세대 혁신 제품을 올 연말까지 출시한다고 공개했다. 다니엘 아라우호 MX사업부 상무는 “구글과의 협력으로 구축한 XR 생태계를 기반으로 AI 기능을 적용한 헤드셋을 통해 갤럭시 제품군 경쟁력을 높일 것”이라고 말했다.삼성전자는 AI 기능을 적용한 TV와 가전 판매를 늘리는 동시에 미래 성장 동력으로 낙점한 HVAC 사업을 적극 키운다는 전략을 세웠다. 삼성전자는 HVAC 사업 확대를 위해 지난 5월 2조4000억원을 들여 독일 HVAC 기업인 플랙트그룹을 사들였다. 한인택 삼성전자 생활가전(DA)사업부 상무는 “지난해 7월 설립한 미국 레녹스와의 합작사, 플랙트그룹 등과 결합해 데이터센터 및 상업용 시장 공략에 나설 것”이라고 말했다.삼성전자는 올해 플랙트그룹과 함께 미국 마시모 오디오사업부, 미국 디지털 헬스케어 회사 젤스 등 세 차례에 걸쳐 M&A 소식을 발표하며 잠잠하던 M&A 엔진을 재가동했다. 박순철 삼성전자 경영지원실장(CFO)은 “다양한 신성장 분야의 후보 업체를 검토 중”이라며 추가 M&A를 예고했다. 신성장 분야는 AI, 공조, 메디테크, 로봇, 전장, 핀테크, 부품 등이다.김채연 기자 why29@hankyung.com
----------------------------------------------------------------------------------------------------
Document 4:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 한화오션 두산테스나 NHN 원익IPS
----------------------------------------------------------------------------------------------------
Document 5:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.에이디테크놀로지 LG씨엔에스 NAVER 동진쎄미켐 한선엔지니어링
----------------------------------------------------------------------------------------------------
Document 6:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 SK하이닉스 삼성전기 LG이노텍 삼성에스디에스
----------------------------------------------------------------------------------------------------
Document 7:

삼성전자 서초사옥의 삼성 깃발. 뉴스1
----------------------------------------------------------------------------------------------------
Document 8:

※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.





                투자수익률 상위 1％ 고수들이 4일 오전 삼성전자를 집중 매수하고 있다. 반면 두산에너빌리티는 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 삼성전자, 한화엔진, HD한국조선해양 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％ 투자자의 매매동향을 취합한 결과다.오전 10시 현재 삼성전자가 7만50원으로 이전 거래일보다 1.67% 올랐다. 앞서 삼성은 미국 전기차업체 테슬라와 165억달러(약 23조원) 규모의 인공지능(AI) 반도체 공급 계약을 체결했다고 지난달 28일 공시했다. 김영건 미래에셋증권 연구원은 지난 1일 보고서에서 이번 계약 관련, “AI 빅테크로부터 기술력을 공식 인정받은 사례”라며 “고대역폭메모리(HBM) 사업 부진도 단숨에 시간 문제로 전략했다”고 호했다. 지난달 31일 한국산 제품에 대한 미국의 상호관세율(15%) 확정도 불확실성 완화에 기여했다.한화엔진은 3만5300원으로 0.43% 상승했다. 한화엔진은 지난 2분기 338억원의 영업이익을 냈다고 지난달 24일 발표했다. 전년 동기 대비 81.4% 증가한 규모다.





                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 두산에너빌리티, 에이치브이엠, 파마리서치 순이다. 주가는 각각 직전 거래일 대비 4.89%, -13.53%, 0.54% 변동했다.에이치브이엠은 우주항공 등 미래산업용 특수금속을 만드는 회사로 급등 후 차익실현 매물이 쏟아지고 있다. 지난 1일에는 일론 머스크 테슬라 CEO의 스페이스X와 제품 공급계약을 체결했다고 밝히면서 상한가로 직행했다.





                이태호 기자 thlee@hankyung.com
----------------------------------------------------------------------------------------------------
Document 9:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.SK하이닉스 카카오페이 다날 한화시스템 솔브레인
----------------------------------------------------------------------------------------------------
Document 10:

반도체 소부장(소재·부품·장비) 관련주가 일제히 급등했다. 삼성전자가 테슬라의 차세대 인공지능(AI) 칩을 수탁생산한다는 소식에 수혜 기대가 커지면서다.





                30일 한국거래소에 따르면 최근 3거래일 동안 KRX 반도체지수는 3% 넘게 올랐다. 전체 KRX지수 중 세 번째로 높은 상승률이다. 특히 반도체 장비 제조사 원익IPS 주가는 같은 기간 21.2% 급등했다. 반도체용 식각액 공급 업체 솔브레인과 후공정 업체인 두산테스나 주가도 각각 23.6%, 24.4% 뛰었다.삼성전자 공급망에 속한 소부장 종목의 상승세가 두드러졌다는 평가가 나온다. 테슬라의 자율주행 차량과 휴머노이드 로봇에 들어가는 차세대 AI칩 생산을 삼성전자가 맡기로 하면서다. 2033년까지 22조7647억원어치를 공급하는 삼성 반도체 역사상 최대 규모 계약이다.반도체 소부장주를 집중 매수하는 세력은 주로 기관투자가다. 3거래일간 원익IPS를 126억원어치 사들였다. 같은 기간 솔브레인도 192억원어치 순매수했다. 반도체 소부장주 주가가 올 들어서도 지지부진하자 투자 매력이 더 높아졌다는 게 증권가 해석이다. 주요 반도체 소부장주는 2021년 고점 대비 40~50%가량 조정받은 상태다. 운용사 관계자는 “반도체 소부장주의 기관 수급이 빈 상황에서 삼성전자의 테슬라 수주 소식이 나오자 매수세가 강하게 들어왔다”며 “반도체 소부장주의 밸류에이션(실적 대비 주가 수준) 매력이 높다”고 진단했다.증권가에서는 반도체 소부장주 상승세가 하반기에도 이어질 것으로 전망했다. 대신증권은 원익IPS와 솔브레인을 삼성전자 대규모 수주에 따른 대표적 수혜주로 제시했다.삼성증권은 두산테스나와 하나마이크론을 주목했다. 추후 삼성전자의 파운드리(반도체 수탁생산) 가동률이 높아지면 수혜를 볼 것으로 봤다. 이종욱 삼성증권 연구원은 “파운드리 가동률이 전반적으로 올라가면 이들 종목이 우선 주목받을 것”이라고 전망했다. 시장에선 삼성전자가 테슬라 물량을 내년 2분기부터 본격 생산할 것으로 보고 있다. 현재 짓고 있는 미국 텍사스 테일러 공장이 생산지다.류은혁 기자 ehryu@hankyung.com
----------------------------------------------------------------------------------------------------
Document 11:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.두산에너빌리티 NHN KCP 풀무원 펩트론 한텍
----------------------------------------------------------------------------------------------------
Document 12:

삼성전자, 올해 2분기 실적 발표




삼성전자 서초사옥./한국경제 이솔 기자삼성전자 반도체 사업이 올해 2분기 4000억원의 영업이익을 거두면서 적자를 면했다. 작년 2분기 6조 4000억원대 영업이익과 비교하면 94% 급감한 수준이다. 2조원대 적자를 기록한 2023년 4분기 이후 역대 최저치다. 삼성전자 측은 "재고자산 평가 충당금 등 일회성 비용이 반영되면서 실적이 하락했다"고 했다.삼성전자는 연결기준으로 올해 2분기 매출 74조6000억원, 영업이익 4조7000억원을 각각 기록했다고 31일 공시했다. 전체 매출은 전년 동기 대비 0.67% 늘었지만, 영업이익은 55.23% 급감했다. 삼성전자는 지난 8일 이같은 수준의 잠정실적을 발표했고, 이날 확정실적을 공시했다. 이번 실적은 당초 시장 눈높이를 밑도는 수준이다.반도체 사업을 담당하는 DS(Device Solutions) 부문의 매출은 27조 9000억 원, 영업이익은 4000억 원을 기록했다.삼성전자는 메모리에서 HBM3E와 고용량 DDR5제품 판매 비중을 확대해 서버 수요가 증가했고 파운드리는 전 분기 대비 11%의 매출 성장이 있었다고 밝혔다. 영업이익은 매출 성장에도 불구하고, 메모리 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향에 따른 재고 충당 발생으로 감소했다고 설명했다.가전과 TV, 모바일 등을 포함한 디바이스경험(DX) 부문은 매출 43조 6000억 원, 영업이익 3조3000억 원을 기록했다. 스마트폰 신모델 출시 효과 감소와 TV 시장의 경쟁 심화로 전 분기 대비 매출이 16% 감소했고 영업이익도 1조4000억 원 감소했다.또한 원달러 환율이 하락하면서 달러 거래 비중이 높은 부품 사업을 중심으로 전분기 대비 약 5000억 원 수준의 부정적 영향이 있었다고 했다.김영은 기자 kye0218@hankyung.com
----------------------------------------------------------------------------------------------------
Document 13:

파운드리의 적자가 꼽힌다. 지난 3월까지만 해도 업계에서는 “삼성전자가 자사 AP 공정 수율도 잡지 못하는 상황에서 다른 빅테크의 수주를 따올 수 있겠냐”는 지적이 나왔다. 반면 파운드리 1위인 TSMC는 주요 빅테크의 물량을 싹쓸이하며 역대급 실적을 기록했다. 시장조사업체 트렌드포스에 따르면 올해 1분기 파운드리 시장 점유율은 TSMC 67.6%, 삼성전자 7.7%였다. 중국 SMIC는 6%로 삼성전자를 턱밑까지 추격했다. 증권가에선 2분기 실적 발표 이후 삼성전자 파운드리 사업부가 글로벌 빅테크를 비롯한 신규 거래선을 확보해 영업적자를 해소할 것으로 전망한 바 있다. 박유악 키움증권 연구원은 지난 21일 보고서를 통해 "삼성전자의 반도체 부문 기술 경쟁력 회복을 예상한다"며 "내년 애플 아이폰18용 이미지센서(CIS) 양산, 테슬라 등 신규 거래선 확보를 통해 영업적자의 폭을 축소시켜 나갈 전망"이라고 했다.시장에서는 이번 대규모 공급계약을 주가 반등의 신호탄으로 해석했다. 대규모 공급계약 공시로 이날 삼성전자의 주가는 3.4% 오른 6만8200원에 거래를 시작했다.김영은 기자 kye0218@hankyung.com
----------------------------------------------------------------------------------------------------
Document 14:

<앵커>주요 산업들의 업황을 가장 빠르게 확인하는 시간,키워드나우,한경에이셀 박이경 애널리스트와 함께 합니다.지난 주 검색량 52주 최고치 기록한 키워드 살펴볼가요<박이경 연구원>지난 주에도 많은 키워드들이 부각이 됐던 한 주였습니다. 먼저 기아와 지난 주 K라면 말씀드렸는데, 삼양식품 불닭, 농심의 신라면에 대한 검색이 또 52주 내 신고점을 기록했습니다.또 농심, 빙그레, 삼성전자의 갤럭시, 지누스도 검색량이 많이 증가했던 모습이었고요.풀무원이 김밥 관련해서 주목을 받았던 한 주였는데, 풀무원에 대한 검색도 많이 늘었습니다. 또 롯데쇼핑의 롯데마트, 동서의 맥심커피, KT&G의 릴플러스도 검색량 신고점에 달하는 걸 확인할 수 있었습니다.릴플러스가 궐련형전자담배 기기라면 에쎄는 일반담배 종류은데, 에쎄 담배에 대한 검색량도 늘었던 모습이고요. 카카오의 카카오톡, CJ ENM의 티빙, 인바디도 리스트에 들어왔습니다.또 LG전자의 세탁기도 검색량이 늘었고요. 에이블씨엔씨의 어퓨의 경우엔 매각 뉴스가 나오면서 검색이 많이 된 것 같더라고요. 다른 기초 화장품 브랜드로는 아모레퍼시픽의 코스알엑스, 네오팜의 리얼베리어가 눈에 띄었습니다.미용기기에서는 슈링크로 유명한 클래시스의 볼뉴머가 검색량이 많이 늘었는데요, 좀 찾아보니까 러시아 쪽에서 검색이 증가한 걸로 보였습니다.색조화장품에서는 클리오의 페리페라가, 게임에서는 크래프톤의 펍지, 엔터에서는 하이브의 투어스가 검색량 신고점을 경신했습니다.유튜브에서는 구글에서와 마찬가지로 삼양식품의 불닭이 다시한번 검색량 상승랠리가 나타나고 있었고요. 농심의 신라면도 함께 검색이 또 늘었습니다. 마지막으로 가전제품 쪽에서는 삼성전자의 티비와 쿠쿠홀딩스의 쿠쿠를 소비자들이 많이 찾은 걸로 보였습니다.<앵커>삼성 갤럭시Z폴드7 검색량이 눈에 띕니다.신제품이 나와서 그런건가요?<박이경 연구원>이번 검색량 급증은 단순한 신제품 발표 이상의 의미가 있어요.지난 7월 9일에 삼성 갤럭시 Z 폴드7이 공개됐었습니다. 지난 25일에 정식 출시가 됐었고요.올해 폴드7은 전작들과는 달리, 하드웨어 사양보다는 소프트웨어와 AI 기능 중심의 마케팅으로 방향을 전환했어요.대표적으로 ‘삼성 노트 AI 요약’, ‘음성통화 중 실시간 통역’, ‘AI 기반 화면분할 자동화’ 같은 기능이 공개되면서 글로벌 언론에서도 접히는 스마트폰이 더 이상 기술 과시가 아니라 실사용 중심으로 진화했다는 평가를 받았던 부분이
----------------------------------------------------------------------------------------------------
Document 15:

삼성전자의 주가가 최근 약세를 벗고 반등세를 보이기 시작했다. 가장 큰 촉매는 최고경영진의 법적 불확실성 제거로, 이재용 회장이 최종 무죄 판결을 받으며 경영 전면에 나설 수 있는 기틀이 마련됐다는 점이다. 이 소식이 전해진 직후 주가는 즉각 반등했으며, 투자자들은 경영 안정성과 전략 재정비 기대감을 반영했다.또한 최근 사상 최대 규모인 약 165억 달러에 달하는 파운드리(위탁생산) 계약 체결 소식이 주가 상승의 실질적 동력을 제공했다. 계약의 상대방과 조건은 장기간 비공개로 유지되지만, 대외 수익성과 기술력에 대한 기대가 급격히 증가하며 증권 시장에서 긍정적인 반응을 끌어냈다.여기에 AI 반도체 수요 기대도 맞물렸다. 글로벌 AI 프로젝트에서 핵심적인 역할을 하는 고대역폭 메모리(HBM) 매출 증가 기대와 함께 삼성의 파운드리 경쟁력에 대한 인식이 강해지면서, 투자심리가 개선되었다.






외국인 투자자의 매수세도 뒤따랐다. 낮은 밸류에이션과 저가 매수 흐름 속에서 글로벌 자금이 유입되며 기술주 랠리를 견인했고, 삼성전자도 그 수혜 종목으로 이름을 올렸다.기대와 달리 2분기 실적은 아직 약점으로 작용하고 있다. 미국과 중국 간 기술·무역 리스크로 인해 AI 메모리 칩 수요가 지연되며 이익이 큰 폭 감소할 전망이다. 특히 엔비디아 인증 지연과 중국 수출 제한이 삼성의 성장성 회복에 제약을 주고 있다는 분석이 나온다.그러나 법률 리스크 해소와 대규모 수주 계약, 그리고 AI 메모리 및 파운드리 영역에서의 중장기 성장 기대가 투자자 심리에 긍정적으로 작용하며 주가 흐름에 방향성을 부여하고 있다는 해석이 나온다. 다만 경쟁사 대비 기술적 우위 확보 여부, 수주 계약의 실제 실현 가능성, 글로벌 공급망 환경 변화 등에 대한 면밀한 관찰이 필요한 시점이다.한화엔진, LIG넥스원, 이렘, 다날, KB금융무료상담
----------------------------------------------------------------------------------------------------
Document 16:

한경유레카는 AI알고리즘들의 개별 종목 투자의견(점수)을 한눈에 볼 수 있는 투자 플랫폼입니다. '한경유레카' 앱을 내려받으면 종목별 투자의견과 나에게 맞는 AI알고리즘을 추천받을 수 있습니다.





                28일 삼성전자가 강세다. 삼성전자는 오후 13시 50분 전일대비 5.1% 오른 6만9400원에 거래되며 7만전자를 코앞에 두고 있다.삼성전자가 마지막으로 7만원 대에 장을 마감한 것은 지난해 9월이 마지막이다.당일 삼성전자는 공시를 통해 반도체 위탁생산 공급계약 소식을 전했다. 글로벌 대형기업과 약 22조 7600억원 규모의 계약으로 계약기간은 2025년 7월 24일부터 2033년 12월 31일까지이다.AI알고리즘들의 투자의견을 모아 종합의견을 제시하는 한경유레카는 삼성전자에 대해 7월 17일 매수의견을 제시한바 있다.한경유레카에서는 관심 종목을 등록하면 AI알고리즘들의 종합의견을 무료로 확인할 수 있으며 매매의견이 변동되면 오전 8시 30분에 앱을 통해 알림 서비스를 제공한다.한경닷컴 뉴스룸 open@hankyung.com
----------------------------------------------------------------------------------------------------
Document 17:

07월 28일 삼성전자(005930)는 수주공시를 발표했다.◆삼성전자 수주공시 개요- 반도체 위탁생산 공급계약 22.76조 (매출액대비  7.6 %)삼성전자(005930)는 반도체 위탁생산 공급계약에 관한 단일판매ㆍ공급계약체결              을 28일에 공시했다.계약 상대방은 글로벌 대형기업이고, 계약금액은 22.76조 규모로 최근 삼성전자 매출액 300.87조 대비 약  7.6 % 수준이다. 이번 계약의 기간은 2025년 07월 24일 부터 2033년 12월 31일까지로 약 8년 5개월이다.한편 이번 계약수주는 2025년 07월 26일에 체결된 것으로 보고되었다.




차트

                한편, 오늘 분석한 삼성전자는 글로벌 IT기업으로 알려져 있다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.
----------------------------------------------------------------------------------------------------
Document 18:

사진=연합뉴스

삼성전자 주가가 5% 넘게 강세를 나타내고 있다. 22조원 규모의 반도체 위탁생산 계약 상대가 미국 전기차 업체 테슬라로 밝혀지자 투자심리에 불이 붙은 모습이다.28일 오후 2시 현재 삼성전자는 전 거래일 대비 3600원(5.46%) 뛴 6만9500원에 거래되고 있다. 주가는 장중 6만9700원까지 치솟으며 7만원대 탈환을 시도하고 있다. 장중 기록한 6만9700원은 연중 최고가이기도 하다.대규모 공급계약 소식에 매수세가 몰렸다. 이날 오전 삼성전자는 22조7648억원 규모의 반도체 위탁생산 공급계약을 체결했다고 공시했다. 지난해 연간 매출 300조8709억원의 7.6%에 달한다. 계약 기간은 이달 24일부터 2033년 12월31일까지로 수주 일자는 지난 26일이다. 다만 구체적 계약상대방은 '경영상 비밀유지'를 이유로 공개하지 않았다.공급계약 소식에 장 초반 삼성전자는 3%대 강세를 보였다. 이런 상황에서 삼성전자의 계약 상대가 테슬라로 밝혀지며 상승폭이 가팔라졌다. 일론 머스크 테슬라 최고경영자(CEO)는 27일(현지시간) 이날 자신의 엑스(X·옛 트위터)를 통해 "삼성전자의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라며 "이것의 전략적 중요성은 아무리 강조해도 지나치지 않다"고 말했다.머스크는 삼성전자가 현재 AI4 칩을 생산하고 있다고 밝혔다. 대만 TSMC는 설계가 막 마무리된 AI5 칩을 우선 대만에서 생산하고, 애리조나에서 만들 것이라고 머스크는 전했다.




사진=일론 머스크 테슬라 CEO 엑스
----------------------------------------------------------------------------------------------------
Document 19:

설계를 최적화 해 HBM3E 대비 성능과 효율을 크게 개선했다면서 내년에는 HBM4의 수요가 급증할 것으로 보고 수요에 맞춰 적기에 공급하겠다고 말했습니다.다만 시장에서 우려하는 HBM3E의 수익성은 예상대로 하락할 것으로 보고 있지만 중장기적으로 AI 관련한 HBM 수요는 증가할 것이기 때문에 큰 문제는 없다고 밝혔습니다.특히 향후 수익성이 커질 것으로 보이는 HBM4 개발에 더 집중하겠다는 뜻을 내비쳤습니다.<앵커>지난 28일 삼성전자가 테슬라와 23조원 규모의 파운드리 계약을 맺었습니다. 대규모 계약에 8년 계약을 한 만큼 파운드리 경쟁력이 높아진 것 같은데, 추가로 대형 수주도 기대해도 됩니까?<기자>매 분기 조 단위 적자를 기록하면서 애물단지로 전락한 파운드리 사업부가 테슬라 수주로 분위기 반전에 성공했습니다.삼성은 이번 테슬라 계약을 기점으로 향후 대형 고객 추가 수주가 기대된다면서 미국 테일러 공장의 안정적인 팹 가동이 전망된다고 밝혔습니다.그동안 고객 확보에 어려움을 겪어 공장 가동이 불투명했는데, 이번 수주가 새로운 고객 유치에도 도움이 될 것이라는 겁니다.특히 미국 내 빅테크 고객을 확보해 테일러 공장을 내년부터 본격 가동하겠다고 말했습니다.또한 이번 테슬라의 AI칩인 'AI6'는 2나노 공정으로 생산되는데, 삼성은 2나노 공정 경쟁력을 확보해 대형 고객사 수주 확대가 가능할 것이라고 내다봤습니다.앞으로도 선단 공정 경쟁력을 강화하고, 2나노 성능과 성숙도를 높여 글로벌 고객을 유치하겠다는 전략입니다.시스템 LSI 사업부가 설계하는 모바일 AP인 '엑시노스 2600'도 2나노 공정으로 개발 중인데, 성능이 대폭 개선돼 내년초 갤럭시 S26 시리즈에 탑재하는 것도 고려 중이라고 밝혔습니다.<앵커>삼성이 올해 상반기 헬스케어, 공조 등 신성장 분야에서 여러가지 M&A를 진행했습니다. 이재용 회장이 사법리스크를 털어낸 만큼 초대형 M&A도 기대가 되는데, 추가 M&A 전망은 어떻습니까?<기자>삼성은 컨퍼런스콜에서 AI와 공조, 로봇 등 신성장 분야에서 추가 M&A를 검토하고 있다고 밝혔습니다.삼성은 지난해말부터 레인보우로보틱스(로봇), 플랙트(공조), 마시모(오디오), 젤스(헬스케어) 등 여러 인수합병을 진행했습니다.앞으로도 M&A를 통해 급변하는 글로벌 기술 트렌드에 대응하겠다면서 AI, 공조, 메디텍, 전장 등 신성장 분야의 후보 업체들을 검토 중이라고 설명했습니다. 사업 경쟁력 강화와 사업
----------------------------------------------------------------------------------------------------
Document 20:

가동 속도조절에 들어갔습니다.이번 테슬라 수주기간이 2033년까지 8년인데, 장기 고객을 확보하면서 한숨 돌릴 수 있게 됐습니다.테일러 공장은 4나노 이하 최첨단 공정이 가능하고 추후 2나노 양산도 준비 중인데, 이번 테슬라 AI6 생산은 2나노와 4나노로 진행될 전망입니다.삼성은 그동안 3나노 이하 공정에서 TSMC에 밀리는 모습이었는데, 이번에 2나노에서 경쟁력을 입증한다면 추가 빅테크 수주로 이어질 것이라는 분석입니다.<앵커>이재용 삼성전자 회장이 지난 17일 사법리스크를 완전히 해소했습니다. 이 회장이 복귀하자마자 대규모 계약소식이 전해지면서 이른바 '뉴삼성'에 대한 기대감도 커지고 있죠?<기자>이재용 회장이 지난 17일 대법원에서 최종 무죄가 확정되면서 10년 가까이 따라다녔던 사법리스크를 떨쳐냈습니다.삼성전자는 이 회장 2심 무죄 이후 전장과 공조, 헬스케어 기업을 잇따라 인수했습니다. 이 회장이 그리는 '뉴삼성'의 모습이 가시화되는 분위기입니다.이재용 회장은 지난 2018년 삼성의 4대 미래성장사업으로 AI와 5G, 바이오, 그리고 전장을 꼽았습니다.이번 테슬라와의 계약은 파운드리 수주로 볼 수도 있지만 이 회장이 중요하게 생각하는 전장사업의 대표적인 분야입니다.올해 초 이 회장이 시진핑 주석을 만난 뒤, 삼성전기가 중국 최대 전기차 회사인 비야디에 전장용 MLCC를 공급하게 된 것과도 맞닿아 있습니다.한편, 우리정부가 트럼프 행정부와 막판 관세협상을 진행 중인데, 2주 뒤에는 반도체 품목관세도 예고된 상황입니다.삼성그룹의 역할이 어느 때보다 중요한 상황에서 삼성이 미국 반도체 공장에 장기고객을 확보하게 된 점은 여러모로 긍정적인 소식이라는 분석입니다.<앵커>잘 들었습니다.홍헌표기자 hphong@wowtv.co.kr
----------------------------------------------------------------------------------------------------
Document 21:

사진=연합뉴스

                삼성전기가 8%대 강세를 보이고 있다. 테슬라가 삼성전자에 약 22조8000억원 규모의 AI6 반도체 위탁생산을 맡긴 데 따른 수혜가 기대된다는 분석이 나오면서다.30일 오전 9시19분 현재 삼성전기는 전일 대비 1만1300원(8.22%) 오른 14만8700원에 거래되고 있다.대신증권이 삼성전자가 테슬라에 AI6 칩을 위탁생산해 공급하는 과정에서 삼성전기의 FC-BGA 사업이 수혜를 받을 것이라는 분석을 내놓은 영향으로 보인다.박강호 대신증권 연구원은 “삼성전기는 이전에 테슬라에 공급된 반도체인 AI4와 AI5를 만드는 데 필요한 FC-BGA를 공급하고 있다”며 “이번 공급 계약으로 테슬라와 삼성전자, 그리고 삼성전기의 협력 관계가 더 강화될 것”이라고 예상했다.그는 “FC-BGA를 넘어 카메라, MLCC 등 삼성전기의 모든 사업에서 테슬라와의 관계가 구축·강화되는 중으로 판단된다”고 덧붙였다.한경우 한경닷컴 기자 case@hankyung.com
----------------------------------------------------------------------------------------------------
Document 22:

등 플래그십 중심으로 판매를 이어간다. AI가 강화된 갤럭시A 시리즈 신제품 출시로 스마트폰 시장 점유율도 확대한다. 태블릿과 웨어러블 제품의 경우 AI 기능 강화에 집중하고 확장현실(XR) 헤드셋과 트라이폴드 등 혁신 제품들을 연내 출시해 갤럭시 생태계를 확장한다. 네트워크는 신규 사업 수주와 비용 효율화를 통해 사업 경쟁력 회복을 추진한다. VD는 시청 경험이 향상된 AI TV 라인업으로 성수기 수요에 조기 대응하면서 매출을 끌어올릴 계획이다. 생활가전은 AI 가전 판매 확대와 함께 냉난방공조 등 고부가가치 제품 중심으로 사업구조를 개선한다. 또 공급지 최적화 등으로 관세 영향을 최소화한다는 방침이다. 하만은 소비자용 오디오 제품 판매를 늘리고 전장 매출을 늘려 성장세를 이어간다는 목표다. 삼성디스플레이도 중소형 부문에서 주요 고객사의 신제품 출시로 판매가 늘어날 것으로 전망된다. 대형은 안정적인 TV 패널 공급, 모니터 라인업 보강 등을 발판 삼아 QD-OLED를 확대하는 데 주력한다. 김대영 한경닷컴 기자 kdy@hankyung.com
----------------------------------------------------------------------------------------------------
Document 23:

사진=연합뉴스

                삼성전자가 28일 테슬라로부터 23조원 규모의 반도체 위탁생산(파운드리) 계약을 수주했다는 소식에 급등해 11개월 만에 '7만전자'를 회복했다.이날 오후 3시 15분 현재 코스피 시장에서 삼성전자는 전 거래일 대비 6.30% 오른 7만50원에 거래되고 있다. 삼성전자가 장중 7만원대에서 거래된 것은 지난해 9월 5일 이후 약 11개월 만이다.삼성전자는 이날 개장 전 글로벌 대형기업과 총 22조7648억원 규모의 파운드리 공급 계약을 체결했다고 공시했다.이후 계약 상대방이 테슬라임이 알려졌다. 일론 머스트 테슬라 최고경영자(CEO)는 직접 자신의 엑스(X) 계정을 통해 "삼성의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라고 밝혔다.그는 "테슬라가 생산 효율성 극대화를 돕는 것을 허용하기로 삼성이 동의했다"며 "내가 직접 진전 속도를 가속하기 위해 생산 라인을 둘러볼 것이기 때문에 이는 중요한 지점"이라고 강조했다.김수영 한경닷컴 기자 swimmingk@hankyung.com
----------------------------------------------------------------------------------------------------
Document 24:

※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.





                투자수익률 상위 1％ 고수들이 5일 오전 삼성SDI를 집중 매수하고 있다. 반면 삼성전자는 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 삼성SDI, HD현대중공업, SK바이오팜 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％ 투자자의 매매 동향을 취합한 결과다.오전 10시 현재 삼성SDI가 21만5500원으로 이전 거래일보다 11.25% 급등했다. 2차전지 종목 전반의 강세 속에 돋보이는 움직임이다. 주민우 NH투자증권 연구원은 전날 낸 2차전지 산업 월간 보고서에서 “테슬라의 실적설명회 등에서 에너지저장장치(ESS)의 견조한 수요를 재확인했다”면서 “국내 셀 업체들의 신규 수주로 이어질 전망”이라고 낙관했다.투자 고수들이 두 번째로 많이 매수한 HD현대중공업은 47만500원으로 1.51% 상승했다. 다음으로 많이 산 SK바이오팜은 예상을 웃도는 실적 발표에 힘입어 17.48% 뛰었다. SK바이오팜은 지난 2분기 매출이 전년 동기 대비 31.6% 성장한 1763억원을 기록했다고 이날 밝혔다. 영업이익은 137.6% 증가한 619억원이다.





                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 삼성전자, 삼성중공업, 두산 순이다. 주가는 각각 직전 거래일 대비 1.15%, 6.04%, 8.9% 변동했다.





                이태호 기자 thlee@hankyung.com
----------------------------------------------------------------------------------------------------
Document 25:

이재용 삼성전자 회장(왼쪽 세 번째)이 지난해 5월 미국 실리콘밸리에 위치한 삼성전자 북미 반도체연구소에서 일론 머스크 테슬라 최고경영자(CEO, 오른쪽 네 번째)와 만나 기념 촬영하고 있는 모습. 사진=삼성전자 제공


In [30]:
docs[0].metadata

{'Date': '2025-07-31',
 'ticker': '삼성전자',
 'original_idx': 5953,
 'url': 'https://www.hankyung.com/article/2025073141065',
 'title': '삼성 "HBM4 샘플 출하…품목관세는 예의주시"',
 'chunk_idx': 3}

In [31]:
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=50)
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever
)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [32]:
CrossEncoder_prompt = '''
이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [33]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt)
pretty_print_docs(compressed_docs)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Document 1:

자사주 소각, 이재용 회장의 사법 리스크 해소 등 여러 호재에도 불구하고 삼성전자 주가는 줄곧 6만 원대에 머물렀다.삼성전자가 사실상 ‘잠든 상태’에서도 코스피는 크게 올랐다. 그렇다면 삼성전자가 본격적으로 기지개를 켠다면 어떨까.지난 28일 삼성전자는 테슬라와의 납품 계약, 이른바 ‘23조 잭팟’ 소식에 주가가 7만 원대를 회복했다. 전문가들은 “삼성전자의 반등이야말로 코스피 5000 돌파의 열쇠”라고 진단한다.삼성전자가 지수를 실질적으로 견인하려면 주가는 얼마나 올라야 할까. 삼성전자의 시가총액은 7월 24일 기준 약 390조원이다.2021년 고점(주가 약 9만1000원) 당시에는 약 540조원에 달했다. 단순 계산으로 지수 3300에서 5000까지 51% 오르려면, 삼성전자 역시 현재 주가에서 9만원 이상으로 회복해야 한다는 계산이 나온다.삼성전자와 함께 주가를 견인할 신흥 대장주도 필요하다. 기준은 명확하다. 시가총액이 크고 기관·외국인 수급이 몰리며 정부 정책이나 글로벌 산업 트렌드를 타야 한다. 2025년 7월까지의 상승률 상위 종목 중에는 한화에어로스페이스, LIG넥스원, 두산에너빌리티, SK하이닉스, POSCO홀딩스 등이 후보로 꼽힌다. 이들은 정책, 실적, 수급, 산업 구조 재편이라는 4박자를 동시에 갖춘 기업들이다.정채희 기자 poof34@hankyung.com
----------------------------------------------------------------------------------------------------
Document 2:

삼성전자가 올해 하반기 확장현실(XR) 헤드셋(사진), 두 번 접는 ‘트리폴드폰’ 등 신제품을 출격시킨다. 인공지능(AI), 메디테크(의료기술), 냉난방공조(HVAC) 등 신사업을 강화하기 위해 추가 인수합병(M&A)도 추진한다.31일 삼성전자에 따르면 갤럭시 스마트폰 등 모바일 기기를 담당하는 모바일경험(MX)사업부는 올 2분기 매출 29조2000억원, 영업이익 3조1000억원을 기록했다. 1년 전보다 매출은 6.6%, 영업이익은 39% 늘었다. 갤럭시 S25 시리즈 등 프리미엄 제품과 갤럭시탭 10 시리즈 등 태블릿PC 판매가 늘어난 영향이다.삼성전자는 7월 출시한 갤럭시 Z폴드7·플립7 등 폴더블 신제품 판매를 늘리고 갤럭시 S25 시리즈의 마케팅을 강화해 3분기 실적을 끌어올릴 계획이다. XR 헤드셋, 트리폴드폰 등 차세대 혁신 제품을 올 연말까지 출시한다고 공개했다. 다니엘 아라우호 MX사업부 상무는 “구글과의 협력으로 구축한 XR 생태계를 기반으로 AI 기능을 적용한 헤드셋을 통해 갤럭시 제품군 경쟁력을 높일 것”이라고 말했다.삼성전자는 AI 기능을 적용한 TV와 가전 판매를 늘리는 동시에 미래 성장 동력으로 낙점한 HVAC 사업을 적극 키운다는 전략을 세웠다. 삼성전자는 HVAC 사업 확대를 위해 지난 5월 2조4000억원을 들여 독일 HVAC 기업인 플랙트그룹을 사들였다. 한인택 삼성전자 생활가전(DA)사업부 상무는 “지난해 7월 설립한 미국 레녹스와의 합작사, 플랙트그룹 등과 결합해 데이터센터 및 상업용 시장 공략에 나설 것”이라고 말했다.삼성전자는 올해 플랙트그룹과 함께 미국 마시모 오디오사업부, 미국 디지털 헬스케어 회사 젤스 등 세 차례에 걸쳐 M&A 소식을 발표하며 잠잠하던 M&A 엔진을 재가동했다. 박순철 삼성전자 경영지원실장(CFO)은 “다양한 신성장 분야의 후보 업체를 검토 중”이라며 추가 M&A를 예고했다. 신성장 분야는 AI, 공조, 메디테크, 로봇, 전장, 핀테크, 부품 등이다.김채연 기자 why29@hankyung.com
----------------------------------------------------------------------------------------------------
Document 3:

<앵커>주요 산업들의 업황을 가장 빠르게 확인하는 시간,키워드나우,한경에이셀 박이경 애널리스트와 함께 합니다.지난 주 검색량 52주 최고치 기록한 키워드 살펴볼가요<박이경 연구원>지난 주에도 많은 키워드들이 부각이 됐던 한 주였습니다. 먼저 기아와 지난 주 K라면 말씀드렸는데, 삼양식품 불닭, 농심의 신라면에 대한 검색이 또 52주 내 신고점을 기록했습니다.또 농심, 빙그레, 삼성전자의 갤럭시, 지누스도 검색량이 많이 증가했던 모습이었고요.풀무원이 김밥 관련해서 주목을 받았던 한 주였는데, 풀무원에 대한 검색도 많이 늘었습니다. 또 롯데쇼핑의 롯데마트, 동서의 맥심커피, KT&G의 릴플러스도 검색량 신고점에 달하는 걸 확인할 수 있었습니다.릴플러스가 궐련형전자담배 기기라면 에쎄는 일반담배 종류은데, 에쎄 담배에 대한 검색량도 늘었던 모습이고요. 카카오의 카카오톡, CJ ENM의 티빙, 인바디도 리스트에 들어왔습니다.또 LG전자의 세탁기도 검색량이 늘었고요. 에이블씨엔씨의 어퓨의 경우엔 매각 뉴스가 나오면서 검색이 많이 된 것 같더라고요. 다른 기초 화장품 브랜드로는 아모레퍼시픽의 코스알엑스, 네오팜의 리얼베리어가 눈에 띄었습니다.미용기기에서는 슈링크로 유명한 클래시스의 볼뉴머가 검색량이 많이 늘었는데요, 좀 찾아보니까 러시아 쪽에서 검색이 증가한 걸로 보였습니다.색조화장품에서는 클리오의 페리페라가, 게임에서는 크래프톤의 펍지, 엔터에서는 하이브의 투어스가 검색량 신고점을 경신했습니다.유튜브에서는 구글에서와 마찬가지로 삼양식품의 불닭이 다시한번 검색량 상승랠리가 나타나고 있었고요. 농심의 신라면도 함께 검색이 또 늘었습니다. 마지막으로 가전제품 쪽에서는 삼성전자의 티비와 쿠쿠홀딩스의 쿠쿠를 소비자들이 많이 찾은 걸로 보였습니다.<앵커>삼성 갤럭시Z폴드7 검색량이 눈에 띕니다.신제품이 나와서 그런건가요?<박이경 연구원>이번 검색량 급증은 단순한 신제품 발표 이상의 의미가 있어요.지난 7월 9일에 삼성 갤럭시 Z 폴드7이 공개됐었습니다. 지난 25일에 정식 출시가 됐었고요.올해 폴드7은 전작들과는 달리, 하드웨어 사양보다는 소프트웨어와 AI 기능 중심의 마케팅으로 방향을 전환했어요.대표적으로 ‘삼성 노트 AI 요약’, ‘음성통화 중 실시간 통역’, ‘AI 기반 화면분할 자동화’ 같은 기능이 공개되면서 글로벌 언론에서도 접히는 스마트폰이 더 이상 기술 과시가 아니라 실사용 중심으로 진화했다는 평가를 받았던 부분이
----------------------------------------------------------------------------------------------------
Document 4:

사진=연합뉴스

삼성전자 주가가 5% 넘게 강세를 나타내고 있다. 22조원 규모의 반도체 위탁생산 계약 상대가 미국 전기차 업체 테슬라로 밝혀지자 투자심리에 불이 붙은 모습이다.28일 오후 2시 현재 삼성전자는 전 거래일 대비 3600원(5.46%) 뛴 6만9500원에 거래되고 있다. 주가는 장중 6만9700원까지 치솟으며 7만원대 탈환을 시도하고 있다. 장중 기록한 6만9700원은 연중 최고가이기도 하다.대규모 공급계약 소식에 매수세가 몰렸다. 이날 오전 삼성전자는 22조7648억원 규모의 반도체 위탁생산 공급계약을 체결했다고 공시했다. 지난해 연간 매출 300조8709억원의 7.6%에 달한다. 계약 기간은 이달 24일부터 2033년 12월31일까지로 수주 일자는 지난 26일이다. 다만 구체적 계약상대방은 '경영상 비밀유지'를 이유로 공개하지 않았다.공급계약 소식에 장 초반 삼성전자는 3%대 강세를 보였다. 이런 상황에서 삼성전자의 계약 상대가 테슬라로 밝혀지며 상승폭이 가팔라졌다. 일론 머스크 테슬라 최고경영자(CEO)는 27일(현지시간) 이날 자신의 엑스(X·옛 트위터)를 통해 "삼성전자의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라며 "이것의 전략적 중요성은 아무리 강조해도 지나치지 않다"고 말했다.머스크는 삼성전자가 현재 AI4 칩을 생산하고 있다고 밝혔다. 대만 TSMC는 설계가 막 마무리된 AI5 칩을 우선 대만에서 생산하고, 애리조나에서 만들 것이라고 머스크는 전했다.




사진=일론 머스크 테슬라 CEO 엑스
----------------------------------------------------------------------------------------------------
Document 5:

07월 28일 삼성전자(005930)는 수주공시를 발표했다.◆삼성전자 수주공시 개요- 반도체 위탁생산 공급계약 22.76조 (매출액대비  7.6 %)삼성전자(005930)는 반도체 위탁생산 공급계약에 관한 단일판매ㆍ공급계약체결              을 28일에 공시했다.계약 상대방은 글로벌 대형기업이고, 계약금액은 22.76조 규모로 최근 삼성전자 매출액 300.87조 대비 약  7.6 % 수준이다. 이번 계약의 기간은 2025년 07월 24일 부터 2033년 12월 31일까지로 약 8년 5개월이다.한편 이번 계약수주는 2025년 07월 26일에 체결된 것으로 보고되었다.




차트

                한편, 오늘 분석한 삼성전자는 글로벌 IT기업으로 알려져 있다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.
----------------------------------------------------------------------------------------------------
Document 6:

사진=연합뉴스

                삼성전자가 28일 테슬라로부터 23조원 규모의 반도체 위탁생산(파운드리) 계약을 수주했다는 소식에 급등해 11개월 만에 '7만전자'를 회복했다.이날 오후 3시 15분 현재 코스피 시장에서 삼성전자는 전 거래일 대비 6.30% 오른 7만50원에 거래되고 있다. 삼성전자가 장중 7만원대에서 거래된 것은 지난해 9월 5일 이후 약 11개월 만이다.삼성전자는 이날 개장 전 글로벌 대형기업과 총 22조7648억원 규모의 파운드리 공급 계약을 체결했다고 공시했다.이후 계약 상대방이 테슬라임이 알려졌다. 일론 머스트 테슬라 최고경영자(CEO)는 직접 자신의 엑스(X) 계정을 통해 "삼성의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라고 밝혔다.그는 "테슬라가 생산 효율성 극대화를 돕는 것을 허용하기로 삼성이 동의했다"며 "내가 직접 진전 속도를 가속하기 위해 생산 라인을 둘러볼 것이기 때문에 이는 중요한 지점"이라고 강조했다.김수영 한경닷컴 기자 swimmingk@hankyung.com
----------------------------------------------------------------------------------------------------
Document 7:

<앵커>장 초반 6만전자로 내려갔던 삼성전자가 다시 7만 원대를 회복했습니다.SK하이닉스를 고집하던 외국인 투자자는 삼성전자로 눈을 돌렸고, 증권가에선 삼성전자의 목표가를 높이고 있는데요. 7만전자 굳히기에 들어갈지 마켓 딥다이브 최민정 기자가 정리합니다.<기자>SK하이닉스와 삼성전자의 성적이 바뀌고 있습니다.증권가에선 "이제 SK하이닉스를 팔고, 삼성전자를 사는 게 맞다"라는 말까지 나오고 있는데요.최근 한 달간의 성적을 살펴보면 삼성전자는 20% 가까이 올랐지만, SK하이닉스는 10% 하락했습니다.외국인의 변심이 컸는데요. 외국인은 삼성전자는 3조 원 가까이 사들인 반면, SK하이닉스는 매도 우위를 보이고 있습니다. 덕분에 삼성전자는 외국인 지분율도 50%대를 회복했는데요.테슬라와의 23조 원 수주가 결정적 역할을 했습니다. 적자를 내던 파운드리 사업 회복의 신호탄이란 분석이 나오는데요.납품하게 되는 AI6칩은 1초에 최대 6천 번의 연산이 가능해, 차랑용 부품뿐 아니라 테슬라의 휴머노이드 로봇 등에도 사용될 수 있습니다.미국 텍사스주 테일러 공장에서 생산돼, 미국 관세도 피할 수 있는데요. 증권가에선 삼성전자의 목표주가를 올리고 있습니다. 대신증권은 8만 8천 원을 제시하며 오늘 주가와 비교해 26% 더 오를 수 있다는 분석을 냈는데요.재무적 성과에 대한 측면보다는 향후 대형 수주로 이어질 수 있다는 점을 긍정적으로 바라봅니다.흥국증권은 "전사 기준 연 매출액의 1% 수준으로, 실적에 큰 영향을 주지 못하지만, 추가 수주 기대가 높아졌다"고 평가했는데요.다음 반등의 열쇠는 엔비디아의 HBM3E 퀄(품질) 테스트 통과입니다.엔비디아가 HBM3E 공급 부족으로 삼성전자의 퀄테스트를 앞당길 가능성이 크기 때문인데요.오늘 로이터는 엔비디아가 TSMC에 H20칩 30만 개를 추가 주문했다고 전하며, 중국 내 수요가 견조함을 확인했습니다.삼성전자의 3차 자사주 매입도 순조롭게 진행되고 있는데요.7월 들어 100만 주 씩 사들이며 벌써 9천억 원의 자사주를 매입했습니다. 삼성전자는 지난 8일 3조 9천억 원 규모의 3차 자사주를 취득하고, 이중 2조 8천억 원은 소각하겠다고 밝힌 바 있는데요.앞서 진행된 1·2차 자사주 매입도 완료하며 7조 원에 달하는 자사주를 매입한 겁니다.증권업계 관계자는 "7조 원 규모 자사주 매입·소각이 실제로 집행되면, 삼성전자의 주가 하방을 지지하는 효과가 있을 것"이라고 전합니다.이와
----------------------------------------------------------------------------------------------------
Document 8:

삼성전자, 올해 2분기 실적 발표




삼성전자 서초사옥./한국경제 이솔 기자삼성전자 반도체 사업이 올해 2분기 4000억원의 영업이익을 거두면서 적자를 면했다. 작년 2분기 6조 4000억원대 영업이익과 비교하면 94% 급감한 수준이다. 2조원대 적자를 기록한 2023년 4분기 이후 역대 최저치다. 삼성전자 측은 "재고자산 평가 충당금 등 일회성 비용이 반영되면서 실적이 하락했다"고 했다.삼성전자는 연결기준으로 올해 2분기 매출 74조6000억원, 영업이익 4조7000억원을 각각 기록했다고 31일 공시했다. 전체 매출은 전년 동기 대비 0.67% 늘었지만, 영업이익은 55.23% 급감했다. 삼성전자는 지난 8일 이같은 수준의 잠정실적을 발표했고, 이날 확정실적을 공시했다. 이번 실적은 당초 시장 눈높이를 밑도는 수준이다.반도체 사업을 담당하는 DS(Device Solutions) 부문의 매출은 27조 9000억 원, 영업이익은 4000억 원을 기록했다.삼성전자는 메모리에서 HBM3E와 고용량 DDR5제품 판매 비중을 확대해 서버 수요가 증가했고 파운드리는 전 분기 대비 11%의 매출 성장이 있었다고 밝혔다. 영업이익은 매출 성장에도 불구하고, 메모리 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향에 따른 재고 충당 발생으로 감소했다고 설명했다.가전과 TV, 모바일 등을 포함한 디바이스경험(DX) 부문은 매출 43조 6000억 원, 영업이익 3조3000억 원을 기록했다. 스마트폰 신모델 출시 효과 감소와 TV 시장의 경쟁 심화로 전 분기 대비 매출이 16% 감소했고 영업이익도 1조4000억 원 감소했다.또한 원달러 환율이 하락하면서 달러 거래 비중이 높은 부품 사업을 중심으로 전분기 대비 약 5000억 원 수준의 부정적 영향이 있었다고 했다.김영은 기자 kye0218@hankyung.com
----------------------------------------------------------------------------------------------------
Document 9:

한경유레카는 AI알고리즘들의 개별 종목 투자의견(점수)을 한눈에 볼 수 있는 투자 플랫폼입니다. '한경유레카' 앱을 내려받으면 종목별 투자의견과 나에게 맞는 AI알고리즘을 추천받을 수 있습니다.





                28일 삼성전자가 강세다. 삼성전자는 오후 13시 50분 전일대비 5.1% 오른 6만9400원에 거래되며 7만전자를 코앞에 두고 있다.삼성전자가 마지막으로 7만원 대에 장을 마감한 것은 지난해 9월이 마지막이다.당일 삼성전자는 공시를 통해 반도체 위탁생산 공급계약 소식을 전했다. 글로벌 대형기업과 약 22조 7600억원 규모의 계약으로 계약기간은 2025년 7월 24일부터 2033년 12월 31일까지이다.AI알고리즘들의 투자의견을 모아 종합의견을 제시하는 한경유레카는 삼성전자에 대해 7월 17일 매수의견을 제시한바 있다.한경유레카에서는 관심 종목을 등록하면 AI알고리즘들의 종합의견을 무료로 확인할 수 있으며 매매의견이 변동되면 오전 8시 30분에 앱을 통해 알림 서비스를 제공한다.한경닷컴 뉴스룸 open@hankyung.com
----------------------------------------------------------------------------------------------------
Document 10:

사진=연합뉴스

                코스피지수가 7일 장중 3210선에서 상승세를 유지하고 있다. 삼성전자가 애플의 차세대 칩을 미국 파운드리(반도체 수탁생산) 공장에서 생산하기로 하면서 강세를 보이는 점이 지수 상승을 뒷받침하는 것으로 보인다. 다만 도널드 트럼프 미국 대통령이 반도체에 100% 품목별 관세를 부과하겠다고 밝힌 데 따른 경계감에 상단은 제한된 모습이다.이날 오전 11시11분 현재 코스피지수는 전 거래일보다 12.75포인트(0.4%) 오른 3210.89를 기록하고 있다. 지수는 이날 0.52% 오름세로 출발 후 0.3~0.7% 사이에서 등락률을 보이고 있다. 유가증권시장에서 개인이 128억원 매수 우위인 반면 외국인과 기관이 각각 420억원 95억원 매도 우위다.트럼프 대통령이 반도체에 약 100% 품목별 관세를 부과할 것이란 소식에 투자자들의 경계 심리가 발동한 것으로 풀이된다. 그럼에도 지수가 상승세를 이어가는 건 국내 시가총액 1위인 삼성전자가 강세를 보이고 있기 때문으로 보인다. 삼성전자는 애플의 차세대 칩을 생산하게 됐다는 소식에 2%대 강세로 다시 '7만전자'를 회복했다. 장중 한때 3% 넘게 상승하기도 했다. 이밖에 코스피 시가총액 상위 종목 중 LG에너지솔루션, 현대차, 두산에너빌리티, HD현대중공업, 네이버 등이 오르는 반면 SK하이닉스, 삼성바이오로직스, 한화에어로스페이스, KB금융, 기아, 셀트리온 등이 내리고 있다.같은 시각 코스닥지수는 전 거래일보다 0.17포인트(0.02%) 오른 803.66으로 800선을 사수하고 있다. 코스닥시장에서도 외국인과 기관이 각각 469억원과 191억원 매도 우위인 반면 개인은 794억원 매수 우위다.코스닥 시총 상위 종목 중 파마리서치, 레인보우로보틱스, 휴젤, 클래시스 등이 오르는 반면 알테오젠, 에코프로비엠, 펩트론, 에코프로, HLB, 리가켐바이오, 삼천당제약, 에이비엘바이오 등이 내리고 있다.고정삼 한경닷컴 기자 jsk@hankyung.com
----------------------------------------------------------------------------------------------------
Document 11:

가동 속도조절에 들어갔습니다.이번 테슬라 수주기간이 2033년까지 8년인데, 장기 고객을 확보하면서 한숨 돌릴 수 있게 됐습니다.테일러 공장은 4나노 이하 최첨단 공정이 가능하고 추후 2나노 양산도 준비 중인데, 이번 테슬라 AI6 생산은 2나노와 4나노로 진행될 전망입니다.삼성은 그동안 3나노 이하 공정에서 TSMC에 밀리는 모습이었는데, 이번에 2나노에서 경쟁력을 입증한다면 추가 빅테크 수주로 이어질 것이라는 분석입니다.<앵커>이재용 삼성전자 회장이 지난 17일 사법리스크를 완전히 해소했습니다. 이 회장이 복귀하자마자 대규모 계약소식이 전해지면서 이른바 '뉴삼성'에 대한 기대감도 커지고 있죠?<기자>이재용 회장이 지난 17일 대법원에서 최종 무죄가 확정되면서 10년 가까이 따라다녔던 사법리스크를 떨쳐냈습니다.삼성전자는 이 회장 2심 무죄 이후 전장과 공조, 헬스케어 기업을 잇따라 인수했습니다. 이 회장이 그리는 '뉴삼성'의 모습이 가시화되는 분위기입니다.이재용 회장은 지난 2018년 삼성의 4대 미래성장사업으로 AI와 5G, 바이오, 그리고 전장을 꼽았습니다.이번 테슬라와의 계약은 파운드리 수주로 볼 수도 있지만 이 회장이 중요하게 생각하는 전장사업의 대표적인 분야입니다.올해 초 이 회장이 시진핑 주석을 만난 뒤, 삼성전기가 중국 최대 전기차 회사인 비야디에 전장용 MLCC를 공급하게 된 것과도 맞닿아 있습니다.한편, 우리정부가 트럼프 행정부와 막판 관세협상을 진행 중인데, 2주 뒤에는 반도체 품목관세도 예고된 상황입니다.삼성그룹의 역할이 어느 때보다 중요한 상황에서 삼성이 미국 반도체 공장에 장기고객을 확보하게 된 점은 여러모로 긍정적인 소식이라는 분석입니다.<앵커>잘 들었습니다.홍헌표기자 hphong@wowtv.co.kr
----------------------------------------------------------------------------------------------------
Document 12:

※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.





                투자수익률 상위 1％ 고수들이 4일 오전 삼성전자를 집중 매수하고 있다. 반면 두산에너빌리티는 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 삼성전자, 한화엔진, HD한국조선해양 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％ 투자자의 매매동향을 취합한 결과다.오전 10시 현재 삼성전자가 7만50원으로 이전 거래일보다 1.67% 올랐다. 앞서 삼성은 미국 전기차업체 테슬라와 165억달러(약 23조원) 규모의 인공지능(AI) 반도체 공급 계약을 체결했다고 지난달 28일 공시했다. 김영건 미래에셋증권 연구원은 지난 1일 보고서에서 이번 계약 관련, “AI 빅테크로부터 기술력을 공식 인정받은 사례”라며 “고대역폭메모리(HBM) 사업 부진도 단숨에 시간 문제로 전략했다”고 호했다. 지난달 31일 한국산 제품에 대한 미국의 상호관세율(15%) 확정도 불확실성 완화에 기여했다.한화엔진은 3만5300원으로 0.43% 상승했다. 한화엔진은 지난 2분기 338억원의 영업이익을 냈다고 지난달 24일 발표했다. 전년 동기 대비 81.4% 증가한 규모다.





                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 두산에너빌리티, 에이치브이엠, 파마리서치 순이다. 주가는 각각 직전 거래일 대비 4.89%, -13.53%, 0.54% 변동했다.에이치브이엠은 우주항공 등 미래산업용 특수금속을 만드는 회사로 급등 후 차익실현 매물이 쏟아지고 있다. 지난 1일에는 일론 머스크 테슬라 CEO의 스페이스X와 제품 공급계약을 체결했다고 밝히면서 상한가로 직행했다.





                이태호 기자 thlee@hankyung.com
----------------------------------------------------------------------------------------------------
Document 13:

삼성전자의 주가가 최근 약세를 벗고 반등세를 보이기 시작했다. 가장 큰 촉매는 최고경영진의 법적 불확실성 제거로, 이재용 회장이 최종 무죄 판결을 받으며 경영 전면에 나설 수 있는 기틀이 마련됐다는 점이다. 이 소식이 전해진 직후 주가는 즉각 반등했으며, 투자자들은 경영 안정성과 전략 재정비 기대감을 반영했다.또한 최근 사상 최대 규모인 약 165억 달러에 달하는 파운드리(위탁생산) 계약 체결 소식이 주가 상승의 실질적 동력을 제공했다. 계약의 상대방과 조건은 장기간 비공개로 유지되지만, 대외 수익성과 기술력에 대한 기대가 급격히 증가하며 증권 시장에서 긍정적인 반응을 끌어냈다.여기에 AI 반도체 수요 기대도 맞물렸다. 글로벌 AI 프로젝트에서 핵심적인 역할을 하는 고대역폭 메모리(HBM) 매출 증가 기대와 함께 삼성의 파운드리 경쟁력에 대한 인식이 강해지면서, 투자심리가 개선되었다.






외국인 투자자의 매수세도 뒤따랐다. 낮은 밸류에이션과 저가 매수 흐름 속에서 글로벌 자금이 유입되며 기술주 랠리를 견인했고, 삼성전자도 그 수혜 종목으로 이름을 올렸다.기대와 달리 2분기 실적은 아직 약점으로 작용하고 있다. 미국과 중국 간 기술·무역 리스크로 인해 AI 메모리 칩 수요가 지연되며 이익이 큰 폭 감소할 전망이다. 특히 엔비디아 인증 지연과 중국 수출 제한이 삼성의 성장성 회복에 제약을 주고 있다는 분석이 나온다.그러나 법률 리스크 해소와 대규모 수주 계약, 그리고 AI 메모리 및 파운드리 영역에서의 중장기 성장 기대가 투자자 심리에 긍정적으로 작용하며 주가 흐름에 방향성을 부여하고 있다는 해석이 나온다. 다만 경쟁사 대비 기술적 우위 확보 여부, 수주 계약의 실제 실현 가능성, 글로벌 공급망 환경 변화 등에 대한 면밀한 관찰이 필요한 시점이다.한화엔진, LIG넥스원, 이렘, 다날, KB금융무료상담
----------------------------------------------------------------------------------------------------
Document 14:

반도체 소부장(소재·부품·장비) 관련주가 일제히 급등했다. 삼성전자가 테슬라의 차세대 인공지능(AI) 칩을 수탁생산한다는 소식에 수혜 기대가 커지면서다.





                30일 한국거래소에 따르면 최근 3거래일 동안 KRX 반도체지수는 3% 넘게 올랐다. 전체 KRX지수 중 세 번째로 높은 상승률이다. 특히 반도체 장비 제조사 원익IPS 주가는 같은 기간 21.2% 급등했다. 반도체용 식각액 공급 업체 솔브레인과 후공정 업체인 두산테스나 주가도 각각 23.6%, 24.4% 뛰었다.삼성전자 공급망에 속한 소부장 종목의 상승세가 두드러졌다는 평가가 나온다. 테슬라의 자율주행 차량과 휴머노이드 로봇에 들어가는 차세대 AI칩 생산을 삼성전자가 맡기로 하면서다. 2033년까지 22조7647억원어치를 공급하는 삼성 반도체 역사상 최대 규모 계약이다.반도체 소부장주를 집중 매수하는 세력은 주로 기관투자가다. 3거래일간 원익IPS를 126억원어치 사들였다. 같은 기간 솔브레인도 192억원어치 순매수했다. 반도체 소부장주 주가가 올 들어서도 지지부진하자 투자 매력이 더 높아졌다는 게 증권가 해석이다. 주요 반도체 소부장주는 2021년 고점 대비 40~50%가량 조정받은 상태다. 운용사 관계자는 “반도체 소부장주의 기관 수급이 빈 상황에서 삼성전자의 테슬라 수주 소식이 나오자 매수세가 강하게 들어왔다”며 “반도체 소부장주의 밸류에이션(실적 대비 주가 수준) 매력이 높다”고 진단했다.증권가에서는 반도체 소부장주 상승세가 하반기에도 이어질 것으로 전망했다. 대신증권은 원익IPS와 솔브레인을 삼성전자 대규모 수주에 따른 대표적 수혜주로 제시했다.삼성증권은 두산테스나와 하나마이크론을 주목했다. 추후 삼성전자의 파운드리(반도체 수탁생산) 가동률이 높아지면 수혜를 볼 것으로 봤다. 이종욱 삼성증권 연구원은 “파운드리 가동률이 전반적으로 올라가면 이들 종목이 우선 주목받을 것”이라고 전망했다. 시장에선 삼성전자가 테슬라 물량을 내년 2분기부터 본격 생산할 것으로 보고 있다. 현재 짓고 있는 미국 텍사스 테일러 공장이 생산지다.류은혁 기자 ehryu@hankyung.com
----------------------------------------------------------------------------------------------------
Document 15:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 SK하이닉스 삼성전기 LG이노텍 삼성에스디에스
----------------------------------------------------------------------------------------------------
Document 16:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 한화오션 두산테스나 NHN 원익IPS
----------------------------------------------------------------------------------------------------
Document 17:

때문이다. 업계 관계자는 “삼성이 소니 물량의 20~30%만 뺏어와도 격차를 크게 좁힐 수 있다”고 말했다.이미지센서가 중요한 이유는 카메라 품질뿐만 아니라 스마트폰 두께에도 영향을 주기 때문이다. 스마트폰 브랜드들은 ‘카툭튀’(카메라가 툭 튀어나옴) 문제를 해결하기 위해 이미지센서 경량화를 반도체 기업에 주문하고 있다. 삼성은 동일한 양의 빛으로 더 많은 신호를 만들어내는 ‘나노프리즘’ 기술을 통해 크기를 업계 최소인 0.56마이크로미터(㎛·1㎛=100만분의 1m)까지 줄이는 등 경쟁사와의 ‘기술 초격차’에 성공했다.애플 공급망 진입으로 삼성전자는 ‘반도체 미래 먹거리’로 꼽히는 이미지센서 시장에서 도약의 발판을 마련하게 됐다. 이미지센서는 최근 자율주행차, 휴머노이드 로봇 등 적용처가 늘어나고 있다. 옴디아에 따르면 글로벌 시장 규모가 2024년(28조7000억원)에서 2029년 265억달러(36조5567억원)로 커질 것으로 전망된다.◇시스템반도체 반등 속도애플에 공급되는 이미지센서는 삼성 시스템LSI사업부가 설계하고 미국 오스틴에 있는 삼성 파운드리(반도체 수탁생산) 공장에서 생산한다. 시스템LSI와 파운드리 사업부 실적을 동시에 개선할 수 있다는 얘기다. 애플 공급으로 삼성은 연간 최소 수조원의 매출을 거둘 것으로 업계는 보고 있다.지난달 테슬라와 체결한 165억달러(약 22조8000억원) 규모 공급 계약이 더해지면서 삼성 시스템반도체 사업의 실적 개선 기대가 커지고 있다. 테슬라와 애플 공급으로 ‘품질 인증 마크’를 받은 만큼 추가 고객 수주가 나올 가능성이 높다. 시스템LSI의 스마트폰 애플리케이션프로세서(AP) ‘엑시노스’도 성능과 수율 개선에 힘입어 본궤도에 오르고 있다는 평가가 나온다. 차세대 AP인 ‘엑시노스 2600’가 내년 출시되는 갤럭시 플래그십 스마트폰에 적용될 가능성이 높은 것으로 분석된다.삼성이 테슬라와 애플을 연달아 수주한 배경에는 이재용 삼성전자 회장의 역할이 컸던 것으로 전해졌다. 애플에 공급하는 차세대 이미지센서는 이 회장이 강조해온 ‘세상에 없는 기술을 만들자’는 경영 철학을 바탕으로 개발한 제품일 가능성이 높다. 이 회장은 지난달 중순 글로벌 재계 거물들의 사교 모임인 ‘선 밸리 콘퍼런스’ 행사에 참석하는 등 적극적인 경영 행보를 이어가고 있다.박의명/황정수 기자 uimyung@hankyung.com
----------------------------------------------------------------------------------------------------
Document 18:

<앵커>삼성전자가 테슬라와 약 23조원 규모의 파운드리 공급계약을 맺었습니다. 부진에 빠져있던 삼성 파운드리가 반등의 신호탄을 쏘아올렸다는 평가입니다. 자세한 내용 산업부 홍헌표 기자와 알아보겠습니다. 홍 기자, 가장 궁금했던게 계약 상대방인데, 역시 테슬라였군요?<기자>삼성전자가 이번 계약 소식을 밝히면서 고객사 이름은 밝힐 수 없다고 이야기했습니다.글로벌 회사와 이정도 규모의 계약을 맺을 때 비밀유지를 제대로 하지 않으면 계약이 파기되는 경우가 있습니다.그런데 약 1시간 전쯤 일론 머스크 테슬라 CEO가 직접 삼성과 계약을 맺었다고 SNS에 올렸습니다.머스크는 "테슬라의 완전자율주행 칩인 AI6를 삼성 텍사스 공장에서 생산한다"면서 "이 기술의 전략적 중요성은 엄청나다"고 언급했습니다.그러면서 "삼성은 현재 AI4 칩을 만들고 있고, TSMC는 AI5를 대만에서 생산 중인데, 향후 애리조나 공장에서 만들 것"이라고 밝혔습니다.당초 국내 증권가에서도 삼성전자 2분기 잠정실적 발표 이후 삼성 파운드리가 글로벌 빅테크와 새로운 계약을 맺을 것으로 예상했습니다.키움증권은 "내년 애플 아이폰 18용 이미지센서 양산, 테슬라 등 신규 거래선 확보를 통해 영업적자의 폭을 축소시켜 나갈 전망"이라고 밝히기도 했습니다.이미 테슬라는 삼성전자 파운드리의 주요 고객사입니다. 지난 2019년부터 14나노 ‘완전자율주행(FSD) 칩’을 시작으로 자율주행 반도체를 공급해 왔습니다.지난 2023년 5월에는 이재용 삼성전자 회장이 일론 머스크 테슬라 CEO를 직접 만나 완전자율주행 등 전장용 시스템반도체에 대해 논의하기도 했는데요,이 회장과 머스크의 미래 전장사업에 대한 동맹이 굳건한 것으로 풀이됩니다.<앵커>삼성 파운드리가 계속 실적이 부진한 가운데 이번 계약이 발표되면서 파운드리 사업부가 숨통이 트일 것 같습니다. 이번 계약규모가 165억 달러, 우리 돈으로 22조8천억원입니다. 그런데 계약기간이 8년입니다. 어느정도 성과로 볼 수 있을까요?<기자>삼성전자는 오전에 이 계약 공시를 하면서 계약규모가 전체 매출액 대비 7.6%라고 밝혔습니다.7.6%면 그렇게 큰 규모가 아니라고 생각할 수도 있는데요, 삼성전자 지난해 300조 매출에는 스마트폰, 가전, 메모리반도체 등이 모두 합쳐진 수치입니다.파운드리 성과를 분석하기 위해서는 파운드리 사업부 매출만 떼내서 계산을 해야합니다.삼성은 파운드리만 따로 공시는 하지 않아서 TSMC 매출과
----------------------------------------------------------------------------------------------------
Document 19:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.





삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.





종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.SK하이닉스 카카오페이 다날 한화시스템 솔브레인
----------------------------------------------------------------------------------------------------
Document 20:

이재용 삼성전자 회장(왼쪽 세 번째)이 지난해 5월 미국 실리콘밸리에 위치한 삼성전자 북미 반도체연구소에서 일론 머스크 테슬라 최고경영자(CEO, 오른쪽 네 번째)와 만나 기념 촬영하고 있는 모습. 사진=삼성전자 제공

                이 소식이 전해진 당일인 28일 삼성전자 주가는 6.83% 치솟았지만, 삼성전기는 2.67% 오르는 데 그쳤다. 테슬라의 대규모 AI6 칩 위탁생산 발주가 삼성전기의 FC-BGA 매출 증가로 이어질 가능성이 주식시장에서 주목되지 못하다가, 전날에야 부상한 결과다.박강호 대신증권 연구원은 “삼성전자와 테슬라 (공급망) 내에서 삼성전기의 경쟁력을 반영하면 이번 AI6 칩 생산에서도 최대 FC-BGA 공급업체가 될 것”이라고 평가했다.삼성전기는 이미 테슬라의 AI 칩 공급망 안에서 ‘터줏대감’이다. 삼성전자가 위탁생산하는 AI4 칩뿐만 아니라 파운드리 글로벌 1위 업체인 TSMC가 위탁생산을 맡은 AI5칩에도 FC-BGA를 공급하고 있다.삼성전기는 FC-BGA뿐 아니라 테슬라의 전장용 카메라, MLCC 공급망에서도 한 자리를 차지하고 있다. 특히 전장용 카메라는 테슬라 차량의 자율주행에서 핵심적인 부품이다. 테슬라 차량의 자율주행은 도로 상황 인지를 전적으로 카메라에 의존하고 있어서다.박강호 연구원은 “삼성전기의 카메라 모듈은 테슬라가 전기자동차에서 자율주행, 로보택시, 휴머노이드 분야로 사업 다각화를 추진하면서 공급 규모가 확대될 것으로 예상된다”며 “MLCC 역시 높은 신뢰성을 갖춘 고용량 제품을 중심으로 자동차 대당 채택 규모가 증가하고 있다”고 설명했다.한경우 한경닷컴 기자 case@hankyung.com
----------------------------------------------------------------------------------------------------
Document 21:

플랙트(공조), 마시모(오디오), 젤스(헬스케어) 등 여러 인수합병을 진행했습니다.앞으로도 M&A를 통해 급변하는 글로벌 기술 트렌드에 대응하겠다면서 AI, 공조, 메디텍, 전장 등 신성장 분야의 후보 업체들을 검토 중이라고 설명했습니다. 사업 경쟁력 강화와 사업 규모를 확대하기 위해 비슷한 분야의 업체들을 추가로 인수할 가능성을 내비친 것으로 보입니다.또한 삼성은 올해 상반기 미래 신기술, 우수 기술업체 발굴을 위해 약 40여개 업체에 1억2,000만 달러(1,700억원) 이상을 벤처 투자했다고 강조했습니다.지난 29일에는 국내 AI 반도체 기업인 리벨리온이 삼성 계열사로부터 대규모 투자를 받았다고 발표하기도 했습니다.이재용 회장이 사법리스크 해소로 '뉴삼성' 구축에 속도를 내고 있는 가운데, 지난 2017년 하만과 같은 초대형 M&A도 기대되고 있습니다.<앵커>잘 들었습니다.홍헌표기자 hphong@wowtv.co.kr
----------------------------------------------------------------------------------------------------
Document 22:

한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 'AI 컨센서스'를 제공하는 서비스입니다. '한경유레카' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.






In [34]:
compressed_docs[0]

Document(id='d2b36cf9dccce2895bc8ae765f857eec', metadata={'Date': '2025-07-29', 'ticker': '삼성전자', 'url': 'https://magazine.hankyung.com/business/article/202507249472b', 'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]', 'original_idx': 5709, 'chunk_idx': 3}, page_content='자사주 소각, 이재용 회장의 사법 리스크 해소 등 여러 호재에도 불구하고 삼성전자 주가는 줄곧 6만 원대에 머물렀다.삼성전자가 사실상 ‘잠든 상태’에서도 코스피는 크게 올랐다. 그렇다면 삼성전자가 본격적으로 기지개를 켠다면 어떨까.지난 28일 삼성전자는 테슬라와의 납품 계약, 이른바 ‘23조 잭팟’ 소식에 주가가 7만 원대를 회복했다. 전문가들은 “삼성전자의 반등이야말로 코스피 5000 돌파의 열쇠”라고 진단한다.삼성전자가 지수를 실질적으로 견인하려면 주가는 얼마나 올라야 할까. 삼성전자의 시가총액은 7월 24일 기준 약 390조원이다.2021년 고점(주가 약 9만1000원) 당시에는 약 540조원에 달했다. 단순 계산으로 지수 3300에서 5000까지 51% 오르려면, 삼성전자 역시 현재 주가에서 9만원 이상으로 회복해야 한다는 계산이 나온다.삼성전자와 함께 주가를 견인할 신흥 대장주도 필요하다. 기준은 명확하다. 시가총액이 크고 기관·외국인 수급이 몰리며 정부 정책이나 글로벌 산업 트렌드를 타야 한다. 2025년 7월까지의 상승률 상위 종목 중에는 한화에어로스페이스, LIG넥스원, 두산에너빌리티, SK하이닉스, POSCO홀딩스 등이 후보로 꼽힌다. 이들은 정책, 실적, 수급, 산업 구조 재편이라는 4박자를 동시에 갖춘 기업들이다.정채희 기자 poof34@hankyung.com')

### original 본문 가져오기

In [35]:
def get_full_article_from_chroma(original_idx: int, kind : str, vectordb) -> dict:
    """original_idx 기준으로 chunk들을 모아 원문 복원"""
    # 1. 해당 article의 모든 chunk 가져오기
    VecDB = vectordb._collection
    results = VecDB.get(
      where = { "$and" : [ # 빈 쿼리로 전체 탐색
            {"original_idx": original_idx}, 
            {"ticker": kind}
            ]
         },
         include = ['documents','metadatas']   
        )
    print(f'results : {results}')
    if not results:
        return {"error": f"No chunks found for original_idx {original_idx}"}

    #print(results)
    #print(results['metadatas'][0]['chunk_idx'])

    # 4. 대표 metadata 하나 뽑아 저장
    return {
        "title": results['metadatas'][0]["title"],
        "url": results['metadatas'][0]["url"],
        "Date": results['metadatas'][0]["Date"],
        "ticker": results['metadatas'][0]["ticker"],
        "content": results['documents'][0]
    }

In [36]:
original_idxs = list(map(lambda x: x.metadata['original_idx'], compressed_docs))

In [37]:
original_idxs

[5709,
 5942,
 5914,
 5809,
 5680,
 5557,
 5922,
 5798,
 5615,
 5674,
 5565,
 5574,
 5907,
 5643,
 5533,
 5682,
 5815,
 5896,
 5660,
 5867,
 5953,
 5693,
 5797,
 5882,
 5713,
 5953,
 5515,
 5584,
 5685,
 5673]

In [38]:
top_n_original = [get_full_article_from_chroma(idx,kind='삼성전자',vectordb=vectordb) for idx in original_idxs]

results : {'ids': ['0915dd135d88715d463dd3a01c7a4e2f', 'b81c8d01d976bd79a521a0ca3984cf22', 'c478c40b605cae0db62fc1bee8e01d04', 'd2b36cf9dccce2895bc8ae765f857eec'], 'embeddings': None, 'documents': ['BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세', '결론부터 말하자면 주도주가 바뀌었다.2021년 시장을 지배했던 ‘BBIG’(배터리·바이오·인터넷·게임)는 힘을 잃었다. 2025년의 시장은 ‘지금조방원’(지주회사·금융·조선·방산·원자력)과 ‘ABCDE’(AI·바이오·문화·방산·에너지)의 무대다.코스피 3000 시대를 이끌었던 2021년과 3200선으로 끌어올린 2025년의 주도주를 비교 분석했다. 2021년은 팬데믹 저점이었던 코스피 1457.64(2020년 3월 19일)부터 사상 최고치인 3305.21(2021년 7월 6일)을 기록할 때까지의 구간이다. 상승률은 126.75%. 전례 없는 유동성과 기업 펀더멘털 개선이 맞물린 결과였다. 박스권에 갇혀 있던 국내 증시가 근 18년 만에 구조적 상향 돌파를 이룬 시기로 평가된다.반면 2025년의 상승은 정책 주도형 랠리다. 새 정부의 증시 부양 기조와 거버넌스 개혁 기대가 주가를 끌어올리고 있다.두 시기를 대표하는 코스피 시가총액 상위 50개 종목의 주가 상승률을 비교 분석해 ‘과거의 주도주’와 ‘현재의 주도주’가 어떻게 달라졌는지 분석한 결과, 2025년의 장세는 지주회사, 금융, 조선, 방산, 원자력 등 이른바 ‘지금조방원’이 이끌었다.가장 높은 상승률을 기록한 종목은 현대로템이다. 올해 1월 초 4만9700원이던 주가는 7월 말 19만9800원까지 오르며 302.01% 급등했다. 폴란드와 체결한 K2 전차 등 방산 수출 기대와 글로벌 지정학적 리스크 확대가 주가를 밀어올렸다.두산에너빌리티(289.74%)는 지난 정부의 원전 정책 정상화로 반등에 성공한 이후 최근 AI 산업 확산에 따른 전력 수요 증가로 다시 주목받았다. 한화에어로스페이스(185.84%), LIG넥스원(185.71%)도 방산 수요 확대에 따른 실적 개선 기대가 주가를 끌어올렸다.금융주 역시 2025년 확실한 주도주로 부상했다. 미래에셋증권(154.05%), 우리금융지주(62.33%), 하나금융지주(61.80%), 신한지주(44.81%), 기업은행(41.31%), 카카오뱅크(40.86%), KB금융(38.72%) 등 금융주는 자사주 매입과 배당 확대 기대, 새 정부의 강력한 증시 부양 정책 기대감에 큰 폭으로 올랐다. 1980년대 증권주, 2000년대 보험주에 이어 20년 만의 주도주 탈환이란 분석도 나왔다.한화오션(125.97%), 두산(124.71%), SK스퀘어(103.53%) 등도 세 자릿수 수익률을 기록하며 상반기 랠리의 중심에', '증시 부양 정책 기대감에 큰 폭으로 올랐다. 1980년대 증권주, 2000년대 보험주에 이어 20년 만의 주도주 탈환이란 분석도 나왔다.한화오션(125.97%), 두산(124.71%), SK스퀘어(103.53%) 등도 세 자릿수 수익률을 기록하며 상반기 랠리의 중심에 섰다. 이들 종목은 대부분 새 정부 정책의 직접적인 수혜 업종으로 분류된다. 특히 이재명 대통령이 상법 개정 등 증시 부양책에 드라이브를 걸면서 지주사들이 구조적 재평가를 받을 수 있다는 기대감이 주가에 반영됐다.AI·콘텐츠·에너지 종목들도 강세를 보였다. SK하이닉스(56.70%)는 고성능 HBM 반도체 수요 확대 속에 AI 반도체 핵심 공급사로 떠올랐다. 배당이나 자사주 소각이 아니라 기술력과 산업 내 위상만으로 폭발적 주가 상승을 이끈 사례다.위기와 논란의 카카오(48.95%), 하이브(42.71%)도 콘텐츠·IP 확장과 글로벌 플랫폼 전략이 맞물리며 시장 기대를 다시 얻었다. 특히 AI에 100조원 투입을 계획한 새 정부 기조와 한류 확산이 시너지를 더했다.반면 2021년의 핵심 주도주였던 ‘BBIG’는 부진했다. 배터리·바이오·인터넷·게임의 앞글자를 딴 BBIG는 당시 비대면 시대의 기대를 먹고 자란 성장주들의 집합이었다.주가 성과도 압도적이었다. 카카오(456%), SK이노베이션(290%), 삼성SDI(237%), 네이버(180%) 등이 대표적이다. 하지만 이후 미·중 무역 갈등, 실적 한계와 규제, 밸류에이션 부담이 맞물리며 2025년 랠리에서는 상대적으로 부진한 흐름을 보이고 있다.2021년 주도주 상위 10개 종목 중 절반 이상이 2025년 주도주 랠리에서 배제된 것도 주목할 만하다. HMM과 두산에너빌리티, 카카오 정도만이 주도주 반열에 재등장했을 뿐 나머지는 주가 부진과 산업 모멘텀 소멸로 저조한 수익률을 올리거나 마이너스 수익률을 기록해야 했다.지수 5000의 마지막 열쇠?주도주 분석에서 놓쳐선 안 될 또 하나의 힌트는 ‘대장주의 움직임’이다.앞서 7월 중순까지 코스피는 연초 대비 30% 넘게 상승했지만, 같은 기간 삼성전자 주가는 27.44% 오르는 데 그쳤다. 자사주 소각, 이재용 회장의 사법 리스크 해소 등 여러 호재에도 불구하고 삼성전자 주가는 줄곧 6만 원대에 머물렀다.삼성전자가 사실상 ‘잠든 상태’에서도 코스피는 크게 올랐다. 그렇다면 삼성전자가 본격적으로 기지개를 켠다면 어떨까.지난 28일 삼성전자는 테슬라와의', '자사주 소각, 이재용 회장의 사법 리스크 해소 등 여러 호재에도 불구하고 삼성전자 주가는 줄곧 6만 원대에 머물렀다.삼성전자가 사실상 ‘잠든 상태’에서도 코스피는 크게 올랐다. 그렇다면 삼성전자가 본격적으로 기지개를 켠다면 어떨까.지난 28일 삼성전자는 테슬라와의 납품 계약, 이른바 ‘23조 잭팟’ 소식에 주가가 7만 원대를 회복했다. 전문가들은 “삼성전자의 반등이야말로 코스피 5000 돌파의 열쇠”라고 진단한다.삼성전자가 지수를 실질적으로 견인하려면 주가는 얼마나 올라야 할까. 삼성전자의 시가총액은 7월 24일 기준 약 390조원이다.2021년 고점(주가 약 9만1000원) 당시에는 약 540조원에 달했다. 단순 계산으로 지수 3300에서 5000까지 51% 오르려면, 삼성전자 역시 현재 주가에서 9만원 이상으로 회복해야 한다는 계산이 나온다.삼성전자와 함께 주가를 견인할 신흥 대장주도 필요하다. 기준은 명확하다. 시가총액이 크고 기관·외국인 수급이 몰리며 정부 정책이나 글로벌 산업 트렌드를 타야 한다. 2025년 7월까지의 상승률 상위 종목 중에는 한화에어로스페이스, LIG넥스원, 두산에너빌리티, SK하이닉스, POSCO홀딩스 등이 후보로 꼽힌다. 이들은 정책, 실적, 수급, 산업 구조 재편이라는 4박자를 동시에 갖춘 기업들이다.정채희 기자 poof34@hankyung.com'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'Date': '2025-07-29', 'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]', 'original_idx': 5709, 'ticker': '삼성전자', 'url': 'https://magazine.hankyung.com/business/article/202507249472b', 'chunk_idx': 0}, {'ticker': '삼성전자', 'original_idx': 5709, 'url': 'https://magazine.hankyung.com/business/article/202507249472b', 'Date': '2025-07-29', 'chunk_idx': 1, 'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]'}, {'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]', 'url': 'https://magazine.hankyung.com/business/article/202507249472b', 'Date': '2025-07-29', 'ticker': '삼성전자', 'chunk_idx': 2, 'original_idx': 5709}, {'ticker': '삼성전자', 'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]', 'original_idx': 5709, 'Date': '2025-07-29', 'chunk_idx': 3, 'url': 'https://magazine.hankyung.com/business/article/202507249472b'}]}
results : {'ids': ['235326aac197888b699ef0c17238f454'], 'embeddings': None, 'documents': ['삼성전자가 올해 하반기 확장현실(XR) 헤드셋(사진), 두 번 접는 ‘트리폴드폰’ 등 신제품을 출격시킨다. 인공지능(AI), 메디테크(의료기술), 냉난방공조(HVAC) 등 신사업을 강화하기 위해 추가 인수합병(M&A)도 추진한다.31일 삼성전자에 따르면 갤럭시 스마트폰 등 모바일 기기를 담당하는 모바일경험(MX)사업부는 올 2분기 매출 29조2000억원, 영업이익 3조1000억원을 기록했다. 1년 전보다 매출은 6.6%, 영업이익은 39% 늘었다. 갤럭시 S25 시리즈 등 프리미엄 제품과 갤럭시탭 10 시리즈 등 태블릿PC 판매가 늘어난 영향이다.삼성전자는 7월 출시한 갤럭시 Z폴드7·플립7 등 폴더블 신제품 판매를 늘리고 갤럭시 S25 시리즈의 마케팅을 강화해 3분기 실적을 끌어올릴 계획이다. XR 헤드셋, 트리폴드폰 등 차세대 혁신 제품을 올 연말까지 출시한다고 공개했다. 다니엘 아라우호 MX사업부 상무는 “구글과의 협력으로 구축한 XR 생태계를 기반으로 AI 기능을 적용한 헤드셋을 통해 갤럭시 제품군 경쟁력을 높일 것”이라고 말했다.삼성전자는 AI 기능을 적용한 TV와 가전 판매를 늘리는 동시에 미래 성장 동력으로 낙점한 HVAC 사업을 적극 키운다는 전략을 세웠다. 삼성전자는 HVAC 사업 확대를 위해 지난 5월 2조4000억원을 들여 독일 HVAC 기업인 플랙트그룹을 사들였다. 한인택 삼성전자 생활가전(DA)사업부 상무는 “지난해 7월 설립한 미국 레녹스와의 합작사, 플랙트그룹 등과 결합해 데이터센터 및 상업용 시장 공략에 나설 것”이라고 말했다.삼성전자는 올해 플랙트그룹과 함께 미국 마시모 오디오사업부, 미국 디지털 헬스케어 회사 젤스 등 세 차례에 걸쳐 M&A 소식을 발표하며 잠잠하던 M&A 엔진을 재가동했다. 박순철 삼성전자 경영지원실장(CFO)은 “다양한 신성장 분야의 후보 업체를 검토 중”이라며 추가 M&A를 예고했다. 신성장 분야는 AI, 공조, 메디테크, 로봇, 전장, 핀테크, 부품 등이다.김채연 기자 why29@hankyung.com'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'chunk_idx': 0, 'Date': '2025-07-31', 'ticker': '삼성전자', 'original_idx': 5942, 'url': 'https://www.hankyung.com/article/2025073148211', 'title': "'갤럭시 생태계' 거침없는 확장…XR헤드셋·트리폴드폰 곧 출격"}]}
results : {'ids': ['1e11de8ae65359d8fbefcef45471e51c', 'c7793f1fa1faa84f504a8c55586b3a4c', '4291b41b587430533ca8f768ab294db4', 'b04ea5f3bf6c41e783a7d1f1365bbfe9', 'a9fa1e71600ea714ab89d7d0ea624a42'], 'embeddings': None, 'documents': ['영상 모듈 닫기', '<앵커>주요 산업들의 업황을 가장 빠르게 확인하는 시간,키워드나우,한경에이셀 박이경 애널리스트와 함께 합니다.지난 주 검색량 52주 최고치 기록한 키워드 살펴볼가요<박이경 연구원>지난 주에도 많은 키워드들이 부각이 됐던 한 주였습니다. 먼저 기아와 지난 주 K라면 말씀드렸는데, 삼양식품 불닭, 농심의 신라면에 대한 검색이 또 52주 내 신고점을 기록했습니다.또 농심, 빙그레, 삼성전자의 갤럭시, 지누스도 검색량이 많이 증가했던 모습이었고요.풀무원이 김밥 관련해서 주목을 받았던 한 주였는데, 풀무원에 대한 검색도 많이 늘었습니다. 또 롯데쇼핑의 롯데마트, 동서의 맥심커피, KT&G의 릴플러스도 검색량 신고점에 달하는 걸 확인할 수 있었습니다.릴플러스가 궐련형전자담배 기기라면 에쎄는 일반담배 종류은데, 에쎄 담배에 대한 검색량도 늘었던 모습이고요. 카카오의 카카오톡, CJ ENM의 티빙, 인바디도 리스트에 들어왔습니다.또 LG전자의 세탁기도 검색량이 늘었고요. 에이블씨엔씨의 어퓨의 경우엔 매각 뉴스가 나오면서 검색이 많이 된 것 같더라고요. 다른 기초 화장품 브랜드로는 아모레퍼시픽의 코스알엑스, 네오팜의 리얼베리어가 눈에 띄었습니다.미용기기에서는 슈링크로 유명한 클래시스의 볼뉴머가 검색량이 많이 늘었는데요, 좀 찾아보니까 러시아 쪽에서 검색이 증가한 걸로 보였습니다.색조화장품에서는 클리오의 페리페라가, 게임에서는 크래프톤의 펍지, 엔터에서는 하이브의 투어스가 검색량 신고점을 경신했습니다.유튜브에서는 구글에서와 마찬가지로 삼양식품의 불닭이 다시한번 검색량 상승랠리가 나타나고 있었고요. 농심의 신라면도 함께 검색이 또 늘었습니다. 마지막으로 가전제품 쪽에서는 삼성전자의 티비와 쿠쿠홀딩스의 쿠쿠를 소비자들이 많이 찾은 걸로 보였습니다.<앵커>삼성 갤럭시Z폴드7 검색량이 눈에 띕니다.신제품이 나와서 그런건가요?<박이경 연구원>이번 검색량 급증은 단순한 신제품 발표 이상의 의미가 있어요.지난 7월 9일에 삼성 갤럭시 Z 폴드7이 공개됐었습니다. 지난 25일에 정식 출시가 됐었고요.올해 폴드7은 전작들과는 달리, 하드웨어 사양보다는 소프트웨어와 AI 기능 중심의 마케팅으로 방향을 전환했어요.대표적으로 ‘삼성 노트 AI 요약’, ‘음성통화 중 실시간 통역’, ‘AI 기반 화면분할 자동화’ 같은 기능이 공개되면서 글로벌 언론에서도 접히는 스마트폰이 더 이상 기술 과시가 아니라 실사용 중심으로 진화했다는 평가를 받았던 부분이', '마케팅으로 방향을 전환했어요.대표적으로 ‘삼성 노트 AI 요약’, ‘음성통화 중 실시간 통역’, ‘AI 기반 화면분할 자동화’ 같은 기능이 공개되면서 글로벌 언론에서도 접히는 스마트폰이 더 이상 기술 과시가 아니라 실사용 중심으로 진화했다는 평가를 받았던 부분이 소비자들에게 어필이 된 것 같습니다.<앵커>영국 공항에서 삼성 폴더블폰 1만대가 도난을 당한 사건도 영향을 줬을 것 같습니다.보험에 들어놔서 손실은 없다던데, 아무튼 그만큼 탐난다는 것 아니겠어요. 글로벌 소비자들 반응이 어떻습니까?<박이경 연구원>한국에서뿐만 아니라 글로벌리 긍정적인 반응을 찾아볼 수 있었습니다. 먼저 미국에서는 예약 판매가 역대 최단기간 예약 물량 완판으로 이어졌는데요. 유튜브 언박싱 영상, 벤치마크 비교, 아이폰과의 전환 고민을 담은 콘텐츠가 동시다발적으로 올라왔고, 특히 멀티태스킹 기능, AI 통화 요약, 분할 스크린 자동 구성 기능에 대한 만족도가 높았던 것 같습니다.미국에서 삼성 갤럭시 Z 폴드에 대한 구글 검색 트렌드를 봐도, Z 폴드 시리즈 중에서 가장 흥행한 모델인 21년 출시했던 폴드3 때의 검색량을 앞서는 모습이었던 게 좀 두드러졌던 포인트입니다.<앵커>가격이 일반 스마트폰의 두배 아닙니까. 그런데도 미국 사전예약에서 초기 판매량이 50% 급증했다.스마트폰 강국, 인도에서도 인기가 많았다면서요?<박이경 연구원>인도에서는 이번 폴드7에 대한 관심이 특히 뜨거웠습니다. 실제로 과거 폴드3 공개 당시보다도 검색량이 훨씬 높았고, 단 48시간 만에 21만 대의 사전예약이 이뤄졌을 정도로 기대감이 큰 분위기였어요.커뮤니티에서는 ‘이젠 폴더블이 하나의 카테고리로 자리 잡았다’는 반응도 이어졌습니다.이번 모델을 두고는 특히 가격 대비 성능에 대한 논의가 활발했는데,인도 기준으로 가장 저렴한 모델도 한화 약 280만 원대라 부담스럽다는 의견이 많았습니다.그럼에도 불구하고 실제 흥행으로 이어졌다는 점은, 프리미엄 스마트폰에 대한 수요가 확대되고 있고, 소비자들의 구매 기준이 변하고 있다는 신호로도 해석됩니다.<앵커>2분기 기준 MX사업부 매출이 삼성전자에서 차지하는 비중이 40%에 달합니다. 특히 이번 플립 7 버전에는 삼성 파운드리가 만든 엑시노스 AP칩이 전량 탑재돼 있죠.  그만큼 많이 팔렸을 때 실적 개선효과가 크다라는 얘기가 될 것 같습니다.이번엔 가전쪽 얘기도 들어볼까요.LG 세탁기 검색이 늘었어요?<박이경 연구원>구글', '40%에 달합니다. 특히 이번 플립 7 버전에는 삼성 파운드리가 만든 엑시노스 AP칩이 전량 탑재돼 있죠.  그만큼 많이 팔렸을 때 실적 개선효과가 크다라는 얘기가 될 것 같습니다.이번엔 가전쪽 얘기도 들어볼까요.LG 세탁기 검색이 늘었어요?<박이경 연구원>구글 트렌드에서 ‘LG Washer’의 글로벌 검색량이 크게 올랐습니다. 북미 지역 위주로 검색이 많이 된 걸로 보였는데요.LG전자의 지역별 매출액을 보시면, 지난 1분기 기준으로 글로벌 매출이 60%가 넘고, 그중 미주는 5조 4천억원 이상의 매출을 창출하는데요, 글로벌 안에서 비중은 약 40% 수준입니다.폭발적인 성장을 하진 않지만 꽤나 차지하는 볼륨이 큰 핵심적인 지역인데요.지역별 관심도를 보셔도, 미국, 캐나다에서 검색이 많이 되는 걸 확인할 수 있습니다.<앵커>실제 LG전자 이번 실적에서도 매출은 늘어나는 걸로 나왔는데, 이익률은 나빠지고 있다면서요?<박이경 연구원>네, LG전자의 가전 부문은 2분기에도 매출 성장을 이어갔습니다.하지만 말씀하신 것처럼, 속을 들여다보면 수익성 압박이 분명히 존재합니다.특히 미국을 중심으로 가전 수요가 둔화되고, 프리미엄보다 중저가 제품을 선호하는 소비자들이 늘면서 제품 믹스에서 수익성이 나빠지고 있는 건데요.실제로 미국 최대 전자제품 유통 체인인 베스트바이에서 가장 잘 팔리는 LG 세탁기 모델 가격이 550달러 수준으로 비교적 저렴한 모델입니다.여기에 더해 철강·알루미늄 관세 이슈 같은 외부 변수로 원가 부담과 수익성 악화 우려도 커지고 있고요, 이런 불확실성 때문인지 주가도 다소 부진한 흐름을 보이고 있습니다.그럼에도 불구하고 구독형 모델 확대, 물류비 완화, 볼륨존 제품 확장 같은 전략을 통해 매출 성장세는 방어한 모습입니다.<앵커>자 이런 가운데 유튜브에서는 삼성TV가 검색량 최고치를 기록했다. 이건 무슨 일입니까?<박이경 연구원>유튜브에서 ‘Samsung TV’ 검색량이 1년 내 최고치를 기록했는데요,그 배경에는 단순한 TV 제품 자체보다는 ‘삼성 TV 플러스’라는 자체 콘텐츠 플랫폼의 확대가 있었던 걸로 보입니다.삼성 TV 플러스는 삼성 스마트 TV나 일부 스마트폰·태블릿에서 별도 요금 없이 이용할 수 있는 무료 스트리밍 서비스예요.넷플릭스나 디즈니플러스처럼 구독료를 내는 구조가 아니라, 광고 기반 플랫폼이라서 TV를 켜면 바로 실시간 채널이나 VOD를 무료로 시청할 수 있는 구조입니다.<앵커>아 TV', 'TV나 일부 스마트폰·태블릿에서 별도 요금 없이 이용할 수 있는 무료 스트리밍 서비스예요.넷플릭스나 디즈니플러스처럼 구독료를 내는 구조가 아니라, 광고 기반 플랫폼이라서 TV를 켜면 바로 실시간 채널이나 VOD를 무료로 시청할 수 있는 구조입니다.<앵커>아 TV 기계가 아니라 TV 채널이 검색량을 끌어올렸다.이게 갑자기 왜 늘어요 검색량이?<박이경 연구원>이 삼성 TV 플러스는 현재 전 세계적으로 700개 이상의 채널, 약 8,800만 명의 월간 이용자를 보유하고 있다고 하는데요,미국에서 최근 삼성 텔레비전 네트워크, STN이라고 하는 자체 플래그십 채널을 론칭하면서 콘서트 생중계, 인기 유튜버 콘텐츠 독점 편성, 지역 스포츠 중계까지 영역을 확장하고 있는 게 유튜브 검색량 급증과 맞물려 있는 것 같습니다.첫 콘텐츠로 조나스 브라더스의 투어 공연을 생중계했고요. 또 유명 유튜브 크리에이터들과 파트너십을 발표하면서 이 채널에서만 독점적으로 콘텐츠를 볼 수 있게 했습니다.<앵커>OTT들이나 통신사들이 긴장해야 될 소식 같습니다.삼성이 TV플러스를 강화하는 건 어떤 배경일까요?<박이경 연구원>삼성전자가 삼성 TV 플러스를 적극적으로 키우는 이유는,LG전자 실적 발표 내용에서도 느껴지듯이, TV가 이제는 단순히 하드웨어만으로는 차별화되기 어려운 시장이기 됐기 때문입니다.실제로 글로벌 TV 판매는 전체적으로 정체 혹은 하락세고, 패널이나 해상도, 디자인 같은 요소는 이미 상향 평준화된 상황입니다. 중국 업체들에게 점유율이 밀리고 있기도 하고요.이런 점에서 삼성 TV 플러스는 구독료 없이도 다양한 실시간 채널과 VOD를 제공하면서TV의 차별성과 락인 효과를 동시에 만들어내는 전략 플랫폼으로 작동하고 있어요.하드웨어만으로 경쟁하기 어려운 시대에, 삼성은 이제 TV를 ‘콘텐츠 기기’로 포지셔닝하면서 브랜드의 미래를 재설계하고 있다고 해석할 수 있겠습니다.이근형기자 lgh04@wowtv.co.kr'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'chunk_idx': 0, 'ticker': '삼성전자', 'original_idx': 5914, 'title': '갤럭시Z폴드7 검색량 신고점…"AI 활용성 진화"', 'url': 'https://www.hankyung.com/article/2025080527615', 'Date': '2025-08-05'}, {'original_idx': 5914, 'url': 'https://www.hankyung.com/article/2025080527615', 'ticker': '삼성전자', 'Date': '2025-08-05', 'chunk_idx': 1, 'title': '갤럭시Z폴드7 검색량 신고점…"AI 활용성 진화"'}, {'url': 'https://www.hankyung.com/article/2025080527615', 'chunk_idx': 2, 'title': '갤럭시Z폴드7 검색량 신고점…"AI 활용성 진화"', 'Date': '2025-08-05', 'ticker': '삼성전자', 'original_idx': 5914}, {'title': '갤럭시Z폴드7 검색량 신고점…"AI 활용성 진화"', 'chunk_idx': 3, 'url': 'https://www.hankyung.com/article/2025080527615', 'ticker': '삼성전자', 'Date': '2025-08-05', 'original_idx': 5914}, {'Date': '2025-08-05', 'ticker': '삼성전자', 'url': 'https://www.hankyung.com/article/2025080527615', 'chunk_idx': 4, 'original_idx': 5914, 'title': '갤럭시Z폴드7 검색량 신고점…"AI 활용성 진화"'}]}
results : {'ids': ['6cff046021a82a5d3c40145e7d8298f3', 'e3aff0f960468c3b6fecce49a4d0c880'], 'embeddings': None, 'documents': ['사진=연합뉴스\n\n삼성전자 주가가 5% 넘게 강세를 나타내고 있다. 22조원 규모의 반도체 위탁생산 계약 상대가 미국 전기차 업체 테슬라로 밝혀지자 투자심리에 불이 붙은 모습이다.28일 오후 2시 현재 삼성전자는 전 거래일 대비 3600원(5.46%) 뛴 6만9500원에 거래되고 있다. 주가는 장중 6만9700원까지 치솟으며 7만원대 탈환을 시도하고 있다. 장중 기록한 6만9700원은 연중 최고가이기도 하다.대규모 공급계약 소식에 매수세가 몰렸다. 이날 오전 삼성전자는 22조7648억원 규모의 반도체 위탁생산 공급계약을 체결했다고 공시했다. 지난해 연간 매출 300조8709억원의 7.6%에 달한다. 계약 기간은 이달 24일부터 2033년 12월31일까지로 수주 일자는 지난 26일이다. 다만 구체적 계약상대방은 \'경영상 비밀유지\'를 이유로 공개하지 않았다.공급계약 소식에 장 초반 삼성전자는 3%대 강세를 보였다. 이런 상황에서 삼성전자의 계약 상대가 테슬라로 밝혀지며 상승폭이 가팔라졌다. 일론 머스크 테슬라 최고경영자(CEO)는 27일(현지시간) 이날 자신의 엑스(X·옛 트위터)를 통해 "삼성전자의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라며 "이것의 전략적 중요성은 아무리 강조해도 지나치지 않다"고 말했다.머스크는 삼성전자가 현재 AI4 칩을 생산하고 있다고 밝혔다. 대만 TSMC는 설계가 막 마무리된 AI5 칩을 우선 대만에서 생산하고, 애리조나에서 만들 것이라고 머스크는 전했다.\n                    \n\n\n\n사진=일론 머스크 테슬라 CEO 엑스', '사진=일론 머스크 테슬라 CEO 엑스\n\n                업계에선 이번 계약으로 파운드리 사업 부문이 반전의 계기를 맞았다고 평가한다. 그간 파운드리 사업부는 적자를 이어오며 분사설이 불거지는 등 삼성전자의 \'아픈 손가락\'으로 꼽혀왔다. 블룸버그는 삼성전자가 테슬라와 반도체 공급계약을 체결한 것은 파운드리 사업의 2나노미터 세대 칩 생산이 회복됐음을 의미한다고 해석했다. 또 이번 계약을 통해 삼성 파운드리 매출을 연간 10% 늘어날 것이라고 전망했다.삼성증권 리서치센터는 이번 계약에 대해 "삼성전자와 관련 공급망에 긍정적인 뉴스"라고 평가했다. 이어 "기존 스마트폰 중심 고객 구조에서 데이터센터와 로봇 등으로 적용처가 다변화할 수 있고, 테일러팹 고객사를 확보해 미국 파운드리 사업의 지속 가능성을 높였기 때문"이라고 밝혔다.진영기 한경닷컴 기자 young71@hankyung.com'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'original_idx': 5809, 'ticker': '삼성전자', 'Date': '2025-07-28', 'title': "'23조 잭팟' 삼성전자, 머스크 화답에 날았다…개미들 '환호' [종목+]", 'chunk_idx': 0, 'url': 'https://www.hankyung.com/article/2025072863046'}, {'original_idx': 5809, 'url': 'https://www.hankyung.com/article/2025072863046', 'title': "'23조 잭팟' 삼성전자, 머스크 화답에 날았다…개미들 '환호' [종목+]", 'ticker': '삼성전자', 'Date': '2025-07-28', 'chunk_idx': 1}]}
results : {'ids': ['b0fd659b1bc2300659e73a9ba268ae0a'], 'embeddings': None, 'documents': ['07월 28일 삼성전자(005930)는 수주공시를 발표했다.◆삼성전자 수주공시 개요- 반도체 위탁생산 공급계약 22.76조 (매출액대비  7.6 %)삼성전자(005930)는 반도체 위탁생산 공급계약에 관한 단일판매ㆍ공급계약체결              을 28일에 공시했다.계약 상대방은 글로벌 대형기업이고, 계약금액은 22.76조 규모로 최근 삼성전자 매출액 300.87조 대비 약  7.6 % 수준이다. 이번 계약의 기간은 2025년 07월 24일 부터 2033년 12월 31일까지로 약 8년 5개월이다.한편 이번 계약수주는 2025년 07월 26일에 체결된 것으로 보고되었다.\n                    \n\n\n\n차트\n\n                한편, 오늘 분석한 삼성전자는 글로벌 IT기업으로 알려져 있다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'ticker': '삼성전자', 'title': '삼성전자 수주공시 - 반도체 위탁생산 공급계약 22.76조 (매출액대비  7.6 %)', 'Date': '2025-07-28', 'chunk_idx': 0, 'original_idx': 5680, 'url': 'https://www.hankyung.com/article/202507285312L'}]}
results : {'ids': ['4e6deabfc0b9daf6765f57ff247f38d2'], 'embeddings': None, 'documents': ['사진=연합뉴스\n\n                삼성전자가 28일 테슬라로부터 23조원 규모의 반도체 위탁생산(파운드리) 계약을 수주했다는 소식에 급등해 11개월 만에 \'7만전자\'를 회복했다.이날 오후 3시 15분 현재 코스피 시장에서 삼성전자는 전 거래일 대비 6.30% 오른 7만50원에 거래되고 있다. 삼성전자가 장중 7만원대에서 거래된 것은 지난해 9월 5일 이후 약 11개월 만이다.삼성전자는 이날 개장 전 글로벌 대형기업과 총 22조7648억원 규모의 파운드리 공급 계약을 체결했다고 공시했다.이후 계약 상대방이 테슬라임이 알려졌다. 일론 머스트 테슬라 최고경영자(CEO)는 직접 자신의 엑스(X) 계정을 통해 "삼성의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라고 밝혔다.그는 "테슬라가 생산 효율성 극대화를 돕는 것을 허용하기로 삼성이 동의했다"며 "내가 직접 진전 속도를 가속하기 위해 생산 라인을 둘러볼 것이기 때문에 이는 중요한 지점"이라고 강조했다.김수영 한경닷컴 기자 swimmingk@hankyung.com'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'original_idx': 5557, 'title': "[속보] 삼성전자, 테슬라 대규모 수주에 '7만전자' 찍었다", 'ticker': '삼성전자', 'url': 'https://www.hankyung.com/article/2025072865867', 'chunk_idx': 0, 'Date': '2025-07-28'}]}
results : {'ids': ['862065d286d9a7afd21a7dc51ddba4f1', 'ff75fb75dda03d5b86c18ce1aeca2e3e', '90608c6780d739ccd19626ef33739277'], 'embeddings': None, 'documents': ['영상 모듈 닫기', '<앵커>장 초반 6만전자로 내려갔던 삼성전자가 다시 7만 원대를 회복했습니다.SK하이닉스를 고집하던 외국인 투자자는 삼성전자로 눈을 돌렸고, 증권가에선 삼성전자의 목표가를 높이고 있는데요. 7만전자 굳히기에 들어갈지 마켓 딥다이브 최민정 기자가 정리합니다.<기자>SK하이닉스와 삼성전자의 성적이 바뀌고 있습니다.증권가에선 "이제 SK하이닉스를 팔고, 삼성전자를 사는 게 맞다"라는 말까지 나오고 있는데요.최근 한 달간의 성적을 살펴보면 삼성전자는 20% 가까이 올랐지만, SK하이닉스는 10% 하락했습니다.외국인의 변심이 컸는데요. 외국인은 삼성전자는 3조 원 가까이 사들인 반면, SK하이닉스는 매도 우위를 보이고 있습니다. 덕분에 삼성전자는 외국인 지분율도 50%대를 회복했는데요.테슬라와의 23조 원 수주가 결정적 역할을 했습니다. 적자를 내던 파운드리 사업 회복의 신호탄이란 분석이 나오는데요.납품하게 되는 AI6칩은 1초에 최대 6천 번의 연산이 가능해, 차랑용 부품뿐 아니라 테슬라의 휴머노이드 로봇 등에도 사용될 수 있습니다.미국 텍사스주 테일러 공장에서 생산돼, 미국 관세도 피할 수 있는데요. 증권가에선 삼성전자의 목표주가를 올리고 있습니다. 대신증권은 8만 8천 원을 제시하며 오늘 주가와 비교해 26% 더 오를 수 있다는 분석을 냈는데요.재무적 성과에 대한 측면보다는 향후 대형 수주로 이어질 수 있다는 점을 긍정적으로 바라봅니다.흥국증권은 "전사 기준 연 매출액의 1% 수준으로, 실적에 큰 영향을 주지 못하지만, 추가 수주 기대가 높아졌다"고 평가했는데요.다음 반등의 열쇠는 엔비디아의 HBM3E 퀄(품질) 테스트 통과입니다.엔비디아가 HBM3E 공급 부족으로 삼성전자의 퀄테스트를 앞당길 가능성이 크기 때문인데요.오늘 로이터는 엔비디아가 TSMC에 H20칩 30만 개를 추가 주문했다고 전하며, 중국 내 수요가 견조함을 확인했습니다.삼성전자의 3차 자사주 매입도 순조롭게 진행되고 있는데요.7월 들어 100만 주 씩 사들이며 벌써 9천억 원의 자사주를 매입했습니다. 삼성전자는 지난 8일 3조 9천억 원 규모의 3차 자사주를 취득하고, 이중 2조 8천억 원은 소각하겠다고 밝힌 바 있는데요.앞서 진행된 1·2차 자사주 매입도 완료하며 7조 원에 달하는 자사주를 매입한 겁니다.증권업계 관계자는 "7조 원 규모 자사주 매입·소각이 실제로 집행되면, 삼성전자의 주가 하방을 지지하는 효과가 있을 것"이라고 전합니다.이와', '원은 소각하겠다고 밝힌 바 있는데요.앞서 진행된 1·2차 자사주 매입도 완료하며 7조 원에 달하는 자사주를 매입한 겁니다.증권업계 관계자는 "7조 원 규모 자사주 매입·소각이 실제로 집행되면, 삼성전자의 주가 하방을 지지하는 효과가 있을 것"이라고 전합니다.이와 더해, 삼성전자 임원들도 자자수 매입을 지속하며 주가 상승에 힘을 싣고 있습니다.오는 31일 실적 콘퍼런스콜에 나서는 삼성전자가 어떤 전략을 내놓을지 지켜볼 필요가 있습니다.지금까지 마켓 딥다이브였습니다.최민정기자 choimj@wowtv.co.kr'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'title': '목표가 8만 8천원…"삼성전자, 추가 수주 기대" [마켓딥다이브]', 'Date': '2025-07-29', 'ticker': '삼성전자', 'chunk_idx': 0, 'url': 'https://www.hankyung.com/article/2025072990085', 'original_idx': 5922}, {'chunk_idx': 1, 'Date': '2025-07-29', 'ticker': '삼성전자', 'original_idx': 5922, 'title': '목표가 8만 8천원…"삼성전자, 추가 수주 기대" [마켓딥다이브]', 'url': 'https://www.hankyung.com/article/2025072990085'}, {'ticker': '삼성전자', 'url': 'https://www.hankyung.com/article/2025072990085', 'title': '목표가 8만 8천원…"삼성전자, 추가 수주 기대" [마켓딥다이브]', 'original_idx': 5922, 'chunk_idx': 2, 'Date': '2025-07-29'}]}
results : {'ids': ['599802e9d7cf8533dfb0b62a6cf7e8d6'], 'embeddings': None, 'documents': ['삼성전자, 올해 2분기 실적 발표\r\n                                \n\n\n\n삼성전자 서초사옥./한국경제 이솔 기자삼성전자 반도체 사업이 올해 2분기 4000억원의 영업이익을 거두면서 적자를 면했다. 작년 2분기 6조 4000억원대 영업이익과 비교하면 94% 급감한 수준이다. 2조원대 적자를 기록한 2023년 4분기 이후 역대 최저치다. 삼성전자 측은 "재고자산 평가 충당금 등 일회성 비용이 반영되면서 실적이 하락했다"고 했다.삼성전자는 연결기준으로 올해 2분기 매출 74조6000억원, 영업이익 4조7000억원을 각각 기록했다고 31일 공시했다. 전체 매출은 전년 동기 대비 0.67% 늘었지만, 영업이익은 55.23% 급감했다. 삼성전자는 지난 8일 이같은 수준의 잠정실적을 발표했고, 이날 확정실적을 공시했다. 이번 실적은 당초 시장 눈높이를 밑도는 수준이다.반도체 사업을 담당하는 DS(Device Solutions) 부문의 매출은 27조 9000억 원, 영업이익은 4000억 원을 기록했다.삼성전자는 메모리에서 HBM3E와 고용량 DDR5제품 판매 비중을 확대해 서버 수요가 증가했고 파운드리는 전 분기 대비 11%의 매출 성장이 있었다고 밝혔다. 영업이익은 매출 성장에도 불구하고, 메모리 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향에 따른 재고 충당 발생으로 감소했다고 설명했다.가전과 TV, 모바일 등을 포함한 디바이스경험(DX) 부문은 매출 43조 6000억 원, 영업이익 3조3000억 원을 기록했다. 스마트폰 신모델 출시 효과 감소와 TV 시장의 경쟁 심화로 전 분기 대비 매출이 16% 감소했고 영업이익도 1조4000억 원 감소했다.또한 원달러 환율이 하락하면서 달러 거래 비중이 높은 부품 사업을 중심으로 전분기 대비 약 5000억 원 수준의 부정적 영향이 있었다고 했다.김영은 기자 kye0218@hankyung.com'], 'uris': None, 'included': ['documents', 'metadatas'], 'data': None, 'metadatas': [{'ticker': '삼성전자', 'title': '"6.4조→0.4조" 삼성전자 반도체 영업이익 94% \'뚝\'', 'chunk_idx': 0, 'Date': '2025-07-31', 'url': 'https://magazine.hankyung.com/business/article/202507312901b', 'original_idx': 5798}]}

In [39]:
top_n_original[0]

{'title': '지수 5000의 열쇠, 삼성전자? [코스피 5000을 외치는 사람들]',
 'url': 'https://magazine.hankyung.com/business/article/202507249472b',
 'Date': '2025-07-29',
 'ticker': '삼성전자',
 'content': 'BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세'}

In [40]:
original_contents = list(map(lambda x: x['content'],top_n_original))

In [41]:
total_contents = ''.join(original_contents)

In [42]:
total_contents

'BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세삼성전자가 올해 하반기 확장현실(XR) 헤드셋(사진), 두 번 접는 ‘트리폴드폰’ 등 신제품을 출격시킨다. 인공지능(AI), 메디테크(의료기술), 냉난방공조(HVAC) 등 신사업을 강화하기 위해 추가 인수합병(M&A)도 추진한다.31일 삼성전자에 따르면 갤럭시 스마트폰 등 모바일 기기를 담당하는 모바일경험(MX)사업부는 올 2분기 매출 29조2000억원, 영업이익 3조1000억원을 기록했다. 1년 전보다 매출은 6.6%, 영업이익은 39% 늘었다. 갤럭시 S25 시리즈 등 프리미엄 제품과 갤럭시탭 10 시리즈 등 태블릿PC 판매가 늘어난 영향이다.삼성전자는 7월 출시한 갤럭시 Z폴드7·플립7 등 폴더블 신제품 판매를 늘리고 갤럭시 S25 시리즈의 마케팅을 강화해 3분기 실적을 끌어올릴 계획이다. XR 헤드셋, 트리폴드폰 등 차세대 혁신 제품을 올 연말까지 출시한다고 공개했다. 다니엘 아라우호 MX사업부 상무는 “구글과의 협력으로 구축한 XR 생태계를 기반으로 AI 기능을 적용한 헤드셋을 통해 갤럭시 제품군 경쟁력을 높일 것”이라고 말했다.삼성전자는 AI 기능을 적용한 TV와 가전 판매를 늘리는 동시에 미래 성장 동력으로 낙점한 HVAC 사업을 적극 키운다는 전략을 세웠다. 삼성전자는 HVAC 사업 확대를 위해 지난 5월 2조4000억원을 들여 독일 HVAC 기업인 플랙트그룹을 사들였다. 한인택 삼성전자 생활가전(DA)사업부 상무는 “지난해 7월 설립한 미국 레녹스와의 합작사, 플랙트그룹 등과 결합해 데이터센터 및 상업용 시장 공략에 나설 것”이라고 말했다.삼성전자는 올해 플랙트그룹과 함께 미국 마시모 오디오사업부, 미국 디지털 헬스케어 회사 젤스 등 세 차례에 걸쳐 M&A 소식을 발표하며 잠잠하던 M&A 엔진을 재가동했다. 박순철 삼성전자 경영지원실장(CFO)은 “다양한 신성장 분야의 후보 업체를 검토 중”이라며 추가 M&A를 예고했다. 신성장 분야는 AI, 공조, 메디테크, 로봇, 전장, 핀테크, 부품 등이다.김채연 기자 why29@hankyung.com영상 모듈 닫기사진=연합뉴스\n\n삼성전자 주가가 5% 넘게 강세를 나타내고 있다. 22조원 규모의 반도체 위탁생산 계약 상대가 미국 전기차 업체 테슬라로 밝혀지자 투자심리에 불이 붙은 모습이다.28일 오후 2시 현재 삼성전자는 전 거래일 대비 3600원(5.46%) 뛴 6만9500원에 거래되고 있다. 주가는 장중 6만9700원까지 치솟으며 7만원대 탈환을 시도하고 있다. 장중 기록한 6만9700원은 연중 최고가이기도 하다.대규모 공급계약 소식에 매수세가 몰렸다. 이날 오전 삼성전자는 22조7648억원 규모의 반도체 위탁생산 공급계약을 체결했다고 공시했다. 지난해 연간 매출 300조8709억원의 7.6%에 달한다. 계약 기간은 이달 24일부터 2033년 12월31일까지로 수주 일자는 지난 26일이다. 다만 구체적 계약상대방은 \'경영상 비밀유지\'를 이유로 공개하지 않았다.공급계약 소식에 장 초반 삼성전자는 3%대 강세를 보였다. 이런 상황에서 삼성전자의 계약 상대가 테슬라로 밝혀지며 상승폭이 가팔라졌다. 일론 머스크 테슬라 최고경영자(CEO)는 27일(현지시간) 이날 자신의 엑스(X·옛 트위터)를 통해 "삼성전자의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라며 "이것의 전략적 중요성은 아무리 강조해도 지나치지 않다"고 말했다.머스크는 삼성전자가 현재 AI4 칩을 생산하고 있다고 밝혔다. 대만 TSMC는 설계가 막 마무리된 AI5 칩을 우선 대만에서 생산하고, 애리조나에서 만들 것이라고 머스크는 전했다.\n                    \n\n\n\n사진=일론 머스크 테슬라 CEO 엑스07월 28일 삼성전자(005930)는 수주공시를 발표했다.◆삼성전자 수주공시 개요- 반도체 위탁생산 공급계약 22.76조 (매출액대비  7.6 %)삼성전자(005930)는 반도체 위탁생산 공급계약에 관한 단일판매ㆍ공급계약체결              을 28일에 공시했다.계약 상대방은 글로벌 대형기업이고, 계약금액은 22.76조 규모로 최근 삼성전자 매출액 300.87조 대비 약  7.6 % 수준이다. 이번 계약의 기간은 2025년 07월 24일 부터 2033년 12월 31일까지로 약 8년 5개월이다.한편 이번 계약수주는 2025년 07월 26일에 체결된 것으로 보고되었다.\n                    \n\n\n\n차트\n\n                한편, 오늘 분석한 삼성전자는 글로벌 IT기업으로 알려져 있다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.사진=연합뉴스\n\n                삼성전자가 28일 테슬라로부터 23조원 규모의 반도체 위탁생산(파운드리) 계약을 수주했다는 소식에 급등해 11개월 만에 \'7만전자\'를 회복했다.이날 오후 3시 15분 현재 코스피 시장에서 삼성전자는 전 거래일 대비 6.30% 오른 7만50원에 거래되고 있다. 삼성전자가 장중 7만원대에서 거래된 것은 지난해 9월 5일 이후 약 11개월 만이다.삼성전자는 이날 개장 전 글로벌 대형기업과 총 22조7648억원 규모의 파운드리 공급 계약을 체결했다고 공시했다.이후 계약 상대방이 테슬라임이 알려졌다. 일론 머스트 테슬라 최고경영자(CEO)는 직접 자신의 엑스(X) 계정을 통해 "삼성의 새로운 대규모 텍사스 공장이 테슬라의 차세대 AI6 칩 생산을 전담하게 될 것"이라고 밝혔다.그는 "테슬라가 생산 효율성 극대화를 돕는 것을 허용하기로 삼성이 동의했다"며 "내가 직접 진전 속도를 가속하기 위해 생산 라인을 둘러볼 것이기 때문에 이는 중요한 지점"이라고 강조했다.김수영 한경닷컴 기자 swimmingk@hankyung.com영상 모듈 닫기삼성전자, 올해 2분기 실적 발표\r\n                                \n\n\n\n삼성전자 서초사옥./한국경제 이솔 기자삼성전자 반도체 사업이 올해 2분기 4000억원의 영업이익을 거두면서 적자를 면했다. 작년 2분기 6조 4000억원대 영업이익과 비교하면 94% 급감한 수준이다. 2조원대 적자를 기록한 2023년 4분기 이후 역대 최저치다. 삼성전자 측은 "재고자산 평가 충당금 등 일회성 비용이 반영되면서 실적이 하락했다"고 했다.삼성전자는 연결기준으로 올해 2분기 매출 74조6000억원, 영업이익 4조7000억원을 각각 기록했다고 31일 공시했다. 전체 매출은 전년 동기 대비 0.67% 늘었지만, 영업이익은 55.23% 급감했다. 삼성전자는 지난 8일 이같은 수준의 잠정실적을 발표했고, 이날 확정실적을 공시했다. 이번 실적은 당초 시장 눈높이를 밑도는 수준이다.반도체 사업을 담당하는 DS(Device Solutions) 부문의 매출은 27조 9000억 원, 영업이익은 4000억 원을 기록했다.삼성전자는 메모리에서 HBM3E와 고용량 DDR5제품 판매 비중을 확대해 서버 수요가 증가했고 파운드리는 전 분기 대비 11%의 매출 성장이 있었다고 밝혔다. 영업이익은 매출 성장에도 불구하고, 메모리 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향에 따른 재고 충당 발생으로 감소했다고 설명했다.가전과 TV, 모바일 등을 포함한 디바이스경험(DX) 부문은 매출 43조 6000억 원, 영업이익 3조3000억 원을 기록했다. 스마트폰 신모델 출시 효과 감소와 TV 시장의 경쟁 심화로 전 분기 대비 매출이 16% 감소했고 영업이익도 1조4000억 원 감소했다.또한 원달러 환율이 하락하면서 달러 거래 비중이 높은 부품 사업을 중심으로 전분기 대비 약 5000억 원 수준의 부정적 영향이 있었다고 했다.김영은 기자 kye0218@hankyung.com한경유레카는 AI알고리즘들의 개별 종목 투자의견(점수)을 한눈에 볼 수 있는 투자 플랫폼입니다. \'한경유레카\' 앱을 내려받으면 종목별 투자의견과 나에게 맞는 AI알고리즘을 추천받을 수 있습니다. \n\n\n\n\n\n                28일 삼성전자가 강세다. 삼성전자는 오후 13시 50분 전일대비 5.1% 오른 6만9400원에 거래되며 7만전자를 코앞에 두고 있다.삼성전자가 마지막으로 7만원 대에 장을 마감한 것은 지난해 9월이 마지막이다.당일 삼성전자는 공시를 통해 반도체 위탁생산 공급계약 소식을 전했다. 글로벌 대형기업과 약 22조 7600억원 규모의 계약으로 계약기간은 2025년 7월 24일부터 2033년 12월 31일까지이다.AI알고리즘들의 투자의견을 모아 종합의견을 제시하는 한경유레카는 삼성전자에 대해 7월 17일 매수의견을 제시한바 있다.한경유레카에서는 관심 종목을 등록하면 AI알고리즘들의 종합의견을 무료로 확인할 수 있으며 매매의견이 변동되면 오전 8시 30분에 앱을 통해 알림 서비스를 제공한다.한경닷컴 뉴스룸 open@hankyung.com사진=연합뉴스\n\n                코스피지수가 7일 장중 3210선에서 상승세를 유지하고 있다. 삼성전자가 애플의 차세대 칩을 미국 파운드리(반도체 수탁생산) 공장에서 생산하기로 하면서 강세를 보이는 점이 지수 상승을 뒷받침하는 것으로 보인다. 다만 도널드 트럼프 미국 대통령이 반도체에 100% 품목별 관세를 부과하겠다고 밝힌 데 따른 경계감에 상단은 제한된 모습이다.이날 오전 11시11분 현재 코스피지수는 전 거래일보다 12.75포인트(0.4%) 오른 3210.89를 기록하고 있다. 지수는 이날 0.52% 오름세로 출발 후 0.3~0.7% 사이에서 등락률을 보이고 있다. 유가증권시장에서 개인이 128억원 매수 우위인 반면 외국인과 기관이 각각 420억원 95억원 매도 우위다.트럼프 대통령이 반도체에 약 100% 품목별 관세를 부과할 것이란 소식에 투자자들의 경계 심리가 발동한 것으로 풀이된다. 그럼에도 지수가 상승세를 이어가는 건 국내 시가총액 1위인 삼성전자가 강세를 보이고 있기 때문으로 보인다. 삼성전자는 애플의 차세대 칩을 생산하게 됐다는 소식에 2%대 강세로 다시 \'7만전자\'를 회복했다. 장중 한때 3% 넘게 상승하기도 했다. 이밖에 코스피 시가총액 상위 종목 중 LG에너지솔루션, 현대차, 두산에너빌리티, HD현대중공업, 네이버 등이 오르는 반면 SK하이닉스, 삼성바이오로직스, 한화에어로스페이스, KB금융, 기아, 셀트리온 등이 내리고 있다.같은 시각 코스닥지수는 전 거래일보다 0.17포인트(0.02%) 오른 803.66으로 800선을 사수하고 있다. 코스닥시장에서도 외국인과 기관이 각각 469억원과 191억원 매도 우위인 반면 개인은 794억원 매수 우위다.코스닥 시총 상위 종목 중 파마리서치, 레인보우로보틱스, 휴젤, 클래시스 등이 오르는 반면 알테오젠, 에코프로비엠, 펩트론, 에코프로, HLB, 리가켐바이오, 삼천당제약, 에이비엘바이오 등이 내리고 있다.고정삼 한경닷컴 기자 jsk@hankyung.com영상 모듈 닫기※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.\n\n\n\n\n\n                투자수익률 상위 1％ 고수들이 4일 오전 삼성전자를 집중 매수하고 있다. 반면 두산에너빌리티는 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 삼성전자, 한화엔진, HD한국조선해양 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％ 투자자의 매매동향을 취합한 결과다.오전 10시 현재 삼성전자가 7만50원으로 이전 거래일보다 1.67% 올랐다. 앞서 삼성은 미국 전기차업체 테슬라와 165억달러(약 23조원) 규모의 인공지능(AI) 반도체 공급 계약을 체결했다고 지난달 28일 공시했다. 김영건 미래에셋증권 연구원은 지난 1일 보고서에서 이번 계약 관련, “AI 빅테크로부터 기술력을 공식 인정받은 사례”라며 “고대역폭메모리(HBM) 사업 부진도 단숨에 시간 문제로 전략했다”고 호했다. 지난달 31일 한국산 제품에 대한 미국의 상호관세율(15%) 확정도 불확실성 완화에 기여했다.한화엔진은 3만5300원으로 0.43% 상승했다. 한화엔진은 지난 2분기 338억원의 영업이익을 냈다고 지난달 24일 발표했다. 전년 동기 대비 81.4% 증가한 규모다.\n                    \n\n\n\n\n                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 두산에너빌리티, 에이치브이엠, 파마리서치 순이다. 주가는 각각 직전 거래일 대비 4.89%, -13.53%, 0.54% 변동했다.에이치브이엠은 우주항공 등 미래산업용 특수금속을 만드는 회사로 급등 후 차익실현 매물이 쏟아지고 있다. 지난 1일에는 일론 머스크 테슬라 CEO의 스페이스X와 제품 공급계약을 체결했다고 밝히면서 상한가로 직행했다. \n                    \n\n\n\n\n                이태호 기자 thlee@hankyung.com삼성전자의 주가가 최근 약세를 벗고 반등세를 보이기 시작했다. 가장 큰 촉매는 최고경영진의 법적 불확실성 제거로, 이재용 회장이 최종 무죄 판결을 받으며 경영 전면에 나설 수 있는 기틀이 마련됐다는 점이다. 이 소식이 전해진 직후 주가는 즉각 반등했으며, 투자자들은 경영 안정성과 전략 재정비 기대감을 반영했다.또한 최근 사상 최대 규모인 약 165억 달러에 달하는 파운드리(위탁생산) 계약 체결 소식이 주가 상승의 실질적 동력을 제공했다. 계약의 상대방과 조건은 장기간 비공개로 유지되지만, 대외 수익성과 기술력에 대한 기대가 급격히 증가하며 증권 시장에서 긍정적인 반응을 끌어냈다.여기에 AI 반도체 수요 기대도 맞물렸다. 글로벌 AI 프로젝트에서 핵심적인 역할을 하는 고대역폭 메모리(HBM) 매출 증가 기대와 함께 삼성의 파운드리 경쟁력에 대한 인식이 강해지면서, 투자심리가 개선되었다.\n\n\n\n\n \n\n외국인 투자자의 매수세도 뒤따랐다. 낮은 밸류에이션과 저가 매수 흐름 속에서 글로벌 자금이 유입되며 기술주 랠리를 견인했고, 삼성전자도 그 수혜 종목으로 이름을 올렸다.기대와 달리 2분기 실적은 아직 약점으로 작용하고 있다. 미국과 중국 간 기술·무역 리스크로 인해 AI 메모리 칩 수요가 지연되며 이익이 큰 폭 감소할 전망이다. 특히 엔비디아 인증 지연과 중국 수출 제한이 삼성의 성장성 회복에 제약을 주고 있다는 분석이 나온다.그러나 법률 리스크 해소와 대규모 수주 계약, 그리고 AI 메모리 및 파운드리 영역에서의 중장기 성장 기대가 투자자 심리에 긍정적으로 작용하며 주가 흐름에 방향성을 부여하고 있다는 해석이 나온다. 다만 경쟁사 대비 기술적 우위 확보 여부, 수주 계약의 실제 실현 가능성, 글로벌 공급망 환경 변화 등에 대한 면밀한 관찰이 필요한 시점이다.한화엔진, LIG넥스원, 이렘, 다날, KB금융무료상담반도체 소부장(소재·부품·장비) 관련주가 일제히 급등했다. 삼성전자가 테슬라의 차세대 인공지능(AI) 칩을 수탁생산한다는 소식에 수혜 기대가 커지면서다.\n\n\n\n\n\n                30일 한국거래소에 따르면 최근 3거래일 동안 KRX 반도체지수는 3% 넘게 올랐다. 전체 KRX지수 중 세 번째로 높은 상승률이다. 특히 반도체 장비 제조사 원익IPS 주가는 같은 기간 21.2% 급등했다. 반도체용 식각액 공급 업체 솔브레인과 후공정 업체인 두산테스나 주가도 각각 23.6%, 24.4% 뛰었다.삼성전자 공급망에 속한 소부장 종목의 상승세가 두드러졌다는 평가가 나온다. 테슬라의 자율주행 차량과 휴머노이드 로봇에 들어가는 차세대 AI칩 생산을 삼성전자가 맡기로 하면서다. 2033년까지 22조7647억원어치를 공급하는 삼성 반도체 역사상 최대 규모 계약이다.반도체 소부장주를 집중 매수하는 세력은 주로 기관투자가다. 3거래일간 원익IPS를 126억원어치 사들였다. 같은 기간 솔브레인도 192억원어치 순매수했다. 반도체 소부장주 주가가 올 들어서도 지지부진하자 투자 매력이 더 높아졌다는 게 증권가 해석이다. 주요 반도체 소부장주는 2021년 고점 대비 40~50%가량 조정받은 상태다. 운용사 관계자는 “반도체 소부장주의 기관 수급이 빈 상황에서 삼성전자의 테슬라 수주 소식이 나오자 매수세가 강하게 들어왔다”며 “반도체 소부장주의 밸류에이션(실적 대비 주가 수준) 매력이 높다”고 진단했다.증권가에서는 반도체 소부장주 상승세가 하반기에도 이어질 것으로 전망했다. 대신증권은 원익IPS와 솔브레인을 삼성전자 대규모 수주에 따른 대표적 수혜주로 제시했다.삼성증권은 두산테스나와 하나마이크론을 주목했다. 추후 삼성전자의 파운드리(반도체 수탁생산) 가동률이 높아지면 수혜를 볼 것으로 봤다. 이종욱 삼성증권 연구원은 “파운드리 가동률이 전반적으로 올라가면 이들 종목이 우선 주목받을 것”이라고 전망했다. 시장에선 삼성전자가 테슬라 물량을 내년 2분기부터 본격 생산할 것으로 보고 있다. 현재 짓고 있는 미국 텍사스 테일러 공장이 생산지다.류은혁 기자 ehryu@hankyung.com한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 SK하이닉스 삼성전기 LG이노텍 삼성에스디에스한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.삼성전자 한화오션 두산테스나 NHN 원익IPS삼성전자가 이르면 2027년부터 자체 설계한 고성능 이미지센서를 애플에 공급한다. 미국 오스틴 파운드리(반도체 수탁생산) 공장에서 생산한 제품이 들어간다. 지난달 테슬라와 22조7000억원 규모 인공지능(AI) 칩 파운드리 계약을 체결한 데 이어 ‘스마트폰 제왕’ 애플에도 핵심 반도체를 공급하는 데 성공했다. \n                    \n\n\n\n\n\n\n이미지 크게보기영상 모듈 닫기한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.SK하이닉스 카카오페이 다날 한화시스템 솔브레인2023년 5월 만난 이재용 삼성전자 회장(왼쪽), 일론 머스크 테슬라 최고경영자. / 사진=삼성전자 제공\n\n                삼성전기 주가가 불을 뿜었다. 테슬라가 삼성전자에 대규모로 위탁생산을 맡긴 인공지능(AI) 반도체용 기판인 플립칩 볼그리드어레이(FC-BGA)를 공급하는 데 따른 수혜 가능성이 뒤늦게 관심을 끌면서다. FC-BGA 외에도 삼성전기는 다중적층세라믹콘덴서(MLCC)와 카메라모듈을 테슬라에 공급하고 있다.31일 한국거래소에 따르면 전일 삼성전기는 10.55% 급등한 15만1900원에 거래를 마쳤다. 장중 한때 오름폭이 14.05%까지 커지기도 했다.외국인과 기관이 삼성전기 주식을 쓸어 담았다. 외국인의 삼성전기 주식 순매수 금액은 1127억원이다. 삼성전자(5888억원)에 이어 두 번째로 많이 샀다. 기관도 585억원어치를 사들였다.외국인과 기관의 매수세가 몰린 배경은 삼성전자와 테슬라의 ‘AI 반도체 동맹’이다. 삼성전자는 지난 26일 글로벌 대형기업에 22조7648억원어치 반도체를 위탁생산해 공급하기로 하는 계약을 맺었다고 28일 공시했다. 공시에는 계약 상대방이 명시되지 않았지만, 테슬라의 최고경영자(CEO) 일론 머스크가 엑스(X·옛 트위터)를 통해 “삼성의 텍사스 대형 신공장은 테슬라의 차세대 AI6 칩 생산에 전념하게 될 것”이라며 테슬라가 계약 상대방임을 드러냈다. 머스크 CEO는 “(계약금액인) 165억달러(약 22조8000억원) 수치는 단지 최소액”이라며 “실제 생산량은 몇배 더 높을 것 같다”고도 말했다.\n                    \n\n\n\n이재용 삼성전자 회장(왼쪽 세 번째)이 지난해 5월 미국 실리콘밸리에 위치한 삼성전자 북미 반도체연구소에서 일론 머스크 테슬라 최고경영자(CEO, 오른쪽 네 번째)와 만나 기념 촬영하고 있는 모습. 사진=삼성전자 제공영상 모듈 닫기한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.두산에너빌리티 NHN KCP 풀무원 펩트론 한텍한경유레카는 한국경제신문의 디지털 미디어인 한경닷컴에서 개발한 개별 종목에 대한 인공지능(AI) 알고리즘 업체의 투자 의견을 종합한 \'AI 컨센서스\'를 제공하는 서비스입니다. \'한경유레카\' 앱은 구글 플레이 스토어 혹은 앱스토어에서 내려받을 수 있습니다.\n\n\n\n\n\n삼성전자가 약 22.8조원 규모의 반도체 위탁생산 계약을 체결했다.고객사는 공개되지 않았지만 일론 머스크가 직접 삼성에 AI6 칩 생산을 맡겼다고 밝혀 주목된다.해당 칩은 엔비디아 H100과 유사한 LLM용 ASIC 칩으로, HBM3E가 탑재된다.테슬라 도조 시스템용 추가 수주 가능성도 제기된다. 이 소식에 두산테스나, 에이디테크놀로지 등 반도체 관련주들이 급등했으며, 삼성전자의 파운드리·HBM 사업 확대 기대감도 커지고 있다.\n\n\n\n\n\n종목추천 알고리즘들의 종합플랫폼 한경유레카 내에서 가치투자클럽을 구독하면 매일 공시의 주요종목에 대한 분석글과 추천종목을 실시간으로 문자로 받아볼 수 있다.본 글은 투자 참고용입니다.에이디테크놀로지 LG씨엔에스 NAVER 동진쎄미켐 한선엔지니어링삼성전자 서초사옥의 삼성 깃발. 뉴스1삼성 갤럭시 S25 울트라와 애플 아이폰16 프로. 두 제품은 같은 플래그십 라인이지만 갤럭시가 카메라 성능이 네 배 이상 앞선다. 비밀은 반도체에 있다. 갤럭시는 삼성 시스템LSI사업부가 세계 최초로 개발한 2억 화소 이미지센서를 적용한 반면 애플은 소니(4800만 화소) 제품을 공급받고 있다.\n                    \n\n\n\n\n\n\n이미지 크게보기영상 모듈 닫기사진=연합뉴스\n\n                삼성전기가 8%대 강세를 보이고 있다. 테슬라가 삼성전자에 약 22조8000억원 규모의 AI6 반도체 위탁생산을 맡긴 데 따른 수혜가 기대된다는 분석이 나오면서다.30일 오전 9시19분 현재 삼성전기는 전일 대비 1만1300원(8.22%) 오른 14만8700원에 거래되고 있다.대신증권이 삼성전자가 테슬라에 AI6 칩을 위탁생산해 공급하는 과정에서 삼성전기의 FC-BGA 사업이 수혜를 받을 것이라는 분석을 내놓은 영향으로 보인다.박강호 대신증권 연구원은 “삼성전기는 이전에 테슬라에 공급된 반도체인 AI4와 AI5를 만드는 데 필요한 FC-BGA를 공급하고 있다”며 “이번 공급 계약으로 테슬라와 삼성전자, 그리고 삼성전기의 협력 관계가 더 강화될 것”이라고 예상했다.그는 “FC-BGA를 넘어 카메라, MLCC 등 삼성전기의 모든 사업에서 테슬라와의 관계가 구축·강화되는 중으로 판단된다”고 덧붙였다.한경우 한경닷컴 기자 case@hankyung.com삼성전자, 빅테크와 22조 7647억원 계약 체결\n단일 수주 사상 최대 규모\n美매체, 테슬라·삼성 협상 보도※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.\n\n\n\n\n\n                투자수익률 상위 1％ 고수들이 5일 오전 삼성SDI를 집중 매수하고 있다. 반면 삼성전자는 가장 많이 팔았다.미래에셋엠클럽에 따르면 투자 고수들은 이날 개장 직후부터 오전 10시까지 국내 증시에서 삼성SDI, HD현대중공업, SK바이오팜 등을 많이 순매수했다. 미래에셋증권 계좌로 주식을 거래하면서 최근 한 달 수익률 상위 1％ 투자자의 매매 동향을 취합한 결과다.오전 10시 현재 삼성SDI가 21만5500원으로 이전 거래일보다 11.25% 급등했다. 2차전지 종목 전반의 강세 속에 돋보이는 움직임이다. 주민우 NH투자증권 연구원은 전날 낸 2차전지 산업 월간 보고서에서 “테슬라의 실적설명회 등에서 에너지저장장치(ESS)의 견조한 수요를 재확인했다”면서 “국내 셀 업체들의 신규 수주로 이어질 전망”이라고 낙관했다.투자 고수들이 두 번째로 많이 매수한 HD현대중공업은 47만500원으로 1.51% 상승했다. 다음으로 많이 산 SK바이오팜은 예상을 웃도는 실적 발표에 힘입어 17.48% 뛰었다. SK바이오팜은 지난 2분기 매출이 전년 동기 대비 31.6% 성장한 1763억원을 기록했다고 이날 밝혔다. 영업이익은 137.6% 증가한 619억원이다.\n                    \n\n\n\n\n                같은 시간 고수들이 가장 많이 순매도하고 있는 종목은 삼성전자, 삼성중공업, 두산 순이다. 주가는 각각 직전 거래일 대비 1.15%, 6.04%, 8.9% 변동했다.\n                    \n\n\n\n\n                이태호 기자 thlee@hankyung.com삼성전자 서초사옥. 사진=연합뉴스'

## 요약하기

### 요약함수 호출

버전 2

In [54]:
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

In [55]:
def summarize_top_articles_2(total_contents: str,ticker:str) -> pd.DataFrame:
    # doc : 10개 > max_iter = 3
    # doc : 30 개 > max_iter = 5
    # doc : 20개 >   max_iter = 5
    agent = NewsSummaryAgent(max_iters=10)
    runnable = build_summary_graph(agent)

    rows = []
    doc = total_contents

    state = {"article": doc, "summary": "", "feedback": "", "iteration": 0}
    result = runnable.invoke(state)

    print("✅ 실행 결과 키:", result.keys())
    # 여기서 final_summary 반드시 존재해야 함(위 패치 기준)
    final_summary = result.get("final_summary")
    if not final_summary:
        print("❌ final_summary 없음. 디버그용 전체 상태:", result)
        # 계속 진행할지, 실패로 표기할지 선택

    rows.append({
        "ticker": ticker,
        "date": '2025-07-30', # 위 조회 기준일자로 연동시켜서 바꿀 예정
        "summary": final_summary,
        "feedback": result.get("last_feedback", "피드백 없음"),
    })

    return pd.DataFrame(rows)

In [56]:
result_df = summarize_top_articles_2(total_contents,ticker='삼성전자')

summart : ✅ 주요 요약
- 삼성전자, 테슬라와 22조 원 규모 반도체 위탁생산 계약 체결
  삼성전자는 테슬라와 22조 원 규모의 반도체 위탁생산 계약을 체결했으며, 이는 삼성의 새로운 텍사스 공장에서 테슬라의 차세대 AI6 칩을 생산하는 계약이다.

- 삼성전자, 다양한 신제품 출시 및 신사업 강화 계획
  삼성전자는 XR 헤드셋, 트리폴드폰 등 혁신 제품을 연말까지 출시할 예정이며, AI, 메디테크, HVAC 등 신사업 강화를 위해 추가 M&A를 추진 중이다.

- 삼성전자, 2분기 실적 발표 및 반도체 사업 성장 전략
  삼성전자는 2분기 매출 74조 6천억 원, 영업이익 4조 7천억 원을 기록했으며, 반도체 사업에서는 HBM3E와 DDR5 제품 판매 비중을 확대하고 있다.

🔑 키워드
- 삼성전자
- 테슬라
- 반도체 위탁생산
- AI6 칩
- XR 헤드셋
- 트리폴드폰
- M&A
- HVAC
- 2분기 실적
- HBM3E
- DDR5
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약에서 삼성전자의 주가 변동이나 투자자 반응과 관련된 내용이 빠져 있습니다. 또한, 코스피 지수와 관련된 정보도 포함되지 않았습니다.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

피드백:
포괄성 측면에서, 요약에 삼성전자의 주가 변동이나 투자자 반응에 대한 정보가 포함되면 더 좋을 것입니다. 예를 들어, 삼성전자의 주가가 테슬라와의 계약 소식에 어떻게 반응했는지, 그리고 코스피 지수의 변동 상황도 요약에 추가되면 독자가 더 포괄적인 이해를 할 수 있을 것입니다. 이러한 추가 정보는 요약의 깊이를 더하고 독자에게 더 많은 배경 정보를 제공합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- **삼성전자, 테슬라와 22조 원 규모 반도체 위탁생산 계약 체결**\n  삼성전자는 테슬라와 22조 원 규모의 반도체 위탁생산 계약을 체결했으며, 이는 삼성의 새로운 텍사스 공장에서 테슬라의 차세대 AI6 칩을 생산하는 계약이다. 이 소식에 삼성전자 주가는 11개월 만에 7만 원대를 회복하며 강세를 보였다.\n\n- **삼성전자, 다양한 신제품 출시 및 신사업 강화 계획**\n  삼성전자는 XR 헤드셋, 트리폴드폰 등 혁신 제품을 연말까지 출시할 예정이며, AI, 메디테크, HVAC 등 신사업 강화를 위해 추가 M&A를 추진 중이다. 이러한 전략은 삼성전자의 장기적인 성장 동력을 확보하기 위한 것으로 평가된다.\n\n- **삼성전자, 2분기 실적 발표 및 반도체 사업 성장 전략**\n  삼성전자는 2분기 매출 74조 6천억 원, 영업이익 4조 7천억 원을 기록했으며, 반도체 사업에서는 HBM3E와 DDR5 제품 판매 비중을 확대하고 있다. 그러나 메모리 사업의 재고 자산 평가 충당금으로 인해 영업이익은 감소했다.\n\n- **코스피 지수 및 투자자 반응**\n  삼성전자의 테슬라와의 계약 소식에 코스피 지수는 상승세를 보였으며, 투자자들은 삼성전자의 장기적인 성장 가능성에 긍정적인 반응을 보였다. 특히, 외국인 투자자들의 매수세가 강화되며 기술주 랠리를 견인했다.\n\n🔑 키워드\n- 삼성전자\n- 테슬라\n- 반도체 위탁생산\n- AI6 칩\n- XR 헤드셋\n- 트리폴드폰\n- M&A\n- HVAC\n- 2분기 실적\n- HBM3E\n- DDR5\n- 주가 변동\n- 코스피 지수\n- 투자자 반응'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 좋음
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

피드백:
전체적으로 요약은 원문 기사의 주요 내용을 잘 반영하고 있으며, 중요한 정보가 빠짐없이 포함되어 있습니다. 또한, 불필요한 표현 없이 간결하게 작성되어 있으며, 문장 구성도 자연스럽고 명확합니다. 특정 종목인 삼성전자에 대한 내용만 존재하여 일관성도 잘 유지되고 있습니다. 전반적으로 개선이 필요하지 않은 좋은 요약입니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])

In [46]:
result_df

,ticker,date,summary,feedback
0,삼성전자,2025-07-30,"✅ 주요 요약\n\n- **삼성전자, 테슬라와 22조 원 규모 반도체 위탁생산 계약...","- 정확성: 좋음\n <reason> [요약 내용이 원문 기사와 일치하며, 주요 ..."

In [ ]:
# doc =50, max_iter = 10, 일관성 넣으니 3번 돌고 끝!
print(result_df.summary.values[0])

✅ 주요 요약

- **삼성전자, 테슬라와 22조 원 규모 반도체 위탁생산 계약 체결**
  삼성전자는 테슬라와의 대규모 계약을 통해 AI6 칩을 생산하며, 이는 삼성의 파운드리 사업 확대에 기여할 것으로 기대됨.

- **삼성전자 주가 상승, 11개월 만에 7만 원대 회복**
  테슬라와의 계약 소식으로 삼성전자 주가는 급등하며 7만 원대를 회복, 이는 투자자들의 긍정적인 반응을 이끌어냄.

- **삼성전자, 신제품 출시 및 M&A로 미래 성장 동력 강화**
  삼성전자는 XR 헤드셋과 트리폴드폰 등 차세대 혁신 제품을 연말까지 출시할 계획이며, AI, 메디테크, HVAC 등 신사업을 강화하고 다양한 분야에서 M&A를 추진하여 성장 동력을 확보하고 있음.

- **삼성전자 2분기 실적 발표, 반도체 사업의 도전과 성과**
  삼성전자는 2분기 매출 74조6000억원, 영업이익 4조7000억원을 기록했으며, 반도체 사업은 4000억원의 영업이익을 거두며 적자를 면함. 이는 메모리 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향으로 인한 도전 과제가 있었음.

🔑 키워드
- 삼성전자
- 테슬라
- 반도체 위탁생산
- AI6 칩
- 파운드리 사업
- 주가 상승
- M&A
- 신제품 출시
- 신사업 강화
- 2분기 실적
- 반도체 사업 성과 및 도전

In [ ]:
# doc : 20개, max_iter = 5, 일관성 평가항목 존재
print(result_df.summary.values[0])

✅ 주요 요약

- **삼성전자, 테슬라와 22조 원 규모 반도체 위탁생산 계약 체결**
  삼성전자는 테슬라와의 대규모 반도체 위탁생산 계약을 통해 AI6 칩을 생산하며, 이는 삼성의 파운드리 사업 확장에 중요한 역할을 할 것으로 예상됨.

- **삼성전자 주가, 테슬라 계약 소식에 7만 원대 회복**
  테슬라와의 계약 발표 후 삼성전자 주가는 급등하며 11개월 만에 7만 원대를 회복, 투자자들의 긍정적 반응을 이끌어냄.

- **삼성전자, 2분기 실적 발표: 영업이익 4조7000억 원 기록**
  삼성전자는 2분기 매출 74조6000억 원, 영업이익 4조7000억 원을 기록하며 전년 동기 대비 영업이익이 55.23% 감소했으나, 반도체 사업에서 적자를 면함.

- **삼성전자, 신성장 분야 M&A 및 혁신 제품 출시 계획**
  삼성전자는 AI, 메디테크, HVAC 등 신사업 강화를 위해 추가 M&A를 추진하며, XR 헤드셋과 트리폴드폰 등 혁신 제품 출시로 시장 경쟁력을 높일 계획임.

🔑 키워드
- 삼성전자
- 테슬라
- 반도체 위탁생산
- AI6 칩
- 파운드리
- 주가 상승
- 2분기 실적
- M&A
- 혁신 제품
- XR 헤드셋
- 트리폴드폰

In [ ]:
# doc : 30 , max_iter = 5, 평가항목 일관성 넣기 전
print(result_df.summary.values[0])

삼성전자는 최근 테슬라와 22조 원 규모의 반도체 위탁생산 계약을 체결하며 주가가 급등, 11개월 만에 '7만전자'를 회복했습니다. 이번 계약은 삼성의 텍사스 공장에서 테슬라의 차세대 AI6 칩을 생산하는 것으로, 이는 삼성의 파운드리 사업 확장에 중요한 전환점이 될 것으로 보입니다. 이 계약은 삼성의 기술력과 대외 신뢰도를 높이며, 글로벌 반도체 시장에서의 입지를 강화할 것으로 기대됩니다.

삼성전자는 AI, 메디테크, 냉난방공조(HVAC) 등 신사업 강화를 위해 추가 인수합병(M&A)을 추진 중이며, XR 헤드셋과 트리폴드폰 등 혁신 제품 출시를 계획하고 있습니다. 이러한 신제품들은 삼성의 기술력과 시장 경쟁력을 높이는 데 기여할 것으로 기대됩니다. 특히, AI 기능을 적용한 제품들은 삼성의 미래 성장 동력으로 자리 잡을 전망입니다.

2분기 실적 발표에서는 매출 74조6000억원, 영업이익 4조7000억원을 기록했으나, 전년 대비 영업이익이 55.23% 감소하며 시장 기대치를 밑돌았습니다. 이는 반도체 사업의 재고 자산 평가 충당금과 비메모리 사업의 대중 제재 영향 때문으로 분석됩니다.

코스피 지수는 삼성전자의 강세에 힘입어 상승세를 보였으나, 여전히 많은 투자자들이 손실을 보고 있는 상황입니다. 삼성전자 외에도 카카오, 네이버, LG화학 등 주요 기업들이 손실을 기록하고 있으며, 이는 시장의 불확실성을 반영합니다.

삼성전자의 이번 계약과 신사업 확장 계획은 향후 성장 가능성을 높이며, 주가 상승의 주요 요인으로 작용하고 있습니다. 시장은 삼성의 파운드리 사업 확장과 AI 관련 제품의 성공 가능성에 주목하고 있으며, 이는 삼성의 장기적인 성장 전략에 긍정적인 영향을 미칠 것으로 보입니다. 또한, 삼성전자는 HVAC 사업 확대를 위해 독일의 플랙트그룹을 인수하는 등 적극적인 M&A 활동을 통해 신성장 동력을 확보하고 있습니다.

In [ ]:
# 10개 추출했을 때의 요약문, 일관성 넣기 전
print(result_df.summary.values[0])

✅ 주요 요약

- **삼성전자, 대규모 반도체 위탁생산 계약 체결**
  삼성전자는 약 22.8조원 규모의 반도체 위탁생산 계약을 체결하며, 테슬라와의 AI 반도체 공급 계약을 통해 반도체 사업 확장을 기대하고 있습니다. 이는 삼성 반도체 역사상 최대 규모의 계약으로 주목받고 있습니다.

- **다양한 신제품 출시 및 M&A로 사업 다각화 추진**
  삼성전자는 XR 헤드셋, 트리폴드폰 등 혁신 제품을 출시하고, AI, 메디테크, HVAC 등 신사업 강화를 위해 적극적인 M&A를 추진 중입니다. 특히, HVAC 사업 확장을 위해 독일의 플랙트그룹을 인수하며, 관련 시장 공략을 강화하고 있습니다.

- **반도체 소부장주, 삼성전자 수주 소식에 급등**
  삼성전자의 테슬라 AI 칩 수주 소식으로 반도체 소부장 관련주들이 급등했으며, 이는 기관투자가들의 매수세를 이끌어내고 있습니다.

🔑 키워드
- 삼성전자
- 반도체 위탁생산
- 테슬라
- AI 칩
- M&A
- XR 헤드셋
- HVAC 사업
- 반도체 소부장주
- 기관투자가

**개선 포인트:**
- 삼성전자의 HVAC 사업 확장 및 관련 M&A 활동을 포함하여 포괄성을 강화했습니다. 이를 통해 독자가 삼성전자의 전반적인 전략을 더 잘 이해할 수 있도록 했습니다.

# 과거 버전

In [204]:
import pandas as pd
from datetime import datetime, timedelta
# cross-encoder
from sentence_transformers import CrossEncoder
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

# 1. 모델 준비 (CrossEncoder for Re-ranking) # 예시 모델 하나 생성
rerank_model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# 2. 최근 5일치 필터링 함수
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max()
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

# 3. huggingface 모델 이용.
def rerank_articles(df: pd.DataFrame,ticker:str ,query: str, top_k: int = 5):
    task_df= df[df.ticker == ticker]
    docs = task_df['content'].tolist()
    # 모델 이용?? 
    pairs = [(query, doc) for doc in docs]
    scores = rerank_model.predict(pairs)
    
    task_df_2 = task_df.copy()
    task_df_2['score'] = scores
    return task_df_2.sort_values(by='score', ascending=False).head(top_k)

# 4. 전체 요약 실행 함수
def summarize_top_articles(df: pd.DataFrame, ticker: str, query: str, top_k: int = 5):
    recent_df = get_recent_articles(df, ticker)
    top_df = rerank_articles(recent_df, query=query,ticker=ticker, top_k=top_k)

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)

    results = []
    for _, row in top_df.iterrows():
        state = {
            "article": row['content'],
            "summary": "",
            "feedback": "",
            "iteration": 0
        }
        result = runnable.invoke(state)


        print("✅ 실행 결과 타입:", type(result))
        print("✅ 실행 결과 키 목록:", result.keys())
        print("✅ 실행 결과 전체 내용:", result)

        if "final_summary" not in result:
            print("❌ final_summary 키가 없습니다. 중단합니다.")
            continue  # 또는 raise Exception("final_summary 없음")

        print(f'실행 결과 : {result}')
        results.append({
            "ticker": row['ticker'],
            "date": row['Date'],
            "header": row['header'],
            "url": row['url'],
            "summary": result["final_summary"], 
             "feedback": result.get("last_feedback", "피드백 없음")
        })
    return pd.DataFrame(results)

In [55]:
query = "우리금융지주 관련 시황"
ticker = "우리금융지주"  # 예시
result_df = summarize_top_articles(cusA_news_df, ticker=ticker, query=query, top_k=3)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음 <reason> 원문의 내용을 정확하게 반영하고 있음. </reason>
- 포괄성: 부족함 <reason> 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용이 누락되었음. </reason>
- 간결성: 좋음 <reason> 불필요한 표현 없이 요약 내용을 간결하게 전달하였음. </reason>
- 문장구성: 좋음 <reason> 문장이 자연스럽고 명확하게 구성되어 있음. </reason>

[피드백]
요약의 포괄성이 부족한 점이 아쉽습니다. 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용을 요약에 포함시키면 더욱 완벽한 요약이 될 것 같습니다. 이 부분을 고려하여 요약을 수정해보시는 것을 추천드립니다.
✅ '정확성' 평가 통과
❌ '포괄성' 평가에서 좋음이 아님
[should_stop] next_step = no

KeyError: 'Input to PromptTemplate is missing variables {\'"foo"\', \'"properties"\'}.  Expected: [\'"foo"\', \'"properties"\', \'article\', \'feedback\', \'summary\'] Received: [\'article\', \'summary\', \'feedback\']\nNote: if you intended {"foo"} to be part of the string and not a variable, please escape it with double curly braces like: \'{{"foo"}}\'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT '

In [35]:
def summarize_top_articles(total_contents :str):

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)
    results = []
    
    doc = total_contents

    state = {
        "article": doc['content'],
        "summary": "",
        "feedback": "",
        "iteration": 0
    }
    result = runnable.invoke(state)


    print("✅ 실행 결과 타입:", type(result))
    print("✅ 실행 결과 키 목록:", result.keys())
    print("✅ 실행 결과 전체 내용:", result)

    if "final_summary" not in result:
        print("❌ final_summary 키가 없습니다.")

    print(f'실행 결과 : {result}')
    results.append({
        "ticker": doc['ticker'],
        "date": doc['Date'],
        "header": doc['title'],
        "url": doc['url'],
        "summary": result["final_summary"], 
            "feedback": result.get("last_feedback", "피드백 없음")
    })
    return pd.DataFrame(results)