## 1. 필요 라이브러리 호출

In [83]:
# 환경설정
import os
import sys
import time
from tqdm import tqdm
import nest_asyncio
nest_asyncio.apply()
from dotenv import load_dotenv

load_dotenv()
# duckdb
import duckdb

# 데이터 전처리
import re
import pandas as pd
import numpy as np
import polars as pl
from datetime import datetime, timedelta
from copy import deepcopy

# 데이터 수집
import requests
from bs4 import BeautifulSoup

# 시각화
import matplotlib.pyplot as plt

# VectorDB 저장
from hashlib import md5
from langchain_community.vectorstores.utils import filter_complex_metadata # ChromaDB가 제공하지 못하는 데이터 형태를 자동으로 string처리
from datetime import datetime, timezone

## LLM 활용
# LLM 활용을 위한 dict형태 구축
from collections import defaultdict


# 1. LLM 모델 세팅 (OpenAI)
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

from langchain_openai import ChatOpenAI
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3)


# 임베딩 라이브러리
from langchain_openai import OpenAIEmbeddings # openai 
from FlagEmbedding import BGEM3FlagModel # M3
from langchain_huggingface import HuggingFaceEmbeddings

# 크로마DB
from langchain_chroma import Chroma


# ㄱRe-ranker 모델 활용
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

# 1. 테스트셋 확인
[step]<br>

1) query 생성 : openai(gpt-3.5-turbo) 모델을 이용해서 query 생성
2)

In [3]:
news_df = pd.read_csv('../data/korean_news_data.csv',encoding='UTF-8',index_col=[0])

In [4]:
news_df.head()

  stock                                            content
0  삼성전자  이재명 정부 정책 수혜주로 분류되던 고배당주 상장지수펀드(ETF)에서 자금이 빠져나...
1  삼성전자  【 앵커멘트 】이어폰을 구입할 때 주변 소음을 완벽하게 차단하는 노이즈 캔슬링이 기...
2  삼성전자  [YTN 라디오 신율의 뉴스정면승부]■ 방송 : FM 94.5 (17:00~19:0...
3  삼성전자  삼성전자 모델이 5일 기존 식기세척기보다 에너지 소비효율 등급은 한 단계 높이고, ...
4  삼성전자  대표이사 직속 미래로봇추진단, AI 기반 보행·조작 기술 등 핵심 분야 인력 충원이...

In [5]:
news_df.content[0]

'이재명 정부 정책 수혜주로 분류되던 고배당주 상장지수펀드(ETF)에서 자금이 빠져나가고 있다. 세제개편안에 담긴 배당소득 분리과세 관련 내용이 시장 기대감을 꺾은 것으로 풀이된다.5일 한국경제신문에 따르면 세제개편안이 발표된 후인 이달 1~4일 개인투자자는 국내 상장 배당 ETF 28개를 총 72억원어치 순매도했다. 올 들어 자금이 꾸준히 유입됐지만 처음으로 순유출로 전환했다.배당주 ETF 가운데 가장 규모가 큰 \'PLUS 고배당주\'는 고점 대비 9.1% 하락했다. TIGER 은행고배당플러스TOP10(-9.0%), KODEX 고배당주(-8.4%) 등 주요 배당 ETF의 낙폭도 컸다.배당주 ETF는 대표적인 정책 수혜 펀드로 분류됐다. 배당소득 분리과세가 이뤄질 것이라는 기대감에서다. 배당소득 분리과세는 투자자가 받은 배당소득을 종합과세 대상에서 제외해 분리과세하는 게 핵심이다.시장에서는 분리과세가 도입되면 기업 배당이 늘고, 투자자 세금 부담도 줄어들 것으로 기대했지만 분위기가 달라졌다.정부가 발표한 세제개편안에 따르면 배당소득 분리과세 적용 대상은 전년 대비 현금 배당이 감소하지 않은 상장법인 중 배당 성향이 40% 이상이거나, 배당 성향이 25% 이상이면서 직전 3년 대비 5% 이상 배당이 증가한 기업으로 특정됐다. 삼성전자, SK하이닉스 등 주요 종목 투자자도 혜택을 보기 어려운 조건이다.한시화 한화투자증권 연구원은 "지난 6월 대선 이후 자금이 대거 유입된 대표적인 ETF가 고배당주와 금융주"라며 "기존 개편안보다 까다로운 분리과세 방안이 발표되면서 투자심리가 악화했다"고 분석했다.(사진=연합뉴스)'

In [6]:
def querying(data):
  template = """
  <instruction>
  다음은 뉴스 기사 본문과 해당 기사에 매핑된 종목명(티커)입니다.
  당신의 임무는 뉴스 본문을 보고, 뉴스의 주요 내용을 사용자가 검색할 때 입력할 수 있는 질문을 하나 생성하세요.
  질문은 간결하고, 뉴스의 핵심 사실을 묻도록 작성하세요.

  [뉴스 본문]
  {news_content}  

  </instruction>
<example>
[뉴스 본문]
이재명 정부 정책 수혜주로 분류되던 고배당주 상장지수펀드(ETF)에서 자금이 빠져나가고 있다. 세제개편안에 담긴 배당소득 분리과세 관련 내용이 시장 기대감을 꺾은 것으로 풀이된다.5일 한국경제신문에 따르면 세제개편안이 발표된 후인 이달 1~4일 개인투자자는 국내 상장 배당 ETF 28개를 총 72억원어치 순매도했다. 올 들어 자금이 꾸준히 유입됐지만 처음으로 순유출로 전환했다.배당주 ETF 가운데 가장 규모가 큰 \'PLUS 고배당주\'는 고점 대비 9.1% 하락했다. TIGER 은행고배당플러스TOP10(-9.0%), KODEX 고배당주(-8.4%) 등 주요 배당 ETF의 낙폭도 컸다.배당주 ETF는 대표적인 정책 수혜 펀드로 분류됐다. 배당소득 분리과세가 이뤄질 것이라는 기대감에서다. 배당소득 분리과세는 투자자가 받은 배당소득을 종합과세 대상에서 제외해 분리과세하는 게 핵심이다.시장에서는 분리과세가 도입되면 기업 배당이 늘고, 투자자 세금 부담도 줄어들 것으로 기대했지만 분위기가 달라졌다.정부가 발표한 세제개편안에 따르면 배당소득 분리과세 적용 대상은 전년 대비 현금 배당이 감소하지 않은 상장법인 중 배당 성향이 40% 이상이거나, 배당 성향이 25% 이상이면서 직전 3년 대비 5% 이상 배당이 증가한 기업으로 특정됐다. 삼성전자, SK하이닉스 등 주요 종목 투자자도 혜택을 보기 어려운 조건이다.한시화 한화투자증권 연구원은 "지난 6월 대선 이후 자금이 대거 유입된 대표적인 ETF가 고배당주와 금융주"라며 "기존 개편안보다 까다로운 분리과세 방안이 발표되면서 투자심리가 악화했다"고 분석했다.(사진=연합뉴스)'

[생성한 질문]
세제개편안 발표 이후 고배당주 ETF 자금 흐름은 어떻게 변했나?
</example>

"""

  prompt = ChatPromptTemplate.from_template(template)

  # 3. 체인 구성
  chain = prompt | llm | StrOutputParser()

  # 4. 실행 예시
  query = chain.invoke({"news_content": data})
  return query

In [8]:
news_lst = []

In [9]:
for i in tqdm(range(news_df.shape[0])):
    try :
        news_dict=dict()
        news_dict['stock'] = news_df.stock[i]
        news_dict['content'] = news_df.content[i]
        news_dict['query'] = querying(news_df.content[i])
        news_lst.append(news_dict)
    except:
        news_dict=dict()
        news_dict['stock'] = news_df.stock[i]
        news_dict['content'] = news_df.content[i]
        news_dict['query'] = 'exceed'
        news_lst.append(news_dict)
        continue

100%|██████████| 5558/5558 [2:04:48<00:00,  1.35s/it]

In [11]:
pd.DataFrame(news_lst).to_csv('pair_set.csv',encoding='utf-8')

In [2]:
pair_set = pd.read_csv('../data/news_training_df.csv',index_col=[0])

In [6]:
pair_set.stock.value_counts()

stock
Bank of Montreal                 91
Benchmark Electronics Inc        86
Empire State Realty Trust Inc    83
Inter & Co Inc                   78
PDF Solutions Inc                77
                                 ..
Caseys General Stores Inc         1
Apellis Pharmaceuticals Inc       1
Schlumberger NV                   1
Cytokinetics Inc                  1
Century Therapeutics Inc          1
Name: count, Length: 2653, dtype: int64

In [76]:
target_lst = list(pd.unique(pair_set.stock))

In [86]:
pair_set[pair_set['stock'].isin(target_lst[:10])].stock.value_counts()

stock
삼성전자         30
LG에너지솔루션     27
SK하이닉스       26
삼성바이오로직스     26
KB금융         26
두산에너빌리티      26
HD현대중공업      23
셀트리온         22
한화에어로스페이스    20
현대차          20
Name: count, dtype: int64

## 2. embedding 모델 (w/ bge-M3 모델)

In [8]:
model = BGEM3FlagModel('BAAI/bge-m3',  
                       use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

Fetching 30 files: 100%|██████████| 30/30 [00:00<00:00, 170500.16it/s]

## 3. VectorDB 저장

In [3]:
openai_embedding = OpenAIEmbeddings(model="text-embedding-3-large")
bge_embedding = BGEM3FlagModel('BAAI/bge-m3',use_fp16=True)
persist_directory = "../VectorDB/chroma_news_db"

Fetching 30 files: 100%|██████████| 30/30 [00:00<00:00, 340078.70it/s]

In [4]:
from langchain_community.embeddings import HuggingFaceBgeEmbeddings

bge_embedding = HuggingFaceBgeEmbeddings(
    model_name="BAAI/bge-m3",
    model_kwargs={"device": "cpu"},          # "cpu" | "cuda" | "mps"
    encode_kwargs={"normalize_embeddings": True, "batch_size": 64}
    # query_instruction / embed_instruction는 기본적으로 생략 (M3는 보통 무지시로 OK)
)

/var/folders/xq/zzsj9f116r7brgm2wm610nx00000gn/T/ipykernel_25593/1010925.py:3: LangChainDeprecationWarning: The class `HuggingFaceBgeEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  bge_embedding = HuggingFaceBgeEmbeddings(

In [5]:
vectordb_openai = Chroma(
    persist_directory=persist_directory,
    embedding_function=openai_embedding,
    collection_name="SLM_News_openai")

In [6]:

vectordb_bge = Chroma(
    persist_directory=persist_directory,
    embedding_function=bge_embedding,
    collection_name="SLM_News_bge")

In [7]:
def labeling(data,ticker:str):
  template = """
  <instruction>
  다음은 뉴스 기사 본문과 해당 기사에 매핑된 종목명(티커)입니다.
  당신의 임무는 기사 본문이 해당 종목에 대한 기사인지 여부를 판별하는 것입니다.

  규칙:
  - 1 : 뉴스 내용이 해당 종목 기사 내용임.
     예: 종목명이 기사에 등장하고, 그 종목의 실적, 주가, 제품, 사건, 경영, 산업 동향 등과 밀접한 관련이 있음.
     예) 종목의 실적/주가/사업/이슈/계약/정책/규제/소송/리스크/전망 등.
     예) 섹터 기사라도 해당 종목이 사례/주요 구성원으로 명시적 언급되고 맥락에 기여.
  - 0 : 뉴스 내용이 해당 종목과 직접적으로 관련이 없음  
     예: 종목명이 전혀 등장하지 않거나, 비슷한 용어를 가진 단어의 내용이 등장하더라도 다른 주제가 메인인 경우.
     예) 피상적 나열(태그/키워드/꼬리말 광고)만 존재, 타사 이슈가 중심.
     
  출력 형식:
  - 숫자 1 또는 0만 출력
  </instruction>

  예시:
  ---
  [티커] 삼성전자
  [본문] 삼성전자가 2분기 실적 호조를 발표하며 주가가 3% 상승했다.
  [정답] 1
  ---
  [티커] 삼성전자
  [본문] 미국 증시가 기술주 중심으로 상승세를 보였다. 애플과 구글 주가가 상승했다.
  [정답] 0
  ---

  다음 데이터를 분류하세요.

  [티커] {ticker_name}
  [본문] {news_content}
  [정답]
  """

  prompt = ChatPromptTemplate.from_template(template)

  # 3. 체인 구성
  chain = prompt | llm | StrOutputParser()

  # 4. 실행 예시
  query = chain.invoke({"news_content": data,'ticker_name' : ticker})
  return query

In [8]:
def pick_splitter_by_length(text_len: int) -> RecursiveCharacterTextSplitter:
    """
    뉴스 본문의 길이에 따라 적절한 텍스트 분할기를 반환합니다.
    """
    if text_len <= 1200:
        # 짧은 기사 → 굳이 자르지 않고 1덩어리로 처리
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=0,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 10_000:
        # 중간 길이 → 일반적인 1,200자 기준으로 분할
        return RecursiveCharacterTextSplitter(
            chunk_size=1200,
            chunk_overlap=150,
            separators=["\n\n", "\n", " ", ""]
        )
    elif text_len <= 50_000:
        # 긴 기사 → 덩어리를 좀 더 키움
        return RecursiveCharacterTextSplitter(
            chunk_size=1800,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )
    else:
        # 초장문 → 더 크게 자르되, 요약도 고려 (이건 후속 처리 필요)
        return RecursiveCharacterTextSplitter(
            chunk_size=2000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )

In [9]:
# 2. 문서 리스트 생성 (chunk + metadata 포함)
def make_documents(df):
    docs = []

    for idx, row in tqdm(df.iterrows()):
        text = row["content"]
        splitter = pick_splitter_by_length(len(text))
        chunks = splitter.split_text(text)
        for i, chunk in enumerate(chunks):
            label = labeling(chunks,row['stock'])
            metadata = {
#               "title": row["header"],
#                "url": row["url"],
#                "Date": row["Date"],
                "ticker": row.get("stock", "None"),
                "chunk_idx": i,
                "original_idx": idx,
                'label' : label  #labeling한 결과를 넣자!! 
            }
            time.sleep(0.1)
            docs.append(Document(page_content=chunk, metadata=metadata))

    return docs

In [10]:
def make_doc_id(d: Document) -> str:
    """
    url + chunk_idx(없으면 0) + 시간
    """
    run_utc = datetime.now(timezone.utc)
    base = f"{d.metadata.get('url','')}_{d.metadata.get('chunk_idx', 0)}_{run_utc}"
    return md5(base.encode("utf-8")).hexdigest()

def chunks(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

## Label작업 수행

In [50]:
for ticker in target_lst[:10]:
    print(f"========= ticker {ticker} 진행 중~ =============")
    #task_1_df = get_recent_articles(cusA_news_df,ticker=ticker,days = 30)
    #task_1_df['Date'] = task_1_df.Date.astype('str')
    task_1_df = pair_set[pair_set.stock==ticker]
    # document 만들기
    
    task_1_docs = make_documents(task_1_df)
    length_docs = len(task_1_docs)
    print(f'각 {ticker} 별 docs의 개수 : {length_docs}')
    BATCH = 64  # 상황에 맞게 조절

    for docs in tqdm(chunks(task_1_docs, BATCH), total=(len(task_1_docs) + BATCH - 1) // BATCH):

        ids = [make_doc_id(d) for d in docs]
        vectordb_openai.add_documents(documents=docs, ids=ids)
        time.sleep(0.1)

========= ticker 삼성전자 진행 중~ =============

30it [00:52,  1.76s/it]

각 삼성전자 별 docs의 개수 : 59

100%|██████████| 1/1 [00:03<00:00,  3.64s/it]

========= ticker SK하이닉스 진행 중~ =============

26it [00:33,  1.29s/it]

각 SK하이닉스 별 docs의 개수 : 42

100%|██████████| 1/1 [00:02<00:00,  2.97s/it]

========= ticker LG에너지솔루션 진행 중~ =============

27it [00:33,  1.24s/it]

각 LG에너지솔루션 별 docs의 개수 : 47

100%|██████████| 1/1 [00:02<00:00,  2.75s/it]

========= ticker 삼성바이오로직스 진행 중~ =============

26it [00:31,  1.22s/it]

각 삼성바이오로직스 별 docs의 개수 : 40

100%|██████████| 1/1 [00:02<00:00,  2.14s/it]

========= ticker 한화에어로스페이스 진행 중~ =============

20it [00:27,  1.37s/it]

각 한화에어로스페이스 별 docs의 개수 : 33

100%|██████████| 1/1 [00:03<00:00,  3.07s/it]

========= ticker 현대차 진행 중~ =============

20it [00:25,  1.26s/it]

각 현대차 별 docs의 개수 : 31

100%|██████████| 1/1 [00:03<00:00,  3.61s/it]

========= ticker KB금융 진행 중~ =============

26it [00:41,  1.60s/it]

각 KB금융 별 docs의 개수 : 47

100%|██████████| 1/1 [00:02<00:00,  2.75s/it]

========= ticker 두산에너빌리티 진행 중~ =============

26it [00:36,  1.39s/it]

각 두산에너빌리티 별 docs의 개수 : 46

100%|██████████| 1/1 [00:02<00:00,  2.19s/it]

========= ticker HD현대중공업 진행 중~ =============

23it [00:34,  1.48s/it]

각 HD현대중공업 별 docs의 개수 : 40

100%|██████████| 1/1 [00:01<00:00,  1.99s/it]

========= ticker 셀트리온 진행 중~ =============

22it [00:31,  1.44s/it]

각 셀트리온 별 docs의 개수 : 38

100%|██████████| 1/1 [00:02<00:00,  2.78s/it]

In [18]:
for ticker in target_lst[:10]:
    print(f"========= ticker {ticker} 진행 중~ =============")
    #task_1_df = get_recent_articles(cusA_news_df,ticker=ticker,days = 30)
    #task_1_df['Date'] = task_1_df.Date.astype('str')
    task_1_df = pair_set[pair_set.stock==ticker]
    # document 만들기
    
    task_1_docs = make_documents(task_1_df)
    length_docs = len(task_1_docs)
    print(f'각 {ticker} 별 docs의 개수 : {length_docs}')
    BATCH = 64  # 상황에 맞게 조절

    for docs in tqdm(chunks(task_1_docs, BATCH), total=(len(task_1_docs) + BATCH - 1) // BATCH):
        #print(docs)
        ids = [make_doc_id(d) for d in docs]
        vectordb_bge.add_documents(documents=docs, ids=ids)
        time.sleep(0.1)

========= ticker 삼성전자 진행 중~ =============

30it [00:49,  1.64s/it]

각 삼성전자 별 docs의 개수 : 59

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [01:16<00:00, 76.15s/it]

========= ticker SK하이닉스 진행 중~ =============

26it [00:32,  1.23s/it]

각 SK하이닉스 별 docs의 개수 : 42

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:37<00:00, 37.03s/it]

========= ticker LG에너지솔루션 진행 중~ =============

27it [00:39,  1.46s/it]

각 LG에너지솔루션 별 docs의 개수 : 47

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:41<00:00, 41.05s/it]

========= ticker 삼성바이오로직스 진행 중~ =============

26it [00:33,  1.28s/it]

각 삼성바이오로직스 별 docs의 개수 : 40

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:34<00:00, 34.65s/it]

========= ticker 한화에어로스페이스 진행 중~ =============

20it [00:27,  1.38s/it]

각 한화에어로스페이스 별 docs의 개수 : 33

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:28<00:00, 28.06s/it]

========= ticker 현대차 진행 중~ =============

20it [00:25,  1.25s/it]

각 현대차 별 docs의 개수 : 31

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:26<00:00, 26.50s/it]

========= ticker KB금융 진행 중~ =============

26it [00:39,  1.50s/it]

각 KB금융 별 docs의 개수 : 47

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:42<00:00, 42.87s/it]

========= ticker 두산에너빌리티 진행 중~ =============

26it [00:39,  1.51s/it]

각 두산에너빌리티 별 docs의 개수 : 46

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:41<00:00, 41.23s/it]

========= ticker HD현대중공업 진행 중~ =============

23it [00:33,  1.44s/it]

각 HD현대중공업 별 docs의 개수 : 40

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:35<00:00, 35.86s/it]

========= ticker 셀트리온 진행 중~ =============

22it [00:30,  1.40s/it]

각 셀트리온 별 docs의 개수 : 38

  0%|          | 0/1 [00:00<?, ?it/s]/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
100%|██████████| 1/1 [00:36<00:00, 36.09s/it]

In [11]:
print("Number of documents in DB:", vectordb_openai._collection.count())

Number of documents in DB: 423

In [12]:
print("Number of documents in DB:", vectordb_bge._collection.count())

Number of documents in DB: 423

## 7. cross-encoder 모델(w/langchain 예시)

In [13]:
def _dcg_at_k(labels, k=30):
    L = np.asarray(labels)[:k]
    if L.size == 0: return 0.0
    discounts = 1.0 / np.log2(np.arange(2, L.size + 2))
    return float(np.sum(L * discounts))

def ndcg_at_k(labels, k=30):
    labels = np.asarray(labels)
    dcg  = _dcg_at_k(labels, k)
    idcg = _dcg_at_k(np.sort(labels)[::-1], k)
    return 0.0 if idcg == 0 else dcg / idcg

def precision_at_k(labels, k=30):
    L = np.asarray(labels)[:k]
    return float(L.mean()) if L.size else 0.0

def recall_at_k(labels, total_relevant, k=30):
    if not total_relevant or total_relevant <= 0: return 0.0
    return float(np.sum(np.asarray(labels)[:k])) / float(total_relevant)

def mrr_at_k(labels, k=30):
    L = np.asarray(labels)[:k]
    hit = np.where(L > 0)[0]
    return 0.0 if hit.size == 0 else 1.0 / (hit[0] + 1)

def map_at_k(labels, total_relevant, k=30):
    L = np.asarray(labels)[:k]
    if L.sum() == 0: return 0.0
    precisions, hit = [], 0
    for i, y in enumerate(L, start=1):
        if y:
            hit += 1
            precisions.append(hit / i)
    denom = max(1, min(total_relevant if total_relevant is not None else int(L.sum()), k))
    return float(np.sum(precisions) / denom)

def eval_reranker_chunk(pool_df, ranked_df, k=30, rank_col="rank", score_col="relevance_score"):
    # 1) 풀: label만 필요 (score/rank 불필요)
    total_rel_pool = int(
        pd.to_numeric(pool_df["label"], errors="coerce").fillna(0).clip(0,1).sum()
    )
    print(f'total_rel_pool : {total_rel_pool}')

    # 2) 랭크드: 순서가 필요 (rank 우선, 없으면 score로 정렬, 둘 다 없으면 현재 순서 사용)
    g = ranked_df.copy()
    if rank_col in g.columns:
        g = g.sort_values(rank_col, ascending=True)
    elif score_col in g.columns:
        g = g.sort_values(score_col, ascending=False)
        g[rank_col] = np.arange(1, len(g)+1)
    else:
        g[rank_col] = np.arange(1, len(g)+1)

    y_topk = pd.to_numeric(g["label"], errors="coerce").fillna(0).clip(0,1).astype(int).values[:k]
    print(f'y_topk : {y_topk}')
    return {
        f"Precision@{k}": precision_at_k(y_topk, k),
        f"Recall@{k}(pool)": recall_at_k(y_topk, total_rel_pool, k),
        f"MRR@{k}": mrr_at_k(y_topk, k),
        f"MAP@{k}": map_at_k(y_topk, total_rel_pool, k),
        f"nDCG@{k}": ndcg_at_k(y_topk, k),
        "PoolSize": int(len(pool_df)),
        "PoolRelevant": total_rel_pool,
        "TopK": int(min(len(g), k)),
        "TopKRelevant": int(y_topk.sum()),
    }

## Re-ranker 사용하기 전(openai)

1. 종목마다 측정

In [88]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i + 1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

In [89]:
before_lst = []

In [90]:
for ticker in target_lst[:10]:
    retriever = vectordb_openai.as_retriever(search_kwargs={"k": 30,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    before_lst.extend(raw_docs)
    print(list(map(lambda x: x.metadata['label'],raw_docs))[:5])
    print(list(map(lambda x: x.page_content,raw_docs))[:5])

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['(서울=연합뉴스) 강태우 기자 = 삼성전자가 미래로봇추진단의 잡포스팅(사내 채용공고)과 경력 채용을 동시에 실시한다. 최근 이노X 랩(InnoX Lab) 신설에 이은 내부 역량 강화 차원의 채용으로, 회사가 추진 중인 휴머노이드(인간형 로봇) 사업에도 탄력이 붙을 전망이다.삼성전자 서초사옥[연합뉴스 자료사진]5일 업계에 따르면 삼성전자 디바이스경험(DX) 부문은 이날부터 약 1주간 직원들을 대상으로 잡포스팅을 시행하는 것으로 알려졌다.모집 조직은 미래로봇추진단, 경영지원실, 경영진단팀, 생산기술연구소(생기연), 한국총괄, 디바이스 플랫폼 센터(DPC), 이사회 사무국 등이다.특히 미래로봇추진단의 잡포스팅은 전날 발표된 핵심 전략 과제 전담 조직인 이노X 랩 신설, 경력 채용과 맞물려 주목된다.미래로봇추진단은 지난해 말 삼성전자가 로봇 플랫폼 전문기업 레인보우로보틱스의 최대 주주 지위를 확보하면서 신설한 조직으로, 휴머노이드를 비롯한 삼성의 미래 로봇 기술 개발에 중추적인 역할을 수행한다.이번 잡포스팅에서는 휴머노이드향 미들웨어 개발, 인공지능(AI) 기반의 보행 및 전신 제어, 로봇 조작 기술 개발, 로봇 기구 설계 등의 인력을 미래로봇추진단에 충원하기로 했다.또 경력 채용에서는 로봇 파운데이션 모델(RFM) 개발, 로봇 조작 제어(Manipulation) 담당 인력을 뽑는 중이다.삼성전자는 올해 초에도 유관 부서 인력을 추진단에 투입하는 등 조직 역량을 내외부적으로 강화하고 있는 만큼, 휴머노이드 사업은 한층 속도가 날 전망이다.앞서 삼성전자는 자사 AI, 소프트웨어 기술에 레인보우로보틱스의 로봇 기술을 접목해 지능형 첨단 휴머노이드 개발을 가속하겠다는 계획을 밝힌 바 있다.전날부터 운영을 시작한 이노X 랩과의 유기적인 협업도 기대된다.이노X 랩은 피지컬 AI 기술을 제조 자동화 추진, 휴머노이드 로봇 핵심기술 개발 등의 과제를 수행할 계획이다.한편 삼성전자는 통상 각 사업부의 인력 수요 등에 따라 수시로 잡포스팅을 하고 있다. 이는 직원 커리어 개발은 물론 회사 경쟁력을 향상할 수 있다는 장점이 있다.burning@yna.co.kr', '하이디는 챗GPT처럼 AI 지식 검색, 영상회의 실시간 번역, 회의록 작성, 메일 요약과 초안 작성 등을 지원한다. 내부망에서 사용하기 때문에 외부로 정보가 유출되는 걸 원천적으로 차단할 수 있다. 하이디 도입으로 하루 평균 업무 생산성이 약 10% 향상됐는데, LG디스플레이는 이를 3년 내 30%까지 끌어올릴 방침이다. 외부 솔루션 대신 하이디를 자체 개발함으로써 연간 100억원에 이르는 비용 절감 효과도 거뒀다.다른 제조기업에도 AI 도입 바람이 불고 있다.조주완 LG전자 사장은 지난달 AX를 주제로 열린 임직원 소통 행사 \'AX 토크콘서트\'에 참석해 생성형 AI 데이터 시스템 \'찾다(CHATDA)\' 등을 소개했다.삼성전기는 AI를 기반으로 생산을 자동화하는 프로젝트를 진행 중이다. 이를 통해 중국 기업과 경쟁할 수 있는 생산성을 확보하겠다는 것이다.삼성전자 반도체 부문은 지난해 말 SAIT(옛 종합기술원) 산하에 있던 AI센터와 DS부문 내 혁신센터를 통합해 \'AI센터\'를 신설했다. AI를 활용해 반도체 연구개발(R&D) 역량을 높이려는 목적이다.한 국내 전자업체 CEO는 "한국보다 수십 배 많은 엔지니어를 배출하는 중국과의 경쟁에서 살아남기 위해 한국은 AI에서 답을 찾아야 한다"면서 "공장을 무인 자동화하고 AI를 활용해 R&D를 진행하는 것이 유일한 생존 방법"이라고 조언했다.[이덕주 기자]', '이 회사는 주식을 액면분할해 280만원대였던 주가를 5만원대로 낮췄다. 그 결과 주주가 24만명에서 500만명 이상으로 폭증했다. \'재벌 개혁\'의 단골 표적이던 삼성전자는 이제 국민이 지켜보고, 박수 치고, 걱정하는 \'국민 기업\'이 됐다. 이재용 삼성전자 회장은 웬만한 연예인보다 인기가 많다."기업이 잘돼야 나라가 잘되고, 삼성이 잘살아야 투자자도 잘산다." 지난 3월 당시 더불어민주당 대표였던 이 대통령이 이 회장에게 건넨 말이다. 이 말에 국민, 기업, 정부, 정치권이 한 방향을 바라보는 얼라인먼트의 요체가 담겨 있다.코스피가 5000선에 가까워질수록 이러한 얼라인먼트는 더 단단해질 수 있다. 선진국에선 이미 상식으로 자리 잡은 현상이다. 전 세계를 벌벌 떨게 하는 도널드 트럼프 미국 대통령도 주가가 흔들리면 움찔한다. 성인 62%가 주식을 갖고 있는 미국에선 대통령 지지율과 주가가 사실상 연동돼 있기 때문이다.아직은 상상의 영역일지 모른다. 그러나 머지않아 한국에서도 \'노란봉투법\' 같은 반기업 규제에 대해 기업이 아닌 수많은 투자자가 목소리를 높이는 날이 올 수 있다. 그쯤 되면 일부 시민단체나 귀족 노조의 반시장적 요구도 더 이상 힘을 얻기 어려워질 것이다.시장이 정치에 휘둘리던 시대는 저물고 있다. 시장이 정치를 견제하는 시대가 어서 왔으면 좋겠다. 이미 시장은 정치에 말 걸기 시작했다.[이진우 논설실장]', "대표이사 직속 미래로봇추진단, AI 기반 보행·조작 기술 등 핵심 분야 인력 충원이노X 랩과 유기적 연계…사내 잡포스팅·외부 경력 채용 병행레인보우로보틱스 기술 접목해 지능형 로봇 개발 속도 낼 전망서울 서초구 삼성전자 서초사옥에 설치된 삼성전자 깃발이 바람에 펄럭이고 있다. ⓒ뉴시스[데일리안 = 정진주 기자] 삼성전자가 휴머노이드 개발을 본격화하면서 관련 인재 확보에 나섰다. 대표이사 직속 조직인 미래로봇추진단을 중심으로 전사 차원의 사내 인력 재배치와 외부 채용이 동시에 진행된다.5일 업계에 따르면 삼성전자 디바이스경험(DX) 부문은 이날부터 약 1주일간 미래로봇추진단 등 일부 조직을 대상으로 잡포스팅(사내 채용)을 진행한다.모집 부서는 미래로봇추진단 외에도 경영지원실, 경영진단팀, 생산기술연구소, 한국총괄, 디바이스 플랫폼 센터(DPC), 이사회 사무국 등이다.이 중 미래로봇추진단은 지난해 말 삼성전자가 레인보우로보틱스를 자회사로 편입하며 설립한 대표이사 직속 조직으로, 현재 휴머노이드 개발의 중심 역할을 맡고 있다. 이번 잡포스팅을 통해 추진단은 AI 기반 보행 및 전신 제어, 휴머노이드용 미들웨어, 로봇 기구 설계, 조작 기술 등 분야에서 인력을 충원할 계획이다.사내 채용과 함께 외부 경력직 채용도 진행 중이다. 주요 포지션은 로봇 파운데이션 모델(RFM) 개발, 로봇 조작 제어(Manipulation) 등으로, 고난도 기술 개발이 필요한 핵심 분야다.이번 인재 확보는 전날 본격 가동에 들어간 '이노X 랩'과도 연계된다. 이노X 랩은 피지컬 AI 기술을 기반으로 제조 자동화와 휴머노이드 핵심 기술을 개발하는 전략 조직으로, 미래로봇추진단과 유기적으로 협력할 것으로 보인다.삼성전자는 올해 초부터도 유관 부서 인력을 미래로봇추진단에 배치하는 등 로봇 조직 역량을 내외부적으로 강화해왔으며, 자체 AI·SW 기술과 레인보우로보틱스의 플랫폼 기술을 접목해 차세대 지능형 휴머노이드를 개발하겠다는 계획을 밝힌 바 있다.", '있다. 삼성전자는 최근 스마트폰·가전 사업 등을 담당하는 디바이스 경험(DX) 부문에 인공지능 기술을 활용한 제조 자동화 등 미래 전략 과제를 전담하는 조직인 ‘이노X랩’(혁신과 전환을 합친 말)을 신설했다. 회사 관계자는 “모든 업무에 인공지능을 적용하겠다는 노태문 디바이스경험부문장 직무대행(사장)의 의지에 따라 특별 태스크포스(TF)를 만들어 지원하겠다는 취지”라고 했다.에스케이(SK)그룹도 지난해 말 그룹 최고 의사협의체인 수펙스추구협의회 내에 인공지능 추진단을 확대 신설하며 계열사들의 인공지능 전환을 이끌고 있다. 에스케이는 그룹 총수인 최태원 회장이 직접 제조업 인공지능을 경제계의 최대 현안으로 띄우고 있다.권보경 포스코경영연구원 수석연구원은 “한국 제조 기업들은 중국보다 인공지능 기술 도입이 뒤처진 상태로, 자체 클라우드(인터넷 기반의 정보 저장 공간)와 보안 시스템 등 국내에 인공지능 활용 인프라를 구축할 필요가 있다”고 말했다.']
이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방 요인으로 작용할 것"이라고 전망했다．', '실적 컨퍼런스콜에서 "파트너사와 함께 시스템 내 성능 최적화를 위한 협업을 진행 중이며, HBM 부문을 지난해보다 약 2배 성장시킬 계획"이라고 전했다. SK하이닉스는 HBM4에 10나노급 5세대(1b) 공정을 적용해 이미 수율 안정화를 마치고, 빠르게 생산량 확대(램프업)에 돌입한 것으로 파악된다. 이르면 이번 분기부터 HBM4 매출 반영도 시작될 것으로 기대를 모은다.■공급과잉론 돌파양사의 움직임은 일각에서 제기된 HBM 공급 과잉론을 정면으로 반박하는 행보다. 앞서 글로벌 투자은행 골드만삭스는 보고서를 통해 기존 SK하이닉스가 주도하던 HBM 시장에 삼성전자, 마이크론의 진입으로 경쟁이 심화하면서 HBM 가격이 하락할 수 있다고 경고했다. 그러나 주요 빅테크 기업들이 지속적으로 AI 인프라 투자를 확대하고 있고, HBM4나 커스텀(맞춤형) HBM 같은 차세대 HBM에 대한 수요는 끊이지 않을 것이란 분석이 지배적이다. 반도체 업계 관계자는 "HBM은 현재 물량이 없어서 못 팔고 있는 수준"이라며 "특히 HBM4의 경우 어디가 엔비디아에 먼저 들어가는지 양산 경쟁을 하고 있는 상황이라 시장은 더 활기를 띨 것"이라고 전했다.업계에서는 향후 차세대 HBM 시장을 잡는 기업이 메모리 시장에서 승자가 될 것으로 보고 있다. HBM 시장 1위인 SK하이닉스는 올 2·4분기 영업이익 9조2129억원, 영업이익률 41%를 기록, 사상 최대 실적을 달성했다. HBM 주도권을 잡은 것이 핵심 역할을 했다. SK하이닉스는 2·4분기 글로벌 메모리반도체 시장에서 삼성전자를 제치고 사상 처음으로 매출 1위를 차지하기도 했다.시장조사업체 카운터포인트리서치에 따르면 SK하이닉스는 2·4분기 D램과 낸드를 포함한 전체 메모리 시장에서 21조8000억원의 매출을 기록했다. 같은 기간 삼성전자의 메모리반도체 매출은 21조2000억원에 그쳤다.soup@fnnews.com 임수빈 조은효 기자', '엔비디아, 사상 최고치 경신SK하이닉스 2%대 상승 마감증권가, 목표가 4% 상향…8만6000원[서울=뉴시스] 최진석 기자 = 삼성전자가 올해 2분기 실적을 발표한 31일 서울 삼성전자 서초사옥에 삼성 로고가 보이고 있다. 이날 발표된 삼성전자 올해 2분기 연결 기준 매출은 74조5663억원, 영업이익 4조6761억원의 실적을 기록했다. 전년 같은 분기 대비 매출은 0.67%, 영업이익은 55.23% 하락했다. 2025.07.31. myjs@newsis.com[서울=뉴시스]이지영 기자 = 삼성전자가 7만전자 턱밑에서 상승 마감했다.5일 한국거래소에 따르면 삼성전자는 이날 전 거래일 대비 0.29%(200원) 오른 6만9900원에 장을 마쳤다.삼성전자는 이날 2%대 상승 출발하며 장중 한때 7만원대 거래됐다. 하지만 장 후반 세제 개편안 재검토가 어렵다는 보도가 나오면서 7만전자를 반납했다.시장은 세제 개편안을 국내 증시 악재로 해석하고 있다.삼성전자가 장 초반 강세를 띤 배경은 엔비디아가 급등하는 등 반도체주가 랠리를 펼친 영향이다.엔비디아는 4일(현지시간) 3.62% 급등한 180달러를 기록하며 사상 최고치를 경신했다. 장중 180달러를 돌파한 적은 있지만 마감가 기준으로 180달러를 찍은 것은 이번이 처음이다. 이날 반도체지수도 1.75% 상승 마감했다.반도체 대장주로 함께 묶이는 SK하이닉스도 이날 전 거래일 대비 2.13%(5500원) 오른 26만3500원에 마감했다.증권가는 삼성전자 목표주가를 상향했다.차용호 LS증권 연구원은 이날 보고서를 통해 삼성전자 목표주가를 기존 대비 4% 올린 8만6000원으로 제시했다.차 연구원은 "삼성전자 HBM 사업부에 대한 평가 절하가 있었던 가장 큰 이유가 엔비디아 밸류체인에 포함되지 않았단 점을 감안하면 AMD와 함께 가장 재평가돼야 한다"며 "실적 개선을 위한 걸림돌 중 하나였던 삼성 파운드리 사업부도 테슬라향 신규 수주를 통해 전환을 위한 초석을 마련했다"고 평가했다.이어 "삼성전자 대비 SK하이닉스의 주가순자산비율(PBR) 프리미엄은 37%로 올해 최대치인 80%에서 크게 줄었다"며 "이 과정에서 삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '이차전지, 바이오주 등 성장주가 상대적 강세를 보였다”고 설명했다.엔비디아 강세에 SK하이닉스(2.13%)가 3거래일 만에 종가 기준 26만원을 웃돌았다. 삼성전자(0.29%)는 장중 ‘7만전자’를 터치했으나 오름폭을 줄여 종가 기준 7만원선 회복에는 실패했다.금리 인하 기대가 커지면서 LG에너지솔루션(2.93%), POSCO홀딩스(2.76%) 등 이차전지주와 삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다.지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다.반면 현대차(-0.24%), 기아(-1.36%) 등 자동차주는 내렸다.아울러 카카오(-1.26%)는 정부가 추진하는 ‘독자 AI 파운데이션 모델’ 구축 사업의 지원 대상으로 선정되지 못했다는 보도에 하락했고 자회사가 지원 대상으로 선정된 NAVER(-0.22%)도 내렸다.업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다.코스닥시장에서 외국인과 기관이 각각 467억원, 256억원 순매수했으며, 개인은 631억원 매도 우위를 보였다.에코프로비엠이 2분기 호실적을 공개하면서 15.28% 급등했으며, 모회사 에코프로(8.54%)도 뛰었다.아울러 알테오젠(2.78%), 펩트론(0.34%), 파마리서치(1.62%), 레인보우로보틱스(3.82%) 등도 상승했다.반면 HLB(-0.63%), 에스엠(-0.07%), 펄어비스(-0.51%), 네이처셀(-0.84%) 등은 하락했다.이날 유가증권시장과 코스닥시장의 거래대금은 각각 10조9470억원, 4조7850억원으로 집계됐다.대체거래소 넥스트레이드의 프리마켓과 정규마켓의 거래대금은 총 7조630억원이다.']
이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['사진=게티이미지뱅크미국 내 전기차 보조금 폐지를 앞둔 가운데 기관 투자사들은 오히려 2차전지 종목을 적극 사들인 것으로 나타났다. 증권가에선 순환매 장세에 따라 저평가된 2차전지 업종에 투자금이 몰렸다고 분석한다.5일 한국거래소에 따르면 지난달 이후 이날까지 국내 증시에서 기관 투자사들이 가장 많이 사들인 종목은 LG에너지솔루션(5927억원)으로 집계됐다. 삼성SDI(1377억원)와 엘앤에프(530억원) 등도 순매수 상위권에 이름을 올렸다.기관의 매수세에 힘입어 2차전지 업종도 모처럼 반등에 성공했다. 주요 2차전지 종목을 모은 \'KRX 2차전지 TOP10 지수\'와 \'KRX 전기차 TOP15 지수\'는 각각 13.85%, 12.72% 급등했다. 전체 34개 KRX 테마지수 중 수익률 상위 1, 2위를 기록했다.증권가에선 2차전지 섹터를 단기 투자처로 보고 있다. 국내 2차전지 기업들의 에너지저장장치(ESS) 수주 기대와 리튬 가격 상승을 호재로 꼽으면서다. 주민우 NH투자증권 연구원은 "오는 9월까지는 2차전지 관련주의 주가가 오를 것"이라면서 LG에너지솔루션은 최우선주로 제시했다. 향후 미국에서 ESS 수주가 늘어남에 따라 LG에너지솔루션이 수혜를 입을 것이란 분석에서다.지난해부터 2차전지주 주가가 크게 떨어진 만큼 추가 하락 폭이 크지 않을 것이란 관측도 고개를 들고 있다. 자산운용업계 관계자는 "반도체 섹터에서 차익 실현하는 대신 그간 주가가 많이 내린 2차전지 종목으로 투자금을 옮기는 추세"라고 설명했다.일각에선 올해도 2차전지 업황이 개선되긴 쉽지 않을 것으로 전망한다. 미국 정부가 지급하는 전기차 구입 보조금이 오는 9월 30일 종료되면 판매가 더 줄어들 수 있다는 분석 때문이다. 유럽 전기차 시장은 성장이 기대되지만 최근 중국 기업이 물량 공세를 펼치고 있기 때문에 국내 2차전지업체들이 시장에 침투하기 쉽지 않을 것이란 분석도 나온다.조현렬 삼성증권 연구원은 "미국 내 보조금이 사라지면 전기차 수요 관련 불확실성이 커질 것"이라며 "전기차 배터리 생산 비중이 높은 업체들의 수익 감소는 불가피하다"고 말했다.', "줄여 종가 기준 7만원선 회복에는 실패했다.금리 인하 기대가 커지면서 LG에너지솔루션(2.93%), POSCO홀딩스(2.76%) 등 이차전지주와 삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다.지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다.반면 현대차(-0.24%), 기아(-1.36%) 등 자동차주가 내렸다.아울러 카카오(-1.26%)는 정부가 추진하는 '독자 AI 파운데이션 모델' 구축 사업의 지원 대상으로 선정되지 못했다는 보도에 하락했고 자회사가 지원 대상으로 선정된 NAVER(-0.22%)도 내렸다.업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다.코스닥시장에서 외국인과 기관이 각각 467억원, 256억원 순매수했으며, 개인은 631억원 매도 우위를 보였다.에코프로비엠이 2분기 호실적을 공개하면서 15.28% 급등했으며, 모회사 에코프로(8.54%)도 뛰었다.아울러 알테오젠(2.78%), 펩트론(0.34%), 파마리서치(1.62%), 레인보우로보틱스(3.82%) 등도 상승했다.반면 HLB(-0.63%), 에스엠(-0.07%), 펄어비스(-0.51%), 네이처셀(-0.84%) 등은 하락했다.이날 유가증권시장과 코스닥시장의 거래대금은 각각 10조9천470억원, 4조7천850억원으로 집계됐다.대체거래소 넥스트레이드의 프리마켓과 정규마켓의 거래대금은 총 7조630억원이다.mylux@yna.co.kr", '북미 현지화 수혜주 부각…전기차 침체 속 사업 재편 속도[파이낸셜뉴스] 이차전지 업종이 일제히 급등세를 보였다. 미국 에너지저장장치(ESS) 시장 성장에 따른 기대와 더불어, 최근 침체를 겪던 전기차 배터리 사업의 전환 기대가 모멘텀으로 작용했다는 분석이다.5일 한국거래소에 따르면 삼성SDI는 이날 유가증권시장에서 전일 대비 10.22% 오른 21만3500원에 거래를 마쳤다. 장중 한 때 주가는 전날보다 13.88% 급등한 22만1500원까지 거래됐다. 이 외에도 에코프로머티(11.91%), 엘앤에프(8.35%) 등이 동반 강세를 보였다. 코스닥시장에서도 피노(11.38%), 에코프로(8.54%), 엔켐(4.85%), 대진첨단소재(4.43%), 엠플러스(3.74%), 하이드로리튬(2.07%) 등 관련주가 일제히 오름세를 보였다. 상장지수펀드(ETF)에서는 \'KODEX 2차전지산업 레버리지 ETF\'가 전일 대비 10% 넘게 오르는 등 이차전지주에 대한 투자심리 회복이 뚜렷했다.증시 전문가들은 최근 상승세의 배경으로 리튬 등 원자재 가격 반등과 미국의 고율 관세 정책에 주목했다. 유안타증권 이안나 연구원은 “미국과 중국 간 상호 관세 휴전이 오는 12일 만료되는데, 재연장시 국내 기업들의 북미 공장 비중에 따른 구조적 우위가 더욱 부각될 수 있다”며 “특히 국내 업체들의 북미 내 전지 현지화 비중이 높은 만큼, 하반기부터 다시 비중확대 전략이 유효하다”고 분석했다.여기에 ESS 시장의 성장성도 주가 반등에 긍정적 영향을 미쳤다. 삼성증권 장정훈 연구원은 “전기차 수요 둔화에도 불구하고 미국의 ESS 시장은 고율 관세로 인해 중국 제품의 진입이 어려운 반면, 한국 업체들이 리튬·인산·철(LFP) 배터리를 중심으로 전환하며 점유율 확대 기회를 갖고 있다”고 설명했다.반등의 중심에는 삼성SDI가 있다. 삼성SDI는 최근 2·4분기 실적 발표에서 3978억원의 영업손실을 기록하며 시장 기대치를 밑돌았으나, 북미 ESS 라인 전환과 소형전지 회복을 기반으로 4·4분기 흑자전환 전망이 제시됐다.흥국증권 정진수 연구원은 "스텔란티스 공장에서 일부 전기차 라인을 ESS 생산용으로 전환 중이고 10월 가동이 목표다”라며 “중장기적으로 북미 내 15GWh 이상 규모의 생산능력 확보가 예상되고 이는 연간 2조5000억원 매출로 이어질 것”이라고 분석했다.이차전지 업종에 대한 투자전력 측면에서 이안나 연구원은 “오는 12일 전후 북미', '거래되고 있고, 같은 기간 SK하이닉스(000660)는 4000원(1.55%) 오른 26만 2000원을 가리키고 있다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.66%, 2.13% 오르고 있다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.17% 하락세다.한편 코스닥 지수는 전 거래일 대비 13.36포인트(1.70%) 오른 797.42에 거래되고 있다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 464억원 순매도하고 있으며 외국인과 기관 투자자가 각각 388억원, 176억원치를 순매수하며 매수 우위를 이어나가고 있다. 프로그램별로는 차익과 비차익을 합쳐 187억원 매수 우위를 나타내고 있다.', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]']
이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', "주목을 받았다.이 외에도 △알테오젠(2.78%) △펩트론(0.34%) △파마리서치(1.62%) △레인보우로보틱스(3.82%) △리가켐바이오(2.14%) 등이 상승했고, △HLB(-0.63%) △삼천당제약(-1.13%) 등은 하락했다.환율은 소폭 상승했다. 이날 서울 외환시장에서 원·달러 환율은 전날보다 3.1원 오른 1388.3원에 주간 거래를 마감했다.발로 뛰는 더팩트는 24시간 여러분의 제보를 기다립니다.▶카카오톡: '더팩트제보' 검색▶이메일: jebo@tf.co.kr▶뉴스 홈페이지: http://talk.tf.co.kr/bbs/report/write", "외인·기관 '사자'…삼성전자 상승 폭 축소, 금융·조선주는 강세자동차주 오름폭 축소…'에코프로 형제' 급등국내 주식 시황 (PG)[김토일 제작] 일러스트(서울=연합뉴스) 이민영 기자 = 코스피가 5일 장중 상승 폭을 줄이며 3,200선을 내줬다. 코스닥지수는 800대에서 2% 넘게 오르고 있다.이날 오전 11시 6분 현재 코스피는 전장보다 49.76포인트(1.58%) 오른 3,197.51다.지수는 전장보다 39.40포인트(1.25%) 오른 3,187.15로 출발해 상승 폭을 키워 3,212.31까지 올랐으나 다시 오름폭을 줄이고 있다.유가증권시장에서 외국인과 기관이 각각 1천23억원, 1천112억원 순매수하고 있으며, 개인은 2천426억원 매도 우위를 보이고 있다.외국인은 코스피200선물 시장에서도 3천267억원 '사자'를 나타내고 있다.삼성전자(0.65%)가 장 초반 대비 상승 폭은 줄었지만 전일 대비 상승했고, SK하이닉스(1.84%), LG에너지솔루션(2.93%), 삼성바이오로직스(1.05%), 한화에어로스페이스(1.71%) 등이 오르고 있다.KB금융(3.41%), 신한지주(2.88%) 등 금융주와 HD현대중공업(1.62%) 등 조선주도 강세다.반면 장 초반 상승하던 현대차는 상승 폭을 줄여 전장과 동일한 가격에 거래되고 있으며, 기아(-0.68%)도 오름폭을 줄이다 장중 하락 전환했다. NAVER(-0.22%), 카카오(-2.71%) 등 인터넷 업종도 약세다.업종별로 보면 보험(2.76%), 제약1.43%), 전기전자(1.59%) 등이 오르고 있으며 섬유의류(-0.31%), IT서비스(-0.40%) 등은 하락 중이다.같은 시각 코스닥지수는 전장보다 16.66포인트(2.12%) 오른 800.72다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승 폭을 늘리며 800선을 회복한 뒤 상승 폭을 유지 중이다.에코프로비엠이 장중 2분기 호실적을 공개하면서 12.78% 급등 중이며 에코프로(8.13%)도 오르고 있다.아울러 알테오젠(3.47%), 펩트론(1.53%), 레인보우로보틱스(4.59%), 에이비엘바이오(6.14%), 파마리서치(2.70%) 등도 상승 중이다.HLB(-0.10%), 휴젤(-0.46%), 펄어비스(-0.38%) 등은 하락하고 있다.mylux@yna.co.kr", 'SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.']
이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']

In [91]:
rerank_df_before = pd.DataFrame(list(map(lambda x: x.metadata,before_lst)))

In [92]:
rerank_df_before

     chunk_idx ticker  original_idx label
0            0   삼성전자            21     1
1            1   삼성전자            22     1
2            1   삼성전자            28     1
3            0   삼성전자             4     1
4            1   삼성전자             5     1
..         ...    ...           ...   ...
295          0   셀트리온           268     1
296          0   셀트리온           281     1
297          1   셀트리온           283     1
298          1   셀트리온           285     1
299          0   셀트리온           266     1

[300 rows x 4 columns]

In [ ]:
rerank_df_before[rerank_df_before.ticker=='삼성전자'].original_idx.value_counts() # 60%..

original_idx
36    2
11    2
28    2
10    2
5     2
2     2
14    2
30    2
22    2
34    2
15    1
20    1
7     1
21    1
25    1
13    1
24    1
9     1
4     1
18    1
Name: count, dtype: int64

In [98]:
rerank_df_before[rerank_df_before.ticker=='삼성전자'].label.astype('int').sum()

np.int64(25)

In [31]:
VecDB = vectordb_openai._collection
total_results = VecDB.get(
         include = ['documents','metadatas']   
        )

In [32]:
total_df = pd.DataFrame(total_results['metadatas'])

In [33]:
total_df

    label ticker  chunk_idx  original_idx
0       1   삼성전자          0             0
1       1   삼성전자          0             1
2       0   삼성전자          0             2
3       0   삼성전자          1             2
4       0   삼성전자          2             2
..    ...    ...        ...           ...
418     1   셀트리온          1           285
419     1   셀트리온          0           286
420     1   셀트리온          1           286
421     1   셀트리온          0           288
422     1   셀트리온          0           289

[423 rows x 4 columns]

In [193]:
rerank_eval = []

In [194]:
for kind in target_lst[:10]:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target = rerank_df_before[rerank_df_before.ticker==kind]
    rerank_eval.append(eval_reranker_chunk(total_df_target,rerank_df_target))

total_rel_pool : 34
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 1]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [208]:
rerank_eval_con_before = dict(zip(target_lst[:10],rerank_eval))

In [209]:
pd.DataFrame(rerank_eval_con_before)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.833333,1.000000,1.000000,1.00,1.000000,0.933333,1.000000,1.000000,1.00,0.933333
Recall@30(pool),0.735294,0.714286,0.638298,0.75,0.909091,1.000000,0.638298,0.681818,0.75,0.777778
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,1.000000
MAP@30,0.800881,1.000000,1.000000,1.00,1.000000,0.996170,1.000000,1.000000,1.00,0.827636
nDCG@30,0.991573,1.000000,1.000000,1.00,1.000000,0.999256,1.000000,1.000000,1.00,0.959072
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,30.000000,30.000000,30.000000,30.00,30.000000,30.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,25.000000,30.000000,30.000000,30.00,30.000000,28.000000,30.000000,30.000000,30.00,28.000000

2. 전체 문서에서 특정 ticker 검색

In [99]:
before_lst_total = []

In [100]:
for ticker in target_lst[:10]:
    retriever = vectordb_openai.as_retriever(search_kwargs={"k": 30})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    before_lst_total.extend(raw_docs)
    print(list(map(lambda x: x.metadata['label'],raw_docs))[:5])
    print(list(map(lambda x: x.page_content,raw_docs))[:5])

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.
['0', '1', '1', '1', '1']
['[이데일리 정두리 기자] 다음은 8월 5일자 이데일리 신문 주요 기사다.△1면-관세 못 내면 4중 처벌, 최저임금 어기면 징역 3년-LG·네이버 등 5곳 국가대표AI 만든다-신한銀, 1주택자 전세대출도 빗장-정밀·소형화 통했다 해외뻗는 K의료기기-[사설]교육세제 문제엔 눈감고 금융사 세율만 올리는 정부-[사설]조선업계 마스가 TF 가동, 민관협력 효과 극대화해야△국가대표 AI 톱5 선정-LG “프런티어 AI 활용한 생태계 구축”…네이버 “국민체험형 서비스 개발”-SKT·KT 출신 손잡은 업스테이지…스타트업 유일 골든티켓△기업 경제형벌 합리화 목소리-회계 허위 기재하면 살인죄와 같은 형량…“모기 잡는데 폭탄 쓰는 꼴”-AI교과서 교육자료로 격하…업계 “소송전 불사”-쌀 공급과잉 미리 막는다…여야 농업 4법 합의 입법△종합-소비쿠폰 노린 대형 식자재마트, 단말기 바꿔 결제…“꼼수 영업 막아야”-韓 제조업체 10곳 중 8곳 “주력제품, 이미 레드오션”-미혼남녀 60% 결혼하고 싶어도…현실 장벽은 돈-공급 늘리는 주요 산유국들 국제유가 60달러선 깨질까△의료기기 수출 특수-구부려 찍는 엑스레이, 바늘 없는 채혈기 틈새 찌르니 수출이 터졌다-“글로벌 판매량 1위 비결은 공격적 R&D”-막대한 자본 필요한 중대형 기기는 다국적기업 몫△정치-정당해산 위협에도…여론전 외엔 마땅한 대응 카드없는 국민의힘-휴가 떠난 李대통령, 韓美 정상회담·광복절 메시지 등 고심-美, 中 겨냥한 동맹 현대화 압박 가능성 커…실용외교 시험대-자본시장 신뢰 스스로 걷어찬 與△경제-“4000억이나 세수 줄어든다” 쏙 들어간 통신비 세액공제-탈세 규모 상관없이…주가 조작하면 대기업도 공시-공정위, 정책 발굴 시동…해외 경쟁당국 최신 제도 살핀다△금융-은행권, 전세·신용대출 줄줄이 중단 초강수-삼성화재, ‘5호선 방화’ 피해 미리 보상한다-車보험 구조적 적자…4대 손보사 2분기 순익 감소△글로벌-美, 깎아줄 기미없자…손 내민 스위스·캐나다-보잉 방산부문 노조 30여 년 만에 파업-애플 보란듯…저커버그 “아이폰 다음은 메타글라스”-잘 나가는 한국쌀 日수출 역대 최대△산업-완성차업계 美관세 쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직', '오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '엔비디아, 사상 최고치 경신SK하이닉스 2%대 상승 마감증권가, 목표가 4% 상향…8만6000원[서울=뉴시스] 최진석 기자 = 삼성전자가 올해 2분기 실적을 발표한 31일 서울 삼성전자 서초사옥에 삼성 로고가 보이고 있다. 이날 발표된 삼성전자 올해 2분기 연결 기준 매출은 74조5663억원, 영업이익 4조6761억원의 실적을 기록했다. 전년 같은 분기 대비 매출은 0.67%, 영업이익은 55.23% 하락했다. 2025.07.31. myjs@newsis.com[서울=뉴시스]이지영 기자 = 삼성전자가 7만전자 턱밑에서 상승 마감했다.5일 한국거래소에 따르면 삼성전자는 이날 전 거래일 대비 0.29%(200원) 오른 6만9900원에 장을 마쳤다.삼성전자는 이날 2%대 상승 출발하며 장중 한때 7만원대 거래됐다. 하지만 장 후반 세제 개편안 재검토가 어렵다는 보도가 나오면서 7만전자를 반납했다.시장은 세제 개편안을 국내 증시 악재로 해석하고 있다.삼성전자가 장 초반 강세를 띤 배경은 엔비디아가 급등하는 등 반도체주가 랠리를 펼친 영향이다.엔비디아는 4일(현지시간) 3.62% 급등한 180달러를 기록하며 사상 최고치를 경신했다. 장중 180달러를 돌파한 적은 있지만 마감가 기준으로 180달러를 찍은 것은 이번이 처음이다. 이날 반도체지수도 1.75% 상승 마감했다.반도체 대장주로 함께 묶이는 SK하이닉스도 이날 전 거래일 대비 2.13%(5500원) 오른 26만3500원에 마감했다.증권가는 삼성전자 목표주가를 상향했다.차용호 LS증권 연구원은 이날 보고서를 통해 삼성전자 목표주가를 기존 대비 4% 올린 8만6000원으로 제시했다.차 연구원은 "삼성전자 HBM 사업부에 대한 평가 절하가 있었던 가장 큰 이유가 엔비디아 밸류체인에 포함되지 않았단 점을 감안하면 AMD와 함께 가장 재평가돼야 한다"며 "실적 개선을 위한 걸림돌 중 하나였던 삼성 파운드리 사업부도 테슬라향 신규 수주를 통해 전환을 위한 초석을 마련했다"고 평가했다.이어 "삼성전자 대비 SK하이닉스의 주가순자산비율(PBR) 프리미엄은 37%로 올해 최대치인 80%에서 크게 줄었다"며 "이 과정에서 삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]']
이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.
['0', '1', '1', '1', '1']
['[이데일리 정두리 기자] 다음은 8월 5일자 이데일리 신문 주요 기사다.△1면-관세 못 내면 4중 처벌, 최저임금 어기면 징역 3년-LG·네이버 등 5곳 국가대표AI 만든다-신한銀, 1주택자 전세대출도 빗장-정밀·소형화 통했다 해외뻗는 K의료기기-[사설]교육세제 문제엔 눈감고 금융사 세율만 올리는 정부-[사설]조선업계 마스가 TF 가동, 민관협력 효과 극대화해야△국가대표 AI 톱5 선정-LG “프런티어 AI 활용한 생태계 구축”…네이버 “국민체험형 서비스 개발”-SKT·KT 출신 손잡은 업스테이지…스타트업 유일 골든티켓△기업 경제형벌 합리화 목소리-회계 허위 기재하면 살인죄와 같은 형량…“모기 잡는데 폭탄 쓰는 꼴”-AI교과서 교육자료로 격하…업계 “소송전 불사”-쌀 공급과잉 미리 막는다…여야 농업 4법 합의 입법△종합-소비쿠폰 노린 대형 식자재마트, 단말기 바꿔 결제…“꼼수 영업 막아야”-韓 제조업체 10곳 중 8곳 “주력제품, 이미 레드오션”-미혼남녀 60% 결혼하고 싶어도…현실 장벽은 돈-공급 늘리는 주요 산유국들 국제유가 60달러선 깨질까△의료기기 수출 특수-구부려 찍는 엑스레이, 바늘 없는 채혈기 틈새 찌르니 수출이 터졌다-“글로벌 판매량 1위 비결은 공격적 R&D”-막대한 자본 필요한 중대형 기기는 다국적기업 몫△정치-정당해산 위협에도…여론전 외엔 마땅한 대응 카드없는 국민의힘-휴가 떠난 李대통령, 韓美 정상회담·광복절 메시지 등 고심-美, 中 겨냥한 동맹 현대화 압박 가능성 커…실용외교 시험대-자본시장 신뢰 스스로 걷어찬 與△경제-“4000억이나 세수 줄어든다” 쏙 들어간 통신비 세액공제-탈세 규모 상관없이…주가 조작하면 대기업도 공시-공정위, 정책 발굴 시동…해외 경쟁당국 최신 제도 살핀다△금융-은행권, 전세·신용대출 줄줄이 중단 초강수-삼성화재, ‘5호선 방화’ 피해 미리 보상한다-車보험 구조적 적자…4대 손보사 2분기 순익 감소△글로벌-美, 깎아줄 기미없자…손 내민 스위스·캐나다-보잉 방산부문 노조 30여 년 만에 파업-애플 보란듯…저커버그 “아이폰 다음은 메타글라스”-잘 나가는 한국쌀 日수출 역대 최대△산업-완성차업계 美관세 쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직', '대한조선(439260)가 8월 5일 장 마감 5분 만에 10.19%의 검색비율을 기록해 많은 투자자들의 관심을 받고 있다. 대한조선의 현재가는 103,800원으로 전 거래일 대비 29.91% 상승하며 상한가로 마감했다. 거래량은 5,095,588주를 기록했다.이어 검색비율 2위의 삼성전자(005930)는 0.29% 상승 마감했다. 검색비율 3위의 에코프로비엠(247540)은 15.28% 급등세로 거래를 마쳤다. 검색비율 4위 현대로템(064350)은 0.50% 상승 마감했다. 검색비율 5위 삼성SDI(006400)는 10.22% 상승 마감했다.6위 한화오션(042660)은 등락률 1.57%로 소폭 상승했다. 7위 두산에너빌리티(034020)는 0.78%의 등락률로 주가가 강보합세를 보였다. 8위 카카오(035720)는 -1.26%의 하락세를 보였다. 9위 NAVER(035420)는 -0.22% 하락 마감했다. 10위 카카오페이(377300)는 등락률 0.00%로 보합세를 유지했다.이 밖에도 SK하이닉스(000660) ▲2.13%, 삼성중공업(010140) ▲5.11%, LS ELECTRIC(010120) ▲8.40%, 다날(064260) ▲3.04%, 셀트리온(068270) ▲2.24%, 에코프로(086520) ▲8.54%, SK바이오팜(326030) ▲15.92%, 포스코퓨처엠(003670) ▲8.56%, 올릭스(226950) ▲7.94%, 현대차(005380) ▼0.24% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '대한조선(439260)가 8월 5일 장 마감 5분 만에 10.19%의 검색비율을 기록해 많은 투자자들의 관심을 받고 있다. 대한조선의 현재가는 103,800원으로 전 거래일 대비 29.91% 상승하며 상한가로 마감했다. 거래량은 5,095,588주를 기록했다.이어 검색비율 2위의 삼성전자(005930)는 0.29% 상승 마감했다. 검색비율 3위의 에코프로비엠(247540)은 15.28% 급등세로 거래를 마쳤다. 검색비율 4위 현대로템(064350)은 0.50% 상승 마감했다. 검색비율 5위 삼성SDI(006400)는 10.22% 상승 마감했다.6위 한화오션(042660)은 등락률 1.57%로 소폭 상승했다. 7위 두산에너빌리티(034020)는 0.78%의 등락률로 주가가 강보합세를 보였다. 8위 카카오(035720)는 -1.26%의 하락세를 보였다. 9위 NAVER(035420)는 -0.22% 하락 마감했다. 10위 카카오페이(377300)는 등락률 0.00%로 보합세를 유지했다.이 밖에도 SK하이닉스(000660) ▲2.13%, 삼성중공업(010140) ▲5.11%, LS ELECTRIC(010120) ▲8.40%, 다날(064260) ▲3.04%, 셀트리온(068270) ▲2.24%, 에코프로(086520) ▲8.54%, SK바이오팜(326030) ▲15.92%, 포스코퓨처엠(003670) ▲8.56%, 올릭스(226950) ▲7.94%, 현대차(005380) ▼0.24% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방 요인으로 작용할 것"이라고 전망했다．', 'SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.']
이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.
['0', '1', '1', '1', '1']
['[이데일리 정두리 기자] 다음은 8월 5일자 이데일리 신문 주요 기사다.△1면-관세 못 내면 4중 처벌, 최저임금 어기면 징역 3년-LG·네이버 등 5곳 국가대표AI 만든다-신한銀, 1주택자 전세대출도 빗장-정밀·소형화 통했다 해외뻗는 K의료기기-[사설]교육세제 문제엔 눈감고 금융사 세율만 올리는 정부-[사설]조선업계 마스가 TF 가동, 민관협력 효과 극대화해야△국가대표 AI 톱5 선정-LG “프런티어 AI 활용한 생태계 구축”…네이버 “국민체험형 서비스 개발”-SKT·KT 출신 손잡은 업스테이지…스타트업 유일 골든티켓△기업 경제형벌 합리화 목소리-회계 허위 기재하면 살인죄와 같은 형량…“모기 잡는데 폭탄 쓰는 꼴”-AI교과서 교육자료로 격하…업계 “소송전 불사”-쌀 공급과잉 미리 막는다…여야 농업 4법 합의 입법△종합-소비쿠폰 노린 대형 식자재마트, 단말기 바꿔 결제…“꼼수 영업 막아야”-韓 제조업체 10곳 중 8곳 “주력제품, 이미 레드오션”-미혼남녀 60% 결혼하고 싶어도…현실 장벽은 돈-공급 늘리는 주요 산유국들 국제유가 60달러선 깨질까△의료기기 수출 특수-구부려 찍는 엑스레이, 바늘 없는 채혈기 틈새 찌르니 수출이 터졌다-“글로벌 판매량 1위 비결은 공격적 R&D”-막대한 자본 필요한 중대형 기기는 다국적기업 몫△정치-정당해산 위협에도…여론전 외엔 마땅한 대응 카드없는 국민의힘-휴가 떠난 李대통령, 韓美 정상회담·광복절 메시지 등 고심-美, 中 겨냥한 동맹 현대화 압박 가능성 커…실용외교 시험대-자본시장 신뢰 스스로 걷어찬 與△경제-“4000억이나 세수 줄어든다” 쏙 들어간 통신비 세액공제-탈세 규모 상관없이…주가 조작하면 대기업도 공시-공정위, 정책 발굴 시동…해외 경쟁당국 최신 제도 살핀다△금융-은행권, 전세·신용대출 줄줄이 중단 초강수-삼성화재, ‘5호선 방화’ 피해 미리 보상한다-車보험 구조적 적자…4대 손보사 2분기 순익 감소△글로벌-美, 깎아줄 기미없자…손 내민 스위스·캐나다-보잉 방산부문 노조 30여 년 만에 파업-애플 보란듯…저커버그 “아이폰 다음은 메타글라스”-잘 나가는 한국쌀 日수출 역대 최대△산업-완성차업계 美관세 쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직', 'SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', 'SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '사진=게티이미지뱅크미국 내 전기차 보조금 폐지를 앞둔 가운데 기관 투자사들은 오히려 2차전지 종목을 적극 사들인 것으로 나타났다. 증권가에선 순환매 장세에 따라 저평가된 2차전지 업종에 투자금이 몰렸다고 분석한다.5일 한국거래소에 따르면 지난달 이후 이날까지 국내 증시에서 기관 투자사들이 가장 많이 사들인 종목은 LG에너지솔루션(5927억원)으로 집계됐다. 삼성SDI(1377억원)와 엘앤에프(530억원) 등도 순매수 상위권에 이름을 올렸다.기관의 매수세에 힘입어 2차전지 업종도 모처럼 반등에 성공했다. 주요 2차전지 종목을 모은 \'KRX 2차전지 TOP10 지수\'와 \'KRX 전기차 TOP15 지수\'는 각각 13.85%, 12.72% 급등했다. 전체 34개 KRX 테마지수 중 수익률 상위 1, 2위를 기록했다.증권가에선 2차전지 섹터를 단기 투자처로 보고 있다. 국내 2차전지 기업들의 에너지저장장치(ESS) 수주 기대와 리튬 가격 상승을 호재로 꼽으면서다. 주민우 NH투자증권 연구원은 "오는 9월까지는 2차전지 관련주의 주가가 오를 것"이라면서 LG에너지솔루션은 최우선주로 제시했다. 향후 미국에서 ESS 수주가 늘어남에 따라 LG에너지솔루션이 수혜를 입을 것이란 분석에서다.지난해부터 2차전지주 주가가 크게 떨어진 만큼 추가 하락 폭이 크지 않을 것이란 관측도 고개를 들고 있다. 자산운용업계 관계자는 "반도체 섹터에서 차익 실현하는 대신 그간 주가가 많이 내린 2차전지 종목으로 투자금을 옮기는 추세"라고 설명했다.일각에선 올해도 2차전지 업황이 개선되긴 쉽지 않을 것으로 전망한다. 미국 정부가 지급하는 전기차 구입 보조금이 오는 9월 30일 종료되면 판매가 더 줄어들 수 있다는 분석 때문이다. 유럽 전기차 시장은 성장이 기대되지만 최근 중국 기업이 물량 공세를 펼치고 있기 때문에 국내 2차전지업체들이 시장에 침투하기 쉽지 않을 것이란 분석도 나온다.조현렬 삼성증권 연구원은 "미국 내 보조금이 사라지면 전기차 수요 관련 불확실성이 커질 것"이라며 "전기차 배터리 생산 비중이 높은 업체들의 수익 감소는 불가피하다"고 말했다.', "줄여 종가 기준 7만원선 회복에는 실패했다.금리 인하 기대가 커지면서 LG에너지솔루션(2.93%), POSCO홀딩스(2.76%) 등 이차전지주와 삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다.지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다.반면 현대차(-0.24%), 기아(-1.36%) 등 자동차주가 내렸다.아울러 카카오(-1.26%)는 정부가 추진하는 '독자 AI 파운데이션 모델' 구축 사업의 지원 대상으로 선정되지 못했다는 보도에 하락했고 자회사가 지원 대상으로 선정된 NAVER(-0.22%)도 내렸다.업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다.코스닥시장에서 외국인과 기관이 각각 467억원, 256억원 순매수했으며, 개인은 631억원 매도 우위를 보였다.에코프로비엠이 2분기 호실적을 공개하면서 15.28% 급등했으며, 모회사 에코프로(8.54%)도 뛰었다.아울러 알테오젠(2.78%), 펩트론(0.34%), 파마리서치(1.62%), 레인보우로보틱스(3.82%) 등도 상승했다.반면 HLB(-0.63%), 에스엠(-0.07%), 펄어비스(-0.51%), 네이처셀(-0.84%) 등은 하락했다.이날 유가증권시장과 코스닥시장의 거래대금은 각각 10조9천470억원, 4조7천850억원으로 집계됐다.대체거래소 넥스트레이드의 프리마켓과 정규마켓의 거래대금은 총 7조630억원이다.mylux@yna.co.kr"]
이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.
['0', '1', '1', '1', '1']
['[이데일리 정두리 기자] 다음은 8월 5일자 이데일리 신문 주요 기사다.△1면-관세 못 내면 4중 처벌, 최저임금 어기면 징역 3년-LG·네이버 등 5곳 국가대표AI 만든다-신한銀, 1주택자 전세대출도 빗장-정밀·소형화 통했다 해외뻗는 K의료기기-[사설]교육세제 문제엔 눈감고 금융사 세율만 올리는 정부-[사설]조선업계 마스가 TF 가동, 민관협력 효과 극대화해야△국가대표 AI 톱5 선정-LG “프런티어 AI 활용한 생태계 구축”…네이버 “국민체험형 서비스 개발”-SKT·KT 출신 손잡은 업스테이지…스타트업 유일 골든티켓△기업 경제형벌 합리화 목소리-회계 허위 기재하면 살인죄와 같은 형량…“모기 잡는데 폭탄 쓰는 꼴”-AI교과서 교육자료로 격하…업계 “소송전 불사”-쌀 공급과잉 미리 막는다…여야 농업 4법 합의 입법△종합-소비쿠폰 노린 대형 식자재마트, 단말기 바꿔 결제…“꼼수 영업 막아야”-韓 제조업체 10곳 중 8곳 “주력제품, 이미 레드오션”-미혼남녀 60% 결혼하고 싶어도…현실 장벽은 돈-공급 늘리는 주요 산유국들 국제유가 60달러선 깨질까△의료기기 수출 특수-구부려 찍는 엑스레이, 바늘 없는 채혈기 틈새 찌르니 수출이 터졌다-“글로벌 판매량 1위 비결은 공격적 R&D”-막대한 자본 필요한 중대형 기기는 다국적기업 몫△정치-정당해산 위협에도…여론전 외엔 마땅한 대응 카드없는 국민의힘-휴가 떠난 李대통령, 韓美 정상회담·광복절 메시지 등 고심-美, 中 겨냥한 동맹 현대화 압박 가능성 커…실용외교 시험대-자본시장 신뢰 스스로 걷어찬 與△경제-“4000억이나 세수 줄어든다” 쏙 들어간 통신비 세액공제-탈세 규모 상관없이…주가 조작하면 대기업도 공시-공정위, 정책 발굴 시동…해외 경쟁당국 최신 제도 살핀다△금융-은행권, 전세·신용대출 줄줄이 중단 초강수-삼성화재, ‘5호선 방화’ 피해 미리 보상한다-車보험 구조적 적자…4대 손보사 2분기 순익 감소△글로벌-美, 깎아줄 기미없자…손 내민 스위스·캐나다-보잉 방산부문 노조 30여 년 만에 파업-애플 보란듯…저커버그 “아이폰 다음은 메타글라스”-잘 나가는 한국쌀 日수출 역대 최대△산업-완성차업계 美관세 쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직', '삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.', '삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.', '삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.', '삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.']
이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '0', '1']

In [101]:
rerank_df_before_total = pd.DataFrame(list(map(lambda x: x.metadata,before_lst_total)))

In [ ]:
rerank_df_before_total

       ticker label  original_idx  chunk_idx
0        셀트리온     0           284          0
1     두산에너빌리티     1           231          0
2      SK하이닉스     1            64          0
3    LG에너지솔루션     1            99          0
4        셀트리온     1           275          0
..        ...   ...           ...        ...
295  삼성바이오로직스     1           119          0
296  LG에너지솔루션     1            88          1
297   두산에너빌리티     1           215          1
298   두산에너빌리티     1           216          0
299      KB금융     1           195          1

[300 rows x 4 columns]

In [ ]:
rerank_df_before_total[rerank_df_before_total.ticker == '삼성전자'].original_idx.value_counts() # 1/6 %..

original_idx
22    3
21    2
36    2
15    1
6     1
Name: count, dtype: int64

In [201]:
rerank_eval_total = []

In [202]:
for kind in target_lst[:10]:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target_before_total = rerank_df_before_total[rerank_df_before_total.ticker==kind]
    rerank_eval_total.append(eval_reranker_chunk(total_df_target,rerank_df_target_before_total))

total_rel_pool : 34
y_topk : [1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [0 1 1 0 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 0 1]

In [205]:
rerank_eval_con_before_total = dict(zip(target_lst[:10],rerank_eval_total))

In [206]:
pd.DataFrame(rerank_eval_con_before_total)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.566667
Recall@30(pool),0.294118,0.261905,0.595745,0.75,0.909091,0.535714,0.638298,0.681818,0.75,0.472222
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.500000
MAP@30,0.333333,0.366667,0.933333,1.00,1.000000,0.535714,1.000000,1.000000,1.00,0.322495
nDCG@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.771656
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,10.000000,11.000000,28.000000,30.00,30.000000,15.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,10.000000,11.000000,28.000000,30.00,30.000000,15.000000,30.000000,30.000000,30.00,17.000000

## Re-ranker 모델 사용 후 (openai)

## 1. 종목별 reranker

In [112]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=30)
#compression_retriever = ContextualCompressionRetriever(
#    base_compressor=compressor, base_retriever=retriever_total
#)

검색 유사도 측정
 - 이유 : 적정한 조건을 찾기 위함

In [113]:
scored_docs = []

In [114]:
for ticker in target_lst[:10]:
    retriever = vectordb_openai.as_retriever(search_kwargs={"k": 30,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs.append(dd)
    #scored_docs.sort(key=lambda x: (x.metadata[''],x.metadata["relevance_score"]), reverse=True)

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

RuntimeError: MPS backend out of memory (MPS allocated: 13.72 GB, other allocations: 3.01 GB, max allowed: 18.13 GB). Tried to allocate 1.79 GB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

In [212]:
# 4) 확인 - raw data
for i, d in enumerate(scored_docs, 1):
    if d.metadata['ticker'] == '삼성전자':
        print(f"{i:02d} | ticker : {d.metadata['ticker']}| original_idx : {d.metadata['original_idx']} | chunk_idx : {d.metadata['chunk_idx']}| score : {d.metadata['relevance_score']:.4f}")

01 | ticker : 삼성전자| original_idx : 21 | chunk_idx : 0| score : 0.0052
02 | ticker : 삼성전자| original_idx : 22 | chunk_idx : 1| score : 0.0037
03 | ticker : 삼성전자| original_idx : 28 | chunk_idx : 1| score : 0.0010
04 | ticker : 삼성전자| original_idx : 4 | chunk_idx : 0| score : 0.0018
05 | ticker : 삼성전자| original_idx : 5 | chunk_idx : 1| score : 0.0005
06 | ticker : 삼성전자| original_idx : 9 | chunk_idx : 0| score : 0.0031
07 | ticker : 삼성전자| original_idx : 24 | chunk_idx : 0| score : 0.0137
08 | ticker : 삼성전자| original_idx : 5 | chunk_idx : 0| score : 0.0016
09 | ticker : 삼성전자| original_idx : 13 | chunk_idx : 0| score : 0.0015
10 | ticker : 삼성전자| original_idx : 14 | chunk_idx : 1| score : 0.0002
11 | ticker : 삼성전자| original_idx : 30 | chunk_idx : 0| score : 0.0036
12 | ticker : 삼성전자| original_idx : 22 | chunk_idx : 0| score : 0.0001
13 | ticker : 삼성전자| original_idx : 36 | chunk_idx : 1| score : 0.0043
14 | ticker : 삼성전자| original_idx : 25 | chunk_idx : 0| score : 0.0080
15 | ticker : 삼성전자| original_idx : 14 | chunk_idx : 0| score : 0.0008
16 | ticker : 삼성전자| original_idx : 28 | chunk_idx : 0| score : 0.0055
17 | ticker : 삼성전자| original_idx : 34 | chunk_idx : 1| score : 0.0065
18 | ticker : 삼성전자| original_idx : 11 | chunk_idx : 0| score : 0.0000
19 | ticker : 삼성전자| original_idx : 7 | chunk_idx : 2| score : 0.0007
20 | ticker : 삼성전자| original_idx : 30 | chunk_idx : 1| score : 0.0010
21 | ticker : 삼성전자| original_idx : 20 | chunk_idx : 0| score : 0.0035
22 | ticker : 삼성전자| original_idx : 15 | chunk_idx : 1| score : 0.0008
23 | ticker : 삼성전자| original_idx : 36 | chunk_idx : 0| score : 0.0303
24 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 0| score : 0.0014
25 | ticker : 삼성전자| original_idx : 10 | chunk_idx : 0| score : 0.0039
26 | ticker : 삼성전자| original_idx : 10 | chunk_idx : 1| score : 0.0005
27 | ticker : 삼성전자| original_idx : 34 | chunk_idx : 2| score : 0.0001
28 | ticker : 삼성전자| original_idx : 18 | chunk_idx : 0| score : 0.0031
29 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 7| score : 0.0002
30 | ticker : 삼성전자| original_idx : 11 | chunk_idx : 1| score : 0.0002

### Re-Ranker 모델 측정

In [ ]:
rerank_df = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs)))

NameError: name 'scored_docs' is not defined

In [ ]:
rerank_df.ticker.value_counts()

NameError: name 'rerank_df' is not defined

In [ ]:
rerank_df.head()

   original_idx  chunk_idx label ticker  relevance_score
0            21          0     1   삼성전자         0.005221
1            22          1     1   삼성전자         0.003735
2            28          1     1   삼성전자         0.001007
3             4          0     1   삼성전자         0.001850
4             5          1     1   삼성전자         0.000533

In [ ]:
rerank_df= rerank_df.sort_values(by=['ticker','relevance_score'],ascending=False)

In [ ]:
rerank_df.ticker.value_counts()

ticker
현대차          30
한화에어로스페이스    30
셀트리온         30
삼성전자         30
삼성바이오로직스     30
두산에너빌리티      30
SK하이닉스       30
LG에너지솔루션     30
KB금융         30
HD현대중공업      30
Name: count, dtype: int64

In [218]:
rerank_df[rerank_df.ticker=='삼성전자'].label.value_counts()

label
1    25
0     5
Name: count, dtype: int64

In [219]:
VecDB = vectordb_openai._collection
total_results = VecDB.get(
         include = ['documents','metadatas']   
        )

In [220]:
total_df = pd.DataFrame(total_results['metadatas'])

In [221]:
total_df.shape

(423, 4)

In [222]:
total_df.ticker.value_counts()

ticker
삼성전자         59
LG에너지솔루션     47
KB금융         47
두산에너빌리티      46
SK하이닉스       42
삼성바이오로직스     40
HD현대중공업      40
셀트리온         38
한화에어로스페이스    33
현대차          31
Name: count, dtype: int64

In [223]:
total_df[total_df.ticker=='삼성전자'].label.value_counts()

label
1    34
0    25
Name: count, dtype: int64

In [224]:
rerank_eval = []

In [225]:
for kind in target_lst[:10]:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target = rerank_df[rerank_df.ticker==kind]
    rerank_eval.append(eval_reranker_chunk(total_df_target,rerank_df_target))

total_rel_pool : 34
y_topk : [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]

In [226]:
rerank_eval_con = dict(zip(target_lst[:10],rerank_eval))

In [227]:
pd.DataFrame(rerank_eval_con)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.833333,1.000000,1.000000,1.00,1.000000,0.933333,1.000000,1.000000,1.00,0.933333
Recall@30(pool),0.735294,0.714286,0.638298,0.75,0.909091,1.000000,0.638298,0.681818,0.75,0.777778
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.500000
MAP@30,0.747611,1.000000,1.000000,1.00,1.000000,0.991880,1.000000,1.000000,1.00,0.820347
nDCG@30,0.965826,1.000000,1.000000,1.00,1.000000,0.998366,1.000000,1.000000,1.00,0.905694
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,30.000000,30.000000,30.000000,30.00,30.000000,30.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,25.000000,30.000000,30.000000,30.00,30.000000,28.000000,30.000000,30.000000,30.00,28.000000

## 전체 문서에 대한 Reranking

In [241]:
import gc
gc.collect()

3178

In [244]:
scored_docs_total = []

In [245]:
for ticker in target_lst[:10]:
    retriever = vectordb_openai.as_retriever(search_kwargs={"k": 50})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs_total.append(dd)

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대차"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대차가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "KB금융"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, KB금융가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "두산에너빌리티"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 두산에너빌리티가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "HD현대중공업"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, HD현대중공업가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "셀트리온"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 셀트리온가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [21]:
rerank_df_total = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs_total)))

NameError: name 'scored_docs_total' is not defined

In [250]:
rerank_df_total= rerank_df_total.sort_values(by=['ticker'],ascending=False)

In [251]:
rerank_eval_total = []

In [252]:
for kind in target_lst[:10]:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target_total = rerank_df_total[rerank_df_total.ticker==kind]
    rerank_eval_total.append(eval_reranker_chunk(total_df_target,rerank_df_target_total))

total_rel_pool : 34
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1]

In [253]:
rerank_eval_con_total = dict(zip(target_lst[:10],rerank_eval_total))

In [254]:
pd.DataFrame(rerank_eval_con_total)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.923077,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.800000
Recall@30(pool),0.705882,0.523810,0.638298,0.75,0.909091,0.785714,0.638298,0.681818,0.75,0.666667
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,1.000000
MAP@30,0.784945,0.733333,1.000000,1.00,1.000000,0.785714,1.000000,1.000000,1.00,0.679583
nDCG@30,0.995947,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.954803
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,26.000000,22.000000,30.000000,30.00,30.000000,22.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,24.000000,22.000000,30.000000,30.00,30.000000,22.000000,30.000000,30.000000,30.00,24.000000

## 사용하기 전(bge)

In [34]:
VecDB_bge = vectordb_bge._collection
total_results_bge = VecDB.get(
         include = ['documents','metadatas']   
        )

In [36]:
total_df_bge = pd.DataFrame(total_results_bge['metadatas'])

In [255]:
before_lst_bge = []

In [256]:
for ticker in target_lst[:10]:
    retriever = vectordb_bge.as_retriever(search_kwargs={"k": 30,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    before_lst_bge.extend(raw_docs)
    print(list(map(lambda x: x.metadata['label'],raw_docs))[:5])
    print(list(map(lambda x: x.page_content,raw_docs))[:5])

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '0', '1', '0']
['삼성전자 모델이 5일 기존 식기세척기보다 에너지 소비효율 등급은 한 단계 높이고, 물 사용량은 10%가량 줄인 2025년형 ‘비스포크 식기세척기 카운터탑’ 신제품을 소개하고 있다.', '하이디는 챗GPT처럼 AI 지식 검색, 영상회의 실시간 번역, 회의록 작성, 메일 요약과 초안 작성 등을 지원한다. 내부망에서 사용하기 때문에 외부로 정보가 유출되는 걸 원천적으로 차단할 수 있다. 하이디 도입으로 하루 평균 업무 생산성이 약 10% 향상됐는데, LG디스플레이는 이를 3년 내 30%까지 끌어올릴 방침이다. 외부 솔루션 대신 하이디를 자체 개발함으로써 연간 100억원에 이르는 비용 절감 효과도 거뒀다.다른 제조기업에도 AI 도입 바람이 불고 있다.조주완 LG전자 사장은 지난달 AX를 주제로 열린 임직원 소통 행사 \'AX 토크콘서트\'에 참석해 생성형 AI 데이터 시스템 \'찾다(CHATDA)\' 등을 소개했다.삼성전기는 AI를 기반으로 생산을 자동화하는 프로젝트를 진행 중이다. 이를 통해 중국 기업과 경쟁할 수 있는 생산성을 확보하겠다는 것이다.삼성전자 반도체 부문은 지난해 말 SAIT(옛 종합기술원) 산하에 있던 AI센터와 DS부문 내 혁신센터를 통합해 \'AI센터\'를 신설했다. AI를 활용해 반도체 연구개발(R&D) 역량을 높이려는 목적이다.한 국내 전자업체 CEO는 "한국보다 수십 배 많은 엔지니어를 배출하는 중국과의 경쟁에서 살아남기 위해 한국은 AI에서 답을 찾아야 한다"면서 "공장을 무인 자동화하고 AI를 활용해 R&D를 진행하는 것이 유일한 생존 방법"이라고 조언했다.[이덕주 기자]', '찾지 못했다고 보도했다. 내가 기업들, 정부, 과학자들, 변호사들, 중재자들, 피해자들과 나눈 대화에 따르면 이는 진실이 아니다"라고 썼다. 노 의원은 이 사례를 소개하면서 "이게 우리 언론의 진실"이라며 토론을 마무리했다.우원식 국회의장은 노 의원 토론을 듣고 나서 "언론의 오보를 하나하나 설명하는 게 국민들 관심을 많이 끌었을 것 같고 천성산 사례나 황유미씨 사건을 설명한 건 울림이 있었을 것 같다"고 말했다.', '있다. 삼성전자는 최근 스마트폰·가전 사업 등을 담당하는 디바이스 경험(DX) 부문에 인공지능 기술을 활용한 제조 자동화 등 미래 전략 과제를 전담하는 조직인 ‘이노X랩’(혁신과 전환을 합친 말)을 신설했다. 회사 관계자는 “모든 업무에 인공지능을 적용하겠다는 노태문 디바이스경험부문장 직무대행(사장)의 의지에 따라 특별 태스크포스(TF)를 만들어 지원하겠다는 취지”라고 했다.에스케이(SK)그룹도 지난해 말 그룹 최고 의사협의체인 수펙스추구협의회 내에 인공지능 추진단을 확대 신설하며 계열사들의 인공지능 전환을 이끌고 있다. 에스케이는 그룹 총수인 최태원 회장이 직접 제조업 인공지능을 경제계의 최대 현안으로 띄우고 있다.권보경 포스코경영연구원 수석연구원은 “한국 제조 기업들은 중국보다 인공지능 기술 도입이 뒤처진 상태로, 자체 클라우드(인터넷 기반의 정보 저장 공간)와 보안 시스템 등 국내에 인공지능 활용 인프라를 구축할 필요가 있다”고 말했다.', '거고 굉장히 의미 있다고 저는 생각을 합니다. 그래서 훨씬 뭐, 수사심의위원회 아시잖아요. 대검에 들어와가지고 지난번에도 이재용 삼성전자 회장이라든지.][앵커]외부 전문가가.[박범계 / 더불어민주당 의원 : 네. 외부 전문가들이 모여가지고 하는데 검찰하고 항상 엇박자가 나죠. 그런 측면에서 이것을 제도화하는 거니까 의미가 있다고 보고. 법원 개혁도 대법관 수를 늘리는 것에서 더 나아가서 시민 통제라는 관점에서 놓고 보면 미국은 배심제를 취하고 있지만 우리는 국민참여재판을 의무적으로 하는 배심제에 가까운 형태를 도입할 거냐. 대법관 구성의 다양성을 어떻게 확보할 거냐라는 시민통제. 시민의 눈높이로 보는 통제. 마찬가지로 지금 검찰이나 법원 그다음에 하나가..][앵커]언론이요?[박범계 / 더불어민주당 의원 : 언론. 언론개혁도 오늘 드디어 방송법. KBS법입니다. 다음에는 MBC, 방문진법이고 그다음 EBS 방송법 이렇게 되는데요. 오늘 결국은 핵심은 1명의 양심 있는. 양심이 없는 사람도 있는데 양심 있는 예를 들어서 보도본부장이라든지 앵커라든지 그 얘기를 어제 신동욱 의원이 많이 얘기합디다. 그러나 1명, 2명보다는 적어도 시민 참여 위원회를 통해서 다수의 집단지성을 하는 것이 훨씬 민주적이다라는 우리 믿음으로 통과를 시킨 거거든요.][앵커]알겠습니다. 시민통제, 시민참여가 키워드라고 보고 국민들이 이걸 지켜보면 되겠군요.[박범계 / 더불어민주당 의원 : 그렇습니다][앵커]알겠습니다. 지금까지 민주당 박범계 의원과 함께했습니다. 바쁘신데 나와주셔서 고맙습니다.[박범계 / 더불어민주당 의원 : 고맙습니다.]']
이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '1']
['삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방 요인으로 작용할 것"이라고 전망했다．', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '1%대 올랐다. 클래시스, 휴젤, 펩트론은 강보합권이었다. HLB는 약보합세, 삼천당제약은 1%대 약세였다.서울 외환시장에서 원/달러 환율은 이날 오후 3시30분 기준 전일 대비 3.1원 오른 1388.3원을 나타낸다.이번주 굵직한 경제 지표 발표는 없으나 국내 주요 기업들의 실적이 대거 몰려있다. 김지원 KB증권 연구원은 "에코프로, 카카오, 네이버, LG화학, SK텔레콤 등 주요 기업들이 실적 발표가 예정돼 있다"며 "최근 급등에 따른 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승 가능성이 존재한다"고 짚었다.', '이차전지, 바이오주 등 성장주가 상대적 강세를 보였다”고 설명했다.엔비디아 강세에 SK하이닉스(2.13%)가 3거래일 만에 종가 기준 26만원을 웃돌았다. 삼성전자(0.29%)는 장중 ‘7만전자’를 터치했으나 오름폭을 줄여 종가 기준 7만원선 회복에는 실패했다.금리 인하 기대가 커지면서 LG에너지솔루션(2.93%), POSCO홀딩스(2.76%) 등 이차전지주와 삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다.지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다.반면 현대차(-0.24%), 기아(-1.36%) 등 자동차주는 내렸다.아울러 카카오(-1.26%)는 정부가 추진하는 ‘독자 AI 파운데이션 모델’ 구축 사업의 지원 대상으로 선정되지 못했다는 보도에 하락했고 자회사가 지원 대상으로 선정된 NAVER(-0.22%)도 내렸다.업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다.코스닥시장에서 외국인과 기관이 각각 467억원, 256억원 순매수했으며, 개인은 631억원 매도 우위를 보였다.에코프로비엠이 2분기 호실적을 공개하면서 15.28% 급등했으며, 모회사 에코프로(8.54%)도 뛰었다.아울러 알테오젠(2.78%), 펩트론(0.34%), 파마리서치(1.62%), 레인보우로보틱스(3.82%) 등도 상승했다.반면 HLB(-0.63%), 에스엠(-0.07%), 펄어비스(-0.51%), 네이처셀(-0.84%) 등은 하락했다.이날 유가증권시장과 코스닥시장의 거래대금은 각각 10조9470억원, 4조7850억원으로 집계됐다.대체거래소 넥스트레이드의 프리마켓과 정규마켓의 거래대금은 총 7조630억원이다.', '실적 컨퍼런스콜에서 "파트너사와 함께 시스템 내 성능 최적화를 위한 협업을 진행 중이며, HBM 부문을 지난해보다 약 2배 성장시킬 계획"이라고 전했다. SK하이닉스는 HBM4에 10나노급 5세대(1b) 공정을 적용해 이미 수율 안정화를 마치고, 빠르게 생산량 확대(램프업)에 돌입한 것으로 파악된다. 이르면 이번 분기부터 HBM4 매출 반영도 시작될 것으로 기대를 모은다.■공급과잉론 돌파양사의 움직임은 일각에서 제기된 HBM 공급 과잉론을 정면으로 반박하는 행보다. 앞서 글로벌 투자은행 골드만삭스는 보고서를 통해 기존 SK하이닉스가 주도하던 HBM 시장에 삼성전자, 마이크론의 진입으로 경쟁이 심화하면서 HBM 가격이 하락할 수 있다고 경고했다. 그러나 주요 빅테크 기업들이 지속적으로 AI 인프라 투자를 확대하고 있고, HBM4나 커스텀(맞춤형) HBM 같은 차세대 HBM에 대한 수요는 끊이지 않을 것이란 분석이 지배적이다. 반도체 업계 관계자는 "HBM은 현재 물량이 없어서 못 팔고 있는 수준"이라며 "특히 HBM4의 경우 어디가 엔비디아에 먼저 들어가는지 양산 경쟁을 하고 있는 상황이라 시장은 더 활기를 띨 것"이라고 전했다.업계에서는 향후 차세대 HBM 시장을 잡는 기업이 메모리 시장에서 승자가 될 것으로 보고 있다. HBM 시장 1위인 SK하이닉스는 올 2·4분기 영업이익 9조2129억원, 영업이익률 41%를 기록, 사상 최대 실적을 달성했다. HBM 주도권을 잡은 것이 핵심 역할을 했다. SK하이닉스는 2·4분기 글로벌 메모리반도체 시장에서 삼성전자를 제치고 사상 처음으로 매출 1위를 차지하기도 했다.시장조사업체 카운터포인트리서치에 따르면 SK하이닉스는 2·4분기 D램과 낸드를 포함한 전체 메모리 시장에서 21조8000억원의 매출을 기록했다. 같은 기간 삼성전자의 메모리반도체 매출은 21조2000억원에 그쳤다.soup@fnnews.com 임수빈 조은효 기자']
이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['사진=게티이미지뱅크미국 내 전기차 보조금 폐지를 앞둔 가운데 기관 투자사들은 오히려 2차전지 종목을 적극 사들인 것으로 나타났다. 증권가에선 순환매 장세에 따라 저평가된 2차전지 업종에 투자금이 몰렸다고 분석한다.5일 한국거래소에 따르면 지난달 이후 이날까지 국내 증시에서 기관 투자사들이 가장 많이 사들인 종목은 LG에너지솔루션(5927억원)으로 집계됐다. 삼성SDI(1377억원)와 엘앤에프(530억원) 등도 순매수 상위권에 이름을 올렸다.기관의 매수세에 힘입어 2차전지 업종도 모처럼 반등에 성공했다. 주요 2차전지 종목을 모은 \'KRX 2차전지 TOP10 지수\'와 \'KRX 전기차 TOP15 지수\'는 각각 13.85%, 12.72% 급등했다. 전체 34개 KRX 테마지수 중 수익률 상위 1, 2위를 기록했다.증권가에선 2차전지 섹터를 단기 투자처로 보고 있다. 국내 2차전지 기업들의 에너지저장장치(ESS) 수주 기대와 리튬 가격 상승을 호재로 꼽으면서다. 주민우 NH투자증권 연구원은 "오는 9월까지는 2차전지 관련주의 주가가 오를 것"이라면서 LG에너지솔루션은 최우선주로 제시했다. 향후 미국에서 ESS 수주가 늘어남에 따라 LG에너지솔루션이 수혜를 입을 것이란 분석에서다.지난해부터 2차전지주 주가가 크게 떨어진 만큼 추가 하락 폭이 크지 않을 것이란 관측도 고개를 들고 있다. 자산운용업계 관계자는 "반도체 섹터에서 차익 실현하는 대신 그간 주가가 많이 내린 2차전지 종목으로 투자금을 옮기는 추세"라고 설명했다.일각에선 올해도 2차전지 업황이 개선되긴 쉽지 않을 것으로 전망한다. 미국 정부가 지급하는 전기차 구입 보조금이 오는 9월 30일 종료되면 판매가 더 줄어들 수 있다는 분석 때문이다. 유럽 전기차 시장은 성장이 기대되지만 최근 중국 기업이 물량 공세를 펼치고 있기 때문에 국내 2차전지업체들이 시장에 침투하기 쉽지 않을 것이란 분석도 나온다.조현렬 삼성증권 연구원은 "미국 내 보조금이 사라지면 전기차 수요 관련 불확실성이 커질 것"이라며 "전기차 배터리 생산 비중이 높은 업체들의 수익 감소는 불가피하다"고 말했다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '거래되고 있고, 같은 기간 SK하이닉스(000660)는 4000원(1.55%) 오른 26만 2000원을 가리키고 있다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.66%, 2.13% 오르고 있다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.17% 하락세다.한편 코스닥 지수는 전 거래일 대비 13.36포인트(1.70%) 오른 797.42에 거래되고 있다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 464억원 순매도하고 있으며 외국인과 기관 투자자가 각각 388억원, 176억원치를 순매수하며 매수 우위를 이어나가고 있다. 프로그램별로는 차익과 비차익을 합쳐 187억원 매수 우위를 나타내고 있다.', '1%대 올랐다. 클래시스, 휴젤, 펩트론은 강보합권이었다. HLB는 약보합세, 삼천당제약은 1%대 약세였다.서울 외환시장에서 원/달러 환율은 이날 오후 3시30분 기준 전일 대비 3.1원 오른 1388.3원을 나타낸다.이번주 굵직한 경제 지표 발표는 없으나 국내 주요 기업들의 실적이 대거 몰려있다. 김지원 KB증권 연구원은 "에코프로, 카카오, 네이버, LG화학, SK텔레콤 등 주요 기업들이 실적 발표가 예정돼 있다"며 "최근 급등에 따른 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승 가능성이 존재한다"고 짚었다.', '필요가 있다”고 설명했다.이어 “이번 정치권 내 논의 과정에서 대주주 양도세 뿐만 아니라 배당소득 분리과세가 시장 친화적으로 변경될지 여부도 추후 증시 반전의 재료가 될 전망”이라고 내다봤다.이날 코스피 시장에선 대형주가 1.59%, 중형주가 1.53%, 소형주가 0.87% 모두 올랐다.업종별로는 대부분이 강보합이었다. 보험 업종이 2.71% 전기·가스 업종이 2.14%, 금융 업종이 2.37% 등 상승했다. 다만 섬유·의류는 0.59%, IT서비스는 0.02% 떨어졌다.시가총액 상위 종목도 대부분 올랐다. 삼성전자(005930)는 전 거래일보다 200원(0.29%) 오른 6만 9900원에 거래됐고, 같은 기간 SK하이닉스(000660)는 5500원(2.13%) 오른 26만 3500원을 가리켰다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.93%, 2.45% 상승했다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.36% 하락했다.한편 코스닥 지수는 전 거래일 대비 7.88포인트(1.01%) 오른 791.94에서 출발해 14.54포인트(1.85%) 오른 798.60에 거래를 마쳤다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 752억원 순매도했으며 외국인과 기관 투자자가 각각 648억원, 176억원치를 순매수하며 매수 우위를 보였다. 프로그램별로는 차익과 비차익을 합쳐 375억원 매수 우위를 나타냈다.']
이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '1']
['세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '삼성바이오로직스(0.29%), 셀트리온(2.24%) 등 바이오주가 올랐다. 지난주 말 정부의 세제 개편안에 대한 실망감에 급락했던 KB금융(3.69%), 신한지주(3.19%) 등 금융주는 저가 매수세가 유입되며 이틀 연속 상승했다. 업종별로 보면 금융(2.37%), 화학(1.98%), 전기전자(1.72%) 등이 올랐으며 섬유의류(-0.59%) 등은 내렸다.코스닥지수도 전장보다 14.54포인트(1.85%) 오른 798.60에 장을 마쳤다. 지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 키워 한때 800선을 회복했으나 장중 오름폭을 줄였다. 코스닥시장에서 외국인과 기관이 각각 467억 원, 256억 원 순매수했으며, 개인은 631억 원 매도 우위를 보였다.', '코스피가 5일 오전 3200선 안팎에서 거래되고 있다. 사진은 5일 오전 서울 중구 하나은행 본점 딜링룸./사진=뉴시스코스피가 5일 오전 3200선 안팎에서 거래되고 있다.한국거래소에 따르면 코스피는 이날 오전 10시7분 기준 전 거래일 대비 1.71% 상승한 3201.72를 기록했다. 기관이 1293억원, 외국인이 1340억원 순매수했고 개인이 2808억원 순매도했다.시가총액 상위 종목도 대체로 상승했다. 시총이 큰 순으로 ▲삼성전자(1.15%)  ▲SK하이닉스(2.13%) ▲LG에너지솔루션(2.93%) ▲삼성바이오로직스(1.15%) ▲현대차(0.71%) ▲KB금융(3.60%) ▲HD현대중공업(1.73%) ▲두산에너빌리티(0.62%) 등이 올랐다. 삼성전자는 7만500원으로 7만전자로 복귀했다. 한화에어로스페이스(0.21%)는 내렸다.코스닥은 2.08% 오른 800.40이었다. 기관이 173억원, 외국인이 510억원 순매수했다. 개인은 641억원 순매도했다. 시총 상위 종목은 상승세였다. ▲알테오젠(2.89%) ▲에코프로비엠(13.43%) ▲에코프로(2.71%) ▲펩트론(0.68%) ▲HLB(0.52%) ▲파마리서치(2.16%) ▲레인보우로보틱스(4.78%) ▲리가켐바이오(3.68%) ▲삼천당제약(0.82%) ▲에이비엘바이오(3.49%) 등이다.서울 외환시장에서 원·달러 환율은 0.80원 내린 1385.20원에 거래됐다. 주요국 통화 대비 달러 가치를 나타내는 달러인덱스 지수는 0.03% 하락한 98.75다.']
이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['거래되고 있고, 같은 기간 SK하이닉스(000660)는 4000원(1.55%) 오른 26만 2000원을 가리키고 있다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.66%, 2.13% 오르고 있다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.17% 하락세다.한편 코스닥 지수는 전 거래일 대비 13.36포인트(1.70%) 오른 797.42에 거래되고 있다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 464억원 순매도하고 있으며 외국인과 기관 투자자가 각각 388억원, 176억원치를 순매수하며 매수 우위를 이어나가고 있다. 프로그램별로는 차익과 비차익을 합쳐 187억원 매수 우위를 나타내고 있다.', '왼쪽부터 러셀 보트 백악관 예산관리국장, 존 펠란 미 해군성 장관, 데이비드 김 한화필리조선소 대표가 지난달 30일(현지 시간) 미국 펜실베니아주 필라델피아 한화필리조선소를 둘러보고 있다. 한화그룹 제공한화그룹이 올해 국내 10대 그룹 중 기업가치가 가장 크게 상승한 것으로 나타났다. 한·미 조선 협력 프로젝트인 ‘마스가(MASGA)’가 국내 증시 지형에도 영향을 미친 것으로 풀이된다.5일 한화그룹 등에 따르면 지난해 12월30일 종가 기준 43조5000억원이던 한화그룹 13개 상장사 시가총액은 이달 1일 120조7000억원으로 77조2000억원이 올라 전체 규모 면에서 5위를 차지했다. 올해 코스피 상승분은 600조2000억원이었는데, 한화그룹 상장사들이 코스피 상승분의 12.9%를 견인한 셈이다.한화그룹의 시총 증가율은 177.4%로 코스피 상승폭(30.6%)이나 한화그룹을 제외한 10대 그룹 평균(30.3%)보다도 5배 이상 높았다. 다음으로 증가율이 높은 HD현대(51.7%), SK(35.7%)와 비교해도 압도적으로 높은 수치다.기업가치 상승에는 방위산업과 조선 분야 계열사의 주가 상승이 영향을 미쳤다. 한화에어로스페이스, 한화오션, 한화시스템 등 방산·조선 3사의 시총은 지난달 31일 기준 97조원에 달한다. 지난해 말 32만6000원이던 한화에어로스페이스 주가는 지난달 31일 99만6000원으로 245.1%나 뛰었다.특히 한화오션은 국내 조선업체가 한·미 관세 협상에서 결정적 역할을 하고 있다는 소식이 전해지면서 주가가 크게 올랐다. 지난해 말 3만7350원이던 한화오션 주가는 관세 협상 타결 직후인 이달 1일 11만7400원에 거래를 마쳤고, 시총은 35조9729억원으로 네이버를 제치고 코스피 시총 13위에 올랐다.한화오션의 미국 현지 사업이 한·미 관세 협상 타결에 지렛대 역할을 했다는 평가도 나온다. 한화오션은 지난해 말 필라델피아에 있는 필리조선소를 인수하면서 미국 현지 조선소를 보유한 유일한 국내 조선업체가 됐다. 존 펠란 미국 해군성 장관은 지난 4월 한화 거제조선소를 돌아본 데 이어, 관세 협상 타결 직전인 지난달 30일(현지시간)에는 러셀 보트 백악관 예산관리국장과 함께 필리조선소를 찾기도 했다.', '1~3위 조선업 테마 ETF가 휩쓸어한화오션·HD현대중공업 급등 영향한화오션이 건조한 LNG 운반선. <한화오션>최근 한 달간 상장지수펀드(ETF) 시장에서 조선과 방산 업종 관련 상품이 수익률 상위를 휩쓸었다. 상반기에 이어 하반기도 조선·방산 업종에 대한 투자자들의 관심이 이어지고 있다.5일 한국거래소와 코스콤에 따르면 ‘TIGER 조선TOP10’는 최근 한 달간 31.93% 오르며 전체 ETF 중 수익률 1위를 차지했다.이 ETF는 한화오션, HD현대중공업, HD한국조선해양, 삼성중공업, HD현대미포, 한화엔진 등에 투자한다.2, 3위도 조선업 테마 ETF가 차지했다. ‘SOL 조선TOP3플러스’가 30.77% 오르며 2위를 기록했고, ‘KODEX 친환경조선해운액티브’가 25.92% 상승하며 3위에 올랐다.조선업 대장주인 한화오션이 최근 한 달 동안 58.82% 오르면서 ETF 성과를 견인한 것으로 풀이된다.같은 기간 HD현대중공업은 24.73%, 삼성중공업은 25.64% 올랐다. HD한국조선해양(16.12%), HD현대미포(15.06%)도 동반 상승했다. 한화엔진은 53.27% 급등했다.방산 관련 ETF도 두각을 나타냈다. ‘PLUS K방산’이 수익률 24.73%로 4위를 차지했다.이 ETF는 한화오션, 현대로템, 한화에어로스페이스, LIG넥스원, 한국항공우주, 한화시스템 등을 구성 종목으로 담고 있다.개별 종목 기준으로도 방산주 상승세가 뚜렷했기 때문으로 해석된다.올 상반기 급등했던 방산주들은 최근 한 달간 두자릿수의 견조한 수익률을 기록했다.한화에어로스페이스는 12.66% 올랐고, 현대로템은 11.30% 상승했다. LIG넥스원은 25.18%의 수익률을 거뒀다. 한국항공우주와 한화시스템은 각각 11.69%, 11.75 상승했다.같은 기간 ‘HANARO Fn조선해운’이 23.60% 오르며 5위를 기록했고, ‘SOL K방산’이 23.49 상승하며 뒤를 이었다.이밖에도 전략자원, 원자력, 전력 인프라 관련 테마들이 10위권에 포진했다.‘PLUS 글로벌희토류&전략자원생산기업’(23.03%), ‘SOL 미국원자력SMR’(22.25%), ‘KODEX 미국AI전력핵심인프라’(21.16%), ‘HANARO 전력설비투자’(20.75%)가 상위권에 이름을 올렸다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.']
이 뉴스들 중에서 "현대차"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대차가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '1']
['부품 조달과 관련, 현대차 이승조 재경본부장(부사장)은 지난달 25일 2분기 실적발표 컨퍼런스콜에서 “현재 200여 개 부품에 대해 다양한 업체들로부터 견적을 받고 논의 중이며, 지속적으로 현지에서 부품 소싱 여부와 방법, 규모 등을 신중히 검토할 예정”이라고 밝혔다.이와 관련해 현대차그룹의 부울경 부품 협력업체들도 발등에 불이 떨어졌다.A사의 경우 미국 공장 설비를 배로 늘리기로 했고, 현지 공장이 없는 B사는 공장 신설을 검토중이다. 최근 현지 공장을 지은 C사는 현지 부품 공급에 어려움이 없다는 입장이다. 지역 최대 납품업체 가운데 하나인 D사 관계자는 “현대차그룹의 움직임에 따라 결정해야 할 문제이며 시장 상황을 파악 중”이라고 밝혔다.현대차그룹은 생산·부품 조달 확대와 함께 혼류생산과 로봇 확대 등을 통한 생산 효율을 높이고, 재료비·가공비 절감 노력도 함께 추진하기로 했다.', "기록했다. 연간 판매량 기준 5만대를 넘지 못할 것이라는 전망이 우세하다. 반면 하이브리드차와 전기차 판매량은 각각 20만3000여 대, 7만2000여 대로 디젤차 판매량의 10배, 3배를 기록하고 있다.디젤 차량은 중고차 시장에서도 외면받고 있다. 중고차 플랫폼 케이카가 올해 상반기 판매 데이터를 분석한 결과, 디젤차 비중은 14.9%로 지난해 같은 기간(18.4%) 대비 3.5%포인트 줄었다. 국내 수입차 시장에서도 디젤차 입지가 점점 좁아지고 있다. 올해 상반기 수입 디젤차 판매량은 1737대로 전체 판매량의 1.26%에 불과하다. 2015년 전체 수입차의 70%가량을 차지했던 디젤차는 '디젤게이트' 사건 이후로 판매량이 내리막길을 걸었다.한국수입자동차협회(KAIDA)가 집계하는 수입차 업체 26곳 중 지난 6월까지 디젤차를 판매한 업체는 아우디, BMW, 포드, 메르세데스-벤츠, 폭스바겐 등 5곳에 불과하다.[박제완 기자]", '판매량이 18만3000여 대로 디젤차 판매량(13만5000여 대)을 역전했다.올해 상반기 기준 디젤차 판매량은 2만2000여 대를 기록했다. 연간 판매량 기준 5만대를 넘지 못할 것이라는 전망이 우세하다. 반면 하이브리드차와 전기차 판매량은 각각 20만3000여 대, 7만2000여 대로 디젤차 판매량의 10배, 3배를 기록하고 있다.디젤 차량은 중고차 시장에서도 외면받고 있다. 중고차 플랫폼 케이카가 올해 상반기 판매 데이터를 분석한 결과, 디젤차 비중은 14.9%로 지난해 같은 기간(18.4%) 대비 3.5%포인트 줄었다. 2023년 기록한 20.9%와 비교하면 6%포인트 하락했다.국내 수입차 시장에서도 디젤차 입지가 점점 좁아지고 있다. 올해 상반기 수입 디젤차 판매량은 1737대로 전체 판매량의 1.26%에 불과하다. 2015년 전체 수입차의 70%가량을 차지했던 디젤차는 ‘디젤게이트’ 사건 이후로 판매량이 내리막길을 걸었다. 2023년부터는 전기차 판매량이 디젤차를 앞서기 시작했다.한국수입자동차협회(KAIDA)가 집계하는 수입차 업체 26곳 중 지난 6월까지 디젤차를 판매한 업체는 아우디, BMW, 포드, 메르세데스-벤츠, 폭스바겐 등 5곳에 불과하다. 디젤 신차를 출시하는 업체는 폭스바겐그룹인 아우디와 폭스바겐 2곳 정도다.', '경기도 평택항에 수출용 자동차가 세워져 있다. 연합뉴스정부가 한-미 관세 협상에서 일본, 유럽연합(EU)과 같은 자동차 품목관세 15%에 합의하면서, 기존 무관세 혜택을 누리던 한국 자동차업계는 일본과 유럽연합에 부과되던 일반 관세 2.5%만큼의 손해를 보게 됐다. 일본 자동차업계가 생산 기지를 구축한 멕시코·캐나다와의 관세 협상이라는 변수도 남아 있다. 하지만 자동차업계는 “해볼 만하다”는 분위기다.5일 한겨레 취재 내용을 종합하면 현대차·기아는 최근 미국 시장에서 판매되는 차량 종류가 다양화되는 부분에 주목하고 있다. 7월 미국 시장 판매 실적을 보면, 스포츠실용차(SUV)와 레저용 차량(RV) 등 큰 차량들의 판매 실적이 크게 늘었다. 현대차의 싼타페는 1만4128대가 팔려 지난해 7월에 견줘 판매량이 57.2% 늘었고, 팰리세이드(1만3235대), 제네시스(6687대)도 각각 53.5%, 8% 증가했다. 기아도 준대형 스포츠실용차인 텔루라이드가 1만411대, 카니발이 5928대 팔렸는데 각각 36.1%, 30.1% 증가한 실적이다.판매된 스포츠실용차와 레저용 차량에는 내연기관과 친환경차(하이브리드)가 포함되는데, 현대차·기아는 지난 7월 미국에서 친환경차 4만850대(지난해 대비 42.6% 증가)를 팔아 상승세를 보였다.미국 시장에서 최근 한국의 스포츠실용차와 레저용 차량 등 대형 차량과 하이브리드 등 친환경 차량에 대한 소비자의 관심이 높아진 것이 판매 실적으로 나타났다는 평가가 나온다. 9월30일부터 미국 현지에서 인플레이션감축법(IRA)에 따른 전기차 보조금이 폐지될 예정이어서, 하이브리드 자동차 수요는 더 증가할 것으로 예상된다.일본 현지 생산 비중이 낮은 일본의 완성차업체 빅3(도요타·혼다·닛산)는 일본의 자동차 관세 인하에도 큰 수혜를 기대하기 어렵다는 전망이 나온다. 4일 농협(NH)투자증권이 공개한 보고서를 보면 이들 세 업체는 미국에서 판매하는 차량의 생산 기지를 대부분 북미(미국·멕시코·캐나다)로 전환한 상태다. 도요타와 혼다, 닛산은 각각 판매량의 80.9%, 100%, 86.3%를 이미 북미에서 생산하기 때문에 관세 협상으로 인한 실적 개선이 크지 않다는 분석이다. 더구나 멕시코·캐나다는 여전히 25% 관세가 적용되고 있다. 반면 현대차·기아는 지난해 미국에서 판매한 170만대 가운데 85만9000대를 한국에서 만들어 수출했다. 품목관세 25%를 똑같이 15%로 낮추더라도 한국의', '올해 인도서 가장 많이 팔려누적 120만대로 점유율 31%현대차 인도 법인이 출시한 중형 전기 SUV \'크레타 EV\' 현대차 인도법인 제공【파이낸셜뉴스 뉴델리(인도)=프라갸 아와사티 통신원】현대차 인도 법인이 인도 시장에서 판매하는 중형 전기 스포츠유틸리티차량(SUV) \'크레타\'가 올해 인도 전역에서 가장 많이 팔린 차량에 등극했다. 현대차는 크레타 등의 인기에 힘입어 7월 내수 실적에서 2위를 되찾았다.5일 인도 현지 매체에 따르면 현대자동차 인도 법인은 올해 1월부터 7월까지 현대 크레타가 인도 전 차급을 통틀어 가장 많이 판매된 모델로 등극했다고 발표했다. 해당 기간 동안 크레타는 총 11만7458대가 판매됐다. 이는 전년 동기 대비 8% 성장한 수치다.타룬 가르그 현대차 인도 법인 최고운영책임자(COO)는 "현대 크레타의 출시 10주년을 맞아 인도 소비자들의 변함없는 사랑과 신뢰에 깊이 감사드린다"라며 "2025년 상반기 전체 세그먼트에서 판매 1위를 기록한 것은 단순한 수치를 넘어, 크레타가 인도 고객과 오랜 시간 쌓아온 감성적 유대의 증거"라고 밝혔다.현대차 인도 법인에 따르면 크레타는 올해 상반기 중 3개월간 전 차종 중 판매 1위를 기록했으며, 2015년 인도 시장에 첫 출시된 이후 누적 판매량은 120만대를 돌파했다. 특히 중형 SUV 시장에서는 31% 이상의 시장 점유율로 독주를 이어가고 있다.praghya@fnnews.com']
이 뉴스들 중에서 "KB금융"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, KB금융가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
["24일 서울 영등포구 여의도 63빌딩에서 바라본 여의도 증권가. 2024.1.24/뉴스1 ⓒ News1 김진환 기자(서울=뉴스1) 박승희 기자 = 세제 개편 우려로 급락했던 금융주 전반이 반등 중이다.5일 오전 11시 35분 KB금융지주(105560)는 전일 대비 3300원(3.04%) 오른 11만 1700원에 거래되고 있다. 지난 1일 4.42% 하락한 뒤 전날에 이어 2거래일 연속으로 상승 중이다.이외 신한금융지주회사(055550)(2.88%), 아이엠금융지주(139130)(2.37%), 우리금융지주(316140)(2.06%), 하나금융지주(086790)(1.64%) 등도 강세다.삼성화재해상보험(000810)(3.17%), 한화손해보험(000370)(3.45%), 신영증권(001720)(4.90%), NH투자증권(005940)(3.35%) 등 은행, 보험, 증권주 전반이 오르고 있다.앞서 금융주는 정부의 세제개편안 발표와 함께 하락한 바 있다. 정부가 낸 세제개편안에 따르면 주식 양도소득세 과세 대상인 대주주 기준을 50억 원에서 10억 원으로 낮추고, 증권 거래세를 상향하기로 했다.배당소득 분리과세도 기존에 기대했던 최고 세율 25%에서 35%로 상향되고 고배당 기업 조건도 시장 기대보다 엄격하게 제시됐다.이에 증시 부양 기대감으로 올랐던 금융주가 급락했지만, 투자자 반발에 정치권에서 재검토 논의가 힘을 얻으며 투심이 반등한 것으로 보인다.여기에 미국 연방준비제도(Fed·연준)의 금리 인하 기대도 긍정적인 영향을 미쳤다.미국 노동시장 약화와 '매파 성향'(통화긴축 선호)인 아드리아나 쿠글러 연준 이사의 퇴임으로 9월 연준의 금리 인하 가능성이 힘을 얻고 있다.", "은행 의존도가 82%로 높은 편이다. 올 상반기 하나은행은 순이익이 전년 동기 대비 19.1%나 증가한 2조851억원을 기록해 호실적을 거뒀다. 그러나 증권과 카드, 캐피탈, 자산신탁은 순이익이 모두 하락했다.▷관련기사:\xa0하나금융 상반기 순익 2.3조…비이자익 10% 껑충(7월25일)하나금융\xa0보험 계열사인 하나생명의 경우 순이익이 전년 동기 대비 54.1% 증가했지만, 순이익 규모가 142억원으로 하나캐피탈(149억원)보다 작다.KB·신한, 은행 끌고 비은행 밀었다상반기 사상 최대 실적을 기록한 KB금융과 신한금융의 경우 은행 호실적에 더해 비은행 부문, 특히 보험 계열사의 약진이 눈에 띄었다.KB금융은 올해 상반기 순이익 3조4357억원을 달성했다. 이는 지난해 상반기보다 23.8% 증가한 규모다.▷관련기사:\xa0KB금융, 상반기 역대급 성적표에 주주환원도 '역대급'(7월24일)KB손해보험은 순이익이 전년 동기 대비 2.3% 줄어든 5581억원을 기록했으나, KB금융 비은행 계열사 중 최대 순이익을 기록했다. 보험손익이 전년 동기 대비 28% 감소했지만, 투자손익이 2624억원으로 163.5% 급증하며 순이익 낙폭을 방어했기 때문이다. KB라이프의 경우 전년 상반기보다 2.3% 늘어난 1891억원의 당기순이익을 냈다.신한금융은 상반기 3조374억원 순이익을 내 전년 동기보다 10.6% 증가했다. 특히 신한라이프생명이 3443억원의 순이익을 내며 전년 동기 대비 25% 성장했다. 이는 금융지주 생보사 중 가장 큰 규모로, 신한금융 비은행 부문 가운데 36%나 기여했다.▷관련기사:\xa0신한금융, 올 상반기도 역대 최대…'리딩뱅크' 수성(7월25일)우리 '생보사 인수'·하나 '계열사 협업' 기대우리금융은 하반기 동양생명·ABL생명 인수 효과를 기대하고 있다. 두 보험사의 지난해 순이익을 합산하면 비은행 부문 비중이 약 20%대로 상승할 것으로 회사 측은 예상하고 있다.동양생명과 ABL생명은 별도기준 지난해 순이익이 각각 3102억원, 1047억원을 기록했다. 전년 동기 대비 17.1%, 14.9% 증가한 수치다.올해 1분기 두 회사의 순이익 합계는 643억원이다. 이를 단순 합산해 우리금융 비은행 부문 순이익 비중을 추산하면 1분기 8.3%(동양·ABL생명 순이익 포함 전)에서 16.1%(동양·ABL생명 순이익 포함 후)로 2배가량 뛴다.▷관련기사:\xa0KB손보·신한라이프 효자 노릇…우리금융 '보험' 덕", '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '1%대 올랐다. 클래시스, 휴젤, 펩트론은 강보합권이었다. HLB는 약보합세, 삼천당제약은 1%대 약세였다.서울 외환시장에서 원/달러 환율은 이날 오후 3시30분 기준 전일 대비 3.1원 오른 1388.3원을 나타낸다.이번주 굵직한 경제 지표 발표는 없으나 국내 주요 기업들의 실적이 대거 몰려있다. 김지원 KB증권 연구원은 "에코프로, 카카오, 네이버, LG화학, SK텔레콤 등 주요 기업들이 실적 발표가 예정돼 있다"며 "최근 급등에 따른 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승 가능성이 존재한다"고 짚었다.', '합계는 643억원이다. 이를 단순 합산해 우리금융 비은행 부문 순이익 비중을 추산하면 1분기 8.3%(동양·ABL생명 순이익 포함 전)에서 16.1%(동양·ABL생명 순이익 포함 후)로 2배가량 뛴다.▷관련기사:\xa0KB손보·신한라이프 효자 노릇…우리금융 \'보험\' 덕 볼까(5월2일)하나금융은 비은행 기여도를 오는 2027년 30%까지 확대한다는 계획으로 비은행 계열사 간 협업을 통해 시너지를 확대한다는 전략이다. 다만 올 2월 열린 2024년 연간 실적발표(IR)에서 인수합병(M&A)을 통한 외형 확대 가능성에는 선을 그었다.금융권에서는 기존 계열사 내 협업과 내실 강화만으로는 하나금융이 비은행 부문 비중을 드라마틱하게 끌어올리기는 어려울 것이란 전망이 나온다.설용진 SK증권 연구원은 "하나금융은 증권·캐피탈 등 비은행 자회사가 해외 대체투자, 기업대출 충당금 등 요인으로 다소 부진한 실적을 기록했다"며 "은행의 이익기여도가 여전히 높은 만큼 향후 비은행 부문의 유의미한 회복이 필요할 전망"이라고 짚었다.']
이 뉴스들 중에서 "두산에너빌리티"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 두산에너빌리티가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '1']
['많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', "작용했다.이어 같은 달 충북 청주시 흥덕구 일대에서 분양한 '청주테크노폴리스 하트리움 더 메트로'는 1순위 청약에서 평균 46.26대 1의 경쟁률을 기록했다. 단지 인근에 있는 청주테크노폴리스는 일반산업단지로 SK하이닉스, LG생활건강 등 대기업과 협력사가 다수 입주해 있다.트리븐 창원 투시도. 두산에너빌리티 제공올 여름 산업단지를 품은 아파트 분양에도 이목이 쏠린다.두산에너빌리티는 경남 창원특례시 진해구 자은동에서 '트리븐 창원' 전용 84·107㎡ 총 434가구를 분양 중이다. 이 단지는 다수의 산업단지를 기반으로 우수한 직주근접을 갖췄다. 주변에 진해국가산업단지, 죽곡일반산업단지, 창원국가산업단지 등이 자리해 산업단지 근로자를 중심으로 풍부한 주택 수요가 형성될 것으로 기대되고 있다. 여기에 창원 진해의 미래 먹거리사업으로 평가받는 '명동 마리나항만' 개발이 진행 중이다. 또 바로 앞에 풍호초가 자리하며 동진중, 동진여중, 진해중부고(가칭, 추진 중) 등 모든 학군이 도보권에 위치한다. 차량 약 5~10분 거리에 진해구청과 진해보건소 등 공공·행정기관과 창원지방법원 창원남부시법원, 홈플러스와 롯데마트 등이 자리해 생활 인프라 접근성도 우수하다. 창원 진해구 신도심에 10년 만에 들어서는 신축 아파트라는 점도 주목된다.한화 건설부문은 8월 중 울산광역시 남구 무거동 일원에 '한화포레나 울산무거' 전용 84~166㎡ 총 816가구를 분양할 예정이다. 울산테크노산업단지, 울산석유화학단지, 울산테크노파크 등 산업단지들이 단지 인근에 밀집해 있다. 향후 개발이 예정된 울산 트램 1·4호선과 울산부터 양산, 부산을 잇는 광역철도가 개발 진행 중으로 향후 교통 환경도 더욱 개선될 전망이다.HDC현대산업개발은 강원도 춘천시 삼천동 일원에서 '춘천 레이크시티 2차 아이파크' 전용 84~144㎡ 총 218가구를 8월 선보일 예정이다. 인근에 춘천도시첨단정보산업단지, 삼성SDS 데이터센터, 네이버도시첨단산업단지 등이 자리한다. 또 일부 세대에서 호수 등이 내려다보이는 조망권이 확보됐고 GTX-B 노선 연장사업에 따라 향후 수도권 접근성도 크게 개선될 것으로 보인다.", "■ 용감한 토크쇼 직설 '시장 따라잡기' - 손석우 앵커 경제평론가 및 건국대 겸임교수,\xa0염정 인벡스자산운용 주식운용본부 이사Q.\xa0지난주 급락세를 보였던 코스피가\xa0어제(4일)는 등락을 반복하며 반등을 시도하는\xa0모습이었는데요.\xa0오늘(5일) 흐름은 어떨지, 먼저 장 초반 분위기\xa0이사님은 어떻게 보십니까?Q.\xa0불안감은 여전하죠.\xa0일각에선 2700선까지 빠질 수도 있다.\xa0이런 전망을 하기도 하던데,\xa0과도한 우려가 아닐까 싶은데요.\xa0이사님은 어떻게 보시는지\xa0코스피 방향을 좌우할 변수는 뭐가 있을까요?Q.\xa0모처럼 재개된 외국인 매수 행진이\xa0멈추지 않을까, 하는 우려도 드는데요.\xa0그래도 환율이 지금 하향 안정화를\xa0보이고 있잖습니까?\xa0환율 하락 효과로 외국인 순매수 움직임,\xa0커질 가능성이 더 클지요?Q.\xa0종목별로 얘기를 좀 나눠보면요.\xa0지난 금요일, 가장 하락 폭이 컸던 게 배당 관련주인 증권주와 금융주였죠.\xa0어제 반등을 보였지만, 최근 흐름을 보면,\xa0역대급 실적에도 하락세를\xa0면치 못하고 있는 상황인데요.\xa0일각에선 고배당주를 매수할 적기다.\xa0이런 얘기도 하더라고요?\xa0이사님은 어떻게 보십니까?Q.\xa0지난 금요일, 코스피 대장주\xa0삼성전자는 7만 전자를 내줬고,\xa0SK하이닉스도 급락해 26만 원 선 아래로\xa0고꾸라졌는데요.\xa0어제 흐름을 보면,\xa0삼성전자가 더 크게 반등했단 말이죠?\xa0반도체주에서도 온도차가 느껴지는데, 앞으로도 이런 흐름이 이어질지요?Q.\xa0그리고 어제 장에서 눈에 띈 건,\xa0크게 상승한 두산에너빌리티였습니다.\xa0그런데 두산에너빌의 경우,\xa0급락 뒤 급등하는 모습을 반복하면서,\xa0약 한 달간 6만 원 선에서 횡보하고 있잖습니까? 앞으로의 움직임은 어떨지요?Q.\xa0기존 주도주로 분류되는,\xa0조선주와 방산주 움직임은 어떨는지요?\xa0지난 금요일,\xa0조선주 홀로 선방하는 모습이었는데 어제는 또 다른 흐름이었잖아요?Q.\xa0기존 주도주 제외하고,\xa0변동성 장세의 피난처로 내수 진작 정책 수혜가 기대되는,\xa0내수주에 주목할 필요가 있다.\xa0이런 분석도 나오던데,\xa0이사님은 어떤 종목, 괜찮게 보시는지요?Q.\xa0고용 쇼크로 휘청인 미국증시는\xa0기술주 강세로\xa0하루 만에 반등하는 모습을 보였는데요. 이 상승세가 지속될 수 있을지요?Q.\xa0장 마감 이후,\xa0팔란티어가 2분기 실적을 발표했는데요.\xa0깜짝 실적을 발표하면서, 시간 외 거래서도 주가가 4% 넘게 뛰었더라고요? 올해 가장 많이 오른 종목 중 하나가\xa0팔란티어인데, 과연 어디까지 오를지요? 월가에선 그간 주가가", '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.']
이 뉴스들 중에서 "HD현대중공업"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, HD현대중공업가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['생산성 및 기술협력 MOU를 맺은 HD현대중공업이 함께 힘을 보탤 것으로 보인다.조선업계 관계자는 "현지에 조선소를 보유한 한화오션은 미국 조선소 현대화에 주력하는 한편 HD한국조선해양은 인력 양성 등 실질적 지원에 중점을 맞춰 향후 미국 조선업 재건을 도울 것으로 보인다"고 말했다.vivid@yna.co.kr', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '1~3위 조선업 테마 ETF가 휩쓸어한화오션·HD현대중공업 급등 영향한화오션이 건조한 LNG 운반선. <한화오션>최근 한 달간 상장지수펀드(ETF) 시장에서 조선과 방산 업종 관련 상품이 수익률 상위를 휩쓸었다. 상반기에 이어 하반기도 조선·방산 업종에 대한 투자자들의 관심이 이어지고 있다.5일 한국거래소와 코스콤에 따르면 ‘TIGER 조선TOP10’는 최근 한 달간 31.93% 오르며 전체 ETF 중 수익률 1위를 차지했다.이 ETF는 한화오션, HD현대중공업, HD한국조선해양, 삼성중공업, HD현대미포, 한화엔진 등에 투자한다.2, 3위도 조선업 테마 ETF가 차지했다. ‘SOL 조선TOP3플러스’가 30.77% 오르며 2위를 기록했고, ‘KODEX 친환경조선해운액티브’가 25.92% 상승하며 3위에 올랐다.조선업 대장주인 한화오션이 최근 한 달 동안 58.82% 오르면서 ETF 성과를 견인한 것으로 풀이된다.같은 기간 HD현대중공업은 24.73%, 삼성중공업은 25.64% 올랐다. HD한국조선해양(16.12%), HD현대미포(15.06%)도 동반 상승했다. 한화엔진은 53.27% 급등했다.방산 관련 ETF도 두각을 나타냈다. ‘PLUS K방산’이 수익률 24.73%로 4위를 차지했다.이 ETF는 한화오션, 현대로템, 한화에어로스페이스, LIG넥스원, 한국항공우주, 한화시스템 등을 구성 종목으로 담고 있다.개별 종목 기준으로도 방산주 상승세가 뚜렷했기 때문으로 해석된다.올 상반기 급등했던 방산주들은 최근 한 달간 두자릿수의 견조한 수익률을 기록했다.한화에어로스페이스는 12.66% 올랐고, 현대로템은 11.30% 상승했다. LIG넥스원은 25.18%의 수익률을 거뒀다. 한국항공우주와 한화시스템은 각각 11.69%, 11.75 상승했다.같은 기간 ‘HANARO Fn조선해운’이 23.60% 오르며 5위를 기록했고, ‘SOL K방산’이 23.49 상승하며 뒤를 이었다.이밖에도 전략자원, 원자력, 전력 인프라 관련 테마들이 10위권에 포진했다.‘PLUS 글로벌희토류&전략자원생산기업’(23.03%), ‘SOL 미국원자력SMR’(22.25%), ‘KODEX 미국AI전력핵심인프라’(21.16%), ‘HANARO 전력설비투자’(20.75%)가 상위권에 이름을 올렸다.', '\'한미 조선산업 인재육성을 위한 교육 협력 업무협약(MOU)\'[연합뉴스 자료사진]HD한국조선해양의 모그룹인 HD현대는 지난해 7월 미국의 조선업 재건 지원을 위해 서울대 및 미국 미시간대와 \'한미 조선산업 인재육성을 위한 교육 협력 업무협약(MOU)\'을 맺었다.MOU에 따라 HD현대와 서울대는 미시간대와의 공동 교육, 인턴십 프로그램 도입 등 협력 방안을 마련했다. 이 방안을 확대한 것이 정부의 협상안에 담겼다는 것이 조선업계의 해석이다.또 HD현대는 지난 6월 24∼25일 성남시 판교에 위치한 HD현대 글로벌R&D센터에서 미시간대, 매사추세츠공과대학교(MIT) 등 미국 주요 대학의 조선·해양공학과 교수진 40여 명과 함께 \'한·미 조선협력 전문가 포럼\'을 열었다.여기에서도 논의된 인력 양성 방안은 올해 미국에서 열리는 2회차 행사에서 더욱 구체화될 예정이며, 논의된 내용은 한국과 미국 정부에게도 공유될 전망이다.HD현대와 미국 대학과의 MOU는 올해 초 한국을 방문한 카를로스 델 토로 미국 해군 장관의 제안에 따라 체결됐다.당시 델 토로 장관은 "국가가 필요로 하는 유능한 조선 엔지니어를 양성하려면 세계적인 수준의 교수진과의 협력은 물론 선박 설계 교육 분야의 혁신이 필요하다"고 강조했다.미국 USTR 대표 만난 정기선 수석부회장[연합뉴스 자료사진]앞서 정기선 HD현대 수석부회장은 지난 3월 조선업체 수장으로는 처음으로 미국 해군사관학교에 방문했다. 이를 고려할 때 상선에 이어 특수선 분야 인재 양성 방안도 구체적으로 논의될 것이라는 전망이 나온다.현재 미국과의 함정 사업 협력에서 가장 기대되는 분야는 이지스함이다. HD현대의 조선 계열사인 HD현대중공업은 국내 이지스함의 기본설계를 모두 주관한 국내 유일의 조선사다.정 수석부회장은 지난 5월 아시아태평양경제협력체(APEC) 통상장관 회의 참석을 위해 제주를 찾은 제이미슨 그리어 미국 무역대표부(USTR) 대표와도 만나 이러한 협력 방안을 전달한 것으로 알려졌다.이 밖에도 미국이 관심을 가진 스마트 조선소 구축을 위해서는 현지 조선소를 보유한 한화오션과 미국 최대 방산 조선사인 헌팅턴 잉걸스와 생산성 및 기술협력 MOU를 맺은 HD현대중공업이 함께 힘을 보탤 것으로 보인다.조선업계 관계자는 "현지에 조선소를 보유한 한화오션은 미국 조선소 현대화에 주력하는 한편 HD한국조선해양은 인력 양성 등 실질적 지원에 중점을 맞춰 향후 미국 조선업 재건을 도울 것으로']
이 뉴스들 중에서 "셀트리온"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 셀트리온가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['0', '1', '1', '1', '1']
['쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '1%대 올랐다. 클래시스, 휴젤, 펩트론은 강보합권이었다. HLB는 약보합세, 삼천당제약은 1%대 약세였다.서울 외환시장에서 원/달러 환율은 이날 오후 3시30분 기준 전일 대비 3.1원 오른 1388.3원을 나타낸다.이번주 굵직한 경제 지표 발표는 없으나 국내 주요 기업들의 실적이 대거 몰려있다. 김지원 KB증권 연구원은 "에코프로, 카카오, 네이버, LG화학, SK텔레콤 등 주요 기업들이 실적 발표가 예정돼 있다"며 "최근 급등에 따른 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승 가능성이 존재한다"고 짚었다.', '대한조선(439260)가 8월 5일 장 마감 5분 만에 10.19%의 검색비율을 기록해 많은 투자자들의 관심을 받고 있다. 대한조선의 현재가는 103,800원으로 전 거래일 대비 29.91% 상승하며 상한가로 마감했다. 거래량은 5,095,588주를 기록했다.이어 검색비율 2위의 삼성전자(005930)는 0.29% 상승 마감했다. 검색비율 3위의 에코프로비엠(247540)은 15.28% 급등세로 거래를 마쳤다. 검색비율 4위 현대로템(064350)은 0.50% 상승 마감했다. 검색비율 5위 삼성SDI(006400)는 10.22% 상승 마감했다.6위 한화오션(042660)은 등락률 1.57%로 소폭 상승했다. 7위 두산에너빌리티(034020)는 0.78%의 등락률로 주가가 강보합세를 보였다. 8위 카카오(035720)는 -1.26%의 하락세를 보였다. 9위 NAVER(035420)는 -0.22% 하락 마감했다. 10위 카카오페이(377300)는 등락률 0.00%로 보합세를 유지했다.이 밖에도 SK하이닉스(000660) ▲2.13%, 삼성중공업(010140) ▲5.11%, LS ELECTRIC(010120) ▲8.40%, 다날(064260) ▲3.04%, 셀트리온(068270) ▲2.24%, 에코프로(086520) ▲8.54%, SK바이오팜(326030) ▲15.92%, 포스코퓨처엠(003670) ▲8.56%, 올릭스(226950) ▲7.94%, 현대차(005380) ▼0.24% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]']

In [257]:
before_lst_bge

[Document(id='1e120cef85196b2f8eb16fd8b690182c', metadata={'ticker': '삼성전자', 'original_idx': 3, 'chunk_idx': 0, 'label': '1'}, page_content='삼성전자 모델이 5일 기존 식기세척기보다 에너지 소비효율 등급은 한 단계 높이고, 물 사용량은 10%가량 줄인 2025년형 ‘비스포크 식기세척기 카운터탑’ 신제품을 소개하고 있다.'),
 Document(id='f546454692b45880c13bb0f8001e7c35', metadata={'label': '1', 'chunk_idx': 1, 'ticker': '삼성전자', 'original_idx': 22}, page_content='하이디는 챗GPT처럼 AI 지식 검색, 영상회의 실시간 번역, 회의록 작성, 메일 요약과 초안 작성 등을 지원한다. 내부망에서 사용하기 때문에 외부로 정보가 유출되는 걸 원천적으로 차단할 수 있다. 하이디 도입으로 하루 평균 업무 생산성이 약 10% 향상됐는데, LG디스플레이는 이를 3년 내 30%까지 끌어올릴 방침이다. 외부 솔루션 대신 하이디를 자체 개발함으로써 연간 100억원에 이르는 비용 절감 효과도 거뒀다.다른 제조기업에도 AI 도입 바람이 불고 있다.조주완 LG전자 사장은 지난달 AX를 주제로 열린 임직원 소통 행사 \'AX 토크콘서트\'에 참석해 생성형 AI 데이터 시스템 \'찾다(CHATDA)\' 등을 소개했다.삼성전기는 AI를 기반으로 생산을 자동화하는 프로젝트를 진행 중이다. 이를 통해 중국 기업과 경쟁할 수 있는 생산성을 확보하겠다는 것이다.삼성전자 반도체 부문은 지난해 말 SAIT(옛 종합기술원) 산하에 있던 AI센터와 DS부문 내 혁신센터를 통합해 \'AI센터\'를 신설했다. AI를 활용해 반도체 연구개발(R&D) 역량을 높이려는 목적이다.한 국내 전자업체 CEO는 "한국보다 수십 배 많은 엔지니어를 배출하는 중국과의 경쟁에서 살아남기 위해 한국은 AI에서 답을 찾아야 한다"면서 "공장을 무인 자동화하고 AI를 활용해 R&D를 진행하는 것이 유일한 생존 방법"이라고 조언했다.[이덕주 기자]'),
 Document(id='533133fe60dab1b72de6c9aa6d591294', metadata={'label': '0', 'ticker': '삼성전자', 'chunk_idx': 2, 'original_idx': 34}, page_content='찾지 못했다고 보도했다. 내가 기업들, 정부, 과학자들, 변호사들, 중재자들, 피해자들과 나눈 대화에 따르면 이는 진실이 아니다"라고 썼다. 노 의원은 이 사례를 소개하면서 "이게 우리 언론의 진실"이라며 토론을 마무리했다.우원식 국회의장은 노 의원 토론을 듣고 나서 "언론의 오보를 하나하나 설명하는 게 국민들 관심을 많이 끌었을 것 같고 천성산 사례나 황유미씨 사건을 설명한 건 울림이 있었을 것 같다"고 말했다.'),
 Document(id='689e0b26444be2c7df1065a2897edaaf', metadata={'ticker': '삼성전자', 'chunk_idx': 1, 'original_idx': 5, 'label': '1'}, page_content='있다. 삼성전자는 최근 스마트폰·가전 사업 등을 담당하는 디바이스 경험(DX) 부문에 인공지능 기술을 활용한 제조 자동화 등 미래 전략 과제를 전담하는 조직인 ‘이노X랩’(혁신과 전환을 합친 말)을 신설했다. 회사 관계자는 “모든 업무에 인공지능을 적용하겠다는 노태문 디바이스경험부문장 직무대행(사장)의 의지에 따라 특별 태스크포스(TF)를 만들어 지원하겠다는 취지”라고 했다.에스케이(SK)그룹도 지난해 말 그룹 최고 의사협의체인 수펙스추구협의회 내에 인공지능 추진단을 확대 신설하며 계열사들의 인공지능 전환을 이끌고 있다. 에스케이는 그룹 총수인 최태원 회장이 직접 제조업 인공지능을 경제계의 최대 현안으로 띄우고 있다.권보경 포스코경영연구원 수석연구원은 “한국 제조 기업들은 중국보다 인공지능 기술 도입이 뒤처진 상태로, 자체 클라우드(인터넷 기반의 정보 저장 공간)와 보안 시스템 등 국내에 인공지능 활용 인프라를 구축할 필요가 있다”고 말했다.'),
 Document(id='8633e11bbb0a80233093d150125da32c', metadata={'label': '0', 'original_idx': 7, 'chunk_idx': 6, 'ticker': '삼성전자'}, page_content='거고 굉장히 의미 있다고 저는 생각을 합니다. 그래서 훨씬 뭐, 수사심의위원회 아시잖아요. 대검에 들어와가지고 지난번에도 이재용 삼성전자 회장이라든지.][앵커]외부 전문가가.[박범계 / 더불어민주당 의원 : 네. 외부 전문가들이 모여가지고 하는데 검찰하고 항상 엇박자가 나죠. 그런 측면에서 이것을 제도화하는 거니까 의미가 있다고 보고. 법원 개혁도 대법관 수를 늘리는 것에서 더 나아가서 시민 통제라는 관점에서 놓고 보면 미국은 배심제를 취하고 있지만 우리는 국민참여재판을 의무적으로 하는 배심제에 가까운 형태를 도입할 거냐. 대법관 구성의 다양성을 어떻게 확보할 거냐라는 시민통제. 시민의 눈높이로 보는 통제. 마찬가지로 지금 검찰이나 법원 그다음에 하나가..][앵커]언론이요?[박범계 / 더불어민주당 의원 : 언론. 언론개혁도 오늘 드디어 방송법. KBS법입니다. 다음에는 MBC, 방문진법이고 그다음 EBS 방송법 이렇게 되는데요. 오늘 결국은 핵심은 1명의 양심 있는. 양심이 없는 사람도 있는데 양심 있는 예를 들어서 보도본부장이라든지 앵커라든지 그 얘기를 어제 신동욱 의원이 많이 얘기합디다. 그러나 1명, 2명보다는 적어도 시민 참여 위원회를 통해서 다수의 집단지성을 하는 것이 훨씬 민주적이다라는 우리 믿음으로 통과를 시킨 거거든요.][앵커]알겠습니다. 시민통제, 시민참여가 키워드라고 보고 국민들이 이걸 지켜보면 되겠군요.[박범계 / 더불어민주당 의원 : 그렇습니다][앵커]알겠습니다. 지금까지 민주당 박범계 의원과 함께했습니다. 바쁘신데 나와주셔서 고맙습니다.[박범계 / 더불어민주당 의원 : 고맙습니다.]'),
 Document(id='34124ea6dffe7436785b5a34773fa06d', metadata={'ticker': '삼성전자', 'chunk_idx': 1, 'label': '1', 'original_idx': 28}, page_content='이 회사는 주식을 액면분할해 280만원대였던 주가를 5만원대로 낮췄다. 그 결과 주주가 24만명에서 500만명 이상으로 폭증했다. \'재벌 개혁\'의 단골 표적이던 삼성전자는 이제 국민이 지켜보고, 박수 치고, 걱정하는 \'국민 기업\'이 됐다. 이재용 삼성전자 회장은 웬만한 연예인보다 인기가 많다."기업이 잘돼야 나라가 잘되고, 삼성이 잘살아야 투자자도 잘산다." 지난 3월 당시 더불어민주당 대표였던 이 대통령이 이 회장에게 건넨 말이다. 이 말에 국민, 기업, 정부, 정치권이 한 방향을 바라보는 얼라인먼트의 요체가 담겨 있다.코스피가 5000선에 가까워질수록 이러한 얼라인먼트는 더 단단해질 수 있다. 선진국에선 이미 상식으로 자리 잡은 현상이다. 전 세계를 벌벌 떨게 하는 도널드 트럼프 미국 대통령도 주가가 흔들리면 움찔한다. 성인 62%가 주식을 갖고 있는 미국에선 대통령 지지율과 주가가 사실상 연동돼 있기 때문이다.아직은 상상의 영역일지 모른다. 그러나 머지않아 한국에서도 \'노란봉투법\' 같은 반기업 규제에 대해 기업이 아닌 수많은 투자자가 목소리를 높이는 날이 올 수 있다. 그쯤 되면 일부 시민단체나 귀족 노조의 반시장적 요구도 더 이상 힘을 얻기 어려워질 것이다.시장이 정치에 휘둘리던 시대는 저물고 있다. 시장이 정치를 견제하는 시대가 어서 왔으면 좋겠다. 이미 시장은 정치에 말 걸기 시작했다.[이진우 논설실장]'),
 Document(id='632c0c776d1ba215b699ff8b1acd3236', metadata={'label': '0', 'ticker': '삼성전자', 'chunk_idx': 7, 'original_idx': 2}, page_content='가지는 뭐냐 하면 집중투표제 의무화, 노란봉투법도 8월 임시국회 때 이게 통과가 될 거예요. 그런데 제가 조금 우려되는 거는 유럽 주한 유럽 상공회의소 여기에서 기업 철수할 수 있다 암참도 반대한다. 이렇게 해도 될까요? 더군다나 지금 미국하고 관세도 생겼는데 어떻게 보세요?★ 고란 : 노란봉투법 같은 경우에는 사실 증시에 미치는 영향은 별로 없고요. 이건 기업과 어떻게 보면 노동자 간의 갈등 문제 같은 거잖아요.◇ 신율 : 근데 이게 노란봉투법에서 대부분 걱정하는 게 하청 기업이 원청 기업한테 직접 쟁위를 할 수가 있다라는거죠.★ 고란 : 주식시장 관점에서만 보자면 집중투표제 의무화는 주식시장이 환영하는 거고요. 왜냐하면 이거는 소액 주주의 권리를 보호하는 그런 조치 중에 하나이기 때문에 노랑봉투법에 대해서는 별로 개의치 않습니다.◇ 신율 : 근데 막 기업이 진짜 떠나면 어떻게 해요?★ 고란 : 기업이 과연 떠날까요?◇ 신율 : 그거는 모르죠. 그건 봐야죠.★ 고란 : 아무튼 이 부분에 대해서는 시장에는 노란봉투법이나 집중 의무제나 이거 하겠다는 것에 대해서는 시장에 긍정적이다. 그러나 기업 특히 경영자에게는 부정적이겠죠. 당연히◇ 신율 : 그런데 그게 장기적으로 보면 결국 주식시장에 영향을 안 미쳐요?★ 고란 : 그렇게 장기전까지 보기는 어려운데 집중투표제 의무화나 아니면 노란봉투법 때문에 기업의 주가가 하락할까? 기업의 실적에 악영향을 미칠까라고 생각하지 않습니다.◇ 신율 : 그러면 15% 관세는요?★ 고란 : 영향 미치죠. 이건 당연히◇ 신율 : 근데 진짜 궁금한 게 어제 조갑제 대표님이 그런 말씀하시고, 지난주 금요일날 조응천 전 의원께서는 직접 트루스 소셜이라고 얘기하는 트럼프의 SNS를 직접 보셨는데, 물론 트럼프 대통령에게 100% 다 맞는다고 얘기할 수는 없지만 분명히 이랬거든요. 미국한테 한국 제품 수출하는 건 15%, 그런데 한국이 미국산 제품 수출하는 건 수입할 때는 0%. 맞아요? 그거 맞습니까?★ 고란 : 맞습니다. FTA 맺었잖아요.◇ 신율 : 우리나라는 FTA를 준수하고 미국은 FTA를 준수하지 않는다. 그러면 상호 관세가 아니라 일반 관세 아닌가요?★ 고란 : 근데 이름을 상호 관세라고 그냥 붙인 거예요.◇ 신율 : 이름을.★ 고란 : 그거 원래 보편 관세다. 그런데 트럼프가 마음대로 상호 관세라고 이름 바꾼 거라고 말씀하시는 분들이 있습니다.◇ 신율 : 근데 그렇게 되면'),
 Document(id='1ef2d422b12582f7067e783ccb9ba0f6', metadata={'ticker': '삼성전자', 'label': '0', 'original_idx': 2, 'chunk_idx': 4}, page_content='올해 상반기에 이거 주가가 많이 올라서 팔았어요. 그래 가지고 수익을 5억을 냈습니다. 그러면 9월 1일까지 나 5억 벌었어요라고 신고해야 돼요. 그리고 신고하고 여기다가 세금 내야 됩니다. 25% 3억 이상이니까.◇ 신율 : 근데 그런 사례는 듣기만 해도 기분이 좋다. 어쨌든 5억씩 받고★ 고란 : 근데 만약에 여기서 잠깐 여기서 더 좋은 게 있어요. 더 좋은 게 아까 마지막 날에 51억 있다고 했잖아요. 그런데 그 마지막 날에 제가 미리 2억을 팔았어요. 49억을 맞췄어.◇ 신율 : 그러면 돈 안 내?★ 고란 : 그러면 대주주가 아닙니다. 그럼 제가 올해 상반기에 이거 팔아가지고 5억 벌었잖아요. 그러면 이 5억에 대한 세금 한 푼도 안 내도 됩니다.◇ 신율 : 그렇게 되겠죠.★ 고란 : 그래서 이건 문제가 뭐냐. 50억 가진 사람 그리고 주식 한 종목입니다. 한 종목에 10억 가진 사람 이거 부자들 세금 내야지라는 게 일반적인 생각인데, 투자하시는 분들은 다 알아요. 왜냐하면 이 사람들이 아까 말씀드렸잖아요. 이게 내가 연간 얼마를 트레이딩해서 얼마를 벌었건 간에 얼마를 들고 있었건 간에 하등에 문제가 안 되고 연말 기준일에만 안 들고 있으면 돼요. 그러면 나는 대주주가 안 되기 위해서 저 같은 큰 손, 그런 큰 손들이 하는 행태는 뭘까요? 터는 거죠. 그 기준일 전에 파는 거죠. 그런데 기준일 전에 파는 게 일종의 눈치 싸움이라서 마지막 기준일만 안 지키면 되니까 그보다 일주일 전에 팔아요. 근데 남들이 일주일 전에 팔 것 같으니까 나는 일주일 전에 팔아야지, 더 팔아야지 하다 보니까. 코스닥 시장, 아무래도 규모가 큰 시가총액이 큰 곳에서는 이렇게 나오는 대주주 물량에 따라서 주가가 휘청거리지는 않아요. 삼성전자가 이거 갖고 휘청거리지는 않죠. 그런데 이게 작은 코스닥 종목들 시가총액이 작은 애들 1000억짜리, 500억 짜리 이런 애들은 이런 대주주들이 물량 내놓으면 휘청휘청합니다. 그러다 보니까 아까 눈치 게임이라고 일주일 먼저 팔아야지, 일주일 먼저 이렇게 하다 보니까 코스닥 시장에서 통하는 게 뭐냐 하면 코스닥은 1년에 10개월만 투자하는 거야, 10월까지만 투자하는 거야라는 얘기가 돌아요. 왜냐하면 대주주 양도세 회피 물량이 연말에 나올 거니까 그전에 내 거 먼저 팔아야지. 주가 하락하기 전에 나는 정리할 수 있는 거잖아요. 이런 일이 반복돼 왔어요. 그런데 그 기준이 그나마 50억이었는데'),
 Document(id='9d52c39d00ec4468a36625f10accbdc2', metadata={'chunk_idx': 1, 'original_idx': 34, 'label': '0', 'ticker': '삼성전자'}, page_content='사실관계를 바로잡고자 지율스님이 정정보도를 청구했고 소송 6년 만인 2018년 10월27일 조선일보는 6조원의 손실이 발생하지 않았고 공사 중단 기간도 6개월이었다고 정정보도를 했다.그런데 같은 내용의 정정보도는 두 번 더 있었다. 조선일보는 2009년 4월24일자 <환경운동의 내리막길은 천성산에서 시작됐다>란 제목의 사설과 <고속철 공사 방해 지율 스님 유죄>란 제목의 기사에서 천성산 터널공사가 중단된 기간이 1년이라고 보도했다가 사실과 달라 같은해 6월5일 정정보도문을 실었다. 당시 조선일보는 "직접적인 공사 관련 손실은 145억 원"이라고 했다. 3개월 뒤인 9월26일에도 조선일보는 1년 이상 공사가 중단돼 2조5000여억 원의 손실을 입게 됐다는 취지의 보도를 했는데 실제 손실액은 약 145억이라고 정정보도를 했다.노 의원은 "정정보도를 세 번씩 싣는 사례가 여기 있다"며 "징벌적 손해배상제가 도입됐다면 적용되고도 남았다"고 지적했다. 이어 "우리가 감시한다는 것을 강하게 보여주지 않으면 또 오보낼 것"이라며 "같은 것으로 또 (오보)하는 것 이들에게는 일도 아니다"라고 말했다.노 의원은 삼성전자 반도체공장에서 일하다 백혈병을 얻고 세상을 떠난 고 황유미씨 보상과 관련해 오보 사례도 소개했다. 당시 같은 사업장에서도 산재 사망사건이 계속 나오자 삼성이 사회적 압력을 받고 있었는데 당시 조선일보가 황유미씨 유족을 향해 "기업에 대해 마치 호구를 만난 듯 천문학적 돈을 요구한다"는 식의 보도를 한 사례를 지적했다.UN(유엔) 인권이사회가 채택한 보고서를 연합뉴스를 비롯해 수많은 매체가 인용보도했는데 그 중 \'삼성의 백혈병 문제 해결 노력을 인정했다\'는 내용이 주로 인용됐다. 하지만 바스쿤트 툰작 유엔 특별보고관은 한국 언론의 해당 보도를 오보라고 지적하면서 "삼성전자나 대한민국 정부 어느 쪽도 노동환경이 안전함을 입증하지 못했다"고 유엔 인권이사회에서 발언했다.또 2016년 9월18일 바스쿠트 툰작 보고관은 한겨레 기고를 통해 "최근 일부 언론기사가 내 보고서를 심각하게 오독해 삼성전자의 노동조건이 전직 노동자들의 질병과 장애를 일으켰다는 증거를 찾지 못했다고 보도했다. 내가 기업들, 정부, 과학자들, 변호사들, 중재자들, 피해자들과 나눈 대화에 따르면 이는 진실이 아니다"라고 썼다. 노 의원은 이 사례를 소개하면서 "이게 우리 언론의 진실"이라며 토론을 마무리했다.우원식 국회의장은 노 의원 토론을 듣고'),
 Document(id='558c3f5953e4d5da2a5de8afb69162f1', metadata={'original_idx': 13, 'chunk_idx': 0, 'label': '1', 'ticker': '삼성전자'}, page_content='▲ 평택시-삼성전자 평택캠퍼스 임원진 간담회경기 평택시는 정장선 시장이 지난 1일 윤태양 부사장(글로벌 제조&인프라 총괄) 등 삼성전자 평택캠퍼스 임원들과 간담회를 했다고 4일 밝혔습니다.이번 간담회는 삼성전자 평택캠퍼스의 지속적인 투자 등 관련 현안 공유 및 실질적인 협력 방안 모색을 위해 마련됐습니다.이 자리에서 정 시장은 "평택은 이미 삼성전자를 중심으로 반도체산업 생태계가 빠르게 구축되고 있다"며 "글로벌 반도체와 AI 산업의 전환기를 맞아 삼성전자가 세계적 핵심 기업으로 더욱 성장하도록 지자체 차원의 협력을 아끼지 않겠다"고 말했습니다.평택시는 삼성전자의 관내 투자 계획에 따른 지역경제 활성화 및 고용 창출에 대한 시민들의 기대감이 높아지고 있는 만큼 이에 맞춘 소통과 협력을 지속해서 이어갈 계획이라고 밝혔습니다.삼성전자 측은 평택캠퍼스 활성화를 위한 기존 투자 계획은 차질 없이 진행되고 있다고 밝힌 뒤 평택캠퍼스 연결도로 및 교통망 등 기반 시설 개선과 관련한 지원 방안을 시와 논의했습니다.시는 앞으로 반도체 관련 기업들과 지속적인 소통 및 협력을 통해 \'반도체 국가첨단전략산업 특화단지 평택\'으로서의 입지를 더욱 강화해 나갈 계획입니다.(사진=평택시 제공, 연합뉴스)'),
 Document(id='570a47894e770f6229e70befde27ec71', metadata={'ticker': '삼성전자', 'label': '1', 'original_idx': 1, 'chunk_idx': 0}, page_content='【 앵커멘트 】이어폰을 구입할 때 주변 소음을 완벽하게 차단하는 노이즈 캔슬링이 기능이 한때 인기였는데요.요즘엔 오히려 외부 소리를 자연스럽게 들을 수 있는 \'오픈형\' 제품이 주목받고 있습니다.달리기와 같은 야외 활동을 할 때 위험한 상황을 피하기 쉽기 때문인데요.민지숙 기자가 취재했습니다.【 기자 】러닝 크루 멤버들이 가볍게 몸을 풀고 달리기를 시작합니다.코스에 물웅덩이가 보이면, 서로 구호를 외치며 피해 갑니다."바닥 조심, 바닥"멤버들 귀에는 모두 이어폰이 끼워져 있는데, 최근 러너들 사이에 인기가 높은 \'오픈형 이어폰\'입니다.오픈형 이어폰은 귓구멍을 완전히 막지 않고, 귀에 거는 형태로 소리를 자연스럽게 흘려보내는 방식의 이어폰입니다.▶ 인터뷰 : 손대국 / 인천 송현동- "달리는 이유 자체가 자연 하고 같이 달리고 싶은데 귀가 막히면 주변 소리가 안 들리니까 주변 풍경 소리도 듣고."주변의 소리를 들을 수 있어 위급 상황에도 안전한 대처가 가능하다는 장점이 있습니다.▶ 스탠딩 : 민지숙 / 기자- "이렇게 주변 소리를 들을 수 있기 때문에, 옆으로 빠르게 지나가는 사람들도 안전하게 피할 수 있습니다."▶ 인터뷰 : 김주은 / 경기도 용인시- "안전이 제일 큰 거 같아요. 급할 때 경적 소리, 아니면 \'지나갈게요\' 하는 소리. 무슨 사고가 나거나 넘어지는 소리도 들을 수 있고요."최근 무선 이어폰 업계에선 안전성을 강화하면서, 독특한 디자인의 매력도 있는 오픈형 이어폰에 주목하고 있습니다.글로벌 이어폰 시장에서 오픈형 제품 비중은 올 1분기 9%로 사상 최고치를 기록했고.2033년엔 5조 2500억 규모로 확대될 것이란 전망이 나옵니다.시장의 40% 정도를 중국 업체가 선점하는 가운데 삼성전자도 오디오 자회사를 통해 이 시장에 뛰어들었습니다.소음을 완전히 차단하기보다 소리를 열어두는 선택, 안전까지 생각한 소비자들의 변화에 업계가 반응하고 있습니다.MBN 뉴스 민지숙입니다.영상취재: 김준모 기자, 배병민 기자영상편집: 김미현그래픽: 염하연'),
 Document(id='5e03e1cbf4bdde29a6fd45c308960159', metadata={'ticker': '삼성전자', 'original_idx': 36, 'chunk_idx': 1, 'label': '1'}, page_content="SK하이닉스(+2.13%), LG에너지솔루션(+2.93%), 삼성바이오로직스(+0.29%), 한화에어로스페이스(+2.45%), 삼성전자우(+0.35%), KB금융(+3.69%), 두산에너빌리티(+0.78%), HD현대중공업(+0.11%) 등 9종목이 상승 마감했다.■ 코스닥...외국인·기관 '쌍끌이 매수' 이틀 연속 '급등'코스닥도 코스피 처럼 외국인과 기관이 동반 매수에 나서면서 14.54포인트(1.85%) 상승한 798.60으로 마감하는 등 전날에 이어 이날도 급등장을 연출했다. 코스닥에서는 코스피와 달리 기관이 매수와 매도를 오갔는데 이날은 매수로 돌아서면서 외국인과 함께 지수를 끌어 올렸다.이날 외국인과 기관은 각각 457억원, 256억원 순매수했고, 개인이 홀로 632억원 순매도했다.상승종목은 1184종목, 하락은 426종목으로 전날과 같이 상승세가 시장을 압도했다. 보합은 114종목이었다. 시가총액 상위 10위 종목도, HLB(-0.63%), 삼천당제약(-1.13%) 두 종목을 제외한 8종목이 일제히 상승했다.알테오젠(+2.78%), 에코프로비엠(+15.28%), 에코프로(+8.54%), 펩트론(+0.34%), 파마리서치(+1.62%), 레인보우로보틱스(+3.82%), 리가켐바이오(+2.14%), 에이비엘바이오(+5.02%) 등 8종목이 상승 마감했다.■ 넥스트레이드...상승 출발ㆍ상승 유지ㆍ상승 거래중대체거래소 넥스트레이드도 한국거래소(KRX)와 같이 시작부터 상승 출발했고, 이후에도 줄곧 상승세를 키웠다.프리마켓은 기준가(전일 정규시장 종가)보다 1.23%나 상승하며 출발했고, 메인마켓에서도 상승폭을 더 확대해 1.68% 상승 마감했다. 정규시장 마감후 거래가 이뤄지는 애프터마켓은 17시 07분 현재 이날 KRX 종가 대비 0.01% 상승 거래되고 있다.이날 대체거래소에서 기준가보다 크게 오른 종목은 대한조선(+29.91%), GS피앤엘(+24.87%), 넥스틸(+16.65%) 등이며, 하락폭이 큰 종목은 셀비온(-12.07%), 지누스(-7.60%), DN오토모티브(-6.03%) 등이다."),
 Document(id='1d90e345b5337f52012487f3fbacb762', metadata={'ticker': '삼성전자', 'label': '1', 'chunk_idx': 0, 'original_idx': 4}, page_content="대표이사 직속 미래로봇추진단, AI 기반 보행·조작 기술 등 핵심 분야 인력 충원이노X 랩과 유기적 연계…사내 잡포스팅·외부 경력 채용 병행레인보우로보틱스 기술 접목해 지능형 로봇 개발 속도 낼 전망서울 서초구 삼성전자 서초사옥에 설치된 삼성전자 깃발이 바람에 펄럭이고 있다. ⓒ뉴시스[데일리안 = 정진주 기자] 삼성전자가 휴머노이드 개발을 본격화하면서 관련 인재 확보에 나섰다. 대표이사 직속 조직인 미래로봇추진단을 중심으로 전사 차원의 사내 인력 재배치와 외부 채용이 동시에 진행된다.5일 업계에 따르면 삼성전자 디바이스경험(DX) 부문은 이날부터 약 1주일간 미래로봇추진단 등 일부 조직을 대상으로 잡포스팅(사내 채용)을 진행한다.모집 부서는 미래로봇추진단 외에도 경영지원실, 경영진단팀, 생산기술연구소, 한국총괄, 디바이스 플랫폼 센터(DPC), 이사회 사무국 등이다.이 중 미래로봇추진단은 지난해 말 삼성전자가 레인보우로보틱스를 자회사로 편입하며 설립한 대표이사 직속 조직으로, 현재 휴머노이드 개발의 중심 역할을 맡고 있다. 이번 잡포스팅을 통해 추진단은 AI 기반 보행 및 전신 제어, 휴머노이드용 미들웨어, 로봇 기구 설계, 조작 기술 등 분야에서 인력을 충원할 계획이다.사내 채용과 함께 외부 경력직 채용도 진행 중이다. 주요 포지션은 로봇 파운데이션 모델(RFM) 개발, 로봇 조작 제어(Manipulation) 등으로, 고난도 기술 개발이 필요한 핵심 분야다.이번 인재 확보는 전날 본격 가동에 들어간 '이노X 랩'과도 연계된다. 이노X 랩은 피지컬 AI 기술을 기반으로 제조 자동화와 휴머노이드 핵심 기술을 개발하는 전략 조직으로, 미래로봇추진단과 유기적으로 협력할 것으로 보인다.삼성전자는 올해 초부터도 유관 부서 인력을 미래로봇추진단에 배치하는 등 로봇 조직 역량을 내외부적으로 강화해왔으며, 자체 AI·SW 기술과 레인보우로보틱스의 플랫폼 기술을 접목해 차세대 지능형 휴머노이드를 개발하겠다는 계획을 밝힌 바 있다."),
 Document(id='514c121d791800063816b786697610fe', metadata={'label': '1', 'chunk_idx': 0, 'ticker': '삼성전자', 'original_idx': 36}, page_content='코스피, 50.25포인트(1.60%) 상승 3198.00 마감코스닥, 14.54포인트(1.85%) 상승 798.60 마감◆…코스피가 5일, 전날에 이어 큰 폭으로 오르면서, 다시 3200선에 가까워졌다. [사진=연합뉴스]지난 금요일 \'폭락장\'을 겪은 후, 양도세 기준에 대한 재검토 논의가 확대되고 5일 대통령실이 세제개편안 재검토를 언급하자, 코스피는 50.25포인트(1.60%) 오른 3198.00으로 마감하는 등 \'급등세\'를 보였다.시장에서는 세제 재검토뿐만 아니라 금리 인하 움직임까지 포착되면서 금리 인하에 대한 기대감도 더해졌다는 목소리가 나온다.신한투자증권 이재원 연구원은 "대통령실의 주식 양도세 기준 재검토 및 여당에 의견 수렴 요청 보도가 나오면서 세제개편안에 대한 우려가 완화됐다"면서 "이밖에도 금리 인하 기대에 코스닥 2차전지, 바이오 등 성장주가 상대적으로 강세를 보였다"고 설명했다.시장이 다시 상승 분위기로 전환되자, 외국인과 기관도 다시 \'쌍끌이 매수\'에 나섰는데, 지난 금요일 하루를 제외하고는 10 거래일 연속 순매수세를 펼치고 있다.한편, 미국시장은 9월 금리인하에 대한 기대로 전날 다우(+1.34%), S&P500(+1.47%), 나스닥(+1.95%), 필라델피아반도체(+1.75%) 등 일제히 상승세로 전환됐고, 이날 아시아 증시도 일본 니케이(+0.64%), 홍콩 항셍(+0.57%), 중국 상해(+0.96%), 베트남 호치민(+0.27%) 등 전반적으로 강세를 보였다.■ 코스피...10일 이어지는 외국인·기관 \'쌍끌이 매수\'이날 유가증권 시장에서는 외국인과 기관이 전날에 이어 다시 \'쌍끌이 매수\'에 나섰다. 지난 8월 1일 하루를 빼고 10 거래일 동안 동반매수를 이어가면서, 이날도 각각 2919억원, 947억원 순매수했다. 개인은 10 거래일 매도행진을 이어가며 이날도 4720억원 순매도했다.상승종목은 687종목, 하락은 190종목으로 전날보다 상승세가 더 확대됐다. 보합은 58종목이었다. 시가총액 상위 10위 종목도 현대차(-0.24%) 한 종목을 제외한 나머지 9종목이 일제히 상승했다.삼성전자(+0.29%), SK하이닉스(+2.13%), LG에너지솔루션(+2.93%), 삼성바이오로직스(+0.29%), 한화에어로스페이스(+2.45%), 삼성전자우(+0.35%), KB금융(+3.69%), 두산에너빌리티(+0.78%), HD현대중공업(+0.11%) 등 9종목이 상승 마감했다.■'),
 Document(id='d2e1371019bd9bd6b0504cdcc12f55c2', metadata={'chunk_idx': 0, 'ticker': '삼성전자', 'original_idx': 22, 'label': '1'}, page_content='AI에이전트가 수율까지 높여설계시간 한달서 8일로 단축삼성전기, 자동화 생산 진행"중국과 경쟁 답 AI서 찾아야"중국 기업과 벌이는 글로벌 경쟁에서 살아남기 위해 제조업체들이 인공지능(AI)을 빠르게 도입하고 있다. AI를 활용해 제조·설계는 물론 사무 업무까지 전반적으로 생산성을 높이겠다는 전략이다.LG디스플레이는 5일 인공지능 전환(AX:AI Transformation) 온라인 세미나를 열고 올해를 AX 혁신 원년으로 삼아 개발부터 생산, 사무 영역까지 자체 개발한 AI를 적용한다고 밝혔다.AI로 생산성 향상이 두드러지는 영역은 디스플레이 수율이다. AI가 각 패널에서 발생하는 불량률이 높은 영역을 찾아내 원인을 자동 분석한다. LG디스플레이는 여기서 그치지 않고 수율 향상 작업을 AI 에이전트들끼리 직접 수행하는 고도화도 준비 중이다. 이영주 LG디스플레이 제조AI실장은 "현재는 AI가 감지하고 사람이 판단하지만 앞으로는 슈퍼 에이전트 AI를 만들어서 AI가 슈퍼 에이전트에 보고하게 할 것"이라면서 "슈퍼 에이전트가 문제가 있는 설비를 다시 스케줄링하고 공정제어도 직접 하는 것이 목표"라고 설명했다.이런 AI 개발이 가능해진 것은 유기발광다이오드(OLED) 제조공정의 전문(도메인) 지식을 AI에 학습시켰기 때문이다. AI로 인해 품질 개선에 걸리는 시간은 3주에서 2일로 크게 줄었고 양품 생산량이 늘면서 연간 2000억원 넘는 비용 효과를 얻었다.생산뿐 아니라 설계에도 AI를 도입했다. LG디스플레이는 복잡한 곡면 패널 설계를 위한 \'에지 설계 AI 알고리즘\'을 6월 자체 개발했다. 패널 설계기간이 1개월에서 8시간으로 단축됐고, 오류율도 크게 낮아졌다. 광학 설계에서도 AI가 설계안 작성부터 검증, 제안까지 수행해 설계기간을 5일에서 8시간으로 줄였다.LG디스플레이는 패널 기판 설계에 AI를 우선 적용한 뒤 재료·소자, 회로, 기구 등으로 단계적으로 확대할 계획이다.LG디스플레이 AI에는 LG AI연구원의 엑사원(EXAONE)을 활용했다. 사무직을 위한 AI 어시스턴트 \'하이디(HI-D)\'에는 엑사원이 파운데이션 모델로 적용되고 있다. 하이디는 챗GPT처럼 AI 지식 검색, 영상회의 실시간 번역, 회의록 작성, 메일 요약과 초안 작성 등을 지원한다. 내부망에서 사용하기 때문에 외부로 정보가 유출되는 걸 원천적으로 차단할 수 있다. 하이디 도입으로 하루 평균 업무 생산성이 약 10% 향상됐는데,'),
 Document(id='d4d7b079dc0564b25c19f43c1503ed1e', metadata={'ticker': '삼성전자', 'chunk_idx': 0, 'label': '1', 'original_idx': 21}, page_content='(서울=연합뉴스) 강태우 기자 = 삼성전자가 미래로봇추진단의 잡포스팅(사내 채용공고)과 경력 채용을 동시에 실시한다. 최근 이노X 랩(InnoX Lab) 신설에 이은 내부 역량 강화 차원의 채용으로, 회사가 추진 중인 휴머노이드(인간형 로봇) 사업에도 탄력이 붙을 전망이다.삼성전자 서초사옥[연합뉴스 자료사진]5일 업계에 따르면 삼성전자 디바이스경험(DX) 부문은 이날부터 약 1주간 직원들을 대상으로 잡포스팅을 시행하는 것으로 알려졌다.모집 조직은 미래로봇추진단, 경영지원실, 경영진단팀, 생산기술연구소(생기연), 한국총괄, 디바이스 플랫폼 센터(DPC), 이사회 사무국 등이다.특히 미래로봇추진단의 잡포스팅은 전날 발표된 핵심 전략 과제 전담 조직인 이노X 랩 신설, 경력 채용과 맞물려 주목된다.미래로봇추진단은 지난해 말 삼성전자가 로봇 플랫폼 전문기업 레인보우로보틱스의 최대 주주 지위를 확보하면서 신설한 조직으로, 휴머노이드를 비롯한 삼성의 미래 로봇 기술 개발에 중추적인 역할을 수행한다.이번 잡포스팅에서는 휴머노이드향 미들웨어 개발, 인공지능(AI) 기반의 보행 및 전신 제어, 로봇 조작 기술 개발, 로봇 기구 설계 등의 인력을 미래로봇추진단에 충원하기로 했다.또 경력 채용에서는 로봇 파운데이션 모델(RFM) 개발, 로봇 조작 제어(Manipulation) 담당 인력을 뽑는 중이다.삼성전자는 올해 초에도 유관 부서 인력을 추진단에 투입하는 등 조직 역량을 내외부적으로 강화하고 있는 만큼, 휴머노이드 사업은 한층 속도가 날 전망이다.앞서 삼성전자는 자사 AI, 소프트웨어 기술에 레인보우로보틱스의 로봇 기술을 접목해 지능형 첨단 휴머노이드 개발을 가속하겠다는 계획을 밝힌 바 있다.전날부터 운영을 시작한 이노X 랩과의 유기적인 협업도 기대된다.이노X 랩은 피지컬 AI 기술을 제조 자동화 추진, 휴머노이드 로봇 핵심기술 개발 등의 과제를 수행할 계획이다.한편 삼성전자는 통상 각 사업부의 인력 수요 등에 따라 수시로 잡포스팅을 하고 있다. 이는 직원 커리어 개발은 물론 회사 경쟁력을 향상할 수 있다는 장점이 있다.burning@yna.co.kr'),
 Document(id='d88386677a4bf714954c579faf06caf6', metadata={'chunk_idx': 0, 'label': '1', 'ticker': '삼성전자', 'original_idx': 9}, page_content="전작대비 판매 속도 두달 빨라갤 Z 폴드7·플립7도 흥행 지속삼성전자는 올해 2월 출시한 '갤럭시 S25 시리즈(사진)'가 지난 1일 국내 판매량 300만대를 돌파했다고 5일 밝혔다.갤럭시 S25 시리즈는 출시 이후 100만대, 200만대 판매를 전작 보다 1~2주 이상 빠르게 달성한 데 이어 300만대 판매는 전작 대비 2달 이상 단축하며 역대 S 시리즈 5G 폰 중 최단 기간 판매 기록을 썼다.갤럭시 S25 시리즈는 역대 최고 성능과 개인화된 AI 기능인 '나우 브리프'를 탑재해 출시 전부터 큰 관심을 모았다. 특히 갤럭시 S 시리즈 사상 역대 최다인 130만대의 사전 판매 실적을 기록하며 돌풍의 시작을 알렸다. 출시 후에는 '생성형 편집'과 '슬로우 모션', '오디오 지우개' 등 소비자들이 자주 사용하는 갤럭시 AI 기능이 좋다는 입소문을 타면서 갤럭시 S25 시리즈 장기 흥행에 큰 기여를 했다. 또한 새롭게 선보인 'New 갤럭시 AI 구독클럽'은 가입 1년 후 최대 50% 잔존가 보장 혜택으로 삼성닷컴 구매 고객 10명 중 3명이 가입하는 등 신제품 흥행을 뒷받침했다.한편 하반기 플래그십 모델인 '갤럭시 Z 폴드7'과 '갤럭시 Z 플립7'도 지난달 25일 출시 이후 전작 대비 크게 웃도는 판매 실적을 기록하며 흥행을 이어가고 있다. 특히 슬림한 하드웨어와 폴더블 폼팩터에 특화된 ONE UI 8, 직관적인 AI 기능을 앞세워 갤럭시 폴더블 시리즈 사상 역대 최대 사전 판매 기록인 104만대를 달성했다.삼성전자는 혁신적인 하드웨어와 AI 기술을 기반으로 상반기부터 하반기까지 이어지는 플래그십 스마트폰의 흥행 돌풍을 통해 국내 스마트폰 시장에서의 입지를 더욱 공고히 하고 있다고 강조했다. 구자윤 기자"),
 Document(id='4028ba338d2cecb8f4f8849b584e8972', metadata={'chunk_idx': 0, 'original_idx': 0, 'label': '1', 'ticker': '삼성전자'}, page_content='이재명 정부 정책 수혜주로 분류되던 고배당주 상장지수펀드(ETF)에서 자금이 빠져나가고 있다. 세제개편안에 담긴 배당소득 분리과세 관련 내용이 시장 기대감을 꺾은 것으로 풀이된다.5일 한국경제신문에 따르면 세제개편안이 발표된 후인 이달 1~4일 개인투자자는 국내 상장 배당 ETF 28개를 총 72억원어치 순매도했다. 올 들어 자금이 꾸준히 유입됐지만 처음으로 순유출로 전환했다.배당주 ETF 가운데 가장 규모가 큰 \'PLUS 고배당주\'는 고점 대비 9.1% 하락했다. TIGER 은행고배당플러스TOP10(-9.0%), KODEX 고배당주(-8.4%) 등 주요 배당 ETF의 낙폭도 컸다.배당주 ETF는 대표적인 정책 수혜 펀드로 분류됐다. 배당소득 분리과세가 이뤄질 것이라는 기대감에서다. 배당소득 분리과세는 투자자가 받은 배당소득을 종합과세 대상에서 제외해 분리과세하는 게 핵심이다.시장에서는 분리과세가 도입되면 기업 배당이 늘고, 투자자 세금 부담도 줄어들 것으로 기대했지만 분위기가 달라졌다.정부가 발표한 세제개편안에 따르면 배당소득 분리과세 적용 대상은 전년 대비 현금 배당이 감소하지 않은 상장법인 중 배당 성향이 40% 이상이거나, 배당 성향이 25% 이상이면서 직전 3년 대비 5% 이상 배당이 증가한 기업으로 특정됐다. 삼성전자, SK하이닉스 등 주요 종목 투자자도 혜택을 보기 어려운 조건이다.한시화 한화투자증권 연구원은 "지난 6월 대선 이후 자금이 대거 유입된 대표적인 ETF가 고배당주와 금융주"라며 "기존 개편안보다 까다로운 분리과세 방안이 발표되면서 투자심리가 악화했다"고 분석했다.(사진=연합뉴스)'),
 Document(id='474cba83acf73bc9a825cd10b085f53a', metadata={'ticker': '삼성전자', 'label': '0', 'original_idx': 7, 'chunk_idx': 3}, page_content='물으려고 하겠지만 적어도 워낙 혐의가 많아요. 그중에서 지금 하나 터진 게 있지 않습니까? JTBC 단독 보도였던 제가 아주 흥미롭게 봤는데요. 권성동 의원과 관련된 큰 거 1장을 대통령 선거 기간, 윤석열 후보를 위해서 큰 거 1장을 서포트했다. 대통령 선거에서 큰 거 1장 어느 정도일까요?][앵커]일단 1억 수수로 저희가 취재가 되고 있죠.[박범계 / 더불어민주당 의원 : 그렇게 보도를 하셨죠? 그래서 저는 과연 그걸 가지고 큰 거 1장이라고 할 수 있을 것인가. 이 다이어리, 소위 통일교의 2인자라고 할 수 있는 윤영호 전 세계본부장의 다이어리, 비망록이 있다는 건데 그것은 제가 이런 생각이 듭니다. 과거 안종범 수석이라고 생각나십니까?][앵커]안종범 수첩.[박범계 / 더불어민주당 의원 : 수첩. 박근혜 소위 유죄의 결정적인 증거물이 됐던. 그래서 이것을 보면서 이것이 통일교에 연결되고 건진법사 연결되고 그라프 소위 6000만 원짜리 목걸이와 연결되고 그 이전에 나토 첫 번째 해외순방 때 김건희가 차고 갔던. 외우기도 어려워요. 반클리프 아펠이라는 어마어마한 고가의 이 두개의 목걸이와 관련된 드디어 윤핵관의 핵심 중에 핵심인 권성동 의원이 등장했다. 저는 이 부분이 양평고속도로 건과 함께 가장 주목해야 될 김건희 특검에서 가장 주목할 대목이다 이런 생각이 들어요.][앵커]언급하신 김에 그 부분 조금 더 여쭤보면 그래픽 같이 띄워주시죠. 2022년 1월 5일이라고 날짜까지 정확하게 나오고 있고요. 그리고 여의도의 모 중식당. 여기는 괄호로 저희가 표현해 놨지만 이름도 정확히 나와 있고요. 그리고 큰 거 1장이라고. 서포트, 지원이라는 뜻으로 해석할 수 있겠죠. 이 정도라면 날짜와 장소까지 정확하게 나와 있고 또 다른 보도에 따르면 1억 돈다발 사진도 확보가 됐다고 한다면 특검은 지금 굉장히 이 사안에 대해서는 자신 있을 것 같습니다.[박범계 / 더불어민주당 의원 : 이미 윤 모 통일교 전 세계본부장에 영장이 발부됐잖아요. 구속영장이 발부됐다는 것은 범죄 사실에 대한 소명이 이루어졌다. 그리고 도주 및 증거인멸의 우려가 있다. 그런 측면에서 지금 JTBC가 유능한 매체입니다만 어찌 됐든 물적 증거가 확보가 된 거잖아요. 그런 측면에서 이 수사는 상당한 정도로 쾌도난마의 수사를 보여줄 거고 여기서 머무르지는 않을 것이다 하는 생각이 듭니다.][앵커]그리고 또 김건희 씨가 사용했던 비화폰 관련해서도 보도가 많이 나오고 있습니다. 그중에 접근 등급이라는 게 나눠져 있는데 A등급, A그룹인 비화폰을 썼다, 김건희 씨가. 이건 대통령 부속실장이나 경호처장 수준이다라고 하는데 그렇다면 글쎄요. 국정농단이라고까지 표현을 할 만한 수준으로 혐의가 더 많을 수 있다라고 보십니까?[박범계 / 더불어민주당 의원 : 부속실장. 경호처장. 뭐 오죽했으면 홍준표 전 시장이 그런 표현을 썼겠습니까? 박근혜 국정농단을 능가하는. 저는 비서실장, 경호처장 수준이 아니고 이 장면. 최근에 제가 봤던 유튜브 동영상인데 언젠가 해외순방을 해서 두 내외가 귀국할 때 윤석열 전 대통령이 먼저 자기 환영을 나온 참모들하고 쭉 악수를 하고 자기가 돌아서서 그 옆에 서고 거기에 김건희 씨가 쭉 역시 같은 마찬가지로 악수를 하면서 들어오면서 윤석열 전 대통령과 악수하는 장면 기억나십니까?][앵커]저도 본 것 같습니다.[박범계 / 더불어민주당 의원 : 그 장면이 그냥 저게 해프닝이 아니고 그냥 개그를 하려고 하는 것이 아니고 이것이야말로 등급의 차이를 보여주는 것 아닌가. 윤석열과 김건희의 계급의 차이를 보여주는 것 아닌가. 아니면 실세의 차이. 세력의 있고 없고의 차이 아닌가. 누가 정말 국정운영을'),

In [258]:
rerank_df_before_bge = pd.DataFrame(list(map(lambda x: x.metadata,before_lst_bge)))

In [38]:
rerank_df_before_bge

NameError: name 'rerank_df_before_bge' is not defined

In [261]:
total_df = pd.DataFrame(total_results['metadatas'])

In [ ]:
rerank_eval_bge = []

In [37]:
for kind in target_lst[:10]:
    total_df_target = total_df_bge[total_df_bge.ticker==kind]
    rerank_df_target_bge = rerank_df_before_bge[rerank_df_before_bge.ticker==kind]
    rerank_eval_bge.append(eval_reranker_chunk(total_df_target,rerank_df_target_bge))

NameError: name 'rerank_df_before_bge' is not defined

In [264]:
rerank_eval_con_bge = dict(zip(target_lst[:10],rerank_eval_bge))

In [265]:
pd.DataFrame(rerank_eval_con_bge)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.633333,1.000000,1.000000,1.00,1.000000,0.900000,1.000000,0.966667,1.00,0.900000
Recall@30(pool),0.558824,0.714286,0.638298,0.75,0.909091,0.964286,0.638298,0.659091,0.75,0.750000
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.500000
MAP@30,0.435597,1.000000,1.000000,1.00,1.000000,0.960500,1.000000,0.956528,1.00,0.750363
nDCG@30,0.884663,1.000000,1.000000,1.00,1.000000,0.999238,1.000000,0.997855,1.00,0.890603
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,30.000000,30.000000,30.000000,30.00,30.000000,30.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,19.000000,30.000000,30.000000,30.00,30.000000,27.000000,30.000000,29.000000,30.00,27.000000

## 전체 종목에 대한 검색

In [266]:
before_lst_bge_total = []

In [267]:
for ticker in target_lst[:10]:
    retriever = vectordb_bge.as_retriever(search_kwargs={"k": 30})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    before_lst_bge_total.extend(raw_docs)
    print(list(map(lambda x: x.metadata['label'],raw_docs))[:5])
    print(list(map(lambda x: x.page_content,raw_docs))[:5])

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '필요가 있다”고 설명했다.이어 “이번 정치권 내 논의 과정에서 대주주 양도세 뿐만 아니라 배당소득 분리과세가 시장 친화적으로 변경될지 여부도 추후 증시 반전의 재료가 될 전망”이라고 내다봤다.이날 코스피 시장에선 대형주가 1.59%, 중형주가 1.53%, 소형주가 0.87% 모두 올랐다.업종별로는 대부분이 강보합이었다. 보험 업종이 2.71% 전기·가스 업종이 2.14%, 금융 업종이 2.37% 등 상승했다. 다만 섬유·의류는 0.59%, IT서비스는 0.02% 떨어졌다.시가총액 상위 종목도 대부분 올랐다. 삼성전자(005930)는 전 거래일보다 200원(0.29%) 오른 6만 9900원에 거래됐고, 같은 기간 SK하이닉스(000660)는 5500원(2.13%) 오른 26만 3500원을 가리켰다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.93%, 2.45% 상승했다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.36% 하락했다.한편 코스닥 지수는 전 거래일 대비 7.88포인트(1.01%) 오른 791.94에서 출발해 14.54포인트(1.85%) 오른 798.60에 거래를 마쳤다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 752억원 순매도했으며 외국인과 기관 투자자가 각각 648억원, 176억원치를 순매수하며 매수 우위를 보였다. 프로그램별로는 차익과 비차익을 합쳐 375억원 매수 우위를 나타냈다.', '필요가 있다”고 설명했다.이어 “이번 정치권 내 논의 과정에서 대주주 양도세 뿐만 아니라 배당소득 분리과세가 시장 친화적으로 변경될지 여부도 추후 증시 반전의 재료가 될 전망”이라고 내다봤다.이날 코스피 시장에선 대형주가 1.59%, 중형주가 1.53%, 소형주가 0.87% 모두 올랐다.업종별로는 대부분이 강보합이었다. 보험 업종이 2.71% 전기·가스 업종이 2.14%, 금융 업종이 2.37% 등 상승했다. 다만 섬유·의류는 0.59%, IT서비스는 0.02% 떨어졌다.시가총액 상위 종목도 대부분 올랐다. 삼성전자(005930)는 전 거래일보다 200원(0.29%) 오른 6만 9900원에 거래됐고, 같은 기간 SK하이닉스(000660)는 5500원(2.13%) 오른 26만 3500원을 가리켰다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.93%, 2.45% 상승했다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.36% 하락했다.한편 코스닥 지수는 전 거래일 대비 7.88포인트(1.01%) 오른 791.94에서 출발해 14.54포인트(1.85%) 오른 798.60에 거래를 마쳤다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 752억원 순매도했으며 외국인과 기관 투자자가 각각 648억원, 176억원치를 순매수하며 매수 우위를 보였다. 프로그램별로는 차익과 비차익을 합쳐 375억원 매수 우위를 나타냈다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.']
이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '0', '1']
['SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', 'SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97p(2.04%) 오른 800.03이다.지수는 전장보다 7.88p(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '삼성전자의 주가 상승과 더불어 SK하이닉스의 HBM 산업 경쟁 심화 우려로 인한 주가 조정이 함께 이뤄졌다"고 진단했다.그러면서 "내년 HBM 공급 초과분은 6%로 크지 않을 것으로 예상된다"며 "중국향 AI 칩, 소버린 AI, 네오 클라우드 등이 수요의 상방 요인으로 작용할 것"이라고 전망했다．']
이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.
['1', '0', '1', '1', '1']
['사진=게티이미지뱅크미국 내 전기차 보조금 폐지를 앞둔 가운데 기관 투자사들은 오히려 2차전지 종목을 적극 사들인 것으로 나타났다. 증권가에선 순환매 장세에 따라 저평가된 2차전지 업종에 투자금이 몰렸다고 분석한다.5일 한국거래소에 따르면 지난달 이후 이날까지 국내 증시에서 기관 투자사들이 가장 많이 사들인 종목은 LG에너지솔루션(5927억원)으로 집계됐다. 삼성SDI(1377억원)와 엘앤에프(530억원) 등도 순매수 상위권에 이름을 올렸다.기관의 매수세에 힘입어 2차전지 업종도 모처럼 반등에 성공했다. 주요 2차전지 종목을 모은 \'KRX 2차전지 TOP10 지수\'와 \'KRX 전기차 TOP15 지수\'는 각각 13.85%, 12.72% 급등했다. 전체 34개 KRX 테마지수 중 수익률 상위 1, 2위를 기록했다.증권가에선 2차전지 섹터를 단기 투자처로 보고 있다. 국내 2차전지 기업들의 에너지저장장치(ESS) 수주 기대와 리튬 가격 상승을 호재로 꼽으면서다. 주민우 NH투자증권 연구원은 "오는 9월까지는 2차전지 관련주의 주가가 오를 것"이라면서 LG에너지솔루션은 최우선주로 제시했다. 향후 미국에서 ESS 수주가 늘어남에 따라 LG에너지솔루션이 수혜를 입을 것이란 분석에서다.지난해부터 2차전지주 주가가 크게 떨어진 만큼 추가 하락 폭이 크지 않을 것이란 관측도 고개를 들고 있다. 자산운용업계 관계자는 "반도체 섹터에서 차익 실현하는 대신 그간 주가가 많이 내린 2차전지 종목으로 투자금을 옮기는 추세"라고 설명했다.일각에선 올해도 2차전지 업황이 개선되긴 쉽지 않을 것으로 전망한다. 미국 정부가 지급하는 전기차 구입 보조금이 오는 9월 30일 종료되면 판매가 더 줄어들 수 있다는 분석 때문이다. 유럽 전기차 시장은 성장이 기대되지만 최근 중국 기업이 물량 공세를 펼치고 있기 때문에 국내 2차전지업체들이 시장에 침투하기 쉽지 않을 것이란 분석도 나온다.조현렬 삼성증권 연구원은 "미국 내 보조금이 사라지면 전기차 수요 관련 불확실성이 커질 것"이라며 "전기차 배터리 생산 비중이 높은 업체들의 수익 감소는 불가피하다"고 말했다.', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.']
이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '1']
['세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '코스피 주요 종목들이 전반적으로 보합세를 나타내고 있다.5일 오후 12시 20분 한국거래소에 따르면, 시가총액 1위인 삼성전자(005930)는 현재가 69,800원으로 전 거래일 대비 0.14% 상승하고 있다. 상장주식수 5,919만6,638주와 외국인비율 50.61%를 기록하며, 거래량은 9,241,052주다. PER은 13.52, ROE는 9.03으로 안정적인 재무 상태를 유지하고 있다. SK하이닉스(000660)는 현재가 260,500원으로 0.97% 상승했다. 외국인비율은 55.06%이며, 거래량은 1,171,742주다. PER 7.30, ROE 31.06을 기록하며 재무적으로 양호한 상태를 보인다.LG에너지솔루션(373220)은 2.66% 상승하며 거래량 298,504주를 기록하고 있다. 삼성바이오로직스(207940)는 0.67% 상승했으며 거래량은 21,586주다. 한화에어로스페이스(012450)는 1.71% 상승하고 있으며 거래량은 127,667주를 기록 중이다. 삼성전자우(005935)는 전 거래일 대비 0.35% 상승하며 거래량은 840,247주다. 두산에너빌리티(034020)는 0.78% 상승하며 거래량은 2,973,106주를 기록 중이다. HD현대중공업(329180)은 0.54% 상승하며 거래량 126,827주를 보이고 있다.한편, 시가총액 20위권 종목들은 셀트리온(068270) ▲1.96%, 기아(000270) ▼0.97%, NAVER(035420) ▼1.08%, 한화오션(042660) ▲0.92%, 신한지주(055550) ▲2.43%, 삼성물산(028260) ▲0.74%, 현대모비스(012330) ▼0.70%, HD한국조선해양(009540) ▲3.85%, 삼성생명(032830) ▲2.33%, 한국전력(015760) ▲2.28% 등의 성적을 기록하고 있다.현재 시장은 보합세를 보이고 있으며, 외국인 투자자들의 동향에 따라 거래량이 좌우되고 있다. 거래량이 많은 종목들이 비교적 긍정적인 등락률을 보이는 가운데, 해외 투자자들의 비율이 높은 종목들의 경우 안정적인 재무 지표를 유지하고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]']
이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '0', '1']
['거래되고 있고, 같은 기간 SK하이닉스(000660)는 4000원(1.55%) 오른 26만 2000원을 가리키고 있다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.66%, 2.13% 오르고 있다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.17% 하락세다.한편 코스닥 지수는 전 거래일 대비 13.36포인트(1.70%) 오른 797.42에 거래되고 있다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 464억원 순매도하고 있으며 외국인과 기관 투자자가 각각 388억원, 176억원치를 순매수하며 매수 우위를 이어나가고 있다. 프로그램별로는 차익과 비차익을 합쳐 187억원 매수 우위를 나타내고 있다.', '거래되고 있고, 같은 기간 SK하이닉스(000660)는 4000원(1.55%) 오른 26만 2000원을 가리키고 있다. LG에너지솔루션(373220)과 한화에어로스페이스(012450) 역시 각각 2.66%, 2.13% 오르고 있다. 다만 현대차(005380)와 기아(000270)는 각각 0.24%, 1.17% 하락세다.한편 코스닥 지수는 전 거래일 대비 13.36포인트(1.70%) 오른 797.42에 거래되고 있다. 코스닥도 장중 최고 801.63을 기록하며 800선을 돌파하기도 했다.코스닥 시장에선 개인 투자자가 464억원 순매도하고 있으며 외국인과 기관 투자자가 각각 388억원, 176억원치를 순매수하며 매수 우위를 이어나가고 있다. 프로그램별로는 차익과 비차익을 합쳐 187억원 매수 우위를 나타내고 있다.', '생산성 및 기술협력 MOU를 맺은 HD현대중공업이 함께 힘을 보탤 것으로 보인다.조선업계 관계자는 "현지에 조선소를 보유한 한화오션은 미국 조선소 현대화에 주력하는 한편 HD한국조선해양은 인력 양성 등 실질적 지원에 중점을 맞춰 향후 미국 조선업 재건을 도울 것으로 보인다"고 말했다.vivid@yna.co.kr', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '대한조선(439260)가 8월 5일 장 마감 5분 만에 10.19%의 검색비율을 기록해 많은 투자자들의 관심을 받고 있다. 대한조선의 현재가는 103,800원으로 전 거래일 대비 29.91% 상승하며 상한가로 마감했다. 거래량은 5,095,588주를 기록했다.이어 검색비율 2위의 삼성전자(005930)는 0.29% 상승 마감했다. 검색비율 3위의 에코프로비엠(247540)은 15.28% 급등세로 거래를 마쳤다. 검색비율 4위 현대로템(064350)은 0.50% 상승 마감했다. 검색비율 5위 삼성SDI(006400)는 10.22% 상승 마감했다.6위 한화오션(042660)은 등락률 1.57%로 소폭 상승했다. 7위 두산에너빌리티(034020)는 0.78%의 등락률로 주가가 강보합세를 보였다. 8위 카카오(035720)는 -1.26%의 하락세를 보였다. 9위 NAVER(035420)는 -0.22% 하락 마감했다. 10위 카카오페이(377300)는 등락률 0.00%로 보합세를 유지했다.이 밖에도 SK하이닉스(000660) ▲2.13%, 삼성중공업(010140) ▲5.11%, LS ELECTRIC(010120) ▲8.40%, 다날(064260) ▲3.04%, 셀트리온(068270) ▲2.24%, 에코프로(086520) ▲8.54%, SK바이오팜(326030) ▲15.92%, 포스코퓨처엠(003670) ▲8.56%, 올릭스(226950) ▲7.94%, 현대차(005380) ▼0.24% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]']
이 뉴스들 중에서 "현대차"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대차가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '0', '1', '1']
['부품 조달과 관련, 현대차 이승조 재경본부장(부사장)은 지난달 25일 2분기 실적발표 컨퍼런스콜에서 “현재 200여 개 부품에 대해 다양한 업체들로부터 견적을 받고 논의 중이며, 지속적으로 현지에서 부품 소싱 여부와 방법, 규모 등을 신중히 검토할 예정”이라고 밝혔다.이와 관련해 현대차그룹의 부울경 부품 협력업체들도 발등에 불이 떨어졌다.A사의 경우 미국 공장 설비를 배로 늘리기로 했고, 현지 공장이 없는 B사는 공장 신설을 검토중이다. 최근 현지 공장을 지은 C사는 현지 부품 공급에 어려움이 없다는 입장이다. 지역 최대 납품업체 가운데 하나인 D사 관계자는 “현대차그룹의 움직임에 따라 결정해야 할 문제이며 시장 상황을 파악 중”이라고 밝혔다.현대차그룹은 생산·부품 조달 확대와 함께 혼류생산과 로봇 확대 등을 통한 생산 효율을 높이고, 재료비·가공비 절감 노력도 함께 추진하기로 했다.', "기록했다. 연간 판매량 기준 5만대를 넘지 못할 것이라는 전망이 우세하다. 반면 하이브리드차와 전기차 판매량은 각각 20만3000여 대, 7만2000여 대로 디젤차 판매량의 10배, 3배를 기록하고 있다.디젤 차량은 중고차 시장에서도 외면받고 있다. 중고차 플랫폼 케이카가 올해 상반기 판매 데이터를 분석한 결과, 디젤차 비중은 14.9%로 지난해 같은 기간(18.4%) 대비 3.5%포인트 줄었다. 국내 수입차 시장에서도 디젤차 입지가 점점 좁아지고 있다. 올해 상반기 수입 디젤차 판매량은 1737대로 전체 판매량의 1.26%에 불과하다. 2015년 전체 수입차의 70%가량을 차지했던 디젤차는 '디젤게이트' 사건 이후로 판매량이 내리막길을 걸었다.한국수입자동차협회(KAIDA)가 집계하는 수입차 업체 26곳 중 지난 6월까지 디젤차를 판매한 업체는 아우디, BMW, 포드, 메르세데스-벤츠, 폭스바겐 등 5곳에 불과하다.[박제완 기자]", '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.']
이 뉴스들 중에서 "KB금융"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, KB금융가 단순히 함께 언급된 기사라면 제외해줘.
['1', '1', '1', '1', '1']
['세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', "24일 서울 영등포구 여의도 63빌딩에서 바라본 여의도 증권가. 2024.1.24/뉴스1 ⓒ News1 김진환 기자(서울=뉴스1) 박승희 기자 = 세제 개편 우려로 급락했던 금융주 전반이 반등 중이다.5일 오전 11시 35분 KB금융지주(105560)는 전일 대비 3300원(3.04%) 오른 11만 1700원에 거래되고 있다. 지난 1일 4.42% 하락한 뒤 전날에 이어 2거래일 연속으로 상승 중이다.이외 신한금융지주회사(055550)(2.88%), 아이엠금융지주(139130)(2.37%), 우리금융지주(316140)(2.06%), 하나금융지주(086790)(1.64%) 등도 강세다.삼성화재해상보험(000810)(3.17%), 한화손해보험(000370)(3.45%), 신영증권(001720)(4.90%), NH투자증권(005940)(3.35%) 등 은행, 보험, 증권주 전반이 오르고 있다.앞서 금융주는 정부의 세제개편안 발표와 함께 하락한 바 있다. 정부가 낸 세제개편안에 따르면 주식 양도소득세 과세 대상인 대주주 기준을 50억 원에서 10억 원으로 낮추고, 증권 거래세를 상향하기로 했다.배당소득 분리과세도 기존에 기대했던 최고 세율 25%에서 35%로 상향되고 고배당 기업 조건도 시장 기대보다 엄격하게 제시됐다.이에 증시 부양 기대감으로 올랐던 금융주가 급락했지만, 투자자 반발에 정치권에서 재검토 논의가 힘을 얻으며 투심이 반등한 것으로 보인다.여기에 미국 연방준비제도(Fed·연준)의 금리 인하 기대도 긍정적인 영향을 미쳤다.미국 노동시장 약화와 '매파 성향'(통화긴축 선호)인 아드리아나 쿠글러 연준 이사의 퇴임으로 9월 연준의 금리 인하 가능성이 힘을 얻고 있다.", "은행 의존도가 82%로 높은 편이다. 올 상반기 하나은행은 순이익이 전년 동기 대비 19.1%나 증가한 2조851억원을 기록해 호실적을 거뒀다. 그러나 증권과 카드, 캐피탈, 자산신탁은 순이익이 모두 하락했다.▷관련기사:\xa0하나금융 상반기 순익 2.3조…비이자익 10% 껑충(7월25일)하나금융\xa0보험 계열사인 하나생명의 경우 순이익이 전년 동기 대비 54.1% 증가했지만, 순이익 규모가 142억원으로 하나캐피탈(149억원)보다 작다.KB·신한, 은행 끌고 비은행 밀었다상반기 사상 최대 실적을 기록한 KB금융과 신한금융의 경우 은행 호실적에 더해 비은행 부문, 특히 보험 계열사의 약진이 눈에 띄었다.KB금융은 올해 상반기 순이익 3조4357억원을 달성했다. 이는 지난해 상반기보다 23.8% 증가한 규모다.▷관련기사:\xa0KB금융, 상반기 역대급 성적표에 주주환원도 '역대급'(7월24일)KB손해보험은 순이익이 전년 동기 대비 2.3% 줄어든 5581억원을 기록했으나, KB금융 비은행 계열사 중 최대 순이익을 기록했다. 보험손익이 전년 동기 대비 28% 감소했지만, 투자손익이 2624억원으로 163.5% 급증하며 순이익 낙폭을 방어했기 때문이다. KB라이프의 경우 전년 상반기보다 2.3% 늘어난 1891억원의 당기순이익을 냈다.신한금융은 상반기 3조374억원 순이익을 내 전년 동기보다 10.6% 증가했다. 특히 신한라이프생명이 3443억원의 순이익을 내며 전년 동기 대비 25% 성장했다. 이는 금융지주 생보사 중 가장 큰 규모로, 신한금융 비은행 부문 가운데 36%나 기여했다.▷관련기사:\xa0신한금융, 올 상반기도 역대 최대…'리딩뱅크' 수성(7월25일)우리 '생보사 인수'·하나 '계열사 협업' 기대우리금융은 하반기 동양생명·ABL생명 인수 효과를 기대하고 있다. 두 보험사의 지난해 순이익을 합산하면 비은행 부문 비중이 약 20%대로 상승할 것으로 회사 측은 예상하고 있다.동양생명과 ABL생명은 별도기준 지난해 순이익이 각각 3102억원, 1047억원을 기록했다. 전년 동기 대비 17.1%, 14.9% 증가한 수치다.올해 1분기 두 회사의 순이익 합계는 643억원이다. 이를 단순 합산해 우리금융 비은행 부문 순이익 비중을 추산하면 1분기 8.3%(동양·ABL생명 순이익 포함 전)에서 16.1%(동양·ABL생명 순이익 포함 후)로 2배가량 뛴다.▷관련기사:\xa0KB손보·신한라이프 효자 노릇…우리금융 '보험' 덕", '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.']
이 뉴스들 중에서 "두산에너빌리티"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 두산에너빌리티가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '1', '1', '0']
['많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는']
이 뉴스들 중에서 "HD현대중공업"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, HD현대중공업가 단순히 함께 언급된 기사라면 제외해줘.
['1', '0', '1', '1', '1']
['생산성 및 기술협력 MOU를 맺은 HD현대중공업이 함께 힘을 보탤 것으로 보인다.조선업계 관계자는 "현지에 조선소를 보유한 한화오션은 미국 조선소 현대화에 주력하는 한편 HD한국조선해양은 인력 양성 등 실질적 지원에 중점을 맞춰 향후 미국 조선업 재건을 도울 것으로 보인다"고 말했다.vivid@yna.co.kr', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.', '건설(1.87%) 운송장비·부품(1.67%) 금속(1.54%) 등의 순으로 상승했다. 통신(-0.40%) 운송·창고(-0.35%)는 하락 마감했다.시총 상위 종목 가운데서는HLB(-0.63%)과 삼천당제약(-1.13%)이 내리는 가운데 에코프로비엠(15.28%) 에코프로(8.54%) 등 이차전지주가 급등세를 보였고 알테오젠(2.78%) 펩트론(0.34%) 파마리서치(1.62% ) 레인보우로보틱스(3.82%) 리가켐바이오(2.14%) 에이비엘바이오(5.02%) 등도 상승 마감했다.이번 주는 국내 주요 기업들의 실적 발표가 몰려있어 시장이 실적에 연동해 움직일 것으로 예상된다. 카카오, 네이버(NAVER), LG화학, SK텔레콤 등의 실적 발표가 대기 중이다.김지원 KB증권 연구원은 "최근 급등세로 고점 부담이 존재하는 만큼 실적 모멘텀이 확인돼야 현 지수대에서 추가 상승할 수 있을 것으로 보인다"고 분석했다.']
이 뉴스들 중에서 "셀트리온"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 셀트리온가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

['1', '1', '0', '1', '1']
['오늘(8월 5일) 오전 9시에 개장한 국내 증시에서 삼성전자(005930)가 개장 5분 만에 10.58%의 검색비율을 기록하며 많은 투자자들의 관심을 받고 있다. 삼성전자의 현재가는 71,300원으로 전 거래일 대비 2.30% 상승하며 상승세를 보이고 있다. 거래량은 1,326,241주를 기록했다.이어 두산에너빌리티(034020)가 검색비율 2위를 기록하며 0.78%의 등락률을 기록하고 있다. 검색비율 3위의 한화오션(042660)은 1.66% 상승하며 순조롭게 출발하는 모습이다. 검색비율 4위 SK하이닉스(000660)는 개장 초반부터 2.13%의 상승률로 상승 중이다. 검색비율 5위 NAVER(035420)은 0.00% 등락률로 큰 움직임을 보이지 않고 있다.6위 카카오(035720)는 등락률 -1.44%로 하락세를 보이고 있다. 7위 대한조선(439260)은 3.50%의 등락률로 주가가 소폭 상승 중이다. 8위 현대로템(064350)은 0.75%의 등락률로 상승세를 보이고 있다. 9위 알테오젠(196170)은 3.59% 상승하며 시동을 거는 모습이다. 10위 HJ중공업(097230)은 하락률 -1.08%로 주가가 다소 하락하고 있다.이 밖에도 삼성전자우 ▲4.32%, 한국전력 ▼0.05%, 에이비온 ▲2.43%, 흥구석유 ▲1.39%, 국보 ▼0.02%, 가온전선 ▼0.31%, AP헬스케어 ▼0.3%, 티에스이 ▼0.12%, 이마트 ▼0.23%, 미래산업 ▲4.44% 등이 많이 검색되고 있다.[서울신문과 MetaVX의 생성형 AI가 함께 작성한 기사입니다]', '세제 개편안은 당분간 증시 뉴스 흐름의 중심에 있을 예정”이라고 설명했다.시가총액 상위 종목 중 삼성전자(2.15%)가 7만1000원대를 회복했으며, SK하이닉스(2.13%)도 26만원대로 올라섰다.아울러 LG에너지솔루션(2.26%), 삼성바이오로직스(1.24%), 현대차(1.42%), 기아(0.78%), KB금융(3.23%) 등이 오르고 있다.NAVER(-0.22%), 카카오(-2.53%) 등 인터넷 업종은 하락 중이다.업종별로 보면 증권(2.58%), 전기전자(2.21%), 화학(2.02%) 등 대다수 업종이 오르고 있으며 IT서비스(0.60%)는 하락 중이다.같은 시각 코스닥지수도 전장보다 15.97포인트(2.04%) 오른 800.03이다.지수는 전장보다 7.88포인트(1.01%) 오른 791.94로 출발해 상승폭을 확대 중이다.코스닥시장에서 외국인이 101억원 순매수하고 있으며 개인과 기관은 각각 55억원, 12억원 매도 우위를 보이고 있다.에코프로비엠(5.56%), 에코프로(4.17%) 등 이차전지주와 알테오젠(3.36%), 펩트론(1.53%), 파마리서치(2.16%) 등이 오르고 있다.HLB(-0.21%), 휴젤(-1.23%), 카카오게임즈(-0.42%) 등은 하락 중이다.', '쇼크…“핀셋 정책지원 절실”-車 생산 美 현지화, 노란봉투법에 막히나-LG화학, 친환경 바이오 오일 공장 첫삽-안마해상풍력 케이블 공급 대한전선 1816억 규모 계약-오너 리스크에 실적 악화까지…분할 1년만에 위기 맞은 HS효성-삼성전자, AI·휴머노이드 전담조직 이노X랩 신설△산업-“관세폭탄 맞은 철강 살린다”…K스틸법 발의-세아베스틸, 中 특수강 봉강 반덤핑 제소-다쏘시스템, K조선 디지털 전환 혁신 이끈다-“논문 찾기 쉬워진다”…네이버, 검색결과에 통합 노출△산업-중기 수출 7분기 연속 성장…K뷰티·車가 이끌었다-동원산업, 동원F&B 자회사 편입…“해외진출 본격 시동”-CJ온스타일 더엣지 급성장…패션 독립 브랜드로 키운다△제약·바이오-새 정부 출범 후 7곳 예심청구…바이오기업 코스닥 상장 러시-“빅파마가 원하는 차별화한 신약 보유기업 찾아야”-셀트리온 유플라이마 유럽 점유율 24%…처방실적 선두 눈앞△증권-“폭락장에도 거래세는 하루 180억” 뿔난 개미들 통행세 논란 재점화-삼양컴텍·에스엔시스·에스투더블유, 조선·방산·인공지능 강세 이을까-배당소득 분리과세 너무 까다로워…배당 기대심리도 꺾였다-“변동성 장세 시작…조선·소비관광주 주목해야”△부동산-정비사업 조합 곳곳 내분에 건설사 속앓이-인왕산 아래 옥인동 4층 신축 가능해졌다△문화-낯선 생명체, 88대 스크린서 잉태하고 미술관서 낳다-한 배우의 번민 그린 무대△스포츠-해발 800m서 쾌적하게 라운드…후쿠오카로 골프여행 떠나볼까-“아직 축구선수로서 할 일 남아” 손흥민 질주, END 아닌 AND-AIG 여자오픈 4위 김아림…“아쉽지만 동기부여 생겼죠”-이현중·여준석 출격 한국 男농구…죽음의 조 뚫고 아시아컵 8강 도전△이데일리가 만났습니다-“한국 경제 복합적 위기…AI중심으로 산업·사회 대전환 나설 때”-“GDP 떨어지면 나라살림 더 악화…재정의 경기대응 역할 중요”△피플-배경훈 “모두의 AI로 나아가는 이정표 되길”-CJ대한통운, 한국 사업 인사 단행…FT본부장에 윤철주-우리銀, 딜링룸 새단장…트레이딩 최적화-“광복 정신 되새기자”…교보생명, 남상락 자수 태극기 래핑-시몬스, 김민수 전 루이비통 총괄대표 영입-실험극 거장 美공연연출가 로버트 윌슨 별세△오피니언-사람을 움직이는 말에는 철학이 있다-아프리카…중동 진출의 교두보 튀니지-기업 부채 양보다 질△전국-“북한산 고도제한 완화로 지역발전 물꼬…무분별한 난개발 막을 것”-새단장 속도내는', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.', '많았다. 전날에는 삼성전자,한화엔진(082740), HD한국조선해양 등이 순매수 상위였으며 순매도는두산에너빌리티(034020),대한조선(439260),알테오젠(196170)순으로 많았다.미래에셋증권은 자사 고객 중에서 지난 1개월간 수익률 상위 1% 투자자들의 매매 종목을 집계해 실시간·전일·최근 5일 기준으로 모바일트레이딩시스템(MTS)상에서 공개하고 있다. 이 통계 데이터는 미래에셋증권의 의견과 무관한 단순 정보 안내이며 각각의 투자자 개인에게 맞는 투자 또는 수익 달성을 보장하지 않는다. 테마주 관련 종목은 이상 급등락 가능성이 있으므로 유의해야 한다.']

In [268]:
rerank_df_before_bge_total = pd.DataFrame(list(map(lambda x: x.metadata,before_lst_bge_total)))

In [270]:
rerank_eval_bge_total = []

In [271]:
for kind in target_lst[:10]:
    total_df_target = total_df[total_df.ticker==kind]
    rerank_df_target_bge_total = rerank_df_before_bge_total[rerank_df_before_bge_total.ticker==kind]
    rerank_eval_bge_total.append(eval_reranker_chunk(total_df_target,rerank_df_target_bge_total))

total_rel_pool : 34
y_topk : [1 1 1 0]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1]

In [ ]:
rerank_eval_con_bge_total = dict(zip(target_lst[:10],rerank_eval_bge_total))

In [273]:
pd.DataFrame(rerank_eval_con_bge_total)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.750000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.733333
Recall@30(pool),0.088235,0.476190,0.638298,0.75,0.909091,0.428571,0.553191,0.681818,0.75,0.611111
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.500000
MAP@30,0.100000,0.666667,1.000000,1.00,1.000000,0.428571,0.866667,1.000000,1.00,0.524801
nDCG@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.844991
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,4.000000,20.000000,30.000000,30.00,30.000000,12.000000,26.000000,30.000000,30.00,30.000000
TopKRelevant,3.000000,20.000000,30.000000,30.00,30.000000,12.000000,26.000000,30.000000,30.00,22.000000

## Reranker 모델 사용 후(bge)

1) 종목별

In [14]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=30)
#compression_retriever = ContextualCompressionRetriever(
#    base_compressor=compressor, base_retriever=retriever_total
#)

In [15]:
scored_docs_bge = []

In [290]:
import gc

In [291]:
gc.collect()

3774

In [18]:
for ticker in target_lst[:10]:
    retriever = vectordb_bge.as_retriever(search_kwargs={"k": 30,'filter' : {'ticker' : ticker}})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs_bge.append(dd)
    #scored_docs.sort(key=lambda x: (x.metadata[''],x.metadata["relevance_score"]), reverse=True)

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.

/var/folders/xq/zzsj9f116r7brgm2wm610nx00000gn/T/ipykernel_25593/1928182108.py:8: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대차"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대차가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "KB금융"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, KB금융가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "두산에너빌리티"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 두산에너빌리티가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "HD현대중공업"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, HD현대중공업가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "셀트리온"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 셀트리온가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [20]:
# 4) 확인 - raw data
for i, d in enumerate(scored_docs_bge, 1):
    if d.metadata['ticker'] == '삼성전자':
        print(f"{i:02d} | ticker : {d.metadata['ticker']}| original_idx : {d.metadata['original_idx']} | chunk_idx : {d.metadata['chunk_idx']}| score : {d.metadata['relevance_score']:.4f}")

01 | ticker : 삼성전자| original_idx : 3 | chunk_idx : 0| score : 0.0011
02 | ticker : 삼성전자| original_idx : 22 | chunk_idx : 1| score : 0.0037
03 | ticker : 삼성전자| original_idx : 34 | chunk_idx : 2| score : 0.0001
04 | ticker : 삼성전자| original_idx : 5 | chunk_idx : 1| score : 0.0005
05 | ticker : 삼성전자| original_idx : 7 | chunk_idx : 6| score : 0.0010
06 | ticker : 삼성전자| original_idx : 28 | chunk_idx : 1| score : 0.0010
07 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 7| score : 0.0002
08 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 4| score : 0.0025
09 | ticker : 삼성전자| original_idx : 34 | chunk_idx : 1| score : 0.0065
10 | ticker : 삼성전자| original_idx : 13 | chunk_idx : 0| score : 0.0015
11 | ticker : 삼성전자| original_idx : 1 | chunk_idx : 0| score : 0.0045
12 | ticker : 삼성전자| original_idx : 36 | chunk_idx : 1| score : 0.0043
13 | ticker : 삼성전자| original_idx : 4 | chunk_idx : 0| score : 0.0018
14 | ticker : 삼성전자| original_idx : 36 | chunk_idx : 0| score : 0.0303
15 | ticker : 삼성전자| original_idx : 22 | chunk_idx : 0| score : 0.0001
16 | ticker : 삼성전자| original_idx : 21 | chunk_idx : 0| score : 0.0052
17 | ticker : 삼성전자| original_idx : 9 | chunk_idx : 0| score : 0.0031
18 | ticker : 삼성전자| original_idx : 0 | chunk_idx : 0| score : 0.0008
19 | ticker : 삼성전자| original_idx : 7 | chunk_idx : 3| score : 0.0013
20 | ticker : 삼성전자| original_idx : 10 | chunk_idx : 0| score : 0.0039
21 | ticker : 삼성전자| original_idx : 15 | chunk_idx : 0| score : 0.0028
22 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 0| score : 0.0014
23 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 9| score : 0.0002
24 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 1| score : 0.0001
25 | ticker : 삼성전자| original_idx : 24 | chunk_idx : 0| score : 0.0137
26 | ticker : 삼성전자| original_idx : 2 | chunk_idx : 3| score : 0.0001
27 | ticker : 삼성전자| original_idx : 15 | chunk_idx : 1| score : 0.0008
28 | ticker : 삼성전자| original_idx : 5 | chunk_idx : 0| score : 0.0016
29 | ticker : 삼성전자| original_idx : 28 | chunk_idx : 0| score : 0.0055
30 | ticker : 삼성전자| original_idx : 34 | chunk_idx : 0| score : 0.0001

In [39]:
rerank_df_bge = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs_bge)))

In [40]:
rerank_df_bge= rerank_df_bge.sort_values(by=['ticker','relevance_score'],ascending=False)

In [41]:
rerank_df_bge.head()

    ticker  chunk_idx label  original_idx  relevance_score
155    현대차          0     1           174         0.043823
153    현대차          0     1           161         0.036635
170    현대차          0     1           173         0.027360
173    현대차          0     1           176         0.015825
159    현대차          0     1           170         0.011025

In [42]:
total_df_bge

    ticker label  chunk_idx  original_idx
0     삼성전자     1          0             0
1     삼성전자     1          0             1
2     삼성전자     0          0             2
3     삼성전자     0          1             2
4     삼성전자     0          2             2
..     ...   ...        ...           ...
418   셀트리온     1          1           285
419   셀트리온     1          0           286
420   셀트리온     1          1           286
421   셀트리온     1          0           288
422   셀트리온     1          0           289

[423 rows x 4 columns]

In [43]:
rerank_eval_bge = []

In [45]:
for kind in target_lst[:10]:
    total_df_target = total_df_bge[total_df_bge.ticker==kind]
    rerank_df_target_bge = rerank_df_bge[rerank_df_bge.ticker==kind]
    rerank_eval_bge.append(eval_reranker_chunk(total_df_target,rerank_df_target_bge))

total_rel_pool : 34
y_topk : [1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1]

In [46]:
rerank_eval_co_bge = dict(zip(target_lst[:10],rerank_eval_bge))

In [47]:
pd.DataFrame(rerank_eval_co_bge)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.633333,1.000000,1.000000,1.00,1.000000,0.900000,1.000000,0.966667,1.00,0.90000
Recall@30(pool),0.558824,0.714286,0.638298,0.75,0.909091,0.964286,0.638298,0.659091,0.75,0.75000
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.50000
MAP@30,0.529454,1.000000,1.000000,1.00,1.000000,0.952391,1.000000,0.936941,1.00,0.78702
nDCG@30,0.942577,1.000000,1.000000,1.00,1.000000,0.997520,1.000000,0.992367,1.00,0.90352
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.00000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.00000
TopK,30.000000,30.000000,30.000000,30.00,30.000000,30.000000,30.000000,30.000000,30.00,30.00000
TopKRelevant,19.000000,30.000000,30.000000,30.00,30.000000,27.000000,30.000000,29.000000,30.00,27.00000

## 전체

In [62]:
scored_docs_bge_total = []

In [63]:
for ticker in target_lst[:10]:
    retriever = vectordb_bge.as_retriever(search_kwargs={"k": 50})
    CrossEncoder_prompt = f'''
    이 뉴스들 중에서 "{ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, {ticker}가 단순히 함께 언급된 기사라면 제외해줘.
    '''
    print(CrossEncoder_prompt.strip())
    raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
    pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]
    scores = model.score(pairs)

    # 3) 점수 붙이고 재정렬
    for d, s in zip(raw_docs, scores):
        dd = deepcopy(d)
        dd.metadata["relevance_score"] = float(s)
        scored_docs_bge_total.append(dd)
    #scored_docs.sort(key=lambda x: (x.metadata[''],x.metadata["relevance_score"]), reverse=True)

이 뉴스들 중에서 "삼성전자"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성전자가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "LG에너지솔루션"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, LG에너지솔루션가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "삼성바이오로직스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 삼성바이오로직스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "한화에어로스페이스"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 한화에어로스페이스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "현대차"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 현대차가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "KB금융"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, KB금융가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "두산에너빌리티"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 두산에너빌리티가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "HD현대중공업"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, HD현대중공업가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

이 뉴스들 중에서 "셀트리온"가 핵심 주제로 다뤄진 기사만 알려줘.
    다른 회사 언급이 많거나, 셀트리온가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [70]:
rerank_df_bge_total = pd.DataFrame(list(map(lambda x: x.metadata,scored_docs_bge_total)))

In [71]:
rerank_df_bge_total= rerank_df_bge_total.sort_values(by=['ticker','relevance_score'],ascending=False)

In [72]:
rerank_eval_bge_total = []

In [73]:
for kind in target_lst[:10]:
    total_df_target = total_df_bge[total_df_bge.ticker==kind]
    rerank_df_target_bge_total = rerank_df_bge_total[rerank_df_bge_total.ticker==kind]
    rerank_eval_bge_total.append(eval_reranker_chunk(total_df_target,rerank_df_target_bge_total))

total_rel_pool : 34
y_topk : [1 1 1 1 1 0 0 0 0]
total_rel_pool : 42
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 33
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 28
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 47
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 44
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 40
y_topk : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
total_rel_pool : 36
y_topk : [1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1]

In [74]:
rerank_eval_co_bge_total = dict(zip(target_lst[:10],rerank_eval_bge_total))

In [75]:
pd.DataFrame(rerank_eval_co_bge_total)

,삼성전자,SK하이닉스,LG에너지솔루션,삼성바이오로직스,한화에어로스페이스,현대차,KB금융,두산에너빌리티,HD현대중공업,셀트리온
Precision@30,0.555556,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.633333
Recall@30(pool),0.147059,0.714286,0.638298,0.75,0.909091,0.678571,0.638298,0.681818,0.75,0.527778
MRR@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,1.000000
MAP@30,0.166667,1.000000,1.000000,1.00,1.000000,0.678571,1.000000,1.000000,1.00,0.519521
nDCG@30,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.00,0.945909
PoolSize,59.000000,42.000000,47.000000,40.00,33.000000,31.000000,47.000000,46.000000,40.00,38.000000
PoolRelevant,34.000000,42.000000,47.000000,40.00,33.000000,28.000000,47.000000,44.000000,40.00,36.000000
TopK,9.000000,30.000000,30.000000,30.00,30.000000,19.000000,30.000000,30.000000,30.00,30.000000
TopKRelevant,5.000000,30.000000,30.000000,30.00,30.000000,19.000000,30.000000,30.000000,30.00,19.000000

# 요약문 실험 테스트 수행

## 1. original 본문 가져오기

In [297]:
test_ticker = '우리금융지주'

In [298]:
CrossEncoder_prompt_test = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [312]:
retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
compressor = CrossEncoderReranker(model=model, top_n=50)

In [313]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
)

In [315]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt_test)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [316]:
def get_full_article_from_chroma(original_idx: int, kind : str, vectordb) -> dict:
    """original_idx 기준으로 chunk들을 모아 원문 복원"""
    # 1. 해당 article의 모든 chunk 가져오기
    VecDB = vectordb._collection
    results = VecDB.get(
      where = { "$and" : [ # 빈 쿼리로 전체 탐색
            {"original_idx": original_idx}, 
            {"ticker": kind}
            ]
         },
         include = ['documents','metadatas']   
        )
        
    if not results:
        return {"error": f"No chunks found for original_idx {original_idx}"}

    #print(results)
    #print(results['metadatas'][0]['chunk_idx'])

    # 4. 대표 metadata 하나 뽑아 저장
    return {
        "title": results['metadatas'][0]["title"],
        "url": results['metadatas'][0]["url"],
        "Date": results['metadatas'][0]["Date"],
        "ticker": results['metadatas'][0]["ticker"],
        "content": results['documents'][0]
    }

In [317]:
original_idxs = list(map(lambda x: x.metadata['original_idx'], compressed_docs))

In [318]:
top_n_original = [get_full_article_from_chroma(idx,kind=test_ticker,vectordb=vectordb) for idx in original_idxs]

In [320]:
top_n_original[:5]

[{'title': "'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",
  'url': 'https://www.hankyung.com/article/202507145874L',
  'Date': '2025-07-14',
  'ticker': '우리금융지주',
  'content': '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 296.2만주를 순매수했고, 개인들도 41.8만주를 순매수했다. 하지만 기관은 294.9만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 51.3%, 26.2%로 비중이 높다.더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'},
 {'title': "'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",
  'url': 'https://www.hankyung.com/article/202507084010L',
  'Date': '2025-07-08',
  'ticker': '우리금융지주',
  'content': '◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.'},
 {'title': '"우리금융지주, 연말로 갈수록 고배당 부각…목표가↑"-NH',
  'url': 'https://www.hankyung.com/article/2025070836976',
  'Date': '2025-07-08',
  'ticker': '우리금융지주',
  'content': '사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.com'},
 {'title': '대출 수익성 악화에…4대 금융 실적 꺾였다',
  'url': 'https://www.hankyung.com/article/2025071501731',
  'Date': '2025-07-15',
  'ticker': '우리금융지주',
  'content': 'KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기'},
 {'title': '“금리 하락에도 이익 증가” 금융지주, 실적 온도차',
  'url': 'https://magazine.hankyung.com/business/article/202507210813b',
  'Date': '2025-07-21',
  'ticker': '우리금융지주',
  'content': '서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요'}]

In [321]:
original_contents = list(map(lambda x: x['content'],top_n_original))

In [322]:
total_contents = ''.join(original_contents)

In [323]:
total_contents

'◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 296.2만주를 순매수했고, 개인들도 41.8만주를 순매수했다. 하지만 기관은 294.9만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 51.3%, 26.2%로 비중이 높다.더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.comKB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.※Today\'s Pick은 매일 아침 여의도 애널리스트들이 발간한 종목분석 보고서 중 투자의견 및 목표주가가 변경된 종목을 위주로 한국경제 기자들이 핵심 내용을 간추려 전달합니다.\n\n\n\n\n충북 오창에 위치한 에코프로비엠 본사. 사진=에코프로비엠KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 내며 분기 기준 사상 최대 실적 기록을 썼다. 이자이익 증가세가 사실상 멈췄지만, 환율이 안정된 덕분에 비이자이익이 15% 넘게 늘어난 영향이 크다는 분석이 나온다.25일 금융권에 따르면 4대 금융지주의 지난 2분기 순이익은 총 5조3954억원이었다. 지난해 같은 기간(5조1241억원)과 비교해 2713억원(5.3%) 늘었다. 4대 금융지주의 순이익 합산액이 5조3000억원을 넘은 것은 이번이 처음이다.금융지주별로 보면 하나금융의 순이익이 작년 2분기 1조347억원에서 올 2분기 1조1733억원으로 1386억원(13.4%) 늘어 가장 큰 증가폭을 보였다. 같은 기간 신한금융은 1조4255억원에서 1조5491억원으로 1236억원(8.7%) 불어났다. KB금융의 2분기 순이익은 1조7384억원으로 4대 금융지주 중 가장 많았지만, 전년 동기 대비로는 0.3% 증가하는 데 그쳤다. 우리금융의 순이익은 같은 기간 9315억원에서 9346억원으로 0.3% 늘었다.실적 증가를 이끈 것은 비이자이익이다. 4대 금융지주의 비이자이익은 작년 2분기 3조4264억원에서 올 2분기 3조9591억원으로 5327억원(15.5%) 증가했다. 원화가 강세 흐름을 보이면서 외화환산이익이 늘었다는 게 4대 금융지주의 공통된 설명이다. 반면 4대 금융지주의 올 2분기 이자이익은 전년 동기 대비 0.4% 늘어나는 데 그쳤다.정의진/김진성 기자 justjin@hankyung.com[커버스토리] 2025 밸류업 CEO 50\n\n\n\n\n\n\n\n\n\n\n\n<2025 밸류업 CEO 50 - 금융>11위 임종룡 우리금융지주업종명 금융지주취임일 주가(원) 11,010     최근 주가(원) 21,350     취임일 2023년 3월 24일주가수익률 93.9%배당수익률 21.8%총주주수익률 115.7%12위 빈대인 BNK금융지주업종명 금융지주취임일 주가(원) 6,250     최근 주가(원) 11,790     취임일 2023년 3월 17일주가수익률 88.6%배당수익률 20.5%총주주수익률 109.1%13위 양종희 KB금융업종명 금융지주취임일 주가(원) 54,100     최근 주가(원) 106,500     취임일 2023년 11월 21일주가수익률 96.9%배당수익률 10.4%총주주수익률 107.2%14위 정종표 DB손해보험업종명 보험취임일 주가(원) 65,300     최근 주가(원) 120,200     취임일 2023년 1월 1일주가수익률 84.1%배당수익률 18.5%총주주수익률 102.6%15위 김성태 기업은행업종명 은행취임일 주가(원) 9,560     최근 주가(원) 17,290     취임일 2023년 1월 3일주가수익률 80.9%배당수익률 21.4%총주주수익률 102.3% 16위 함영주 하나금융지주업종명 금융지주취임일 주가(원) 49,350     최근 주가(원) 80,000     취임일 2022년 3월 25일주가수익률 62.1%배당수익률 22.8%총주주수익률 84.9%17위 진옥동 신한지주업종명 금융지주취임일 주가(원) 35,750     최근 주가(원) 59,300 취임일 2023년 3월 23일주가수익률 65.9%배당수익률 13.5%총주주수익률 79.4%18위 박종문 삼성증권업종명 증권취임일 주가(원) 41,550     최근 주가(원) 67,700     취임일 2024년 3월 21일주가수익률 62.9%배당수익률 8.4%총주주수익률 71.4%19위 윤병운 NH투자증권업종명 증권취임일 주가(원) 12,350     최근 주가(원) 19,170     취임일 2024년 3월 27일주가수익률 55.2%배당수익률 7.7%총주주수익률 62.9%20위 박봉권 교보증권업종명 증권취임일 주가(원) 6,770     최근 주가(원) 8,450     취임일 2020년 2월 4일주가수익률 24.8%배당수익률 28.1%총주주수익률 52.9%출산정책 지원, 미 관세 소식, 스테이블코인 등등… 요즘처럼 뉴스 하나에 시장이 요동치는 시대엔, 방향을 잡아줄 확실한 나침반이 필요할 때! 매일 갈아타는 시장 주도주, 오늘도 놓칠 건가요?“불새와 함께라면, 상한가는 남의 얘기가 아닙니다.”\n\n\n\n\n \n\n👉 애경케미칼, 콜마홀딩스 적중의 비밀 확인! (클릭)한국증시의 다양한 대내외 변수 속에서도 높은 수익률과 압도적인 종목 적중률로 단숨에 개인투자자들의 주목을 받는 ‘불새’ 전문가!특히 화제가 되는 건 “내일의 상한가가 미리 보인다”는 평가.불새는 매일 아침 시황 분석, 이슈 정리, 유망 테마 종목, 그리고 핵심 진입 타이밍까지 친절하게 짚어준다. 초보자도 이해할 수 있을 정도로 쉬운 해설에 더해, 결과는 놀라울 정도로 정확하다는 평이다.✅ 정책 테마의 중심에서 상한가를 선점하고 싶다면? 지금 확인!(클릭)무엇보다 놀라운 점은, 이 모든 정보가 100% 무료라는 사실.불새가 운영 중인 텔레그램 채널에 입장만 하면, 아무 조건 없이 매일 고퀄리티 정보를 받아볼 수 있다.👉 내일의 상한가 종목, 입장만 하면 바로 확인 가능! (클릭)ㅤ-최근 핫이슈 종목한화오션, 우리기술투자, 카카오, 키이스트, 우리금융지주무료상담◆ 최근 애널리스트 분석의견- 장기 보유 매력 유효 - 미래에셋증권, 매수07월 14일 미래에셋증권의 정태준 애널리스트는 우리금융지주에 대해 "투자의견 매수로 상향, 목표주가 29,000원으로 상향. 주주환원 매력 배가 예상. 2분기 지배주주순이익은 컨센서스에 부합하는 8,477억원을 예상"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.영상 모듈 닫기국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가고 있다. 특히 신한지주가 18년 만에 사상 최고가를 경신하는 등 주요 금융주가 연이어 52주 신고가를 돌파하고 있다.하나증권에 따르면, 4대 금융지주의 2분기 합산 순이익은 6조 4천억 원 수준으로 전년 동기 대비 약 3.5% 증가할 것으로 전망된다. 이러한 실적 개선은 금리 안정과 비이자 수익 확대 전략, 건전성 관리 성과에 기인한 것으로 분석된다.또한 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것이라는 전망이 제기되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다. 배당 외에도 자사주 정책이 강화될 경우 금융주의 밸류에이션 리레이팅 가능성도 커지고 있다.증권주 역시 국내 증시 반등과 거래대금 증가에 따른 수혜 기대감에 힘입어 주목받고 있다. 주요 증권사들의 올해 영업이익 전망치는 약 1조 2천억 원으로, 이는 전년 대비 10.2% 증가한 수준이다.이 같은 흐름에 따라 8일 장중 ▲신한지주, ▲하나금융지주, ▲KB금융, ▲우리금융지주, ▲유안타증권, ▲iM금융지주, ▲JB금융지주, ▲BNK금융지주 등이 일제히 52주 신고가를 돌파했다. 특히 신한지주는 7만 원 선을 돌파하며 2006년 이후 18년 만에 최고가를 기록했다.외국인 투자자는 16일 거래소에서 KB금융, 현대차, 메리츠금융지주 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 KB금융, 현대차, 메리츠금융지주, 삼성SDI, NAVER, 우리금융지주, 삼성중공업, 풍산, 두산에너빌리티, 한화솔루션등이다.이중에 운수장비 업종에 속한 종목이 2개 포함되어 있다.NAVER, 풍산, DL이앤씨 등은 전일 대비 주가가 상승했고, KB금융, 현대차, 메리츠금융지주 등은 주가가 하락했다.[07월16일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방BBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세정부가 발표한 배당소득 분리과세안이 시장 기대보다 후퇴하면서 배당주가 지난 1일 일제히 급락했다. 하지만 오히려 저가 매수 기회로 삼아야 한다는 조언이 증권가 일각에서 나온다. 기업들이 배당을 늘리는 추세인 데다 주가가 반등했을 때 자본차익을 기대할 수 있어서다. 이번 세제 개편안에 따른 분리과세 조건을 충족하는 기업과 조건을 맞추기 위해 배당을 늘릴 종목에 주목하라는 게 전문가들의 조언이다.\n                    \n\n\n\n\n\n\n이미지 크게보기KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방외국인 투자자는 15일 거래소에서 현대차, 삼성화재, 기아 등을 중점적으로 매도한 것으로 나타났다.외국인 투자자의 순매도 상위 20개 종목은 현대차, 삼성화재, 기아, 기업은행, SK텔레콤, NAVER, 신한지주, 우리금융지주, 삼성SDI, DB손해보험등이다.이중에 보험 업종에 속한 종목이 3개 포함되어 있다.기업은행, NAVER, 우리금융지주 등은 전일 대비 주가가 상승했고, 현대차, 삼성화재, 기아 등은 주가가 하락했다.[07월15일]거래소 외국인 순매도 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.Getty Images Bank\n\n                하나금융지주와 기업은행을 비롯한 5개 금융지주사가 자본성증권(신종자본증권 및 후순위채권) 발행에 나섰다.금융권 자본성증권에 대한 기관투자가들의 선호도가 높아진 최근 흐름에 맞춰 낮은 금리에 자본을 확충한다는 계획이다.보험사 중에서는 DB손해보험이 5000억원 규모의 기본자본 신종자본증권을 보험업계에서 처음으로 발행한다. ◇ 금융사·보험사 자본조달 봇물하나금융과 기업은행은 다음 달 자본성증권 발행을 앞두고 이사회 결의에 나섰다.영상 모듈 닫기서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요남산에서 바라본 서울 시내 스케치.2024.05.31 최혁 기자지난 2년 동안 국내 시가총액 상위 100대 기업의 주주환원 규모가 35% 이상 증가한 것으로 나타났다.특히 KT&G는 시가총액 대비 주주환원 비율에서 1위를 기록했다.6일 기업데이터연구소 CEO스코어에 따르면 2022년 33조7240억 원이던 주주환원 총액은 2024년 45조5784억 원으로 11조8544억 원 35.2% 증가했다.같은 기간 조사 대상 기업들의 시가총액도 1405조4819억 원에서 1664조9773억 원으로 증가하며 시총 대비 환원율은 2.4%에서 2.7%로 소폭 상승했다.\r\n                    \n\n\nCEO스코어 제공주주환원 항목 중 가장 큰 비중을 차지하는 배당금은 2022년 31조8891억 원에서 지난해 37조3201억 원으로 17.0% 증가했다.하지만 전체 주주환원에서 배당이 차지하는 비중은 94.6%에서 81.9%로 낮아졌다.이는 주식소각의 증가에 따른 변화로 같은 기간 주식소각 총액은 1조8349억 원에서 8조2583억 원으로 무려 350.1% 급증했다.기업별로 보면 지난해 시가총액 대비 주주환원 비율이 가장 높은 기업은 KT&G로 10.0%에 달했다.\r\n                    \n\n\nCEO스코어 제공이어 키움증권(9.1%), 우리금융지주(9.0%), 삼성증권(8.0%), SK텔레콤(8.0%) 등이 상위권에 올랐다. 이 외에도 NH투자증권, 하나금융지주, 기업은행, 기아, 삼성물산 등이 상위 10위 안에 포함됐다.특히 금융업권 기업들이 전반적으로 높은 주주환원율을 보인 점이 눈에 띈다. 배당과 자사주 소각 등을 통해 적극적으로 주주 가치를 제고하려는 움직임이 활발하게 나타났다.반면 주주환원을 전혀 하지 않은 기업들도 다수 존재했다. 삼성바이오로직스, LG에너지솔루션, 두산에너빌리티, 한화오션, 알테오젠, 삼성중공업, 카카오페이 등 총 17개 기업은 지난해 주주환원 활동을 하지 않은 것으로 조사됐다.정유진 기자 jinjin@hankyung.com은행 관련 상장지수펀드(ETF) 수익률이 고공 행진하고 있다. 편입된 은행주들이 잇달아 신고가를 갈아 치우면서다. 하반기 은행주의 주주환원 정책이 확대될 것이란 기대도 커지고 있다.\n\n\n\n\n\n                9일 한국거래소에 따르면 국내 상장 ETF(레버리지·인버스 제외)의 최근 1주일(7월 2~8일) 수익률 상위권을 은행 ETF가 휩쓸었다. 가장 높은 수익을 낸 건 ‘TIGER 은행’으로, 이 기간 10.14% 올랐다. KB·신한·하나·우리금융 등 4대 금융지주 주식을 각각 포트폴리오의 20% 내외로 담은 상품이다. 이날 기준 하나금융지주의 비중이 20.04%이고 KB금융(19.06%), 신한지주(18.03%) 등도 높은 비중으로 편입했다.2위부터 4위도 은행 관련 상품이 채웠다. ‘TIGER 은행고배당플러스TOP10’이 해당 기간 9.91%의 수익률을 내며 2위에 올랐다. ‘SOL 금융지주플러스고배당’(9.48%), ‘KODEX 은행’(9.4%) 등이 뒤를 이었다.은행주는 최근 눈에 띄는 상승세를 보이고 있다. KRX은행지수의 1주일 상승률은 9.69%에 달하는데, 이는 35개 KRX지수 중 1위다. 4대 금융지주의 주가는 전날 나란히 장중 52주 최고가를 찍기도 했다.최근 상법 개정안이 국회를 통과한 데 이어 배당소득 분리과세 등 배당 관련 세제도 개편될 가능성이 점쳐지며 대표적인 저PBR(주가순자산비율)주인 은행주에 대한 상승 기대가 커졌다는 분석이 나온다. 박혜진 대신증권 연구원은 “배당 세제 개편 관련 기대감만으로도 은행주는 코스피지수를 웃도는 주가 상승률을 보이고 있다”고 말했다.양지윤 기자 yang@hankyung.com▶마켓인사이트 8월 6일 오후 3시 13분금융지주들이 하반기 신종자본증권(영구채) 발행 작업에 시동을 걸고 있다. 최대 1조8000억원에 육박하는 금융지주의 신종자본증권이 하반기 채권시장에 쏟아질 전망이다. 조달 환경도 개선된 만큼 신종자본증권을 통해 유동성 확보와 자본 확충을 모두 잡겠다는 구상으로 풀이된다.6일 금융감독원 전자공시시스템에 따르면 주요 금융지주가 이사회 결의를 통해 확정한 하반기 신종자본증권 조달 규모는 총 1조7900억원으로 집계됐다. 올해 상반기 금융지주 신종자본증권 발행 규모(1조7050억원)를 웃돈다.신종자본증권은 주식과 채권 성격을 동시에 지닌 하이브리드 채권을 뜻한다. 국제결제은행(BIS) 기준 자기자본비율 산정 때 자본으로 인정받을 수 있어 금융사가 주로 발행한다.5대 금융지주에서는 신한, 하나, 우리, 농협금융이 하반기 신종자본증권 조달 계획을 확정했다. 신한, 하나, 우리금융은 각각 최대 4000억원 규모의 신종자본증권 발행을 추진한다. 농협금융은 지난달 25일 3400억원 규모 신종자본증권 발행을 의결했다.지방에 거점에 둔 금융지주에서는 iM금융과 BNK금융이 신종자본증권 카드를 꺼내 들었다. iM금융은 1000억원을 신종자본증권을 통해 조달할 계획이다. BNK금융은 최대 1500억원어치 신종자본증권을 발행한다는 방침이다.금융지주들이 앞다퉈 자본 확충에 나선 것은 기존에 발행한 신종자본증권의 차환 물량이 줄줄이 도래하기 때문이다. 예컨대 신한, 하나, 우리금융은 신종자본증권으로 조달하는 자금의 대부분을 채무상환용으로 쓸 계획이다. 계열사 지원 등 운영자금 확보를 위해 신종자본증권을 활용하는 경우도 있다. 농협금융은 NH투자증권 등 계열사 유상증자 자금을 지원하기 위해 이번 신종자본증권 발행에 나선 것으로 알려졌다.신종자본증권 조달 환경이 개선되고 있는 것도 호재다. 한 금융지주 관계자는 “보험사보다 신용도가 높은 금융지주 신종자본증권의 희소성이 높아지고 있다”며 “기관과 개인투자자의 관심이 커 목표 물량을 모두 채울 가능성이 크다”고 말했다.장현주 기자 blacksea@hankyung.com정부가 발표한 배당소득 분리과세안이 시장 기대보다 후퇴하면서 배당주가 지난 1일 일제히 급락했다. 하지만 오히려 저가 매수 기회로 삼아야 한다는 조언이 증권가 일각에서 나온다. 기업들이 배당을 늘리는 추세인 데다 주가가 반등했을 때 자본차익을 기대할 수 있어서다. 이번 세제 개편안에 따른 분리과세 조건을 충족하는 기업과 조건을 맞추기 위해 배당을 늘릴 종목에 주목하라는 게 전문가들의 조언이다.\n                    \n\n\n\n\n\n\n이미지 크게보기[한경ESG] 지속가능경영 보고서 CEO 말말말 - 4대 금융지주 \n\n\n\n\n\n“KB금융그룹은 ‘세상을 바꾸는 금융’이라는 사명을 바탕으로 금융의 본질을 넘어 더 멀리 보고 더 깊이 고민하겠습니다.”양종희 KB금융그룹 회장 세상을 바꾸는 금융[1] KB금융그룹은 고객에게는 신뢰할 수 있는 금융, 주주에게는 장기적 성장 가능성을 제시하는 기업, 지역사회에는 함께 성장하는 든든한 동반자가 되는 것을 진정한 가치로 삼아 최선을 다하고 있습니다. [2] 금융은 단순한 자금 중개를 넘어 개인의 삶과 기업의 미래, 나아가 사회 전체의 지속가능성을 연결하는 중요한 기반입니다. 금융의 본질적 역할을 되새기며, 다음 세대에게 더 나은 환경과 기회를 전하는 책임을 다하고자 합니다.[3] KB금융그룹은 기후 위기, 저출생, 지역 소멸, 일자리 문제 등 우리 삶을 위협하는 문제를 외면하지 않고, 금융 본업의 역량을 발휘해 사회와 함께하는 따뜻한 파트너십을 실천해왔습니다. 또 돌봄과 소상공인 지원 등 의미 있는 사회적가치를 창출하고, 이웃과 사회와의 관계를 균형 있게 헤아리며 공존을 추구하고자 했습니다.[4] 앞으로도 KB금융그룹은 고객의 신뢰와 사회의 기대를 가장 소중한 자산으로 여기며, 국민 모두의 성장이 KB의 성장으로 이어지는 지속가능한 길을 함께 만들어가겠습니다.※한경 마켓PRO 텔레그램을 구독하시면 프리미엄 투자 콘텐츠를 보다 편리하게 볼 수 있습니다. 텔레그램에서 ‘마켓PRO’를 검색하면 가입할 수 있습니다.ETF 주간 수익률 TOP20지난 한 주간 금융주(은행, 증권, 보험) 등 고배당주에 투자하는 상장지수펀드(ETF)들이 수익률 상위권을 휩쓸었다.  13일 한국거래소에 따르면 지난 7~11일 기준 국내 상장 ETF 수익률 상위 20개 종목 중 14개가 고배당주 관련 ETF인 것으로 나타났다. 정부와 국회가 배당 활성화 정책을 추진하면서 정책 수혜 기대가 커진 영향이다. \n                    \n\n\n\ndb한경db\n\n                지난 한 주간 금융주(은행, 증권, 보험) 등 고배당주에 투자하는 상장지수펀드(ETF)들이 수익률 상위권을 휩쓸었다.  13일 한국거래소에 따르면 지난 7~11일 기준 국내 상장 ETF 수익률 상위 20개 종목 중 14개가 고배당주 관련 ETF인 것으로 나타났다. 정부와 국회가 배당 활성화 정책을 추진하면서 정책 수혜 기대가 커진 영향이다. \n                    \n\n\n\ndb외국인 투자자는 08일 거래소에서 이수페타시스, 삼성중공업, SK하이닉스 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 이수페타시스, 삼성중공업, SK하이닉스, 하나금융지주, 삼양식품, HD현대, KB금융, 신한지주, 동양철관, 현대차등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.이수페타시스, 삼성중공업, SK하이닉스 등은 전일 대비 주가가 상승했고, POSCO홀딩스, LG화학 등은 주가가 하락했다.[07월08일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기국내 은행 및 증권주들이 2분기 실적 호조와 주주환원 기대감에 힘입어 강세를 이어가고 있다. 특히 신한지주가 18년 만에 사상 최고가를 경신하는 등 주요 금융주가 연이어 52주 신고가를 돌파하고 있다.하나증권에 따르면, 4대 금융지주의 2분기 합산 순이익은 6조 4천억 원 수준으로 전년 동기 대비 약 3.5% 증가할 것으로 전망된다. 이러한 실적 개선은 금리 안정과 비이자 수익 확대 전략, 건전성 관리 성과에 기인한 것으로 분석된다.또한 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것이라는 전망이 제기되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다. 배당 외에도 자사주 정책이 강화될 경우 금융주의 밸류에이션 리레이팅 가능성도 커지고 있다.증권주 역시 국내 증시 반등과 거래대금 증가에 따른 수혜 기대감에 힘입어 주목받고 있다. 주요 증권사들의 올해 영업이익 전망치는 약 1조 2천억 원으로, 이는 전년 대비 10.2% 증가한 수준이다.이 같은 흐름에 따라 8일 장중 ▲신한지주, ▲하나금융지주, ▲KB금융, ▲우리금융지주, ▲유안타증권, ▲iM금융지주, ▲JB금융지주, ▲BNK금융지주 등이 일제히 52주 신고가를 돌파했다. 특히 신한지주는 7만 원 선을 돌파하며 2006년 이후 18년 만에 최고가를 기록했다.2분기 실적 발표 시즌에 본격 돌입하면서 주도주의 성적표가 윤곽을 드러내고 있다. 코스피지수가 단기 급등하며 밸류에이션(실적 대비 주가 수준)이 높아진 만큼 실적이 주가 향방을 가를 주요 변수로 작용할 것이라는 분석이 나온다.사진=게티이미지뱅크 \n\n                올해 강세장을 주도해 온 전력기기주는 지난 1월 말 큰 조정을 겪었다. 중국의 저가 인공지능(AI) 모델 ‘딥시크’의 등장으로 엔비디아 등 미국 AI주가 동반 급락하던 때다. 당시 신한자산운용 주식운용팀 펀드매니저들은 이 같은 조정을 저가 매수로 기회로 보고 HD현대일렉트릭과 효성중공업 등 전력기기주 비중을 대폭 늘렸다. 이후 전력기기주가 급등하면서 ‘SOL 코리아메가테크액티브’ 상장지수펀드(ETF)는 올해 코스피지수를 두 배 이상 앞지르는 성적을 내고 있다. ◇펀드매니저가 주도주에 집중 투자\n\n\n\n\n\n\n\n이미지 크게보기영상 모듈 닫기KB 신한 하나 우리 등 4대 금융지주가 올해 2분기 5조4000억원에 육박하는 순이익을 거두며 성장을 이어갔다. 거듭된 금리 하락으로 주력 사업인 ‘이자 장사’가 녹록지 않은 상황에서 환율 하락에 따른 환차익 증가와 각종 수수료 수입 확대에 힘입어 선방했다는 분석이 나온다. 다만 하반기에는 실적이 나빠질 것이란 우려가 적지 않다. 경기 침체가 계속되는 가운데 정부가 더 강력한 가계대출 억제 정책을 꺼내 들면서 대출 자산 확대가 어려워졌기 때문이다.◇非이자이익 힘입어 선방POSCO홀딩스는 최근 글로벌 금융시장에서 새롭게 주목받고 있다. 먼저 해외 투자자들이 높은 관심을 보인 그린본드 발행은 기업의 친환경 전환 전략에 대한 시장의 신뢰를 강화한 대표적 이벤트였다. POSCO홀딩스는 에너지 소재와 신재생 인프라 투자 자금 조달을 위해 700백만 달러 규모의 글로벌 그린본드를 성공적으로 발행했으며, 예상보다 높은 수요에 힘입어 빠르게 완판된 것으로 알려졌다. 이 과정은 지속 가능한 경영과 ESG 중심 전략에 대한 시장 평가를 크게 끌어올렸다.기술 협업 측면에서도 긍정적 변화가 감지된다. POSCO홀딩스는 호주의 그린 수소 기업 ‘Hysata’와의 전해조 기술 공동 개발을 추진하고 있으며, 이는 향후 수소 경제 시대의 성장 동력으로 꼽히는 혁신 프로젝트에 대한 기대감을 자극했다. 전해조 소재와 시스템 기술 역량을 결합해 상업화 속도를 높이려는 이 전략은 ESG 트렌드가 실질 사업으로 이어지는 구조적 모멘텀으로 인식된다.기업 구조 개선과 수급 재평가도 흐름을 뒷받침한다. 해외 증권사 애널리스트들은 최근 POSCO홀딩스의 매출 회복과 함께 실적 기반 기업가치 재평가 가능성에 대한 리포트를 내놓고 있으며, 일부는 철강산업 내 경쟁사 대비 상대 강도(RS) 지표의 상승 여력을 언급하기도 했다. 내년 초 예정된 실적 발표도 중요한 분기점으로 꼽히고 있으며, 시장에서는 이를 통해 상승 주도권이 강화될 수 있다는 기대가 형성되고 있다.수출·투자 측면에서도 주목할 만한 진전이 있다. POSCO E&C는 최근 태국 LNG 터미널 프로젝트 수주에 성공하며 인프라 사업에서의 해외 성과를 확보했으며, 이는 그룹의 비철강 부문 수익 확장 가능성을 증명했다. 이러한 프로젝트 중심 수익 기반 확대는 기업 리스크를 분산시키고 성장 잠재력을 강화하는 요소로 평가된다.다날, 우리금융지주, 한화시스템, 쿠콘, 삼성바이오로직스무료상담영상 모듈 닫기이재명 대통령이 국내 금융권의 ‘이자놀이’를 경고하자 금융당국이 전 업권 협회장을 긴급 소집해 투자 확대 등 관련 대책을 논의한다. 사상 최대 이익을 거둔 금융사들의 대출 위주 영업 방식을 첨단산업과 벤처·대체투자 등 ‘생산적 금융’으로 전환하는 방안 등을 검토할 것으로 예상된다.27일 금융위원회에 따르면 권대영 금융위 부위원장은 28일 은행연합회, 생명보험협회, 손해보험협회, 여신금융협회, 금융투자협회 등 업권을 대표하는 협회장들과 긴급 조찬 간담회를 할 예정이다. 간담회에서는 업권별 기업 투자 촉진 및 자본시장 활성화 방안 등을 논의할 것으로 전해졌다.금융당국 고위 관계자는 “사상 최대 이익을 거둔 금융사들을 향해 국민의 비판 목소리가 커지고 있다”며 “시대적 요구를 반영한 개선책을 정부와 업계가 함께 마련하기 위한 첫 번째 자리”라고 말했다. 이 대통령은 지난 24일 열린 수석·보좌관회의에서 “손쉬운 주택담보대출 같은 이자놀이에 매달릴 것이 아니라 투자 확대에도 신경 써달라”며 “그래야 국민 경제의 파이가 커지고 금융기관도 건전하게 성장 발전할 수 있지 않겠냐”고 했다. 금융당국, 부동산 대신 기업투자 주문할 듯 벤처 투자 등 생산적 금융 강조…금융권도 규제 개선 건의할 듯금융지주들이 미처 계산하지 못한 재원 부족 문제로 자사주 매입 시기를 내년으로 미루는 일이 잇따르고 있다. 앞다퉈 주주환원 확대를 약속했지만, 배당가능이익이라는 상법상 제약을 간과한 채 속도전을 펼친 탓이다. 손쉬운 ‘이자 놀이’ 대신 기업에 자금 투입을 늘리라는 정부 요구로 자본 비율 관리까지 까다로워지면서 당초 약속한 주주가치 제고 계획이 흔들릴 것이라는 관측이 나온다.국내 은행권이 주가연계증권(ELS) 등 고위험 상품 판매와 운영에 따른 손실액을 10년간 위험가중자산(RWA)에 반영하는 규제와 관련해 외부 컨설팅을 받기로 했다. 해외 사례 수집 등을 통해 근거를 마련한 뒤 “재발 우려를 차단했다면 관련 손실을 RWA에 반영하지 않도록 해달라”고 금융당국에 요구하기 위해서다. 은행의 건전성 관리에 오랫동안 부담을 안긴 ‘홍콩 H지수 ELS 사태’의 족쇄에서 벗어날지 주목된다. ◇“판매 중단 상품 손실은 예외”\n\n\n\n\n\n\n\n이미지 크게보기올해 2분기 국민연금은 국내 증시 상승세에 맞춰 금융, 지주, 내수 관련주 비중을 확대하며 포트폴리오를 조정했다. 이와 동시에 업황 부진이 이어지는 2차전지 업종에 대한 지분 비중은 줄였다.국민연금은 상법 개정안 통과 기대에 따른 주주환원 여력과 지배구조 개편 수혜가 예상되는 금융주와 지주사에 대한 투자를 늘렸으며, 내수 진작 기대가 커지면서 내수주도 추가 매수했다. 반면 2차전지 업종은 당분간 실적 기대가 낮아짐에 따라 비중을 축소했다.또한 일부 기업에 대해 단순투자 목적에서 일반투자로 보유 목적을 변경하며 지배구조 개선 등 주주 의견 전달을 강화하려는 움직임도 보였다. 국민연금은 내년도 기금운용계획에서 국내주식 비중을 소폭 줄이고 해외주식 비중을 늘릴 계획이다.한편, 스탁론에 대한 

In [324]:
len(total_contents)

22496

수기 입력으로 확인
> 확인 사유 : 0번째 문서가 이상하..?

In [310]:
retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
CrossEncoder_prompt = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''
print(CrossEncoder_prompt.strip())
raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]

scores = model.score(pairs)
scored = sorted(zip(raw_docs, scores), key=lambda x: float(x[1]), reverse=True)[:50]
scored_docs=[]
# 3) 점수 붙이고 재정렬
for d, s in zip(raw_docs, scores):
    dd = deepcopy(d)
    dd.metadata["relevance_score"] = float(s)
    scored_docs.append(dd)

이 뉴스들 중에서 "우리금융지주"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, 우리금융지주가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [311]:
pd.DataFrame(list(map(lambda x: x.metadata,scored_docs))).sort_values(by=['ticker','relevance_score'],ascending=False).head(5)

,chunk_idx,title,url,label,original_idx,ticker,Date,relevance_score
3,0,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",https://www.hankyung.com/article/202507145874L,1,237,우리금융지주,2025-07-14,0.602175
14,0,"'우리금융지주' 52주 신고가 경신, 전일 외국인 대량 순매수",https://www.hankyung.com/article/202507084010L,1,374,우리금융지주,2025-07-08,0.467356
9,0,"""우리금융지주, 연말로 갈수록 고배당 부각…목표가↑""-NH",https://www.hankyung.com/article/2025070836976,1,476,우리금융지주,2025-07-08,0.397002
6,1,대출 수익성 악화에…4대 금융 실적 꺾였다,https://www.hankyung.com/article/2025071501731,1,158,우리금융지주,2025-07-15,0.358331
10,0,"“금리 하락에도 이익 증가” 금융지주, 실적 온도차",https://magazine.hankyung.com/business/article...,1,446,우리금융지주,2025-07-21,0.265313

## 요약하기

### 요약함수 호출
- 가져온 원 본문을 전부 적용하기

In [119]:
from summart_function_openai_2 import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

In [124]:
def summarize_top_articles_2(total_contents: str,ticker:str,max_iters:int) -> pd.DataFrame:
    agent = NewsSummaryAgent(max_iters=max_iters)
    runnable = build_summary_graph(agent)

    rows = []
    doc = total_contents

    state = {"article": doc, "summary": "", "feedback": "", "iteration": 0}
    result = runnable.invoke(state)

    print("✅ 실행 결과 키:", result.keys())
    # 여기서 final_summary 반드시 존재해야 함(위 패치 기준)
    final_summary = result.get("final_summary")
    if not final_summary:
        print("❌ final_summary 없음. 디버그용 전체 상태:", result)
        # 계속 진행할지, 실패로 표기할지 선택

    rows.append({
        "ticker": ticker,
        "date": '2025-07-30', # 위 조회 기준일자로 연동시켜서 바꿀 예정
        "summary": final_summary,
        "feedback": result.get("last_feedback", "피드백 없음"),
    })

    return pd.DataFrame(rows)

In [325]:
result_df = summarize_top_articles_2(total_contents,ticker=test_ticker,max_iters=5)

summart : ✅ 주요 요약
- 외국인, 우리금융지주 대량 순매수
  외국인은 최근 3일 연속으로 우리금융지주 주식을 대량 순매수하며 투자자들의 관심이 집중되고 있다.

- 우리금융지주, 2분기 순이익 감소 전망
  우리금융지주의 2분기 순이익은 전년 대비 감소할 것으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용 등으로 인한 판매관리비 증가가 원인으로 분석된다.

- 4대 금융지주, 비이자이익 증가로 실적 선방
  KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있다.

🔑 키워드: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망.
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 언급된 외국인 순매수와 관련된 정보는 기사에 있지만, 요약에서 언급된 '우리금융지주 2분기 순이익 감소 전망'의 구체적인 원인인 '모바일 트레이딩 시스템 개발과 신규 인력 채용'은 기사에 명시되어 있지 않습니다.] </reason>
- 포괄성: 부족함 <reason> [요약은 외국인 순매수와 2분기 실적 전망에 대한 주요 내용을 다루고 있지만, 기사에 포함된 다양한 애널리스트 의견과 금융지주들의 배당 및 자사주 매입 관련 정보가 누락되었습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 핵심 정보를 간결하게 전달하고 있습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있어 이해하기 쉽습니다.] </reason>
- 일관성: 부족함 <reason> [요약은 특정 종목인 '우리금융지주'에 대한 내용에 집중하고 있지만, 기사에는 다른 금융지주들에 대한 정보도 포함되어 있어 일관성이 부족합니다.] </reason>

**피드백:**
- 정확성을 높이기 위해서는 기사에 명시된 정보만을 기반으로 요약을 작성해야 합니다. 예를 들어, '모바일 트레이딩 시스템 개발과 신규 인력 채용'과 같은 구체적인 원인은 기사에 명시되지 않았으므로 요약에서 제외해야 합니다.
- 포괄성을 개선하기 위해서는 기사에 언급된 다양한 애널리스트 의견, 금융지주들의 배당 및 자사주 매입 관련 정보 등도 포함하여 전체적인 맥락을 더 잘 반영해야 합니다.
- 일관성을 높이기 위해서는 특정 종목에 대한 정보뿐만 아니라 기사에 포함된 다른 금융지주들에 대한 정보도 고려하여 요약을 작성해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n- 외국인, 우리금융지주 대량 순매수\n  외국인은 최근 3일 연속으로 우리금융지주 주식을 대량 순매수하며 투자자들의 관심이 집중되고 있다.\n\n- 우리금융지주, 2분기 순이익 감소 전망\n  우리금융지주의 2분기 순이익은 전년 대비 감소할 것으로 예상되며, 이는 판매관리비 증가가 원인으로 분석된다.\n\n- 4대 금융지주, 비이자이익 증가로 실적 선방\n  KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있다.\n\n- 애널리스트 의견 및 배당 매력\n  NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망이다.\n\n- 금융지주들의 배당 및 자사주 매입\n  4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있다.\n\n🔑 키워드: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입."
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약 내용이 원문 기사와 일부 일치하지 않으며, 특히 외국인 순매수와 관련된 수치가 일관되지 않음] </reason>
- 포괄성: 부족함 <reason> [중요한 정보가 모두 포함되지 않았으며, 특히 금융지주들의 실적과 관련된 세부 사항이 누락됨] </reason>
- 간결성: 좋음 <reason> [불필요한 표현 없이 간결하게 작성됨] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성됨] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용만 존재하지 않고, 여러 금융지주에 대한 내용이 혼재되어 있음] </reason>

**피드백:**
1. **정확성**: 요약에서 외국인 순매수와 관련된 수치가 원문과 일치하지 않으므로, 원문에서 제공된 수치를 정확히 반영해야 합니다.

2. **포괄성**: 금융지주들의 실적에 대한 세부 사항, 특히 각 금융지주의 실적 변화와 그 원인에 대한 정보가 요약에 포함되어야 합니다. 예를 들어, 각 금융지주의 순이익 변화와 그 이유에 대한 정보가 필요합니다.

3. **일관성**: 요약은 특정 종목(우리금융지주)에 대한 내용으로 일관되게 작성되어야 합니다. 현재 요약은 여러 금융지주에 대한 내용을 혼재하고 있어, 특정 종목에 집중된 요약을 작성해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입."
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 좋음
- 포괄성: 부족함 <reason> [요약에서 언급된 내용 외에도 기사에는 다른 금융지주사들의 실적 및 전망, 배당 정책, 외국인 투자 동향 등 다양한 정보가 포함되어 있으나, 요약에서는 주로 우리금융지주에 대한 내용만 다루고 있습니다.] </reason>
- 간결성: 좋음
- 문장구성: 좋음
- 일관성: 좋음

피드백:
포괄성 측면에서 개선이 필요합니다. 기사에는 우리금융지주 외에도 다른 금융지주사들의 실적, 배당 정책, 외국인 투자 동향 등 다양한 정보가 포함되어 있습니다. 요약에서는 이러한 다양한 정보를 포함하여 독자가 전체 기사의 주요 내용을 파악할 수 있도록 해야 합니다. 특히, 다른 금융지주사들의 실적 및 전망, 배당 정책에 대한 정보도 요약에 포함되면 더 포괄적인 요약이 될 것입니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상되며, 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었으나, 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주."
[should_stop] Iteration: 3
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약은 원문 기사의 주요 내용을 대부분 반영하고 있지만, 일부 세부 사항과 수치가 원문과 일치하지 않거나 누락되었습니다.] </reason>
- 포괄성: 부족함 <reason> [요약은 주요 포인트를 다루고 있지만, 기사에서 다룬 모든 중요한 내용을 포함하지 않았습니다. 특히, 다른 금융지주사의 실적 및 전망에 대한 세부 사항이 부족합니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장 구조가 자연스럽고 명확하게 작성되었습니다.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목에 대한 내용에 집중되어 있지 않고, 여러 금융지주사에 대한 내용이 혼재되어 있습니다.] </reason>

피드백:
1. **정확성 및 포괄성 개선**: 요약에서 언급된 수치와 세부 사항이 원문과 일치하도록 주의하세요. 특히, 다른 금융지주사들의 실적 및 전망에 대한 구체적인 수치를 포함하여 포괄성을 높일 필요가 있습니다.

2. **일관성 개선**: 요약의 초점을 명확히 하여 특정 종목이나 주제에 대한 일관된 정보를 제공하도록 하세요. 여러 금융지주사에 대한 정보를 다룰 경우, 각 금융지주사에 대한 정보를 명확히 구분하여 제시하는 것이 좋습니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주."
[should_stop] Iteration: 4
[should_stop] Feedback:
 - 정확성: 좋음
  <reason> 요약 내용이 원문 기사와 대체로 일치하며, 주요 정보가 정확하게 전달되었습니다. </reason>

- 포괄성: 부족함
  <reason> 원문 기사에서 다루고 있는 다양한 금융지주사들의 실적 및 전망에 대한 정보가 충분히 포함되지 않았습니다. </reason>

- 간결성: 좋음
  <reason> 요약이 불필요한 표현 없이 간결하게 작성되었습니다. </reason>

- 문장구성: 좋음
  <reason> 문장이 자연스럽고 명확하게 구성되어 있습니다. </reason>

- 일관성: 부족함
  <reason> 요약이 특정 종목(우리금융지주)에 초점을 맞추고 있으나, 원문 기사는 다양한 금융지주사에 대한 정보를 포함하고 있습니다. </reason>

**피드백:**
포괄성과 일관성 측면에서 개선이 필요합니다. 원문 기사는 다양한 금융지주사의 실적과 전망을 다루고 있으므로, 요약에서도 다른 금융지주사들에 대한 정보가 더 포함되어야 합니다. 또한, 요약이 특정 종목에만 집중되지 않도록 다양한 금융지주사에 대한 정보를 균형 있게 다루는 것이 중요합니다. 이를 통해 독자가 전체적인 금융 시장 상황을 더 잘 이해할 수 있도록 해야 합니다.
[should_stop] next_step = no
====== result : refined_summary="✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.\n\n- **우리금융지주, 2분기 순이익 감소 전망**\n  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.\n\n- **4대 금융지주, 비이자이익 증가로 실적 선방**\n  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.\n\n- **애널리스트 의견 및 배당 매력**\n  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.\n\n- **금융지주들의 배당 및 자사주 매입**\n  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.\n\n- **다른 금융지주사들의 실적 및 전망**\n  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.\n\n- **금융지주사들의 장기 전망**\n  - 4대 금융지주의 연간 순이익은 총 18조원에 육박할 것으로 예상되며, 이는 비이자이익 증가와 주주환원 정책 강화에 기인합니다. 그러나 경기 침체와 대출 규제 강화로 인해 하반기 실적에는 불확실성이 존재합니다.\n\n🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주, 주주환원 정책."
[should_stop] Iteration: 5
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 언급된 일부 정보가 원문 기사와 일치하지 않거나 부정확합니다. 예를 들어, 외국인 순매수와 관련된 수치가 일치하지 않습니다.] </reason>
- 포괄성: 부족함 <reason> [요약에서 중요한 정보가 일부 누락되었습니다. 예를 들어, 다른 금융지주사의 실적 및 전망에 대한 정보가 충분히 포함되지 않았습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성되었습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목인 우리금융지주에 대한 내용에 집중되어 있지만, 다른 금융지주사에 대한 정보도 포함되어 있어 일관성이 부족합니다.] </reason>

피드백:
1. **정확성**: 원문 기사와의 일치성을 높이기 위해 요약에서 언급된 수치와 정보를 다시 한 번 확인하고, 정확하게 반영해야 합니다.
2. **포괄성**: 다른 금융지주사들의 실적 및 전망에 대한 정보를 더 포함하여 전체적인 맥락을 제공해야 합니다.
3. **일관성**: 특정 종목에 대한 내용만을 요약하려면, 다른 금융지주사에 대한 정보는 제외하거나 별도로 분리하여 작성하는 것이 좋습니다.
[should_stop] next_step = yes
final_output
✅ 실행 결과 키: dict_keys(['article', 'summary', 'feedback', 'iteration', 'final_summary', 'last_feedback', 'refined_once'])

In [326]:
result_df

,ticker,date,summary,feedback
0,우리금융지주,2025-07-30,"✅ 주요 요약\n\n- **외국인, 우리금융지주 대량 순매수**\n - 외국인은 ...",- 정확성: 부족함 <reason> [요약에서 언급된 일부 정보가 원문 기사와 일치...

In [327]:
print(result_df.summary.values[0])

✅ 주요 요약

- **외국인, 우리금융지주 대량 순매수**
  - 외국인은 최근 3일 동안 우리금융지주 주식을 29.4만주 순매수하며 투자자들의 주목을 받고 있습니다. 지난 한 달 동안 외국인은 490.4만주를 순매수한 반면, 기관은 470.8만주를 순매도했습니다.

- **우리금융지주, 2분기 순이익 감소 전망**
  - 우리금융지주의 2분기 순이익은 전년 대비 8.6% 감소한 8784억원으로 예상됩니다. 이는 모바일 트레이딩 시스템 개발과 신규 인력 채용에 따른 판매관리비 증가가 주요 원인으로 분석됩니다.

- **4대 금융지주, 비이자이익 증가로 실적 선방**
  - KB, 신한, 하나, 우리 등 4대 금융지주는 비이자이익 증가 덕분에 2분기 실적이 개선되었습니다. 그러나 하반기에는 경기 침체와 대출 자산 확대 어려움으로 실적이 나빠질 우려가 있습니다.

- **애널리스트 의견 및 배당 매력**
  - NH투자증권과 상상인증권은 우리금융지주의 배당 매력을 강조하며 투자의견을 '매수'로 유지했습니다. 하반기 자사주 매입 가능성은 낮지만, 배당 매력은 더욱 부각될 전망입니다.

- **금융지주들의 배당 및 자사주 매입**
  - 4대 금융지주는 하반기 자사주 매입 및 소각 규모가 최소 1조 6천억 원에 이를 것으로 예상되며, 주주친화 정책 강화가 주가 상승의 모멘텀으로 작용하고 있습니다.

- **다른 금융지주사들의 실적 및 전망**
  - 신한금융지주는 2분기 순이익이 1.3% 증가할 것으로 예상되며, 하나금융지주는 7% 이상 증가할 것으로 보입니다. 이는 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있기 때문입니다.

- **금융지주사들의 장기 전망**
  - 4대 금융지주의 연간 순이익은 총 18조원에 육박할 것으로 예상되며, 이는 비이자이익 증가와 주주환원 정책 강화에 기인합니다. 그러나 경기 침체와 대출 규제 강화로 인해 하반기 실적에는 불확실성이 존재합니다.

🔑 **키워드**: 외국인 순매수, 우리금융지주, 2분기 순이익, 비이자이익, 4대 금융지주, 경기 침체, 대출 자산, 실적 전망, 배당 매력, 자사주 매입, 신한금융지주, 하나금융지주, 주주환원 정책.

## 피드백 정리
- 삼성전자  : 삼성전자에 대한 내용 잘 요약
- 우리금융지주 : 우리금융지주에 대한 내용 잘 요약
- SK하이닉스 : 요약은 되었으나,, 시장 내/외부 사람들의 구매 패턴, 동향에 대한 정보가 주로 요약이 되고 있음<br>
            > recall@50(pool) 이 상당히 낮게 나옴!
  > SK하이닉스에 대한 케이스를 봤을 때, chunk에 대해서만 요약을 해야하나 싶음<br>
  > 2025.08.11) 현재 작업은 전체 원문에 대한 요약이었음. 그래서.. SK 하이닉스 회사 본질에 대한 정보를 제대로 요약해주지 못하나 싶음<br>
  > 프롬프트 내부 요약 평가 기준 의 "일관성" 영역에 명확히 종목명을 말해야겠다..

## 2. chunk만 수행하기

In [ ]:
test_ticker = '우리금융지주'
CrossEncoder_prompt_test = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''

In [254]:
#model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-base")
model = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
compressor = CrossEncoderReranker(model=model, top_n=50)

In [255]:
retriever_test = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})

In [256]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retriever_test
)

In [257]:
compressed_docs = compression_retriever.invoke(CrossEncoder_prompt)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [259]:
list(map(lambda x: x.metadata['title'],compressed_docs))[:5]

["SK하이닉스 또 '사상 최고' 실적…분기 영업익 9조 넘었다",
 "SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+]",
 "'역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다",
 'AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화',
 'SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위']

compressed_docs와 수기로 계산한 것이 같은 것 증명

In [246]:
retriever = vectordb.as_retriever(search_kwargs={"k": 50,'filter' : {'ticker' : test_ticker}})
CrossEncoder_prompt = f'''
이 뉴스들 중에서 "{test_ticker}"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, {test_ticker}가 단순히 함께 언급된 기사라면 제외해줘.
'''
print(CrossEncoder_prompt.strip())
raw_docs = retriever.get_relevant_documents(CrossEncoder_prompt)
pairs = [(CrossEncoder_prompt, d.page_content) for d in raw_docs]

scores = model.score(pairs)
scored = sorted(zip(raw_docs, scores), key=lambda x: float(x[1]), reverse=True)[:50]
scored_docs=[]
# 3) 점수 붙이고 재정렬
for d, s in zip(raw_docs, scores):
    dd = deepcopy(d)
    dd.metadata["relevance_score"] = float(s)
    scored_docs.append(dd)

이 뉴스들 중에서 "SK하이닉스"가 핵심 주제로 다뤄진 기사만 알려줘.
다른 회사 언급이 많거나, SK하이닉스가 단순히 함께 언급된 기사라면 제외해줘.

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

In [260]:
pd.DataFrame(list(map(lambda x: x.metadata,scored_docs))).sort_values(by=['ticker','relevance_score'],ascending=False).head(5)

,original_idx,title,url,label,chunk_idx,ticker,Date,relevance_score
47,3560,SK하이닉스 또 '사상 최고' 실적…분기 영업익 9조 넘었다,https://www.hankyung.com/article/202507248226g,1,1,SK하이닉스,2025-07-24,0.684618
25,3927,SK하이닉스 사상 최대 실적에도…'신중론' 여전한 이유 [종목+],https://www.hankyung.com/article/2025072510306,1,1,SK하이닉스,2025-07-25,0.672207
37,3724,"'역대급 실적' SK하이닉스, 2분기 영업이익 9조원 넘었다",https://magazine.hankyung.com/business/article...,1,0,SK하이닉스,2025-07-24,0.611750
15,3744,"AI 수요 폭증과 HBM 기술 주도에 힘입은 SK하이닉스, 주가 반등 흐름 가속화",https://www.hankyung.com/article/202507313103a,1,0,SK하이닉스,2025-07-31,0.601519
14,3867,"SK하이닉스, 삼성전자 제치고 ‘대학생이 일하고 싶은 기업’ 첫 1위",https://magazine.hankyung.com/job-joy/article/...,1,2,SK하이닉스,2025-07-28,0.455363

이어서 시작

In [336]:
unique_lst = list(set(list(map(lambda x: x.page_content,compressed_docs))))

In [337]:
chunk_total = ''.join(unique_lst)

In [338]:
chunk_total

'KB 신한 하나 우리 등 4대 금융지주의 올해 2분기 합산 순이익이 전년 동기 대비 감소한 것으로 파악됐다. 금융지주의 실적이 전년 동기 대비 감소한 것은 홍콩 H지수 주가연계증권(ELS) 배상으로 1조원 넘는 일회성 비용이 발생한 2024년 1분기를 제외하면 1년 반 만에 처음이다. 금융회사의 핵심 수익원인 이자수익이 줄줄이 감소한 결과다. 금융지주의 핵심 자회사인 은행들이 가계대출 억제 정책과 경기 침체로 대출 자산을 확대하기 어려운 만큼 향후 금융지주의 실적 감소세가 본격화할 것이란 관측이 제기된다.\n                    \n\n\n\n\n\n\n이미지 크게보기증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요 금융지주들의 연간 실적 전망은 오히려 상향 조정되는 추세다.이는 각 금융지주가 이자이익 축소에 대비해 새로운 수익원 확보에 주력했기 때문으로 분석된다.KB금융은 오는 24일, 신한·하나·우리금융은 25일 차례로 2분기 실적을 발표할 예정이다.정유진 기자 jinjin@hankyung.com강세장을 이끈 것은 5조원 순매수한 연기금 외에 자사주와 외국인이다. 현재까지 자사주 매입은 약 10조원에 달할 것으로 추정되는데 삼성전자와 은행이 주요 매수 주체였다. 이 추세는 정부 정책과 맞물려서 하반기에도 이어진다. 하반기 6조원이 더해지면 올해 약16조원이 자사주 매입의 형태로 증시에 유입되는데 이는 작년의 2조원 자사주 순매수와 크게 대비된다. 외인은 연초부터 4월 말까지 트럼프의 관세 악재로 18조 매도했지만 이후 매수로 전환해서 12조원의 순매수를 누적했다.2000년 이후 25년 동안 외인의 누적 순매수 추세는 2번의 80조원 싸이클과 1번의 40조원 사이클을 보인 후 4번째 순환사이클을 막 시작했다. 직전 순매수 저점에서 12조를 매수하면서 업사이클로 전환했는데 향후 몇 년에 걸쳐 수십 조원의 한국 주식 순매수가 지속될 것으로 전망된다. 외인은 한국의 기업이익이 추세적으로 증가하고 원화 강세가 추세를 형성할 때 수년 지속되는 매수 싸이클을 형성하는데 이번에는 친주주 성향의 새 정부 정책으로 순매수 싸이클 정점이 높고 지속 기간도 높을 것으로 전망된다. 정부의 부동산 억제 정책과 증시 친화적인 정책으로 국내 투자가들의 장기투자 전환 가능성도 높아 수년간 지속되는 강세장이 예상된다. 원전주/증권/은행지수가 걱정의 벽을 타고 예상보다 큰 폭으로 상승했고 이익 전망이 구조적으로 향상된 조선, 방산, 원전, 전력기기 업종과 주주 환원이 강화된 지주, 금융 업종이 상반기 상승을 주도했다. 급등한 지수보다 더 큰 폭으로 오른 상반기 주도주에 대한 차익 실현 수요가 매우 커서 그동안 소외된 삼성전자와 밸류체인, 2차전지, 소재의 반등이 강력한데 그럼에도 후자의 이익 규모와 지속성이 제한적이어서 8월 이후의 유망 업종 선택에는 많은 고민이 필요하다. 기존 주도 업종들은 성장 가능성에도 불구하고 밸류에이션 부담과 피크 아웃에 대한 우려가 상존해서 주가 및 기간 조정을 염두에 두고 저가 매수를 고려해야 하고 소외되었던 주식들의 급반등은 조심스러운 시각으로 접근할 필요성이 높다. KOSPI 3,000pt 이후 매수 강도를 높여가고 있는 외인이 선호하면서 하반기 및 내년에 이익이 크게 증가할 수 있는 대형주에 대한 매수 수요가 지속될 가능성이 높은 국면이 기대된다. 업종별 키 맞추기지수가 걱정의 벽을 타고 예상보다 큰 폭으로 상승했고 이익 전망이 구조적으로 향상된 조선, 방산, 원전, 전력기기 업종과 주주 환원이대장주라는 걸 감안해도 너무 올랐다는 건가요?<기자> 그렇습니다. 한국투자증권과 삼성증권 등 경쟁사들이 미래에셋증권에 대해 2분기 어닝 서프라이즈 기대가 된다면서도 투자의견을 \'중립\'으로 하향 조정했습니다. 다른 증권사 대비 더 다양한 수혜가 이미 반영됐다고 판단한 건데요. 대표적인 게 자사주 소각 의무화와 스테이블코인 법제화입니다.미래에셋증권의 자사주 보유량은 23% 수준으로 대형 증권사 가운데 가장 많습니다. 또 자회사인 미래에셋컨설팅이 스테이블 코인 상표를 출원하면서 사실상 정책적 호재는 모두 입었습니다. 주가가 고평가 됐다는 입장에서는 자사주 소각과 스테이블 코인은 이제 법안 발의 단계인 탓에 실제 실행까진 지금은 너무 이른 시점이라는 판단입니다.우리가 적정주가를 산정하는 방법 가운데 하나로 주가순자산비율(PBR)을 활용하잖아요. 증권업종은 대표적인 저 PBR 업종인데요. 최근 가파른 주가 상승으로 미래에셋증권이 한때 PBR 1배 수준를 넘기기도 했습니다. 순이익이 커지면 PBR은 낮아지는데. 2분기 순이익 증가분을 반영해도 PBR이 1배 수준을 보여 추가 상승여력이 낮다는 평가입니다.<앵커> 우리 증권사들도 금융위기 전에는 PBR 1배 이상을 보인 것으로 아는데요.<기자> 증권업 호황시절인 2008년 이전에 1배에서 1.5배 수준을 보이긴 했는데요. 그 이후엔 드물었습니다. 팬데믹 기간 1배에 근접하긴 했지만 다시 하락해 최근까지 0.4배 정도에 머물렀습니다. 현재 JP모건이나 골드만삭스, 모건스탠리 같은 글로벌 투자은행(IB)들의 PBR이 2배 수준에 근접하는데요.더 오를 수 있다는 쪽에선 미래에셋증권 뿐만 아니라 다른 증권사들의 PBR이 평균 0.9배 수준으로 올라왔다는 점을 강조합니다. 무엇보다 증권업종의 저 PBR이 한국 증시의 이른바 \'코리아 디스카운드\'로부터 비롯됐다는 점에서 증시 상승세가 이어진다면 PBR 1.2배 이상까지도 문제 없다는 시각이 있습니다. 실제 NH투자증권은 미래에셋증권의 타겟 PBR을 1.2배로 설정해 목표주가를 28,000원으로 제시했습니다.<앵커> 네. 잘 들었습니다.정재홍기자 jhjeong@wowtv.co.kr금융당국이 예정에 없던 긴급 간담회를 소집한 것은 사상 최대 이익을 거둔 금융지주를 향한 금융권 안팎의 ‘불편한 기류’가 확산하고 있어서다. 경기 악화, 미국발(發) 관세 불확실성 등 각종 악재가 불거지는 와중에 금융권만 때아닌 호황을 누리고 있다는 비판이 커지고 있기 때문이다.KB 신한 하나 우리 등 4대 금융은 올 상반기에만 10조원 넘는 순이익을 냈다. 이자이익과 비이자이익이 동시에 불어나며 역대 최대 순이익을 올렸다. 저금리 기조 속에도 4대 금융의 상반기 이자수익은 21조924억원으로, 작년 동기(20조8106억원) 대비 2818억원(1.4%) 늘었다. 금융권 관계자는 “금리, 환율 하락으로 유가증권·외환·파생 이익 등이 전반적으로 급증했고 은행 퇴직연금·방카슈랑스 판매수수료와 증권 중개수수료 등 비이자이익도 증가했다”고 설명했다.역대급 이익을 낸 금융권을 향한 정부의 압박은 한층 거세지고 있다. 이재명 대통령이 ‘이자놀이’를 비판하면서다. 이 대통령은 시장 유동 자금이 부동산이 아니라 국가 경쟁력을 높일 수 있는 혁신 기업에 유입돼야 한다는 의견을 여러 차례 밝혔다.금융당국은 이번 간담회를 통해 대통령 핵심 공약인 ‘100조원 첨단산업 펀드’ 조성을 위한 금융권의 적극적인 참여를 독려할 것으로 보인다. 앞서 정부는 국민과 기업이 함께 참여하는 100조원 규모 펀드를 통해 인공지능(AI), 바이오, 항공우주 등 첨단 산업 경쟁력을 높이겠다는 로드맵을 마련했다. 다양한 자본시장 활성화 방안도 논의될 전망이다. 앞서 권대영 금융위원회 부위원장은 “금융권에 넘치는 돈이 자본시장 등 생산적인 곳으로 흘러갈 수 있도록 물꼬를 트겠다”고 공언했다.금융권은 이번 간담회에서 벤처 투자 등을 늘리기 위한 규제 개선 방안을 건의한다는 계획이다. 현 제도로는 정부가 요구하는 기업 투자에 적극 뛰어들기 어렵기 때문이다. 금융당국은 업계 요구를 받아들여 위험가중자산(RWA) 가중치 조정 등의 제도 개편을 고심 중이다.박재원 기자 wonderful@hankyung.com남산에서 바라본 서울 시내 스케치.2024.05.31 최혁 기자지난 2년 동안 국내 시가총액 상위 100대 기업의 주주환원 규모가 35% 이상 증가한 것으로 나타났다.특히 KT&G는 시가총액 대비 주주환원 비율에서 1위를 기록했다.6일 기업데이터연구소 CEO스코어에 따르면 2022년 33조7240억 원이던 주주환원 총액은 2024년 45조5784억 원으로 11조8544억 원 35.2% 증가했다.같은 기간 조사 대상 기업들의 시가총액도 1405조4819억 원에서 1664조9773억 원으로 증가하며 시총 대비 환원율은 2.4%에서 2.7%로 소폭 상승했다.\r\n                    \n\n\nCEO스코어 제공주주환원 항목 중 가장 큰 비중을 차지하는 배당금은 2022년 31조8891억 원에서 지난해 37조3201억 원으로 17.0% 증가했다.하지만 전체 주주환원에서 배당이 차지하는 비중은 94.6%에서 81.9%로 낮아졌다.이는 주식소각의 증가에 따른 변화로 같은 기간 주식소각 총액은 1조8349억 원에서 8조2583억 원으로 무려 350.1% 급증했다.기업별로 보면 지난해 시가총액 대비 주주환원 비율이 가장 높은 기업은 KT&G로 10.0%에 달했다.\r\n                    \n\n\nCEO스코어 제공이어 키움증권(9.1%), 우리금융지주(9.0%), 삼성증권(8.0%), SK텔레콤(8.0%) 등이 상위권에 올랐다. 이 외에도 NH투자증권, 하나금융지주, 기업은행, 기아, 삼성물산 등이 상위 10위 안에 포함됐다.특히 금융업권 기업들이 전반적으로 높은 주주환원율을 보인 점이 눈에 띈다. 배당과 자사주 소각 등을 통해 적극적으로 주주 가치를 제고하려는 움직임이 활발하게 나타났다.반면 주주환원을 전혀 하지 않은 기업들도 다수 존재했다. 삼성바이오로직스, LG에너지솔루션, 두산에너빌리티, 한화오션, 알테오젠, 삼성중공업, 카카오페이 등 총 17개 기업은 지난해 주주환원 활동을 하지 않은 것으로 조사됐다.정유진 기자 jinjin@hankyung.com4일 금융권에 따르면 KB금융은 지난달 24일 밸류업(기업가치 제고) 전략의 일환으로 자사주 8500억원어치를 매입·소각하겠다고 발표했다. 그러면서 올해 배당가능이익 한도 때문에 1900억원어치는 내년에 취득해 없애겠다는 계획을 내놨다. 배당가능이익은 전년도 이익잉여금 중 배당과 자사주 매입에 쓰이지 않고 남은 금액을 말한다. 현재 상법에서는 배당가능이익을 초과하지 않는 선에서 자사주를 매입·소각하도록 돼 있다. 국내 은행계 금융지주가 배당가능이익이 부족해 자사주 매입을 다음해로 미룬 것은 지난해 JB금융(310억원)에 이어 이번이 두 번째다.KB금융은 지난해 10월 발표한 밸류업 계획에 따라 올해 보통주자본비율(CET1) 13%를 초과하는 자본은 모두 주주환원에 쓰기로 했다. 그런데 CET1(6월 말 13.74%)이 예상 이상으로 오르면서 준비된 재원만으로는 약속한 규모로 주주환원을 하기 어려운 상황이 발생했다. 나상록 KB금융 최고재무책임자(CFO)는 “은행과 증권 등 계열사 중간배당 등을 통해 배당가능이익을 늘리는 방안을 검토하고 있다”며 “1900억원어치 자사주 매입이 해를 넘기더라도 이 내용과 별도로 내년 주주환원 규모를 산정할 것”이라고 말했다.자사주 소각 때문에 주요 주주 지분율이 상승해 법에서 허용하는 한도를 넘길 수 있다는 문제도 여전하다. 삼양사는 6월 30일 JB금융 주식 12만5000주를 처분해 지분율을 14.37%에서 14.30%로 낮췄다. JB금융의 자사주 매입·소각으로 지분율이 금융지주회사법상 한도인 10%(지방금융지주는 15%)를 넘기는 것을 방지하기 위해 내린 결정이다. OK저축은행도 같은 이유로 지난달 8일 계열사인 OK캐피탈에 iM금융 주식을 매각해 지분율을 9.7%에서 7.92%로 떨어뜨렸다.정부가 혁신기업과 중소·벤처기업, 소상공인에게 더 많은 자금을 공급하라고 요구해 금융지주의 주주환원 계획에 차질이 생길 가능성도 있다. 금융권 관계자는 “비교적 위험가중치가 높은 기업 대출을 대거 늘리면 주주환원 기준이 되는 CET1 관리가 어려워질 수 있다”고 말했다.김진성 기자 jskim1028@hankyung.com<앵커> 오늘 금융지주 주가가 오전에 잠시 조정받는 듯했는데 KB금융 제외하곤 낙폭을 줄여가는 모습입니다. 앞서 최민정 기자 언급한 자사주 의무 소각 관련해 금융지주들에는 어떤 영향이 있을지 경제부 유주안 기자와 이야기 나눠봅니다. 금융지주들은 자사주 매입과 소각에 꽤 적극적인데, 보유중인 자사주의 비중은 어떻습니까?<기자>4대 금융지주 자사주 보유 현황(KB 4.54%, 신한 2.09%, 하나 3.77%, 우리 1.16%)은, 보시다시피 비중이 크다고 보이진 않습니다.자사주 소각 의무화 추진에 따른 수혜주로 꼽히는 미래에셋(22.98) 대신(25.12) 신영(52.58%) 등에 비하면 매우 작은 수준이고요, 일반지주사들(티와이홀딩스 29.79%, SK 24.8%, 롯데지주 27.37% 등)에 비해서도 비중이 낮습니다.과거 역사를 살펴보면 금융주에 있어서는 자사주 ‘지배의 도구’보다는 인수합병 때 주식교환을 하기 위해, 전략적 투자자와 주식을 스왑하는 차원에서 일정 부분 보유해왔던 것을 알 수 있고요, 최근 들어서는 매입하면 바로 소각해서 주식의 가치를 올리는, 주주환원의 수단으로 자사주를 활용해 왔습니다.따라서, 자사주 소각 의무화에 따른 강제성 측면에서 금융지주에 미치는 단기적 직접적 영향은 크지 않겠습니다. 중장기적으로 볼 때 금융지주의 주주환원에 보다 힘이 실릴 것이란 기대감으로 이어질 수 있는데요,정책이 추구하는 목표를 이미 금융지주사들이 실행해 옮기고 있는 것이고, 향후 상장사들 사이에 자사주 매입소각이 보편화되면 재무적 여력과, 주주환원에 대한 강한 의지를 가진 금융사들이 더 적극적인 주주환원을 펼칠 수 있는 배경이 될 수 있을 것입니다.또한, 정부가 함께 추진중인 배당소득 분리과세 정책은 배당성향이 높고, 분기배당에 적극적인 금융주에게 특히 긍정적인 정책으로 받아들여지고 있습니다.<앵커> 어제 삼성전자 실적으로 인해 다소 가라앉은 분위기로 어닝시즌 개막되었는데요. 금융주 실적은 어떨 걸로 전망됩니까?<기자> 4대 지주만 놓고 볼 때, 당초 2분기는 좀 쉬어갈 것으로 예상이 되었습니다. 이는 2024년 2분기에 실적이 워낙 좋았던 것에 대한 기저효과와 더불어, 시중금리가 내려가면서 이자이익이 축소될 것으로 예상되었기 때문입니다.에프앤가이드 취합 컨센서스로 보면 KB금융의 2분기 당기순이익이 전년동기대비 약 5% 감소한 1조 6300억원, 우리금융지주 약 9% 감소한 8700억원으로 전망이이미지 크게보기\n\n\n\n                15일 금융정보업체 에프앤가이드에 따르면 4대 금융지주의 지난 2분기 순이익 추정치는 총 5조80억원이다. 작년 2분기(5조1241억원)와 비교해 1161억원(2.3%) 줄어든 규모다.4대 금융지주의 분기 단위 순이익이 전년 동기 대비 감소한 것은 작년 1분기(-6910억원) 이후 처음이다. 작년 1분기엔 4대 시중은행(국민·신한·하나·우리)이 홍콩 H지수 ELS 배상을 위해 총 1조3174억원을 일회성 비용인 충당부채로 적립한 영향으로 금융지주 실적이 줄었다. 홍콩 ELS 배상이라는 일회성 비용을 제외하면 4대 금융지주의 합산 순이익이 전년 동기 대비 감소한 것은 2023년 4분기(-3458억원) 이후 1년6개월 만에 처음이다.2분기엔 별다른 일회성 비용이 발생하지 않았는데도 실적이 줄어든 것으로 추정되는 것은 이자수익 감소세가 본격화했기 때문이다. 에프앤가이드에 따르면 KB금융의 이자수익은 작년 2분기 7조6116억원에서 올 2분기 7조5600억원으로 516억원(0.7%) 감소한 것으로 추정된다. 같은 기간 하나금융의 이자수익도 6조36억원에서 5조7800억원으로 4.7% 줄어들고, 우리금융은 5조4184억원에서 5조3620억원으로 1% 축소됐을 것으로 추산된다. 신한금융의 이자수익 추정치는 집계되지 않았다.업계에서는 올해 2분기를 시작으로 금융지주의 분기별 실적이 본격적인 감소세에 접어들 것이란 전망이 많다. 기준금리 인하로 핵심 수익성 지표인 순이자마진(NIM)이 하락하는 가운데 정부가 강력한 가계대출 억제 정책을 펼치고 있어 대출을 늘리기 어렵기 때문이다. 정부는 지난달 27일 발표한 ‘가계부채 관리 방안’(6·27 부동산 대책)을 통해 올 하반기부터 가계대출 증가량 목표치를 당초 계획 대비 50% 수준으로 줄이겠다고 밝혔다.한 금융지주 여신 담당 임원은 “금융지주들이 모두 공격적인 기업가치 제고(밸류업) 계획을 내놓은 가운데 경기 침체가 심화하고 있어 밸류업에 불리한 기업대출을 확대하기가 쉽지 않은 노릇”이라며 “양적 성장보다 내실을 다지는 방향으로 나아갈 것”이라고 말했다.4대 금융지주는 오는 24일 KB금융이, 25일 신한·하나·우리금융이 2분기 실적을 발표한다. 상반기 기준으로는 작년 실적을 끌어내린 홍콩 H지수 ELS 배상과 관련한 기저효과로 올해 실적이 전년 대비 개선됐을 것으로 추정된다.정의진 기자 justjin@hankyung.com◆ 최근 애널리스트 분석의견- 갈수록 돋보일 고배당 매력 - NH투자증권, BUY07월 09일 NH투자증권의 정준섭 애널리스트는 우리금융지주에 대해 "\'25년 2분기 지배순이익은 다소 부진할 예정. 경상 실적(이자이 익, 비이자이익)은 견조하나, 책준형 신탁 충당금 등으로 대손비용률 상승 (65bp, +20bp q-q, +21bp y-y)이 예상되기 때문. 우리금융지주는 하반기 자사주 매입 기대감은 낮지만, 배당 매력은 갈수록 돋보일 전망"이라고 분석하며, 투자의견 \'BUY\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.우리금융지주 등을 편입하고 있다. 강대권 라이프자산운용 대표는 “주주환원과 배당 확대는 앞으로 수년간 국내 증시의 주요 테마가 될 것”이라며 “액티브 ETF는 펀드매니저가 종목을 관리하고 장기 수익을 목표로 하기 때문에 퇴직연금에 편입하기 좋은 상품”이라고 설명했다.태광산업에 대한 행동주의로 주목받은 트러스톤자산운용의 대표 상품은 ‘TRUSTON 주주가치액티브’(올해 수익률 40.97%)다. 태광산업을 비롯해 NH투자증권, 현대엘리베이터, KB금융, 삼성카드, 키움증권 등에 투자한다. ‘HANARO 주주가치성장코리아액티브’(33.59%)도 같은 테마로 시장에서 주목하는 ETF 가운데 하나다.헤지펀드의 강자 타임폴리오자산운용은 미국 증시에 투자하는 액티브 ETF에서 경쟁력을 과시하고 있다. AI 관련주에 집중 투자하는 ‘TIMEFOLIO 글로벌AI인공지능액티브’ ‘TIMEFOLIO 미국나스닥100액티브’ 등이 대표적이다.최만수 기자 bebop@hankyung.comBBIG에서 지금조방원으로, 코스피 주도주의 변화\r\n                                \n\n\n\n28일 서울 여의도 한국거래소에 삼성전자 종가가 70,400원을 나타내고 있다. 이날 코스피 지수는 전장보다 13.47포인트(0.42%) 오른 3,209.52에 거래를 마쳤다. 25.7.28 /한국경제신문 이솔 기자‘신고가’의 계절이다. 지난 6월 한 달에만 상장주 5개 종목 중 1개꼴로 52주 신고가를 갈아치웠다. 코스피는 연초 대비 32.72% 상승하며 3300선 돌파를 목표로 하고 있다. 혹자는 “코스피200에서 눈감고 골라도 수익이 나는 장세”라고 말할 정도다.그런데 이상하다. 코스피지수가 역사적 고점을 향해가고 있지만, 웃지 못하는 이들이 많다. ‘국민주’ 삼성전자가 지난 28일 간만에 기지개를 켜며 7만 원대를 회복했지만, 2021년 고점에 물린 개미 투자자 상당수는 여전히 손실 구간에 머물러 있다.NH투자증권에 따르면 해당 플랫폼 기준 삼성전자 보유자 중 손실은 본 투자자는 무려 62.11%에 달한다. 한때 ‘차세대 국민주’로 주목받았던 카카오(손실 투자자 비율 89.09%)와 네이버(81.24%), LG화학(84.59%) 등도 상황은 비슷하다. “20년 만에 진짜 랠리가 왔다는데 내 계좌는 왜 이 모양일까.”유동성 장세와 정책 장세사진=우리금융지주\n\nNH투자증권은 8일 우리금융지주에 대해 "연말로 갈수록 고배당 매력이 부각될 것"이라며 목표주가를 기존 2만3000원에서 2만9000원으로 상향 조정했다. 투자의견은 \'매수\'를 유지했다.이 증권사 정준섭 연구원은 "올 1~4분기 균등 배당을 시행하는 타사와 달리 우리금융지주는 4분기 주당배당금(DPS) 비중이 커 기말 예상 배당수익률(2.9%)도 높다"며 "게다가 결산 배당부터 감액 배당 도입에 따라 개인투자자가 체감하는 배당수익률은 더 높아질 것"으로 내다봤다.우리금융지주가 올 하반기 자사주를 매입할 가능성은 낮다고 정 연구원은 판단했다. 보험사 인수와 경쟁사 대비 열위한 자본비율 등 고려할 사안이 많기 때문이란 설명이다.정 연구원은 "동양생명·ABL생명 계열사 편입으로 염가매수차익 발생이 예상된다"며 "하지만 자본과 보험계약마진(CSM), 염가매수차익은 자본 효율화 과정에서 변동될 여지가 있다"고 말했다.그러면서 "단기 호재보다는 중장기 금융 포트폴리오 구축과 비이자이익 개선 관점에서 긍정적 요인"이라고 덧붙였다.고정삼 한경닷컴 기자 jsk@hankyung.com[커버스토리] 2025 밸류업 CEO 50\n\n\n\n\n\n\n\n\n\n\n\n<2025 밸류업 CEO 50 - 금융>11위 임종룡 우리금융지주업종명 금융지주취임일 주가(원) 11,010     최근 주가(원) 21,350     취임일 2023년 3월 24일주가수익률 93.9%배당수익률 21.8%총주주수익률 115.7%12위 빈대인 BNK금융지주업종명 금융지주취임일 주가(원) 6,250     최근 주가(원) 11,790     취임일 2023년 3월 17일주가수익률 88.6%배당수익률 20.5%총주주수익률 109.1%13위 양종희 KB금융업종명 금융지주취임일 주가(원) 54,100     최근 주가(원) 106,500     취임일 2023년 11월 21일주가수익률 96.9%배당수익률 10.4%총주주수익률 107.2%14위 정종표 DB손해보험업종명 보험취임일 주가(원) 65,300     최근 주가(원) 120,200     취임일 2023년 1월 1일주가수익률 84.1%배당수익률 18.5%총주주수익률 102.6%15위 김성태 기업은행업종명 은행취임일 주가(원) 9,560     최근 주가(원) 17,290     취임일 2023년 1월 3일주가수익률 80.9%배당수익률 21.4%총주주수익률 102.3% 16위 함영주 하나금융지주업종명 금융지주취임일 주가(원) 49,350     최근 주가(원) 80,000     취임일 2022년 3월 25일주가수익률 62.1%배당수익률 22.8%총주주수익률 84.9%17위 진옥동 신한지주업종명 금융지주취임일 주가(원) 35,750     최근 주가(원) 59,300 취임일 2023년 3월 23일주가수익률 65.9%배당수익률 13.5%총주주수익률 79.4%18위 박종문 삼성증권업종명 증권취임일 주가(원) 41,550     최근 주가(원) 67,700     취임일 2024년 3월 21일주가수익률 62.9%배당수익률 8.4%총주주수익률 71.4%19위 윤병운 NH투자증권업종명 증권취임일 주가(원) 12,350     최근 주가(원) 19,170     취임일 2024년 3월 27일주가수익률 55.2%배당수익률 7.7%총주주수익률 62.9%20위 박봉권 교보증권업종명 증권취임일 주가(원) 6,770     최근 주가(원) 8,450     취임일 2020년 2월 4일주가수익률 24.8%배당수익률 28.1%총주주수익률 52.9%KB금융이 최대 8천억원, 신한과 하나가 각 3~4천억원, 우리 1500억원, 도합 1조6천원에 달하는 자사주 소각 파티를 벌일 것으로 기대하고 있습니다.배당과 자사주 매입소각 합친 총주주환원율이 올해 50% 넘어가는 케이스도 탄생할지 관전포인트입니다.<앵커> 그간 주가가 많이도 올랐는데, 향후 추가 상승을 기대해볼 수 있나요?<기자> 2분기 이후 4대 금융지주 주가는 일제히 40% 이상 올랐습니다.워낙 국내 증시 저평가 되어있다보니 주식시장에서 장부가 만큼만이라도 평가를 받으라는 의미에서 PBR 1배가 목표치로 설정되어 있는데요, 주가가 45% 올랐어도 KB금융의 PBR이 0.7배 수준입니다. 나머지 3곳은 장부가 절반의 가치밖에 인정을 못 받고 있습니다.따라서 오늘 주가 하락에 대해서는 금융권 안팎과, 기업분석하는 증권업계 쪽에선 최근 급등에 따른 단기조정의 성격으로 파악을 하고 있습니다.마지막으로 4곳 중 어디가 가장 좋을 것이냐도 궁금하실텐데. KB금융이 실적과 주주환원 측면에서 압도적일 것으로 예상되고 주가 측면에서도 1위 프리미엄이 지속될 것이란 전망이 있는 동시에 또다른 측면에선 키맞추기가 이뤄질 것으로 예상하기도 합니다.  KB가 0.7배 수준까지 올랐으니, 2~4위권이 부지런히 키맞추기를 위해 올라올 것으로 기대하는 시각도 있습니다.<네 잘 들었습니다>유주안기자 jayou@wowtv.co.kr◇하이닉스·KB금융…실적 ‘슈퍼위크’22일 금융정보업체 에프앤가이드에 따르면 증권사 세 곳 이상이 내놓은 상장사 100곳의 올해 2분기 영업이익 추정치는 총 39조5944억원인 것으로 집계됐다. 한 달 전 같은 곳을 대상으로 추정한 금액(42조3291억원)보다 6.4% 감소했다. 올 초(44조4976억원)와 비교해선 11%가량 낮아진 수치다. 주요 종목의 2분기 실적 발표가 줄줄이 예고된 가운데 종목별 ‘옥석 가리기’가 중요해진 배경이다.새로운 반도체 대장주 SK하이닉스는 24일 2분기 실적을 발표한다. SK하이닉스의 2분기 실적 컨센서스(증권사 추정치 평균)는 매출 20조6109억원, 영업이익 9조199억원이다. 전년 동기 대비 매출과 영업이익이 각각 25.5%, 64.9% 급증했을 것으로 관측됐다. 3개월 전 영업이익 추정치(7조8988억원)와 비교해 시장의 눈높이가 대폭 높아졌다.전문가들은 SK하이닉스가 무난히 사상 첫 분기 영업이익 9조원 시대를 열 것으로 보고 있다. 호실적 기대를 높이는 일등 공신은 고대역폭메모리(HBM)다. 손인준 흥국증권 연구원은 “메타 등 전방업체의 경쟁 심화, 엔비디아의 중국 수출 허가 등 계속해서 확인되는 인공지능(AI) 수요 강세 신호를 감안하면 HBM 경쟁 심화 및 가격 하락 우려는 지양할 필요가 있다”고 말했다.새 정부 출범 후 주도주로 자리매김한 금융주는 24일 KB금융을 시작으로 25일 신한·하나·우리금융 등이 잇달아 실적을 내놓는다. 4대 금융지주의 2분기 순이익은 총 5조1118억원으로 전년 동기(5조1687억원)보다 1.1% 감소했을 것으로 추정됐다. 자사주 매입·소각 등 주주환원 규모가 시장 기대를 충족할지도 관심사다. ◇탄력받는 조선·방산·원전올해 국내 증시의 상승장을 이끈 조선·방산·원전주는 2분기 실적 발표를 계기로 한층 탄력받을 것이란 전망이 많다. 한화오션(29일 실적 발표)의 2분기 영업이익 추정치는 한 달 전보다 6.8% 늘어났다. 3개월 전보다는 64.1% 급증했다.한화에어로스페이스, 현대로템, 한국항공우주산업, LIG넥스원 등 대형 방산업체 4곳의 2분기 영업이익 추정치는 1조1049억원으로, 역대 처음 분기 영업이익 1조원 시대를 열 전망이다.한 달 전보다 2분기 영업이익 추정치가 가장 많이 늘어난 방산주는 풍산(10.9%)이다. 한화시스템(3.4%) 한화에어로스페이스(2.4%) 등이 뒤를 이었다.원전 대장주 두산에너빌리티는 25일 2분기👀주목할 만한 보고서 에코프로비엠-소형/ESS 호조와 일회성 이익으로 컨센서스 상회📈목표주가 : 13만원→15만원(상향) / 현재주가 : 12만4500원   투자의견 : 매수(유지) /  KB증권[체크 포인트]- 2분기 실적 매출액 7,797억원 (-4% YoY), 영업이익 490억원(+1,159% YoY, 영업이익률 6.3%)으로 컨센서스 상회.- 3분기 실적은 매출액 7,726억원 (+48% YoY), 영업이익 371억원(흑자전환, 영업이익률 4.8%)으로 기대. IRA 종료로 인해 북미 EV향 판매는 소폭 감소할 것으로 예상. 다만 소형전지/ESS향은 수요 강세 흐름이 지속될 것으로 전망. 2분기에 이어 인도네시아 투자활동 이익과 재고평가손실 충당금 환입이 예상되어 수익성도 양호할 것.- 전방 고객의 EV/소형전지/ESS향 판매 증가 등을 고려해 2026E~2030E 평균 영업이익률 기존 4.8%에서 5.4%로 상향 조정. 우리금융지주-가장 높은 배당수익률📈목표주가 : 2만2000원→3만1000원(상향) / 현재주가 : 2만4900원   투자의견 : 매수(유지) /  유안타증권[체크 포인트]- 2분기 지배주주순이익은 9,346억원으로 컨센서스를 12.6% 상회. 컨센서스를 상회한 이유는 벤처캐피탈 자회사에서 투자한 달바글로벌 평가이익 470억원 및 지점매각익 100억원이 영업외손익에 반영됐기 때문.- 2025년 자사주 1,500억원을 매입을 진행했으며 추가적인 자사주 매입은 없을 것으로 판단.- 우리금융지주는 자본잉여금을 이익잉여금으로 이입해 비과세 배당 실시 발표. 3조원 수준으로 3~4년간의 주주환원 재원으로 활용될 전망. 해당 비과세 배당은 2025년 결산 배당부터 적용될 전망. 결산배당을 비과세 시 배당수익률은 5.7%로 커버리지 은행 중 가장 높은 수준.- 올해 CET-1 비율 12.5% 초과 달성으로 내년부터는 35%가 넘는 총주주환원율이 기대. 2) 비과세 배당을 통한 높은 배당수익률은 경쟁사와 차별화된 투자 포인트로 작용할 것. 3) 증권 및 보험 자회사의 이익기여도 확대가 기대. BNK금융지주-대손비용 우려는 완화되고 있다📈목표주가 : 1만4500원→1만8000원(상향) / 현재주가 : 1만4410원   투자의견 : 매수(유지) /  유안타증권[체크 포인트]- 2분기 지배주주순이익은 3,092억원으로 컨센서스를 26.5% 실적을 기록. 디지털타워 매각으로 일회성 이익 약 540억원이 반영◆ 주체별 매매동향- 전일 외국인 대량 순매수지난 한달을 기준으로 보면 외국인이 490.4만주를 순매수했고, 개인들도 15.8만주를 순매수했다. 하지만 기관은 470.8만주를 순매도했다. 같은 기간 이 종목의 거래 비중은 외국인과 개인이 각각 52.6%, 24.3%로 비중이 높다.한편 외국인은 이 종목에 대해서 최근 3일 연속 29.4만주 순매수를 하고 있다. 더욱이 전일 외국인이 대량 순매수를 하고 있어 투자자들의 관심이 집중되고 있다.[그래프]우리금융지주 외국인/기관 매매동향\n\n\n\n\n\n\n\n\n\n\n\n◆ 최근 애널리스트 분석의견- 2Q25 Preview: 시간이 더 필요하다 - 상상인증권, BUY(신규)07월 03일 상상인증권의 김현수 애널리스트는 우리금융지주에 대해 "2분기 실적은 컨센서스를 소폭 상회할 전망. 동양 ABL생명 편입 완료, CET1 비율 하락은 제한적. 여전히 낮은 CET1 비율, 주주환원 확대는 시간이 필요할 예정: 1분기 말 기준 CET1 비율은 12.4%로, 지난해 말(12.0%) 대비 소폭 개선됐지만 내부 목표치인 13.0%에는 여전히 미치지 못하는 수준이다. 2분기 중 원·달러 환율 하락으로 약 18bp의 자본여력이 추가될 것으로 예상되나, 최근 편입된 보험사의 운영에 따른 자본소요를 감안할 때, 적극적인 주주환원 확대는 시간이 필요할 것으로 판단된다."이라고 분석하며, 투자의견 \'BUY(신규)\', 목표주가 \'30,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.6일 투자은행(IB)업계에 따르면 하나금융은 이달 29일 2700억원 규모의 신종자본증권(AA-)을 발행을 앞두고 20일 수요예측에 나설 예정이다. 기관 투자가의 높은 수요를 예상해 최대 4000억원까지 한도를 열어뒀다. 금리는 연 3%대 초반을 예상하고 있다.기업은행도 3000억원 규모의 후순위채권(AA+) 발행에 대한 이사회 결의를 마친 뒤 곧 수요예측에 들어갈 예정이다.신한지주, 우리금융지주, BNK금융지주 등도 지난달 이사회 결의를 열고 자본성증권 발행을 결정했다. 신한지주는 신종자본증권(AA-) 2700억원을 발행해 운영자금으로 400억원, 채무상환자금으로 2300억원을 사용할 예정이다. 우리금융지주는 2700억원 규모의 신종자본증권(AA-)을 발행해 운영자금에 700억원, 채무상환에 2000억원을 투입한다. BNK금융지주는 1050억원 규모의 신종자본증권(AA-)을 발행해 모두 운영자금에 사용한다.이들 금융지주들은 증권사와 보험사, 캐피탈사 등도 거느리고 있다. 증권사의 자기자본을 확대하고, 보험사의 지급여력 개선 등에도 해당 자금이 사용될 예정이다. 신용도가 높은 금융지주사가 대량으로 자금을 조달한 뒤 각 계열사에 투입해 재무건전성을 높이는 역할이다.보험사들도 금융당국의 새로운 자본규제를 앞두고 자금 조달에 나서고 있다. DB손해보험은 다음 달 1일 5000억원 규모의 기본자본 신종자본증권(AA) 발행을 계획하고 있다. 희망 금리는 최대 3.8%로 책정했다.보험사의 자본은 손실흡수성에 따라 기본자본(Tier1, 자본금·이익잉여금 등)과 보완자본(Tier2, 후순위채권 등)으로 나뉜다. 금감원은 보험사의 자본 건전성을 강화하기 위해 기본자본 지급여력(K-ICS·킥스)비율을 새 자본규제 지표로 도입할 방침이다. ◇ 높은 수익률에 국고채 대비 선호시중은행들은 지난해 자본성증권 약 4조7700억원을 발행했다. 지난 5년 동안 발행한 자본성증권은 총 21조5850억원, 연평균 4조3000억원 규모다. 보험사도 지난해 약 8조3250억원의 자본성증권을 발행하며 자본을 확충했다.금융지주사의 자본성증권 발행이 활발해지면서 스프레드는 축소되는 추세다. 지난 6월 발행된 우리은행의 10년 만기 후순위채의 스프레드는 0.44%포인트로 역대 최저 수준을 기록했다.스프레드는 회사채 수익률과 동일 만기 국고채 수익률 간 금리차를 뜻한다. 이는 해당 기업의 신용도가 높다는 뜻으로, 투자자[한경ESG] 지속가능경영 보고서 CEO 말말말 - 4대 금융지주 \n\n\n\n\n\n“KB금융그룹은 ‘세상을 바꾸는 금융’이라는 사명을 바탕으로 금융의 본질을 넘어 더 멀리 보고 더 깊이 고민하겠습니다.”양종희 KB금융그룹 회장 세상을 바꾸는 금융[1] KB금융그룹은 고객에게는 신뢰할 수 있는 금융, 주주에게는 장기적 성장 가능성을 제시하는 기업, 지역사회에는 함께 성장하는 든든한 동반자가 되는 것을 진정한 가치로 삼아 최선을 다하고 있습니다. [2] 금융은 단순한 자금 중개를 넘어 개인의 삶과 기업의 미래, 나아가 사회 전체의 지속가능성을 연결하는 중요한 기반입니다. 금융의 본질적 역할을 되새기며, 다음 세대에게 더 나은 환경과 기회를 전하는 책임을 다하고자 합니다.[3] KB금융그룹은 기후 위기, 저출생, 지역 소멸, 일자리 문제 등 우리 삶을 위협하는 문제를 외면하지 않고, 금융 본업의 역량을 발휘해 사회와 함께하는 따뜻한 파트너십을 실천해왔습니다. 또 돌봄과 소상공인 지원 등 의미 있는 사회적가치를 창출하고, 이웃과 사회와의 관계를 균형 있게 헤아리며 공존을 추구하고자 했습니다.[4] 앞으로도 KB금융그룹은 고객의 신뢰와 사회의 기대를 가장 소중한 자산으로 여기며, 국민 모두의 성장이 KB의 성장으로 이어지는 지속가능한 길을 함께 만들어가겠습니다.◆ 최근 애널리스트 분석의견- 장기 보유 매력 유효 - 미래에셋증권, 매수07월 14일 미래에셋증권의 정태준 애널리스트는 우리금융지주에 대해 "투자의견 매수로 상향, 목표주가 29,000원으로 상향. 주주환원 매력 배가 예상. 2분기 지배주주순이익은 컨센서스에 부합하는 8,477억원을 예상"이라고 분석하며, 투자의견 \'매수\', 목표주가 \'29,000원\'을 제시했다.한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.외국인 투자자는 08일 거래소에서 이수페타시스, 삼성중공업, SK하이닉스 등을 중점적으로 사들인 것으로 나타났다.외국인 투자자의 순매수 상위 20개 종목은 이수페타시스, 삼성중공업, SK하이닉스, 하나금융지주, 삼양식품, HD현대, KB금융, 신한지주, 동양철관, 현대차등이다.이중에 전기,전자 업종에 속한 종목이 3개 포함되어 있다.이수페타시스, 삼성중공업, SK하이닉스 등은 전일 대비 주가가 상승했고, POSCO홀딩스, LG화학 등은 주가가 하락했다.[07월08일]거래소 외국인 순매수 상위 종목한경로보뉴스이 기사는 한국경제신문과 금융 AI 전문기업 씽크풀이 공동 개발한 기사 자동생성 알고리즘에 의해 실시간으로 작성된 것입니다.서울 시내에 설치된 시중은행 ATM 기기 모습. 2024.12.30/뉴스1국내 주요 금융지주들의 2분기 실적 전망이 상반된 모습을 보이고 있다.21일 금융정보업체 에프앤가이드에 따르면 4대 금융지주(KB·신한·하나·우리)의 2분기 당기순이익은 총 5조 1118억원으로 전년 동기(5조 1687억원)보다 1.1% 감소할 것으로 전망된다.KB금융은 2분기 순이익이 1조 6413억원으로 작년 2분기(1조 7107억원)보다 4.1% 감소할 것으로 예상된다.이는 지난해 1분기 홍콩 H지수 주가연계증권(ELS) 손실 배상에 따른 대규모 충당금이 반영된 기저효과 때문이다. H지수가 반등하면서 충당금 환입이 발생했기 때문에 지난해 2분기 실적이 유독 양호했다. 이런 기저효과로 인해 올해 2분기 실적은 자연스럽게 줄어들 수밖에 없다는 분석이다.우리금융지주는 2분기 순이익이 8784억원으로 1년 전 9615억원보다 8.6% 감소할 것으로 예상된다.우리금융은 최근 우리투자증권 출범 후 모바일 트레이딩 시스템(MTS) 개발, 신규 인력 채용 등으로 상당한 판매관리비를 지출했다. 이러한 비용이 실적에 부정적인 영향을 미친 것으로 분석된다.반면 신한금융지주는 지난해 2분기 1조 4510억원에서 올해 2분기 1조 4700억원으로 순이익이 1.3% 증가할 것으로 전망된다.같은 기간 하나금융지주 순이익은 1조 456억원에서 1조 1221억원으로 7% 이상 늘어날 것으로 예상된다. 하나금융은 신용카드, 증권 중개, 운용리스 등 수수료 수익이 양호한 흐름을 이어가고 있으며, 환율 하락에 따른 외화 환산 이익이 실적 개선을 이끌고 있다.4대 금융지주의 올해 상반기 또는 연간 기준 순이익은 사상 최대 규모를 기록할 가능성이 큰 것으로 전망된다.특히 이들의 연간 순이익은 총 18조원에 육박할 것으로 예상된다. KB금융은 지난해 5조 286억원에서 올해 5조 6152억원으로 11.7% 신한금융은 4조 5582억원에서 5조845억원으로 11.5%, 하나금융은 3조 7685억원에서 4조 158억원으로 6.6% 성장할 것으로 보인다.반면 우리금융은 동양생명과 ABL생명까지 품은 결과 일회성 비용 증가로 순이익이 지난해 3조 1715억원에서 올해 3조 1095억원으로 소폭 줄어들 것으로 예상된다.4대 금융지주의 순이익 합계는 지난해 16조 5268억원에서 올해 17조 8250억원으로 8% 가까이 증가할 전망이다.정부의 고강도 부동산 대출 규제에도 불구하고 주요결론부터 말하자면 주도주가 바뀌었다.2021년 시장을 지배했던 ‘BBIG’(배터리·바이오·인터넷·게임)는 힘을 잃었다. 2025년의 시장은 ‘지금조방원’(지주회사·금융·조선·방산·원자력)과 ‘ABCDE’(AI·바이오·문화·방산·에너지)의 무대다.코스피 3000 시대를 이끌었던 2021년과 3200선으로 끌어올린 2025년의 주도주를 비교 분석했다. 2021년은 팬데믹 저점이었던 코스피 1457.64(2020년 3월 19일)부터 사상 최고치인 3305.21(2021년 7월 6일)을 기록할 때까지의 구간이다. 상승률은 126.75%. 전례 없는 유동성과 기업 펀더멘털 개선이 맞물린 결과였다. 박스권에 갇혀 있던 국내 증시가 근 18년 만에 구조적 상향 돌파를 이룬 시기로 평가된다.반면 2025년의 상승은 정책 주도형 랠리다. 새 정부의 증시 부양 기조와 거버넌스 개혁 기대가 주가를 끌어올리고 있다.두 시기를 대표하는 코스피 시가총액 상위 50개 종목의 주가 상승률을 비교 분석해 ‘과거의 주도주’와 ‘현재의 주도주’가 어떻게 달라졌는지 분석한 결과, 2025년의 장세는 지주회사, 금융, 조선, 방산, 원자력 등 이른바 ‘지금조방원’이 이끌었다.가장 높은 상승률을 기록한 종목은 현대로템이다. 올해 1월 초 4만9700원이던 주가는 7월 말 19만9800원까지 오르며 302.01% 급등했다. 폴란드와 체결한 K2 전차 등 방산 수출 기대와 글로벌 지정학적 리스크 확대가 주가를 밀어올렸다.두산에너빌리티(289.74%)는 지난 정부의 원전 정책 정상화로 반등에 성공한 이후 최근 AI 산업 확산에 따른 전력 수요 증가로 다시 주목받았다. 한화에어로스페이스(185.84%)

In [339]:
len(chunk_total)

37824

In [340]:
result_df_chunk = summarize_top_articles_2(chunk_total,ticker=test_ticker,max_iters=5)

summart : ✅ 주요 요약
- 4대 금융지주, 2분기 순이익 전년 대비 감소
  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 감소했으며, 이는 이자수익 감소와 가계대출 억제 정책으로 인한 결과로 분석됨.

- 금융지주, 주주환원 정책 강화
  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.

- 정부의 부동산 대출 규제와 증시 친화 정책
  정부의 부동산 대출 규제에도 불구하고 금융지주들의 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.

🔑 키워드
- 4대 금융지주
- 순이익 감소
- 이자수익
- 가계대출 억제
- 주주환원 정책
- 자사주 매입
- 부동산 대출 규제
- 증시 친화 정책
[should_stop] Iteration: 0
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약 내용이 원문 기사와 일부 일치하지 않으며, 특히 금융지주의 순이익 증가에 대한 부분이 잘못 전달됨] </reason>
- 포괄성: 부족함 <reason> [기사의 중요한 정보 중 일부가 누락되었으며, 특히 정부의 정책 변화와 이에 따른 금융지주의 대응 전략이 충분히 다루어지지 않음] </reason>
- 간결성: 좋음 <reason> [요약은 간결하게 작성되어 있으며, 불필요한 정보가 포함되지 않음] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있음] </reason>
- 일관성: 부족함 <reason> [특정 종목에 대한 내용이 아닌, 전체 금융지주에 대한 내용임에도 불구하고 일관성이 부족함] </reason>

피드백:
1. 정확성을 높이기 위해 원문 기사에서 언급된 순이익 증가와 감소에 대한 정보를 정확히 반영해야 합니다. 특히, 금융지주의 순이익이 전년 대비 증가했다는 부분을 명확히 해야 합니다.
2. 포괄성을 개선하기 위해 정부의 부동산 대출 규제와 증시 친화 정책에 대한 자세한 설명을 추가해야 합니다. 또한, 금융지주들의 새로운 수익원 확보 전략에 대한 정보도 포함되어야 합니다.
3. 일관성을 유지하기 위해 요약의 초점을 금융지주 전체에 맞추고, 특정 종목에 대한 정보는 배제해야 합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n- 4대 금융지주, 2분기 순이익 전년 대비 증가\n  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 증가했으며, 이는 비이자수익의 증가와 환율 안정에 따른 외화환산이익 덕분으로 분석됨.\n\n- 금융지주, 주주환원 정책 강화\n  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.\n\n- 정부의 부동산 대출 규제와 증시 친화 정책\n  정부의 부동산 대출 규제에도 불구하고 금융지주들의 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.\n\n🔑 키워드\n- 4대 금융지주\n- 순이익 증가\n- 비이자수익\n- 환율 안정\n- 주주환원 정책\n- 자사주 매입\n- 부동산 대출 규제\n- 증시 친화 정책'
[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약에서 4대 금융지주의 순이익이 전년 대비 증가했다고 했으나, 원문에서는 순이익이 감소했다고 언급하고 있습니다. 이는 요약의 핵심 내용이 원문과 일치하지 않음을 의미합니다.] </reason>
- 포괄성: 부족함 <reason> [요약에서 정부의 부동산 대출 규제와 증시 친화 정책에 대한 언급은 있지만, 원문에서 다루는 다양한 금융 관련 이슈와 세부 사항들이 충분히 포함되지 않았습니다.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 핵심 사항을 간결하게 전달하고 있습니다.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있습니다.] </reason>
- 일관성: 부족함 <reason> [요약에서 특정 종목에 대한 내용만 존재하지 않고, 다양한 주제를 다루고 있어 일관성이 부족합니다.] </reason>

피드백:
- 정확성을 높이기 위해 원문 기사에서 언급된 순이익 감소와 관련된 내용을 정확히 반영해야 합니다.
- 포괄성을 개선하기 위해 원문에서 다루는 다양한 금융 이슈, 예를 들어 주주환원 정책의 구체적인 내용이나 금융지주들의 실적 전망에 대한 세부 사항을 추가하는 것이 좋습니다.
- 일관성을 유지하기 위해 요약의 초점을 명확히 하고, 특정 주제나 종목에 대한 내용을 중심으로 구성하는 것이 필요합니다.
[should_stop] next_step = no
====== result : refined_summary='✅ 주요 요약\n\n- 4대 금융지주, 2분기 순이익 감소\n  KB, 신한, 하나, 우리 등 4대 금융지주의 2분기 합산 순이익이 전년 동기 대비 감소했으며, 이는 이자수익 감소와 경기 침체로 인한 대출 자산 확대의 어려움 때문으로 분석됨.\n\n- 금융지주, 주주환원 정책 강화\n  4대 금융지주는 자사주 매입 및 소각을 포함한 주주환원 정책을 강화하고 있으며, 이는 주가 상승과 주주가치 제고에 긍정적인 영향을 미칠 것으로 예상됨.\n\n- 정부의 부동산 대출 규제와 증시 친화 정책\n  정부의 부동산 대출 규제에도 불구하고 금융지주들의 연간 실적 전망은 상향 조정되고 있으며, 이는 새로운 수익원 확보와 증시 친화적인 정책 덕분으로 분석됨.\n\n🔑 키워드\n- 4대 금융지주\n- 순이익 감소\n- 이자수익 감소\n- 주주환원 정책\n- 자사주 매입\n- 부동산 대출 규제\n- 증시 친화 정책'
[should_stop] Iteration: 2
[should_stop] Feedback:
 - 정확성: 부족함 <reason> [요약이 원문 기사와 완전히 일치하지 않음. 특히, 4대 금융지주의 순이익이 감소한 이유와 관련된 구체적인 내용이 부족함.] </reason>
- 포괄성: 부족함 <reason> [기사의 중요한 정보 중 일부가 누락되었음. 예를 들어, 금융지주의 비이자이익 증가와 관련된 내용이 포함되지 않음.] </reason>
- 간결성: 좋음 <reason> [요약은 불필요한 표현 없이 간결하게 작성됨.] </reason>
- 문장구성: 좋음 <reason> [문장이 자연스럽고 명확하게 구성되어 있음.] </reason>
- 일관성: 부족함 <reason> [요약이 특정 종목에 대한 내용만 존재하는 것이 아니라 다양한 정보를 포함하고 있음.] </reason>

피드백:
1. **정확성**: 원문 기사에서 4대 금융지주의 순이익 감소 이유에 대한 구체적인 내용을 더 명확하게 반영해야 합니다. 예를 들어, 이자수익 감소 외에도 비이자이익 증가와 같은 다른 요인들도 포함되어야 합니다.

2. **포괄성**: 금융지주의 비이자이익 증가와 정부의 정책 변화가 금융지주 실적에 미치는 영향 등 중요한 정보가 누락되었습니다. 이러한 정보를 포함하여 요약의 포괄성을 높일 필요가 있습니다.

3. **일관성**: 요약이 특정 종목에 대한 내용만 다루는 것이 아니라, 다양한 측면에서 정보를 제공해야 합니다. 이를 위해 관련 정보를 더 체계적으로 정리하여 일관성을 높여야 합니다.
[should_stop] next_step = no

KeyboardInterrupt:

In [270]:
print(result_df_chunk.summary.values[0])

✅ 주요 요약

- **SK하이닉스, 2분기 사상 최대 실적 기록**
  SK하이닉스는 2분기 매출 22조2320억원, 영업이익 9조2129억원을 기록하며 사상 최대 실적을 달성했다. 이는 AI 메모리 수요 증가와 D램 및 낸드플래시 출하량 증가에 기인한다.

- **HBM 시장에서의 경쟁 심화 우려**
  SK하이닉스는 HBM 시장에서의 독점적 지위가 경쟁 심화로 인해 위협받을 수 있다는 우려가 제기되고 있다. 삼성전자와 마이크론의 시장 진입이 예상되며, 가격 하락 가능성이 논의되고 있다.

- **SK하이닉스의 HBM 수요 성장 확신**
  SK하이닉스는 HBM 수요가 지속적으로 증가할 것이라고 확신하며, AI 시장에서의 핵심 제품으로서의 중요성을 강조하고 있다. 이에 따라 HBM 생산을 위한 투자를 확대할 계획이다.

- **주가 변동 및 외부 기관의 평가**
  SK하이닉스의 실적 발표 이후 주가는 일시적으로 상승했으나, 외부 기관의 평가에 따라 변동성을 보였다. 골드만삭스는 HBM 시장의 경쟁 심화로 인한 가격 하락 가능성을 지적하며 투자의견을 하향 조정했다. 반면, 다른 기관들은 SK하이닉스의 기술력과 시장 지배력을 긍정적으로 평가하며, 장기적인 성장 가능성을 강조했다.

🔑 키워드
- SK하이닉스
- 2분기 실적
- HBM 시장
- AI 메모리
- 경쟁 심화
- 가격 하락
- 투자 확대
- 주가 변동
- 외부 기관 평가

## 원문 그대로 vs chunking만 사용 비교
> 결론 : chunking된 문서만을 사용하는 게 유리?

[SK하이닉스]

1. 원문 그대로
- **외국인 투자자, 전기·전자 및 운수장비 업종에 집중 매수 및 매도**  <br>
  외국인 투자자들은 한화오션, SK하이닉스, 두산에너빌리티 등을 중점적으로 매수했으며, SK하이닉스, 카카오페이, NAVER 등을 매도했습니다. 특히, 전기·전자 업종에 속한 종목들이 다수 포함되어 있으며, 이들 종목의 주가 변동이 투자 전략에 영향을 미쳤습니다.<br>

- **기관 투자자, 전기·전자 및 운수장비 업종에 집중**  <br>
  기관 투자자들은 삼성전자, 현대차, 삼성전기 등 전기·전자 업종의 종목을 중점적으로 매수했으며, SK하이닉스, KODEX 200선물인버스2X 등을 매도했습니다. <br>이들 종목 중 일부는 전일 대비 주가가 상승했습니다.

- **코스피지수 상승, 투자자 고민 증가**  <br>
  코스피지수가 3200을 넘어섰지만, 주식 매입 시점을 고민하는 투자자들이 증가하고 있습니다. 기존 대장주들의 추가 상승 가능성과 이미 충분히 올랐다는 부담감이 동시에 작용하고 있습니다.

- **주요 종목의 주가 변동**  <br>
  한화오션, SK하이닉스, 두산에너빌리티 등은 전일 대비 주가가 상승했으며, 기아, 삼성전자, 현대차 등은 주가가 하락했습니다. 이러한 변동은 투자자들의 매수 및 매도 전략에 영향을 미치고 있습니다.


2. chunking된 문서만 사용
- **SK하이닉스, 2분기 사상 최대 실적 기록**<br>
  SK하이닉스는 2분기 매출 22조2320억원, 영업이익 9조2129억원을 기록하며 사상 최대 실적을 달성했다. 이는 AI 메모리 수요 증가와 D램 및 낸드플래시 출하량 증가에 기인한다.<br>

- **HBM 시장에서의 경쟁 심화 우려**<br>
  SK하이닉스는 HBM 시장에서의 독점적 지위가 경쟁 심화로 인해 위협받을 수 있다는 우려가 제기되고 있다. 삼성전자와 마이크론의 시장 진입이 예상되며, 가격 하락 가능성이 논의되고 있다.<br>

- **SK하이닉스의 HBM 수요 성장 확신**<br>
  SK하이닉스는 HBM 수요가 지속적으로 증가할 것이라고 확신하며, AI 시장에서의 핵심 제품으로서의 중요성을 강조하고 있다. 이에 따라 HBM 생산을 위한 투자를 확대할 계획이다.

- **주가 변동 및 외부 기관의 평가**<br>
  SK하이닉스의 실적 발표 이후 주가는 일시적으로 상승했으나, 외부 기관의 평가에 따라 변동성을 보였다. 골드만삭스는 HBM 시장의 경쟁 심화로 인한 가격 하락 가능성을 지적하며 투자의견을 하향 조정했다. 반면, 다른 기관들은 SK하이닉스의 기술력과 시장 지배력을 긍정적으로 평가하며, 장기적인 성장 가능성을 강조했다.<br>

# 과거 버전

In [204]:
import pandas as pd
from datetime import datetime, timedelta
# cross-encoder
from sentence_transformers import CrossEncoder
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from summary_function_openai import NewsSummaryAgent, build_summary_graph  # 너가 만든 것

# 1. 모델 준비 (CrossEncoder for Re-ranking) # 예시 모델 하나 생성
rerank_model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# 2. 최근 5일치 필터링 함수
def get_recent_articles(df: pd.DataFrame, ticker: str, days: int = 5):
    df['Date'] = pd.to_datetime(df['Date'])
    today = df['Date'].max()
    recent_df = df[
        (df['ticker'] == ticker) &
        (df['Date'] >= today - timedelta(days=days))
    ]
    return recent_df.sort_values(by="Date", ascending=False)

# 3. huggingface 모델 이용.
def rerank_articles(df: pd.DataFrame,ticker:str ,query: str, top_k: int = 5):
    task_df= df[df.ticker == ticker]
    docs = task_df['content'].tolist()
    # 모델 이용?? 
    pairs = [(query, doc) for doc in docs]
    scores = rerank_model.predict(pairs)
    
    task_df_2 = task_df.copy()
    task_df_2['score'] = scores
    return task_df_2.sort_values(by='score', ascending=False).head(top_k)

# 4. 전체 요약 실행 함수
def summarize_top_articles(df: pd.DataFrame, ticker: str, query: str, top_k: int = 5):
    recent_df = get_recent_articles(df, ticker)
    top_df = rerank_articles(recent_df, query=query,ticker=ticker, top_k=top_k)

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)

    results = []
    for _, row in top_df.iterrows():
        state = {
            "article": row['content'],
            "summary": "",
            "feedback": "",
            "iteration": 0
        }
        result = runnable.invoke(state)


        print("✅ 실행 결과 타입:", type(result))
        print("✅ 실행 결과 키 목록:", result.keys())
        print("✅ 실행 결과 전체 내용:", result)

        if "final_summary" not in result:
            print("❌ final_summary 키가 없습니다. 중단합니다.")
            continue  # 또는 raise Exception("final_summary 없음")

        print(f'실행 결과 : {result}')
        results.append({
            "ticker": row['ticker'],
            "date": row['Date'],
            "header": row['header'],
            "url": row['url'],
            "summary": result["final_summary"], 
             "feedback": result.get("last_feedback", "피드백 없음")
        })
    return pd.DataFrame(results)

In [55]:
query = "우리금융지주 관련 시황"
ticker = "우리금융지주"  # 예시
result_df = summarize_top_articles(cusA_news_df, ticker=ticker, query=query, top_k=3)

/Users/Work/SU/Project/streamlit/Streamlit/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[should_stop] Iteration: 1
[should_stop] Feedback:
 - 정확성: 좋음 <reason> 원문의 내용을 정확하게 반영하고 있음. </reason>
- 포괄성: 부족함 <reason> 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용이 누락되었음. </reason>
- 간결성: 좋음 <reason> 불필요한 표현 없이 요약 내용을 간결하게 전달하였음. </reason>
- 문장구성: 좋음 <reason> 문장이 자연스럽고 명확하게 구성되어 있음. </reason>

[피드백]
요약의 포괄성이 부족한 점이 아쉽습니다. 원문에서 언급된 '기술 경쟁력 확보, 고객사 확대, 수익구조 개선 등 실질적 사업성과로 뒷받침돼야 한다는 지적' 등의 중요한 내용을 요약에 포함시키면 더욱 완벽한 요약이 될 것 같습니다. 이 부분을 고려하여 요약을 수정해보시는 것을 추천드립니다.
✅ '정확성' 평가 통과
❌ '포괄성' 평가에서 좋음이 아님
[should_stop] next_step = no

KeyError: 'Input to PromptTemplate is missing variables {\'"foo"\', \'"properties"\'}.  Expected: [\'"foo"\', \'"properties"\', \'article\', \'feedback\', \'summary\'] Received: [\'article\', \'summary\', \'feedback\']\nNote: if you intended {"foo"} to be part of the string and not a variable, please escape it with double curly braces like: \'{{"foo"}}\'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT '

In [35]:
def summarize_top_articles(total_contents :str):

    agent = NewsSummaryAgent()
    runnable = build_summary_graph(agent)
    results = []
    
    doc = total_contents

    state = {
        "article": doc['content'],
        "summary": "",
        "feedback": "",
        "iteration": 0
    }
    result = runnable.invoke(state)


    print("✅ 실행 결과 타입:", type(result))
    print("✅ 실행 결과 키 목록:", result.keys())
    print("✅ 실행 결과 전체 내용:", result)

    if "final_summary" not in result:
        print("❌ final_summary 키가 없습니다.")

    print(f'실행 결과 : {result}')
    results.append({
        "ticker": doc['ticker'],
        "date": doc['Date'],
        "header": doc['title'],
        "url": doc['url'],
        "summary": result["final_summary"], 
            "feedback": result.get("last_feedback", "피드백 없음")
    })
    return pd.DataFrame(results)